/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojcollapsible"],function(b,f){(function(){b.ya("oj.ojAccordion",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{multiple:!1,expanded:null,beforeExpand:null,expand:null,beforeCollapse:null,collapse:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-accordion oj-component").attr("role","group");this.options.expanded=this.UU(this.options.expanded);this.Ld()},lf:function(a,b,c){this.nf(b,c,{launcher:this.element.find(".oj-collapsible-header-icon").first()})},
_destroy:function(){this.element.removeClass("oj-accordion oj-component").removeAttr("role");this.element.children().removeClass("oj-accordion-collapsible");this.element.children(".oj-accordion-created").removeClass("oj-accordion-created").ojCollapsible("destroy")},_setOption:function(a,b,c){if("multiple"===a)!1==b&&!0==this.options.multiple&&this.element.children(".oj-expanded").first().siblings(".oj-collapsible").ojCollapsible("collapse",!1);else if("expanded"===a){this.ika(b);return}this._super(a,
b,c)},refresh:function(){this._super();this.Ld()},Ld:function(){this.mha();this._setOption("disabled",this.options.disabled);this.JX=!0;this._setOption("expanded",this.options.expanded);this.JX=!1;this.xj()},mha:function(){this.element.children(":oj-collapsible").each(function(){f(this).ojCollapsible("option","expandArea","header")});this.Jk=this.element.children().not(":oj-ojCollapsible").ojCollapsible({expandArea:"header"}).addClass("oj-accordion-created").end().addClass("oj-accordion-collapsible")},
xj:function(){var a={keydown:this.wq,ojbeforeexpand:this.p$,ojexpand:this.dca,ojbeforecollapse:this.n$,ojcollapse:this.gaa};this._off(this.Jk);this._on(this.Jk,a)},wq:function(a){if(!a.altKey&&!a.ctrlKey&&(f(a.target).hasClass("oj-collapsible-header")||f(a.target).hasClass("oj-collapsible-header-icon"))){var b=f.ui.keyCode,c=this.Jk.not(".oj-disabled"),e=c.length,g=f(a.target).closest(".oj-collapsible"),h=c.index(g),k=!1;if(0<=h)switch(a.keyCode){case b.RIGHT:case b.DOWN:k=c[(h+1)%e];break;case b.LEFT:case b.UP:k=
c[(h-1+e)%e];break;case b.HOME:k=c[0];break;case b.END:k=c[e-1]}k&&(g&&f(g).trigger("ojfocusout"),f(k).trigger("ojfocus"),a.preventDefault())}},eV:function(a){return!this.options.multiple&&(a=f(a.target).closest(".oj-collapsible"),a.parent().is(":oj-ojAccordion"))?a.siblings(".oj-collapsible.oj-expanded").map(function(){return f(this).data("oj-ojCollapsible")}):f()},p$:function(a){if(!this.oC(a))return!0;var b,c=this,e;this.eV(a).each(function(){var g=this.element;e=c.qt(g,f(a.target));g={header:g.find(".oj-collapsible-header"),
content:g.find(".oj-collapsible-content")};return b=this._trigger("beforeCollapse",a,g)});e||(e=c.qt(null,f(a.target)));this.options.multiple||this._trigger("beforeExpand",a,e);return b},dca:function(a,b){if(this.oC(a)&&!this.hI){var c,e=this;this.eV(a).each(function(){this.collapse(!1,a,b);c=e.qt(this.element,f(a.target))});c||(c=e.qt(null,f(a.target)));this.options.multiple||this._trigger("expand",a,c);this.tM()}},n$:function(a,b){return this.oC(a)&&!this.options.multiple?this._trigger("beforeCollapse",
a,this.sX(a,b)):!0},gaa:function(a,b){if(!this.hI&&this.oC(a)){var c=this.sX(a,b);this.options.multiple||this._trigger("collapse",a,c);this.tM()}},qt:function(a,b){return{fromCollapsible:a,toCollapsible:b}},sX:function(a,b){var c;if(b.toCollapsible)c=b;else{if(a.originalEvent&&a.originalEvent.target){var e=f(a.originalEvent.target);e.hasClass("oj-collapsible")&&(c=this.qt(f(a.target),e))}c||(c=this.qt(f(a.target),null))}return c},oC:function(a){return f(a.target).is(this.Jk)},tM:function(){var a,
d=[];this.Jk.each(function(b){f(this).ojCollapsible("option","expanded")&&(a=f(this).attr("id"),d.push(a?a:b))});b.b.KT(this.options.expanded,d)||this.option("expanded",d,{_context:{Za:!0,Ec:!0}})},UU:function(a){if(Array.isArray(a)){var b,c=[];this.element.children().each(function(e){(b=f(this).attr("id"))?-1!=a.indexOf(b)?c.push(b):-1!=a.indexOf(e)&&c.push(b):-1!=a.indexOf(e)&&c.push(e)});!this.options.multiple&&1<c.length&&(c=[c[c.length-1]]);return c}return null},ika:function(a){this.JX||(a=this.UU(a));
if(a){var d=this,c,e,g,h=0;this.Jk.each(function(k){c=f(this);e=c.attr("id");g=!1;e?e==a[h]&&(g=!0):k==a[h]&&(g=!0);g&&h++;c.ojCollapsible("option","expanded")!==g&&(b.r.warn("JET Accordion: override collapsible "+k+" expanded setting"),d.hI=!0,c.ojCollapsible("option","expanded",g),d.hI=!1)})}this.tM()},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;a=a.index;if("number"!==typeof a||0>a||a>=this.Jk.length)return null;a=this.Jk[a];switch(b){case "oj-accordion-content":b=
"oj-collapsible-content";break;case "oj-accordion-header":b="oj-collapsible-header";break;case "oj-accordion-disclosure":case "oj-accordion-header-icon":b="oj-collapsible-disclosure";break;case "oj-accordion-collapsible":return a;default:return null}return f(a).ojCollapsible("getNodeBySubId",{subId:b})},getSubIdByNode:function(a){for(var b=-1,c=a;c;){b=Array.prototype.indexOf.call(this.Jk,c);if(-1!=b)break;c=c.parentElement}c=null;if(-1!=b)switch(a=(a=f(this.Jk[b]).ojCollapsible("getSubIdByNode",
a))?a:{},a.subId){case "oj-collapsible-content":c="oj-accordion-content";break;case "oj-collapsible-header":c="oj-accordion-header";break;case "oj-collapsible-disclosure":case "oj-collapsible-header-icon":c="oj-accordion-disclosure";break;default:c="oj-accordion-collapsible"}return c?{subId:c,index:b}:null}})})()});