/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojdatasource-common"],function(b,f,a){b.yb=function(a){this.data=a;this.current=0;this.Init();this.yL(10)};o_("ArrayPagingDataSource",b.yb,b);b.b.ga(b.yb,b.Pi,"oj.ArrayPagingDataSource");b.yb.prototype.Init=function(){b.yb.q.Init.call(this)};b.b.g("ArrayPagingDataSource.prototype.Init",{Init:b.yb.prototype.Init});b.yb.prototype.kJ=function(){return this.Lw()?this.dm:this.totalSize()-this.current};b.yb.prototype.Dq=function(a){a=a||{};this.Ef=Array(this.kJ());
for(var b=0;b<this.Ef.length;b++)this.Ef[b]=this.data[this.current+b];this.Ax();this.gj=this.$+this.Ef.length-1;a.silent||this.handleEvent("sync",{data:this.Ef,startIndex:this.current})};b.yb.prototype.Ax=function(){if(void 0!==this.Lj){this.Lj.removeAll();for(var a=0;a<this.Ef.length;a++)this.Lj.push(this.Ef[a])}};b.yb.prototype.handleEvent=function(a,c){return b.yb.q.handleEvent.call(this,a,c)};b.yb.prototype.nm=function(){return this.Ef};b.b.g("ArrayPagingDataSource.prototype.getWindow",{nm:b.yb.prototype.nm});
b.yb.prototype.zy=function(){void 0===this.Lj&&(this.Lj=a.observableArray(),this.Ax());return this.Lj};b.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{zy:b.yb.prototype.zy});b.yb.prototype.getPage=function(){return this.Kc};b.b.g("ArrayPagingDataSource.prototype.getPage",{getPage:b.yb.prototype.getPage});b.yb.prototype.setPage=function(a,c){c=c||{};a=parseInt(a,10);try{b.yb.q.handleEvent.call(this,b.$b.D.BEFOREPAGE,{page:a,previousPage:this.Kc})}catch(e){return Promise.reject(null)}this.pageSize=
null!=c.pageSize?c.pageSize:this.pageSize;c.startIndex=a*this.pageSize;var f=this.Kc;this.Kc=a;this.$=c.startIndex;var h=this;return new Promise(function(a,d){h.Ae(c).then(function(){b.yb.q.handleEvent.call(h,b.$b.D.PAGE,{page:h.Kc,previousPage:f});a(null)},function(){h.Kc=f;h.$=h.Kc*h.pageSize;d(null)})})};b.b.g("ArrayPagingDataSource.prototype.setPage",{setPage:b.yb.prototype.setPage});b.yb.prototype.getStartItemIndex=function(){return this.$};b.b.g("ArrayPagingDataSource.prototype.getStartItemIndex",
{getStartItemIndex:b.yb.prototype.getStartItemIndex});b.yb.prototype.getEndItemIndex=function(){return this.gj};b.b.g("ArrayPagingDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.yb.prototype.getEndItemIndex});b.yb.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.pageSize)};b.b.g("ArrayPagingDataSource.prototype.getPageCount",{getPageCount:b.yb.prototype.getPageCount});b.yb.prototype.fetch=function(a){a=a||{};if(void 0!==a.pageSize&&void 0!==a.startIndex){if(!this.Lw())return Promise.resolve();
this.dm=a.startIndex+a.pageSize}this.Dq(null);return Promise.resolve()};b.b.g("ArrayPagingDataSource.prototype.fetch",{fetch:b.yb.prototype.fetch});b.yb.prototype.Ae=function(a){var b=a||{};void 0!==b.startIndex&&(this.current=b.startIndex);void 0!==b.pageSize&&(this.dm=this.pageSize=b.pageSize);this.Dq(a);return Promise.resolve({data:this.Ef,startIndex:this.current})};b.yb.prototype.Lw=function(){return this.current+this.dm<this.totalSize()};b.yb.prototype.yL=function(a){this.dm=this.pageSize=a;
this.Dq(null)};b.yb.prototype.totalSize=function(){return this.data.length};b.yb.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("ArrayPagingDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.yb.prototype.totalSizeConfidence});b.yb.prototype.getCapability=function(){return null};b.b.g("ArrayPagingDataSource.prototype.getCapability",{getCapability:b.yb.prototype.getCapability})});