/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(b,f){(function(){b.ya("oj.ojCheckboxset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:!1,value:void 0},refresh:function(){this._super();this.Aa()},widget:function(){return this.Wpa},Ud:function(a,c){var e=[],g;this._super(a,c);b.re.Rk([{V:"disabled",vc:!0},{V:"title"},{V:"placeholder"},{V:"required",We:!0,vc:!0}],c,this);this.sh=this.pI();void 0===c.value&&
(g=this.sh.filter(":checked"),0<g.length&&(g.each(function(){e.push(f(this).val())}),this.option("value",e,{_context:{Ec:!0,Za:!0}})),void 0===this.options.value&&(this.options.value=[]))},_ComponentCreate:function(){this._super();if(this.element.is("fieldset"))throw Error("ojCheckboxset cannot be bound to a fieldset. Use a div instead.");this.sh._ojRadioCheckbox();this.Wpa=this.element.addClass("oj-checkboxset oj-component").attr("role","group").wrapInner("\x3cdiv class\x3d'oj-checkboxset-wrapper'\x3e\x3c/div\x3e");
this._on(this.Cl);this.Aa()},nG:function(){this.sh=this.pI();this.sh.filter(".oj-checkbox").each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.sh.not(".oj-checkbox")._ojRadioCheckbox()},Focus:function(){this.Td().first().focus();return!0},qG:function(){},pI:function(){var a=this.element.find("input[type\x3dcheckbox]:first");0===a.length&&b.r.warn("Could not find any input type\x3dcheckbox within this element");
a=a.attr("name");return void 0===a?(a=this.element.find("input[type\x3dcheckbox]"),a.not("[name]")):this.element.find("input[type\x3dcheckbox][name\x3d"+a+"]")},lf:function(a,b,e){a=this.element.find("input[type\x3dcheckbox]:tabbable").first();this.nf(b,e,{launcher:a})},_GetMessagingLauncherElement:function(){var a=this.Td(),c=b.we.Ok("radioset").renderInputAs;return c&&"html"!==c?this.widget():a},Aa:function(){this.ao(this.options.disabled)},Cl:{change:function(a){this.Hz(a)}},Hz:function(b){var c=
this.ag();this.ec(c,b,a)},ag:function(){return this.gs()},li:function(a){var b;this.sh._ojRadioCheckbox("option","checked",!1);if(null!=a)for(var e=0;e<a.length;e++)b=a[e],b="[value\x3d'"+b+"']",b=this.sh.filter(b),void 0!==b&&0<b.length&&(b.prop("checked")||b._ojRadioCheckbox("option","checked",!0))},gs:function(){var a=[],b=this.sh.filter(":checked");if(0===b.length)return[];b.each(function(){a.push(f(this).val())});return a},_GetDefaultStyleClass:function(){return"oj-checkboxset"},Td:function(){return this.pI()},
mG:function(){},uz:function(){return!0},ao:function(a){a=!!a;this.sh.each(function(){f(this).data("oj-_ojRadioCheckbox").Jv(a)});this.sh._ojRadioCheckbox("refreshDisabled")},_setOption:function(a,b,e){this._super(a,b,e);"disabled"===a&&this.ao(b)},getNodeBySubId:function(a){var b=this._super(a);return b||(a=a.subId,"oj-checkboxset-inputs"!==a)?b||null:this.sh.get()},_destroy:function(){var a=this._super(),b=this.element[0].firstChild;this.sh&&this.sh._ojRadioCheckbox("destroy");f(b).contents().unwrap();
return a}});var a={Yq:!1}})()});