/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b){b.Ic=function(f,a,d,c,e){b.l.ey(d);this.Yb=f;this.oe=a;this.oE=d;this.wg=c;this.P3=e};o_("CollectionHeaderSet",b.Ic,b);b.Ic.prototype.I4=function(f){b.l.FD(f);null!=f&&f.length===this.R()&&(this.or=f)};b.Ic.prototype.getData=function(f,a){var d;b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");if(null!=this.wg){if(null==this.or)return null;d=this.or[f-this.Yb];
return d.get(this.wg)}return this.oE[f]};b.b.g("CollectionHeaderSet.prototype.getData",{getData:b.Ic.prototype.getData});b.Ic.prototype.getMetadata=function(f,a){var d;b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");if(null!=this.wg){if(null==this.or)return null;d=this.or[f-this.Yb];return{key:b.cp.dt(d)}}d=this.getData(f,a);return this.P3.key===d?{key:d,sortDirection:this.P3.direction}:{key:d}};b.b.g("CollectionHeaderSet.prototype.getMetadata",
{getMetadata:b.Ic.prototype.getMetadata});b.Ic.prototype.pg=function(){return 0<this.R()?1:0};b.b.g("CollectionHeaderSet.prototype.getLevelCount",{pg:b.Ic.prototype.pg});b.Ic.prototype.Rb=function(f,a){b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};b.b.g("CollectionHeaderSet.prototype.getExtent",{Rb:b.Ic.prototype.Rb});b.Ic.prototype.ie=function(f,a){b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");
b.l.assert(null==a||0==a,"level out of bounds");return 1};b.b.g("CollectionHeaderSet.prototype.getDepth",{ie:b.Ic.prototype.ie});b.Ic.prototype.R=function(){return Math.max(0,this.oe-this.Yb)};b.b.g("CollectionHeaderSet.prototype.getCount",{R:b.Ic.prototype.R});b.Ic.prototype.ta=function(){return this.Yb};b.b.g("CollectionHeaderSet.prototype.getStart",{ta:b.Ic.prototype.ta});b.Ic.prototype.q2=function(){return this.oe};b.b.g("CollectionHeaderSet.prototype.getEnd",{q2:b.Ic.prototype.q2});b.Ic.prototype.y2=
function(){return this.oE};b.b.g("CollectionHeaderSet.prototype.getHeaders",{y2:b.Ic.prototype.y2});b.Ic.prototype.uy=function(){return this.wg};b.b.g("CollectionHeaderSet.prototype.getRowHeader",{uy:b.Ic.prototype.uy});b.Dd=function(f,a,d,c,e){b.l.ey(e);this.Ji=f;this.lr=a;this.Xk=d;this.kr=c;this.Pd=e};o_("CollectionCellSet",b.Dd,b);b.Dd.prototype.I4=function(f){b.l.FD(f);null!=f&&f.length===this.R("row")&&(this.or=f)};b.Dd.prototype.getData=function(b){var a;a=this.Mb(b);return null==a?null:a.get(this.Pd[b.column])};
b.b.g("CollectionCellSet.prototype.getData",{getData:b.Dd.prototype.getData});b.Dd.prototype.getMetadata=function(f){var a;a=this.Mb(f);return null==a?null:{keys:{row:b.cp.dt(a),column:this.Pd[f.column]}}};b.b.g("CollectionCellSet.prototype.getMetadata",{getMetadata:b.Dd.prototype.getMetadata});b.Dd.prototype.Mb=function(f){var a;if(null==this.or)return null;b.l.Df(f);a=f.row;f=f.column;b.l.assert(a>=this.Ji&&a<=this.lr&&f>=this.Xk&&f<=this.kr);return this.or[a-this.Ji]};b.Dd.prototype.R=function(b){return"row"===
b?Math.max(0,this.lr-this.Ji):"column"===b?Math.max(0,this.kr-this.Xk):0};b.b.g("CollectionCellSet.prototype.getCount",{R:b.Dd.prototype.R});b.Dd.prototype.getStartRow=function(){return this.Ji};b.b.g("CollectionCellSet.prototype.getStartRow",{getStartRow:b.Dd.prototype.getStartRow});b.Dd.prototype.s2=function(){return this.lr};b.b.g("CollectionCellSet.prototype.getEndRow",{s2:b.Dd.prototype.s2});b.Dd.prototype.getStartColumn=function(){return this.Xk};b.b.g("CollectionCellSet.prototype.getStartColumn",
{getStartColumn:b.Dd.prototype.getStartColumn});b.Dd.prototype.r2=function(){return this.kr};b.b.g("CollectionCellSet.prototype.getEndColumn",{r2:b.Dd.prototype.r2});b.Dd.prototype.Co=function(){return this.Pd};b.b.g("CollectionCellSet.prototype.getColumns",{Co:b.Dd.prototype.Co});b.cp=function(){};b.cp.dt=function(b){var a;a=b.Vf();null==a&&(a=b.gp());return a};b.wa=function(f,a){this.Ba=f;null!=a&&(this.Yy=a.rowHeader,this.columns=a.columns);this.O_();b.wa.q.constructor.call(this)};o_("CollectionDataGridDataSource",
b.wa,b);b.b.ga(b.wa,b.Om,"oj.CollectionDataGridDataSource");b.wa.prototype.Init=function(){b.wa.q.Init.call(this);this.zm={};this.$K()};b.b.g("CollectionDataGridDataSource.prototype.Init",{Init:b.wa.prototype.Init});b.wa.prototype.$K=function(){this.Ba.on("add",this.dfa.bind(this));this.Ba.on("remove",this.ffa.bind(this));this.Ba.on("change",this.efa.bind(this));this.Ba.on("refresh",this.wea.bind(this));this.Ba.on("reset",this.xea.bind(this))};b.wa.prototype.yga=function(){return null!=this.data};
b.wa.prototype.R=function(b){var a;void 0==this.precision&&(this.precision={});if("row"==b){a=this.ge();if(-1===a||0===a&&(!this.yga()||0<this.ho()))return this.precision[b]="estimate",-1;this.precision[b]="exact";return this.ho()}if("column"==b){if(null!=this.columns)return this.precision[b]="exact",this.columns.length;this.precision[b]="estimate";return-1}return 0};b.b.g("CollectionDataGridDataSource.prototype.getCount",{R:b.wa.prototype.R});b.wa.prototype.og=function(b){null!=this.precision&&null!=
this.precision[b]||this.R(b);return this.precision[b]};b.b.g("CollectionDataGridDataSource.prototype.getCountPrecision",{og:b.wa.prototype.og});b.wa.prototype.Gf=function(b,a,d){var c,e;null!=a&&(c=b.axis,e={},e.h3=b,e.callbacks=a,e.fy=d,this.zm[c]=e)};b.b.g("CollectionDataGridDataSource.prototype.fetchHeaders",{Gf:b.wa.prototype.Gf});b.wa.prototype.Sea=function(f,a,d,c){var e,g,h,k;e=f.axis;g=f.start;h=f.count;if("column"===e)null!=this.columns?(c=Math.min(this.columns.length,g+h),k=new b.Ic(g,c,
this.columns,void 0,this.Ai)):k=new b.Cd(g,g,e,null);else if("row"===e){if(null!=this.Yy){null!=c&&(h=c.count);c=Math.min(this.ho(),g+h);k=new b.Ic(g,c,this.columns,this.Yy);this.e_(g,c,k,f,a,d);return}k=new b.Cd(g,g,e,null)}null!=a&&a.success&&a.success.call(d.success,k,f)};b.wa.prototype.lW=function(b){var a,d,c,e,g,h;for(a=0;a<b.length;a+=1)d=b[a],"row"===d.axis?(c=d.start,e=d.count):"column"===d.axis&&(g=d.start,h=d.count);return{rowStart:c,rowCount:e,colStart:g,colCount:h}};b.wa.prototype.oea=
function(f,a,d,c){var e,g,h;e=this.lW(f);g=e.rowStart;c=null!=c?Math.min(this.ho(),g+c.count):Math.min(this.ho(),g+e.rowCount);h=e.colStart;e=Math.min(null==this.columns?0:this.columns.length,h+e.colCount);e=new b.Dd(g,c,h,e,this.columns);this.e_(g,c,e,f,a,d)};b.wa.prototype.e_=function(b,a,d,c,e,g){var h;for(h=[];b<a;b++)h.push(this.Ba.at(b,{deferred:!0}));Promise.all(h).then(function(a){d.I4(a);e.success.call(g.success,d,c)})};b.wa.prototype.ng=function(b,a,d){null!=a&&(this.yg={},this.yg.p1=b,
this.yg.callbacks=a,this.yg.fy=d);this.fca(b)};b.b.g("CollectionDataGridDataSource.prototype.fetchCells",{ng:b.wa.prototype.ng});b.wa.prototype.fZ=function(b){var a,d,c,e,g;a=this.zm[b];null!=a&&(d=a.h3,c=a.callbacks,e=a.fy,"row"===b&&(g=a.zM),this.Sea(d,c,e,g),this.zm[b]=null)};b.wa.prototype.wia=function(){this.oea(this.yg.p1,this.yg.callbacks,this.yg.fy,this.yg.zM)};b.wa.prototype.fca=function(b){var a;b=this.lW(b);a=b.rowStart;this.Ba.Zy(a,b.rowCount).then(function(b){this.data=!0;this.$ja(b.start,
b.count);void 0===this.columns?this.Ba.at(a,{deferred:!0}).then(function(a){null!=a&&this.CL(a);this.ZU()}.bind(this)):this.ZU()}.bind(this),function(a){this.gca(a)}.bind(this))};b.wa.prototype.gca=function(f){b.r.error(f);null!=this.zm&&(this.gZ("column",f),this.gZ("row",f));null!=this.yg&&this.xia(f)};b.wa.prototype.gZ=function(b,a){var d,c,e;d=this.zm[b];null!=d&&(c=d.callbacks,e=d.fy,d=d.h3,c.error&&c.error.call(e.error,a,d),this.zm[b]=null)};b.wa.prototype.xia=function(b){var a,d,c;a=this.yg.callbacks;
d=this.yg.fy;c=this.yg.p1;a.error&&a.error.call(d.error,b,c);this.yg=null};b.wa.prototype.ZU=function(){null!=this.zm&&(this.fZ("column"),this.fZ("row"));null!=this.yg&&this.wia()};b.wa.prototype.$ja=function(b,a){var d={start:b,count:a};null!=this.zm.row&&(this.zm.row.zM=d);null!=this.yg&&(this.yg.zM=d)};b.wa.prototype.CL=function(b){this.columns=b.keys();-1!=this.columns.indexOf(this.Yy)&&this.columns.splice(this.columns.indexOf(this.Yy),1)};b.wa.prototype.keys=function(f){var a,d,c,e,g;a=f.row;
d=f.column;g=this;return new Promise(function(f){g.Ba.at(a,{deferred:!0}).then(function(a){null==a?f({row:null,column:null}):(c=b.cp.dt(a),null==g.columns&&g.CL(a),e=g.columns[d],f({row:c,column:e}))}.bind(g))})};b.b.g("CollectionDataGridDataSource.prototype.keys",{keys:b.wa.prototype.keys});b.wa.prototype.tg=function(b){var a,d,c,e;a=b.row;d=b.column;e=this;return new Promise(function(b){e.Ba.indexOf(a,{deferred:!0}).then(function(a){-1===a?b({row:-1,column:-1}):null==e.columns?e.Ba.at(a,{deferred:!0}).then(function(f){e.CL(f);
c=e.columns.indexOf(d);-1===c&&(a=-1);b({row:a,column:c})}.bind(e)):(c=e.columns.indexOf(d),-1===c&&(a=-1),b({row:a,column:c}))}.bind(e))})};b.b.g("CollectionDataGridDataSource.prototype.indexes",{tg:b.wa.prototype.tg});b.wa.prototype.getCapability=function(b){return"sort"===b?"column":"move"===b?"row":null};b.b.g("CollectionDataGridDataSource.prototype.getCapability",{getCapability:b.wa.prototype.getCapability});b.wa.prototype.sort=function(b,a,d){var c,e,g;null==d&&(d={});null==b?this.mL(a,d):(e=
b.direction,g=b.key,b=b.axis,"column"===b?(this.Ba.Wa()?(this.Ba.comparator=g,this.Ba.sortDirection="ascending"===e?1:-1):("ascending"===e&&(c=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===e&&(c=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());
return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.Ba.comparator=c),this.Ba.sort(),this.O_(g),null!=a&&null!=a.success&&a.success.call(d.success)):null!=a&&null!=a.error&&a.error.call(d.error,"Axis value not supported"))};b.b.g("CollectionDataGridDataSource.prototype.sort",{sort:b.wa.prototype.sort});b.wa.prototype.mL=function(b,a){this.Ba.comparator=null;this.Ba.reset();null!=b&&null!=b.success&&b.success.call(a.success)};b.wa.prototype.O_=function(b){var a,d;a=this.Ba.comparator;d=-1===this.Ba.sortDirection?
"descending":"ascending";null==b&&"function"===typeof a?this.Ai={}:(this.Ai={},this.Ai.axis="column",this.Ai.direction=d,this.Ai.key=null==b?a:null)};b.wa.prototype.move=function(b,a,d,c,e){var g;this.Ba.get(b,{deferred:!0}).then(function(d){null==a?(this.Ba.remove(d),this.Ba.add(d),null!=c&&null!=c.success&&c.success.call(e.success)):(b===a?(g=this.Ba.indexOf(a,{deferred:!0}),this.Ba.remove(d)):(this.Ba.remove(d),g=this.Ba.indexOf(a,{deferred:!0})),g.then(function(a){this.Ba.add(d,{at:a,xra:!0});
null!=c&&null!=c.success&&c.success.call(e.success)}.bind(this)))}.bind(this))};b.b.g("CollectionDataGridDataSource.prototype.move",{move:b.wa.prototype.move});b.wa.prototype.md=function(){return"valid"};b.b.g("CollectionDataGridDataSource.prototype.moveOK",{md:b.wa.prototype.md});b.wa.prototype.nk=function(b,a,d,c,e){var g={source:this};g.operation=b;g.keys={row:a,column:d};g.indexes={row:c,column:e};return g};b.wa.prototype.dfa=function(f){var a,d;this.Ba.indexOf(f,{deferred:!0}).then(function(c){d=
b.cp.dt(f);a=this.nk("insert",d,null,c,-1);this.handleEvent("change",a)}.bind(this))};b.wa.prototype.ffa=function(f,a,d){this.handleEvent("change",this.nk("delete",b.cp.dt(f),null,d.index,-1))};b.wa.prototype.efa=function(f){var a,d;this.Ba.indexOf(f,{deferred:!0}).then(function(c){d=b.cp.dt(f);a=this.nk("update",d,null,c,-1);this.handleEvent("change",a)}.bind(this))};b.wa.prototype.wea=function(){this.data=null;this.handleEvent("change",this.nk("refresh",null,null))};b.wa.prototype.xea=function(){this.data=
null;this.handleEvent("change",this.nk("reset",null,null))};b.wa.prototype.ho=function(){return this.Ba.size()};b.wa.prototype.ge=function(){return void 0===this.Ba.totalResults?-1:this.Ba.totalResults};b.wa.prototype.l2=function(){return this.Ba};b.b.g("CollectionDataGridDataSource.prototype.getCollection",{l2:b.wa.prototype.l2});b.wa.prototype.Co=function(){return this.columns};b.b.g("CollectionDataGridDataSource.prototype.getColumns",{Co:b.wa.prototype.Co});b.wa.prototype.uy=function(){return this.Yy};
b.b.g("CollectionDataGridDataSource.prototype.getRowHeader",{uy:b.wa.prototype.uy});b.wa.prototype.getData=function(){return this.data};b.b.g("CollectionDataGridDataSource.prototype.getData",{getData:b.wa.prototype.getData})});