/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b,f){b.wc=function(a,d){this.data={};if(!(a instanceof b.j))throw Error(b.T.dc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.dc._ERR_DATA_INVALID_TYPE_DETAIL);b.wc.q.constructor.call(this,a,d);this.Ub=a;this.s9();this.Init();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d)this.Mx=!0};o_("CollectionTableDataSource",b.wc,b);b.b.ga(b.wc,b.T,"oj.CollectionTableDataSource");b.wc.prototype.Init=function(){b.wc.q.Init.call(this)};
b.b.g("CollectionTableDataSource.prototype.Init",{Init:b.wc.prototype.Init});b.wc.prototype.at=function(a,d){d=d||{};d.deferred=!0;var c=this.Ub.at(a,d),e=this;e.Tw=!0;var f;return new Promise(function(d,k){null!=c?c.then(function(b){e.Tw=!1;f={data:b.attributes,index:a,key:b.id};d(f)},function(a){e.Tw=!1;b.T.q.handleEvent.call(e,b.T.D.ERROR,a);k(a)}):d(null)})};b.b.g("CollectionTableDataSource.prototype.at",{at:b.wc.prototype.at});b.wc.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||
this.Mx?this.Ae(a):Promise.resolve()};b.b.g("CollectionTableDataSource.prototype.fetch",{fetch:b.wc.prototype.fetch});b.wc.prototype.get=function(a,d){d=d||{};d.deferred=!0;var c=this.Ub.get(a,d),e=this,f;return new Promise(function(a,d){null!=c?c.then(function(b){f={data:b.attributes,index:b.index,key:b.id};a(f)},function(a){b.T.q.handleEvent.call(e,b.T.D.ERROR,a);d(a)}):a(null)})};b.b.g("CollectionTableDataSource.prototype.get",{get:b.wc.prototype.get});b.wc.prototype.sort=function(a){if(null==
a)return Promise.resolve();var b=this;return new Promise(function(c){b.cka(a);b.Ub.sort(null);c({header:a.key,direction:a.direction})})};b.b.g("CollectionTableDataSource.prototype.sort",{sort:b.wc.prototype.sort});b.wc.prototype.totalSize=function(){var a=0<=this.Ub.totalResults?this.Ub.totalResults:-1;if(-1<a){var b=this.Ub.size();return b>a?b:a}if(0<this.oI)a=this.oI;else if("atLeast"==this.totalSizeConfidence())return this.Ub.size();return a};b.b.g("CollectionTableDataSource.prototype.totalSize",
{totalSize:b.wc.prototype.totalSize});b.wc.prototype.totalSizeConfidence=function(){return 0<=this.Ub.totalResults?"actual":this.Ub.hasMore?"atLeast":"unknown"};b.b.g("CollectionTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.wc.prototype.totalSizeConfidence});b.wc.prototype.s9=function(){var a=this;this.Ub.on(b.Y.D.SYNC,function(d){if(d instanceof b.j&&!a.Tw&&!a.NX){var c=d.offset,e=d.lastFetchCount;0<e?(a.$=c,a.La=e,a.Tw=!0,d.Nr(c,c+e).then(function(b){a.Tw=!1;var d=[],e=[],
f;for(f=0;f<b.length;f++)null!=b[f]&&(d.push(b[f].attributes),e.push(b[f].id));a.Rg.call(a,{silent:!1},{data:d,keys:e,startIndex:c},null)})):(d=a.iq(),a.Rg.call(a,{silent:!1},d,null))}});this.Ub.on(b.Y.D.ALLADDED,function(d,c){var e=[],f=[],h=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),f.push(c[k].id),h.push(c[k].index);b.T.q.handleEvent.call(a,b.T.D.ADD,{data:e,keys:f,indexes:h})});this.Ub.on(b.Y.D.ALLREMOVED,function(d,c){var e=[],f=[],h=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),
f.push(c[k].id),h.push(c[k].index);b.T.q.handleEvent.call(a,b.T.D.REMOVE,{data:e,keys:f,indexes:h})});this.Ub.on(b.Y.D.RESET,function(d){b.T.q.handleEvent.call(a,b.T.D.RESET,d)});this.Ub.on(b.Y.D.SORT,function(d,c){null!=c&&c.add||b.T.q.handleEvent.call(a,b.T.D.SORT,d)});this.Ub.on(b.Y.D.CHANGE,function(d){b.T.q.handleEvent.call(a,b.T.D.CHANGE,{data:[d.attributes],keys:[d.id],indexes:[d.index]})});this.Ub.on(b.Y.D.DESTROY,function(d){b.T.q.handleEvent.call(a,b.T.D.DESTROY,d)});this.Ub.on(b.Y.D.REFRESH,
function(d){b.T.q.handleEvent.call(a,b.T.D.REFRESH,d)});this.Ub.on(b.Y.D.ERROR,function(d,c,e){b.T.q.handleEvent.call(a,b.T.D.ERROR,d,c,e)})};b.wc.prototype.Ae=function(a){this.Lx(a);a=a||{};var b=this;this.Kga=0<a.pageSize?!0:!1;this.$=null==a.startIndex?this.$:a.startIndex;this.dC=!0;this.La=0<a.pageSize?a.pageSize:-1;a.pageSize=this.La;a.startIndex=this.$;a.refresh=!0;return new Promise(function(c,e){if(b.Kga)b.Ub.Zy(b.$,b.La).then(function(e){var f=[],g=[],m;for(m=0;m<e.models.length;m++)f[m]=
e.models[m].attributes,g[m]=e.models[m].id;f={data:f,keys:g,startIndex:b.$};e.models.length<b.La?0>b.totalSize()&&(b.oI=b.$+e.models.length):b.oI=null;b.Rg.call(b,a,f,null);c(f)},function(c){b.Rg.call(b,a,null,c);e(c)});else if(0<b.Ub.size()){var f=b.iq();b.Rg.call(b,a,f,null);c(f)}else b.Ub.fetch({success:function(e){b.Ub=e;e=b.iq();b.Rg.call(b,a,e,null);c(e)},error:function(c,f){b.Ub=c;b.Rg.call(b,a,null,f);e(f)}})})};b.wc.prototype.Lx=function(a){this.NX=!0;a.silent||b.T.q.handleEvent.call(this,
b.T.D.REQUEST,{startIndex:a.startIndex})};b.wc.prototype.Rg=function(a,d,c){this.NX=!1;null!=c?b.T.q.handleEvent.call(this,b.T.D.ERROR,c):a.silent||b.T.q.handleEvent.call(this,b.T.D.SYNC,d)};b.wc.prototype.cka=function(a){if(null==a)this.Ub.comparator=null;else{var b=a.key;a=a.direction;var c=null;this.Ub.Wa()?(this.Ub.comparator=b,this.Ub.sortDirection="ascending"===a?1:-1):("ascending"==a?c=function(a){return f.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(c=function(a,c){var h,k;f.isFunction(a.get)?
(h=a.get(b),k=c.get(b)):(h=a[b](),k=c[b]());return h===k?0:h>k?-1:1}),this.Ub.comparator=c)}};b.wc.prototype.iq=function(){var a=this.Ub.size()-1,b=[],c=[],e;for(e=0;e<=a;e++)b[e]=this.Ub.at(e).attributes,c[e]=this.Ub.at(e).id;return{data:b,keys:c,startIndex:this.$}};b.wc.prototype.getCapability=function(){return null};b.b.g("CollectionTableDataSource.prototype.getCapability",{getCapability:b.wc.prototype.getCapability})});