/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","knockout","ojs/ojdatasource-common","ojs/ojmodel","ojs/ojknockout-model"],function(b,f,a){b.nb=function(a){this.Ba=a;this.current=0;this.Init();this.Ef=[];this.yL(10)};o_("CollectionPagingDataSource",b.nb,b);b.b.ga(b.nb,b.Pi,"oj.CollectionPagingDataSource");b.nb.prototype.Init=function(){b.nb.q.Init.call(this)};b.b.g("CollectionPagingDataSource.prototype.Init",{Init:b.nb.prototype.Init});b.nb.prototype.kJ=function(){return this.Lw()?this.dm:this.totalSize()-this.current};
b.nb.prototype.Dq=function(){this.Ef=Array(this.kJ());var a=this;return this.Ba.Nr(this.current,this.current+this.Ef.length).then(function(b){for(var e=0;e<b.length;e++)a.Ef[e]=b[e];a.Ax();a.gj=a.$+a.Ef.length-1})};b.nb.prototype.Ax=function(){if(void 0!==this.Lj){this.Lj.removeAll();for(var a=0;a<this.Ef.length;a++)this.Lj.push(b.Ha.map(this.Ef[a]))}};b.nb.prototype.nm=function(){return this.Ef};b.b.g("CollectionPagingDataSource.prototype.getWindow",{nm:b.nb.prototype.nm});b.nb.prototype.zy=function(){void 0===
this.Lj&&(this.Lj=a.observableArray(),this.Ax());return this.Lj};b.b.g("CollectionPagingDataSource.prototype.getWindowObservable",{zy:b.nb.prototype.zy});b.nb.prototype.getPage=function(){return this.Kc};b.b.g("CollectionPagingDataSource.prototype.getPage",{getPage:b.nb.prototype.getPage});b.nb.prototype.setPage=function(a,c){c=c||{};a=parseInt(a,10);try{b.nb.q.handleEvent.call(this,b.$b.D.BEFOREPAGE,{page:a,previousPage:this.Kc})}catch(e){return Promise.reject(null)}this.pageSize=null!=c.pageSize?
c.pageSize:this.pageSize;c.startIndex=a*this.pageSize;var f=this.Kc;this.Kc=a;this.$=c.startIndex;var h=this;return new Promise(function(a,d){h.Ae(c).then(function(){b.nb.q.handleEvent.call(h,b.$b.D.PAGE,{page:h.Kc,previousPage:f});a(null)},function(){h.Kc=f;h.$=h.Kc*h.pageSize;d(null)})})};b.b.g("CollectionPagingDataSource.prototype.setPage",{setPage:b.nb.prototype.setPage});b.nb.prototype.getStartItemIndex=function(){return this.$};b.b.g("CollectionPagingDataSource.prototype.getStartItemIndex",
{getStartItemIndex:b.nb.prototype.getStartItemIndex});b.nb.prototype.getEndItemIndex=function(){return this.gj};b.b.g("CollectionPagingDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.nb.prototype.getEndItemIndex});b.nb.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.pageSize)};b.b.g("CollectionPagingDataSource.prototype.getPageCount",{getPageCount:b.nb.prototype.getPageCount});b.nb.prototype.fetch=function(a){var b=a||{};if(void 0!==b.pageSize&&void 0!==
b.startIndex){if(!this.Lw())return this.DC(null),Promise.resolve();this.dm=b.startIndex+b.pageSize;var e=this;return this.Dq().then(function(){e.DC(null)})}return this.Ae(a)};b.b.g("CollectionPagingDataSource.prototype.fetch",{fetch:b.nb.prototype.fetch});b.nb.prototype.Ae=function(a){var b=a||{};void 0!==b.startIndex&&(this.current=b.startIndex);void 0!==b.pageSize&&(this.dm=this.pageSize=b.pageSize);var e=this;return new Promise(function(a){try{e.Ba.fetch({success:function(){e.Dq().then(function(){e.DC(b);
a({data:e.nm(),startIndex:e.current})})}})}catch(d){e.Dq().then(function(){e.DC(b);a({data:e.nm(),startIndex:e.current})})}})};b.nb.prototype.DC=function(a){a=a||{};a.silent||this.handleEvent("sync",{data:this.nm(),startIndex:this.current});a.success&&a.success()};b.nb.prototype.handleEvent=function(a,c){return b.nb.q.handleEvent.call(this,a,c)};b.nb.prototype.Lw=function(){return this.current+this.dm<this.totalSize()};b.nb.prototype.yL=function(a){this.dm=this.pageSize=a};b.nb.prototype.size=function(){var a=
this.nm();return a?a.length:0};b.b.g("CollectionPagingDataSource.prototype.size",{size:b.nb.prototype.size});b.nb.prototype.totalSize=function(){return this.Ba.length};b.b.g("CollectionPagingDataSource.prototype.totalSize",{totalSize:b.nb.prototype.totalSize});b.nb.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("CollectionPagingDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.nb.prototype.totalSizeConfidence});b.nb.prototype.getCapability=function(){return null};b.b.g("CollectionPagingDataSource.prototype.getCapability",
{getCapability:b.nb.prototype.getCapability})});