/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,f){function a(a,b,e,f,h,k){this.pc=a;this.Vha=b;this.Is=e;this.xA=f;h&&(h.apa&&(this.oia=h.apa),h.Roa&&(this.Nha=h.Roa),h.o4&&(this.pia=h.o4),h.b4&&(this.Oha=h.b4),h.n4&&(this.nia=h.n4),h.a4&&(this.Mha=h.a4));k&&(k.B4&&(this.k_=k.B4),k.una&&(this.xI=k.una),k.Ama&&(this.Lp=k.Ama),k.eh&&(this.qA=k.eh),k.Qh&&(this.KC=k.Qh));this.vA=!0;this.Xs=0;a=navigator.userAgent.toLowerCase();if(-1!==a.indexOf("gecko/"))this.j$=!0;else if(-1!==a.indexOf("opera"))this.k$=
!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.l$=!0}a.prototype.Fm=function(b){var c=this;if(b){this.Faa();this.Waa(this.oia,this.pia,this.nia);this.Iaa(this.Nha,this.Oha,this.Mha);var e=this.qj,f=this.eD;f?(this.AA=f.offsetWidth,this.zA=e.offsetHeight):(f=this.zD,this.AA=e.offsetWidth,this.zA=f.offsetHeight);this.ZB();this.YB();this.ex=function(a){c.lfa(a)};a.qf(this.pc,"mousewheel",this.ex);a.qf(this.pc,"wheel",this.ex);this.YL=function(a){c.QJ(a)};a.qf(this.be,"touchstart",
this.YL);this.VL=function(a){c.PJ(a)};a.qf(this.be,"touchmove",this.VL);this.Tx=function(a){c.NJ(a)};a.qf(this.be,"touchend",this.Tx);a.qf(this.be,"touchcancel",this.Tx);this.EK=0}else this.GZ();this.xH();this.GS(b);this.Se(!0);b&&this.qA&&(this.Wg=function(){c.Se(!1)},this.qA.call(this.Lp,this.pc,this.Wg),this.qA.call(this.Lp,this.zn,this.Wg))};a.prototype.destroy=function(){var b=this.pc;a.ee(b,"mousewheel",this.ex);a.ee(b,"wheel",this.ex);a.ee(this.be,"touchstart",this.YL);a.ee(this.be,"touchmove",
this.VL);a.ee(this.be,"touchend",this.Tx);a.ee(this.be,"touchcancel",this.Tx);this.Tx=this.VL=this.YL=this.ex=null;this.KC&&this.Wg&&(this.KC.call(this.Lp,b,this.Wg),this.KC.call(this.Lp,this.zn,this.Wg));this.Wg=null;a.Eja(this.CH,b);this.PS=null;this.NL?b.removeChild(this.NL):(b.removeChild(this.be),b.removeChild(this.zD),b.removeChild(this.xM));this.zD=this.xM=this.yK=this.OK=this.eD=this.ML=this.NL=this.CH=this.be=this.zn=this.yk=this.qj=null;this.xH();this.Is=this.Lp=this.KC=this.qA=this.xI=
this.k_=this.pc=null};a.Fja=function(b,c,e){var f=null;e&&(f=a.NH(),c.appendChild(f));var h=null;for(b=b.childNodes;0<b.length;){h||(h=[]);var k=b[0];if(1===k.nodeType){e||(f=a.NH(),c.appendChild(f));var l=a.PA();l.appendChild(k);f.appendChild(l);h.push(k)}else e?f.appendChild(k):c.appendChild(k)}return h};a.Eja=function(a,b){if(a)for(var e=a.childNodes;0<e.length;){var f=e[0];if(1===f.nodeType){for(var h=f.childNodes;0<h.length;){var k=h[0];1===k.nodeType?(b.appendChild(k.firstChild),f.removeChild(k)):
b.appendChild(k)}a.removeChild(f)}else b.appendChild(f)}};a.qw=function(a){var b=a.ownerDocument.defaultView,e=null;return e=b?b.getComputedStyle(a,null):a.currentStyle};a.Yca=function(b){b=a.qw(b);return a.gg(b.width)};a.Xca=function(b){b=a.qw(b);return a.gg(b.height)};a.gg=function(a){return 0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};a.qf=function(a,b,e){a.addEventListener?a.addEventListener(b,e,!1):a.attachEvent&&a.attachEvent("on"+b,e)};a.ee=function(a,b,e){a.removeEventListener?
a.removeEventListener(b,e,!1):a.detachEvent&&a.detachEvent("on"+b,e)};a.fea=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};a.dU=function(){var a=document.createElement("div");a.style.display="table";return a};a.NH=function(){var a=document.createElement("div");a.style.display="table-row";return a};a.PA=function(){var a=document.createElement("div");a.style.display="table-cell";return a};a.Y0=function(a,b,e,f){var h=document.createElement("div"),k=
h.style;k.display="inline-block";h.appendChild(a);b.appendChild(h);e&&(k.maxWidth=h.offsetWidth+"px");f&&(k.maxHeight=h.offsetHeight+"px");return h};a.prototype.Hb=function(){return"horizontal"===this.Vha};a.prototype.Bga=function(){return!this.zV().hasChildNodes()};a.prototype.GZ=function(){this.EK=this.Sg();this.BT();this.xL(0);this.ZB();this.YB()};a.prototype.xH=function(){this.$C=this.ge=null};a.prototype.Se=function(a){a||this.GZ();this.xH();this.ge&&this.$C||(this.ge=this.yY());a||this.GS(!1);
a=this.ge;this.Q9(a.Of,a.lh)};a.prototype.Q9=function(a,b){var e=this.qj.style,f=this.yk.style;if(this.Hb()){var h=.5*(b-this.zA);e.top=h+"px";f.top=h+"px"}else h=.5*(a-this.AA),this.xA?(e.left=-h+"px",f.left=-h+"px"):(e.left=h+"px",f.left=h+"px")};a.prototype.GS=function(b){var c=this.zn,e=this.Hb(),f=e?a.Yca(this.pc):a.Xca(this.pc);(e?c.offsetWidth:c.offsetHeight)>f&&this.G_(f);this.cx=0;this.ax=e?c.offsetWidth-f+this.AA:c.offsetHeight-f+this.zA;0>this.ax&&(this.ax=0);this.ZB();this.YB();this.Qt(b?
this.cx:this.EK,!0);this.EK=0};a.prototype.Faa=function(){var b=this,c=this.Hb(),e=document.createElement("div");this.be=e;var f=e.style;f.overflow="hidden";f.display=this.rw();f.position="relative";c&&(f.verticalAlign="top");var h=this.pc,k=document.createElement("div");this.zn=k;var l=k.style;l.position="relative";c&&(l.display="inline-block");e.appendChild(k);l=null;if(c){this.NL=l=a.dU();var m=a.NH(),n=a.PA();this.ML=n;var p=a.PA(),r=a.PA();this.eD=r;var s=r.style;n.style.verticalAlign="top";
s.verticalAlign="top";p.appendChild(e);m.appendChild(n);m.appendChild(p);m.appendChild(r);l.appendChild(m)}m=a.dU();n=a.Fja(h,m,c);if(this.Is)for(n=[],p=this.Is.children,r=p.length,s=0;s<r;s++){var q=p[s];1===q.nodeType&&n.push(q)}(this.PS=n)&&0<n.length&&(this.CH=m,k.appendChild(m));l?h.appendChild(l):(this.xM=l=document.createElement("div"),this.zD=m=document.createElement("div"),h.appendChild(l),h.appendChild(e),h.appendChild(m));c&&(c=e.offsetHeight,k=k.offsetHeight,c>k&&(f.marginBottom=k-c+"px"));
a.qf(e,"scroll",function(){b.tfa()})};a.prototype.rw=function(){return this.Hb()?"inline-block":"block"};a.prototype.Waa=function(b,c,e){var f=this,h=document.createElement("div");this.yk=h;b&&h.setAttribute("id",b);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");b=h.style;b.display=this.rw();b.position="relative";if(c=this.Hb())b.verticalAlign="top";a.qf(h,"click",function(){f.m_()});this.ML?this.OK=a.Y0(h,this.ML,c,!c):this.xM.appendChild(h);e&&h.appendChild(e)};a.prototype.Iaa=function(b,
c,e){var f=this,h=document.createElement("div");this.qj=h;b&&h.setAttribute("id",b);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");b=h.style;b.display=this.rw();b.position="relative";if(c=this.Hb())b.verticalAlign="top";a.qf(h,"click",function(){f.l_()});this.eD?this.yK=a.Y0(h,this.eD,c,!c):this.zD.appendChild(h);e&&h.appendChild(e)};a.prototype.zV=function(){var a=this.Is;a||(a=this.zn);return a};a.prototype.yY=function(){var a=this.CH,b=this.PS,e={Of:0,lh:0},f=[];if(this.zV().hasChildNodes()&&
a&&b&&0<b.length)for(var a=this.Hb(),h=0,h=this.zn.offsetWidth,k=0,l=null,m=0;m<b.length;m++){var n=b[m];if(1===n.nodeType){var p=n.offsetWidth,r=n.offsetHeight,s={Of:p,lh:r,id:n.id};if(a){var q=n.offsetLeft;this.Is||0!==q||(n=n.parentNode,q=n.offsetLeft);s.start=this.xA?h-(q+p):q;0===m&&(k=s.start);s.start-=k;e.Of=s.start+p;e.lh=Math.max(e.lh,r);s.end=e.Of-1}else q=n.offsetTop,this.Is||0!==q||(n=n.parentNode,q=n.offsetTop),s.start=q,e.Of=Math.max(e.Of,p),e.lh=s.start+r,s.end=e.lh-1;l&&l.end>=s.start&&
(p=l.end-(s.start-1),l.end-=p,a?l.Of-=p:l.lh-=p);f.push(s);l=s}}this.$C=f;return e};a.prototype.jt=function(){if(!this.$C){var a=this.yY();this.ge||(this.ge=a)}return this.$C};a.prototype.aJ=function(){return this.yK?this.yK:this.qj};a.prototype.hJ=function(){return this.OK?this.OK:this.yk};a.prototype.Xka=function(){this.aJ().style.display=this.rw()};a.prototype.Yka=function(){this.hJ().style.display=this.rw()};a.prototype.YB=function(){this.aJ().style.display="none"};a.prototype.ZB=function(){this.hJ().style.display=
"none"};a.prototype.wt=function(){return"none"!==this.aJ().style.display};a.prototype.Uw=function(){return"none"!==this.hJ().style.display};a.prototype.zI=function(){return this.Hb()?this.AA:this.zA};a.prototype.Nla=function(a){var b=this.zI(),e=this.Sg(),f=this.bt(),h=this.vC();a<=this.cx?(this.Uw()&&(f+=b,e-=b),this.ZB()):h&&(this.Uw()||(f-=b,e+=b),this.Yka());a>=this.ax?(this.wt()&&(f+=b),this.YB()):h&&(this.wt()||(f-=b),this.Xka());this.xL(e);h?this.G_(f):this.BT()};a.prototype.G_=function(a){var b=
this.be.style;a+="px";this.Hb()?b.maxWidth=a:b.maxHeight=a};a.prototype.BT=function(){var a=this.be.style;this.Hb()?a.maxWidth="":a.maxHeight=""};a.prototype.xL=function(a){var b=this.be;this.Hb()?b.scrollLeft=this.FH(a):b.scrollTop=a};a.prototype.bt=function(){var a=this.be;return this.Hb()?a.offsetWidth:a.offsetHeight};a.prototype.Qt=function(a,b){this.sn||(this.vA=!1,this.y_(a,b))};a.prototype.y_=function(b,c){if(!this.Bga()){this.sn=!0;b=this.laa(b);this.Nla(b);var e=this.k_;if(c||!e||b===this.Sg())this.OY(this.vA?
this.Sg():b);else{var f=this;e.call(this.Lp,this.be,this.FH(b),Math.abs(this.Sg()-b)/a.I8,function(){f.OY(b)})}}};a.prototype.Sg=function(){var a=this.be;return this.Hb()?this.raa(a.scrollLeft):a.scrollTop};a.prototype.vC=function(){var a=this.zn,b=this.be;return this.Hb()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};a.prototype.laa=function(a){!this.vC()||a<this.cx?a=this.cx:a>this.ax&&(a=this.ax);return a};a.prototype.lfa=function(b){var c=this.sn;if(this.vC()&&!this.sn){var e=a.fea(b);
0>e&&this.wt()?(c=!0,this.l_()):0<e&&this.Uw()&&(c=!0,this.m_())}c&&(b.preventDefault(),b.stopPropagation())};a.prototype.QJ=function(a){a=a.touches;this.vC()&&!this.sn&&1===a.length&&(this.cj=!0,a=a[0],this.kD=this.Hb()?a.pageX:a.pageY,this.ZL=this.Sg(),this.Bla=this.hT(),this.Cla=this.iT(),this.G0=this.wt(),this.H0=this.Uw())};a.prototype.PJ=function(b){var c=this.Hb(),e=b.touches[0],e=(c?e.pageX:e.pageY)-this.kD,f=c&&this.xA?0<e:0>e,h=f&&this.G0||!f&&this.H0;if(this.cj&&h){h=this.be;if(Math.abs(e)<
a.Y8*(c?h.offsetWidth:h.offsetHeight)){if(this.Qt(this.ZL-e,!0),this.G0&&!this.wt()||this.H0&&!this.Uw())this.cj=!1}else this.Qt(f?this.Bla:this.Cla,!1),this.cj=!1;this.Ot=!0}this.Ot&&(b.preventDefault(),b.stopPropagation())};a.prototype.NJ=function(){this.cj&&this.Qt(this.ZL,!1);this.Ot=this.cj=!1};a.prototype.tfa=function(){this.vA&&!this.sn&&this.y_(this.Sg(),!0)};a.prototype.OY=function(a){this.xL(a);this.jka();this.sn=!1;if(this.xI){this.Xs=this.fT();a=this.gT();var b=this.jt(),e=b[this.Xs];
this.Xs!==a&&this.Sg()>e.start&&this.Xs<b.length-2&&(this.Xs++,e=b[this.Xs]);this.rca=e.id;this.xI.call(this.Lp,this.rca)}};a.prototype.jka=function(){var a=this;window.setTimeout(function(){a&&(a.vA=!0)},0)};a.prototype.l_=function(){this.sn||this.Qt(this.hT(),!1)};a.prototype.m_=function(){this.sn||this.Qt(this.iT(),!1)};a.prototype.hT=function(){var a=this.F$(),b=0;return b=a===this.fT()?this.Sg()+this.bt():this.H$(a)};a.prototype.iT=function(){var a=this.G$(),b=0,b=a===this.gT()?this.Sg()-this.bt():
this.E$(a);this.wt()||(b+=this.zI());b<this.zI()&&(b=this.cx);return b};a.prototype.H$=function(a){return this.jt()[a].start};a.prototype.E$=function(a){return this.jt()[a].end-this.bt()+1};a.prototype.fT=function(){var a=this.CA(this.Sg());return 0>a?0:a};a.prototype.gT=function(){var a=this.CA(this.Sg()+this.bt()-1),b=this.jt();return 0>a?b.length-1:a};a.prototype.G$=function(){var a=this.CA(this.Sg()-1);return 0>a?0:a};a.prototype.F$=function(){var a=this.CA(this.Sg()+this.bt()),b=this.jt();return 0>
a?b.length-1:a};a.prototype.CA=function(a){for(var b=this.jt(),e=0;e<b.length;e++)if(a<=b[e].end)return e;return-1};a.prototype.FH=function(a){var b=a;if(this.xA&&this.Hb())if(this.j$)b=-a;else if(this.l$||this.k$)b=this.zn.offsetWidth-this.be.offsetWidth-a;return b};a.prototype.raa=function(a){return this.FH(a)};a.I8=1.1;a.Y8=.33;(function(){b.ya("oj.ojConveyorBelt",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},_ComponentCreate:function(){this._super();
this.element.addClass("oj-conveyorbelt oj-component");this.options.disabled&&b.r.warn(d);this.Aa(!0)},refresh:function(){this._super();var a="rtl"===this.ac()!==this.tf;a&&this.XH();this.Aa(a)},ml:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},gn:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},Aa:function(c){if(this.Vv()){this.Uc=null;this.tf="rtl"===this.ac();var d=this.element,g=this.options;if(c&&!this.DA){var h=g.orientation,k=null,l=null,m=null,n=null,p=null;"vertical"!==h?(k=
"oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",m=this.MA("oj-conveyorbelt-overflow-icon oj-start"),n=this.MA("oj-conveyorbelt-overflow-icon oj-end"),p=this.U9):(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",m=this.MA("oj-conveyorbelt-overflow-icon oj-top"),n=this.MA("oj-conveyorbelt-overflow-icon oj-bottom"),p=this.V9);
var r={};r.o4=k;r.b4=l;r.n4=m;r.a4=n;k={};k.eh=b.v.eh;k.Qh=b.v.Qh;"enabled"!==b.ba.kN()&&(k.B4=p);p=null;g.contentParent&&(p=f(g.contentParent)[0]);this.DA=new a(d[0],h,p,this.tf,r,k)}this.DA.Fm(c);c&&(c=d.find(".oj-conveyorbelt-overflow-indicator"),this.Mka(c))}else d=!1,this.Uc&&(d=this.Uc[0]),this.Uc=[c||d]},_destroy:function(){this.XH();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,e,f){var h=!1;switch(a){case "containerParent":case "orientation":h=
!0;break;case "disabled":b.r.warn(d)}h&&this.XH();this._super(a,e,f);h&&this.Aa(!0)},XH:function(){var a=this.DA;a&&(this.element.find(".oj-conveyorbelt-overflow-indicator").off(this.eventNamespace),a.destroy());this.DA=null},Vv:function(){var a=document.createElement("div"),b=a.style;b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var d=!1;try{d=0<a.offsetWidth&&0<a.offsetHeight}catch(f){}b.removeChild(a);return d},Mka:function(a){a.on("mousedown"+this.eventNamespace,function(a){f(a.currentTarget).addClass("oj-active")}).on("mouseup"+
this.eventNamespace,function(a){f(a.currentTarget).removeClass("oj-active")}).on("mouseenter"+this.eventNamespace,function(a){a=a.currentTarget;f(a).addClass("oj-hover");f(a).removeClass("oj-default")}).on("mouseleave"+this.eventNamespace,function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active");f(a).addClass("oj-default")})},MA:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon "+a);return b},U9:function(a,b,d,h){var k={};k.scrollLeft=
b;f(a).animate(k,d,"swing",h)},V9:function(a,b,d,h){var k={};k.scrollTop=b;f(a).animate(k,d,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:
"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-conveyorbelt-start-overflow-indicator"}),d=this.getNodeBySubId({subId:"oj-conveyorbelt-end-overflow-indicator"}),f=this.getNodeBySubId({subId:"oj-conveyorbelt-top-overflow-indicator"}),k=this.getNodeBySubId({subId:"oj-conveyorbelt-bottom-overflow-indicator"}),l=this.element[0];a&&a!=l;){if(a===b)return{subId:"oj-conveyorbelt-start-overflow-indicator"};
if(a===d)return{subId:"oj-conveyorbelt-end-overflow-indicator"};if(a===f)return{subId:"oj-conveyorbelt-top-overflow-indicator"};if(a===k)return{subId:"oj-conveyorbelt-bottom-overflow-indicator"};a=a.parentElement}return null}});var d="JET ConveyorBelt: 'disabled' option not supported"})()});