/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b){b.pe=function(b,a,d,c,e){this.uE=b;this.Ba=a;this.KM=[];this.dz=d;this.start=c<a.length?c:a.length-1;this.count=-1===e?a.length:Math.min(a.length,e)};o_("CollectionNodeSet",b.pe,b);b.pe.prototype.uP=function(b){this.$U(this).then(function(){b.success&&b.success()})};b.pe.prototype.$U=function(b){return new Promise(function(a){function d(e){e<c?b.O5(e,{success:function(a){null!==a?b.$U(a).then(function(){d(e+1)}):d(e+
1)}}):a(void 0)}var c=b.R();d(0)})};b.pe.prototype.O5=function(b,a){var d=this.Ba.at(b);if(this.dz.Fu(d).leaf)this.KM[b]=null,a.success(null);else{var c=this.dz.iz(d),d=this.dz.Fu(d).key,e=this;this.dz.Uu(c,0,-1,{success:function(c){e.KM[b]=c;a.success(c)}},d)}};b.pe.prototype.getParent=function(){return this.uE};b.b.g("CollectionNodeSet.prototype.getParent",{getParent:b.pe.prototype.getParent});b.pe.prototype.ta=function(){return this.start};b.b.g("CollectionNodeSet.prototype.getStart",{ta:b.pe.prototype.ta});
b.pe.prototype.R=function(){return this.count};b.b.g("CollectionNodeSet.prototype.getCount",{R:b.pe.prototype.R});b.pe.prototype.getData=function(b){this.tH(b);return this.Ba.at(b).attributes};b.b.g("CollectionNodeSet.prototype.getData",{getData:b.pe.prototype.getData});b.pe.prototype.tH=function(b){if(b<this.start||b>this.start+this.count)throw"Out of range";};b.pe.prototype.getMetadata=function(b){this.tH(b);var a={};b=this.Ba.at(b);b=this.dz.Fu(b);a.key=b.key;a.leaf=b.leaf;a.depth=b.depth;return a};
b.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:b.pe.prototype.getMetadata});b.pe.prototype.If=function(b){this.tH(b);return this.KM[b]};b.b.g("CollectionNodeSet.prototype.getChildNodeSet",{If:b.pe.prototype.If});b.Ia=function(f){f=f||{};this.Wy=f.root;this.Cma=f.childCollectionCallback;this.Fu=f.parseMetadata;this.Ar=null;this.Ju="none";this.Nd={};b.Ia.q.constructor.call(this)};o_("CollectionTreeDataSource",b.Ia,b);b.Ia.prototype.Fu=function(b){return{key:b.idAttribute+"\x3d"+b.id}};
b.b.ga(b.Ia,b.mp,"oj.CollectionTreeDataSource");b.Ia.prototype.Init=function(){b.Ia.q.Init.call(this)};b.b.g("CollectionTreeDataSource.prototype.Init",{Init:b.Ia.prototype.Init});b.Ia.prototype.Ye=function(b){var a=this.Nd[b];if(a&&0<a.length)return a.length;this.nN(b,{success:function(a){return a.length}});return-1};b.b.g("CollectionTreeDataSource.prototype.getChildCount",{Ye:b.Ia.prototype.Ye});b.Ia.prototype.nN=function(b,a){this.Ff(b,null,{success:function(b){a.success(b.Ba)},error:a.error})};
b.b.g("CollectionTreeDataSource.prototype.getChildCollection",{nN:b.Ia.prototype.nN});b.Ia.prototype.Ff=function(b,a,d){a=a||{};var c=a.start?a.start:0,e=a.count?a.count:-1;if(null===b)this.Uu(null,c,e,d,null);else{var g=this;this.ZI(this.Wy,b,0).then(function(a){if(a){a=g.iz(a.Po);try{g.Uu(a,c,e,d,b)}catch(k){d&&d.error&&d.error({status:k.message})}}else d&&d.error&&d.error(b)})}};b.b.g("CollectionTreeDataSource.prototype.fetchChildren",{Ff:b.Ia.prototype.Ff});b.Ia.prototype.i6=function(b,a,d){var c=
0;d&&d.at&&(c=d.at);a=this.HB(a);b=this.LA(this,"insert",c,a,this.kZ(null!=a&&0<a.length?a[a.length-1]:null,b));this.handleEvent("change",b)};b.Ia.prototype.j6=function(b,a,d){var c=0;d&&d.index&&(c=d.index);this.eja(b);b=this.LA(this,"delete",c,this.HB(a),null);this.handleEvent("change",b)};b.Ia.prototype.k6=function(b){var a=this.Jca(b),d=null,c=null;a&&(d=a.index,c=this.HB(a.Ba));b=this.LA(this,"update",d,c,this.kZ(null!=c&&0<c.length?c[c.length-1]:null,b));this.handleEvent("change",b)};b.Ia.prototype.F5=
function(b){b=this.LA(this,"refresh",null,this.HB(b),null);this.handleEvent("refresh",b)};b.Ia.prototype.kZ=function(f,a){var d=new b.j;d.add(a);return this.dW(d,f,0,1)};b.Ia.prototype.HB=function(f){var a=[],d=null;do d=this.Lda(f),null!==d&&(d!==b.Ia.XP&&a.unshift(d),f=this.Kca(d));while(null!=d);return a};b.Ia.XP="%!@ROOT%#@!";b.Ia.prototype.qB=function(f){var a=f instanceof b.t?this.Fu(f).key:f;return f?a:b.Ia.XP};b.Ia.prototype.uS=function(b){return this.Nd[this.qB(b)]};b.Ia.prototype.w_=function(f,
a){a.on(b.Y.D.ADD,this.i6,this);a.on(b.Y.D.REMOVE,this.j6,this);a.on(b.Y.D.CHANGE,this.k6,this);a.on(b.Y.D.SYNC,this.F5,this);this.Nd[this.qB(f)]=a};b.Ia.prototype.eja=function(b){b=this.qB(b);for(var a in this.Nd)if(this.Nd.hasOwnProperty(a)&&a===b){this.Nd[b].off(null,null,this);delete this.Nd[b];break}};b.Ia.prototype.Vga=function(b,a){for(var d=a.length,c=0;c<d;c++){var e=this.qB(a.at(c));if(b===e)return!0}return!1};b.Ia.prototype.Jca=function(b){for(var a in this.Nd)if(this.Nd.hasOwnProperty(a))for(var d=
this.Nd[a],c=0;c<d.length;c++)if(d.at(c)===b)return{index:c,Ba:d};return null};b.Ia.prototype.Kca=function(b){for(var a in this.Nd)if(this.Nd.hasOwnProperty(a)){var d=this.Nd[a];if(this.Vga(b,d))return d}return null};b.Ia.prototype.Lda=function(b){for(var a in this.Nd)if(this.Nd.hasOwnProperty(a)&&this.Nd[a]===b)return a;return null};b.Ia.prototype.iz=function(b){var a=!0,d=this.uS(b);d||(a=!1,d=this.Cma(this.Wy,b),null!=d&&(this.NS(d),this.w_(b,d)));return{Ba:d,HM:a}};b.Ia.prototype.LA=function(b,
a,d,c,e){return{source:b,operation:a,index:d,parent:c,data:e}};b.Ia.prototype.Uu=function(b,a,d,c,e){var g=this;null===b&&((b=this.uS(null))?b={Ba:b,HM:!0}:(b={Ba:g.Wy,HM:!1},g.w_(null,this.Wy)));b&&g.XU(b,function(b){c.success&&c.success(g.dW(b,e,a,d))},c.error)};b.Ia.prototype.dW=function(f,a,d,c){return new b.pe(a,f,this,d,c)};b.Ia.prototype.Xja=function(b,a){var d=this;return new Promise(function(c){function e(a,b,f){a<b.length?b.at(a,{deferred:!0}).then(function(l){if(l){var m=d.Fu(l);if(f===
m.key){c(l);return}}a++;e(a,b,f)}):c(null)}e(0,b,a)})};b.Ia.prototype.ZI=function(b,a,d){var c=this;return new Promise(function(e){c.Xja(b,a).then(function(g){function h(c,g){if(c<k){var n=g.iz(b.at(c));n.Ba?g.XU(n,function(b){g.ZI(b,a,d+1).then(function(a){a?e(a):(c++,h(c,g))})},null):(c++,h(c,g))}else e(null)}if(g)e({Po:g,depth:d});else{var k=b.length;h(0,c)}})})};b.Ia.prototype.XU=function(b,a,d){b.HM?a(b.Ba):(this.Ar&&"none"!==this.Ar&&(b.Ba.OM=this.Ar,b.Ba.OO=this.Ju),0<b.Ba.length||!b.Ba.a6()?
a(b.Ba):b.Ba.fetch({success:function(b){a(b)},error:d}))};b.Ia.prototype.pu=function(b,a){var d=this;null===b?this.Uu(null,0,-1,{success:function(b){b.uP({success:function(){a.success&&a.success(b)}})}},null):this.ZI(this.Wy,b,0).then(function(c){c&&(c=d.iz(c.Po),d.Uu(c,0,-1,{success:function(b){b.uP({success:function(){a.success&&a.success(b)}})}},b))})};b.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{pu:b.Ia.prototype.pu});b.Ia.prototype.sort=function(b,a){var d=b.key,c=b.direction,
e=!1;d!==this.Ar&&(this.Ar=d,e=!0);c!==this.Ju&&(this.Ju=c,e=!0);if(e){"none"===this.Ju&&(this.Nd={});for(var g in this.Nd)this.Nd.hasOwnProperty(g)&&this.NS(this.Nd[g])}a&&a.success&&a.success()};b.b.g("CollectionTreeDataSource.prototype.sort",{sort:b.Ia.prototype.sort});b.Ia.prototype.NS=function(b){b.comparator=this.Ar;b.sortDirection="ascending"===this.Ju?1:-1;b.sort()};b.Ia.prototype.jm=function(){return{key:this.Ar,direction:this.Ju}};b.b.g("CollectionTreeDataSource.prototype.getSortCriteria",
{jm:b.Ia.prototype.jm});b.Ia.prototype.move=function(){b.l.Wb()};b.b.g("CollectionTreeDataSource.prototype.move",{move:b.Ia.prototype.move});b.Ia.prototype.md=function(){return"invalid"};b.b.g("CollectionTreeDataSource.prototype.moveOK",{md:b.Ia.prototype.md});b.Ia.prototype.getCapability=function(b){return"sort"===b?"default":"move"===b?"none":"batchFetch"===b||"fetchDescendants"===b?"disable":null};b.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:b.Ia.prototype.getCapability})});