/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","promise","ojs/ojdatasource-common"],function(b,f){b.Va=function(a,b){this.Init();this.qa=a;this.Zg=b;this.Gr()};o_("Cube",b.Va,b);b.b.ga(b.Va,b.b,"oj.Cube");b.Va.prototype.Init=function(){b.Va.q.Init.call(this)};b.Va.prototype.fm=function(){var a=this.gW(),b=[];Array.prototype.push.apply(b,a?a.fm():this.sf);for(a=2;a<this.sf.length;a++)b.push(this.sf[a]);return b};b.b.g("Cube.prototype.getAxes",{fm:b.Va.prototype.fm});b.Va.prototype.bJ=function(){return this.sf};b.Va.prototype.lm=
function(a){var b=this.gW();a=b.Rha(a);for(a=b=b.X0(a,0,[]);Array.isArray(a)&&1===a.length;)if(a=a[0],!Array.isArray(a))return a;return b};b.b.g("Cube.prototype.getValues",{lm:b.Va.prototype.lm});b.Va.prototype.setPage=function(a){this.HK=a instanceof Array?a:[a]};b.Va.prototype.l4=function(a,d,c,e,f){var h=this.Zg,k=this.dV(a);if(!k)return!1;a=null;c<h.length?a=this.dV(c):(a={axis:c,levels:[]},h.push(a));c=k.levels;h=a.levels;a=d<c.length?c[d]:null;if(!a)return!1;e>=h.length?(h.push(a),c.splice(d,
1)):f===b.Va.sF.SWAP?(c[d]=h[e],h[e]=a):(f===b.Va.sF.AFTER&&e++,h.splice(e,0,a),h===c&&e<d&&d++,c.splice(d,1));this.Gr();return!0};b.b.g("Cube.prototype.pivot",{l4:b.Va.prototype.l4});b.Va.prototype.dV=function(a){for(var b=0;b<this.Zg.length;b++)if(this.Zg[b].axis===a)return this.Zg[b];return null};b.Va.prototype.C2=function(){return this.Zg};b.b.g("Cube.prototype.getLayout",{C2:b.Va.prototype.C2});b.Va.sF={BEFORE:"before",AFTER:"after",SWAP:"swap"};o_("Cube.PivotType",b.Va.sF,b);b.Va.prototype.X0=
function(a,b,c){var e=[];if(0===a.length)return b=c.slice(0),this.lq(b);var f=a.slice(1),h=a[0].start;a=a[0].count;for(c[b]=h;c[b]<h+a;c[b]++)e.push(this.X0(f,b+1,c));return e};b.Va.prototype.Rha=function(a){var b=[];if(!a)return b;for(var c=Math.min(a.length,this.sf.length),e=0;e<c;e++){var f=a[e];f instanceof Object&&(f.hasOwnProperty("start")||f.hasOwnProperty("count"))?f.hasOwnProperty("start")?f.hasOwnProperty("count")?b.push(this.mB(f.start,f.count,e)):b.push(this.mB(f.start,1,e)):b.push(this.mB(0,
f.count,e)):b.push(this.mB(f,1,e))}return b};b.Va.prototype.mB=function(a,b,c){c=this.fm()[c].Rb();if(a>=c||0>a)a=0;b=Math.min(b,c-a);return{start:a,index:a,count:b}};b.Va.prototype.lq=function(a){var d=this.zaa(a);return d&&(d=d.hp(),0<d.length&&(d=this.i[d[0].key]))?new b.Sf(d.value,a,d.DD,d.rows,d.Wo):new b.Sf(null,a,void 0,[])};b.Va.prototype.Q5=function(){var a=this.Gda();this.HK=[];for(var b=0;b<a.length;b++)this.Zp(a[b].axis,a[b].levels),this.HK.push({axis:a[b].axis,index:0});if(0===a.length)for(a=
this.bJ(),b=0;b<a.length;b++)this.Zp(a[b].axis,a[b].levels)};b.Va.prototype.Gda=function(){for(var a=[],b=0;b<this.Zg.length;b++)1<this.Zg[b].axis&&a.push(this.Zg[b]);return a};b.Va.prototype.bJ=function(){for(var a=[],b=0;b<this.Zg.length;b++)2>this.Zg[b].axis&&a.push(this.Zg[b]);return a};b.Va.prototype.Gr=function(){this.sf=[];this.i=[];this.RH=[];this.Q5();if(null!==this.qa)for(var a=0;a<this.qa.length;a++){for(var d=new b.Oi,c=2;c<this.sf.length;c++)d=this.sf[c].RP(this.qa[a],d);for(var d=d.hp(),
e=0;e<d.length;e++){var c=d[e].key,f=this.RH[c];f||(f=this.RH[c]=this.ZE(this.bJ()));for(var h=new b.Oi,k=f.sf.length,c=0;c<k;c++)h=f.sf[c].RP(this.qa[a],h);h=c=h.hp();if(void 0!==d[e].N1)for(h=[],k=0;k<c.length;k++)h.push(d[e]);f.dla(c,h,this.qa[a])}}};b.Va.prototype.dla=function(a,b,c){for(var e=0;e<a.length;e++)this.i[a[e].key]=this.P9(b[e],this.i[a[e].key],c)};b.Va.prototype.gW=function(){return this.RH[this.gda(this.HK)]};b.Va.prototype.gda=function(a){var d=new b.Oi;if(a&&0<a.length){a.sort(function(a,
b){return a.axis-b.axis});for(var c=this.sf,e=0;e<a.length;e++)d=c[a[e].axis].jz(a[e].index,d)}return d.hp()[0].key};b.Va.fY=function(a){return a?void 0!==a.value&&null!==a.value:!1};b.Va.prototype.zc=function(a,b,c,e,f){c.push(e);e={};for(var h in f)f.hasOwnProperty(h)&&(e[h]=f[h]);e.value=a;e.DD=b;e.rows=c;return e};b.Va.Ce=function(a){return b.Ea.jd(a.value)?!1:!isNaN(a.value)};b.Va.prototype.P9=function(a,d,c){var e=this.aF(a.N1),f=e.eu,h=b.Va.fY(d),k=b.Va.fY(a),l=h&&b.Va.Ce(d),m=k&&b.Va.Ce(a);
switch(f){case b.Rf.SUM:return h&&k?l&&m?this.zc(d.value+a.value,f,d.rows,c,{}):this.zc(NaN,f,d.rows,c,{}):k&&!h?m?this.zc(a.value,f,[],c,{}):this.zc(NaN,f,[],c,{}):d;case b.Rf.AVERAGE:return h&&k?l&&m?this.zc((d.Lu+a.value)/(d.rows.length+1),f,d.rows,c,{Lu:d.Lu+a.value}):this.zc(NaN,f,d.rows,c,{Lu:d.Lu}):k&&!h?m?this.zc(a.value,f,[],c,{Lu:a.value}):this.zc(NaN,f,[],c,{Lu:NaN}):d;case b.Rf.VARIANCE:case b.Rf.STDDEV:return h&&k?l&&m?(h=d.value+(a.value-d.value)/(d.rows.length+1),this.zc(h,f,d.rows,
c,{Wo:d.Wo+(a.value-d.value)*(a.value-h)})):this.zc(NaN,f,d.rows,c,{Wo:NaN}):k&&!h?m?this.zc(a.value,f,[],c,{Wo:0}):this.zc(NaN,f,[],c,{Wo:NaN}):d;case b.Rf.NONE:return this.zc(null,f,h?d.rows:[],c,{});case b.Rf.FIRST:return h?this.zc(d.value,f,d.rows,c,{}):k?this.zc(a.value,f,[],c,{}):d;case b.Rf.MIN:return h&&k?l&&m?this.zc(Math.min(d.value,a.value),f,d.rows,c,{}):this.zc(NaN,f,d.rows,c,{}):k&&!h?m?this.zc(a.value,f,[],c,{}):this.zc(NaN,f,[],c,{}):d;case b.Rf.MAX:return h&&k?l&&m?this.zc(Math.max(d.value,
a.value),f,d.rows,c,{}):this.zc(NaN,f,d.rows,c,{}):k&&!h?m?this.zc(a.value,f,[],c,{}):this.zc(NaN,f,[],c,{}):d;case b.Rf.COUNT:return h&&k?this.zc(d.value+1,f,d.rows,c,{}):k&&!h?this.zc(1,f,[],c,{}):d;case b.Rf.CUSTOM:return a=e.Jb.call(this,h?d.value:void 0,k?a.value:void 0),this.zc(a,f,h?d.rows:[],c,{})}};b.Va.prototype.Zp=function(a,d){a>=this.sf.length&&Array.prototype.push.apply(this.sf,Array(a-this.sf.length+1));this.sf[a]||(this.sf[a]=new b.Ze(d,a,this));return this.sf[a]};b.Va.prototype.zaa=
function(a){for(var d=this.fm(),c=new b.Oi,e=0;e<a.length;e++)c=d[e].jz(a[e],c);return c};b.Va.prototype.Tr=function(){b.l.Wb()};b.Va.prototype.ZE=function(){b.l.Wb()};b.Va.prototype.$E=function(){b.l.Wb()};b.Va.prototype.aF=function(){b.l.Wb();return{}};b.Rf={SUM:"sum",AVERAGE:"avg",STDDEV:"stddev",VARIANCE:"variance",NONE:"none",FIRST:"first",MIN:"min",MAX:"max",COUNT:"count",CUSTOM:"custom"};o_("CubeAggType",b.Rf,b);b.Zb=function(a,b,c,e){this.Init();this.vd=[];this.Cq=e;this.kba=c;this.i={};this.i.value=
a;this.i.label=b};o_("CubeAxisValue",b.Zb,b);b.b.ga(b.Zb,b.b,"oj.CubeAxisValue");b.Zb.prototype.Init=function(){b.Zb.q.Init.call(this)};b.Zb.prototype.cr=function(){return this.kba};b.b.g("CubeAxisValue.prototype.getLevel",{cr:b.Zb.prototype.cr});b.Zb.prototype.ie=function(){return 1};b.b.g("CubeAxisValue.prototype.getDepth",{ie:b.Zb.prototype.ie});b.Zb.prototype.E2=function(){for(var a=[],b=this.Cq;b&&b.Cq;)a.unshift(b),b=b.Cq;return a};b.b.g("CubeAxisValue.prototype.getParents",{E2:b.Zb.prototype.E2});
b.Zb.prototype.getChildren=function(){return this.vd};b.b.g("CubeAxisValue.prototype.getChildren",{getChildren:b.Zb.prototype.getChildren});b.Zb.prototype.Rb=function(){if(-1<this.Us)return this.Us;if(this.vd&&0!==this.vd.length)for(var a=this.Us=0;a<this.getChildren().length;a++)this.Us+=this.getChildren()[a].Rb();else this.Us=1;return this.Us};b.b.g("CubeAxisValue.prototype.getExtent",{Rb:b.Zb.prototype.Rb});b.Zb.prototype.ta=function(){if(-1<this.Ih)return this.Ih;if(!this.Cq)return 0;for(var a=
this.Cq.ta(),b=this.Cq.jW(this);b;)a+=b.Rb(),b=this.Cq.jW(b);return this.Ih=a};b.b.g("CubeAxisValue.prototype.getStart",{ta:b.Zb.prototype.ta});b.Zb.prototype.Hc=function(){return this.i.value};b.b.g("CubeAxisValue.prototype.getValue",{Hc:b.Zb.prototype.Hc});b.Zb.prototype.sN=function(){return this.i.label?this.i.label:this.Hc()};b.b.g("CubeAxisValue.prototype.getLabel",{sN:b.Zb.prototype.sN});b.Zb.prototype.R5=function(a){var b=this.Gca();if(null===b)return null;if(b.yu())return this.Qca(a);if(a=
a[b.attribute])for(b=0;b<this.vd.length;b++)if(this.vd[b].Hc()===a)return this.vd[b];return null};b.Zb.prototype.Qca=function(a){for(var b=0;b<this.vd.length;b++){var c=this.vd[b].Hc();if(a.hasOwnProperty(c)&&a[c]===c)return this.vd[b]}return null};b.Zb.prototype.Gca=function(){return this.vd&&0<this.vd.length?this.vd[0].cr():null};b.Zb.prototype.S5=function(a){return this.qI(a,0,this.vd.length-1)};b.Zb.prototype.qI=function(a,b,c){if(b>c)return null;var e=Math.floor((b+c)/2),f=this.vd[e],h=f.ta();
return h>a?this.qI(a,b,e-1):h+f.Rb()-1<a?this.qI(a,e+1,c):f};b.Zb.prototype.OE=function(a,d,c){for(var e=0;e<this.vd.length;e++)if(this.vd[e].Hc()===a)return this.vd[e];a=new b.Zb(a,d,c,this);this.vd.push(a);return a};b.Zb.prototype.T5=function(){var a={};a[this.cr().attribute]=this.Hc();return a};b.Zb.prototype.jW=function(a){for(var b=0;b<this.vd.length;b++)if(this.vd[b]===a){if(0<b)return this.vd[b-1];break}return null};b.Ze=function(a,d,c){this.Init();this.axis=d;this.oY=[];for(d=0;d<a.length;d++)this.oY.push(c.$E(a[d],
this));this.gw=c;this.qo=new b.Zb(null,null,null,null)};o_("CubeAxis",b.Ze,b);b.b.ga(b.Ze,b.b,"oj.CubeAxis");b.Ze.prototype.Init=function(){b.Ze.q.Init.call(this)};b.Ze.prototype.Nk=function(){return this.oY};b.b.g("CubeAxis.prototype.getLevels",{Nk:b.Ze.prototype.Nk});b.Ze.prototype.Rb=function(){return this.qo.Rb()};b.b.g("CubeAxis.prototype.getExtent",{Rb:b.Ze.prototype.Rb});b.Ze.prototype.lm=function(a){for(var b=[],c=this.qo;c;)(c=c.S5(a))&&b.push(c);return b};b.b.g("CubeAxis.prototype.getValues",
{lm:b.Ze.prototype.lm});b.Ze.prototype.Fi=function(a){a=a?JSON.parse(a):{};for(var b=this.qo,c=null;b;)c=b,b=b.R5(a);return c?c.ta():-1};b.b.g("CubeAxis.prototype.getIndex",{Fi:b.Ze.prototype.Fi});b.Ze.prototype.jz=function(a,b){return this.AP(a,this.Nk().length-1,b)};b.Ze.prototype.AP=function(a,b,c){a=this.lm(a);b=this.Nk()[b];for(var e=0;e<a.length;e++){var f=a[e];f.cr().yu()?c.NE(f.Hc()):c.BF(f);if(f.cr()===b)break}return c};b.Ze.prototype.RP=function(a,b){return this.gw.Tr(this,0,this.qo,a,b,
!0)};b.Sf=function(a,b,c,e,f){this.Init();this.i={};this.i.value=a;this.i.roa=b;this.i.DD=c;this.i.rows=e;this.i.Wo=f};o_("CubeDataValue",b.Sf,b);b.b.ga(b.Sf,b.b,"oj.CubeDataValue");b.Sf.prototype.Init=function(){b.Sf.q.Init.call(this)};b.Sf.prototype.Hc=function(){switch(this.i.DD){case b.Rf.STDDEV:return Math.sqrt(this.MW());case b.Rf.VARIANCE:return this.MW();default:return this.i.value}};b.b.g("CubeDataValue.prototype.getValue",{Hc:b.Sf.prototype.Hc});b.Sf.prototype.A2=function(){return this.i.roa};
b.b.g("CubeDataValue.prototype.getIndices",{A2:b.Sf.prototype.A2});b.Sf.prototype.I2=function(){return this.i.rows};b.b.g("CubeDataValue.prototype.getRows",{I2:b.Sf.prototype.I2});b.Sf.prototype.e2=function(){return this.i.DD};b.b.g("CubeDataValue.prototype.getAggregation",{e2:b.Sf.prototype.e2});b.Sf.prototype.MW=function(){if(isNaN(this.i.Wo))return NaN;var a=this.i.rows.length;return 1<a?this.i.Wo/(a-1):0};b.Ni=function(a,d){var c=d.row?d.row.start:0,e=d.row?d.row.count:0,f=d.column?d.column.start:
0,h=d.column?d.column.count:0;b.l.Zl(c,null);b.l.Zl(e,null);b.l.Zl(f,null);b.l.Zl(h,null);this.gw=a;this.KL={row:c,column:f};this.qo=this.gw.lm([{start:f,count:h},{start:c,count:e}]);h=this.qo.length;0<h&&(e=this.qo[0].length);this.vaa={row:e,column:h}};o_("CubeCellSet",b.Ni,b);b.Ni.prototype.getData=function(a){return(a=this.qo[a.column-this.KL.column][a.row-this.KL.row])?a.Hc():null};b.b.g("CubeCellSet.prototype.getData",{getData:b.Ni.prototype.getData});b.Ni.prototype.getMetadata=function(a){var b=
{keys:{}};b.keys.row=this.qV(a,"row",2);b.keys.column=this.qV(a,"column",1);return b};b.b.g("CubeCellSet.prototype.getMetadata",{getMetadata:b.Ni.prototype.getMetadata});b.Ni.prototype.qV=function(a,d,c){var e=this.gw.fm();return void 0!==a[d]&&e.length>=c?(c=new b.Oi,c=e[b.Eb.QT(d)].jz(a[d],c),c.hp()[0].key):null};b.Ni.prototype.ta=function(a){return this.KL[a]};b.b.g("CubeCellSet.prototype.getStart",{ta:b.Ni.prototype.ta});b.Ni.prototype.R=function(a){return this.vaa[a]};b.b.g("CubeCellSet.prototype.getCount",
{R:b.Ni.prototype.R});b.Uf=function(a,d,c){this.Init();this.An=c;this.XG();b.Uf.q.constructor.call(this,a,d)};o_("DataValueAttributeCube",b.Uf,b);b.b.ga(b.Uf,b.Va,"oj.DataValueAttributeCube");b.Uf.prototype.qa=null;b.Uf.prototype.Init=function(){b.Uf.q.Init.call(this)};b.Uf.prototype.Gr=function(){b.Uf.q.Gr.call(this)};b.Uf.prototype.aF=function(a){return this.Ms[a]};b.Uf.prototype.$E=function(a,d){return a.dataValue?new b.Fg(null,d,!0):new b.Fg(a.attribute,d,!1)};b.Uf.prototype.ZE=function(a){return new b.Uf(null,
a,this.An)};b.Uf.prototype.Tr=function(a,b,c,e,f,h){if(b>=a.Nk().length)return f;var k=a.Nk()[b];if(k.yu())return this.uia(a,c,e,b,f);c=c.OE(e[k.attribute],null,k);h&&f.BF(c);return this.Tr(a,b+1,c,e,f,h)};b.Uf.prototype.uia=function(a,b,c,e,f){for(var h=!0,k=0;k<this.An.length;k++){var l=this.An[k].attribute,m=this.An[k].label;c.hasOwnProperty(l)&&(m=b.OE(l,m,a.Nk()[e]),f.NE(l,c[l]),this.Tr(a,e+1,m,c,f,h),h=!1)}return f};b.Uf.prototype.XG=function(){this.Ms=[];for(var a=0;a<this.An.length;a++){var d=
this.An[a];this.Ms[d.attribute]=d.aggregation?{eu:d.aggregation,Jb:d.callback}:{eu:b.Rf.SUM,Jb:d.callback}}};b.Oi=function(){this.nK=[];this.i=[]};b.Oi.prototype.BF=function(a){this.nK.push(a)};b.Oi.prototype.NE=function(a,b){this.i.push({name:a,value:b})};b.Oi.prototype.hp=function(){var a=[],b=this.u$();if(0===this.i.length)a.push({key:JSON.stringify(b)});else for(var c=0;c<this.i.length;c++){var e=f.extend(!0,{},b);e[this.i[c].name]=this.i[c].name;a.push({key:JSON.stringify(e),N1:this.i[c].name,
value:this.i[c].value})}return a};b.Oi.prototype.u$=function(){for(var a={},b=0;b<this.nK.length;b++){var c=this.nK[b].T5(),e;for(e in c)c.hasOwnProperty(e)&&(a[e]=c[e])}return a};b.Ke=function(a,b,c,e){this.gw=b;this.Tv=a;this.Ih=void 0===c?0:c;this.uaa=void 0===e?this.Tv.Rb():Math.min(e,this.Tv.Rb()-c);this.SU=c+e-1};o_("CubeHeaderSet",b.Ke,b);b.Ke.prototype.getData=function(a,b){var c=this.lq(a,b);return c?c.sN():null};b.b.g("CubeHeaderSet.prototype.getData",{getData:b.Ke.prototype.getData});b.Ke.prototype.getMetadata=
function(a,d){var c=new b.Oi,c=this.Tv.AP(a,d,c);return(c=c.hp())&&0<c.length?{key:c[0].key}:null};b.b.g("CubeHeaderSet.prototype.getMetadata",{getMetadata:b.Ke.prototype.getMetadata});b.Ke.prototype.pg=function(){return this.Tv.Nk().length};b.b.g("CubeHeaderSet.prototype.getLevelCount",{pg:b.Ke.prototype.pg});b.Ke.prototype.Rb=function(a,b){var c=this.lq(a,b),e=c.Rb(),c=c.ta(),f=c+e-1,h=a<c+e-1;c<this.Ih&&(e-=this.Ih-c);f>this.SU&&(e-=f-this.SU);return{extent:e,more:{before:a>c,after:h}}};b.b.g("CubeHeaderSet.prototype.getExtent",
{Rb:b.Ke.prototype.Rb});b.Ke.prototype.ie=function(a,b){return this.lq(a,b).ie()};b.b.g("CubeHeaderSet.prototype.getDepth",{ie:b.Ke.prototype.ie});b.Ke.prototype.R=function(){return this.uaa};b.b.g("CubeHeaderSet.prototype.getCount",{R:b.Ke.prototype.R});b.Ke.prototype.ta=function(){return this.Ih};b.b.g("CubeHeaderSet.prototype.getStart",{ta:b.Ke.prototype.ta});b.Ke.prototype.lq=function(a,b){void 0===b&&(b=0);var c=this.Tv.lm(a);return c&&c.length>b?c[b]:null};b.Eb=function(a){b.Eb.q.constructor.call(this,
a)};o_("CubeDataGridDataSource",b.Eb,b);b.b.ga(b.Eb,b.Om,"oj.CubeDataGridDataSource");b.Eb.prototype.E4=function(a){this.data=a;this.hV()};b.b.g("CubeDataGridDataSource.prototype.setCube",{E4:b.Eb.prototype.E4});b.Eb.prototype.setPage=function(a){this.data.setPage(a);this.hV()};b.b.g("CubeDataGridDataSource.prototype.setPage",{setPage:b.Eb.prototype.setPage});b.Eb.prototype.hV=function(){this.handleEvent("change",{source:this,operation:"refresh"})};b.Eb.prototype.R=function(a){return(a=this.Zp(a))?
a.Rb():0};b.b.g("CubeDataGridDataSource.prototype.getCount",{R:b.Eb.prototype.R});b.Eb.prototype.og=function(){return"exact"};b.b.g("CubeDataGridDataSource.prototype.getCountPrecision",{og:b.Eb.prototype.og});b.Eb.prototype.Gf=function(a,d,c){var e=new b.Ke(this.Zp(a.axis),this.data,a.start,a.count);d.success.call(c?c.success:void 0,e,a)};b.b.g("CubeDataGridDataSource.prototype.fetchHeaders",{Gf:b.Eb.prototype.Gf});b.Eb.prototype.ng=function(a,d,c){for(var e={},f=0;f<a.length;f++){var h=void 0===
a[f].start?0:a[f].start;if("row"===a[f].axis){var k=void 0===a[f].count?this.data.fm()[1].Rb():a[f].count;e.row={start:h,count:k}}"column"===a[f].axis&&(k=void 0===a[f].count?this.data.fm()[0].Rb():a[f].count,e.column={start:h,count:k})}e=new b.Ni(this.data,e);d.success.call(c?c.success:void 0,e,a)};b.b.g("CubeDataGridDataSource.prototype.fetchCells",{ng:b.Eb.prototype.ng});b.Eb.prototype.keys=function(a){var b={},b=this.Hn(a,"row",b),b=this.Hn(a,"column",b);return Promise.resolve(b)};b.b.g("CubeDataGridDataSource.prototype.keys",
{keys:b.Eb.prototype.keys});b.Eb.prototype.Hn=function(a,d,c){var e=this.Zp(d);a=a[d];var f=new b.Oi,f=e?e.jz(a,f):"";c[d]=f.hp()[0].key;return c};b.Eb.prototype.tg=function(a){var b={},b=this.Ug(a,"row",b),b=this.Ug(a,"column",b);return Promise.resolve(b)};b.b.g("CubeDataGridDataSource.prototype.indexes",{tg:b.Eb.prototype.tg});b.Eb.prototype.Ug=function(a,b,c){c[b]=this.Zp(b).Fi(a[b]);return c};b.Eb.prototype.sort=function(){b.l.Wb()};b.b.g("CubeDataGridDataSource.prototype.sort",{sort:b.Eb.prototype.sort});
b.Eb.prototype.move=function(){b.l.Wb()};b.b.g("CubeDataGridDataSource.prototype.move",{move:b.Eb.prototype.move});b.Eb.prototype.md=function(){return"invalid"};b.b.g("CubeDataGridDataSource.prototype.moveOK",{md:b.Eb.prototype.md});b.Eb.prototype.getCapability=function(a){switch(a){case "sort":return"none";case "move":return"none"}return null};b.b.g("CubeDataGridDataSource.prototype.getCapability",{getCapability:b.Eb.prototype.getCapability});b.Eb.QT=function(a){return"row"===a?1:0};b.Eb.prototype.Zp=
function(a){a=b.Eb.QT(a);var d=this.data.fm();return d.length>a?d[a]:null};b.Tf=function(a,d,c){this.Init();this.An=c;this.$la=c.valueAttr;this.Xga=c.labelAttr;var e=c.defaultAggregation;this.mU=e?b.Tf.Sca(e):{eu:b.Rf.SUM};this.MG=c.aggregation;this.XG();b.Tf.q.constructor.call(this,a,d)};o_("DataColumnCube",b.Tf,b);b.b.ga(b.Tf,b.Va,"oj.DataColumnCube");b.Tf.prototype.Init=function(){b.Tf.q.Init.call(this)};b.Tf.prototype.Gr=function(){b.Tf.q.Gr.call(this)};b.Tf.prototype.aF=function(a){return this.Ms[a]?
this.Ms[a]:this.mU};b.Tf.prototype.ZE=function(a){return new b.Tf(null,a,this.An)};b.Tf.prototype.$E=function(a,d){return a.attribute===this.Xga?new b.Fg(a.attribute,d,!0):new b.Fg(a.attribute,d,!1)};b.Tf.prototype.Tr=function(a,b,c,e,f,h){if(b>=a.Nk().length)return f;var k=a.Nk()[b],l=e[k.attribute];c=c.OE(l,null,k);k.yu()?f.NE(l,e[this.$la]):f.BF(c);return this.Tr(a,b+1,c,e,f,h)};b.Tf.Sca=function(a){return b.Ea.jd(a)?{eu:a}:{eu:a.aggregation,Jb:a.callback}};b.Tf.prototype.XG=function(){this.Ms=
[];if(this.MG)for(var a=0;a<this.MG.length;a++){var b=this.MG[a],c=b.aggregation;this.Ms[b.value]=c?{eu:c,Jb:b.callback}:this.mU}};b.Fg=function(a,b,c){this.Init();this.attribute=a;this.US=b;this.axis=b.axis;this.lU=c};o_("CubeLevel",b.Fg,b);b.b.ga(b.Fg,b.b,"oj.CubeLevel");b.Fg.prototype.Init=function(){b.Fg.q.Init.call(this)};b.Fg.prototype.Hc=function(a){if(a=this.US.lm(a))for(var b=0;b<a.length;b++)if(a[b].cr()===this)return a[b];return null};b.b.g("CubeLevel.prototype.getValue",{Hc:b.Fg.prototype.Hc});
b.Fg.prototype.yu=function(){return this.lU};b.b.g("CubeLevel.prototype.isDataValue",{yu:b.Fg.prototype.yu});b.Fg.prototype.lU=!1;b.Fg.prototype.US=null});