/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/internal-deps/datagrid/DvtDataGrid","ojs/ojcomponentcore","ojs/ojdatasource-common","ojs/ojarraydatagriddatasource","ojs/ojflattenedtreedatagriddatasource","ojs/ojpagingdatagriddatasource","ojs/ojinputnumber","ojs/ojmenu","ojs/ojdialog","ojs/ojpagingcontrol"],function(b,f,a){b.Th=function(a,c){this.tpa=a;this.Upa=c;this.Pa={};this.Pa.datagrid="oj-datagrid";this.Pa.cell="oj-datagrid-cell";this.Pa.cellcontent="oj-datagrid-cell-content";this.Pa.celltext="oj-datagrid-cell-text";
this.Pa.banded="oj-datagrid-banded";this.Pa.row="oj-datagrid-row";this.Pa.databody="oj-datagrid-databody";this.Pa.topcorner="oj-datagrid-top-corner";this.Pa.bottomcorner="oj-datagrid-bottom-corner";this.Pa.rowheaderspacer="oj-datagrid-row-header-spacer";this.Pa.colheaderspacer="oj-datagrid-column-header-spacer";this.Pa.status="oj-datagrid-status";this.Pa.emptytext="oj-datagrid-empty-text";this.Pa.header="oj-datagrid-header";this.Pa.groupingcontainer="oj-datagrid-header-grouping";this.Pa.headercell=
"oj-datagrid-header-cell";this.Pa.headercelltext="oj-datagrid-header-cell-text";this.Pa.headercellcontent="oj-datagrid-header-cell-content";this.Pa.rowheader="oj-datagrid-row-header";this.Pa.colheader="oj-datagrid-column-header";this.Pa.colheadercell="oj-datagrid-column-header-cell";this.Pa.rowheadercell="oj-datagrid-row-header-cell";this.Pa["scroller-mobile"]="oj-datagrid-scroller-touch";this.Pa.scroller="oj-datagrid-scroller";this.Pa.scrollers="oj-datagrid-scrollers";this.Pa.focus="oj-focus";this.Pa.hover=
"oj-hover";this.Pa.active="oj-active";this.Pa.selected="oj-selected";this.Pa.disabled="oj-disabled";this.Pa.enabled="oj-enabled";this.Pa["default"]="oj-default";this.Pa.sortcontainer="oj-datagrid-sort-icon-container";this.Pa.sortascending="oj-datagrid-sort-ascending-icon";this.Pa.sortdescending="oj-datagrid-sort-descending-icon";this.Pa.icon="oj-component-icon";this.Pa.clickableicon="oj-clickable-icon-nocontext";this.Pa.info="oj-helper-hidden-accessible";this.Pa.rowexpander="oj-rowexpander";this.Pa.cut=
"oj-datagrid-cut";this.Pa.selectaffordancetop="oj-datagrid-touch-selection-affordance-top";this.Pa.selectaffordancebottom="oj-datagrid-touch-selection-affordance-bottom";this.Pa.toucharea="oj-datagrid-touch-area";this.Pa.draggable="oj-draggable";this.Pa.drag="oj-drag";this.Pa.drop="oj-drop";this.Pa.activedrop="oj-active-drop";this.Pa.validdrop="oj-valid-drop";this.Pa.invaliddrop="oj-invalid-drop";this.fh={};this.fh.sortCol="oj-datagrid-sortCol";this.fh.sortColAsc="oj-datagrid-sortColAsc";this.fh.sortColDsc=
"oj-datagrid-sortColDsc";this.fh.sortRow="oj-datagrid-sortRow";this.fh.sortRowAsc="oj-datagrid-sortRowAsc";this.fh.sortRowDsc="oj-datagrid-sortRowDsc";this.fh.resize="oj-datagrid-resize";this.fh.resizeWidth="oj-datagrid-resizeWidth";this.fh.resizeHeight="oj-datagrid-resizeHeight";this.fh.cut="oj-datagrid-cut";this.fh.paste="oj-datagrid-paste";this.fh.discontiguousSelection="oj-datagrid-discontiguousSelection";this.attributes={};this.attributes.key="data-oj-key";this.attributes.resizable="data-oj-resizable";
this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander="data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";this.attributes.container=b.Components.hn;this.attributes.extent="data-oj-extent";this.attributes.start="data-oj-start";this.attributes.depth="data-oj-depth";this.attributes.level="data-oj-level";this.attributes.tabMod="data-oj-tabmod"};o_("DataGridResources",b.Th,b);b.Th.prototype.w3=function(){return"rtl"===this.tpa?
!0:!1};b.b.g("DataGridResources.prototype.isRTLMode",{w3:b.Th.prototype.w3});b.Th.prototype.X2=function(a,b){return this.Upa(a,b)};b.b.g("DataGridResources.prototype.getTranslatedText",{X2:b.Th.prototype.X2});b.Th.prototype.vN=function(a){return null!=a?this.Pa[a]:null};b.b.g("DataGridResources.prototype.getMappedStyle",{vN:b.Th.prototype.vN});b.Th.prototype.$D=function(a){return null!=a?this.fh[a]:null};b.b.g("DataGridResources.prototype.getMappedCommand",{$D:b.Th.prototype.$D});b.Th.prototype.uN=
function(a){return null!=a?this.attributes[a]:null};b.b.g("DataGridResources.prototype.getMappedAttribute",{uN:b.Th.prototype.uN});b.ya("oj.ojDataGrid",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{bandingInterval:{row:0,column:0},data:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,selectionMode:null,dnd:{reorder:{row:"disable"}},scrollPolicy:"auto",selection:[],header:{row:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",
style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},resize:null,sort:null,optionChange:null,ready:null,scroll:null},_ComponentCreate:function(){this._super();this.root=this.element[0];this.oh=this.root.getAttribute("id");this.grid=new a;this.grid.setVisibility(a.VISIBILITY_STATE_RENDER);f(this.root).addClass("oj-datagrid oj-component");this.BO={data:"all",header:["className","renderer",
"style","template"]}},hf:function(){var a=this;this.Ek(this.root);f(this.root).empty();this._super();this.xr=new b.Th(this.ac(),this.PB.bind(a));this.z_();this.Rt();null!=this.jc&&(this.lA(),this.grid.SetDataSource(this.jc));this.grid.SetOptions(this.options);this.grid.SetResources(this.xr);this.grid.SetCreateContextCallback(this.yha.bind(a));this.grid.SetRemoveCallback(this.aL.bind(a));this.grid.addListener("resize",function(b){a._trigger("resize",b.event,b.ui)});this.grid.addListener("select",function(b){a.option("selection",
b.ui.selection,{_context:{originalEvent:b.event,Za:!0},changed:!0})});this.grid.addListener("sort",function(b){a._trigger("sort",b.event,b.ui)});this.grid.addListener("keydown",function(b){a._trigger("keydown",b.event,b.ui)});this.grid.addListener("active",function(b){a._trigger("active",b.event,b.ui)});this.grid.addListener("ready",function(){a._trigger("ready",null,{})});this.grid.addListener("scroll",function(b){a._trigger("scroll",b.event,b.ui)});this.nx();null!=this.jc&&this.tj(this.root)},refresh:function(){this._super();
this.Ek(this.root);f(this.root).empty();!0===this.Yla&&(this.options.contextMenu=null);this.z_();null!=this.jc&&(this.jc instanceof b.$a&&(this.jc.Le(),this.jc.Init()),this.lA(),this.grid.SetDataSource(this.jc));this.grid.SetOptions(this.options);this.grid.SetResources(this.xr);this.grid.getVisibility()!=a.VISIBILITY_STATE_RENDER&&this.grid.setVisibility(a.VISIBILITY_STATE_REFRESH);this.nx();null!=this.jc&&this.tj(this.root)},_destroy:function(){null!=this.jc&&this.jc.Le&&this.jc.Le();this.grid.destroy();
this.Ek(this.root);f(this.root).empty()},_setOptions:function(a,b){var e;this.jc?(e=this.Uka(a),this._super(a,b),e?this.refresh():this.grid.UpdateOptions(a)):(this._super(a,b),null!=a.data&&this.refresh())},ml:function(){this._super();this.nx()},ll:function(){this._super();this.grid.getVisibility()===a.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},gn:function(){this._super();this.nx()},ii:function(){this._super();this.grid.getVisibility()===a.VISIBILITY_STATE_VISIBLE&&
this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},Uka:function(a){var c,e,g,f,k,l;g=!1;for(e in a)if(e in this.BO)if("data"===e){g=!0;break}else if("header"==e)for(f in a.header){if("column"==f||"row"==f||"cell"==f)for(k in a.header[f]){for(c=0;c<this.BO.header.length;c++)if(k==this.BO.header[c])for(l in this.options.header[f])if(l==k&&a.header[f][k]!=this.options.header[f][k]){g=!0;break}if(g)break}if(g)break}else for(l in this.options)if(l==e&&!b.b.gh(a[e],this.options[l])){g=!0;break}return g},
jC:function(a,b){return this.options.header[a]&&this.options.header[a].resizable?"disable"!==this.options.header[a].resizable[b]:!1},dY:function(a){return this.options.header[a]?"disable"!==this.options.header[a].sortable:!1},lA:function(){var a,c,e=null,g=null,h=null,k=null,l,m;a=this;if(null==this.options.contextMenu){if(null!=this.jc){c=f("\x3cul\x3e");c.css("display","none").attr("id",this.oh+"contextmenu");f(this.root).append(c);if(this.jC("column","width")||this.jC("column","height")||this.jC("row",
"width")||this.jC("row","height"))e=this.ni("resize");l=this.jc.getCapability("sort");!this.dY("column")||"column"!==l&&"full"!==l||(g=this.ni("sortCol"));!this.dY("row")||"row"!==l&&"full"!==l||(g=null!=g?g.add(this.ni("sortRow")):this.ni("sortRow"));if("enable"===this.options.dnd.reorder.row)switch(this.jc.getCapability("move")){case "none":break;default:k=this.cg("cut").add(this.cg("paste"))}this.nj()&&b.v.Od()&&(this.UA=!1,h=this.cg("discontiguousSelection"));if(null!=e||null!=g||null!=k||null!=
h)c.append(e).append(g).append(k).append(h),c.ojMenu(),this.Yla=!0,this._setOption("contextMenu","#"+c.attr("id")),c.on("ojselect",this.lj.bind(this))}}else null==this.vK&&(this.vK=[]),c=f(this.options.contextMenu),e=c.find("[data-oj-command]"),m=[],e.each(function(){var b;b=f(this).children("a");if(0===b.length||-1!=a.vK.indexOf(b.get(0)))b=f(this).attr("data-oj-command").split("-"),b=a.ni(b[b.length-1]),f(this).replaceWith(b),m.push(b.children("a").get(0))}),this.vK=m,c.data("oj-ojMenu")&&c.ojMenu("refresh"),
c.on("ojselect",this.lj.bind(this))},ni:function(a){if("resize"===a)return this.cg("resize").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.cg("resizeWidth")).append(this.cg("resizeHeight")));if("sortCol"===a)return this.cg("sortCol").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.cg("sortColAsc")).append(this.cg("sortColDsc")));if("sortRow"===a)return this.cg("sortRow").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.cg("sortRowAsc")).append(this.cg("sortRowDsc")));if(-1!=Object.keys(this.xr.fh).indexOf(a))return f(this.cg(a))},
cg:function(a){var b=f("\x3cli\x3e\x3c/li\x3e");b.attr("data-oj-command",this.Gl(a));b.append(this.YG(a));return b},YG:function(a){var b="label"+a.charAt(0).toUpperCase()+a.slice(1);"discontiguousSelection"===a&&(b="labelEnableNonContiguous");return f('\x3ca href\x3d"#"\x3e\x3c/a\x3e').text(this.PB(b))},EV:function(){return f(this.options.contextMenu).get(0)},PB:function(a,b){return this.A(a,b)},qfa:function(){var a=f("#"+this.oh+"spinner").ojInputNumber("option","value");f("#"+this.oh+"dialog").ojDialog("close");
this.grid.handleContextMenuReturn(this.mu,this.Jj,a);this.mu.target.focus()},w$:function(a,b){var e,g,h,k,l;e=f("#"+this.oh+"dialog");h=f("#"+this.oh+"spinner");0===e.length||0===h.length?(e=f("\x3cdiv\x3e"),e.attr("id",this.oh+"dialog"),e.attr("title",a),g=f('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),k=f('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),e.append(g).append(k),h=f('\x3cinput id\x3d"'+this.oh+'spinner"/\x3e'),l=f('\x3cbutton id\x3d"'+this.oh+'dialogsubmit"/\x3e'),g.append(h),
k.append(l),f(this.root).append(e),l.ojButton({Q:"ojButton",label:this.PB("labelResizeDialogSubmit")}),l.on("click",this.qfa.bind(this)),h.ojInputNumber({Q:"ojInputNumber",max:1E3,min:20,step:1,value:b}),e.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",of:f(this.root)}})):(h.ojInputNumber("option","value",b),f("#"+this.oh+"dialog").ojDialog("open"))},lj:function(a,b){var e;this.Jj=b.item.attr("data-oj-command");this.Jj===this.Gl("sortColAsc")||
this.Jj===this.Gl("sortColDsc")||this.Jj===this.Gl("cut")||this.Jj===this.Gl("paste")?this.grid.handleContextMenuReturn(this.mu,this.Jj,null):this.Jj===this.Gl("resizeWidth")||this.Jj===this.Gl("resizeHeight")?(e=f(this.mu.target).closest("."+this.Zd("cell")),0==e.length&&(e=f(this.mu.target).closest("."+this.Zd("headercell"))),0<e.length&&(e=this.Jj===this.Gl("resizeWidth")?e.outerWidth():e.outerHeight(),this.w$(b.item.text(),e))):this.Jj===this.Gl("discontiguousSelection")&&(this.UA=!this.UA,this.grid.handleContextMenuReturn(this.mu,
this.Jj,this.UA),e=this.UA?"labelDisableNonContiguous":"labelEnableNonContiguous",b.item.children().first().text(this.PB(e)))},lf:function(a,b,e){this.grid.handleContextMenuGesture(b,e,this.qaa.bind(this))},qaa:function(a,b,e){var g;null!=a&&(this.mu=b.originalEvent,g=a.launcher,a=a.capabilities,this.nha(a),g="keyboard"===e?{position:{of:g},launcher:f(g)}:{launcher:f(g)},this.nf(b,e,g))},t9:function(a){var b;b=f(this.EV());b.find("[data-oj-command\x3d"+a+"]").hasClass("oj-disabled")||b.find("[data-oj-command\x3d"+
a+"]").addClass("oj-disabled")},fja:function(a){f(this.EV()).find("[data-oj-command\x3d"+a+"]").removeClass("oj-disabled")},nha:function(a){var b,e;for(b in a)a.hasOwnProperty(b)&&(e=this.xr.$D(b),"disable"===a[b]?this.t9(e):this.fja(e))},oca:function(a){var b;b=a.parent();a=a.index();return{rowIndex:b.index(),columnIndex:a}},Iqa:function(a){var b;b=this.Sda().children().eq(0).children().eq(a.rowIndex+1);a=this.Lca().children().eq(0).children().eq(a.columnIndex);return{rowHeader:b,columnHeader:a}},
MV:function(){return f(this.root)},Lca:function(){return f("#"+this.oh+"\\:columnHeader")},Sda:function(){return f("#"+this.oh+"\\:rowHeader")},Rca:function(){return f("#"+this.oh+"\\:databody ."+this.Zd("row"))},z_:function(){this.jc=null!=this.options.data?this.options.data:null},Rt:function(){var a=this.options.selection;null!=a&&this.grid.SetSelection(a)},yha:function(a){a.component=b.Components.sg(this.element,"ojDataGrid")},PC:function(a){this.grid.SetAccessibleContext(a)},Ek:function(a){a&&
this.De&&b.v.Qh(a,this.De)},tj:function(a){a&&(null==this.De&&(this.De=this.Se.bind(this)),b.v.eh(a,this.De))},Se:function(a,b){0<a&&0<b&&(this.nx(),this.grid.HandleResize(a,b))},getNodeBySubId:function(a){var b,e,g,h;if(null==a)return this.element?this.element[0]:null;b=a.subId;if("oj-datagrid-cell"===b)b=a.rowIndex-this.grid.getStartRow(),a=a.columnIndex-this.grid.getStartColumn(),g=this.Rca().eq(b).children().eq(a);else if("oj-datagrid-sort-icon"===b||"oj-datagrid-sort-ascending"===b||"oj-datagrid-sort-descending"===
b||"oj-datagrid-header"===b){h=a.axis;g=a.index;a=null==a.level?0:a.level;"column"===h?e=this.OV(g,a,f("#"+this.oh+"\\:columnHeader"),this.grid.getStartColumnHeader()):"row"===h&&(e=this.OV(g,a,f("#"+this.oh+"\\:rowHeader"),this.grid.getStartRowHeader()));if(null==e)return null;if("oj-datagrid-sort-icon"===b)return e.children("."+this.Zd("sortcontainer")).children().get(0);g="oj-datagrid-sort-ascending"===b?e.find("."+this.Zd("sortascending")):"oj-datagrid-sort-descending"===b?e.find("."+this.Zd("sortdescending")):
e}return null!=g&&0<g.length?g[0]:null},getSubIdByNode:function(a){var b,e,g;b=f(a).closest("."+this.Zd("cell"));if(0<b.length)return a=this.oca(b),{subId:"oj-datagrid-cell",rowIndex:a.rowIndex+this.grid.getStartRow(),columnIndex:a.columnIndex+this.grid.getStartColumn()};e=f(a).closest("."+this.Zd("headercell"));return 0<e.length?(g=e.hasClass(this.Zd("colheadercell"))?"column":"row",b=this.hda(e),e=this.ida(e),a=f(a).hasClass(this.Zd("sortascending"))?"oj-datagrid-sort-ascending":f(a).hasClass(this.Zd("sortdescending"))?
"oj-datagrid-sort-descending":"oj-datagrid-header",{subId:a,index:b,axis:g,level:e}):null},Zd:function(a){return this.xr.vN(a)},In:function(a){return this.xr.uN(a)},Gl:function(a){return this.xr.$D(a)},zga:function(){return null!=this.root.offsetParent?!0:!1},nx:function(){var b=this.grid.getVisibility();this.zga()?(b===a.VISIBILITY_STATE_RENDER?this.grid.render(this.root):b===a.VISIBILITY_STATE_REFRESH&&this.grid.refresh(this.root),this.grid.setVisibility(a.VISIBILITY_STATE_VISIBLE)):b===a.VISIBILITY_STATE_VISIBLE&&
this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},OV:function(a,b,e,g){if(0>b)return null;if(e.children().first().children().last().hasClass(this.Zd("headercell")))return e.children().first().children("."+this.Zd("headercell")).eq(a-g);e=this.NV(a,b,0,e.children().first().children());if(null==e)return null;if(b<=parseInt(e.attr(this.In("level")),10)+parseInt(e.children().eq(0).attr(this.In("depth")),10)-1)return e.children().eq(0);g=parseInt(e.attr(this.In("start")),10);a=a-g+1;return e.children().eq(a)},
NV:function(a,b,e,g){var f,k,l,m;if(null==g.eq(1)||g.eq(1).hasClass(this.Zd("headercell")))return b===e?g.eq(0).parent():null;f=g.parent().parent();for(l=f.hasClass(this.Zd("colheader"))||f.hasClass(this.Zd("rowheader"))?0:1;l<g.length;l++)if(f=parseInt(g.eq(l).attr(this.In("start")),10),k=parseInt(g.eq(l).attr(this.In("extent")),10),m=parseInt(g.eq(l).children().eq(0).attr(this.In("depth")),10),a>=f&&a<f+k)return b<e+m?g.eq(l):this.NV(a,b,e+m,g.eq(l).children());return null},hda:function(a){var b;
if(a.parent().hasClass(this.Zd("groupingcontainer"))){b=parseInt(a.parent().attr(this.In("start")),10);if(a.get(0)===a.parent().children(":first").get(0))return b;b--}else b=a.hasClass(this.Zd("rowheadercell"))?this.grid.getStartRowHeader():this.grid.getStartColumnHeader();return b+=a.index()},ida:function(a){var b;return a.parent().hasClass(this.Zd("groupingcontainer"))?(b=parseInt(a.parent().attr(this.In("level")),10),a.get(0)===a.parent().children(":first").get(0)?b:b+1):0},nj:function(){return null==
this.options.selectionMode||"multiple"!==this.options.selectionMode.row&&"multiple"!==this.options.selectionMode.cell?!1:!0},aL:function(a){f(a).remove()},scrollTo:function(a){this.grid.scroll(a)}})});