/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore","jqueryui-amd/draggable","jqueryui-amd/mouse"],function(b,f){(function(){b.ya("oj.ojResizable",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,start:null,
stop:null},zK:function(a){return parseInt(a,10)||0},Ce:function(a){return!isNaN(parseInt(a,10))},jX:function(a,b){if("hidden"===f(a).css("overflow"))return!1;var c=b&&"left"===b?"scrollLeft":"scrollTop",e=!1;if(0<a[c])return!0;a[c]=1;e=0<a[c];a[c]=0;return e},_ComponentCreate:function(){this._super();var a,b,c,e,g,h=this;a=this.options;b=this.element.mouse.bind(this.element);b();this.tm=b("instance");this.tm._mouseCapture=function(a){return h.Aha(a)};this.tm._mouseStart=function(a){return h.Dha(a)};
this.tm._mouseDrag=function(a){return h.Bha(a)};this.tm._mouseStop=function(a){return h.dx(a)};this.element.addClass("oj-resizable");f.extend(this,{tE:this.element,EC:[],rk:null});this.handles=a.handles||(f(".oj-resizable-handle",this.element).length?{Gra:".oj-resizable-n",tra:".oj-resizable-e",Pra:".oj-resizable-s",Of:".oj-resizable-w",Rra:".oj-resizable-se",Tra:".oj-resizable-sw",Hra:".oj-resizable-ne",Jra:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&
(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},b=0;b<a.length;b++)c=f.trim(a[b]),g="oj-resizable-"+c,e=f("\x3cdiv class\x3d'oj-resizable-handle "+g+"'\x3e\x3c/div\x3e"),this.handles[c]=".oj-resizable-"+c,this.element.append(e);this.Aja=function(){for(var a in this.handles)this.handles[a].constructor===String&&(this.handles[a]=this.element.children(this.handles[a]).first().show())};this.Aja();this.Bfa=f(".oj-resizable-handle",this.element);this.Bfa.mouseover(function(){h.w4||
(this.className&&(e=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),h.axis=e&&e[1]?e[1]:"se")});this.tm._mouseInit()},_destroy:function(){this.tm&&this.tm._mouseDestroy();try{this.tm.destroy(),this.tm=null}catch(a){}f(this.tE).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove();return this},Aha:function(a){var b,c,e=!1;for(b in this.handles)if(c=f(this.handles[b])[0],
c===a.target||f.contains(c,a.target))e=!0;return!this.options.disabled&&e},Dha:function(a){var b,c,e;e=this.options;b=this.element.position();var g=this.element;this.w4=!0;/absolute/.test(g.css("position"))?g.css({position:"absolute",top:g.css("top"),left:g.css("left")}):g.is(".oj-draggable")&&g.css({position:"absolute",top:b.top,left:b.left});this.Bja();b=this.zK(this.helper.css("left"));c=this.zK(this.helper.css("top"));e.containment&&(b+=f(e.containment).scrollLeft()||0,c+=f(e.containment).scrollTop()||
0);this.offset=this.helper.offset();this.position={left:b,top:c};this.size={width:g.width(),height:g.height()};this.Mj={width:g.width(),height:g.height()};this.So={left:b,top:c};this.FE={width:g.outerWidth()-g.width(),height:g.outerHeight()-g.height()};this.Xoa={left:a.pageX,top:a.pageY};this.Gk=this.Mj.width/this.Mj.height||1;e=f(".oj-resizable-"+this.axis).css("cursor");f("body").css("cursor","auto"===e?this.axis+"-resize":e);g.addClass("oj-resizable-resizing");this.SK("start",a);this.S9(a);this.oaa(a);
return!0},Bha:function(a){var b,c=this.helper,e={},g=this.Xoa;b=a.pageX-g.left||0;var g=a.pageY-g.top||0,h=this.Ch[this.axis];this.Gu={top:this.position.top,left:this.position.left};this.Hu={width:this.size.width,height:this.size.height};if(!h)return!1;b=h.apply(this,[a,b,g]);this.Wla(a.shiftKey);a.shiftKey&&(b=this.Vla(b,a));b=this.Oja(b,a);this.Ola(b);this.SK("resize",a);this.R9(a,this.ui());this.naa(a,this.ui());this.position.top!==this.Gu.top&&(e.top=this.position.top+"px");this.position.left!==
this.Gu.left&&(e.left=this.position.left+"px");this.size.width!==this.Hu.width&&(e.width=this.size.width+"px");this.size.height!==this.Hu.height&&(e.height=this.size.height+"px");c.css(e);!this.rk&&this.EC.length&&this.Bia();f.isEmptyObject(e)||this._trigger("resize",a,this.ui());return!1},dx:function(a){this.w4=!1;f("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.SK("stop",a);this.T9(a);this.paa(a);return!1},Wla:function(a){var b,c,e,f;f=this.options;f={minWidth:this.Ce(f.minWidth)?
f.minWidth:0,maxWidth:this.Ce(f.maxWidth)?f.maxWidth:Infinity,minHeight:this.Ce(f.minHeight)?f.minHeight:0,maxHeight:this.Ce(f.maxHeight)?f.maxHeight:Infinity};a&&(a=f.minHeight*this.Gk,c=f.minWidth/this.Gk,b=f.maxHeight*this.Gk,e=f.maxWidth/this.Gk,a>f.minWidth&&(f.minWidth=a),c>f.minHeight&&(f.minHeight=c),b<f.maxWidth&&(f.maxWidth=b),e<f.maxHeight&&(f.maxHeight=e));this.Zla=f},Ola:function(a){this.offset=this.helper.offset();this.Ce(a.left)&&(this.position.left=a.left);this.Ce(a.top)&&(this.position.top=
a.top);this.Ce(a.height)&&(this.size.height=a.height);this.Ce(a.width)&&(this.size.width=a.width)},Vla:function(a){var b=this.position,c=this.size,e=this.axis;this.Ce(a.height)?a.width=a.height*this.Gk:this.Ce(a.width)&&(a.height=a.width/this.Gk);"sw"===e&&(a.left=b.left+(c.width-a.width),a.top=null);"nw"===e&&(a.top=b.top+(c.height-a.height),a.left=b.left+(c.width-a.width));return a},Oja:function(a){var b=this.Zla,c=this.axis,e=this.Ce(a.width)&&b.maxWidth&&b.maxWidth<a.width,f=this.Ce(a.height)&&
b.maxHeight&&b.maxHeight<a.height,h=this.Ce(a.width)&&b.minWidth&&b.minWidth>a.width,k=this.Ce(a.height)&&b.minHeight&&b.minHeight>a.height,l=this.So.left+this.Mj.width,m=this.position.top+this.size.height,n=/sw|nw|w/.test(c),c=/nw|ne|n/.test(c);h&&(a.width=b.minWidth);k&&(a.height=b.minHeight);e&&(a.width=b.maxWidth);f&&(a.height=b.maxHeight);h&&n&&(a.left=l-b.minWidth);e&&n&&(a.left=l-b.maxWidth);k&&c&&(a.top=m-b.minHeight);f&&c&&(a.top=m-b.maxHeight);a.width||a.height||a.left||!a.top?a.width||
a.height||a.top||!a.left||(a.left=null):a.top=null;return a},Bia:function(){if(this.EC.length){var a,b,c,e,f,h=this.helper||this.element;for(a=0;a<this.EC.length;a++){f=this.EC[a];if(!this.iu)for(this.iu=[],c=[f.css("borderTopWidth"),f.css("borderRightWidth"),f.css("borderBottomWidth"),f.css("borderLeftWidth")],e=[f.css("paddingTop"),f.css("paddingRight"),f.css("paddingBottom"),f.css("paddingLeft")],b=0;b<c.length;b++)this.iu[b]=(parseInt(c[b],10)||0)+(parseInt(e[b],10)||0);f.css({height:h.height()-
this.iu[0]-this.iu[2]||0,width:h.width()-this.iu[1]-this.iu[3]||0})}}},Bja:function(){this.element.offset();this.helper=this.element},Ch:{e:function(a,b){return{width:this.Mj.width+b}},w:function(a,b){return{left:this.So.left+b,width:this.Mj.width-b}},n:function(a,b,c){return{top:this.So.top+c,height:this.Mj.height-c}},s:function(a,b,c){return{height:this.Mj.height+c}},se:function(a,b,c){return f.extend(this.Ch.s.apply(this,arguments),this.Ch.e.apply(this,[a,b,c]))},sw:function(a,b,c){return f.extend(this.Ch.s.apply(this,
arguments),this.Ch.w.apply(this,[a,b,c]))},ne:function(a,b,c){return f.extend(this.Ch.n.apply(this,arguments),this.Ch.e.apply(this,[a,b,c]))},nw:function(a,b,c){return f.extend(this.Ch.n.apply(this,arguments),this.Ch.w.apply(this,[a,b,c]))}},SK:function(a,b){"resize"!==a&&this._trigger(a,b,this.ui())},S9:function(){function a(a){f(a).each(function(){var a=f(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),
10)})})}var b=this.options;"object"!==typeof b.alsoResize||b.alsoResize.parentNode?a(b.alsoResize):b.alsoResize.length?(b.alsoResize=b.alsoResize[0],a(b.alsoResize)):f.each(b.alsoResize,function(b){a(b)})},R9:function(a,b){function c(a,c){f(a).each(function(){var a=f(this),e=f(this).data("oj-resizable-alsoresize"),g={};f.each(c&&c.length?c:a.parents(b.tE[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(e[b]||0)+(k[b]||0);c&&0<=c&&(g[b]=c||null)});a.css(g)})}var e=
this.options,g=this.Mj,h=this.So,k={height:this.size.height-g.height||0,width:this.size.width-g.width||0,top:this.position.top-h.top||0,left:this.position.left-h.left||0};"object"!==typeof e.alsoResize||e.alsoResize.nodeType?c(e.alsoResize,null):f.each(e.alsoResize,function(a,b){c(a,b)})},T9:function(){f(this).removeData("oj-resizable-alsoresize")},oaa:function(){var a,b,c,e,g,h=this,k=h.element;c=h.options.containment;if(k=c instanceof f?c.get(0):/parent/.test(c)?k.parent().get(0):c)h.HD=f(k),/document/.test(c)||
c===document?(h.ID={left:0,top:0},h.z1={left:0,top:0},h.To={element:f(document),left:0,top:0,width:f(document).width(),height:f(document).height()||document.body.parentNode.scrollHeight}):(a=f(k),b=[],f(["Top","Right","Left","Bottom"]).each(function(c,e){b[c]=h.zK(a.css("padding"+e))}),h.ID=a.offset(),h.z1=a.position(),h.A1={height:a.innerHeight()-b[3],width:a.innerWidth()-b[1]},c=h.ID,e=h.A1.height,g=h.A1.width,g=h.jX(k,"left")?k.scrollWidth:g,e=h.jX(k)?k.scrollHeight:e,h.To={element:k,left:c.left,
top:c.top,width:g,height:e})},naa:function(a,b){var c,e,f,h;c=this.options;e=this.ID;h=this.position;var k=a.shiftKey;f={top:0,left:0};var l=this.HD,m=!0;l[0]!==document&&/static/.test(l.css("position"))&&(f=e);h.left<(this.rk?e.left:0)&&(this.size.width+=this.rk?this.position.left-e.left:this.position.left-f.left,k&&(this.size.height=this.size.width/this.Gk,m=!1),this.position.left=c.helper?e.left:0);h.top<(this.rk?e.top:0)&&(this.size.height+=this.rk?this.position.top-e.top:this.position.top,k&&
(this.size.width=this.size.height*this.Gk,m=!1),this.position.top=this.rk?e.top:0);this.offset.left=this.To.left+this.position.left;this.offset.top=this.To.top+this.position.top;c=Math.abs((this.rk?this.offset.left-f.left:this.offset.left-e.left)+this.FE.width);e=Math.abs((this.rk?this.offset.top-f.top:this.offset.top-e.top)+this.FE.height);f=this.HD.get(0)===this.element.parent().get(0);h=/relative|absolute/.test(this.HD.css("position"));f&&h&&(c-=Math.abs(this.To.left));c+this.size.width>=this.To.width&&
(this.size.width=this.To.width-c,k&&(this.size.height=this.size.width/this.Gk,m=!1));e+this.size.height>=this.To.height&&(this.size.height=this.To.height-e,k&&(this.size.width=this.size.height*this.Gk,m=!1));m||(this.position.left=b.Gu.left,this.position.top=b.Gu.top,this.size.width=b.Hu.width,this.size.height=b.Hu.height)},paa:function(){var a=this.options,b=this.ID,c=this.z1,e=this.HD,g=f(this.helper),h=g.offset(),k=g.outerWidth()-this.FE.width,g=g.outerHeight()-this.FE.height;this.rk&&!a.animate&&
/relative/.test(e.css("position"))&&f(this).css({left:h.left-c.left-b.left,width:k,height:g});this.rk&&!a.animate&&/static/.test(e.css("position"))&&f(this).css({left:h.left-c.left-b.left,width:k,height:g})},ui:function(){return{tE:this.tE,element:this.element,helper:this.helper,position:this.position,size:this.size,Mj:this.Mj,So:this.So,Hu:this.Hu,Gu:this.Gu}}})})();(function(){b.ya("oj.ojDialog",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",
initialVisibility:"hide",modality:"modal",position:{my:"center",at:"center",of:window,collision:"fit",Wra:function(a){var b=f(this).css(a).offset().top;0>b&&f(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_ComponentCreate:function(){this._super();this.Woa={display:this.element[0].style.display,width:this.element[0].style.width,height:this.element[0].style.height};
this.So={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.tO=this.element.attr("title");this.options.title=this.options.title||this.tO;this.fba();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.Nb);this.fz=!1;if(this.element.find(".oj-dialog").length){var a=this;this.element.find(".oj-dialog-header").each(function(b,c){var e=f(c);if(!e.closest(".oj-dialog-body").length)return a.po=e,a.fz=!0,
!1})}else this.po=this.element.find(".oj-dialog-header"),this.po.length&&(this.fz=!0);this.fz?(this.Vaa(this.po),this.po.prependTo(this.Nb),"icon"===this.options.cancelBehavior&&(this.KA(this.po),this.Yx=this.po.find(".oj-dialog-title"),this.Yx.length&&this.Yx.insertAfter(this.Zo))):this.eba();this.Im=this.element.children(".oj-dialog-footer");this.Uaa(this.Im);this.Im.length&&(this.Im.addClass("oj-helper-clearfix"),this.Im.appendTo(this.Nb));"title-bar"===this.options.dragAffordance&&f.fn.draggable&&
this.Ct();this.Sn=!1},pQ:function(){"show"===this.options.initialVisibility&&this.open()},_destroy:function(){this.pba&&window.clearTimeout(this.pba);this.isOpen()&&this.Rp();this.Vl&&(this.Vl("instance")&&this.Vl("destroy"),this.Vl=null);this.Im.length&&(this.Im.removeClass("oj-helper-clearfix"),f("#"+this.WY).replaceWith(this.Im));this.TA();if(this.fz){var a=this.Nb.find(".oj-dialog-header");a&&f("#"+this.XY).replaceWith(a)}this.o5&&(this.o5.remove(),this.o5=null);this.element.removeUniqueId().removeClass("oj-dialog-content oj-dialog-default-content").css(this.Woa);
this.Nb&&this.Nb.stop(!0,!0);this.element.unwrap();this.tO&&this.element.attr("title",this.tO);this.Jm&&(this.Jm.remove(),this.Jm=null);delete this.sj;delete this.Sn;this._super()},widget:function(){return this.Nb},disable:f.noop,enable:f.noop,close:function(a){if(this.isOpen()&&(!1!==this._trigger("beforeClose",a)||this.Pw)){this.Sn=!1;this.tca=null;this.opener.filter(":focusable").focus().length||f(this.document[0].activeElement).blur();var d={};d[b.N.Qa.cf]=this.Nb;b.N.le().close(d);this._trigger("close",
a)}},isOpen:function(){return this.Sn},open:function(a){if(!1!==this._trigger("beforeOpen",a)){if(!this.isOpen()){this.Sn=!0;this.opener=f(this.document[0].activeElement);"resizable"===this.options.resizeBehavior&&this.xY();a="rtl"===this.ac();a=b.nc.xg(this.options.position,a);var d={};d[b.N.Qa.cf]=this.Nb;d[b.N.Qa.Zu]=this.opener;d[b.N.Qa.cv]=a;d[b.N.Qa.Wh]=this.options.modality;d[b.N.Qa.dp]=this.ft();d[b.N.Qa.Sm]="oj-dialog-layer";d[b.N.Qa.Rm]=b.N.Rm.xF;b.N.le().open(d);this._trigger("open")}this.oV()}},
refresh:function(){this._super()},oV:function(){var a=this.tca;a&&0<a.length&&b.v.Ho(this.Nb[0],a[0])||(a||(a=this.element.find("[autofocus]")),a.length||(a=this.element.find(":tabbable")),a.length||this.Im.length&&(a=this.Im.find(":tabbable")),a.length||this.ZO&&(a=this.ZO.filter(":tabbable")),a.length||(a=this.Nb),a.eq(0).focus(),this._trigger("focus"))},_keepFocus:function(a){a.preventDefault();a=this.document[0].activeElement;this.Nb[0]===a||f.contains(this.Nb[0],a)||this.oV()},Ce:function(a){return!isNaN(parseInt(a,
10))},fba:function(){this.aY=!1;this.element.uniqueId();this.kI=this.element.attr("id");this.ema="ojDialogWrapper-"+this.kI;this.Nb=f("\x3cdiv\x3e");this.Nb.addClass("oj-dialog oj-component").hide().attr({tabIndex:-1,role:this.options.role,id:this.ema});this.Nb.insertBefore(this.element);this._on(this.Nb,{keyup:function(){},keydown:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===f.ui.keyCode.ESCAPE)a.preventDefault(),a.stopImmediatePropagation(),
this.close(a);else if(a.keyCode===f.ui.keyCode.TAB&&"modeless"!==this.options.modality){var b=this.Nb.find(":tabbable"),c=b.filter(":first"),e=b.filter(":last");a.shiftKey?a.shiftKey&&(a.target===c[0]||a.target===this.Nb[0]?(e.focus(),a.preventDefault()):(c=b.index(document.activeElement),1==c&&b[0]&&(b[0].focus(),a.preventDefault()))):a.target===e[0]||a.target===this.Nb[0]?(c.focus(),a.preventDefault()):(c=b.index(document.activeElement),0==c&&b[1]&&(b[1].focus(),a.preventDefault()))}}});this.element.find("[aria-describedby]").length||
this.Nb.attr({"aria-describedby":this.element.uniqueId().attr("id")})},TA:function(){this.Zo&&(this.Zo.remove(),this.ZO=this.Zo=null)},KA:function(a){this.Zo=f("\x3cdiv\x3e").addClass("oj-dialog-header-close-wrapper").attr("tabindex","1").attr("aria-label","close").attr("role","button").appendTo(a);this.ZO=f("\x3cspan\x3e").addClass("oj-component-icon oj-clickable-icon oj-dialog-close-icon").attr("alt","close icon").prependTo(this.Zo);this._on(this.Zo,{click:function(a){a.preventDefault();a.stopImmediatePropagation();
this.close(a)},mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active")},keyup:function(a){if(a.keyCode&&a.keyCode===f.ui.keyCode.SPACE||a.keyCode===f.ui.keyCode.ENTER)a.preventDefault(),a.stopImmediatePropagation(),this.close(a)}})},eba:function(){var a;this.Jm=f("\x3cdiv\x3e").addClass("oj-dialog-header oj-helper-clearfix").prependTo(this.Nb);
this._on(this.Jm,{mousedown:function(a){f(a.target).closest(".oj-dialog-close-icon")||this.Nb.focus()}});"icon"===this.options.cancelBehavior&&this.KA(this.Jm);a=f("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").appendTo(this.Jm);this.E0(a);this.Nb.attr({"aria-labelledby":a.attr("id")})},E0:function(a){this.options.title||a.html("\x26#160;");a.text(this.options.title)},Ct:function(){function a(a){return{position:a.position,offset:a.offset}}var b=this,c=this.options;this.Nb.draggable({nra:!1,
cancel:".oj-dialog-content, .oj-dialog-header-close",handle:".oj-dialog-header",containment:"document",start:function(c,g){f(this).addClass("oj-dialog-dragging");b.ZS();b._trigger("dragStart",c,a(g))},drag:function(c,f){b._trigger("drag",c,a(f))},stop:function(e,g){c.position=[g.position.left-b.document.scrollLeft(),g.position.top-b.document.scrollTop()];f(this).removeClass("oj-dialog-dragging");b.L0();b._trigger("dragStop",e,a(g))}});this.Nb.addClass("oj-draggable")},xY:function(){function a(a){return{originalPosition:a.So,
originalSize:a.Mj,position:a.position,size:a.size}}var b=this;this.Nb.css("position");this.Vl=this.Nb.ojResizable.bind(this.Nb);this.Vl({cancel:".oj-dialog-content",containment:"document",handles:"n,e,s,w,se,sw,ne,nw",start:function(c,e){b.aY=!0;f(this).addClass("oj-dialog-resizing");b.ZS();b._trigger("resizeStart",c,a(e))},resize:function(c,e){b._trigger("resize",c,a(e))},stop:function(c,e){b.aY=!1;f(this).removeClass("oj-dialog-resizing");b.L0();b._trigger("resizeStop",c,a(e))}})},MK:function(){var a=
"rtl"===this.ac(),a=b.nc.xg(this.options.position,a);this.Nb.position(a);this.YY()},YY:function(){b.N.le().YO(this.Nb,b.N.xc.Um)},_setOption:function(a,d,c){var e;e=this.Nb;if("disabled"!==a)switch(this._super(a,d,c),a){case "dragAffordance":(a=e.hasClass("oj-draggable"))&&"none"===d&&(e.draggable("destroy"),this.Nb.removeClass("oj-draggable"));a||"title-bar"!==d||this.Ct();break;case "position":this.MK();break;case "resizeBehavior":e=!1;this.Vl&&(e=!0);e&&"resizable"!=d&&(this.Vl("instance")&&this.Vl("destroy"),
this.Vl=null);e||"resizable"!==d||this.xY();break;case "title":this.E0(this.Jm.find(".oj-dialog-title"));break;case "role":e.attr("role",d);break;case "modality":this.isOpen()&&(e={},e[b.N.Qa.cf]=this.Nb,e[b.N.Qa.Wh]=d,b.N.le().ju(e));break;case "cancelBehavior":"none"===d||"escape"===d?this.TA():"icon"===d&&(this.fz?(this.TA(),this.KA(this.po),this.Yx=this.po.find(".oj-dialog-title"),this.Yx.length&&this.Yx.insertAfter(this.Zo)):(this.TA(),this.KA(this.Jm),this.U4=this.Jm.find(".oj-dialog-title"),
this.U4.length&&this.U4.insertAfter(this.Zo)))}},ZS:function(){this.GN=this.document.find("iframe").map(function(){var a=f(this),b=a.offset();return f("\x3cdiv\x3e").css({width:a.outerWidth(),height:a.outerHeight()}).appendTo(a.parent()).offset(b)[0]})},L0:function(){this.GN&&(this.GN.remove(),delete this.GN)},Uaa:function(a){this.WY="ojDialogPlaceHolderFooter-"+this.kI;this.eia=f("\x3cdiv\x3e").hide().attr({id:this.WY});this.eia.insertBefore(a)},Vaa:function(a){this.XY="ojDialogPlaceHolderHeader-"+
this.kI;this.fia=f("\x3cdiv\x3e").hide().attr({id:this.XY});this.fia.insertBefore(a)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close-wrapper":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":a="."+
a;if(!this.widget().find(a))break;return this.widget().find(a)[0];case "oj-dialog-close-icon":case "oj-dialog-close":if(!this.widget().find(".oj-dialog-close-icon"))break;return this.widget().find(".oj-dialog-close-icon")[0]}return null},getSubIdByNode:function(a){if(null!=a){a=f(a);if(a.hasClass("oj-dialog-header"))return{subId:"oj-dialog-header"};if(a.hasClass("oj-dialog-footer"))return{subId:"oj-dialog-footer"};if(a.hasClass("oj-dialog-content"))return{subId:"oj-dialog-content"};if(a.hasClass("oj-dialog-header-close-wrapper"))return{subId:"oj-dialog-header-close-wrapper"};
if(a.hasClass("oj-dialog-close-icon"))return{subId:"oj-dialog-close"};if(a.hasClass("oj-resizable-n"))return{subId:"oj-resizable-n"};if(a.hasClass("oj-resizable-e"))return{subId:"oj-resizable-e"};if(a.hasClass("oj-resizable-s"))return{subId:"oj-resizable-s"};if(a.hasClass("oj-resizable-w"))return{subId:"oj-resizable-w"};if(a.hasClass("oj-resizable-se"))return{subId:"oj-resizable-se"};if(a.hasClass("oj-resizable-sw"))return{subId:"oj-resizable-sw"};if(a.hasClass("oj-resizable-ne"))return{subId:"oj-resizable-ne"};
if(a.hasClass("oj-resizable-nw"))return{subId:"oj-resizable-nw"}}return null},Mq:function(){this.element.remove()},ft:function(){if(!this.sj){var a=this.sj={};a[b.N.xc.Rr]=f.proxy(this.Rp,this);a[b.N.xc.Sr]=f.proxy(this.Mq,this);a[b.N.xc.Um]=f.proxy(this.YY,this)}return this.sj},Rp:function(){this.Pw=!0;this.close();delete this.Pw}})})()});