/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery"],function(b,f){b.Gg=function(a,b,c){c=c||{};this.i=b;this.$A=a;this.Vs=c.fetchSize;this.Vs=0<this.Vs?this.Vs:25;this.Dt=c.maxCount;this.Dt=0<this.Dt?this.Dt:500;this.OC=0;this.p0=c.success;this.Yba=c.error;this.Eq();f(this.$A).on("scroll.domscroller",function(a){var b=f(a.target).scrollTop();a=f(a.target)[0].scrollHeight-f(a.target)[0].clientHeight;0<a&&this.vfa(b,a)}.bind(this))};b.Gg.prototype.destroy=function(){this.Dk();f(this.$A).off("scroll.domscroller")};b.b.g("DomScroller.prototype.destroy",
{destroy:b.Gg.prototype.destroy});b.Gg.prototype.checkViewport=function(){return 0<this.$A[0].clientHeight&&!this.Q$()?this.bV():Promise.resolve(null)};b.b.g("DomScroller.prototype.checkViewport",{checkViewport:b.Gg.prototype.checkViewport});b.Gg.prototype.vfa=function(a,b){if(1>=b-a){var c=this;this.bV().then(function(a){null!=c.p0&&c.p0(a)},this.Yba)}};b.Gg.prototype.Q$=function(){var a=this.$A;return a[0].scrollHeight>a[0].clientHeight+1?!0:!1};b.Gg.prototype.bV=function(){if(this.cB)return this.cB;
var a=this.Dt-this.OC;if(0<a){var b=this.Vs,c=this;a<this.Vs&&(b=a);var e=this.hca({pageSize:b});return this.cB=new Promise(function(b){e.then(function(d){c.cB=null;null!=d&&(c.OC=d.data.length+d.startIndex,a<c.Vs&&(d.maxCount=c.Dt,d.maxCountLimit=!0));b(d)})})}return Promise.resolve({maxCount:this.Dt,maxCountLimit:!0})};b.Gg.prototype.hca=function(a){a=a||{};var b=a.pageSize;this.Dh=this.Dh?this.Dh+b:b;if(-1==this.i.totalSize()||this.i.totalSize()>this.Dh){var c=this;return new Promise(function(a,
f){c.i.fetch({startIndex:c.Dh,pageSize:b}).then(function(b){a(b)},function(){f(null)})})}return Promise.resolve()};b.Gg.prototype.Mn=function(){this.Dh=null;this.OC=0};b.Gg.prototype.Cea=function(a){this.Dh=a.startIndex;this.OC=a.data.length+this.Dh};b.Gg.prototype.Eq=function(){var a=this.i;if(null!=a){this.Dk();this.Ua=[];this.Ua.push({eventType:b.T.D.SORT,eventHandler:this.Mn.bind(this)});this.Ua.push({eventType:b.T.D.REFRESH,eventHandler:this.Mn.bind(this)});this.Ua.push({eventType:b.T.D.RESET,
eventHandler:this.Mn.bind(this)});this.Ua.push({eventType:b.T.D.SYNC,eventHandler:this.Cea.bind(this)});var d,c;for(d=0;d<this.Ua.length;d++)(c=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&(this.Ua[d].eventHandler=c)}};b.Gg.prototype.Dk=function(){var a=this.i;if(null!=this.Ua&&null!=a){var b;for(b=0;b<this.Ua.length;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}}});