/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation","ojs/internal-deps/dvt/DvtToolkit","promise"],function(b,f,a,d,c){function e(a,b){this.bia=b;this.Sja=a;this.qba="/"}b.Eg=function(a){this.Init(a)};o_("AttributeGroupHandler",b.Eg,b);b.b.ga(b.Eg,b.b,"oj.AttributeGroupHandler");b.Eg.prototype.Init=function(a){b.Eg.q.Init.call(this);this.Zw=a?a:{};this.Rv={};this.yD=0;this.tz=this.gr();for(var c in this.Zw)a=this.tz.indexOf(this.Zw[c]),-1!==a&&this.tz.splice(a,1)};b.Eg.prototype.gr=
function(){return[]};b.b.g("AttributeGroupHandler.prototype.getValueRamp",{gr:b.Eg.prototype.gr});b.Eg.prototype.Hc=function(a){if(this.Zw[a])return this.Zw[a];this.Rv[a]||(this.Rv[a]=this.tz[this.yD],this.yD==this.tz.length-1?this.yD=0:this.yD++);return this.Rv[a]};b.b.g("AttributeGroupHandler.prototype.getValue",{Hc:b.Eg.prototype.Hc});b.Eg.prototype.h2=function(){var a=[],b;for(b in this.Rv)a.push({category:b,value:this.Rv[b]});return a};b.b.g("AttributeGroupHandler.prototype.getCategoryAssignments",
{h2:b.Eg.prototype.h2});b.Eg.prototype.$0=function(a,b){this.Zw[a]=b};b.b.g("AttributeGroupHandler.prototype.addMatchRule",{$0:b.Eg.prototype.$0});b.jv=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",b.jv,b);b.b.ga(b.jv,b.Eg,"oj.ShapeAttributeGroupHandler");b.jv.Sv="square circle diamond plus triangleDown triangleUp human".split(" ");b.jv.prototype.gr=function(){return b.jv.Sv.slice()};e.prototype.Lja=function(a,b,c,d){for(var e={};a&&-1<b.indexOf(c);){var g=b.substring(0,b.indexOf(c));
d&&void 0===a[g]&&(a[g]={});a=a[g];b=b.substring(b.indexOf(c)+1,b.length)}a&&(e.object=a,e.parameter=b);return e};e.prototype.f_=function(a){void 0===this.Yw&&(a=this.Lja(this.Sja,this.bia,this.qba,a),this.Yw=a.object,this.GK=a.parameter)};e.prototype.Hc=function(){this.f_(!1);return void 0===this.Yw?void 0:this.Yw[this.GK]};e.prototype.N4=function(a,b){this.f_(!0);if(b||!this.Yw[this.GK])this.Yw[this.GK]=a};var g={CSS_TEXT_PROPERTIES:function(a){var b={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,
"oj-ledGauge")?(b["font-size"]=!0,b.color=!0):a.hasClass(a,"oj-chartSliceLabel")?b.color=!0:a.hasClass("oj-treemap-node-header")&&(b["font-weight"]=!0));return g.z$(a,b)},CSS_BACKGROUND_PROPERTIES:function(a){return g.q$(a)},CSS_URL:function(a){return g.aia(a)},$Q:"rgb(254, 0, 254)",x7:"Times",y7:"1px",bR:"1",aR:"normal",q7:4,bD:{},ena:function(a,b){return a.css(b)},aia:function(a){return(a=a.css("background-image"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):
a},q$:function(a){var b={};a.css("border-top-color")&&(b["border-color"]=a.css("border-top-color"));a.css("border-width")&&a.css("border-style")&&"none"!=a.css("border-style")&&(b["border-width"]=a.css("border-width"));a.css("background-color")&&(b["background-color"]=a.css("background-color"));return b},z$:function(a,b){var c={},d=a.css("font-family");d&&d!==g.x7&&(c["font-family"]=d.replace(/"/g,"'"));d=a.css("font-size");!d||-1<d.indexOf("px")&&parseFloat(d)<g.q7||b["font-size"]||(c["font-size"]=
d);(d=a.css("font-weight"))&&d!==g.bR&&!b["font-weight"]&&(c["font-weight"]=d);(d=a.css("color"))&&d!==g.$Q&&!b.color&&(c.color=d);(d=a.css("font-style"))&&d!==g.aR&&(c["font-style"]=d);return c},bpa:function(a,b,c,d){var e=f(document.createElement("div"));e.attr("style","display:none;");a.append(e);a="";for(var p=0;p<c.length;p++)a=a+c[p]+" ";e.attr("class",a);f(document.body).append(e);c=f(document.createElement("div"));c.css("font-size",g.y7);c.css("color",g.$Q);c.css("font-weight",g.bR);c.css("font-style",
g.aR);e.append(c);for(var r in d)a=d[r],a instanceof Array||(a=[a]),g.yia(c,b,r,a);e.remove()},yia:function(a,b,c,d){g.bD[c]||(g.bD[c]={});for(var n=null,p=0;p<d.length;p++){var r=d[p],s=r.property;if(s){var q=g.bD[c][s];"undefined"==typeof q&&(n||(n=f(document.createElement("div")),n.addClass(c),a.append(n)),q=g.Mja(n,s),g.bD[c][s]=q);if(null!=q){var r=new e(b,r.path),t=g[s];if(null!=t){var w=r.Hc();if("CSS_URL"!==s){s="";if(null!=w){for(var x in q)-1===w.indexOf(x)&&(s+=x+":"+q[x]+";");s+=w}else for(x in q)s+=
x+":"+q[x]+";";q=s}}r.N4(q,null!=t)}}}},Mja:function(a,b){var c=g[b],c=c?c(a):g.ena(a,b);return null==c||"string"==typeof c&&""==c.replace(/^\s+/g,"")?null:c}};b.ya("oj.dvtBaseComponent",f.oj.baseComponent,{_ComponentCreate:function(){this._super();this.xC=this.iL=0;this.wk=null;this.VK=f(document.createElement("div"));this.VK.attr("style","visibility:hidden;");this.element.append(this.VK);var a=this.element[0].parentElement;this.eg=a&&a.iI?a.iI:new c.DvtContext(this.element[0],null,this.VK[0]);this.eg.setReadingDirection(this.ac());
this.eg.setTooltipAttachedCallback(b.Components.Nf);this.eg.setTooltipStyleClass("oj-dvt-tooltip");this.eg.setDatatipStyleClass("oj-dvt-datatip");f(document.body).hasClass("oj-hicontrast")&&c.DvtAgent.setHighContrast(!0);this.na=this.jf(this.eg,this.hi,this);this.eg.getStage().addChild(this.na);!1!==c.requireJS&&(this.xka(),this.jZ());this.ls();this.options._environment="jet"},hf:function(){this._super();this.element.attr("tabIndex",0);this.bg();this.Wl=this.Se.bind(this);b.v.eh(this.element[0],this.Wl,
250)},refresh:function(){this._super();this.eg.setReadingDirection(this.ac());this.jZ();this.bg()},getNodeBySubId:function(a){var b=this.na&&this.na.getAutomation?this.na.getAutomation():null;if(b)return b.getDomElementForSubId(this.ai(a))},getSubIdByNode:function(a){var b=this.na&&this.na.getAutomation?this.na.getAutomation():null;if(b)return(a=b.getSubIdForDomElement(a))?this.$f(a):null},ai:function(){return null},$f:function(){return null},Wz:function(){for(var a=this.ye(),b=0;b<a.length;b++)this.element.addClass(a[b]);
g.bpa(this.element,this.options,this.ye(),this.bi())},ye:function(){return["oj-dvtbase"]},bi:function(){return{"oj-dvt-status-message":{path:"_statusMessageStyle",property:"CSS_TEXT_PROPERTIES"}}},di:function(){return[]},ei:function(){var a=this.options.translations,a={"DvtUtilBundle.CLEAR_SELECTION":a.labelClearSelection,"DvtUtilBundle.COLON_SEP_LIST":a.labelAndValue,"DvtUtilBundle.INVALID_DATA":a.labelInvalidData,"DvtUtilBundle.NO_DATA":a.labelNoData,"DvtUtilBundle.DATA_VISUALIZATION":a.labelDataVisualization,
"DvtUtilBundle.STATE_SELECTED":a.stateSelected,"DvtUtilBundle.STATE_UNSELECTED":a.stateUnselected,"DvtUtilBundle.STATE_MAXIMIZED":a.stateMaximized,"DvtUtilBundle.STATE_MINIMIZED":a.stateMinimized,"DvtUtilBundle.STATE_EXPANDED":a.stateExpanded,"DvtUtilBundle.STATE_COLLAPSED":a.stateCollapsed,"DvtUtilBundle.STATE_ISOLATED":a.stateIsolated,"DvtUtilBundle.STATE_HIDDEN":a.stateHidden,"DvtUtilBundle.STATE_VISIBLE":a.stateVisible,"DvtUtilBundle.SCALING_SUFFIX_THOUSAND":a.labelScalingSuffixThousand,"DvtUtilBundle.SCALING_SUFFIX_MILLION":a.labelScalingSuffixMillion,
"DvtUtilBundle.SCALING_SUFFIX_BILLION":a.labelScalingSuffixBillion,"DvtUtilBundle.SCALING_SUFFIX_TRILLION":a.labelScalingSuffixTrillion,"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION":a.labelScalingSuffixQuadrillion},c=b.Ja.sy("abbreviated");a["DvtUtilBundle.MONTH_SHORT_JANUARY"]=c[0];a["DvtUtilBundle.MONTH_SHORT_FEBRUARY"]=c[1];a["DvtUtilBundle.MONTH_SHORT_MARCH"]=c[2];a["DvtUtilBundle.MONTH_SHORT_APRIL"]=c[3];a["DvtUtilBundle.MONTH_SHORT_MAY"]=c[4];a["DvtUtilBundle.MONTH_SHORT_JUNE"]=c[5];a["DvtUtilBundle.MONTH_SHORT_JULY"]=
c[6];a["DvtUtilBundle.MONTH_SHORT_AUGUST"]=c[7];a["DvtUtilBundle.MONTH_SHORT_SEPTEMBER"]=c[8];a["DvtUtilBundle.MONTH_SHORT_OCTOBER"]=c[9];a["DvtUtilBundle.MONTH_SHORT_NOVEMBER"]=c[10];a["DvtUtilBundle.MONTH_SHORT_DECEMBER"]=c[11];return a},jZ:function(){var a=this.ei();c.DvtBundle.addLocalizedStrings(a)},xka:function(){var a={};a.numberConverterFactory=b.pa.o2("number");a.dateToIsoConverter=function(a){return a instanceof Date?b.ob.dateToLocalIso(a):a};a.isoToDateConverter=function(a){return"string"==
typeof a?b.ob.isoToLocalDate(a):a};this.eg.setLocaleHelpers(a)},_destroy:function(){this.eg.hideTooltips();this.na.destroy&&this.na.destroy();b.v.Qh(this.element[0],this.Wl);this.element.children().remove();this.element.removeAttr("role").removeAttr("tabIndex");for(var a=this.ye(),c=0;c<a.length;c++)this.element.removeClass(a[c]);this._super()},_setOptions:function(a,b){this._superApply(arguments);if(!this.XS){var c=!1,d=this.di(),e=["highlightedCategories","selection","dataCursorPosition"];f.each(a,
function(a){if(0>d.indexOf(a)&&0>e.indexOf(a))return c=!0,!1});c?this.bg():(void 0!==a.highlightedCategories&&this.na.highlight(a.highlightedCategories),void 0!==a.selection&&this.na.select(a.selection),void 0!==a.dataCursorPosition&&this.na.positionDataCursor&&this.na.positionDataCursor(a.dataCursorPosition))}},jf:function(){return null},hi:function(a){var b=a&&a.getType?a.getType():null;b===c.DvtCategoryHideShowEvent.TYPE_HIDE||b===c.DvtCategoryHideShowEvent.TYPE_SHOW?this.gc("hiddenCategories",
a.hiddenCategories):b===c.DvtCategoryRolloverEvent.TYPE_OVER||b===c.DvtCategoryRolloverEvent.TYPE_OUT?this.gc("highlightedCategories",a.categories):b===c.DvtOptionChangeEvent.TYPE?this.gc(a.key,a.value,a.optionMetadata):this.options.contextMenu&&b===c.DvtComponentTouchEvent.TOUCH_HOVER_END_TYPE&&this.nf(f.Event(a.getNativeEvent()),"touch")},Se:function(){var a=this.element.width(),b=this.element.height();(null==this.AD||null==this.WB||5<=Math.abs(a-this.AD)+Math.abs(b-this.WB))&&this.bg(!0)},ls:function(){},
bg:function(a){this.eg.isReadyToRender()?(this.AD=this.Lz()?null:this.element.width(),this.WB=this.Lz()?null:this.element.height(),this.options._width=this.AD,this.options._height=this.WB,this.options._locale=b.ba.qg(),this.Wz(),this.iL++,a?this.wk||this.hL(null):0===this.Kja().length&&this.hL(this.options),this.kL=!1):this.kL=!0},ml:function(){this._super();this.kL&&this.bg()},gn:function(){this._super();this.kL&&this.bg()},ii:function(){this._super();this.eg.hideTooltips()},ll:function(){this._super();
this.eg.hideTooltips()},gc:function(a,b,c){this.XS=!0;this.option(a,b,{_context:{Ec:!0,rr:c,Za:!0}});this.XS=!1},lf:function(a,b,c){"touch"!==c&&("keyboard"===c?this.nf(b,c,{position:{of:this.na.getKeyboardFocus()}}):this._super(a,b,c))},uv:function(a){return(a=b.Components.sg(a)("instance"))?a.na:null},Mg:function(a){if(a){var b={},c;for(c in a)this.y9(a,c,b);Object.defineProperties(a,b)}},y9:function(a,b,c){var d=("selected"==b?"is":"get")+b.charAt(0).toUpperCase()+b.slice(1);c[d]={value:function(){return a[b]}}},
rp:function(a){for(var b="",c=0;c<a.length;c++)b+="["+a[c]+"]";return b},kl:function(a){for(var b=[],c=0;0<a.indexOf("[",c);){var d=a.indexOf("[",c)+1,c=a.indexOf("]",c);b.push(Number(a.substring(d,c)));c+=1}return b},Ah:function(a){return Number(this.Fz(a))},Fz:function(a){var b=a.indexOf("[")+1,c=a.indexOf("]");return a.substring(b,c)},ci:function(){return{}},Kja:function(){this.wk=null;var a=this.ci(),b;for(b in a)for(var c=a[b],d=0;d<c.length;d++)if("root"===b){if(this.Up(this.options,c[d]))break}else{var e=
this.options[b];if(e)for(var g=0;g<e.length&&!this.Up(e[g],c[d]);g++);}var f=[];this.xC=0;if(this.wk){var s=this;for(b in a)c=a[b],c.forEach(function(a){var c;if("root"===b)(c=s.kW(s.wk,a))&&f.push(c);else{var d=s.wk[b];if(d)for(var e=0;e<d.length;e++)(c=s.kW(d[e],a))&&f.push(c)}})}return f},Up:function(a,b){if(!this.wk){var d=(new e(a,b)).Hc();d&&(d instanceof Function||d instanceof Promise)&&(this.wk=c.DvtJSONUtils.clone(this.options))}return null!==this.wk},kW:function(a,b){var c=new e(a,b),d=
c.Hc();d instanceof Function&&(d=Promise.resolve(d(this.XQ(a))));if(d&&d instanceof Promise){this.xC++;var g=this.iL,f=this;d.then(function(a){f.UZ(g,c,a)},function(){f.UZ(g,c,[])});return d}return null},UZ:function(a,b,c){a===this.iL&&(this.xC--,b.N4(c,!0),0===this.xC&&(this.hL(this.wk),this.wk=null))},hL:function(a){var c=this.Lz()&&this.Wl;c&&b.v.Qh(this.element[0],this.Wl);this.na.render(a,this.AD,this.WB);c&&b.v.eh(this.element[0],this.Wl,250)},XQ:function(){return{}},Lz:function(){return!1}},
!0);b.Ie=function(a){this.Sv=[];if(f(document.body).hasClass("oj-hicontrast"))this.Sv=b.Ie.JQ.slice();else{if(!b.Ie.bw){b.Ie.bw=[];var c=f(document.createElement("div"));c.attr("style","display:none;");c.attr("id","attrGps");f(document.body).append(c);for(var d=0;d<b.Ie.VR.length;d++){var e=f(document.createElement("div"));e.addClass(b.Ie.VR[d]);c.append(e);(e=e.css("color"))&&b.Ie.bw.push(e)}c.remove()}this.Sv=0<b.Ie.bw.length?b.Ie.bw.slice():b.Ie.JQ.slice()}this.Init(a)};o_("ColorAttributeGroupHandler",
b.Ie,b);b.b.ga(b.Ie,b.Eg,"oj.ColorAttributeGroupHandler");b.Ie.JQ="#267db3 #68c182 #fad55c #ed6647 #8561c8 #6ddbdb #ffb54d #e371b2 #47bdef #a2bf39 #a75dba #f7f37b".split(" ");b.Ie.VR="oj-dvt-category1 oj-dvt-category2 oj-dvt-category3 oj-dvt-category4 oj-dvt-category5 oj-dvt-category6 oj-dvt-category7 oj-dvt-category8 oj-dvt-category9 oj-dvt-category10 oj-dvt-category11 oj-dvt-category12".split(" ");b.Ie.bw=null;b.Ie.prototype.gr=function(){return this.Sv.slice()}});