/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(b,f,a){b.re={};o_("EditableValueUtils",b.re,b);b.re.yna=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=void 0!==a.attr("readonly")?!!a.prop("readonly"):void 0;break;case "required":c=
a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=void 0!==a.attr("title")?a.prop("title"):void 0;break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.b2=!0,e.value=c):e.b2=!1;return e};b.re.Rk=function(a,c,d,e){for(var g={},f=0;f<a.length;f++){var h,k;h=a[f];k=h.V;var l=h.option||k,u=h.We,v=h.vc,y=d.element,B=d.options[l];void 0===c[l]&&(B=d.options[l],k=b.re.yna(y,k),k.b2?(h=k.value,u&&("boolean"===typeof u?h=b.re.Gma(l,
h):"function"===typeof u&&(h=u.call(d,h))),g[l]=h):void 0===B&&(g[l]=h.PD));u=l in g?g[l]:B;v&&"boolean"===typeof v&&b.re.bqa(l,u)}null!=e&&e(g);d.option(g,{_context:{Ec:!0,Za:!0}})};b.re.bqa=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+"' has invalid value set: "+b;};b.re.Gma=function(a,b){var c=b;switch(a){case "required":c=b?!0:!1}return c};b.eb=function(a){this.Init(a)};
b.Sa.AE(b.Sa.$c.mz,b.eb);b.b.ga(b.eb,b.mc,"oj.PopupMessagingStrategy");b.eb.as={ojRadioset:{position:"launcher",Bj:{open:"focus focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",Bj:{open:"focusin mouseover",close:"mouseout"}},ojInputText:{position:"launcher",Bj:{open:"focusin"}},ojTextArea:{position:"launcher",Bj:{open:"focusin"}},ojInputPassword:{position:"launcher",Bj:{open:"focusin"}},ojSwitch:{position:"launcher",Bj:{open:"focusin mouseover",close:"mouseout"}},ojSlider:{position:"launcher",
Bj:{open:"focusin mouseover",close:"mouseout"}},"default":{position:"launcher-wrapper",Bj:{open:"focusin"}}};b.eb.oG="oj-form-control-hint";b.eb.J8="oj-form-control-hint-converter";b.eb.L8="oj-form-control-hint-validator";b.eb.K8="oj-form-control-hint-title";b.eb.prototype.to=function(a){b.eb.q.to.call(this,a);this.aga()};b.eb.prototype.vr=function(a){b.eb.q.vr.call(this,a);this.Q0()};b.eb.prototype.update=function(){b.eb.q.update.call(this);this.Q0()};b.eb.prototype.Lk=function(){this.Hla();this.uba();
b.eb.q.Lk.call(this)};b.eb.prototype.GT=function(){this.ZX()&&this.He.ojPopup("close")};b.eb.prototype.aga=function(){this.zC||this.Zia()};b.eb.prototype.SY=function(){var a,c;if(this.K$()&&(c=this.bT(),!b.Ea.Gi(c))){var d=this.iW();a=d.ojPopup("isOpen");a?a&&(a=d[0],a.innerHTML="",a.innerHTML=c,d.ojPopup("refresh")):(a=d[0],a.innerHTML="",a.innerHTML=c,d.ojPopup("open",this.Vh()))}};b.eb.prototype.K$=function(){var a=this.Si().options,b=a.readOnly||!1;return!(a.disabled||b)};b.eb.prototype.Q0=function(){var a;
a=!1;var b,c;if(this.ZX()){var d=this.iW();a=d.ojPopup("isOpen");b=this.bT();c=document.activeElement===this.Vh()[0]?!0:!1;a?b?(a=d[0],a.innerHTML="",a.innerHTML=b,d.ojPopup("refresh")):d.ojPopup("close"):c&&b&&this.SY()}};b.eb.prototype.Hla=function(){var a=b.eb.as[this.Si().widgetName],a=a?a.Bj:b.eb.as["default"].Bj;if(a.open){var c=this.zC;delete this.zC;c&&this.Vh().off(a.open,c)}a.close&&(c=this.HT)&&this.Vh().off(a.close,c)};b.eb.prototype.Zia=function(){var a=this.Vh(),c=b.eb.as[this.Si().widgetName],
c=c?c.Bj:b.eb.as["default"].Bj;if(c.open){var d=this.zC;d||(d=this.zC=f.proxy(this.SY,this));a.on(c.open,d)}c.close&&(d=this.HT,d||(d=this.HT=f.proxy(this.GT,this)),a.on(c.close,d))};b.eb.prototype.Nda=function(){var a,c=b.eb.as[this.Si().widgetName];(c=c?c.position:b.eb.as["default"].position)&&("launcher"===c?a=this.Vh():"launcher-wrapper"===c&&(a=this.Vh().parent()));a||(a=this.Si().widget());return{my:"start bottom",at:"end top",collision:"flipcenter",of:a}};b.eb.prototype.iW=function(){if(this.He)return this.He;
var a=b.rd.D2(),c=this.Nda();a.ojPopup("option","position",c);a.ojPopup("option","close",f.proxy(this.hia,this));a.ojPopup("option","open",f.proxy(this.iia,this));return this.He=a};b.eb.prototype.iia=function(a){var c=f(a.target),d=this;window.setTimeout(function(){b.Components.KN(c)?c.ojPopup("option","autoDismiss","focusLoss"):delete d.He},10)};b.eb.prototype.hia=function(a){a=f(a.target);b.Components.KN(a)&&(a.ojPopup("option","autoDismiss","none"),a.ojPopup("option","open",null),a.ojPopup("option",
"close",null));delete this.He;a.children().remove()};b.eb.prototype.uba=function(){this.GT();b.rd.ina()};b.eb.prototype.bT=function(){var a="",c=this.Si().document[0],d=[],e=!1;this.eQ()&&d.push(this.ZG(c));(this.wF()||this.gQ()||this.fQ())&&d.push(this.s$(c));f.each(d,function(d,g){g&&(e?a=a.concat(b.Na.Ina(c)):e=!0,a=a.concat(g))});return a};b.eb.prototype.ZG=function(a){var c;c="";var d=this.bF();this.kF()&&(c=this.cF(),c=b.Na.m1(a,c,d,!1));return c};b.eb.prototype.s$=function(a){var c=[],d,e=
"";this.wF()&&(c=this.zP(),c=c.length?c[0]:"",e+=b.Na.GM(a,b.eb.J8,c,!1,b.eb.oG));if(this.gQ())for(c=this.W5(),d=0;d<c.length;d++)e+=b.Na.GM(a,b.eb.L8,c[d],!1,b.eb.oG);this.fQ()&&(e+=b.Na.GM(a,b.eb.K8,this.V5(),!0,b.eb.oG));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};b.eb.prototype.ZX=function(){return this.He?b.Components.KN(this.He):!1};b.Na={};b.Na.GM=function(a,c,d,e,g){var h;d&&(h=f(a.createElement("div")),h.addClass(g+(" "+c)),h.append(b.Na.EW(a,d,e)));return h?
h.get(0).outerHTML:""};b.Na.L2=function(a){var c;switch(a){case b.X.Qb.FATAL:c=b.ha.A("oj-message.fatal");break;case b.X.Qb.ERROR:c=b.ha.A("oj-message.error");break;case b.X.Qb.WARNING:c=b.ha.A("oj-message.warning");break;case b.X.Qb.INFO:c=b.ha.A("oj-message.info");break;case b.X.Qb.CONFIRMATION:c=b.ha.A("oj-message.confirmation")}return c};b.Na.Ina=function(a){return(a=f(a.createElement("hr")))?a.get(0).outerHTML:""};b.Na.m1=function(a,c,d,e){var g="",f,h,k,l,u={};l=[];for(f=0;f<c.length;f++)k=
c[f],l=k instanceof b.X?k:new b.X(k.summary,k.detail,k.severity),h=b.X.vu(l.severity),u[h]||(u[h]=[]),u[h].push(l);for(f=d;f>=b.X.Qb.CONFIRMATION;f--)for(l=u[f]||[],c=0;c<l.length;c++)k=l[c],b.l.xd(k,b.X),h=b.X.vu(k.severity),d=b.Na.L2(h),d=k.summary||d,k=k.detail||"",g=g.concat(b.Na.l1(a,d,k,h,e));return g};b.Na.l1=function(a,c,d,e,g){var h,k;k=b.Na.L2(e);h=f(a.createElement("div"));h.addClass(b.Na.M8);g&&h.addClass(b.Na.Wda(e));g=f(a.createElement("span"));g.addClass(b.Na.Vda(e)).attr("title",k).attr("role",
"img");h.append(g);e=f(a.createElement("span"));e.addClass(b.Na.P8);k=f(a.createElement("div"));k.addClass(b.Na.T8).text(c);e.append(k);d&&(c=b.Na.EW(a,d,!0),a=f(a.createElement("div")),a.addClass(b.Na.Q8).append(c),e.append(a));h.append(e);return h?h.get(0).outerHTML:""};b.Na.Vda=function(a){var c;switch(a){case b.X.Qb.FATAL:c=b.Na.UR;break;case b.X.Qb.ERROR:c=b.Na.UR;break;case b.X.Qb.WARNING:c=b.Na.V8;break;case b.X.Qb.INFO:c=b.Na.S8;break;case b.X.Qb.CONFIRMATION:c=b.Na.O8}return b.Na.S6+c};b.Na.Wda=
function(a){switch(a){case b.X.Qb.FATAL:a=b.Na.TR;break;case b.X.Qb.ERROR:a=b.Na.TR;break;case b.X.Qb.WARNING:a=b.Na.U8;break;case b.X.Qb.INFO:a=b.Na.R8;break;default:a=b.Na.N8}return a};b.Na.EW=function(a,c,d){var e=null;b.Ea.jd(c)&&(d&&b.v.Coa(c)?e=b.v.Dma(c.substring(6,c.length-7)):(e=a.createElement("span"),e.textContent=c));return e};b.Na.S6="oj-component-icon oj-message-status-icon ";b.Na.M8="oj-message";b.Na.T8="oj-message-summary";b.Na.Q8="oj-message-detail";b.Na.P8="oj-message-content";b.Na.UR=
"oj-message-error-icon";b.Na.V8="oj-message-warning-icon";b.Na.S8="oj-message-info-icon";b.Na.O8="oj-message-confirmation-icon";b.Na.TR="oj-message-error";b.Na.U8="oj-message-warning";b.Na.R8="oj-message-info";b.Na.N8="oj-message-confirmation";b.rd={};b.rd.D2=function(){var a=b.rd.hW(),c=a.find("."+b.rd.pG);0===c.length?(c=f(b.rd.Mda()).hide(),c.appendTo(a),c.ojPopup({rootAttributes:{"class":b.rd.W8},initialFocus:"none",tail:"simple",autoDismiss:"none",modality:"modeless"})):c=f(c[0]);return c};b.rd.ina=
function(){if(0<b.rd.dda()){var a=b.rd.D2();a.ojPopup("destroy");a.remove()}};b.rd.hW=function(){var a=f("#"+b.rd.oR);if(0<a.length)return a;a=f("\x3cdiv\x3e");a.attr("id",b.rd.oR);a.attr("role","presentation");a.appendTo(f(document.body));return a};b.rd.dda=function(){return b.rd.hW().find("."+b.rd.pG).length};b.rd.Mda=function(){return"\x3cdiv class\x3d'"+b.rd.pG+"'\x3e\x3c/div\x3e"};b.rd.pG="oj-messaging-popup-container";b.rd.W8="oj-messaging-popup";b.rd.oR="__oj_messaging_popup_pool";(function(){b.ya("oj._ojLabel",
f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{ariaRequiredUnsupported:!1,describedById:null,help:{definition:null,source:null},required:!1,rootAttributes:null},xa:{pS:"tooltipHelp",qS:"tooltipRequired"},widget:function(){return this.Er},refresh:function(){this._super();this.uZ();this.qZ()},Ud:function(a,b){this._super(a,b);this.R$();this.rH()},_ComponentCreate:function(){this._super();this.iD=this.eventNamespace+"TouchEatClick";this.XB=this.eventNamespace+
"HelpDefPopup";this.tn=b.v.Od();this.Rba()},Dv:function(a){this.Hx=a.attr("class")},us:function(){this.Hx?this.element.attr("class",this.Hx):this.element.removeAttr("class")},Rba:function(){var a=this.options,b=a.required,a=a.ariaRequiredUnsupported,c=this.JY(),d=null;this.Er=this.element.wrap(this.Zaa()).closest(".oj-component");this.Eha();c&&(d=this.IH());this.UT(d);b&&(a?d.appendChild(this.OA()):this.element.before(this.OA()))},UT:function(a){var b=this.options,c=b.help.definition;if(b.help.source||
c)this.oga(a),this.A9(),this.e$()},R$:function(){var a=this.options.required;if(null!==a&&"boolean"!==typeof a)throw Error("Option 'required' has invalid value set: "+a);},rH:function(){var a=this.options;if(this.JY()&&null==a.describedById)throw Error("ojLabel's describedById option must be set if help source is set\n\r\n      or (ariaRequiredUnsupported and required is set).");},Eha:function(){var a=this.element.attr("class"),b;if(a&&(a=a.split(/\s+/),null!=a)){b=a.length;for(var c=0;c<b;c++){var d=
a[c];0<d.indexOf("-label")&&(this.Er.addClass(d),this.element.removeClass(d))}}},IH:function(){var a=this.Er.find(".oj-label-group"),b=document.createElement("span");b.setAttribute("id",this.options.describedById);a.prepend(b);return b},Zaa:function(){var a=this.options.rootAttributes,b,c;c="oj-label oj-component";a&&(b=a["class"]);null!==b&&(c=c+" "+b);a=document.createElement("div");a.className=c;c=document.createElement("div");c.className="oj-label-group";a.appendChild(c);return a},OA:function(){var a=
this.A(this.xa.qS),b=document.createElement("span");b.className="oj-label-required-icon oj-component-icon";b.setAttribute("role","img");b.setAttribute("title",a);return b},Caa:function(a,c){var d;if(this.uC()){d=document.createElement("a");d.setAttribute("tabindex","0");d.setAttribute("target","_blank");d.className="oj-label-help-icon-anchor oj-label-help-icon oj-component-icon oj-clickable-icon-nocontext";if(c)try{b.v.aqa(c),d.setAttribute("href",c)}catch(e){throw Error(e+". The source option ("+
c+") is invalid.");}a?d.setAttribute("title",a):d.setAttribute("title",this.A(this.xa.pS))}return d},e$:function(){var b;b=this.options.help.definition;var c,d,e;d=this.widget().find(".oj-label-help-icon-anchor");if(0!=d.length){c=b?b:this.A(this.xa.pS);this.Nw?(e=f(document.getElementById(this.Nw)))&&e.text(c):(b=document.createElement("div"),b.style.display="none",e=f(b),e.uniqueId(),this.Nw=e.prop("id"),e.text(c),c=document.getElementsByTagName("body")[0],c.appendChild(b));this.tn&&(this.ZA&&this.widget().off(this.iD),
this.ZA=function(){return!1});var g=this;this.AC||(this.AC=function(a){g.mfa(a,e,d,!1)});if(this.tn)d.Zk({recognizers:[[a.Press,{time:750}]]}).on("press",this.AC);else d.on("focusin"+this.XB+" mousedown"+this.XB,this.AC);b={my:"start bottom",at:"end top",collision:"flipcenter",of:d};e.ojPopup({position:b,modality:"modeless"})}},mfa:function(a,b,c,d){if("mousedown"===a.type)d=!0;else if("focusin"===a.type&&d)d=!1;else{if(this.tn)if("press"===a.type){var e=this.widget();e.on("click"+this.iD,this.ZA);
var g=this;b.on("ojclose",function(){e.off(g.iD);g.ZA=null})}else b.off("ojclose");b.ojPopup("isOpen")||b.ojPopup("open",c)}},A9:function(){var a=this.element,b=this.options.help.definition,c;b&&(a.addClass("oj-label-help-def"),(c=a.attr("title"))?a.attr("title",c+" "+b):a.attr("title",b))},NZ:function(a){this.tn&&(this.widget().off(this.iD),this.ZA=null,a.Zk().off(this.XB));a.off(this.XB);this.AC=null},OZ:function(){var a;if(null!=this.Nw){if(a=f(document.getElementById(this.Nw)))a.ojPopup("destroy"),
a.remove();this.Nw=null}},mja:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},oga:function(a){var b=this.options.help.source,c=this.options.help.definition;this.uC()&&f(a).prepend(this.Caa(c,b))},JY:function(){var a=this.options;return this.uC()||a.ariaRequiredUnsupported&&a.required},uC:function(){var a=this.options;return a.help.source||a.help.definition},qZ:function(){var a,b;this.rH();this.mja();a=this.Er.find(".oj-label-help-icon");1===a.length&&(this.NZ(a),
this.OZ(),a.remove());a=this.uC();b=document.getElementById(this.options.describedById);null!=a&&null==b?b=this.IH():null==a&&null!==b&&0===b.children.length&&b.remove();this.UT(b)},uZ:function(){var a,b;b=this.Er.find(".oj-label-required-icon");a=this.options.describedById;this.options.required?(this.rH(),0===b.length?this.options.ariaRequiredUnsupported?(b=document.getElementById(a),null==b&&(b=this.IH()),b.appendChild(this.OA())):this.element.before(this.OA()):(a=this.A(this.xa.qS),b.attr("title",
a))):(b.remove(),b=document.getElementById(a),null!==b&&0===b.children.length&&b.remove())},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.uZ();"help"===a&&this.qZ()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-label-help-icon")[0]?
b={subId:"oj-label-help-icon"}:a===this.widget().find(".oj-label-required-icon")[0]&&(b={subId:"oj-label-required-icon"}));return b||this._superApply(arguments)},_destroy:function(){var a=this.Er.find(".oj-label-help-icon");this.NZ(a);this.OZ();b.v.unwrap(this.element,this.Er);return this._super()}})})();var d={D5:1,kP:2,nP:3,SP:4,TP:5,VP:6,r6:7,z6:8,kQ:9,lQ:10,C6:11},c={zo:!0,Li:d.kP},e={zo:!0,Li:d.nP},g={zo:!0,Li:d.VP},h={zo:!0,Li:d.SP},k={zo:!0,Li:d.TP},l={zo:!0,Li:d.lQ};b.ya("oj.editableValue",
f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:null,source:null},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,required:!1,title:"",validators:void 0,value:void 0},getNodeBySubId:function(a){return this._super(a)},isValid:function(){void 0===this.vM&&(this.vM=this.cea());return this.vM},refresh:function(){this._super();this.JU(!0)},reset:function(){this.FA();this.Gx(this.aj.r6);this.XK(this.options.value,!0)},showMessages:function(){var a=
this.options.messagesHidden,c,d=!1,e,g=[];for(e=0;e<a.length;e++)d=!0,c=a[e],c instanceof b.Fc&&c.uca(),g.push(c.clone());d&&(this.$v("messagesHidden"),this.sD("messagesShown",g))},validate:function(){return this.ec(this.ag(),null,this.gA)},Hv:{tP:1,B6:2,WP:3},aj:d,gA:{Yq:!1,Li:d.kQ},Ud:function(a,b){this._super(a,b)},_ComponentCreate:function(){var a=this.element,b=this.YQ(a);this._super();this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=[];this.options.messagesShown=
0<this.options.messagesCustom.length?this.baa(this.options.messagesCustom):[];this.qG(a);this.tp()&&(this.nn(this.options.placeholder),this.SH=!0);f.each(["required","title"],function(c,d){d in b&&a.removeAttr(d)})},hf:function(){this._super();this.Laa();this.JU(!1);this.bC();this.Gx(this.aj.D5);0<this.options.messagesShown.length&&this.Jx("messagesShown",this.options.messagesShown,null,!0);this.widget().addClass("oj-form-control")},Dv:function(a){this.b9(a)},us:function(a){this.H8(a)},qQ:function(a,
b){switch(a){case "disabled":this.rQ(a,e);break;case "converter":this.E6(a);break;case "displayOptions":this.bC();break;case "help":this.Og(a,this.options[a]);break;case "messagesCustom":this.vha(b);break;case "placeholder":this.gia(b);break;case "readOnly":this.rQ(a,h);break;case "required":this.F6(a);break;case "title":this.vla();break;case "translations":this.refresh();break;case "value":this.G6(a,b);break;case "validators":this.Wr(a)}},E6:function(a){var b=!1;this.F8();this.UB()&&(b=!0);b?(this.GA(),
this.uD(c)):this.Og(a,this.options[a],!0)},rQ:function(a,b){var c=!this.options[a];this.Og(a,this.options[a]);c&&this.h_(b)},F6:function(a){this.Og(a,this.options[a]);this.h_(g)},G6:function(a,b){var c=!1,d,e=b?b._context:null;e&&(c=e.originalEvent?!0:!1,d=e.zo||!1);c||(d||this.FA(null),this.Gx(this.aj.C6));this.Og(a,this.options[a],!0)},Wr:function(){var a=!1;this.SR();this.UB()&&(a=!0);a&&(this.GA(),this.uD(l))},qv:function(){var a=this.options.readOnly||!1;return this.options.disabled||a?!1:!0},
_destroy:function(){this.widget();var a=this._super();this.FA(null,!0);this.$s().Lk();this.Ob&&null!=b.Components.sg(this.Ob[0])&&this.Ob._ojLabel("destroy");return a},Focus:function(){this.Td().focus();return!0},_setOption:function(a,c,d){var e;e=!1;if("string"===typeof a&&void 0!==c)switch(a){case "messagesHidden":e=!0;break;case "messagesShown":e=!0;break;case "rawValue":e=!0}if(e)return b.r.error(a+" option cannot be set"),this;e=this._superApply(arguments);this.qQ(a,d);return e},Td:function(){return this.element},
s7:function(){var a=this.pV(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=f("label[for\x3d'"+a+"']"),0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=this.pV(a),null!==a&&0!==a.length)?a:null},gs:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.Td()},Qc:function(){this.Gc||(this.Gc=b.ob.getConverterInstance(this.options.converter));return this.Gc||null},vv:function(){this.qX||
(this.qX={});return this.qX},ag:function(){return this.Td().val()},WQ:function(){if(!this.Nv){var a=[],c=this.options.validators,d,e=!0,g=this.vv(),f=[],h,k;k=Object.keys(g);h=k.length;if(0<h){for(var l=0;l<h;l++)d=k[l],f.push(g[d]);a=a.concat(f)}if(c){f=[];for(k=0;k<c.length;k++)d=c[k],"object"===typeof d?(d.validate&&"function"===typeof d.validate||(e=!1),e||(h=d.type)&&"string"===typeof h&&((g=b.pa.Fr(h))?(d=b.lc.Xe({},d.options)||{},d.converter=d.converter||this.Qc(),d.label=d.label||this.TI(),
d=g.createValidator(d)):b.r.error("Unable to locate a validatorFactory for the requested type: "+h)),f.push(d)):b.r.error("Unable to parse the validator provided:"+d);a=a.concat(f)}this.Nv=a}return this.Nv||[]},SR:function(){this.Nv&&(this.Nv.length=0);this.Nv=null;this.$s().update(this.qi(this.Bh.mQ))},F8:function(){this.Gc=null;this.$s().update(this.qi(this.Bh.jP))},cn:function(){return this.options.required},Hz:function(a){var b=this.ag();this.ec(b,a)},ws:function(a,b){var c={};c._context={originalEvent:b,
Ec:!0,Za:!0};this.options.rawValue!==a&&this.option("rawValue",a,c)},Og:function(a,b,c){switch(a){case "converter":b=this.options.value;this.XK(b,c);break;case "disabled":this.zZ("disabled",this.options.disabled);break;case "help":b=this.options.help.definition;c=this.options.help.source;a=this.yI();this.Ob&&(this.Ob._ojLabel("option","describedById",a),this.Ob._ojLabel("option","help",{definition:b,source:c}));break;case "required":this.zZ("required",this.cn());this.mG(b);this.Ob&&(a=this.yI(),this.Ob._ojLabel("option",
{describedById:a,ariaRequiredUnsupported:this.uz()}),this.Ob._ojLabel("option","required",b));break;case "value":this.XK(b,c)}},mG:function(a){var b=this.Td();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},uz:function(){return!1},nG:function(){this.Ob&&this.Ob._ojLabel("refresh");this.Gc=this.ZJ=null;this.SR()},li:function(a){var b=this.Td();b.val()!==a&&b.val(a)},qG:function(a){"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled)},nn:function(a){this.Td().attr("placeholder",
a)},WR:function(a){this.options.placeholder=a},tp:function(){return this.options.placeholder},EQ:function(){this.WR("");this.nn("")},ec:function(a,c,d){var e=d&&"boolean"===typeof d.Yq?d.Yq:!0;if(void 0===a)return b.r.warn("Attempt to set a value of undefined"),!1;if(e&&a===this.oda())b.r.Ny>b.r.Tm&&b.r.info("Validation skipped and value option not updated as submitted value '"+a.toString?a.toString():a+" same as previous.");else if(a=this.sS(a,c,d),void 0!==a&&this.isValid()){var g;d&&d._context&&
(g=d._context);this.S0(a,c,d&&d.Li,g);return!0}return!1},sS:function(a,c,d){var e=d&&d.cqa?d.cqa:this.Hv.tP,g=d&&d.Li?d.Li:this.aj.z6;d=d&&d.zo||!1;if(void 0===a)b.r.warn("Attempt to set a value of undefined");else if(this.qv()){d||this.FA(c);this.D_(a);try{return this.Tja(a,e,g,c)}catch(f){}}else b.r.Ny>b.r.Tm&&b.r.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},rv:function(a,c,d){return"value"===
a?b.b.gh(c,d):0===a.indexOf("messages")?this.wha(c,d):this._superApply(arguments)},_GetDefaultStyleClass:function(){b.l.Wb();return""},Bh:{Ou:1,nQ:2,jP:3,mQ:4,iQ:5},mn:{disabled:"oj-disabled",required:"oj-required"},FA:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.$v("messagesHidden",a),this.$v("messagesShown",a),this.$v("messagesCustom",a))},GA:function(){var a=this.options.messagesShown,c=a.length,d;this.$v("messagesHidden");
for(var e=c-1;0<=e;e--)d=a[e],d instanceof b.Fc&&a.splice(e,1);a.length!==c&&this.Jx("messagesShown",a,null,!0)},Jx:function(a,b,c,d){var e={},g=0===b.length&&0===this.options[a].length;if(d||!g)e._context={originalEvent:c,Ec:!0,Za:!0},e.changed=d||!g,this.Ija(),this.option(a,b,e),this.Tla()},$v:function(a,b){this.Jx(a,[],b)},baa:function(a){var c,d=[],e;if(a&&0<a.length)for(e=0;e<a.length;e++)c=a[e],c instanceof b.X?d.push(c.clone()):(c=new b.X(c.summary,c.detail,c.severity),c=Object.freeze?Object.freeze(c):
c,d.push(c));return d},Laa:function(){if(this.Ob=this.s7()){var a=this.options.help.definition,b=this.options.help.source,c=this.uz(),d=this.r9(b,a,this.options.required,c);this.Ob._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:d,required:this.options.required,ariaRequiredUnsupported:c,help:{definition:a,source:b}})}},JU:function(a){var b=!1;a?(this.nG(),this.bC(),this.UB()&&(b=!0),this.GA(),b?this.uD(k):(this.cn()&&this.Gx(k.Li),this.Og("value",this.options.value,
!0))):(this.Og("value",this.options.value),this.Og("required",this.options.required));this.Og("disabled",this.options.disabled)},Nqa:function(){return this.NY},oda:function(){void 0===this.CK&&(this.CK="");return this.CK},pV:function(a){a=a.attr("aria-labelledby");return void 0!==a?f("label[id\x3d'"+a+"']"):null},yI:function(){this.element.uniqueId();return this.element.prop("id")+"Icons"},r9:function(a,b,c,d){var e=this.yI();(a||b||c&&d)&&this.HG(e);return e},HG:function(a){this.Td().each(function(){var b=
f(this).attr("aria-describedby");b?f(this).attr("aria-describedby",b+" "+a):f(this).attr("aria-describedby",a)})},DB:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},TI:function(){if(this.Ob)return this.Ob.text()},KW:function(){this.V0||(this.V0=new b.Mi(this.isValid(),this.DB()));return this.V0},RJ:function(){return!b.X.isValid(this.DB())},UB:function(){return!this.isValid()&&0<this.options.messagesShown.length},Dfa:function(){for(var a=this.options.messagesShown,
c,d,e=0;e<a.length;e++)c=a[e],c instanceof b.Fc&&c.SX()&&(d=d||[],d.push(c));return void 0===d?!1:!b.X.isValid(d)},bC:function(){var a=this.$s(),b=this._GetMessagingLauncherElement(),c=this.qi(this.Bh.Ou);this.SH||this.EQ();a.to(b,c)},vha:function(a){var c=this.options.messagesCustom,d=[],e,g,f=this.options.messagesShown,h=a?a._context:null;for(g=0;g<f.length;g++)e=f[g],e instanceof b.Fc&&e.SX()&&d.push(e);for(g=0;g<c.length;g++)d.push(c[g]);this.Jx("messagesShown",d,h?h.originalEvent:null,a&&a.changed)},
gia:function(a){a=(a&&a._context||{}).Aoa?!1:!0;this.nn(this.options.placeholder);a?(this.SH=!0,this.Qc()&&this.bC()):this.SH=!1},uka:function(a){this.NY=a},D_:function(a){this.CK=a},vla:function(){this.$s().update(this.qi(this.Bh.iQ))},sD:function(a,b,c){var d,e,g;if("object"===typeof b&&Array.isArray(b))for(g=this.options[a],d=b.length,e=0;e<d;e++)g.push(b[e]);this.Jx(a,g,c,!0)},Tla:function(){this.$s().update(this.qi())},S0:function(a,b,c,d){d=d||{};b&&(d.originalEvent=b);switch(c){case this.aj.kP:case this.aj.nP:case this.aj.SP:case this.aj.TP:case this.aj.VP:case this.aj.kQ:case this.aj.lQ:d.Ec=
!0,d.zo=!0}this.option({value:a},{_context:d})},Ija:function(){this.vM=void 0},cea:function(){var a=this.DB(),b=!0;a&&0!==a.length&&(b=!this.RJ());return b},Yp:function(a){var c=a,d=this.Qc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(a):b.r.Ny>b.r.Tm&&b.r.info("converter does not support the format method."));return c},$s:function(){this.Sp||(this.Sp=new b.Sa(this));return this.Sp},kda:function(a){var b,c=[];b="";var d;this.cn()&&(b=this.QV(),b.getHint&&"function"===
typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b);return c},QV:function(){var a;a={};var c;null==this.ZJ&&(a=this.options.translations?this.options.translations.required||{}:{},c={hint:a.hint||null,label:this.TI(),messageSummary:a.messageSummary||null,messageDetail:a.messageDetail||null},this.ZJ=(a=b.pa.Fr(b.Zc.VALIDATOR_TYPE_REQUIRED))?a.createValidator(c):null);return this.ZJ},qi:function(a){var b=
{},c=this.Qc(),d="",e=[];a=a||this.Bh.nQ;if(a===this.Bh.Ou||a===this.Bh.nQ)e=this.DB(),this.KW().update(this.isValid(),e),b.t5=this.KW();if(a===this.Bh.Ou||a===this.Bh.jP)c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(d=c.getHint()||""),b.B1=d;if(a===this.Bh.Ou||a===this.Bh.mQ)c=this.WQ(),e=this.kda(c)||[],b.dqa=e;if(a===this.Bh.Ou||a===this.Bh.iQ)b.title=this.options.title||"";return b},wha:function(a,c){var d=-1,e,g=!0,h=f.extend([],a),k=f.extend([],c);if(h.length!==k.length)return!1;
f.each(h,function(a,c){c instanceof b.X?e=c:(e=new b.X(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):e);d=-1;f.each(k,function(a,b){e.Ao(b)&&(d=a)});-1<d?k.splice(d,1):g=!1});return g},BC:function(a){var c=this.Qc(),d=a;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(a):b.r.Ny>b.r.Tm&&b.r.info("converter does not support the parse method."));return d},JG:function(a,c){var d,e,g;a instanceof b.Je||a instanceof b.yh?(d=a.uu(),b.l.xd(d,b.X),g=d.severity,e=d.summary,
d=d.detail):(g=b.X.Qb.ERROR,e=b.ha.A("oj-message.error"),d=a.message||b.ha.A("oj-converter.detail"));c.push({summary:e,detail:d,severity:g})},RK:function(a,c,d){var e={},g=[],f=a.bx||[];e.context=c||0;e.display=d||b.Fc.Jr.tF;0===f.length&&this.JG(a,f);for(c=0;c<f.length;c++)a=f[c],g.push(this.yaa(a.summary,a.detail,a.severity,e));return g||null},yaa:function(a,c,d,e){a=new b.Fc(a,c,d,e);return a=Object.seal?Object.seal(a):a},XK:function(a,b){var c=a||this.options.value,d;d=this.NY;(b||c!==d)&&this.Rla(c)},
zZ:function(a,b){-1!==Object.keys(this.mn).indexOf(a)&&this.widget().toggleClass(this.mn[a],!!b)},Gx:function(a){if(this.qv())try{this.U0(this.options.value,this.Hv.WP)}catch(c){(a=this.RK(c,a,b.Fc.Jr.fF))&&this.sD("messagesHidden",a)}else b.r.Ny>b.r.Tm&&b.r.info("Deferred validation skipped as component is readonly or disabled.")},Tja:function(a,b,c,d){var e=a;try{b===this.Hv.tP&&(e=this.BC(a)),this.U0(e,b===this.Hv.WP)}catch(g){throw a=this.RK(g,c),this.sD("messagesShown",a,d),g;}return e},h_:function(a){var b=
!0;this.UB()&&(b=!1);this.GA();b?this.cn()&&this.Gx(a.Li):this.uD(a)},Rla:function(a,b){var c,d;this.uka(a);c=a;try{c=this.Yp(a)}catch(e){d=this.RK(e),this.sD("messagesShown",d,b)}this.li(c);c=this.ag();this.D_(c);this.ws(c,null)},uD:function(a){var b;b=this.sS(this.ag(),null,a);void 0===b||!this.isValid()&&this.Dfa()||this.S0(b,null,a.Li)},U0:function(a,c){var d=this.WQ(),e,g,f=[];if(this.cn()){e=this.QV();try{e.validate(b.Ea.trim(a))}catch(h){this.JG(h,f)}}if(!c)for(g=0;g<d.length;g++)if(e=d[g],
"object"===typeof e)if(e.validate&&"function"===typeof e.validate)try{e.validate(a)}catch(k){this.JG(k,f)}else b.r.Ny>b.r.Tm&&b.r.info("validator does not support the validate method.");if(0<f.length)throw d=Error(),d.bx=f,d;}},!0);b.Components.Em({editableValue:{displayOptions:{messages:["inline"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}}});b.bf=function(a){this.Init(a)};b.Sa.AE(b.Sa.$c.Yu,b.bf);b.b.ga(b.bf,b.mc,"oj.InlineMessagingStrategy");b.bf.prototype.vr=
function(a){b.bf.q.vr.call(this,a);this.rZ()};b.bf.prototype.MO=function(a){return a&&void 0!==a.t5?!0:!1};b.bf.prototype.update=function(){b.bf.q.update.call(this);this.rZ()};b.bf.prototype.Lk=function(){this.QZ();b.bf.q.Lk.call(this)};b.bf.prototype.rZ=function(){var a,b;a=this.Si().widget();this.LU()||(this.He=f("\x3cdiv class\x3d'oj-messaging-inline-container'\x3e\x3c/div\x3e"),this.HG(this.He),a.append(this.He));(b=this.t$())?(a=this.He[0],a.innerHTML="",a.innerHTML=b):this.QZ()};b.bf.prototype.QZ=
function(){this.LU()&&this.He&&(this.cja(this.He),this.He.remove(),this.He=null)};b.bf.prototype.HG=function(a){var c=this.Vh();b.l.xd(c,jQuery);b.l.xd(a,jQuery);a=a.uniqueId().attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(a);d=f.trim(d.join(" "));c.attr("aria-describedby",d)};b.bf.prototype.cja=function(a){var c=this.Vh();b.l.xd(c,jQuery);b.l.xd(a,jQuery);a=a.attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];a=f.inArray(a,d);-1!==a&&d.splice(a,1);(d=f.trim(d.join(" ")))?
c.attr("aria-describedby",d):c.removeAttr("aria-describedby")};b.bf.prototype.t$=function(){var a=this.Si().document[0];return this.eQ()?this.ZG(a):""};b.bf.prototype.ZG=function(a){var c;c="";var d=this.bF();this.kF()&&(c=this.cF(),c=b.Na.m1(a,c,d,!0));return c};b.bf.prototype.LU=function(){return null!=this.He}});