/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise"],function(b,f){b.Ed=function(){this.Init()};b.b.ga(b.Ed,b.Hg,"oj.FilmStripPagingModel");b.Ed.prototype.Init=function(){b.Ed.q.Init.call(this);this.Kc=-1;this.ge=0;this.La=-1};b.b.g("FilmStripPagingModel.prototype.Init",{Init:b.Ed.prototype.Init});b.Ed.prototype.Apa=function(a){this.ge=a};b.Ed.prototype.getPage=function(){return this.Kc};b.b.g("FilmStripPagingModel.prototype.getPage",{getPage:b.Ed.prototype.getPage});b.Ed.prototype.setPage=
function(a,b){a=parseInt(a,10);try{var c=this.getPageCount(),e=this.Kc,f=this.La,h=f;b&&b.pageSize&&(h=b.pageSize);var k=Math.ceil(this.ge/h);if(0>a||a>k-1)throw Error("JET FilmStrip: Invalid 'page' set: "+a);var l=!1;if(a!=e||h!=f){if(!1===this.handleEvent("beforePage",{page:a,previousPage:e}))return Promise.reject();l=!0}this.Kc=a;this.La=h;var m=this.getPageCount(),n=this;return new Promise(function(b){c!=m&&n.handleEvent("pageCount",{pageCount:m,previousPageCount:c});l&&n.handleEvent("page",{page:a,
previousPage:e});b(null)})}catch(p){return Promise.reject(p)}};b.b.g("FilmStripPagingModel.prototype.setPage",{setPage:b.Ed.prototype.setPage});b.Ed.prototype.getStartItemIndex=function(){return this.Kc*this.La};b.b.g("FilmStripPagingModel.prototype.getStartItemIndex",{getStartItemIndex:b.Ed.prototype.getStartItemIndex});b.Ed.prototype.getEndItemIndex=function(){return Math.min(this.getStartItemIndex()+this.La,this.ge)-1};b.b.g("FilmStripPagingModel.prototype.getEndItemIndex",{getEndItemIndex:b.Ed.prototype.getEndItemIndex});
b.Ed.prototype.getPageCount=function(){return Math.ceil(this.ge/this.La)};b.b.g("FilmStripPagingModel.prototype.getPageCount",{getPageCount:b.Ed.prototype.getPageCount});b.Ed.prototype.totalSize=function(){return this.ge};b.b.g("FilmStripPagingModel.prototype.totalSize",{totalSize:b.Ed.prototype.totalSize});b.Ed.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("FilmStripPagingModel.prototype.totalSizeConfidence",{totalSizeConfidence:b.Ed.prototype.totalSizeConfidence});(function(){function a(a){var b=
f("\x3cdiv\x3e\x3c/div\x3e");b.text(a);return b[0].innerHTML}function d(a){a.css("-webkit-transform",p).css("-ms-transform",p).css("transform",p)}function c(a,b){a.css("-webkit-transform",b).css("-ms-transform",b).css("transform",b)}b.ya("oj.ojFilmStrip",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{maxItemsPerPage:0,orientation:"horizontal",currentItem:0,arrowPlacement:"adjacent",arrowVisibility:"auto"},_ComponentCreate:function(){this._super();var a=this.element;
a.addClass("oj-filmstrip oj-component").attr("tabindex",0).attr("role","region");a.uniqueId();a=this.options;a.disabled&&b.r.warn(da);if(a.orientation!==v&&a.orientation!==fa)throw Error(s+a.orientation);if(a.arrowPlacement!==e&&a.arrowPlacement!==Y)throw Error(q+a.arrowPlacement);if(a.arrowVisibility!==ba&&a.arrowVisibility!==x&&a.arrowVisibility!==y&&a.arrowVisibility!==h)throw Error(t+a.arrowVisibility);this.cz=this.eventNamespace+"Touch";this.rE=this.eventNamespace+"Mouse";this.A3=this.eventNamespace+
"Key";this.oO=this.eventNamespace+"NavArrowHoverable";this.Aa(!0)},refresh:function(){this._super();this.Aa(!1)},getItemsPerPage:function(){return this.vq},getPagingModel:function(){return this.ce},ml:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},gn:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},Aa:function(a){if(this.Vv()){this.Uc=null;this.tf="rtl"===this.ac();this.tn=b.v.Od();var c=this.element,d=this;a?(this.vq=0,this.JJ=function(a){d.IJ(a)},this.ce=new b.Ed,this.yn=0,this.Ww=
-1,this.qk=function(){d.pq()},this.Wg=function(){d.Se()},this.tn&&(this.fX=function(a){d.QJ(a)},this.eX=function(a){d.PJ(a)},this.OJ=function(a){d.NJ(a)},this.L9()),this.WW=function(a){d.hfa(a)},this.XW=function(a){d.ifa(a)},this.ZW=function(a){d.kfa(a)},this.H9(),this.VW=function(a){d.nq(a)},this.F9()):this.xU();for(var e=c.children(),f=0;f<e.length;f++)b.Components.Bg(e[f]);a&&(a=this.ce,a.Apa(e.length),a.on("page",this.JJ));this.bma();this.HS();for(f=0;f<e.length;f++)b.Components.Nf(e[f]);b.v.eh(c[0],
this.Wg)}else c=!1,this.Uc&&(c=this.Uc[0]),this.Uc=[a||c]},_destroy:function(){this.tn&&(this.yja(),this.OJ=this.eX=this.fX=null);this.sja();this.ZW=this.XW=this.WW=null;this.qja();this.VW=null;this.xU();this.ce.off("page",this.JJ);this.qk=this.Wg=this.ce=this.JJ=null;var a=this.element;a.removeClass("oj-filmstrip oj-component "+J).removeAttr("tabindex role");a.removeUniqueId();this._super()},xU:function(){b.v.Qh(this.element[0],this.Wg);this.Ww=-1;this.ux&&(clearTimeout(this.ux),this.ux=null);for(var a=
this.BB(),c=0;c<a.length;c++)b.Components.Bg(a[c]);this.vT();this.RI().unwrap();this.Kla();for(c=0;c<a.length;c++)b.Components.Nf(a[c])},_setOption:function(a,c,d){var f=this.options,g=!1,k=-1,l=this.ce,m=l.getPage();switch(a){case "disabled":b.r.warn(da);break;case "orientation":if(c!==v&&c!==fa)throw Error(s+c);g=f.orientation!=c;break;case "maxItemsPerPage":g=f.maxItemsPerPage!=c;break;case "arrowPlacement":if(c!==e&&c!==Y)throw Error(q+c);g=f.arrowPlacement!=c;break;case "arrowVisibility":if(c!==
ba&&c!==x&&c!==y&&c!==h)throw Error(t+c);g=f.arrowVisibility!=c;break;case B:if(f.currentItem!=c&&(k=this.sI(c),0>k||k>=l.getPageCount()))throw Error(r+c);}this._super(a,c,d);switch(a){case B:-1<k&&k!=m&&l.setPage(k)}g&&this.Aa(!1)},Se:function(){if(!this.VS)this.VS=!0,this.HS(!0),this.VS=!1;else if(!this.ux){var a=this;this.ux=setTimeout(function(){a.ux=null;a.Se()},0)}},Hb:function(){return this.options.orientation!==fa},tw:function(){return this.Hb()?this.tf?"right":"left":"top"},$p:function(){return this.Hb()?
"width":"height"},Vv:function(){var a=document.createElement("div"),b=a.style;b.position="absolute";b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},bma:function(){var a=this.element,b=this.Hb();a.children().addClass(C).wrap("\x3cdiv class\x3d'"+E+" "+N+"'\x3e\x3c/div\x3e");var c=this.tw();this.rj=c=a.children().wrapAll("\x3cdiv class\x3d'"+E+" "+H+"' style\x3d'"+c+": 0px;'\x3e\x3c/div\x3e").parent();
var d=this.options;d.arrowVisibility!==x&&d.arrowPlacement===e&&(this.DH=c.wrap("\x3cdiv class\x3d'"+E+" oj-filmstrip-content-container'\x3e\x3c/div\x3e").parent());a.addClass(E);b||a.addClass(R);d.arrowVisibility!==x&&(this.yk=this.Xaa(),this.qj=this.Jaa(),this.wK()&&this.Oka())},Kla:function(){var a=this.element,b=this.BB();this.mla();this.yk&&(this.Fp(this.yk),this.yk=null);this.qj&&(this.Fp(this.qj),this.qj=null);var c=a.children(T+A);c&&c.remove();b.removeClass(C).unwrap().unwrap();this.rj=null;
this.DH&&(b.unwrap(),this.DH=null);a.removeClass(E+" "+R)},Oka:function(){this.element.on("mouseenter"+this.oO,function(a){f(a.currentTarget).hasClass("oj-disabled")||f(a.currentTarget).addClass(J)}).on("mouseleave"+this.oO,function(a){f(a.currentTarget).removeClass(J)})},mla:function(){this.element.off(this.oO)},wK:function(){var a=this.options,b=a.arrowVisibility;return b===y||b===h&&a.arrowPlacement===Y},Ffa:function(){return 0<this.ce.getPage()},Efa:function(){var a=this.ce;return a.getPage()<
a.getPageCount()-1},qia:function(){if(this.Ffa()){var a=this.ce;a.setPage(a.getPage()-1)}},Pha:function(){if(this.Efa()){var a=this.ce;a.setPage(a.getPage()+1)}},FU:function(a,b){this.options.arrowPlacement===e?b.css("visibility",a?"":x):b.parent().css("display",a?"":M)},Ula:function(){if(this.options.arrowVisibility!==x){var a=this.ce,b=a.getPage(),a=a.getPageCount();this.FU(0!==b,this.yk);this.FU(b!==a-1,this.qj)}},Xaa:function(){var b=this.element,c=this.Hb()?U:ha,d=this.XT(c);this.options.arrowPlacement===
Y?b.append(d):b.prepend(d);var b=a(this.A("labelAccArrowPreviousPage")),e=a(this.A("tipArrowPreviousPage")),c=this.WT(d,c,b,e),f=this;c.on("click",function(){f.qia()});return c},Jaa:function(){var b=this.element,c=this.Hb()?F:I,d=this.XT(c);b.append(d);var b=a(this.A("labelAccArrowNextPage")),e=a(this.A("tipArrowNextPage")),c=this.WT(d,c,b,e),f=this;c.on("click",function(){f.Pha()});return c},XT:function(a){var b=f(document.createElement("div"));b.addClass(A+" "+a);this.options.arrowPlacement===Y&&
(b.addClass("oj-filmstrip-arrow-container-overlay"),this.wK()&&b.addClass(z));return b},WT:function(a,b,c,d){var f="\x3cdiv class\x3d'"+D+" oj-default oj-enabled "+b+"' role\x3d'button' tabindex\x3d'-1'";a.append(f+("\x3e\x3cspan class\x3d'oj-filmstrip-arrow-icon "+b+" oj-component-icon'\x3e\x3c/span\x3e\x3c/div\x3e"));b=this.element.attr("id");a=a.children(T+D).eq(0);a.uniqueId();f=a.attr("id");c&&a.attr("aria-label",c);d&&a.attr("title",d);a.attr("aria-labelledby",f+" "+b);this._hoverable(a);this.Jp(a);
this.options.arrowPlacement===e&&this.wK()&&a.addClass(z);return a},RI:function(){return this.rj.find(T+N)},BB:function(){return this.rj.find(T+C)},Jn:function(){return this.rj.children(T+Q)},vT:function(){var a=this.rj;this.Jn().css(w,p).css(ca,p);this.RI().css(w,p).css(ca,p);a.css(this.$p(),p)},HS:function(a){this.vT();var c=this.options,d=this.Hb(),h=c.maxItemsPerPage,l=1>h,m=this.element,n=this.RI();if(0>this.Ww){var q=this.SV(c.currentItem),q=f(n[q]),r=q.children(T+C);r.css(k,p);b.Components.Hm(r[0]);
this.Ww=d?q.width():q.height()}q=d?m.width():m.height();c.arrowVisibility!==x&&c.arrowPlacement===e&&(m=m.children(T+A).eq(0),d=d?m.width():m.height(),q-=2*d);this.yn=q;l||(d=Math.max(Math.floor(q/this.Ww),1),d<h&&(h=d));h=l?Math.max(Math.floor(q/this.Ww),1):h;l=q/h;n.css(w,l+aa).css(ca,l+aa);l=Math.ceil(n.length/h);r=this.Jn();d=!1;m=this.ce;if(m.getPageCount()!=l||this.vq!=h||!r||1>r.length){d=!0;if(a)for(var s=0;s<n.length;s++)b.Components.Bg(n[s]);r&&0<r.length&&n.unwrap();for(s=0;s<n.length;s+=
h)n.slice(s,s+h).wrapAll("\x3cdiv class\x3d'"+E+" "+Q+"' style\x3d'"+k+": "+M+";' "+g+"\x3d'true'\x3e\x3c/div\x3e");if(a)for(s=0;s<n.length;s++)b.Components.Nf(n[s])}r=this.Jn();r.css(w,q+aa).css(ca,q+aa);a=this.DH;this.rj.css(this.$p(),q);a&&a.css(this.$p(),q);a=0;if(c.currentItem||0===c.currentItem)a=this.sI(c.currentItem,h);m.getPageCount()!=l||this.vq!=h||m.getPage()!=a?m.setPage(a,{pageSize:h}):d&&(c=m.getPage(),this.IJ({previousPage:c,page:c}))},IJ:function(a){var b=a.page,c=a.previousPage;
a=this.rj;var d=this.Jn(),e=this.ce.La,g=0>c||c==b||this.vq!=e;this.vq=e;e=null;g||(e=f(d[c]));var h=this.tw(),k=f(d[b]),l=k.is(u);l&&this.mM(k);var m=this.Fs;-1<c&&!g&&(m=!0,a.css(this.$p(),2*this.yn),b<c&&l&&a.css(h,-this.yn+aa),b>c?(e.addClass(O),k.addClass(G)):(e.addClass(W),k.addClass(P)));if(m){var n=this,p=this.Fs;p&&0>c&&d.filter(S).addClass(L);setTimeout(function(){n.fV(b,c,g,p)},25)}else this.fV(b,c,g)},fV:function(a,b,e,g){var h=this.rj;e||(this.WS=!0,h.on("transitionend"+this.eventNamespace+
" webkitTransitionEnd"+this.eventNamespace,this.qk));e?this.pq():(e=this.Jn(),g&&d(e),-1<b?(g=a>b,b=f(e[b]),a=f(e[a]),b.addClass(L),a.addClass(L),g?(b.removeClass(O),a.removeClass(G),b.addClass(V),a.addClass(K)):(b.removeClass(W),a.removeClass(P),b.addClass(X),a.addClass(Z))):g&&(a=e.filter(S),c(a,"translate3d(0, 0, 0)")))},pq:function(){this.WS=!1;var a=this.rj,c=this.tw();a.off(this.eventNamespace).css(this.$p(),this.yn).css(c,"0px");c=null;if(b.pd.JD(a[0])||this.qj&&b.pd.JD(this.qj[0])||this.yk&&
b.pd.JD(this.yk[0]))c=document.activeElement;for(var a=this.ce.getPage(),e=this.Jn(),g=0;g<e.length;g++)g!=a&&this.lX(f(e[g]));e.removeClass(L+" "+V+" "+K+" "+X+" "+Z);d(e);this.Ula();c&&f(c).is(u)&&(c=this.element,(e=b.pd.v2(e[a]))?b.pd.ny(e):b.pd.ny(c[0]));this.sI(this.options.currentItem)!=a&&(a=this.JV(a),this.option(B,a,{_context:{Ec:!0}}))},SV:function(a){var c=-1,d=this.BB();if("number"===typeof a)0<=a&&a<d.length&&(c=a);else if("string"===typeof a&&b.v.kE(a))for(var e=0;e<d.length;e++){var f=
d[e].id;if(f&&0<f.length&&f===a){c=e;break}}return c},sI:function(a,b){var c=this.SV(a),d=-1;-1<c&&(void 0===b&&(b=this.vq),d=Math.floor(c/b));return d},JV:function(a,b,c){var d=this.ce;void 0===b&&(b=d.getPageCount());return 0<=a&&a<b&&(b=this.BB(),void 0===c&&(c=this.vq),a*=c,a<b.length)?(c=b[a].id)&&0<c.length?c:a:-1},lX:function(a){b.Components.Xo(a[0]);a.css(k,M).attr(g,"true");a.find(T+C).css(k,M)},mM:function(a){a.css(k,p).removeAttr(g);a.find(T+C).css(k,p);b.Components.Hm(a[0])},F9:function(){this.element.on("keydown"+
this.A3,this.VW)},qja:function(){this.element.off(this.A3)},H9:function(){this.element.on("mousedown"+this.rE,this.WW).on("mousemove"+this.rE,this.XW).on("mouseup"+this.rE,this.ZW)},sja:function(){this.element.off(this.rE)},L9:function(){this.element.on("touchstart"+this.cz,this.fX).on("touchmove"+this.cz,this.eX).on("touchend"+this.cz,this.OJ).on("touchcancel"+this.cz,this.OJ)},yja:function(){this.element.off(this.cz)},nq:function(a){var b=this.ce,c=b.getPage(),d=-1;switch(a.keyCode){case f.ui.keyCode.RIGHT:d=
this.tf?c-1:c+1;break;case f.ui.keyCode.LEFT:d=this.tf?c+1:c-1;break;case f.ui.keyCode.DOWN:d=c+1;break;case f.ui.keyCode.UP:d=c-1;break;case f.ui.keyCode.HOME:d=0;break;case f.ui.keyCode.END:d=b.getPageCount()-1;break;default:return}-1<d&&d<b.getPageCount()&&b.setPage(d);a.preventDefault()},hfa:function(a){this.RU(a.originalEvent)},ifa:function(a){this.QU(a,a.originalEvent)},kfa:function(){this.PU()},QJ:function(a){a=a.originalEvent.touches;1===a.length&&this.RU(a[0])},PJ:function(a){this.QU(a,a.originalEvent.touches[0]);
(this.cj||this.Ot)&&a.preventDefault()},NJ:function(){this.PU()},RU:function(a){1<this.ce.getPageCount()&&!this.WS&&(this.cj=!0,this.Fs=!1,this.kD=this.Hb()?a.pageX:a.pageY)},Xfa:function(a){this.kD=this.Hb()?a.pageX:a.pageY;a=this.tw();var b=this.rj,c=this.ce,d=this.Jn(),e=1;0<c.getPage()&&(this.mM(f(d[c.getPage()-1])),b.css(a,-this.yn+aa),e++);c.getPage()<c.getPageCount()-1&&(this.mM(f(d[c.getPage()+1])),e++);1<e&&b.css(this.$p(),e*this.yn);this.ZL=parseInt(b.css(a),10)},QU:function(a,b){if(this.cj){var d=
this.Hb(),e=(d?b.pageX:b.pageY)-this.kD;if(this.Fs){var g=d&&this.tf?0<e:0>e,h=this.ce,k=h.getPage();if(g&&k<h.getPageCount()-1||!g&&0<k){var p=this.element[0],q=Math.min(m*(d?p.offsetWidth:p.offsetHeight),n),r=this.tw(),s=this.rj,p=this.Jn();Math.abs(e)>=q?(d=g?k+1:k-1,this.JV(d),k=g?k-1:k+1,-1<k&&k<h.getPageCount()&&this.lX(f(p[k])),g&&-1<k&&(p=parseInt(s.css(r),10),s.css(r,p+this.yn+aa)),s.css(this.$p(),2*this.yn),this.cj=!1,h.setPage(d)):(h=d&&this.tf?-e:e,h=d?"translate3d("+h+"px, 0, 0)":"translate3d(0, "+
h+"px, 0)",c(p.filter(S),h));this.Ot=!0}this.Ot&&(a.preventDefault(),a.stopPropagation())}else Math.abs(e)>l&&(this.Xfa(b),this.Fs=!0)}},PU:function(){if(this.cj&&this.Fs){var a=this.ce.getPage();this.IJ({previousPage:a,page:a})}this.Ot=this.Fs=this.cj=!1},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-filmstrip-start-arrow"===a?this.widget().find(T+D+T+U)[0]:"oj-filmstrip-end-arrow"===a?this.widget().find(T+D+T+F)[0]:"oj-filmstrip-top-arrow"===
a?this.widget().find(T+D+T+ha)[0]:"oj-filmstrip-bottom-arrow"===a?this.widget().find(T+D+T+I)[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-filmstrip-start-arrow"}),c=this.getNodeBySubId({subId:"oj-filmstrip-end-arrow"}),d=this.getNodeBySubId({subId:"oj-filmstrip-top-arrow"}),e=this.getNodeBySubId({subId:"oj-filmstrip-bottom-arrow"}),f=this.element[0];a&&a!=f;){if(a===b)return{subId:"oj-filmstrip-start-arrow"};if(a===c)return{subId:"oj-filmstrip-end-arrow"};if(a===d)return{subId:"oj-filmstrip-top-arrow"};
if(a===e)return{subId:"oj-filmstrip-bottom-arrow"};a=a.parentElement}return null}});var e="adjacent",g="aria-hidden",h="auto",k="display",l=3,m=.33,n=100,p="",r="JET FilmStrip: Value of 'currentItem' option not found: ",s="JET FilmStrip: Unsupported value set as 'orientation' option: ",q="Unsupported value set as 'arrowPlacement' option: ",t="Unsupported value set as 'arrowVisibility' option: ",w="flex-basis",x="hidden",u=":hidden",v="horizontal",y="hover",B="currentItem",M="none",I="oj-bottom",F=
"oj-end",D="oj-filmstrip-arrow",A="oj-filmstrip-arrow-container",z="oj-filmstrip-arrow-transition",E="oj-filmstrip-container",J="oj-filmstrip-hover",C="oj-filmstrip-item",N="oj-filmstrip-item-container",Q="oj-filmstrip-page",H="oj-filmstrip-pages-container",L="oj-filmstrip-transition",G="oj-filmstrip-transition-next-newpage-from",O="oj-filmstrip-transition-next-oldpage-from",P="oj-filmstrip-transition-prev-newpage-from",W="oj-filmstrip-transition-prev-oldpage-from",K="oj-filmstrip-transition-next-newpage-to",
V="oj-filmstrip-transition-next-oldpage-to",Z="oj-filmstrip-transition-prev-newpage-to",X="oj-filmstrip-transition-prev-oldpage-to",R="oj-filmstrip-vertical",U="oj-start",ha="oj-top",Y="overlay",T=".",aa="px",fa="vertical",ba="visible",S=":visible",ca="-webkit-flex-basis",da="JET FilmStrip: 'disabled' option not supported"})()});