/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojrowexpander"],function(b){b.af=function(f,a,d,c,e){b.l.ey(d);this.Yb=f;this.oe=a;this.oE=d;this.xb=c;this.wg=e};o_("FlattenedTreeHeaderSet",b.af,b);b.af.prototype.getData=function(f,a){var d;b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return null!=this.wg&&null!=this.xb?(d=this.xb.getData(f-this.Yb+this.xb.ta()),null!=d?d.get?d.get(this.wg):d[this.wg]:null):this.oE[f]};b.b.g("FlattenedTreeHeaderSet.prototype.getData",
{getData:b.af.prototype.getData});b.af.prototype.getMetadata=function(f,a){b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return null!=this.wg&&null!=this.xb?this.xb.getMetadata(f-this.Yb+this.xb.ta()):{key:this.getData(f)}};b.b.g("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:b.af.prototype.getMetadata});b.af.prototype.R=function(){return null!=this.wg&&null!=this.xb?Math.min(this.xb.R(),this.oe-this.Yb):Math.max(0,this.oe-this.Yb)};
b.b.g("FlattenedTreeHeaderSet.prototype.getCount",{R:b.af.prototype.R});b.af.prototype.pg=function(){return 0<this.R()?1:0};b.b.g("FlattenedTreeHeaderSet.prototype.getLevelCount",{pg:b.af.prototype.pg});b.af.prototype.Rb=function(f,a){b.l.assert(f<=this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};b.b.g("FlattenedTreeHeaderSet.prototype.getExtent",{Rb:b.af.prototype.Rb});b.af.prototype.ie=function(f,a){b.l.assert(f<=
this.oe&&f>=this.Yb,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return 1};b.b.g("FlattenedTreeHeaderSet.prototype.getDepth",{ie:b.af.prototype.ie});b.Uh=function(f,a,d,c,e,g){b.l.ey(g);this.Ji=f;this.lr=a;this.Xk=d;this.kr=c;this.xb=e;this.Pd=g};o_("FlattenedTreeCellSet",b.Uh,b);b.Uh.prototype.getData=function(f){var a;a=this.mW(f);if(null==a)return null;f=a[0];a=a[1];b.l.assert(f<this.xb.ta()+this.xb.R()&&a<this.Pd.length);a=this.Pd[a];f=this.xb.getData(f);return null!=
f?f.get?f.get(a):f[a]:null};b.b.g("FlattenedTreeCellSet.prototype.getData",{getData:b.Uh.prototype.getData});b.Uh.prototype.getMetadata=function(f){var a;a=this.mW(f);if(null==a)return null;f=a[0];a=a[1];b.l.assert(f<this.xb.ta()+this.xb.R()&&a<this.Pd.length);a=this.Pd[a];f=this.xb.getMetadata(f);f.keys={row:f.key,column:a};return f};b.b.g("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:b.Uh.prototype.getMetadata});b.Uh.prototype.mW=function(f){var a;b.l.Df(f);if(null==this.xb||0==this.xb.length)return null;
a=f.row-this.Ji+this.xb.ta();f=f.column;b.l.Zl(a,null);b.l.Zl(f,null);b.l.assert(0<=a&&0<=f);return[a,f]};b.Uh.prototype.ta=function(b){return"row"===b?this.Ji:"column"===b?this.Xk:0};b.b.g("FlattenedTreeCellSet.prototype.getStart",{ta:b.Uh.prototype.ta});b.Uh.prototype.R=function(b){return"row"===b?Math.min(this.lr-this.Ji,this.xb.R()):"column"===b?this.kr-this.Xk:0};b.b.g("FlattenedTreeCellSet.prototype.getCount",{R:b.Uh.prototype.R});b.$a=function(f,a){b.$a.q.constructor.call(this,f,a)};o_("FlattenedTreeDataGridDataSource",
b.$a,b);b.b.ga(b.$a,b.ca,"oj.FlattenedTreeDataGridDataSource");b.$a.prototype.Init=function(){b.$a.q.Init.call(this);this.Pd=b.$a.q.ty.call(this,"columns");this.wg=b.$a.q.ty.call(this,"rowHeader")};b.b.g("FlattenedTreeDataGridDataSource.prototype.Init",{Init:b.$a.prototype.Init});b.$a.prototype.og=function(b){return"row"===b?"estimate":"actual"};b.b.g("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",{og:b.$a.prototype.og});b.$a.prototype.R=function(b){return"row"===b?-1:"column"===b?
this.Pd.length:0};b.b.g("FlattenedTreeDataGridDataSource.prototype.getCount",{R:b.$a.prototype.R});b.$a.prototype.Gf=function(f,a,d){var c,e;c=f.axis;if("column"===c)c=f.start+f.count,c>this.R("column")&&(c=this.R("column")-f.start),e=new b.af(f.start,c,this.Pd);else if("row"===c){if(null!=this.wg){this.Vk={range:f,callbacks:a,callbackObjects:d};return}e=new b.Cd(f.start,f.start,c,null)}null!=e&&null!=a&&null!=a.success&&(null==d&&(d={}),a.success.call(d.success,e,f))};b.b.g("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",
{Gf:b.$a.prototype.Gf});b.$a.prototype.ng=function(f,a,d){var c,e,g,h;for(c=0;c<f.length;c++)if(e=f[c],"row"==e.axis){g=e.start;h=e.count;break}b.$a.q.Bo.call(this,{start:g,count:h},{success:function(b){this.EJ(b,f,a,d,0)}.bind(this),error:function(b){this.Qea(b,{start:g,count:h},a,d)}.bind(this)})};b.b.g("FlattenedTreeDataGridDataSource.prototype.fetchCells",{ng:b.$a.prototype.ng});b.$a.prototype.keys=function(f){var a,d;a=f.row;d=f.column;return new Promise(function(c){a>b.$a.q.Cna.call(this).end||
d>this.Pd.length?c(null):c({row:b.$a.q.getKey.call(this,a),column:this.Pd[d]})}.bind(this))};b.b.g("FlattenedTreeDataGridDataSource.prototype.keys",{keys:b.$a.prototype.keys});b.$a.prototype.tg=function(f){var a,d,c,e,g;c=f.row;e=f.column;return new Promise(function(f){a=b.$a.q.Fi.call(this,c);for(g=0;g<this.Pd.length;g++)if(this.Pd[g]===e){d=g;break}0<=a||0<=d?f({row:a,column:d}):f(null)}.bind(this))};b.b.g("FlattenedTreeDataGridDataSource.prototype.indexes",{tg:b.$a.prototype.tg});b.$a.prototype.sort=
function(f,a,d){return b.$a.q.getWrappedDataSource.call(this).sort(f,{success:function(){this.xfa(a,d)}.bind(this),error:a.error})};b.b.g("FlattenedTreeDataGridDataSource.prototype.sort",{sort:b.$a.prototype.sort});b.$a.prototype.xfa=function(b,a){this.refresh();b.success&&(null==a&&(a={}),b.success.call(a.success))};b.$a.prototype.move=function(f,a,d,c){b.$a.q.getWrappedDataSource.call(this).move(f,a,d,c)};b.b.g("FlattenedTreeDataGridDataSource.prototype.move",{move:b.$a.prototype.move});b.$a.prototype.getCapability=
function(f){return"default"===b.$a.q.getWrappedDataSource.call(this).getCapability(f)?"column":"none"};b.b.g("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:b.$a.prototype.getCapability});b.$a.prototype.By=function(f,a){b.$a.q.By.call(this,f,a)};b.$a.prototype.EJ=function(f,a,d,c){var e,g,h,k,l,m;for(e=0;e<a.length;e++)g=a[e],"row"==g.axis?(h=g.start,k=g.count):"column"==g.axis&&(l=g.start,m=g.count,l+m>this.R("column")&&(m=this.R("column")-l));this.Vk&&(e=this.Vk.range,e.start==
h&&e.count==k&&this.KJ(f,e,this.Vk.callbacks,this.Vk.callbackObjects),this.Vk=null);f=new b.Uh(h,h+k,l,l+m,f,this.Pd);d.success&&(null==c&&(c={}),d.success.call(c.success,f,a))};b.$a.prototype.Qea=function(b,a,d,c){var e;this.Vk&&(e=this.Vk.range,e.start==a.start&&e.count==a.count&&(a=this.Vk.callbacks,e=this.Vk.callbackObjects,a.error&&(null==e&&(e={}),a.error.call(e.error,b))),this.Vk=null);d.error&&(null==c&&(c={}),d.success.call(c.error,b))};b.$a.prototype.KJ=function(f,a,d,c){f=new b.af(a.start,
a.start+a.count,this.Pd,f,this.wg);d.success&&(null==c&&(c={}),d.success.call(c.success,f,a))};b.$a.prototype.gE=function(f,a,d){var c,e,g,h;c=null;this.wg&&(c=new b.af(f,f+d.R(),this.Pd,d,this.wg));a=new b.Uh(f,f+d.R(),0,this.Pd.length,d,this.Pd);g=[];h=[];for(e=0;e<d.R();e++)g.push({row:this.Tg(f+e).key}),h.push({row:f+e,column:-1});f={source:this,operation:"insert"};f.result=a;c&&(f.header=c);f.keys=g;f.indexes=h;b.$a.q.handleEvent.call(this,"change",f)};b.$a.prototype.CE=function(f){var a,d,c;
a=[];c=[];for(d=0;d<f.length;d++)a.push({row:f[d].key}),c.push({row:f[d].index,column:-1});f={source:this,operation:"delete"};f.keys=a;f.indexes=c;b.$a.q.handleEvent.call(this,"change",f)};b.$a.prototype.DN=function(f,a){a.success.call(null,new b.Me(null,f.start))}});