/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b){b.lb=function(f,a){a=a||{};if(!(f instanceof b.ca))throw Error(b.T.dc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.dc._ERR_DATA_INVALID_TYPE_DETAIL);this.i=f;this.cd=[];this.$=0;this.Xn=[];null==this.i.ty("fetchSize")&&(this.i.qN=function(){return-1});var d=this;this.i.gE=function(a,e,f){var h,k,l,m=[],n=[],p=[];for(e=0;e<f.R();e++)h=f.getData(e),l=f.getMetadata(e).key,k=a+e,d.Xn[k]={},d.Xn[k].nodeSet=f,d.Xn[k].startIndex=a,m.push(h),
n.push(l),p.push(k),d.qa.data.splice(k,0,h),d.qa.keys.splice(k,0,l),d.qa.indexes.splice(k,0,k);d.La||b.T.q.handleEvent.call(d,b.T.D.ADD,{data:m,keys:n,indexes:p});d.wx();d.La&&setTimeout(function(){d.fetch()},0)};this.i.CE=function(a){var e,f,h=[],k=[],l=[];for(e=0;e<a.length;e++)f=a[e].index-e,h.push(""),k.push(""),l.push(f),d.qa.data.splice(f,1),d.qa.keys.splice(f,1),d.qa.indexes.splice(f,1);d.La||b.T.q.handleEvent.call(d,b.T.D.REMOVE,{data:h,keys:k,indexes:l});d.wx();d.La&&setTimeout(function(){d.fetch()},
0)};this.Init();if(null!=a&&("enabled"==a.startFetch||null==a.startFetch)||null==a)this.Mx=!0};o_("FlattenedTreeTableDataSource",b.lb,b);b.b.ga(b.lb,b.T,"oj.FlattenedTreeTableDataSource");b.lb.prototype.Init=function(){b.lb.q.Init.call(this)};b.b.g("FlattenedTreeTableDataSource.prototype.Init",{Init:b.lb.prototype.Init});b.lb.prototype.getCapability=function(){return"full"};b.b.g("FlattenedTreeTableDataSource.prototype.getCapability",{getCapability:b.lb.prototype.getCapability});b.lb.prototype.getWrappedDataSource=
function(){return this.i};b.b.g("FlattenedTreeTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:b.lb.prototype.getWrappedDataSource});b.lb.prototype.fetch=function(b){b=b||{};return"init"!=b.fetchType||this.Mx?this.Ae(b):Promise.resolve()};b.b.g("FlattenedTreeTableDataSource.prototype.fetch",{fetch:b.lb.prototype.fetch});b.lb.prototype.at=function(b){var a;a=0>b||b>=this.qa.length?null:{data:this.qa.data[b],index:b,key:this.qa.keys[b]};return new Promise(function(b){b(a)})};b.b.g("FlattenedTreeTableDataSource.prototype.at",
{at:b.lb.prototype.at});b.lb.prototype.collapse=function(b){this.i.collapse(b)};b.b.g("FlattenedTreeTableDataSource.prototype.collapse",{collapse:b.lb.prototype.collapse});b.lb.prototype.expand=function(b){this.i.expand(b)};b.b.g("FlattenedTreeTableDataSource.prototype.expand",{expand:b.lb.prototype.expand});b.lb.prototype.get=function(){b.l.Wb();return null};b.b.g("FlattenedTreeTableDataSource.prototype.get",{get:b.lb.prototype.get});b.lb.prototype.on=function(f,a){if("expand"==f||"collapse"==f)this.i.on(f,
a);else b.lb.q.on.call(this,f,a)};b.b.g("FlattenedTreeTableDataSource.prototype.on",{on:b.lb.prototype.on});b.lb.prototype.off=function(f,a){"expand"==f||"collapse"==f?this.i.off(f,a):b.lb.q.off.call(this,f,a)};b.b.g("FlattenedTreeTableDataSource.prototype.off",{off:b.lb.prototype.off});b.lb.prototype.sort=function(f){if(null==f)return Promise.resolve();var a=this;f.axis="column";return new Promise(function(d,c){a.i.getWrappedDataSource().sort(f,{success:function(){setTimeout(function(){a.i.refresh();
a.qa=null;var c={header:f.key,direction:f.direction};b.T.q.handleEvent.call(a,b.T.D.SORT,c);d(c)},0)}.bind(this),error:function(a){c(a)}.bind(this)})})};b.b.g("FlattenedTreeTableDataSource.prototype.sort",{sort:b.lb.prototype.sort});b.lb.prototype.totalSize=function(){return-1};b.b.g("FlattenedTreeTableDataSource.prototype.totalSize",{totalSize:b.lb.prototype.totalSize});b.lb.prototype.YI=function(b){return this.Xn[b].nodeSet.getMetadata(b-this.Xn[b].startIndex)};b.lb.prototype.Ae=function(f){f=f||
{};this.Lx(f);this.$=null==f.startIndex?this.$:f.startIndex;var a=Number.MAX_VALUE;this.La=null==f.pageSize?this.La:f.pageSize;null!=this.La&&(a=this.La);var d=this.$;if(null!=this.qa)if(null!=this.La){var c=this.qa.data.length-1;if(this.$+this.La-1<=c){var c=b.lb.xB(this.qa,this.$,this.La),a=[],d=[],e;for(e=this.$;e<=c;e++)a[e-this.$]=this.qa.data[e],d[e-this.$]="";c={data:a,keys:d,startIndex:this.$};this.Rg(f,c,null);return Promise.resolve(c)}this.$<=c&&(d=c+1)}else this.i.refresh(),this.qa=null;
var g={start:d,count:a},h=this;return new Promise(function(a,c){h.i.Bo(g,{success:function(c){h.EJ(c);f.refresh=!0;var d=b.lb.xB(h.qa,h.$,h.La),e=[],g=[],l;for(l=h.$;l<=d;l++)e[l-h.$]=h.qa.data[l],g[l-h.$]=c.getMetadata(l).key;c={data:e,keys:g,startIndex:h.$};h.Rg(f,c,null);a(c)}.bind(this),error:function(a){h.Rg(f,null,a);c(a)}.bind(this)})})};b.lb.prototype.EJ=function(f){var a,d;for(a=0;a<f.R();a++)d=this.$+a,this.Xn[d]={},this.Xn[d].nodeSet=f,this.Xn[d].startIndex=this.$;this.qa||(this.qa={},
this.qa.data=[],this.qa.keys=[],this.qa.indexes=[]);b.lb.iq(f,this,this.qa)};b.lb.prototype.Lx=function(f){f.silent||b.T.q.handleEvent.call(this,b.T.D.REQUEST,{startIndex:f.startIndex})};b.lb.prototype.Rg=function(f,a,d){null!=d?b.T.q.handleEvent.call(this,b.T.D.ERROR,d):f.silent||b.T.q.handleEvent.call(this,b.T.D.SYNC,a)};b.lb.xB=function(b,a,d){var c=b.data.length-1;0<d&&(c=a+d-1,c=c>b.data.length-1?b.data.length-1:c);return c};b.lb.iq=function(b,a,d){a=b.R()-1;var c;for(c=b.ta();c<=a;c++){var e=
b.getData(c);d.data[c]=e;d.keys[c]="";d.indexes[c]=c}};b.lb.prototype.wx=function(){for(var b=0;b<this.qa.data.length;b++)this.qa.indexes[b]=b}});