/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojbutton"],function(b,f){b.ya("oj.ojInputNumber",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:b.pa.bm(b.Pj.CONVERTER_TYPE_NUMBER).createConverter(),max:null,min:null,placeholder:void 0,rawValue:void 0,readOnly:!1,step:1,value:null},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputnumber-up"===c&&(b=this.widget().find(".oj-inputnumber-up")[0]),
"oj-inputnumber-down"===c&&(b=this.widget().find(".oj-inputnumber-down")[0]),"oj-inputnumber-input"===c&&(b=this.widget().find(".oj-inputnumber-input")[0]));return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-inputnumber-up")[0]?b={subId:"oj-inputnumber-up"}:a===this.widget().find(".oj-inputnumber-down")[0]?b={subId:"oj-inputnumber-down"}:a===this.widget().find(".oj-inputnumber-input")[0]&&(b={subId:"oj-inputnumber-input"}));return b||this._superApply(arguments)},
refresh:function(){this._super();this.Aa()},stepDown:function(a){this.k0(a,!1)},stepUp:function(a){this.k0(a,!0)},widget:function(){return this.Dr},Ud:function(a,d){var c=this.options,e=this;this._superApply(arguments);b.re.Rk([{V:"disabled",vc:!0},{V:"placeholder"},{V:"value"},{V:"readonly",option:"readOnly",vc:!0},{V:"required",We:!0,vc:!0},{V:"title"},{V:"min"},{V:"max"},{V:"step"}],d,this,function(a){for(var b=["value","step","min","max"],d=0;d<b.length;d++){var f=b[d],m=f in a?a[f]:c[f];null!=
m&&(a[f]="step"===f?e.lx(m):e.xk(f,m))}});if(void 0===c.value)throw Error("ojInputNumber has no value");if(null!=c.min&&null!=c.max&&c.max<c.min)throw Error("ojInputNumber's max must not be less than min");},_ComponentCreate:function(){var a=this.element;this._super();this.kw();a.removeAttr("pattern");this.FX={};this.Aa();this._on(this.Cl);this._focusable(this.Dr);this.Jp(this.Dr)},qQ:function(a,b,c){this._superApply(arguments);switch(a){case "min":case "max":this.Og(a,this.options[a])}},_setOption:function(a,
b,c){var e;e="value"===a||"max"===a||"min"===a?this.xk(a,b):"step"===a?this.lx(b):b;this._super(a,e,c);if("max"===a||"min"===a)this.cU(),this.Wr();"disabled"===a&&this.element.prop("disabled",!!b);"readOnly"===a&&(this.element.prop("readonly",!!b),this.GC("readOnly",this.options.readOnly),this.vZ("readOnly",this.options.readOnly))},_destroy:function(){var a=this._super();this.ez.ojButton("destroy");this.jy.ojButton("destroy");this.ez.remove();this.jy.remove();this.jy=this.ez=null;b.v.unwrap(this.element,
this.Dr);clearTimeout(this.Xc);return a},Og:function(a,b,c){this._superApply(arguments);var e="value"===a||"max"===a||"min"===a,f=e||"disabled"===a,h;f&&(h=this.tB());e&&this.WK(h);"converter"===a&&this.pZ(h);f&&this.qM(h)},Qc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputNumber.prototype.options.converter},vv:function(){var a=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.cU();return f.extend(this.FX,a)},_GetDefaultStyleClass:function(){return"oj-inputnumber"},
Cl:{input:function(a){this.ws(this.element.val(),a)},keydown:function(a){a.keyCode===f.ui.keyCode.ENTER?(this.$S(a),a.preventDefault()):this.Ih()&&this.wq(a)&&a.preventDefault()},keyup:function(a){this.Nx(a)},focus:function(){this.Am=this.element.val()},blur:function(a){this.IM?delete this.IM:this.$S(a)},"mousedown .oj-inputnumber-button":function(a){function b(){this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.Am=c,this._delay(function(){this.Am=c}))}var c;c=this.element[0]===
this.document[0].activeElement?this.Am:this.element.val();a.preventDefault();b.call(this);this.IM=!0;this._delay(function(){delete this.IM;b.call(this)});this.Ih();this.Dx(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a)},"mouseup .oj-inputnumber-button":function(a){this.Nx(a)},"mouseenter .oj-inputnumber-button":function(a){f(a.currentTarget).hasClass("oj-active")&&(this.Ih(),this.Dx(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.Nx(a)}},
xa:{j9:"tooltipDecrement",k9:"tooltipIncrement"},mn:{readOnly:"oj-read-only"},Aa:function(){var a=this.A(this.xa.k9),b=this.A(this.xa.j9),c=this.tB();this.ez.ojButton({label:a});this.jy.ojButton({label:b});this.WK(c);this.qM(c);"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",this.options.readOnly);this.GC("readOnly",this.options.readOnly);this.vZ("readOnly",this.options.readOnly)},Kaa:function(){this.ez=this.Dr.find(".oj-inputnumber-up").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"}});
this.jy=this.Dr.find(".oj-inputnumber-down").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-down-icon"}})},kw:function(){var a=this.element,b=this.Dr=a.addClass("oj-inputnumber-input").wrap("\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e").parent().append("\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e").wrap("\x3cdiv class\x3d'oj-inputnumber oj-component'\x3e\x3c/div\x3e").parent();
this.saveType=a.prop("type");a.attr("type","text");b.find(".oj-inputnumber-button").attr("tabIndex","-1").attr("aria-hidden",!0);this.Kaa()},wq:function(a){var b=f.ui.keyCode;switch(a.keyCode){case b.UP:return this.Dx(null,1,a),!0;case b.DOWN:return this.Dx(null,-1,a),!0}return!1},jra:function(){return"\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e"},Gqa:function(){return"\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e"},
Ih:function(){return this.T4=!0},Dx:function(a,b,c){a=a||500;clearTimeout(this.Xc);this.Xc=this._delay(function(){this.Dx(40,b,c)},a);this.JL(b*this.options.step,c)},JL:function(a,b){var c=this.tB(),c=this.N9(c,a);this.ec(c,b,this.Hv.B6)},kia:function(){var a=this.options,b=a.min,a=this.ZY(a.step);null!=b&&(a=Math.max(a,this.ZY(b)));return a},ZY:function(a){a=a.toString();var b=a.indexOf(".");return-1===b?0:a.length-b-1},N9:function(a,b){var c,e,f=this.options,h=f.min,k=f.step,l=f.max,f=this.kia();
e=null!=h?h:0;c=a-e;var m=Math.round(c/k)*k,m=parseFloat(m.toFixed(f));m!==c?(c=0>b?Math.ceil(c/k)*k:Math.floor(c/k)*k,c=e+c+b):c=a+b;c=parseFloat(c.toFixed(f));return null!=h&&c<h?h:null!=l&&c>l?(h=Math.floor((l-e)/k)*k+e,h=parseFloat(h.toFixed(f))):c},Nx:function(){this.T4&&(clearTimeout(this.Xc),this.T4=!1)},qM:function(a){var b=this.options,c=b.min,e=b.max;if(this.Dr){var f=this.jy,h=this.ez;b.disabled||void 0===a?(f.ojButton("disable"),h.ojButton("disable")):null!=e&&a>=e?(f.ojButton("enable"),
h.ojButton("disable")):(null!=c&&a<=c?f.ojButton("disable"):f.ojButton("enable"),h.ojButton("enable"))}},tB:function(){var a,b;try{b=this.ag()||0,a=this.BC(b)}catch(c){a=void 0}return a},$S:function(a){var b=this.element.val();this.Nx();var c=this.tB();this.WK(c);this.qM(c);this.ec(b,a)},cU:function(){var a=this.options,d=a.min,c=a.max,e=(a=a.translations)?a.numberRange||{}:{},f,h,k,l,m,n,p,a=e.hint||{},r=e.messageDetail||{},e=e.messageSummary||{};null!==a&&(f=a.min||null,h=a.max||null,k=a.inRange||
null);null!==r&&(l=r.rangeOverflow||null,m=r.rangeUnderflow||null);null!==e&&(n=e.rangeOverflow||null,p=e.rangeUnderflow||null);d={min:null!=d?d:void 0,max:null!=c?c:void 0,hint:{min:f||null,max:h||null,inRange:k||null},messageDetail:{rangeOverflow:l||null,rangeUnderflow:m||null},messageSummary:{rangeOverflow:n||null,rangeUnderflow:p||null},converter:this.Qc()};this.FX[b.Zc.VALIDATOR_TYPE_NUMBERRANGE]=b.pa.Fr(b.Zc.VALIDATOR_TYPE_NUMBERRANGE).createValidator(d)},xk:function(a,b){var c;c=null!==b?+b:
b;if(isNaN(c))throw Error("ojInputNumber's "+a+" option is not a number");return c},lx:function(a){if(null===a)return 1;a=this.xk("step",a);if(0>=a)throw Error("Invalid step for ojInputNumber; step must be \x3e 0");if(null===a||0>=a)a=1;return a},GC:function(a,b){-1!=Object.keys(this.mn).indexOf(a)&&this.widget().toggleClass(this.mn[a],!!b)},vZ:function(a,b){b?this.element.removeAttr("role"):this.element.attr("role","spinbutton")},WK:function(a){this.element.attr({"aria-valuemin":this.options.min,
"aria-valuemax":this.options.max,"aria-valuenow":a});this.pZ(a)},pZ:function(a){var b=this.element,c=b.val();this.rv("value",""+a,c)||b.attr({"aria-valuetext":c})},k0:function(a,b){this.Ih();b?this.JL((a||1)*this.options.step):this.JL((a||1)*-this.options.step);this.Nx()}})});