/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b,f){b.ya("oj.inputBase",f.oj.editableValue,{version:"1.0.0",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"",_WIDGET_CLASS_NAMES:"",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_GET_INIT_OPTIONS_PROPS:[{V:"disabled",vc:!0},{V:"pattern"},{V:"placeholder"},{V:"value"},{V:"readonly",option:"readOnly",vc:!0},{V:"required",We:!0,vc:!0},{V:"title"}],_INPUT_HELPER_KEY:"",sQ:"blur",lR:"keydown",dR:"input",OQ:"drop",options:{converter:void 0,placeholder:void 0,
rawValue:void 0,readOnly:!1},Dv:function(a){var b=this._superApply(arguments);this.tia();return b},Ud:function(a,d){this._super(a,d);b.re.Rk(this._GET_INIT_OPTIONS_PROPS,d,this)},_ComponentCreate:function(){var a=this.element,b=this._superApply(arguments),c=this.YQ(a),e=this.options.readOnly;this.uj="rtl"===this.ac();"boolean"===typeof e&&this.element.prop("readonly",e);this.tv()&&(this.dma(),this.PQ()&&this.cma());"pattern"in c&&a.removeAttr("pattern");this.TH={};this.cd=null;return b},hf:function(){var a=
this._superApply(arguments),b=this;this._CLASS_NAMES&&this.element.addClass(this._CLASS_NAMES);this.TS();this.GF();f.each(["disabled","readOnly"],function(a,e){b.options[e]&&b.bZ(e,b.options[e])});return a},bZ:function(a,b){"disabled"===a&&this.element.prop("disabled",b);"readOnly"===a&&(this.element.prop("readonly",b),this.GC("readOnly",b));"disabled"!==a&&"readOnly"!==a||this.TS()},_setOption:function(a,d){var c=this._superApply(arguments);"disabled"!==a&&"readOnly"!==a||this.bZ(a,d);"pattern"===
a&&(this.TH[b.Zc.VALIDATOR_TYPE_REGEXP]=this.PV(),this.Wr());return c},_destroy:function(){var a=this._superApply(arguments);this.element.off("blur drop keydown input");this.cK&&this.cK.remove();this.tv()&&(this.PQ()?b.v.unwrap(this.element,this.cu):b.v.unwrap(this.element));return a},TS:function(){if(!this.options.readOnly&&!this.options.disabled){this.cd={};var a=f.proxy(this.DK,this),b=f.proxy(this.yC,this),c=f.proxy(this.Sha,this),e=function(){this.focus()};this.element.on("blur",a);this.element.on("keydown",
b);this.element.on("input",c);this.element.on("drop",e);this.cd[this.sQ]=a;this.cd[this.lR]=b;this.cd[this.dR]=c;this.cd[this.OQ]=e}else if(this.cd)for(a=[this.sQ,this.lR,this.dR,this.OQ],b=0,c=a.length;b<c;b++)this.cd[a[b]]&&(this.element.off(a[b],this.cd[a[b]]),delete this.cd[a[b]])},mn:{readOnly:"oj-read-only"},tia:function(){for(var a=this._ATTR_CHECK,b=0,c=a.length;b<c;b++){var e=a[b].attr;"setMandatory"in a[b]&&this.element.attr(e,a[b].setMandatory)}},DK:function(a){this.ec(this.ag(),a)},yC:function(a){a.keyCode===
f.ui.keyCode.ENTER&&this.ec(this.ag(),a)},Sha:function(a){this.ws(this.Td().val(),a)},tv:function(){return this._WIDGET_CLASS_NAMES},PQ:function(){return this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES},dma:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._WIDGET_CLASS_NAMES));this.cu=this.element.parent()},cma:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES))},GF:function(){if(this._INPUT_HELPER_KEY&&this.tv()){var a=this.element.attr("aria-describedby")||
"",b=this.bn(this._INPUT_HELPER_KEY);this.element.attr("aria-describedby",a+(" "+b));this.cK=f("\x3cdiv class\x3d'oj-helper-hidden-accessible' id\x3d'"+b+"'\x3e"+this.Wj(this.A(this._INPUT_HELPER_KEY))+"\x3c/div\x3e");this.HF().append(this.cK)}},Wj:function(a){return f("\x3cspan\x3e"+a+"\x3c/span\x3e").text()},HF:function(){return this.widget()},vv:function(){var a=this._superApply(arguments);this.options.pattern&&(this.TH[b.Zc.VALIDATOR_TYPE_REGEXP]=this.PV());return f.extend(this.TH,a)},GC:function(a,
b){-1!=Object.keys(this.mn).indexOf(a)&&this.widget().toggleClass(this.mn[a],!!b)},PV:function(){if(!this.options.pattern)return null;var a={pattern:this.options.pattern,label:this.TI()};f.extend(a,this.options.translations.regexp||{});return b.pa.Fr(b.Zc.VALIDATOR_TYPE_REGEXP).createValidator(a)},bn:function(a){return this.uuid+"_"+a},vqa:function(){return this.uj},refresh:function(){var a=this._superApply(arguments);this.uj="rtl"===this.ac();return a},getNodeBySubId:function(a){return this._super(a)},
widget:function(){return this.tv()?this.cu:this.element}},!0);b.ya("oj.ojInputPassword",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"password"}],_CLASS_NAMES:"oj-inputpassword-input",_WIDGET_CLASS_NAMES:"oj-inputpassword oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputpassword-input"===c&&(b=this.element?this.element[0]:null));return b||
null},_GetDefaultStyleClass:function(){return"oj-inputpassword"}});b.ya("oj.ojTextArea",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3ctextarea\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"oj-textarea-input",_WIDGET_CLASS_NAMES:"oj-textarea oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-textarea-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-textarea"},
Gz:function(){return"oj-inputBase"}});b.ya("oj.ojInputText",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_CLASS_NAMES:"oj-inputtext-input",_WIDGET_CLASS_NAMES:"oj-inputtext oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputtext-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputtext"},
Gz:function(){return"oj-inputBase"}})});