/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b){b.ks=function(){this.id=null;this.depth=0;this.parent=null;this.children=[];this.VN=this.attr=this.title=null};b.ks.prototype.c$=function(b){return function(a,d){return a.attr&&d.attr&&a.attr[b]&&d.attr[b]?a.attr[b]<d.attr[b]?-1:a.attr[b]===d.attr[b]?0:1:a[b]<d[b]?-1:a[b]===d[b]?0:1}};b.ks.prototype.sba=function(b){return function(a,d){return a.attr&&d.attr&&a.attr[b]&&d.attr[b]?a.attr[b]<d.attr[b]?1:a.attr[b]===d.attr[b]?0:-1:a[b]<
d[b]?1:a[b]===d[b]?0:-1}};b.ks.prototype.h0=function(b){var a=b.key;"ascending"===b.direction?this.children.sort(this.c$(a)):"descending"===b.direction&&this.children.sort(this.sba(a));for(var a=0,d=this.children.length;a<d;a++)this.children[a].h0(b)};b.fc=function(f){var a;a=new b.ks;f.id||(a.id="root");this.data=this.fU({count:0},a,f);b.fc.q.constructor.call(this,a)};o_("JsonTreeDataSource",b.fc,b);b.b.ga(b.fc,b.mp,"oj.JsonTreeDataSource");b.fc.prototype.Init=function(){b.fc.q.Init.call(this)};
b.b.g("JsonTreeDataSource.prototype.Init",{Init:b.fc.prototype.Init});b.fc.prototype.fU=function(f,a,d,c){var e,g,h,k,l,m,n;c||(c=0);for(k in d)if("children"==k||0==c&&d instanceof Array)for(e=0==c&&d instanceof Array?d:d[k],c++,n=0;n<e.length;n++){h=e[n];g=new b.ks;h.id||(f.count++,h.attr?h.attr.id||(h.attr.id="rid_"+f.count):g.id="rid_"+f.count);for(l in h)for(m in g)l==m&&"children"!=l&&(g[m]=h[l]),"depth"==m&&(g[m]=c);a.children.push(g);for(m in h)"children"==m&&this.fU(f,a.children[n],h,c)}return a};
b.fc.prototype.Ye=function(b){b||(b=this.data.id);b=this.co(this.data,b);return b.children?b.children.length:0};b.b.g("JsonTreeDataSource.prototype.getChildCount",{Ye:b.fc.prototype.Ye});b.fc.prototype.Ff=function(f,a,d){var c,e,g,h,k;g=[];f||(f=this.data.id);h=this.co(this.data,f);a||(a=[],a.start=0,a.count=h.children.length);a.count||(a.count=h.children.length);a.start||(a.start=0);c=a.start;e=Math.min(h.children.length,c+a.count);for(a=c;a<e;a+=1)k=new b.ks,h.children[a].attr&&(k.attr=h.children[a].attr),
h.children[a].id&&(k.id=h.children[a].id),h.children[a].depth&&(k.depth=h.children[a].depth),h.children[a].title&&(k.title=h.children[a].title),h.children[a].parent&&(k.parent=h.children[a].parent),k.VN=0<h.children[a].children.length?!1:!0,g.push(k);f=new b.Pe(c,e,g,f);null!=d&&null!=d.success&&d.success.call(null,f)};b.b.g("JsonTreeDataSource.prototype.fetchChildren",{Ff:b.fc.prototype.Ff});b.fc.prototype.pu=function(f,a){var d,c,e,g;e=[];f||(f=this.data.id);g=this.co(this.data,f);d=[];d.start=
0;d.count=g.children.length;c=d.start;for(d=Math.min(g.children.length,c+d.count);c<d;c+=1)g.children[c].VN=0<g.children[c].children.length?!1:!0,e.push(g.children[c]);e=new b.Pe(0,e.length,e,f);null!=a&&null!=a.success&&a.success.call(null,e)};b.b.g("JsonTreeDataSource.prototype.fetchDescendants",{pu:b.fc.prototype.pu});b.fc.prototype.md=function(){return"valid"};b.b.g("JsonTreeDataSource.prototype.moveOK",{md:b.fc.prototype.md});b.fc.prototype.move=function(f,a,d,c){var e;e=a;if(!e||e==this.data.id){if("inside"!=
d){b.r.log("Error: root can not be the reference node if position equals to "+d);return}e||(e=this.data.id)}f=this.co(null,f);this.co(f,e)?b.r.log("Error: the node to move contains the reference node as its sub-tree."):(a=this.co(null,e),e=this.gJ(e),this.kja(f),"inside"==d?(this.Yl(f,f.depth-(a.depth+1)),a.children.push(f)):"before"==d?(this.Yl(f,f.depth-a.depth),d=e.children.indexOf(a),-1<d&&(0!=d?e.children.splice(d-1,0,f):e.children.unshift(f))):"after"==d?(this.Yl(f,f.depth-a.depth),d=e.children.indexOf(a),
-1<d&&e.children.splice(d,0,f)):"first"==d?(this.Yl(f,f.depth-a.depth),e.children.unshift(f)):"last"==d&&(this.Yl(f,f.depth-a.depth),e.children.push(f)),null!=c&&null!=c.success&&c.success.call(null,this.data))};b.b.g("JsonTreeDataSource.prototype.move",{move:b.fc.prototype.move});b.fc.prototype.sort=function(b,a){var d;d=this.co(this.data,this.data.id);d.h0(b);null!=a&&null!=a.success&&a.success.call(null,d)};b.b.g("JsonTreeDataSource.prototype.sort",{sort:b.fc.prototype.sort});b.fc.prototype.jm=
function(){return{key:null,direction:"none"}};b.b.g("JsonTreeDataSource.prototype.getSortCriteria",{jm:b.fc.prototype.jm});b.fc.prototype.gJ=function(b,a){var d,c=null;if(b==this.data.id)return null;a||(a=this.data);if(a.children&&0<a.children.length){for(d=0;d<a.children.length;d++)if(a.children[d].id&&a.children[d].id==b||a.children[d].attr&&a.children[d].attr.id==b)return a;for(d=0;d<a.children.length&&!(c=this.gJ(b,a.children[d]));d++);}return c};b.fc.prototype.co=function(b,a){var d,c=null;b||
(b=this.data);if(b.id&&b.id==a||b.attr&&b.attr.id==a)return b;if(null!=b.children)for(d=0;d<b.children.length&&!c;d++)c=b.children[d].id&&b.children[d].id==a||b.children[d].attr&&b.children[d].attr.id==a?b.children[d]:this.co(b.children[d],a);return c};b.fc.prototype.Yl=function(b,a){var d;b.depth-=a;if(b.children&&0!=b.children.length)for(d=0;d<b.children.length;d++)this.Yl(b.children[d],a)};b.fc.prototype.kja=function(b){var a;b.id?a=b.id:b.attr&&(a=b.attr.id);(a=this.gJ(a))||(a=this.data);b=a.children.indexOf(b);
-1<b&&a.children.splice(b,1)};b.fc.prototype.getCapability=function(b){return"fetchDescendants"===b?"enable":"sort"===b?"default":"batchFetch"===b?"disable":"move"===b?"full":null};b.b.g("JsonTreeDataSource.prototype.getCapability",{getCapability:b.fc.prototype.getCapability});b.Pe=function(f,a,d,c){b.l.Zl(f,null);b.l.Zl(a,null);this.Loa=c;this.No=f;this.nE=a;this.Mf=d};o_("JsonNodeSet",b.Pe,b);b.Pe.prototype.getParent=function(){return this.Loa};b.b.g("JsonNodeSet.prototype.getParent",{getParent:b.Pe.prototype.getParent});
b.Pe.prototype.ta=function(){return this.No};b.b.g("JsonNodeSet.prototype.getStart",{ta:b.Pe.prototype.ta});b.Pe.prototype.R=function(){return Math.max(0,this.nE-this.No)};b.b.g("JsonNodeSet.prototype.getCount",{R:b.Pe.prototype.R});b.Pe.prototype.getData=function(f){b.l.assert(f<=this.nE&&f>=this.No);f-=this.No;return this.Mf[f]?this.Mf[f].attr:null};b.b.g("JsonNodeSet.prototype.getData",{getData:b.Pe.prototype.getData});b.Pe.prototype.getMetadata=function(f){var a=[];b.l.assert(f<=this.nE&&f>=this.No);
f-=this.No;a.key=this.Mf[f].id?this.Mf[f].id:this.Mf[f].attr.id;a.leaf=this.Mf[f].VN;a.depth=this.Mf[f].depth;null==a.leaf&&(a.leaf=this.Mf[f].children&&0<this.Mf[f].children.length?!1:!0);return a};b.b.g("JsonNodeSet.prototype.getMetadata",{getMetadata:b.Pe.prototype.getMetadata});b.Pe.prototype.Yl=function(b,a){var d;a++;b.depth=a;if(b.children&&0!=b.children.length)for(d=0;d<b.children.length;d++)this.Yl(b.children[d],a)};b.Pe.prototype.If=function(f){var a,d,c;b.l.assert(f<=this.nE&&f>=this.No);
f-=this.No;d=this.Mf[f].depth;a=this.Mf[f].children;if(0==a.length)return null;f=this.Mf[f].id?this.Mf[f].id:this.Mf[f].attr.id;for(c=0;c<a.length;c++)this.Yl(a[c],d);return new b.Pe(0,a.length,a,f)};b.b.g("JsonNodeSet.prototype.getChildNodeSet",{If:b.Pe.prototype.If})});