/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","knockout","ojs/ojmodel"],function(b,f){b.Ha=function(){};o_("KnockoutUtils",b.Ha,b);b.Ha.IN="oj._internalObj";b.Ha.qh="oj._underUpdate";b.Ha.ku="oj.collectionUpdating";b.Ha.SO="oj.collectionSubscription";b.Ha.$O="oj.collectionUpdatingFunc";b.Ha.map=function(a,d,c){function e(c){return function(d){g[b.Ha.qh]||a.set(c,d)}}var g,h,k,l;if(a instanceof b.j){h=Array(a.Yd());g=c?f.observableArray(h):h;b.Ha.l0(g,a);if(c)for(h=0;h<a.Vb.length;h++)k=a.Vb[h],g()[k]=b.Ha.map(a.ul(k,null,
!0,!1),d);else for(h=0;h<a.Vb.length;h++)k=a.Vb[h],g[k]=b.Ha.map(a.ul(k,null,!0,!1),d);h=function(c){var d;try{if(!g[b.Ha.qh]){g[b.Ha.ku]=!0;for(d=0;d<c.length;d++){var e=c[d].index,f=b.Ha.Mb(c[d].value),h=c[d].status;"added"===h?e>=a.length-1?a.add(f):a.add(f,{at:e}):"deleted"===h&&a.Gq(f,e)}a.comparator&&(g[b.Ha.qh]=!0,g.sort(function(c,d){return b.Ha.lT(c,d,a.comparator,a,this)}),g[b.Ha.qh]=!1)}}catch(k){throw k;}finally{g[b.Ha.ku]=!1}};c&&g.subscribe&&(g[b.Ha.$O]=h,g[b.Ha.SO]=g.subscribe(h,null,
"arrayChange"));c=function(a,c,d){var e;try{!g[b.Ha.ku]&&c instanceof b.j&&(g[b.Ha.qh]=!0,e=d.index,g.splice(e,1))}catch(f){throw f;}finally{g[b.Ha.qh]=!1}};h=function(a,c,e){var f,h;try{if(!g[b.Ha.ku]&&c instanceof b.j&&(g[b.Ha.qh]=!0,f=c.lha(a),void 0!==f&&-1<f))if(h=b.Ha.map(a,d),e.fillIn){for(var k=Array.isArray(g)?g.length:g().length;k<f;k++)g.splice(k,0,b.Ha.map(c.ul(k,null,!0,!1),d));g.splice(f,1,h)}else g.splice(f,0,h)}catch(l){throw l;}finally{g[b.Ha.qh]=!1}};k=function(a){try{!g[b.Ha.ku]&&
a instanceof b.j&&(g[b.Ha.qh]=!0,f.isObservable(g)?(g[b.Ha.SO]&&g[b.Ha.SO].dispose(),g.removeAll(),g[b.Ha.$O]&&g.subscribe(g[b.Ha.$O],null,"arrayChange")):g=[])}catch(c){throw c;}finally{g[b.Ha.qh]=!1}};l=function(c){try{!g[b.Ha.ku]&&c instanceof b.j&&(g[b.Ha.qh]=!0,g.sort(function(d,e){return b.Ha.lT(d,e,a.comparator,c,this)}))}catch(d){throw d;}finally{g[b.Ha.qh]=!1}};a.jl(b.Y.D.ADD,h,void 0,void 0,!0);a.jl(b.Y.D.REMOVE,c,void 0,void 0,!0);a.jl(b.Y.D.RESET,k,void 0,void 0,!0);a.jl(b.Y.D.SORT,l,
void 0,void 0,!0)}else{if(void 0===a)return;g={};c=a.attributes;h=null;for(h in c)c.hasOwnProperty(h)&&(k=f.observable(a.get(h)),g[h]=k,l=e(h),l.hra=h,k.subscribe&&k.subscribe(l));c=function(a){var c,d;try{for(d in g[b.Ha.qh]=!0,c=a.JM(),c)if(c.hasOwnProperty(d))g[d](a.get(d))}catch(e){throw e;}finally{g[b.Ha.qh]=!1}};a.jl(b.Y.D.CHANGE,c,void 0,void 0,!0);b.Ha.l0(g,a);d&&d(g)}return g};o_("KnockoutUtils.map",b.Ha.map,b);b.Ha.Mb=function(a){return a instanceof b.t?a:a.hasOwnProperty(b.Ha.IN)?a[b.Ha.IN]:
a};b.Ha.lT=function(a,d,c,e,f){return b.j.hQ(b.Ha.Mb(a),b.Ha.Mb(d),c,e,f)};b.Ha.l0=function(a,d){Object.defineProperty(a,b.Ha.IN,{value:d,enumerable:!1})}});