/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojdnd"],function(b,f){function a(b,c,e,f,h,k){null==a.KG&&(a.KG=a.yca());this.pc=b;this.uj=c;this.h$=e;f&&f.d5&&(this.tla=f.d5);h&&(h.g5&&(this.aM=h.g5),h.f5&&(this.$L=h.f5),h.k5&&(this.fM=h.k5),h.j5&&(this.eM=h.j5),h.h5&&(this.cM=h.h5),h.i5&&(this.nD=h.i5),h.m5&&(this.hM=h.m5),h.n5&&(this.iM=h.n5),h.l5&&(this.gM=h.l5));k&&(k.a1&&(this.qn=k.a1),k.t4&&(this.bh=k.t4),k.N2&&(this.wW=k.N2),k.W2&&(this.rJ=k.W2),k.P4&&(this.fo=k.P4),k.i3&&(this.mt=k.i3),
k.F3&&(this.At=k.F3),k.E3&&(this.vk=k.E3),k.D3&&(this.Vn=k.D3),k.R4&&(this.Kx=k.R4),k.Nf&&(this.n0=k.Nf),k.Bg&&(this.o0=k.Bg));c=document.createElement("div");e=c.style;e.display="inline-block";e.overflow="hidden";e.visibility="hidden";f=document.createElement("div");e=f.style;e.display="inline-block";c.appendChild(f);b.insertBefore(c,b.firstChild);this.c0=c;this.Jq=f;var l=this;this.qk=function(a){l.pq(a)};this.nX=function(){l.Kfa()};this.mq=function(a){l.GJ(a)};this.oq=function(a){l.MJ(a)}}(function(){function d(a){for(;a;){a=
a.nextSibling;var b=!0;if(a){var c=a.style;!c||c.visibility!==p&&c.display!==r||(b=!1)}if(a&&1===a.nodeType&&b)return a}return null}function c(a,b){for(var c=a;c;){var d=c.style;if(d&&(d.visibility===p||d.display===r))break;d=c.parentNode;if(d===b)return c;c=d}return null}function e(a,b){return b.qc<a.qc?1:a.qc<b.qc?-1:0}function g(a){a&&a.sort(e);return a}function h(a){var b=null;a=f(a);a.hasClass("oj-masonrylayout-tile-1x1")?b={colSpan:1,rowSpan:1}:a.hasClass("oj-masonrylayout-tile-2x1")?b={colSpan:2,
rowSpan:1}:a.hasClass("oj-masonrylayout-tile-3x1")?b={colSpan:3,rowSpan:1}:a.hasClass("oj-masonrylayout-tile-1x2")?b={colSpan:1,rowSpan:2}:a.hasClass("oj-masonrylayout-tile-1x3")?b={colSpan:1,rowSpan:3}:a.hasClass("oj-masonrylayout-tile-2x2")?b={colSpan:2,rowSpan:2}:a.hasClass("oj-masonrylayout-tile-2x3")?b={colSpan:2,rowSpan:3}:a.hasClass("oj-masonrylayout-tile-3x2")&&(b={colSpan:3,rowSpan:2});return b}function k(a){var b=null;a=f(a);a.hasClass("oj-masonrylayout-tile-1x1")?b="oj-masonrylayout-tile-1x1":
a.hasClass("oj-masonrylayout-tile-2x1")?b="oj-masonrylayout-tile-2x1":a.hasClass("oj-masonrylayout-tile-3x1")?b="oj-masonrylayout-tile-3x1":a.hasClass("oj-masonrylayout-tile-1x2")?b="oj-masonrylayout-tile-1x2":a.hasClass("oj-masonrylayout-tile-1x3")?b="oj-masonrylayout-tile-1x3":a.hasClass("oj-masonrylayout-tile-2x2")?b="oj-masonrylayout-tile-2x2":a.hasClass("oj-masonrylayout-tile-2x3")?b="oj-masonrylayout-tile-2x3":a.hasClass("oj-masonrylayout-tile-3x2")&&(b="oj-masonrylayout-tile-3x2");return b}
function l(a,b){f(a).removeClass(b)}function m(a,b){f(a).addClass(b)}b.ya("oj.ojMasonryLayout",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{reorderHandle:null,beforeInsert:null,insert:null,beforeRemove:null,remove:null,beforeResize:null,resize:null,beforeReorder:null,reorder:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-masonrylayout oj-component");this.options.disabled&&b.r.warn(u);this.wr=this.eventNamespace+"ReorderHandle";this.oa=
{};this.oa.rh=!1;this.oa.Ge=!1;this.oa.eP=!1;this.oa.Mm=!1;this.oa.ap=!1;this.On();this.Ov();this.Aa(!0)},refresh:function(){this._super();var a="rtl"===this.ac()!==this.tf;a&&this.yU();this.Aa(a)},ml:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},gn:function(){this._super();this.Uc&&this.Aa(this.Uc[0])},lf:function(a,b,c){this.lia(b);this.nf(b,c,{launcher:f(b.target).closest(":tabbable")})},Aa:function(c){if(this.Vv()){this.Uc=null;this.tf="rtl"===this.ac();this.tn=b.v.Od();var d=this.element,
e=this.options;if(c){var f=this;this.fo=function(a){f.$ka(a)};this.mt=function(a){f.Jfa(a)};this.At=function(){f.bha()};this.vk=function(){f.aha()};this.Vn=function(){f.$ga()};if(!this.yf){var n={};n.d5=w;var p={g5:"oj-masonrylayout-transition-resize-to",f5:"oj-masonrylayout-transition-resize-to-fast",k5:"oj-masonrylayout-tile-transition-move-to",j5:"oj-masonrylayout-tile-transition-move-to-fast",h5:"oj-masonrylayout-tile-transition-hide-from",i5:"oj-masonrylayout-tile-transition-hide-to"};p.m5=x;
p.n5="oj-masonrylayout-tile-transition-show-to";p.l5="oj-masonrylayout-tile-transition-resize-to";var q={};q.a1=m;q.t4=l;q.N2=k;q.W2=h;q.P4=this.fo;q.i3=this.mt;q.F3=this.At;q.E3=this.vk;q.D3=this.Vn;q.R4=g;q.Nf=b.Components.Nf;q.Bg=b.Components.Bg;this.Uja();this.yf=new a(d[0],this.tf,"enabled"===b.ba.kN(),n,p,q)}this.SW=function(a){f.Kea(a)};this.PW=function(a){f.Gea(a)};this.RW=function(a){f.Jea(a)};this.QW=function(a){f.Hea(a)};this.NW=function(a){f.Fea(a)};this.TW=function(a){f.Lea(a)};e.reorderHandle&&
this.S_()}else e=d.children(),this.QL(e),this.EL(e),this.S$();this.yf.Fm(c);c&&(this.Wg=function(){f.Se()},b.v.eh(d[0],this.Wg))}else d=!1,this.Uc&&(d=this.Uc[0]),this.Uc=[c||d]},_destroy:function(){this.Op();var a=this.element;b.v.Qh(a[0],this.Wg);this.Wg=null;this.Rja();for(var c=this.ok(),d=c.length,e=0;e<d;e++)delete c[e].qc;this.yU();a.removeClass("oj-masonrylayout oj-component");this.options.reorderHandle&&this.A0();this.Es=this.Vn=this.vk=this.At=this.mt=this.fo=this.TW=this.NW=this.QW=this.RW=
this.PW=this.SW=null;this._super()},_setOption:function(a,c,d){var e=!1;switch(a){case "reorderHandle":this.A0();e=!0;break;case "disabled":b.r.warn(u);break;case "contextMenu":b.v.Od()||(this.Op(),c&&this.On(c))}this._super(a,c,d);e&&c&&this.S_()},resizeTile:function(a,b){var c=this.yf;c.hE()&&c.WD();var d=f(a),e=d[0],g=k(e);if(b==g)throw Error("JET MasonryLayout: Unable to resize child "+a+" to style class "+b+" because "+b+" is already applied.");!1!==this._trigger("beforeResize",null,{tile:d,
previousSizeStyleClass:g,sizeStyleClass:b})&&(this.Qv||(this.Qv=[]),this.Qv.push(e,g,b),c.resizeTile(a,b))},insertTile:function(a,c){var d=this.yf;d.hE()&&d.WD();isNaN(c)&&(c=-1);var e=f(a),g=e[0];!1!==this._trigger("beforeInsert",null,{tile:e,index:c})&&(g.jY=c,d.ug()&&e.addClass(x),e=g.style,e.top="-1px",this.tf?e.right="-1px":e.left="-1px",this.Pn(g,c),d.woa(g,c),b.Components.Nf(g),this.Es||(this.Es=[]),this.Es.push(a))},removeTile:function(a){var c=this.yf;c.hE()&&c.WD();var d=f(a),e=d[0];if(b.pd.JD(e)){var g=
this.ok(!0),e=g.indexOf(e);0<e&&(this.WH=g[e-1])}!1!==this._trigger("beforeRemove",null,{tile:d})&&c.poa(a)},Se:function(){this.Uv||this.rX||this.yf.opa()},$ka:function(a){var b=f(a),c=a.jY;delete a.jY;this.options.reorderHandle&&this.EL(b);this._trigger("insert",null,{tile:b,index:c})},Jfa:function(a){var c=f(a);this.options.reorderHandle&&this.QL(c);b.Components.Bg(a);a.parentNode.removeChild(a);this.LC(a);this._trigger("remove",null,{tile:c})},bha:function(){if(this.Es){for(var a=this.yf,b=this.Es,
c=0;c<b.length;c++)a.Epa(b[c]);this.Es=null}if(this.Qv){a=this.Qv;for(c=0;c<a.length;c+=3){var b=a[c+1],d=a[c+2],b={tile:f(a[c]),previousSizeStyleClass:b,sizeStyleClass:d};this._trigger("resize",null,b)}this.Qv=null}this.Uv&&(this.uA?this.Iea():this.SG&&this.OW())},aha:function(){this.rX=!0;this.pC=null;var a=document.activeElement;a&&b.v.Sk(this.element[0],a)&&(this.pC=a)},$ga:function(){this.rX=!1;var a=this.element[0];if(this.pC){var c=this.pC;this.pC=null;if(this.WH){if(c=this.WH,this.WH=null,
c&&b.v.Sk(a,c)){var a=this.ok(a,!0),d=a.indexOf(c);0<=d&&d<a.length-1?b.pd.hN(a[d+1]):b.pd.hN(c)}}else b.v.Sk(a,c)?b.pd.ny(c):b.pd.hN(a)}},yU:function(){var a=this.yf;a&&a.destroy();this.yf=null},Vv:function(){var a=document.createElement("div"),b=a.style;b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},ok:function(a){for(var b=this.element.children(w),c=b.length,d=[],e=0;e<c;e++){var f=b[e];if(!a||
a&&f!==this.wd){var g=f.style;g.visibility!==p&&g.display!==r&&d.push(f)}}return d},Uja:function(){var a=this.ok();if(a)for(var b=0;b<a.length;b++){var c=a[b];c.qc||(c.qc=b+1)}},S$:function(){var a=this.ok();if(a)for(var b=0;b<a.length;b++){var c=a[b];c.qc||this.Pn(c,b)}},Rja:function(){var a=this.ok(),c=this.ok();g(c);for(var d=0;d<a.length;d++){var e=a[d],f=c[d];e!=f&&(b.Components.Bg(f),e.parentNode.insertBefore(f,e),b.Components.Nf(f),e=a.indexOf(f),e>d&&(a.splice(e,1),a.splice(d,0,f)))}},Pn:function(a,
b){var c=this.ok();0>b&&(b=c.length);if(c)for(var d=0;d<c.length;d++){var e=c[d];e.qc&&e.qc>=b+1&&e.qc++}a.qc=b+1},LC:function(a){if(a.qc){var b=this.ok();if(b)for(var c=0;c<b.length;c++){var d=b[c];d.qc&&d.qc>a.qc&&d.qc--}delete a.qc}},On:function(a){var b=null,c=null;a||this.options.contextMenu||(b=this.element.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;c=f.type(b);if("function"==c){try{b=b()}catch(d){b=null}c=f.type(b)}if("string"===
c){if(b=f(b)){b.css("display",r);c=this.oa;if(!c)return;c.Ge=b;c.rh=!0}this.oa.rh&&a&&this.Ov()}}},Ov:function(){if(this.oa&&this.oa.rh&&this.options.reorderHandle){var a=this.oa.Ge,b=this;a.on("ojselect",f.proxy(this.lj,this));var c=!1;a.find("[data-oj-command]").each(function(){if(0===f(this).children("a").length){var a=f(this).attr("data-oj-command").slice(17);f(this).replaceWith(b.ni(a));f(this).addClass("oj-menu-item");c=!0}});c&&a.ojMenu("refresh");this.oa.eP=a.find("#"+v);this.oa.Mm=a.find("#"+
y);this.oa.ap=a.find("#"+B)}},Op:function(){var a=this.oa;a&&a.rh&&(a.rh=!1,a.Ge.off("ojselect"),a.Ge=null)},lia:function(a){a=c(a.originalEvent.target,this.element[0]);this.oa.tile=a;if(this.oa.rh){var b=this.oa.ND,e=!1,f=this.oa.eP;if(f){var g=f.hasClass(q),h=!1;b&&a===b&&(h=!0);h&&!g?(f.addClass(q),e=!0):!h&&g&&(f.removeClass(q),e=!0)}if(f=this.oa.Mm)g=f.hasClass(q),h=!1,b&&a!==b&&a!==d(b)||(h=!0),h&&!g?(f.addClass(q),e=!0):!h&&g&&(f.removeClass(q),e=!0);if(f=this.oa.ap)g=f.hasClass(q),h=!1,b&&
b!==a&&b!==d(a)||(h=!0),h&&!g?(f.addClass(q),e=!0):!h&&g&&(f.removeClass(q),e=!0);e&&this.oa.Ge.ojMenu("refresh")}},ni:function(a){var b=M[a];a=I[a];var c=f('\x3ca href\x3d"#"\x3e\x3c/a\x3e');c.text(this.A(a));c.wrap("\x3cli id\x3d"+b+"\x3e\x3c/li\x3e");return c.parent()},qha:function(a){a&&(this.oa.ND=a)},BY:function(a,b){if(a&&this.oa.ND){var c=this.oa.ND;this.oa.ND=!1;this.Fba(c,a,b)}},Fba:function(a,b,c){var e=a.qc-1,g=f(a);if(!1!==this._trigger("beforeReorder",null,{tile:g,fromIndex:e})){this.LC(a);
var h=b.qc-1;c||h++;var k=this.element[0];c||(b=d(b));this.Pn(a,h);k.insertBefore(a,b);this.yf.Fm(!0);this._trigger("reorder",null,{tile:g,fromIndex:e,toIndex:h})}},lj:function(a,b){var c=b?b.item.attr("id"):void 0;c===v?this.qha(this.oa.tile):c===y?this.BY(this.oa.tile,!0):c===B&&this.BY(this.oa.tile,!1)},FW:function(a){var b=this.ok(!0);g(b);for(var c=b.length,d=0;d<c;d++)if(b[d]===a)return d;return-1},S_:function(){var a=this.element,b=a.children();this.EL(b);a.on("dragstart"+this.wr,this.SW).on("dragenter"+
this.wr,this.PW).on("dragover"+this.wr,this.RW).on("dragleave"+this.wr,this.QW).on("dragend"+this.wr,this.NW).on("drop"+this.wr,this.TW)},EL:function(a){var b=this.options;a.filter(b.reorderHandle).attr(s,"true").addClass(t);a.find(b.reorderHandle).attr(s,"true").addClass(t)},A0:function(){var a=this.element,b=a.children();this.QL(b);a.off(this.wr)},QL:function(a){var b=this.options;a.filter(b.reorderHandle).removeAttr(s).removeClass(t);a.find(b.reorderHandle).removeAttr(s).removeClass(t)},Kea:function(a){if(this.options.reorderHandle&&
!this.Uv){var b=c(a.target,this.element[0]);if(b){var d=this.FW(b);b.mK=d;d={tile:f(b),fromIndex:d};!1!==this._trigger("beforeReorder",null,d)&&(a=a.originalEvent,this.gI(b,a.pageX,a.pageY,a.dataTransfer))}}},Gea:function(a){a=a.originalEvent;var c=a.relatedTarget,d=this.element[0],e=!1;c?e=d!=c&&!b.v.Sk(d,c):this.NU&&(e=(c=document.elementFromPoint(a.clientX,a.clientY))&&(c==d||b.v.Sk(d,c)));e&&((this.NU=!1,this.Bn)?this.wd&&(f(this.wd).css("display",""),this.yf.Fm(!1,!0)):a.dataTransfer.dropEffect=
"none")},Jea:function(a){var b=a.originalEvent;b.dataTransfer.dropEffect="move";this.Mba(b.pageX,b.clientX,b.clientY);a.preventDefault();return!1},Hea:function(a){var c=a.originalEvent,d=c.relatedTarget;a=this.element[0];var e=!1;e=d?a!=d&&!b.v.Sk(a,d):(c=document.elementFromPoint(c.clientX,c.clientY))&&c!=a&&!b.v.Sk(a,c);e&&(this.NU=!0,this.wd&&(f(this.wd).css("display",r),this.yf.Fm(!1,!0)))},wT:function(){if(this.YA){clearTimeout(this.YA);this.YA=null;var a=this.Bn;a&&f(a).removeClass("oj-drag")}},
Fea:function(){this.wT();if(!this.UG){var a=this.Bn;if(a&&this.wd){var c=this.wd;b.v.Sk(this.element[0],a)&&(f(c).css("display",""),this.LC(c),c.parentNode.removeChild(c),f(a).css("display",""),this.Pn(a,a.qc-1),this.yf.Fm(!1,!0));delete a.mK}this.wd=this.Bn=null;this.wA=this.uA=!1;this.fI=null;this.Uv=this.SG=!1}},Lea:function(a){var b=this.yf;b.hE()&&b.WD();this.wT();b=a.originalEvent;this.Uba(this.Bn,b.pageX,b.pageY);a.stopPropagation();return!1},gI:function(a,c,d,e){this.Uv=!0;this.TG=this.wA=
this.UG=!1;this.Bn=a;var g=this.element[0],h=k(a),l=this.wd=document.createElement("div");l.qc=a.qc;l.className=h+" oj-drop";var h=l.style,m=a.style;h.top=m.top;this.tf?h.right=m.right:h.left=m.left;h=f(a).offset();g.insertBefore(l,a);this.fI=c={left:c-h.left,top:d-h.top};f(a).addClass("oj-drag");e.effectAllowed="move";e.setData("text/html",a.outerHTML);e.setDragImage(a,c.left,c.top);var n=this;this.YA=setTimeout(function(){n.TG=!0;m.display=r;f(a).removeClass("oj-drag");n.YA=null;b.Components.Xo(a)},
0)},Mba:function(a,b,e){this.wA=!0;if(this.TG&&!this.uA){var g=this.element[0];b=document.elementFromPoint(b,e);if((b=c(b,g))&&b!==this.wd&&b!==this.Bn){var h=f(g).offset();e=d(this.wd);a=a-h.left>=b.offsetLeft+.5*b.offsetWidth;this.LC(this.wd);a&&!this.tf||!a&&this.tf?(a=d(b))?(this.Pn(this.wd,a.qc-1),g.insertBefore(this.wd,a)):(this.Pn(this.wd,b.qc),g.appendChild(this.wd)):(this.Pn(this.wd,b.qc-1),g.insertBefore(this.wd,b));e!==d(this.wd)&&(this.uA=this.yf.Fm(!1,!0))}}},Iea:function(){this.uA=!1},
Uba:function(a,c,d){this.UG=!0;var e=this.element[0],g=this.wd;this.wd=null;b.Components.Bg(a);e.replaceChild(a,g);b.Components.Nf(a);a.qc=g.qc;g=a.style;g.display="";b.Components.Hm(a);var h=f(e).offset(),k=this.fI;g.top=d-k.top-h.top+n;c=c-k.left-h.left;this.tf?(g.right=e.offsetWidth-(c+f(a).outerWidth(!0))+n,g.left=""):g.left=c+n;this.fI=null;this.wA?this.SG=this.yf.Fm(!1,!0):this.OW()},OW:function(){this.TG=this.wA=this.UG=this.Uv=this.SG=!1;var a=this.Bn;this.Bn=null;var b=a.mK;delete a.mK;var c=
this.FW(a),a={tile:f(a),fromIndex:b,toIndex:c};this._trigger("reorder",null,a)},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)}});var n="px",p="hidden",r="none",s="draggable",q="oj-disabled",t="oj-draggable",w=".oj-masonrylayout-tile-1x1, .oj-masonrylayout-tile-1x2, .oj-masonrylayout-tile-1x3, .oj-masonrylayout-tile-2x1, .oj-masonrylayout-tile-2x2, .oj-masonrylayout-tile-2x3, .oj-masonrylayout-tile-3x1, .oj-masonrylayout-tile-3x2",x="oj-masonrylayout-tile-transition-show-from",
u="JET MasonryLayout: 'disabled' option not supported",v="ojmasonrylayoutcut",y="ojmasonrylayoutpastebefore",B="ojmasonrylayoutpasteafter",M={cut:v,"paste-before":y,"paste-after":B},I={cut:"labelCut","paste-before":"labelPasteBefore","paste-after":"labelPasteAfter"}})();a.prototype.Fm=function(a,b){var e=!1;a?(e=this.Zg()?!0:!1,this.VZ()):(this.vk&&this.vk(),this.jM(b),e=this.dM());return e};a.prototype.destroy=function(){for(var a=this.pc,b=this.kq(),e=0;e<b.length;e++){var f=b[e].style;this.uj?
f.right="":f.left="";f.top=""}a.removeChild(this.c0);this.o0=this.n0=this.Kx=this.Vn=this.vk=this.At=this.mt=this.fo=this.rJ=this.wW=this.bh=this.qn=this.pc=this.tl=this.ck=this.mi=this.dk=this.bj=this.oq=this.mq=this.nX=this.qk=this.Jq=this.c0=null};a.prototype.resizeTile=function(a,b){var e=this.pc.querySelector(a);if(e){this.dk||(this.dk=[]);var f=this.dk;f.push(e);f.push(b);this.b_=!0;this.tx()}};a.prototype.woa=function(a,b){var e=this.kq();this.Kx&&this.Kx(e);var f=null;0<=b&&b<e.length&&(f=
e[b]);this.pc.insertBefore(a,f);this.tx()};a.prototype.Epa=function(b){if(b=this.pc.querySelector(b))this.mi||(this.mi=[]),this.mi.push(b),this.HL=!0,this.pj!==a.PR&&this.pj!==a.Vz?this.tx():this.HL=!1};a.prototype.poa=function(a){if(a=this.pc.querySelector(a))this.ck||(this.ck=[]),this.ck.push(a),this.oX=!0,this.tx()};a.prototype.opa=function(){this.b_||this.oX||this.HL||(this.vk&&this.vk(),this.jM(!1),this.dM())};a.prototype.ug=function(){if(this.C0)return!1;this.C$||(this.X9=this.h$?!1:a.Fga(a.KG[0],
a.KG[1]),this.C$=!0);return this.X9};a.prototype.hE=function(){return null!=this.pj||null!=this.bj&&0<this.bj.length};a.prototype.WD=function(){this.C0=!0;this.Ul(this.fM);this.Ul(this.eM);this.Ul(this.cM);this.Ul(this.nD);this.Ul(this.hM);this.Ul(this.iM);this.Ul(this.gM);this.bh(this.Jq,this.aM);this.bh(this.Jq,this.$L);a.ee(this.pc,"transitionend",this.qk);a.ee(this.pc,"webkitTransitionEnd",this.qk);for(var b=this.kq(),c=0;c<b.length;c++){var e=b[c];e.rA&&delete e.rA;a.ee(e,"transitionend",this.mq);
a.ee(e,"webkitTransitionEnd",this.mq);a.ee(e,"transitionend",this.oq);a.ee(e,"webkitTransitionEnd",this.oq)}this.nt?(clearTimeout(this.nt),this.nt=null,this.GJ(null)):this.Tt?(clearTimeout(this.Tt),this.Tt=null,this.GL()):this.pj===a.Vz||null!=this.bj&&0<this.bj.length?this.pq(null):this.pj===a.QR&&this.MJ(null);this.C0=!1};a.$ca=function(b){var c=a.qw(b);return{Of:b.offsetWidth+(a.gg(c.marginLeft)+a.gg(c.marginRight)),lh:b.offsetHeight+(a.gg(c.marginTop)+a.gg(c.marginBottom))}};a.Zca=function(b){b=
a.qw(b);return{paddingLeft:a.gg(b.paddingLeft),paddingRight:a.gg(b.paddingRight),paddingTop:a.gg(b.paddingTop),paddingBottom:a.gg(b.paddingBottom),borderLeftWidth:a.gg(b.borderLeftWidth),borderRightWidth:a.gg(b.borderRightWidth),borderTopWidth:a.gg(b.borderTopWidth),borderBottomWidth:a.gg(b.borderBottomWidth)}};a.qw=function(a){var b=a.ownerDocument.defaultView,e=null;return e=b?b.getComputedStyle(a,null):a.currentStyle};a.gg=function(a){return 0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=
0),a):0};a.qf=function(a,b,e){a.addEventListener?a.addEventListener(b,e,!1):a.attachEvent&&a.attachEvent("on"+b,e)};a.ee=function(a,b,e){a.removeEventListener?a.removeEventListener(b,e,!1):a.detachEvent&&a.detachEvent("on"+b,e)};a.RS=function(a,b){if(a)for(var e=0;e<a.length;e++)if(a[e]==b)return e;return-1};a.Fga=function(a,b){var e=["gecko",16,"trident",6,"webkit",533.1],f=e.length;if(0==f%2)for(var h=0;h<=f-2;h+=2)if(a==e[h]){if(b>=e[1+h])return!0;break}return!1};a.yca=function(){var b=a.xi,c=
null,e=-1,f=navigator.userAgent.toLowerCase();-1!=f.indexOf("msie")||-1!=f.indexOf("trident")?(c="trident",e=b(f,/trident\/(\d+[.]\d+)/),-1==e&&(e=b(f,/msie (\d+\.\d+);/),-1==e&&(e=b(f,/msie (\d+\.\d+)b;/)),e-=4),null!=document.documentMode&&(e=Math.min(e,document.documentMode-4))):-1!=f.indexOf("applewebkit")?(c="webkit",e=b(f,/applewebkit\/(\d+([.]\d+)*)/)):-1!=f.indexOf("gecko/")&&(c="gecko",e=b(f,/rv:(\d+[.]\d+)/));return[c,e]};a.xi=function(a,b){var e=a.match(b);return e&&(e=e[1])?parseFloat(e):
-1};a.kaa=function(a,b){return a.HE>b.HE?1:a.HE<b.HE?-1:a.GE>b.GE?1:a.GE<b.GE?-1:0};a.prototype.tx=function(){this.$B||(this.pj?this.TK||(this.TK=!0):this.$B=setTimeout(this.nX,0))};a.prototype.kq=function(){for(var a=this.pc.querySelectorAll(this.tla),b=[],e=0;e<a.length;e++){var f=a[e],h=f.style;0<f.offsetWidth&&0<f.offsetHeight&&"hidden"!=h.visibility&&b.push(f)}return b};a.prototype.dM=function(){var b=this.bj,c=this.Zg();if(this.dk){var e=this.dk;c||(c=[]);for(var f=0;f<e.length;f+=2){var h=
e[f];0>a.RS(c,h)&&c.push(h)}}e=!1;if(!c||1>c.length){if(!b||1>b.length)this.bj=null,this.pq(null),e=!0}else this.bj=c;b=null!=c&&0<c.length;this.ug()||e||this.pq(null);return b};a.prototype.Zg=function(){var b=this.pc,c=this.kq();this.Kx&&this.Kx(c);var e=this.pH=null;this.wn=0;this.qa=1;this.Gt=null;var f=[],h=[],k=[],l=this.uj,m=a.Zca(b),n=0,p=[];this.QS=p;for(var r=0;r<c.length;r++){var s=c[r],q=this.rJ(s);(e=s.rA)&&delete s.rA;if(!this.pH){var t=q;e&&(t=document.createElement("div"),t.className=
e,t=this.rJ(t));this.pH=this.D$(s,t)}e=this.pH;this.Gt||(this.wn=Math.max(Math.floor((b.offsetWidth-m.paddingLeft-m.paddingRight-m.borderLeftWidth-m.borderRightWidth)/e.Of),1),this.bga(this.wn,this.qa),n=this.wn);q.colSpan>n&&(n=q.colSpan);q.colSpan>this.wn&&(q.colSpan=this.wn);for(var w=!1,t=0;t<this.qa;t++){for(var x=0;x<this.wn;x++)if(this.sca(x,t,q)){var w=s.style,u={top:w.top};l?u.right=w.right:u.left=w.left;h.push(u);this.MK(s,x,t,q,e,m);l&&k.push(x);w=!0;p.push({GE:x,HE:t,tile:s});break}if(w)break;
t===this.qa-1&&this.AS()}}e&&(b=this.Jq.style,b.width=n*e.Of+"px",b.height=this.qa*e.lh+"px");for(r=0;r<c.length;r++)s=c[r],w=s.style,u=h[r],""!=u.top&&(l&&parseInt(w.right,10)!==parseInt(u.right,10)||!l&&parseInt(w.left,10)!==parseInt(u.left,10)||parseInt(w.top,10)!==parseInt(u.top,10))&&f.push(s);1>f.length&&(f=null);return f};a.prototype.VZ=function(){var b=this.QS;this.QS=null;for(var b=b.sort(a.kaa),c=this.kq(),e=0;e<c.length;e++){var f=c[e],h=b[e].tile;f!=h&&(this.o0(h),f.parentNode.insertBefore(h,
f),this.n0(h),f=a.RS(c,h),f>e&&(c.splice(f,1),c.splice(e,0,h)))}};a.prototype.bga=function(a,b){for(var e=this.Gt=[],f=0;f<b;f++){var h=[];e.push(h);for(var k=0;k<a;k++)h[k]=!1}};a.prototype.AS=function(){this.qa++;var a=[];this.Gt.push(a);for(var b=0;b<this.wn;b++)a[b]=!1};a.prototype.sca=function(a,b,e){var f=e.colSpan;e=e.rowSpan;for(var h=b;h<b+e;h++){h>=this.qa&&this.AS();for(var k=a;k<a+f;k++)if(k>=this.wn||this.Gt[h][k])return!1}return!0};a.prototype.MK=function(a,b,e,f,h,k){var l=f.colSpan;
f=f.rowSpan;for(var m=this.Gt,n=e;n<e+f;n++)for(var p=b;p<b+l;p++)m[n][p]=!0;a=a.style;a.top=k.paddingTop+e*h.lh+"px";this.uj?a.right=k.paddingRight+b*h.Of+"px":a.left=k.paddingLeft+b*h.Of+"px"};a.prototype.J9=function(a){for(var b=this.kq(),e=0;e<b.length;e++)this.qn(b[e],a)};a.prototype.Ul=function(a){for(var b=this.kq(),e=0;e<b.length;e++)this.bh(b[e],a)};a.prototype.jM=function(b){this.nY||(this.WZ=b,this.ug()&&(this.J9(b?this.eM:this.fM),this.qn(this.Jq,b?this.$L:this.aM),a.qf(this.pc,"transitionend",
this.qk),a.qf(this.pc,"webkitTransitionEnd",this.qk)),this.nY=!0)};a.prototype.pq=function(b){var c=!0;if(this.bj){var e=this.bj;if(b){var f=b.target;for(b=0;b<e.length;b++)if(f===e[b]){e.splice(b,1);break}}else this.ug()||(e=this.bj=[]);0<e.length&&(c=!1)}if(c){if(this.dk&&(c=this.dk,this.dk=null,this.ug()))for(b=0;b<c.length;b+=2)this.bh(c[b],this.gM);this.WZ?(this.ug()&&(this.Ul(this.eM),this.bh(this.Jq,this.$L)),this.WZ=!1):this.ug()&&(this.Ul(this.fM),this.bh(this.Jq,this.aM));this.ug()&&(a.ee(this.pc,
"transitionend",this.qk),a.ee(this.pc,"webkitTransitionEnd",this.qk));this.HL=this.oX=this.b_=this.nY=!1;this.VZ();this.At&&this.At();if(this.pj===a.Vz)if(this.ug()){var h=this;this.Tt=setTimeout(function(){h.GL()},0)}else this.GL();else this.pj||this.Vn&&this.Vn()}};a.prototype.D$=function(b,c){var e=a.$ca(b);return{Of:e.Of/c.colSpan,lh:e.lh/c.rowSpan}};a.prototype.Kfa=function(){this.$B&&(clearTimeout(this.$B),this.$B=null);this.vk&&this.vk();this.pj=a.PR;if(this.ck&&this.ug()){for(var b=this.ck,
c=0;c<b.length;c++){var e=b[c];a.qf(e,"transitionend",this.mq);a.qf(e,"webkitTransitionEnd",this.mq);this.qn(e,this.cM)}var f=this;this.nt=setTimeout(function(){for(var a=0;a<b.length;a++){var c=b[a];f.bh(c,f.cM);f.qn(c,f.nD)}},0)}else this.GJ(null)};a.prototype.GJ=function(b){this.nt&&(clearTimeout(this.nt),this.nt=null);if(b){b.preventDefault();b.stopPropagation();b=b.target;this.bh(b,this.nD);a.ee(b,"transitionend",this.mq);a.ee(b,"webkitTransitionEnd",this.mq);var c=this.ck;if(c){for(var e=0;e<
c.length;e++){var f=c[e];if(f===b){c.splice(e,1);this.tl||(this.tl=[]);var h=this.tl;h.push(b);break}}1>c.length&&(this.ck=null)}}else if(!this.ug()&&(c=this.ck)){for(e=0;e<c.length;e++)f=c[e],this.tl||(this.tl=[]),h=this.tl,h.push(f);this.ck=null}if(!this.ck){if(this.tl){h=this.tl;for(e=0;e<h.length;e++)b=h[e],this.ug()&&this.bh(b,this.nD),c=b.style,this.uj?c.right="":c.left="",c.top="",this.mt&&this.mt(b);this.tl=null}this.pj=a.Vz;this.jM(!1);if(this.dk)for(h=this.dk,e=0;e<h.length;e+=2)b=h[e],
c=h[e+1],f=this.wW(b),this.bh(b,f),this.qn(b,c),this.ug()&&(this.qn(b,this.gM),b.rA=f);this.dM()}};a.prototype.GL=function(){this.Tt&&(clearTimeout(this.Tt),this.Tt=null);this.pj=a.QR;if(this.mi&&this.ug())for(var b=this.mi,c=0;c<b.length;c++){var e=b[c];a.qf(e,"transitionend",this.oq);a.qf(e,"webkitTransitionEnd",this.oq);this.qn(e,this.iM);this.bh(e,this.hM)}else{if(this.mi)for(b=this.mi,c=0;c<b.length;c++)e=b[c],this.bh(e,this.hM);this.MJ(null)}};a.prototype.MJ=function(b){if(b){b.preventDefault();
b.stopPropagation();b=b.target;this.bh(b,this.iM);a.ee(b,"transitionend",this.oq);a.ee(b,"webkitTransitionEnd",this.oq);var c=this.mi;if(c){for(var e=0;e<c.length;e++){var f=c[e];if(f===b){c.splice(e,1);this.fo&&this.fo(b);break}}1>c.length&&(this.mi=null)}}else if(!this.ug()&&(c=this.mi)){for(e=0;e<c.length;e++)f=c[e],this.fo&&this.fo(f);this.mi=null}this.mi||(this.pj=null,this.Vn&&this.Vn(),this.TK&&(this.TK=!1,this.tx()))};a.PR=1;a.Vz=2;a.QR=3});