/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore"],function(b,f){(function(){b.ya("oj.ojMenu",f.oj.baseComponent,{defaultElement:"\x3cul\x3e",delay:300,role:"menu",widgetEventPrefix:"oj",options:{menuSelector:"ul",openOptions:{initialFocus:"menu",launcher:null,position:{my:"start top",at:"start bottom",collision:"flipfit"}},submenuOpenOptions:{position:{my:"start top",at:"end top",collision:"flipfit"}},beforeOpen:null,select:null},_ComponentCreate:function(){this._super();this._focusForTesting=
this.fg;this._nextForTesting=this.LY;this._selectForTesting=this.vj;this.Sq=this.element;this.nO=!1;this.element.uniqueId().addClass("oj-menu oj-component").hide().attr({role:this.role,tabIndex:"0"});this._on(!0,{"mousedown .oj-menu-item":function(a){this.options.disabled&&a.preventDefault()},click:function(a){this.options.disabled&&a.preventDefault()},keydown:function(a){!this.options.disabled||a.keyCode!==f.ui.keyCode.ESCAPE&&a.keyCode!==f.ui.keyCode.TAB||(a.keyCode===f.ui.keyCode.TAB&&a.preventDefault(),
this.ic&&this.kB(a))}});this.options.disabled&&this.element.addClass("oj-disabled").attr("aria-disabled","true");var a=function(a){if(!this.iN){this.iN=!0;var b=f(a.currentTarget);b.siblings().removeClass("oj-focus-ancestor");this.fg(a,b)}}.bind(this);this._on({"mousedown .oj-menu-item \x3e a":function(a){a.preventDefault()},"click .oj-disabled \x3e a":function(a){a.preventDefault()},click:function(){this.nO=!1},touchstart:function(){this.iN=!1},mouseover:function(){this.iN=!1},"click .oj-menu-item:has(a)":function(a){var b=
f(a.target).closest(".oj-menu-item");!this.nO&&b.not(".oj-disabled").length&&(this.nO=!0,a.preventDefault(),this.Da&&this.Da.closest(b).length&&this.Da.get(0)!=b.get(0)||(b.has(".oj-menu").length?this.Xd(a):(this.vj(a),this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.Da&&1===this.Da.parents(".oj-menu").length&&clearTimeout(this.Xc)))))},"mouseenter .oj-menu-item":a,"touchstart .oj-menu-item":a,mouseleave:function(a){this.gk(a,"eventSubtree")},"mouseleave .oj-menu":function(a){this.gk(a,
"eventSubtree")},focus:function(a,b){if(!b){var c=this.Da||this.element.children(".oj-menu-item").eq(0);this.fg(a,c)}},keydown:this.wq,keyup:function(a){if(a.keyCode==f.ui.keyCode.ENTER||a.keyCode==f.ui.keyCode.SPACE)this.kA=!1}});this.Zx=f.proxy(this.$x,this);this.Aa()},As:function(a){if(arguments.length)d=a;else return d},yH:function(b){if(("focus"===b.type||"mousedown"===b.type||"touchstart"===b.type||93==b.which||121==b.which&&b.shiftKey||93==b.keyCode)&&("mousedown"!==b.type||!d)){var e=a.slice(0,
a.length);f.each(e,function(a,d){!f(b.target).closest(d.element).length&&("keydown"===b.type||"mousedown"===b.type&&3===b.which||!f(b.target).closest(d.ic).length||d.Zga&&("mousedown"===b.type&&3!==b.which||"touchstart"===b.type))&&(d.gk(b,"eventSubtree"),d.ic&&d.Hp(b))})}},_setOption:function(a,d){this._superApply(arguments);this.ic||("submenuOpenOptions"===a?this.cD=b.nc.xg(d.position,this.Lf):"submenuOpenOptions.position"===a&&(this.cD=b.nc.xg(d,this.Lf)))},_destroy:function(){this.element.is(":visible")&&
this.Hp();clearTimeout(this.Xc);delete this.Xc;this.element.removeAttr("aria-activedescendant").removeClass("oj-component").find(".oj-menu").addBack().removeClass("oj-menu oj-menu-submenu oj-menu-icons oj-menu-text-only").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();this.element.find(".oj-menu-item").removeClass("oj-menu-item").removeAttr("role").children("a").removeAttr("aria-disabled").removeUniqueId().removeClass("oj-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=
f(this);a.data("oj-ojMenu-submenu-icon")&&a.remove()});this.element.find("a").removeAttr("aria-expanded");this.element.find(".oj-menu-divider").removeClass("oj-menu-divider").removeAttr("role");0<=a.indexOf(this)&&a.splice(a.indexOf(this),1);delete this.sj;delete this.Zx;var b=this.vn;isNaN(b)||(delete this.vn,window.clearTimeout(b));this._super()},wq:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")}var d,h,k,l,m=!0;switch(a.keyCode){case f.ui.keyCode.HOME:this.tC("first",
"first",a);break;case f.ui.keyCode.END:this.tC("last","last",a);break;case f.ui.keyCode.UP:this.ria(a);break;case f.ui.keyCode.DOWN:this.LY(a);break;case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.keyCode===f.ui.keyCode.RIGHT^this.Lf?this.Da&&!this.Da.is(".oj-disabled")&&this.Xd(a):this.gk(a,"active");break;case f.ui.keyCode.ENTER:case f.ui.keyCode.SPACE:this.Mea(a);this.kA=!0;var n=this;setTimeout(function(){n.kA=!1},100);break;case f.ui.keyCode.TAB:a.preventDefault();this.ic&&this.kB(a);break;
case f.ui.keyCode.ESCAPE:this.ic?(h=this.element.attr("aria-activedescendant"),k="#"+this.element.attr("id")+"\x3e*\x3ea",h&&!f("#"+h).is(k)?this.gk(a,"active"):this.kB(a)):this.gk(a,"active");break;default:m=!1,d=this.xE||"",h=String.fromCharCode(a.keyCode),k=!1,clearTimeout(this.tna),h===d?k=!0:h=d+h,l=new RegExp("^"+b(h),"i"),d=this.Sq.children(".oj-menu-item").filter(function(){return l.test(f(this).children("a").text())}),d=k&&-1!==d.index(this.Da.next())?this.Da.nextAll(".oj-menu-item"):d,d.length||
(h=String.fromCharCode(a.keyCode),l=new RegExp("^"+b(h),"i"),d=this.Sq.children(".oj-menu-item").filter(function(){return l.test(f(this).children("a").text())})),d.length?(this.fg(a,d),1<d.length?(this.xE=h,this.tna=this._delay(function(){delete this.xE},1E3)):delete this.xE):delete this.xE}m&&a.preventDefault()},Mea:function(a){this.Da&&!this.Da.is(".oj-disabled")&&(this.Da.children("a[aria-haspopup\x3d'true']").length?this.Xd(a):this.vj(a))},refresh:function(){this._super();this.Aa();var a=this.element;
if(a.is(":visible")){var b=a.data("oj-menu-position");b&&a.position(b);a.find(".oj-menu").each(function(){var a=f(this);a.is(":visible")&&(b=a.data("oj-menu-position"))&&a.position(b)})}},Aa:function(){this.Lf="rtl"===this.ac();this.cD=b.nc.xg(this.options.submenuOpenOptions.position,this.Lf);var a=this,d=this.element.find(this.options.menuSelector),g=d.add(this.element),h=g.children();h.filter(".oj-menu-divider").has("a").removeClass("oj-menu-divider oj-menu-item").removeAttr("role");h.filter(":not(.oj-menu-item):has(a)").addClass("oj-menu-item").attr("role",
"presentation").children("a").uniqueId().attr({tabIndex:"-1",role:"menuitem"});h.filter(":not(.oj-menu-item)").each(function(){var a=f(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("oj-menu-divider").attr("role","separator")});h.filter(".oj-disabled").children("a").attr("aria-disabled","true");h.filter(":not(.oj-disabled)").children("a").removeAttr("aria-disabled");d.filter(":not(.oj-menu)").addClass("oj-menu oj-menu-submenu").hide().attr({role:this.role,"aria-hidden":"true"}).each(function(){var b=
f(this),d=a.mJ(b),e=f("\x3cspan\x3e");e.addClass("oj-menu-submenu-icon oj-component-icon").data("oj-ojMenu-submenu-icon",!0);d.attr("aria-haspopup","true").attr("aria-expanded","false").append(e);d=d.attr("id");b.attr("aria-labelledby",d)});g.each(function(){var a=f(this),b=a.children().children().children(".oj-menu-item-icon").length;a.toggleClass("oj-menu-icons",!!b).toggleClass("oj-menu-text-only",!b)});this.Da&&!f.contains(this.element[0],this.Da[0])&&this.WG()},mJ:function(a){return a.prev("a")},
fra:function(){return"menuitem"},mA:function(a){return a.add(a.prev(".oj-menu-divider")).add(a.next(".oj-menu-divider"))},fg:function(a,b){a&&"focus"===a.type||clearTimeout(this.Xc);b=b.first();this.vY(b,a);var d=b.parent().closest(".oj-menu-item");this.mA(d).addClass("oj-focus-ancestor");a&&"keydown"===a.type?this.vl():this.Xc=this._delay(function(){delete this.Xc;this.vl()},this.delay);d=b.children(".oj-menu");d.length&&a&&/^mouse/.test(a.type)&&!this.Da.hasClass("oj-disabled")&&this.bla(d);this.Sq=
b.parent()},vY:function(a,b){if(!a.is(this.Da)){var d=this.Da?this.Da:f(),h=a.children("a");this.Da=a;this.element.attr("aria-activedescendant",h.attr("id"));this.mA(d).removeClass("oj-focus");this.mA(a).addClass("oj-focus");this._trigger("_activeItem",b,{previousItem:d,item:a,privateNotice:"The _activeItem event is private.  Do not use."})}},bja:function(a){if(this.Da){var b=this.Da;this.Da=null;this.element.removeAttr("aria-activedescendant");this.mA(b).removeClass("oj-focus");this._trigger("_activeItem",
a,{previousItem:b,item:f(),privateNotice:"The _activeItem event is private.  Do not use."})}},WG:function(a){clearTimeout(this.Xc);this.bja(a)},kB:function(a){this.ic.focus();this.Hp(a)},Hp:function(c){var d={};d[b.N.Qa.cf]=this.element;b.N.le().close(d);this.element.removeData("oj-menu-position");this.ic=void 0;this._trigger("__dismiss",c,{});0<=a.indexOf(this)&&a.splice(a.indexOf(this),1)},open:function(c,d,g){this.element.is(":visible")&&this.Hp();d=f.extend({},this.options.openOptions,d);d.position=
f.extend({},d.position);g=f.extend({},this.options.submenuOpenOptions,g);b.nc.Qha(c);this.Zga=this.jA;if(this._trigger("beforeOpen",c,{openOptions:d})){var h=d.launcher;if((h="string"===f.type(h)?f(h):h)&&h.length){var k=b.nc.xg(d.position,this.Lf);k.of=b.nc.Uoa(k.of,h,c);if(null==k.of)b.r.warn("position.of passed to Menu.open() is 'event', but the event is null.  Ignoring the call.");else{var l=this.element[0],m=a.slice(0,a.length);f.each(m,function(a,b){b.element[0]!==l&&(b.gk(c,"eventSubtree"),
b.ic&&b.Hp(c))});this.cD=b.nc.xg(g.position,this.Lf);g=this.Zx;f.isFunction(k.using)&&k.using!==g&&(k.origUsing=k.using);k.using=g;g={};g[b.N.Qa.cf]=this.element;g[b.N.Qa.Zu]=h;g[b.N.Qa.cv]=k;g[b.N.Qa.dp]=this.ft();g[b.N.Qa.Sm]="oj-menu-layer";b.N.le().open(g);this.element.data("oj-menu-position",k);d=d.initialFocus;((k="firstItem"===d)||"menu"===d)&&this.element.focus();k?this.fg(c,this.element.children().first()):this.WG(c);this.ic=h;a.push(this)}}else b.r.warn("When calling Menu.open(), must specify openOptions.launcher via the component option, method param, or beforeOpen listener.  Ignoring the call.")}},
bla:function(a){clearTimeout(this.Xc);"true"===a.attr("aria-hidden")&&(this.Xc&&clearTimeout(this.Xc),this.Xc=this._delay(function(){delete this.Xc;this.vl();this.RY(a)},this.delay))},RY:function(b){var d=f.extend({of:this.Da},this.cD);clearTimeout(this.Xc);this.element.find(".oj-menu").not(b.parents(".oj-menu")).hide().attr("aria-hidden","true").removeData("oj-menu-position");b.show().removeAttr("aria-hidden").position(d).data("oj-menu-position",d);this.mJ(b).attr("aria-expanded","true");!this.ic&&
0>a.indexOf(this)&&a.push(this)},FG:function(a,b,d){function h(){delete k.Xc;var d=b?k.element:f(a&&a.target).closest(k.element.find(".oj-menu"));d.length||(d=k.element);k.vl(d);k.WG(a);k.Sq=d}clearTimeout(this.Xc);var k=this;d?this.Xc=this._delay(h,d):h()},vl:function(b){b||(b=this.Da?this.Da.parent():this.element);var d=b.find(".oj-menu");d.hide().attr("aria-hidden","true").removeData("oj-menu-position");this.mJ(d).attr("aria-expanded","false");b.find("oj-focus-ancestor").removeClass("oj-focus-ancestor");
this.ic||0<=a.indexOf(this)&&b===this.element&&a.splice(a.indexOf(this),1)},gk:function(a,d){if(null==d||"active"===d){var f=this.Sq&&this.Sq.closest(".oj-menu-item",this.element);f&&f.length&&(this.vl(),this.fg(a,f))}else"all"===d||"eventSubtree"===d?this.FG(a,"all"===d,this.delay):b.r.warn("Invalid param "+d+" passed to Menu._collapse().  Ignoring the call.")},Xd:function(a){var b=this.Da&&this.Da.children(".oj-menu ").children(".oj-menu-item").first();b&&b.length&&(this.RY(b.parent()),this.Xc&&
clearTimeout(this.Xc),this.Xc=this._delay(function(){delete this.Xc;this.fg(a,b)}))},LY:function(a){this.tC("next","first",a)},ria:function(a){this.tC("prev","last",a)},ara:function(){return this.Da&&!this.Da.prevAll(".oj-menu-item").length},bra:function(){return this.Da&&!this.Da.nextAll(".oj-menu-item").length},tC:function(a,b,d){var f;this.Da&&(f="first"===a||"last"===a?this.Da["first"===a?"prevAll":"nextAll"](".oj-menu-item").eq(-1):this.Da[a+"All"](".oj-menu-item").eq(0));f&&f.length&&this.Da||
(f=this.Sq.children(".oj-menu-item")[b]());this.fg(d,f)},vj:function(a){if(!this.Da&&a&&a.target){var d=f(a.target).closest(".oj-menu-item");d.closest(this.element).length&&this.vY(d,a)}this.Da?this.Da.has(".oj-menu").length||this.Da.is(".oj-disabled")?b.r.warn("Selecting a disabled menu item or parent menu item is not allowed."):(d={item:this.Da},this.FG(a,!0),this.ic&&this.kB(a),this._trigger("select",a,d)):b.r.warn("Menu._select() called when no menu item is focused and no menu item can be inferred from event param.")},
Mq:function(){this.element.remove()},ft:function(){if(!this.sj){var a=this.sj={};a[b.N.xc.Rr]=f.proxy(this.FT,this);a[b.N.xc.Sr]=f.proxy(this.Mq,this);a[b.N.xc.Um]=f.proxy(this.refresh,this);a[b.N.xc.Qr]=f.proxy(this.yH,this)}return this.sj},FT:function(){this.vl(this.element);this.Hp(null)},$x:function(a,d){var g=d.element.element;g.css(a);(g=g.data("oj-menu-position"))&&(g=g.origUsing)&&g(a,d);b.nc.JN(d)&&(this.vn=this._delay(f.proxy(this.FT,this),1))}});var a=[],d=!1})()});