/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery"],function(b,f){b.X=function(a,b,c){this.Init(a,b,c)};o_("Message",b.X,b);b.X.Tj={CONFIRMATION:"confirmation",INFO:"info",WARNING:"warning",ERROR:"error",FATAL:"fatal"};o_("Message.SEVERITY_TYPE",b.X.Tj,b);b.X.Qb={FATAL:5,ERROR:4,WARNING:3,INFO:2,CONFIRMATION:1};o_("Message.SEVERITY_LEVEL",b.X.Qb,b);b.b.ga(b.X,b.b,"oj.Message");b.X.prototype.Init=function(a,d,c){b.X.q.Init.call(this);this.summary=a;this.detail=d;this.severity=c||b.X.Tj.ERROR};b.b.g("Message.prototype.Init",
{Init:b.X.prototype.Init});b.X.prototype.o1=function(){return!0};b.X.prototype.Ao=function(a){return a&&b.X.vu(this.severity)===b.X.vu(a.severity)&&this.summary===a.summary&&this.detail===a.detail?!0:!1};b.b.g("Message.prototype.equals",{Ao:b.X.prototype.Ao});b.X.prototype.clone=function(){return new b.X(this.summary,this.detail,this.severity)};b.b.g("Message.prototype.clone",{clone:b.X.prototype.clone});b.X.vu=function(a){a&&("string"===typeof a?(a=b.X.YF.indexOf(a,1),a=-1===a?b.X.Qb.ERROR:a):"number"===
typeof a&&a<b.X.Qb.CONFIRMATION&&a>b.X.Qb.FATAL&&(a=b.X.Qb.ERROR));return a?a:b.X.Qb.ERROR};o_("Message.getSeverityLevel",b.X.vu,b);b.X.Jna=function(a){var d;a&&("string"===typeof a?(d=b.X.YF.indexOf(a,1),-1===d&&(a=b.X.Tj.ERROR)):"number"===typeof a&&(a=a<b.X.Qb.CONFIRMATION&&a>b.X.Qb.FATAL?b.X.Tj.ERROR:b.X.YF[a]));return a||b.X.Tj.ERROR};o_("Message.getSeverityType",b.X.Jna,b);b.X.tu=function(a){var d=-1,c;a&&0<a.length&&f.each(a,function(a,g){g&&(c=b.X.vu(g.severity));d=d<c?c:d});return d};o_("Message.getMaxSeverity",
b.X.tu,b);b.X.isValid=function(a){return b.X.tu(a)>=b.X.Qb.ERROR?!1:!0};o_("Message.isValid",b.X.isValid,b);b.X.YF=["none",b.X.Tj.CONFIRMATION,b.X.Tj.INFO,b.X.Tj.WARNING,b.X.Tj.ERROR,b.X.Tj.FATAL];b.Fc=function(a,b,c,e){this.Init(a,b,c,e)};b.b.ga(b.Fc,b.X,"oj.ComponentMessage");b.Fc.Jr={tF:"shown",fF:"hidden"};b.Fc.R6={display:b.Fc.Jr.tF,context:""};b.Fc.prototype.Init=function(a,d,c,e){b.Fc.q.Init.call(this,a,d,c);this.gb=f.extend({},b.Fc.R6,e)};b.Fc.prototype.Ao=function(a){return b.Fc.q.Ao.call(this,
a)&&this.gb.display===a.gb.display};b.Fc.prototype.clone=function(){return new b.Fc(this.summary,this.detail,this.severity,this.gb)};b.Fc.prototype.o1=function(){return!(this.gb&&this.gb.display&&this.gb.display===b.Fc.Jr.fF)};b.Fc.prototype.uca=function(){this.gb&&b.Fc.Jr.fF===this.gb.display&&(this.gb.display=b.Fc.Jr.tF)};b.Fc.prototype.SX=function(){return this.gb&&this.gb.context?!0:!1}});