/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","knockout","promise"],function(b,f){b.ea={};b.ea.KQ={coverStart:{qr:"oj-animation-coverstart",Qo:"oj-animation-coverstart",Ro:!0},coverUp:{Qo:"oj-animation-coverup",Ro:!0},fade:{qr:"oj-animation-fade",Qo:"oj-animation-fade",Ro:!1},revealDown:{qr:"oj-animation-revealdown",Ro:!1},revealEnd:{qr:"oj-animation-revealend",Qo:"oj-animation-revealend",Ro:!1},zoomIn:{Qo:"oj-animation-zoomin",Ro:!0},zoomOut:{qr:"oj-animation-zoomout",Ro:!1}};b.ea.KS=function(a,b,c){var e=$(a);return new Promise(function(a){function f(){a(!0)}
var k="oj-"+c,l=k+"-active";e.addClass(b);e.addClass(k);window.requestAnimationFrame(function(){e.addClass(l)});if((k=e.css("animationDuration")||e.css("webkitAnimationDuration"))&&"0s"!=k)e.on("animationend webkitAnimationEnd",f);else if((k=e.css("transitionDuration")||e.css("webkitTransitionDuration"))&&"0s"!=k)e.on("transitionend webkitTransitionEnd",f);else a(!0)})};b.ea.W9=function(a,d,c){var e=[];c=b.ea.KQ[c];a&&c&&c.qr&&e.push(b.ea.KS(a,c.qr,"leave"));d&&c&&c.Qo&&e.push(b.ea.KS(d,c.Qo,"enter"));
return Promise.all(e)};b.ea.xS=function(a,b){for(var c=f.virtualElements.firstChild(a);c;)1==c.nodeType?b.push(c):8==c.nodeType&&this.xS(c,b),c=f.virtualElements.nextSibling(c)};b.ea.B$=function(a,b){a._ojOldRoot=b};b.ea.eea=function(a){return a._ojOldRoot};b.ea.oU=function(a){if(a.isInitial)return!1;if(1==a.node.nodeType)return!0;if(8==a.node.nodeType){var d=[];b.ea.xS(a.node,d);if(d&&1==d.length)return b.ea.B$(a,d[0]),!0}return!1};b.ea.Dda=function(a){var d;1==a.node.nodeType?d=a.node:8==a.node.nodeType&&
(d=b.ea.eea(a));return d};b.ea.OH=function(a){var b=$(document.createElement("div")),c={position:"absolute",height:a.offsetHeight+"px",width:a.offsetWidth+"px",left:a.offsetLeft+"px",top:a.offsetTop+"px"};b.appendTo(a.offsetParent);b.css(c);b.addClass("oj-animation-host-viewport");a=document.createElement("div");a.className="oj-animation-host";b.append(a);return a};b.ea.rU=function(a,d){var c={},e=b.ea.KQ[d],f=b.ea.Dda(a);e&&(e.Qo&&!e.Ro&&(c.newViewParent=b.ea.OH(f)),e.qr&&(c.oldViewParent=b.ea.OH(f)),
e.Qo&&e.Ro&&(c.newViewParent=b.ea.OH(f)));return c};b.ea.nU=function(a,d){return b.ea.W9(a.oldViewParent,a.newViewParent,d).then(function(){b.ea.jia(a)})};b.ea.SZ=function(a,b){var c=a[b];c&&(c=c.parentNode)&&c.parentNode&&c.parentNode.removeChild(c)};b.ea.jia=function(a){a.removeOldView();a.insertNewView();b.ea.SZ(a,"newViewParent");b.ea.SZ(a,"oldViewParent")};b.ea.dq=function(a){return{canAnimate:b.ea.oU,prepareAnimation:function(d){return b.ea.rU(d,a)},animate:function(d){return b.ea.nU(d,a)}}};
b.ea.$I=function(a){null==b.ea.xK&&(b.ea.xK=b.we.i4("oj-animation-navigate-methods"));return b.ea.xK?b.ea.xK[a]:null};b.ea.Jha=function(a,d){return b.ea.$I(d)&&b.ea.oU(a)};b.ea.Kha=function(a,d){var c=b.ea.$I(d);return b.ea.rU(a,c)};b.ea.Iha=function(a,d){var c=b.ea.$I(d);return b.ea.nU(a,c)};b.ea.aW=function(a){return{canAnimate:function(d){return b.ea.Jha(d,a)},prepareAnimation:function(d){return b.ea.Kha(d,a)},animate:function(d){return b.ea.Iha(d,a)}}};b.ea.Lma=b.ea.dq("coverStart");o_("ModuleAnimations.coverStart",
b.ea.Lma,b);b.ea.spa=b.ea.dq("revealEnd");o_("ModuleAnimations.revealEnd",b.ea.spa,b);b.ea.Mma=b.ea.dq("coverUp");o_("ModuleAnimations.coverUp",b.ea.Mma,b);b.ea.rpa=b.ea.dq("revealDown");o_("ModuleAnimations.revealDown",b.ea.rpa,b);b.ea.fqa=b.ea.dq("zoomIn");o_("ModuleAnimations.zoomIn",b.ea.fqa,b);b.ea.gqa=b.ea.dq("zoomOut");o_("ModuleAnimations.zoomOut",b.ea.gqa,b);b.ea.sna=b.ea.dq("fade");o_("ModuleAnimations.fade",b.ea.sna,b);b.ea.lna=b.ea.aW("drillIn");o_("ModuleAnimations.drillIn",b.ea.lna,
b);b.ea.mna=b.ea.aW("drillOut");o_("ModuleAnimations.drillOut",b.ea.mna,b);b.ea.Mpa=function(a){return new function(){function d(a){return function(b){return c[a].call(c,b)}}var c,e=this;this.canAnimate=function(f){var h=a(f);c=null==h?null:b.ModuleAnimations[h];if(!c)return!1;for(var h=["prepareAnimation","animate"],k=0;k<h.length;k++){var l=h[k];e[l]=d(l)}return d("canAnimate")(f)}}};o_("ModuleAnimations.switcher",b.ea.Mpa,b)});