/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","promise"],function(b,f){b.Y=window.oj.Events={on:function(a,b,c){return this.jl(a,b,c,!1,!1)},off:function(a,b,c){return this.AK(a,b,c,!1)},trigger:function(a){var d=Array.prototype.slice.call(arguments);d.unshift(!1);return b.Y.Gb.apply(this,d)},once:function(a,b,c){return this.QY(a,b,c,!1,null)},listenTo:function(a,d,c){var e,g,f,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=b.Y.cq(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].V,f={event:e,
V:g,object:a,Jb:l[k]},this.sH(this._listeningTo,f,b.Y.pY),e=g?e+":"+g:e,void 0===this._listeningTo&&(this._listeningTo=[]),this._listeningTo.push(f),a.jl(e,l[k],null,!0,!1);return this},listenToOnce:function(a,d,c){var e,g,f,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=b.Y.cq(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].V,f={event:e,V:g,object:a,Jb:l[k]},this.sH(this._listeningTo,f,b.Y.pY),e=g?e+":"+g:e,void 0===this._listeningTo&&(this._listeningTo=[]),this._listeningTo.push(f),
a.QY(e,l[k],null,!0,this);return this},stopListening:function(a,d,c){var e,g={},f,k,l,m,n,p,r,s,q;if(null==arguments||1>=arguments.length){p=this._listeningTo?this._listeningTo.length:0;for(s=0;s<p;s++)if(m=this._listeningTo[s],n=a?a===m.object:!0)n=m.object.AK,n.apply(m.object,[m.event,m.Jb,m.context,!0]);this._listeningTo=[];return this}e=d;a&&a.constructor===String&&(e=a);e.constructor===String?g[e]=c:g=e;for(q in g)if(g.hasOwnProperty(q))for(e=b.Y.cq(q),f=0;f<e.length;f+=1)for(k=e[f].event,l=
e[f].V,p=this._listeningTo?this._listeningTo.length:0,s=p-1;0<=s;s-=1)m=this._listeningTo[s],n=a?a===m.object:!0,p=k?k===m.event:!0,r=c?g[q]===m.Jb:!0,m=l?l===m.V:!0,n&&p&&r&&m&&(n=this._listeningTo[s].object.AK,n.apply(this._listeningTo[s].object,[this._listeningTo[s].event,this._listeningTo[s].Jb,this._listeningTo[s].context,!0]),this._listeningTo.splice(s,1));return this}};b.Y.bind=b.Y.on;b.Y.unbind=b.Y.off;b.Y.D={ADD:"add",ALLADDED:"alladded",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",
CHANGE:"change",DESTROY:"destroy",ALLREMOVED:"allremoved",REQUEST:"request",SYNC:"sync",ERROR:"error",INVALID:"invalid",READY:"ready",ALL:"all"};o_("Events.EventType",b.Y.D,b);b.Y.pF=function(a,b){var c,e=b||this;for(c in e)"function"===typeof e[c]&&(a[c]=e[c]);a.Wc={};a._listeningTo=[]};b.Y.QY=function(a,b,c,e,g){var f,k,l,m;l=this.II(a,b);for(m in l)if(l.hasOwnProperty(m))for(a=this.cq(m),b=0;b<a.length;b+=1)f=a[b].event,k=a[b].V,void 0===this.Wc&&(this.Wc=[]),void 0===this.Wc[f]&&(this.Wc[f]=[]),
this.Wc[f].push({Jb:l[m],context:c,V:k,vm:!0,fired:!1,Ko:e,Uy:g});return this};b.Y.U_=function(a){return a.vm?a.fired?!1:a.fired=!0:!0};b.Y.AV=function(a,b){return b.context||b.Uy||a};b.Y.Gb=function(a,d){var c=this.cq(d),e,g,f,k,l,m;k=[];for(e=0;e<c.length;e+=1)g=c[e].event,f=c[e].V,k.push({event:g,V:f});for(e=0;e<k.length;e+=1){l=this.zB(this.Wc,b.Y.D.ALL);c=b.Y.zB(this.Wc,k[e].event,!1);for(g=0;g<(c?c.length:0);g+=1)c[g].V===k[e].V&&c[g].Jb&&(f=Array.prototype.slice.call(arguments),c&&c[g]&&c[g].vm&&
(this.MZ(b.Y.zB(this.Wc,k[e].event,!0),c[g]),c[g].Uy&&c[g].Uy.stopListening(this,d,c[g].Jb)),c&&c[g]&&this.U_(c[g])&&(m=c[g].Jb,a&&!c[g].k3||m.apply(b.Y.AV(this,c[g]),f.slice(2))));for(g=0;g<(l?l.length:0);g+=1)f=Array.prototype.slice.call(arguments),0<f.length&&(f[1]=k[e].V?k[e].event+":"+k[e].V:k[e].event),l&&l[g]&&l[g].Jb&&this.U_(l[g])&&(m=l[g].Jb,a&&!l[g].k3||m.apply(b.Y.AV(this,l[g]),f.slice(1))),l&&l[g]&&l[g].vm&&(this.MZ(this.zB(this.Wc,b.Y.D.ALL,!0),l[g]),l[g].Uy&&l[g].Uy.stopListening(this,
b.Y.D.ALL,l[g].Jb))}return this};b.Y.jl=function(a,d,c,e,g){var f,k,l,m;a=this.II(a,d);for(f in a)if(a.hasOwnProperty(f))for(d=this.cq(f),k=0;k<d.length;k+=1)l=d[k].event,m=d[k].V,void 0===this.Wc&&(this.Wc=[]),void 0===this.Wc[l]&&(this.Wc[l]=[]),m={Jb:a[f],context:c,V:m,Ko:e,k3:g},-1===this.sH(this.Wc[l],m,b.Y.Afa)&&this.Wc[l].push(m);return this};b.Y.AK=function(a,b,c,e){var g,f;if(null==arguments||0==arguments.length)return this.Wc={},this;if(null==a)return this.LZ(a,b,c,e),this;g=this.II(a,b);
for(f in g)g.hasOwnProperty(f)&&this.LZ(f,g[f],c,e);return this};b.Y.II=function(a,b){var c={};a.constructor===String?c[a]=b:c=a;return c};b.Y.LZ=function(a,d,c,e){var g=[],f,k,l,m,n,p,r,s;if(a)g=b.Y.cq(a);else if(void 0!==this.Wc)for(k in this.Wc)this.Wc.hasOwnProperty(k)&&g.push({event:k});for(a=0;a<g.length;a+=1)if(k=g[a].event,l=g[a].V,void 0!==this.Wc&&this.Wc[k]instanceof Array){m=this.Wc[k];for(f=m.length-1;0<=f;f-=1)n=void 0===d||null===d||m[f].Jb==d,p=void 0===c||null===c||m[f].context==
c,r=void 0===l||null===l||m[f].V==l,s=void 0===e||null===e||m[f].Ko==e,n&&p&&r&&s&&m.splice(f,1);0===m.length&&delete this.Wc[k]}};b.Y.MZ=function(a,b){var c,e,g,f,k,l;if(a)for(c=a.length-1;0<=c;c-=1)e=void 0===b.Jb||null===b.Jb||a[c].Jb==b.Jb,g=void 0===b.context||null===b.context||a[c].context==b.context,f=void 0===b.V||null===b.V||a[c].V==b.V,k=void 0===b.Ko||null===b.Ko||a[c].Ko==b.Ko,l=void 0===b.vm||null===b.vm||a[c].vm==b.vm,e&&g&&f&&k&&l&&a.splice(c,1)};b.Y.cq=function(a){a=a?a.split(" "):
[];var b=[],c,e,g;for(c=0;c<a.length;c+=1)e=a[c].split(":"),g=e[0],e=1<e.length?e[1]:null,b.push({event:g,V:e});return b};b.Y.Afa=function(a,b){return a.Jb===b.Jb&&a.V===b.V&&a.context===b.context&&a.Ko===b.Ko&&a.vm===b.vm};b.Y.pY=function(a,b){return a.event===b.event&&a.V===b.V&&a.context===b.context&&a.object===b.object};b.Y.sH=function(a,b,c){var e;if(void 0===a)return-1;for(e=0;e<a.length;e+=1)if(c(a[e],b))return e;return-1};b.Y.zB=function(a,b,c){if(a&&a[b]instanceof Array){if(c)return a[b];
c=[];var e;for(e=0;e<a[b].length;e++)c.push(a[b][e]);return c}return null};b.t=function(a,d){b.t._init(this,a,d,null)};o_("Model",b.t,b);b.b.ga(b.t,b.b,"oj.Model");b.t.prototype.Init=function(){b.t.q.Init.call(this)};b.t.prototype.attributes={};b.b.g("Model.prototype.attributes",{attributes:b.t.prototype.attributes});b.t.prototype.Cc={};b.b.g("Model.prototype.defaults",{Cc:b.t.prototype.Cc});b.t.prototype.id=null;b.b.g("Model.prototype.id",{id:b.t.prototype.id});b.t.prototype.j3="id";b.b.g("Model.prototype.idAttribute",
{j3:b.t.prototype.j3});b.t.prototype.s5=null;b.b.g("Model.prototype.urlRoot",{s5:b.t.prototype.s5});b.t.prototype.zj=null;b.b.g("Model.prototype.customURL",{zj:b.t.prototype.zj});b.t.WJ=0;b.t._init=function(a,d,c,e){var g=null,h;if(!b.t.Xw){a.Init();b.Y.pF(a);a.Gs();a.xO={};a.sE=!1;a.index=-1;c=c||{};a.attributes={};a.defaults&&!c.qoa&&(a.attributes=b.t.HA(f.isFunction(a.defaults)?a.defaults():a.defaults,null));for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);if(d)if(e=c.parse,f.isFunction(e)&&(a.parse=
e),h=b.t.HA(d,a.attributes),h=e?a.parse(h):h,null==h||void 0===h)a.attributes={};else for(g in h)h.hasOwnProperty(g)&&a.zL(g,h[g],!1,!1,c);a.pz();a.hv(c.collection);c.customURL&&(a.customURL=c.customURL);c.url&&(a.url=c.url);c.urlRoot&&(a.urlRoot=c.urlRoot);a.initialize&&a.initialize(d,c);a.Uj()}};b.t.extend=function(a,d){b.t.Xw=!0;var c,e;c=new b.t;b.t.Xw=!1;f.extend(c,this.prototype);a=a||{};for(e in a)a.hasOwnProperty(e)&&(c[e]=a[e]);var g;g=a&&a.constructor&&a.hasOwnProperty("constructor")?a.constructor:
function(d,c){b.t._init(this,d,c,a)};f.extend(g,this);g.prototype=c;g.extend=b.t.extend;g.prototype.constructor=g;b.Y.pF(g,this);if(d)for(e in d)d.hasOwnProperty(e)&&(g[e]=d[e]);return g};o_("Model.extend",b.t.extend,b);b.t.prototype.Gb=function(){};b.t.prototype.pz=function(){this.gp()||(this.cid="id"+b.t.WJ,b.t.WJ+=1)};b.t.prototype.gp=function(){return this.cid};b.t.prototype.iv=function(a){this.index=a};b.t.prototype.U5=function(){return this.index};b.t.prototype.vF=function(a){this.Soa=a};b.t.prototype.qz=
function(a){var b=this.yO;this.yO=a;return b};b.t.prototype.h6=function(a,d,c){var e,g=!1,f=b.Ea.jd(d),k,l=!1;for(e in a.attributes)a.attributes.hasOwnProperty(e)&&(k=this.attributes[e]!=a.attributes[e],f?e===d&&k&&(g=!0):k&&(g=!0),k&&(l=!0,this.attributes[e]=a.attributes[e],this.IG(e,a.attributes[e]),this.eB(e,this.attributes[e],null,c)));this.Uj();l&&this.fB(null,c);return g};b.t.VB=function(a){var b;if(a&&a instanceof Object)for(b in a)if(a.hasOwnProperty(b))return!0;return!1};b.t.prototype.hv=
function(a){null==a?delete this.collection:(this.collection=a,this.Uj())};b.t.prototype.Wu=function(){return this.collection};b.t.prototype.eB=function(a,d,c,e){null!=a&&this.Gb(e,b.Y.D.CHANGE+":"+a,this,d,c)};b.t.prototype.fB=function(a,d){this.Gb(d,b.Y.D.CHANGE,this,a,null)};b.t.prototype.Uj=function(){var a=null;this.collection&&this.collection.modelId&&(a=this.collection.modelId,a=f.isFunction(a)?a.call(this.collection,this.attributes):a);a||(a=this.QI(),a=null!=this.attributes?this.attributes[a]:
null);this.id=a};b.t.prototype.Cka=function(a,d,c){var e=b.b.Iv(this.attributes[a],d);return c||!e?(this.attributes[a]=d,this.Uj(),!e):!1};b.t.prototype.Gs=function(){this.changed={}};b.t.prototype.IG=function(a,b){this.changed[a]=b};b.t.prototype.zL=function(a,d,c,e,g){if(null==a)return!0;var f={},k,l=this.sE;if(e)for(k in a)a.hasOwnProperty(k)&&(f[k]=a[k]);else f[a]=d;a=g||{};if(!this.Yv(f,{validate:a.validate},!1))return!1;l||(this.Gs(),this.xo=[]);this.sE||(this.xO=b.t.HA(this.attributes,null));
this.sE=!0;for(k in f)f.hasOwnProperty(k)&&(this.Cka(k,f[k],c)?(this.IG(k,f[k]),this.xo.push(k)):delete f[k]);c=a.silent;for(k in f)f.hasOwnProperty(k)&&(!c&&(0<this.xo.length||l&&-1===this.xo.indexOf(k))&&(this.j4=!0,this.Zoa=a),this.eB(k,f[k],a,c));if(l)return!0;if(!c&&!l)for(;this.j4;)this.j4=!1,this.fB(this.Zoa,c);this.sE=!1;return!0};b.t.prototype.clear=function(a){var d,c={silent:!0},e;a=a||{};e=a.silent;c.validate=a.validate;this.Gs();for(d in this.attributes)if(this.attributes.hasOwnProperty(d)){if(!this.pD(d,
c,!0))return!1;this.Gb(e,b.Y.D.CHANGE+":"+d,this,void 0,null)}this.attributes={};this.Uj();this.eB(null,null,null,e);this.fB(null,e);return this};b.b.g("Model.prototype.clear",{clear:b.t.prototype.clear});b.t.HA=function(a,d){d=d||{};for(var c in a)d.hasOwnProperty(c)&&a.hasOwnProperty(c)&&void 0===a[c]&&delete a[c];b.lc.Xe(d,a,void 0,!0,1E4);return d};b.t.prototype.clone=function(){var a=new this.constructor,d;for(d in this)this.hasOwnProperty(d)&&this[d]!==this.attributes&&(a[d]=this[d]);a.attributes=
b.t.HA(this.attributes,null);delete a.cid;a.pz();a.Uj();return a};b.b.g("Model.prototype.clone",{clone:b.t.prototype.clone});b.t.prototype.kp=function(a,b){var c=this.Vf();if(void 0!==c&&c==a)return!0;c=this.cid;return void 0!==c&&c==b?!0:!1};b.t.prototype.set=function(a,d,c){var e=c||{},g,f=!0;if(arguments&&0<arguments.length)if(b.Ea.jd(a))e.unset?this.pD(a,null,!1):this.zL(a,d,!1,!1,e)||(f=!1);else if(e=d||{},e.unset)for(g in a)a.hasOwnProperty(g)&&this.pD(g,null,!1);else this.zL(a,null,!0,!0,e)||
(f=!1);return f?this:!1};b.b.g("Model.prototype.set",{set:b.t.prototype.set});b.t.prototype.q5=function(a,b){return this.pD(a,b,!1)};b.b.g("Model.prototype.unset",{q5:b.t.prototype.q5});b.t.prototype.pD=function(a,b,c){b=b||{};var e=b.silent,g={};if(this.has(a)){if(!this.Yv(g,b,!1))return!1;c||this.Gs();delete this.attributes[a];this.IG(a,void 0);this.eB(a,null,null,e);this.fB(null,e)}this.Uj();return!0};b.t.prototype.get=function(a){return this.attributes[a]};b.b.g("Model.prototype.get",{get:b.t.prototype.get});
b.t.prototype.has=function(a){return b.j.zl(this.attributes[a])};b.b.g("Model.prototype.has",{has:b.t.prototype.has});b.t.prototype.fetch=function(a){a=a||{};var d=a.success,c=a.error,e=this,g;g=b.t.Up(a);g.error=function(d,g,f){b.t.Vx(e,!1,a,g,f,d);c&&c.apply(e,arguments)};g.success=function(c){g.xhr&&(a.xhr=g.xhr);b.t.jB(e,c,g);f.isFunction(e.parse)&&e.set(e.parse(c),g);d&&d.call(e,this,c,a)};b.t.Rw("read",this,g)};b.b.g("Model.prototype.fetch",{fetch:b.t.prototype.fetch});b.t.prototype.parse=function(a){return a};
b.t.prototype.url=function(){var a=this.JW(),d=this.Vf();if(a)return d?a+"/"+encodeURIComponent(d):a;if(a=this.collection)return a=b.t.Qm(a,"url"),d&&a?(d="/"==b.t.nda(a)?"":"/",a+d+encodeURIComponent(this.Vf())):a;throw new b.Ym;};b.b.g("Model.prototype.url",{url:b.t.prototype.url});b.t.prototype.keys=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(a);return b};b.b.g("Model.prototype.keys",{keys:b.t.prototype.keys});b.t.prototype.u5=function(){var a,b=[];
for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(this.get(a));return b};b.b.g("Model.prototype.values",{u5:b.t.prototype.u5});b.t.prototype.h4=function(){var a,b=[],c;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(c=[],c.push(a),c.push(this.get(a)),b.push(c));return b};b.b.g("Model.prototype.pairs",{h4:b.t.prototype.h4});b.t.prototype.f4=function(a){var b=[],c,e,g={};if(a instanceof Array)b=a;else for(c=0;c<arguments.length;c++)b.push(arguments[c]);for(e in this.attributes)this.attributes.hasOwnProperty(e)&&
-1==b.indexOf(e)&&(g[e]=this.get(e));return g};b.b.g("Model.prototype.omit",{f4:b.t.prototype.f4});b.t.prototype.k4=function(a){var b=[],c,e={};if(a instanceof Array)b=a;else for(c=0;c<arguments.length;c++)b.push(arguments[c]);for(c=0;c<b.length;c++)this.attributes.hasOwnProperty(b[c])&&(e[b[c]]=this.get(b[c]));return e};b.b.g("Model.prototype.pick",{k4:b.t.prototype.k4});b.t.prototype.q3=function(){var a,b={},c;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(c=this.get(a),b[c]=a);return b};
b.b.g("Model.prototype.invert",{q3:b.t.prototype.q3});b.t.nda=function(a){return a.charAt(a.length-1)};b.t.prototype.Vja=function(){var a=this.JW();return a?a:this.Wu()?this.Wu().url:null};b.t.prototype.JW=function(){return b.t.Qm(this,"urlRoot")};b.t.prototype.parseSave=function(a){return a};b.t.prototype.isValid=function(){var a={};a.validate=this.validate;return this.Yv(this.attributes,a,!1)};b.b.g("Model.prototype.isValid",{isValid:b.t.prototype.isValid});b.t.Qga=function(a,b){a=a||{};return void 0!==
a.validate&&null!==a.validate?a.validate:b};b.t.prototype.Yv=function(a,d,c){d=d||{};var e=this.validate;return e&&b.t.Qga(d,c)&&(this.validationError=e.call(this,a,d))?(this.Gb(!1,b.Y.D.INVALID,this,this.validationError,d),!1):!0};b.t.sia=function(a){var d=!1,c={},e,g={};if(a&&0<a.length){1<a.length&&a[a.length-1]&&b.t.VB(a[a.length-1])&&(d=!0,c=a[a.length-1]||{});if(null==a[0])return{attributes:null,options:c};if(b.t.VB(a[0])||b.b.mh(a[0]))for(e in a[0])a[0].hasOwnProperty(e)&&(g[e]=a[0][e]);else for(e=
0;e<a.length;e+=2)if(void 0!==a[e]||e<a.length-1||!d&&e===a.length-1)g[a[e]]=a[e+1]}return{attributes:g,options:c}};b.t.Up=function(a){var b={},c;a=a||{};for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};b.t.Vx=function(a,d,c,e,g,f){c=c||{};c.textStatus=e;c.errorThrown=g;a.Gb(d,b.Y.D.ERROR,a,f,c)};b.t.prototype.save=function(a,d){var c,e,g,h,k,l;c=b.t.sia(arguments);var m,n,p;p=void 0===a?void 0:c.attributes;d=d||{};m=b.t.Up(c.options);if(!this.Yv(this.attributes,m,!0))return!1;m.wait||this.set(p);
c=void 0===m.forceNew?!1:m.forceNew;h=this;k=m.error;l=m.patch;m.error=function(a,c,e){b.t.Vx(h,!1,d,c,e,a);k&&k.apply(h,arguments)};m.saveAttrs=m.wait?this.g$(p):this.attributes;n=this.attributes;this.attributes=m.saveAttrs;m.saveAttrs=this.toJSON();this.attributes=n;if(!c&&!this.iE())return e=m.success,m.success=function(a){var c;m.xhr&&(d.xhr=m.xhr);a&&(c=f.isFunction(h.parse)?h.parse(a):a,h.attributes=f.extend(!0,h.attributes,c),h.Uj());b.t.jB(h,a,m);m.wait&&h.set(p);e&&e.call(b.t.Ti(m,h),h,a,
d);h.Gs()},m.attrs||(m.attrs=void 0===p?void 0:l?p:m.saveAttrs),b.t.Rw(l?"patch":"update",this,m);g=b.t.zW(m);m.success=function(a){var c;m.xhr&&(d.xhr=m.xhr);if(a){c=f.isFunction(h.parse)?h.parse(a):a;if(!h.Yv(c,m,!0))return;h.attributes=f.extend(!0,h.attributes,c);h.Uj()}m.wait&&h.set(p);b.t.jB(h,a,m);g&&g.call(b.t.Ti(m,h),h,a,d);h.Gs()};m.attrs||(m.attrs=m.saveAttrs);m.parse=!0;l&&(m.saveAttrs=m.attrs);return b.t.Rw("create",this,m)};b.b.g("Model.prototype.save",{save:b.t.prototype.save});b.t.prototype.g$=
function(a){var b={},c;for(c in this.attributes)this.attributes.hasOwnProperty(c)&&(b[c]=this.attributes[c]);for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};b.t.Qm=function(a,b){return a?f.isFunction(a[b])?a[b]():a[b]:f.isFunction(b)?b():b};b.t.FP=function(a){return a&&a.hasOwnProperty("value")&&a.hasOwnProperty("comparator")};b.t.prototype.Cfa=function(a){for(var d in a)if(a.hasOwnProperty(d)){if(!this.attributes.hasOwnProperty(d))return!1;for(var c=Array.isArray(a[d])?a[d]:[a[d]],e=0;e<c.length;e++)if(b.t.FP(c[e])){var g=
c[e].comparator,f=c[e].value;if(b.Ea.jd(g))throw Error("String comparator invalid for local where/findWhere");if(!g(this,d,f))return!1}else if(a[d]!==this.attributes[d])return!1}return!0};b.t.prototype.matches=function(a){a:{for(var b in a)if(this.get(b)!==a[b]){a=!1;break a}a=!0}return a};b.b.g("Model.prototype.matches",{matches:b.t.prototype.matches});b.t.prototype.G5=function(a){a=a.constructor===Array?a:[a];var b;for(b=0;b<a.length;b++)if(this.Cfa(a[b]))return!0;return!1};b.t.zW=function(a){return null!=
a&&a.success?a.success:null};b.t.Ti=function(a,b){return void 0!==a&&void 0!==a.context?a.context:b};b.t.prototype.iE=function(){return void 0==this.Vf()};b.b.g("Model.prototype.isNew",{iE:b.t.prototype.iE});b.t.prototype.QI=function(){return this.idAttribute||"id"};b.t.prototype.Vf=function(){return this.id};b.t.prototype.JM=function(a){if(a){var d={},c;for(c in a)a.hasOwnProperty(c)&&(b.b.Iv(a[c],this.attributes[c])||(d[c]=a[c]));return b.b.mh(d)?!1:d}return b.b.mh(this.changed)?!1:this.changed};
b.b.g("Model.prototype.changedAttributes",{JM:b.t.prototype.JM});b.t.prototype.EN=function(a){return void 0!==a?b.t.VB(this.changed)&&this.changed.hasOwnProperty(a):b.t.VB(this.changed)};b.b.g("Model.prototype.hasChanged",{EN:b.t.prototype.EN});b.t.prototype.destroy=function(a){a=a||{};var d=a.wait,c,e=a.error,g=this,f,k;k=b.t.Up(a);c=b.t.zW(k);var l=this.Wu();k.success=function(e){k.xhr&&(a.xhr=k.xhr);if(l){var f=b.Ea.jd(e)&&!b.Ea.mh(e)?JSON.parse(e):e;l.H_(f,null,e,!0)}d&&g.vI();b.t.jB(g,e,k);c&&
c.call(b.t.Ti(k,g),g,e,a)};k.error=function(d,c,f){g.Gb(!1,b.Y.D.ERROR,g,d,a);e&&e.apply(g,arguments)};if(!this.iE())return f=b.t.Rw("delete",this,k),d||this.vI(),f;d||this.vI();c&&c.call(b.t.Ti(k,g),g,null,a);return!1};b.b.g("Model.prototype.destroy",{destroy:b.t.prototype.destroy});b.t.prototype.iV=function(a,d,c,e){this.Gb(e,b.Y.D.REQUEST,a,d,c)};b.t.prototype.vI=function(){this.Gb(!1,b.Y.D.DESTROY,this,this.collection,null)};b.t.jB=function(a,d,c){a.Gb(!1,b.Y.D.SYNC,a,d,c)};b.t.prototype.toJSON=
function(){var a={},b;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&(Array.isArray(this.attributes[b])?a[b]=this.attributes[b].slice(0):a[b]=this.attributes[b]);return a};b.b.g("Model.prototype.toJSON",{toJSON:b.t.prototype.toJSON});b.t.prototype.Am=function(a){return this.xO[a]};b.b.g("Model.prototype.previous",{Am:b.t.prototype.Am});b.t.prototype.p4=function(){return this.xO};b.b.g("Model.prototype.previousAttributes",{p4:b.t.prototype.p4});b.t.prototype.sync=function(a,b,c){return window.oj.sync(a,
b,c)};b.t.Rw=function(a,d,c){c=c||{};d.oauth&&(c.oauthHeader=d.oauth.getHeader());!c.dataType&&d.dataType&&(c.dataType=d.dataType);!c.jsonpCallback&&d.jsonpCallback&&(c.jsonpCallback=d.jsonpCallback);if("create"===a||"patch"===a||"update"===a)c.uO=d.parseSave.call(d,"patch"===a?c.attrs:c.saveAttrs);var e=null;d instanceof b.t&&(e=d.Vf());var g={};if(c)for(var f in c)g[f]=c[f];e=b.t.cQ(e,d,c);for(f in e)g[f]=e[f];c.xhr=d.sync(a,d,g);g.xhr&&(c.xhr=g.xhr);return c.xhr};b.t.cQ=function(a,d,c){d=d instanceof
b.j?d.l6(c):{};a&&(d.recordID=a);return d};b.UO=function(a,d,c){function e(a){d.iV(d,a,c,c.silent);return a}c=c||{};var g,f=c.success,k=c.error;g=d.customURL;if("create"===a.valueOf())return a=(a=d.Vja())?a:b.t.Qm(d,"url"),g=new b.Ta(a,g),e(g.hma(c.uO,k,c,d));if("read"===a.valueOf()){if(d instanceof b.t)return a=c.url?c.url:b.t.Qm(d,"url"),g=new b.Ta(a,g),e(g.xN(f,k,d.Vf(),c,b.t.Ti(c,d)));a=d.xP(c);g=new b.Ta(a,g);return e(g.Fna(f,k,c,d))}g=new b.Ta(b.t.Qm(d,"url"),g);var l=null;d instanceof b.t&&
(l=d.Vf());return"update"===a.valueOf()?e(g.r5(f,l,c.uO,k,c,d,!1)):"patch"===a.valueOf()?e(g.r5(f,l,c.uO,k,c,d,!0)):"delete"===a.valueOf()?e(g.gna(l,k,c,d)):null};o_("sync",b.UO,b);b.t.Xla=function(a){if(!a.url)throw Error("The url property or function must be specified");};b.ajax=function(){arguments&&0<arguments.length&&b.t.Xla(arguments[0]);return f.ajax.apply(window.oj,arguments)};o_("ajax",b.ajax,b);b.Ym=function(){this.name="URLError";this.message="No URL defined"};o_("URLError",b.Ym,b);b.Ym.prototype=
Error();b.Ym.constructor=b.Ym;b.Ta=function(a,b){this.Xy=a;this.zj=b;f.support.cors=!0};b.Ta.hs="headers";b.Ta.dy=function(a,d,c){var e;a=f.extend(!0,a,c);for(e in d)d.hasOwnProperty(e)&&"oauthHeader"!==e&&(a.hasOwnProperty(e)||(a[e]=d[e]),e===b.Ta.hs&&(a[e]=f.extend(!0,a[e],d[e])));if(d.oauthHeader)for(e in a[b.Ta.hs]||(a[b.Ta.hs]={}),d.oauthHeader)d.oauthHeader.hasOwnProperty(e)&&(a[b.Ta.hs].hasOwnProperty(e)||(a[b.Ta.hs][e]=d.oauthHeader[e]));return a};b.Ta.prototype.Fna=function(a,d,c,e){c=c||
{};var g="jsonp"===c.dataType,f=this.Jw("read",this.Xy,this.zj,null,e,c);a={crossDomain:c.crossDomain||!g,dataType:this.uB(c),jsonpCallback:c.jsonpCallback,context:null!==e?e:this,success:a,error:d};a=this.oA(a);a=b.Ta.dy(a,c,f);c.xhr=this.ajax(a);return c.xhr};b.Ta.prototype.oA=function(a){a[b.Ta.hs]={"Accept-Language":this.qg()};return a};b.Ta.prototype.xN=function(a,d,c,e,g){e=e||{};var f="jsonp"===e.dataType;c=this.Jw("read",this.Xy,this.zj,c,g,e);a={crossDomain:e.crossDomain||!f,dataType:this.uB(e),
jsonpCallback:e.jsonpCallback,context:null!==g?g:this,success:a,error:d};a=this.oA(a);a=b.Ta.dy(a,e,c);e.xhr=this.ajax(a);return e.xhr};b.Ta.prototype.r5=function(a,d,c,e,g,f,k){g=g||{};var l="jsonp"===g.dataType;d=this.Jw(k?"patch":"update",this.Xy,this.zj,d,f,g);k=b.Ta.Qs(g);a={crossDomain:g.crossDomain||!l,contentType:this.Oca(g),dataType:this.uB(g),jsonpCallback:g.jsonpCallback,data:this.Ya(JSON.stringify(c),g,d),emulateHTTP:k,emulateJSON:b.Ta.Rs(g),success:a,error:e,context:null!==f?f:this};
a=this.oA(a);a=b.Ta.dy(a,g,d);a=b.Ta.YS(k,a);g.xhr=this.ajax(a);return g.xhr};b.Ta.YS=function(a,b){if(a){var c=b.beforeSend;b.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",b.wi);if(c)return c.apply(this,arguments)}}return b};b.Ta.prototype.Ya=function(a,d,c){return b.Ta.Rs(d)?(d={_method:c.wi?c.wi:c.type},a&&(d.model=a),d):a};b.Ta.prototype.eda=function(a,d){if(d.type)return{method:d.type};var c=null;"create"===a&&(c="POST");"delete"===a&&(c="DELETE");"patch"===a&&(c="PATCH");
"update"===a&&(c="PUT");if(b.Ta.Qs(d)){var e={method:"POST"};e.wi=c;return e}null===c&&(c="GET");return{method:c}};b.Ta.Qs=function(a){return a.emulateHTTP||b.emulateHTTP};b.Ta.Rs=function(a){return a.emulateJSON||b.emulateJSON};b.Ta.prototype.Jw=function(a,d,c,e,g,h){var k=this.eda(a,h);if(f.isFunction(c)){a=c.call(this,a,g,b.t.cQ(e,g,h));if(b.Ea.jd(a))return d={url:a,type:k.method},k.wi&&(d.wi=k.wi),d;if(a)return a.url=a.hasOwnProperty("url")?a.url:d,a.hasOwnProperty("type")||(a.type=k.method),
!a.hasOwnProperty("data")&&k.wi&&(a.wi=k.wi),a}d={url:b.t.Qm(null,d),type:k.method};k.wi&&(d.wi=k.wi);return d};b.Ta.prototype.gna=function(a,d,c,e){c=c||{};var g="jsonp"===c.dataType;a=this.Jw("delete",this.Xy,this.zj,a,e,c);var f=b.Ta.Qs(c);d={crossDomain:c.crossDomain||!g,success:c.success,error:d,context:null!==e?e:this,emulateHTTP:f,emulateJSON:b.Ta.Rs(c)};(e=this.Ya(null,c,a))&&(d.data=e);d=b.Ta.dy(d,c,a);d=b.Ta.YS(f,d);c.xhr=this.ajax(d);return c.xhr};b.Ta.prototype.hma=function(a,d,c,e){c=
c||{};var g=JSON.stringify(a),f="jsonp"===c.dataType;a=this.Jw("create",this.Xy,this.zj,null,e,c);var k=b.Ta.Qs(c);d={crossDomain:c.crossDomain||!f,contentType:c.contentType||"application/json",dataType:this.uB(c),jsonpCallback:c.jsonpCallback,data:this.Ya(g,c,a),success:c.success,error:d,emulateHTTP:k,emulateJSON:b.Ta.Rs(c),context:null!==e?e:this};d=this.oA(d);d=b.Ta.dy(d,c,a);c.xhr=this.ajax(d);return c.xhr};b.Ta.prototype.uB=function(a){return b.Ta.Rs(a)&&!b.Ta.Qs(a)?"application/x-www-form-urlencoded":
a.dataType||"json"};b.Ta.prototype.Oca=function(a){return b.Ta.Rs(a)&&!b.Ta.Qs(a)?"application/x-www-form-urlencoded":a.contentType||"application/json"};b.Ta.prototype.qg=function(){return b.ba.qg()};b.Ta.prototype.ajax=function(a){if(null===a.url||void 0===a.url)throw new b.Ym;return window.oj.ajax(a)};b.Bb=function(a,d){d=d||{};b.Bb._init(this,d,a||"Authorization")};o_("OAuth",b.Bb,b);b.b.ga(b.Bb,b.b,"oj.OAuth");b.Bb.prototype.Init=function(){b.Bb.q.Init.call(this)};b.Bb.prototype.w2=function(){var a=
{};this.so.access_token||this.LM();a[this.Fk.k1]="Bearer "+this.so.access_token;return a};b.b.g("OAuth.prototype.getHeader",{w2:b.Bb.prototype.w2});b.Bb.prototype.u3=function(){return this.so.mra?!0:!1};b.b.g("OAuth.prototype.isInitialized",{u3:b.Bb.prototype.u3});b.Bb.prototype.LM=function(){var a={},d=this;a[d.Fk.k1]="Basic "+b.Bb.m$(d.Fk.client_id+":"+d.Fk.client_secret);f.ajax({type:"POST",async:!1,url:this.Fk.bearer_url,data:"grant_type\x3dclient_credentials",headers:a,success:function(a){b.Bb.Qw(d.so,
a)},error:function(a){throw Error(a.responseText);}})};b.b.g("OAuth.prototype.clientCredentialGrant",{LM:b.Bb.prototype.LM});b.Bb.prototype.D4=function(a){b.Bb.Qw(this.so,a)};b.b.g("OAuth.prototype.setAccessTokenResponse",{D4:b.Bb.prototype.D4});b.Bb.prototype.d2=function(){return this.so};b.b.g("OAuth.prototype.getAccessTokenResponse",{d2:b.Bb.prototype.d2});b.Bb.prototype.r1=function(){b.Bb.sT(this.so)};b.b.g("OAuth.prototype.cleanAccessTokenResponse",{r1:b.Bb.prototype.r1});b.Bb.prototype.C4=function(a){b.Bb.Qw(this.Fk,
a)};b.b.g("OAuth.prototype.setAccessTokenRequest",{C4:b.Bb.prototype.C4});b.Bb.prototype.c2=function(){return this.Fk};b.b.g("OAuth.prototype.getAccessTokenRequest",{c2:b.Bb.prototype.c2});b.Bb.prototype.q1=function(){b.Bb.sT(this.Fk)};b.b.g("OAuth.prototype.cleanAccessTokenRequest",{q1:b.Bb.prototype.q1});b.Bb._init=function(a,d,c){a.Init();a.Fk={};a.so={};d.access_token?b.Bb.Qw(a.so,d):d.client_id&&d.client_secret&&d.bearer_url&&b.Bb.Qw(a.Fk,d);a.Fk.k1=c};b.Bb.Qw=function(a,b){var c;b=b||{};for(c in b)a[c]=
b[c]};b.Bb.sT=function(a){for(var b in a)a.hasOwnProperty(b)&&"auth_header"!==b&&(a[b]=null,delete a[b])};b.Bb.m$=function(a){var b,c,e,g,f=0,k=0,l=[];do b=a.charCodeAt(f++),c=a.charCodeAt(f++),e=a.charCodeAt(f++),g=b<<16|c<<8|e,b=g>>18&63,c=g>>12&63,e=g>>6&63,g&=63,l[k++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(g);while(f<a.length);l=l.join("");b=a.length%3;return(b?l.slice(0,b-3):l)+"\x3d\x3d\x3d".slice(b||3)};b.j=function(a,d){b.j.Xw||b.j._init(this,a,d,null)};o_("Collection",b.j,b);b.b.ga(b.j,b.b,"oj.Collection");b.j.prototype.Po=null;b.b.g("Collection.prototype.model",{Po:b.j.prototype.Po});b.j.prototype.U3=function(a){var b=this.model;return b&&a?a[b.idAttribute||b.prototype.idAttribute||"id"]:null};b.b.g("Collection.prototype.modelId",
{U3:b.j.prototype.U3});b.j.prototype.length=void 0;b.b.g("Collection.prototype.length",{length:b.j.prototype.length});b.j.prototype.W3=void 0;b.b.g("Collection.prototype.models",{W3:b.j.prototype.W3});b.j.prototype.Vb=[];b.j.prototype.url=null;b.b.g("Collection.prototype.url",{url:b.j.prototype.url});b.j.prototype.xo=[];b.b.g("Collection.prototype.changes",{xo:b.j.prototype.xo});b.j.prototype.zj=null;b.b.g("Collection.prototype.customURL",{zj:b.j.prototype.zj});b.j.prototype.M1=null;b.b.g("Collection.prototype.customPagingOptions",
{M1:b.j.prototype.M1});b.j.prototype.C3=void 0;b.b.g("Collection.prototype.lastFetchSize",{C3:b.j.prototype.C3});b.j.prototype.e3=!1;b.b.g("Collection.prototype.hasMore",{e3:b.j.prototype.e3});b.j.prototype.e5=void 0;b.b.g("Collection.prototype.totalResults",{e5:b.j.prototype.e5});b.j.prototype.B3=void 0;b.b.g("Collection.prototype.lastFetchCount",{B3:b.j.prototype.B3});b.j.prototype.V3=-1;b.b.g("Collection.prototype.modelLimit",{V3:b.j.prototype.V3});b.j.prototype.offset=void 0;b.b.g("Collection.prototype.offset",
{offset:b.j.prototype.offset});b.j.prototype.U1=-1;b.b.g("Collection.prototype.fetchSize",{U1:b.j.prototype.U1});b.j.prototype.OO=1;b.b.g("Collection.prototype.sortDirection",{OO:b.j.prototype.OO});b.j.prototype.OM=null;b.b.g("Collection.prototype.comparator",{OM:b.j.prototype.OM});b.j.prototype.Init=function(){b.j.q.Init.call(this)};b.j.extend=function(a,d){b.j.Xw=!0;var c=new b.j;b.j.Xw=!1;f.extend(c,this.prototype);var e;e=a&&a.constructor&&a.hasOwnProperty("constructor")?a.constructor:function(d,
c){b.j._init(this,d,c,a)};if(d)for(var g in d)d.hasOwnProperty(g)&&(e[g]=d[g]);if(a)for(g in a)a.hasOwnProperty(g)&&(c[g]=a[g]);f.extend(e,this);e.prototype=c;e.extend=b.j.extend;return e.prototype.constructor=e};o_("Collection.extend",b.j.extend,b);b.j._init=function(a,d,c,e){var g,f;a.Init();b.Y.pF(a);if(e)for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);c=c||{};f=["comparator","customPagingOptions","customURL",b.j.Hd,"model","modelLimit","sortDirection","url"];for(g=0;g<f.length;g++)c.hasOwnProperty(f[g])&&
void 0!==c[f[g]]&&(a[f[g]]=c[f[g]]);void 0===a.mk(null)&&a.DE(-1);void 0===a.modelLimit&&a.IO(-1);a.hasMore=!1;a.Hi=0;a.Hq([],!0);c.parse&&(d=a.parse(d));if(null!=d)for(c.c4=!0,f=d instanceof Array?d:[d],g=0;g<f.length;g+=1)a.add(f[g],c);a.Bk();e&&e.initialize&&e.initialize.call(a,d,c)};b.j.prototype.on=function(){};b.j.prototype.jl=function(){};b.j.prototype.Gb=function(){};b.j.prototype.iV=function(a,d,c,e){this.Gb(e,b.Y.D.REQUEST,a,d,c)};b.j.prototype.Gja=function(){this.changes=[]};b.j.prototype.tL=
function(a,b){for(var c=a;c<a+b;c++)-1===this.changes.indexOf(c)&&(this.changes.push(c),this.changes.sort(function(a,b){return a-b}))};b.j.prototype.Hq=function(a,b){this.models=a;if(b)this.Vb=[],this.Gja();else for(var c=0;c<a.length;c++)a[c]&&this.Vb.push(c)};b.j.prototype.Ac=function(){return this.models};b.j.prototype.Tc=function(){return this.Ac().length};b.j.prototype.Yha=function(a){return a<this.Tc()||this.Wa()&&(!this.qq()||0===this.Tc())?!1:!0};b.j.prototype.qq=function(){return b.j.zl(this.totalResults)};
b.j.zl=function(a){return null!=a};b.j.prototype.Cia=function(a){this.Ac().push(a);this.Vb.push(this.Tc()-1);this.tL(this.Tc()-1,1)};b.j.prototype.Dia=function(a){this.tK(a);this.Cia(a);this.Hi++;a.iv(this.Tc()-1)};b.j.prototype.nZ=function(a){if(a)for(var b=0;b<a.length;b++)a[b]&&this.Hi--};b.j.prototype.j0=function(a,b,c){for(var e=a;e<a+b;e++)this.RZ(this.Mb(e));void 0===c?(this.nZ(this.Ac().splice(a,b)),this.i0(a,a+b-1)):(this.nZ(this.Ac().splice(a,b,c)),this.i0(a,a+b-1),this.pga(a),this.tK(c));
this.tL(a,b);0>this.Hi&&(this.Hi=0);this.mZ(a)};b.j.prototype.Mb=function(a){return this.Ac()[a]};b.j.prototype.mZ=function(a){for(var b,c=0;c<this.Vb.length;c++)b=this.Vb[c],b>=a&&this.Mb(b)&&this.Mb(b).iv(b)};b.j.prototype.RZ=function(a){if(a){var b=a.yO;a=a.Soa;b?b.vF(a):this.head=a;a?a.qz(b):this.tail=b}};b.j.prototype.tK=function(a){a.vF(this.head);this.head?this.head.qz(a):this.tail=a;a.qz(null);this.head=a};b.j.prototype.yka=function(a){-1===this.Vb.indexOf(a)&&this.Vb.push(a)};b.j.prototype.pga=
function(a){for(var b=0;b<this.Vb.length;b++)this.Vb[b]>=a&&this.Vb[b]++;this.Vb.push(a)};b.j.prototype.i0=function(a,b){void 0===b&&(b=a);this.AT(a,b);for(var c=b-a+1,e=0;e<this.Vb.length;e++)this.Vb[e]>b&&(this.Vb[e]-=c)};b.j.prototype.AT=function(a,b){void 0===b&&(b=a);for(var c=a;c<=b;c++){var e=this.Vb.indexOf(a);-1<e&&this.Vb.splice(e,1)}};b.j.prototype.UC=function(a,b){var c=this.Mb(a);this.RZ(c);c||this.Hi++;this.tL(a,1);if(this.Ac()[a]=b)this.yka(a),b.iv(a),this.tK(b)};b.j.prototype.$$=function(a){var b=
this.tail,c,e,g=0;for(this.tail=null;b&&g<a;)c=b.U5(),(e=this.Mb(c))&&e.EN()?(this.tail||(this.tail=b),b=b.yO):(this.Hi--,-1<c&&(this.UC(c,void 0),this.AT(c,c)),b.vF(null),b=b.qz(null),g++);this.tail||(this.tail=b);0>this.Hi&&(this.Hi=0);0===this.Hi&&(this.tail=this.head=null)};b.j.prototype.Ex=function(){this.Hi=0;this.tail=this.head=null};b.j.prototype.yq=function(a){if(this.Wa()){var b=this.$V();-1<b&&this.Hi+a>b&&this.$$(this.Hi+a-b)}};b.j.prototype.clone=function(){return this.ET(!0)};b.b.g("Collection.prototype.clone",
{clone:b.j.prototype.clone});b.j.prototype.ET=function(a){var b=new this.constructor,c;this.Wa()&&(b=this.saa(b),b.lL());b=this.taa(b);if(a){var e=[];for(a=0;a<this.Vb.length;a++)e.push(this.Vb[a]);e.sort(function(a,b){return a-b});var g;for(a=0;a<e.length;a++)g=e[a],(c=this.ul(g,null,!0,!1))&&b.sl(c.clone(),{at:g},!0,!1)}return b};b.j.prototype.taa=function(a){var b=["comparator","model","modelId"],c,e;for(e=0;e<b.length;e++)c=b[e],a[c]=this[c];return a};b.j.prototype.saa=function(a){var d=["totalResults",
"hasMore",b.j.Hd],c,e;for(e=0;e<d.length;e++)c=d[e],a[c]=this[c];return a};b.j.prototype.Yd=function(){return this.length};b.j.prototype.Bk=function(){var a=this.Tc();this.length=a;this.Wa()||(this.totalResults=a)};b.j.JH=function(a,b,c){return a.model?f.isFunction(a.model)?new a.model(b,c):new a.model.constructor(b,c):null};b.j.prototype.jx=function(a,d,c){var e=null;d=d||{};d.qoa=c;a instanceof b.t?e=a:this.model?e=b.j.JH(this,a,d):(d.collection=this,e=new b.t(a,d));return d.validate&&e.validate&&
(a=e.validate(e.attributes))?(d.validationError=a,this.Gb(!1,b.Y.D.INVALID,e,a,d),null):e};b.j.prototype.add=function(a,b){this.yq(1);return this.Kw(this.sl(a,b,!1,(b||{}).deferred))};b.b.g("Collection.prototype.add",{add:b.j.prototype.add});b.j.prototype.sl=function(a,d,c,e){function g(a,e,g,f,h){var k,r=null;!p&&t&&g?(x=g.h6(e,a.comparator,n),r=g):(p||(k=a.WV(f))&&c&&m!==k.index&&b.r.warn("Duplicate ID fetched or added without merging, the id \x3d "+k.Vf()),void 0===k?(void 0===m?(a.Dia(f),s=a.Tc()-
1,a.Mb(s).pz()):(s=m,a.Wa()&&c?a.UC(s,f):a.j0(s,0,f),a.Mb(s).pz(),m+=1),void 0===f.Wu()&&f.hv(a),a.Bk(),a.cha(f),u=!0,r=f):r=k);c&&(d=d||{},d.fillIn=!0);x&&void 0===k&&!w&&void 0===m&&1<a.Yd()&&(-1<s&&(q=a.Mb(s).cid),e={},b.lc.Xe(e,d),e.add=!0,a.sort(e),-1<s&&(s=a.Wa()?-1:a.indexOf(a.lN(q),h)));u&&(d.at&&(d.index=s),f?(f.Gb(n,b.Y.D.ADD,f,a,d),v.push(f)):(g.Gb(n,b.Y.D.ADD,g,a,d),v.push(g)));return r}function f(a,e,h){u=!1;var q=a.jx(e,d,!1),k=null,m=null;if(null!=q){s=-1;q.Uj();k=e instanceof b.t?
e:q;if(h)return p?new Promise(function(b){var d=g(a,k,void 0,q,h);y.push(d);b(d)}):a.Eh(k,{silent:!0},h,!0).then(function(b){m=b.m;b=g(a,k,m,q,h);y.push(b)});!p&&t&&(m=c?a.WV(k):a.get(k));(e=g(a,k,m,q,h))&&y.push(e)}else y.push(!1)}function k(a,b){return a.parse&&d.parse&&!d.c4?a.parse(b):b}d=d||{};var l=[],m=d.at,n=d.silent,p=d.force,r,s,q,t=d.merge||!1,w=d.sort,x=!0,u=!1,v=[],y=[];void 0!==m&&0>m&&(m+=this.Yd()+1);a instanceof Array?l=a:l.push(a);if(!c&&(this.Wa()||e)){var B=this;return new Promise(function(a,
c){function e(a){return new Promise(function(b,d){f(B,l[a],!0).then(function(){b(a+1)},d)})}var g=Promise.resolve(0);l=k(B,l);for(r=0;r<l.length;r++)g=g.then(e);g.then(function(){0<v.length&&B.Gb(d.silent,b.Y.D.ALLADDED,B,v,d);a(b.j.nL(y))},c)})}l=k(this,l);for(r=0;r<l.length;r++)f(this,l[r],!1);0<v.length&&this.Gb(d.silent,b.Y.D.ALLADDED,this,v,d);return b.j.nL(y)};b.j.nL=function(a){return 1===a.length?a[0]:a};b.j.prototype.TB=function(){return b.j.zl(this.comparator)};b.j.prototype.sort=function(a){a=
a||{};var d=a.silent,c=this.comparator,e;if(!this.TB())return null;if(this.Wa()){var g=this.totalResults;this.qq()?this.Hq(Array(g),!0):(this.Hq([],!0),this.Ex(),this.Bk());g=a.add?{add:!0}:null;this.Gb(d,b.Y.D.SORT,this,g,null);d=a.startIndex;return void 0!==d&&null!==d?this.Zy(d,this.mk(a)):null}e=this;this.Ac().sort(function(a,d){return b.j.hQ(a,d,c,e,e)});this.mZ(0);g=a.add?{add:!0}:null;this.Gb(d,b.Y.D.SORT,this,g,null);return null};b.b.g("Collection.prototype.sort",{sort:b.j.prototype.sort});
b.j.Hn=function(a,d){return a instanceof b.t?a.get(d):b.t.Qm(a,d)};b.j.hQ=function(a,d,c,e,g){var h,k,l;if(f.isFunction(c)){if(1===c.length){h=c.call(g,a);k=c.call(g,d);h=b.Ea.jd(h)?h.split(","):[h];var m=b.Ea.jd(k)?k.split(","):[k];for(l=0;l<h.length;l++)if(k=b.j.wl(h[l],m[l],e.sortDirection),0!==k)return k}return c.call(g,a,d)}if(b.Ea.jd(c))for(c=c.split(","),l=0;l<c.length;l++)if(h=b.j.Hn(a,c[l]),k=b.j.Hn(d,c[l]),k=b.j.wl(h,k,e.sortDirection),0!==k)return k;return 0};b.j.prototype.S4=function(a,
d){var c=d?d:this.comparator,e;if(!c)return-1;this.Cf("sortedIndex");e=this;return b.j.nca(this.Ac(),a,function(a,d){var k,l;if(f.isFunction(c)){if(1===c.length){k=c.call(e,a);l=c.call(e,d);k=b.Ea.jd(k)?k.split(","):[k];l=b.Ea.jd(l)?l.split(","):[l];var m,n;for(n=0;n<k.length;n++)if(m=b.j.wl(k[n],l[n],e.sortDirection),0!==m)return m}return c.call(e,a,d)}return b.Ea.jd(c)?(k=a.get(c),l=d.get(c),b.j.wl(k,l,e.sortDirection)):0})};b.b.g("Collection.prototype.sortedIndex",{S4:b.j.prototype.S4});b.j.nca=
function(a,b,c){function e(g,f){var k,l;if(g>f)return-1;k=b.gp();l=b.Vf();if(a[g].kp(l,k))return g;if(a[f].kp(l,k))return f;k=Math.floor((f+g)/2);return-1===c(a[k],b)?e(g+1,k):1===c(a[k],b)?e(k,f-1):k}return e(0,a.length-1)};b.j.wl=function(a,b,c){if(-1===c){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};b.j.prototype.unshift=function(a,d){var c={};b.lc.Xe(c,d||{});c.at||(c.at=0);this.yq(1);return this.Kw(this.sl(a,c,!1,c.deferred))};b.b.g("Collection.prototype.unshift",
{unshift:b.j.prototype.unshift});b.j.prototype.Kw=function(a){return f.isFunction(a.then)?this.Wd(function(){return a}):a};b.j.prototype.shift=function(a){a=a||{};var d=this.vf(a),c;if(this.Wa()||d){var e=this;return this.at(0,a).then(function(d){c=e.Gq(d,0,a);e.Gb(a.silent,b.Y.D.ALLREMOVED,e,[c],a);return c})}c=this.Gq(this.at(0),0,a);this.Gb(a.silent,b.Y.D.ALLREMOVED,this,[c],a);return c};b.b.g("Collection.prototype.shift",{shift:b.j.prototype.shift});b.j.prototype.fE=function(a){void 0===a&&(a=
1);this.Cf("initial");var b=[],c;for(c=0;c<this.Yd()-a;c+=1)b.push(this.at(c));return b};b.b.g("Collection.prototype.initial",{fE:b.j.prototype.fE});b.j.prototype.vf=function(a){return(a||{}).deferred};b.j.prototype.last=function(a,b){var c=this.vf(b);void 0===a&&(a=1);if(1===a){var e=this.Tc();0===e&&(e=a);return 0<e?this.at(e-1,c):null}var g=[],e=this.Yd();if(c||this.Wa()){var f=e-a;0>f&&(f=0);0===e&&(e=a);var k=this;return this.Wd(function(){return k.Nr(f,e)})}for(c=e-a;c<e;c+=1)g.push(this.at(c));
return g};b.b.g("Collection.prototype.last",{last:b.j.prototype.last});b.j.prototype.Nr=function(a,b){var c=[],e,g=this;return new Promise(function(f,k){function l(a){return new Promise(function(b,d){g.UH(a,null).then(function(d){c.push(d);b(a+1)},d)})}var m=Promise.resolve(a);for(e=a;e<b;e++)m=m.then(l);m.then(function(){f(c)},k)})};b.j.prototype.FV=function(a){return void 0===a||null===a?this[b.j.Hd]:a};b.j.prototype.I$=function(){var a=this.lastFetchCount;if(void 0===a||null===a)a=this[b.j.Hd];
return void 0===this.offset||null===this.offset?a:this.offset+a};b.j.prototype.next=function(a,d){d=d||{};d[b.j.Hd]=this.FV(a);var c=this.I$(),e=this.Yd();if(0===e&&0<d[b.j.Hd])c=0;else if(c>=e)return d.success&&d.success.call(b.t.Ti(d,this),this,null,d),null;d.startIndex=c;return this.fetch(d)};b.b.g("Collection.prototype.next",{next:b.j.prototype.next});b.j.prototype.J$=function(a){return void 0===this.offset||null===this.offset?0:this.offset-a};b.j.prototype.Am=function(a,d){d=d||{};if(0===this.offset)return d.success&&
this.lastFetchCount&&d.success.call(b.t.Ti(d,this),this,null,d),null;d[b.j.Hd]=this.FV(a);var c=this.J$(d[b.j.Hd]);0>c&&(d[b.j.Hd]=this.offset,c=0);d.startIndex=c;return this.fetch(d)};b.b.g("Collection.prototype.previous",{Am:b.j.prototype.Am});b.j.prototype.IO=function(a){this.modelLimit=a;this.yq(0)};b.b.g("Collection.prototype.setModelLimit",{IO:b.j.prototype.IO});b.j.prototype.$V=function(){return this.modelLimit};b.j.prototype.DE=function(a){this[b.j.Hd]=a};b.b.g("Collection.prototype.setFetchSize",
{DE:b.j.prototype.DE});b.j.prototype.x4=function(a,b){var c=this.vf(b);void 0===a&&(a=1);var e=[];if(this.Wa()||c){var g=this;return this.Wd(function(){return g.Nr(a,g.Yd())})}for(c=a;c<this.Yd();c+=1)e.push(this.at(c));return e};b.b.g("Collection.prototype.rest",{x4:b.j.prototype.x4});b.j.prototype.remove=function(a,d){d=d||{};var c=[],e;a instanceof Array?c=a:c.push(a);var g=[];for(e=c.length-1;0<=e;e-=1)g.unshift(this.Gq(c[e],-1,d));this.Gb(d.silent,b.Y.D.ALLREMOVED,this,c,d);return b.j.nL(g)};
b.b.g("Collection.prototype.remove",{remove:b.j.prototype.remove});b.j.prototype.Gq=function(a,d,c){c=c||{};a=-1==d?this.Eh(a):b.j.Hl(d,a);var e=c.silent;d=a.index;if(-1<d){var g=a.m;void 0!==g&&g.Wu()===this&&g.hv(null);this.j0(d,1);this.Bk();var f={};b.lc.Xe(f,c);f.index=d;void 0!==g&&g.Gb(e,b.Y.D.REMOVE,g,this,f);this.M0(g)}return a.m};b.j.prototype.M0=function(a){void 0!==a&&a.off(null,null,this)};b.j.prototype.cha=function(a){a.jl(b.Y.D.ALL,this.xha,this,!1,!0)};b.j.prototype.xha=function(a,
d,c,e){a===b.Y.D.DESTROY&&this.remove(d);void 0!==c&&c instanceof b.j&&c!==this||(Array.prototype.slice.call(arguments),this.Gb(e&&e.silent,a,d,c,e))};b.j.prototype.refresh=function(a){a=a||{};var d=this;return this.Wd(function(){return new Promise(function(c,e){if(!d.Wa()){var g=void 0!==a.silent&&a.silent;try{d.reset(null,{silent:!0});var f={},k;for(k in a)a.hasOwnProperty(k)&&(f[k]=a[k]);f.success=function(a,e,f){d.Gb(g,b.Y.D.REFRESH,d,f,null);c({collection:a,response:e,options:f})};f.error=function(c,
g,f){e(b.j.fw(c,g,f,d,a))};d.fetch(f);return}catch(l){if(l instanceof b.Ym){d.Gb(g,b.Y.D.REFRESH,d,a,null);c({collection:d,options:a});return}throw l;}}f=a.startIndex;d.Hq([],!0);d.Ex();d.totalResults=void 0;d.Bk();g=void 0!==a.silent&&a.silent;d.Gb(g,b.Y.D.REFRESH,d,a,null);if(void 0===f||null===f)f=0;void 0!==f&&null!==f?d.L_(f,d.mk(a)).then(function(a){c(a)},function(a){e(a)}):c(void 0)})})};b.b.g("Collection.prototype.refresh",{refresh:b.j.prototype.refresh});b.j.prototype.reset=function(a,d){var c=
{};b.lc.Xe(c,d||{});c.previousModels=this.Ac();for(var e,g=0;g<this.Vb.length;g++)if(e=this.Vb[g],e=this.Mb(e))this.M0(e),e.hv(null);this.Hq([],!0);this.Ex();g=void 0!==c.silent&&c.silent;if(!a)return this.totalResults=void 0,this.Bk(),this.Gb(g,b.Y.D.RESET,this,c,null),null;e=null;c.parse&&(a=this.parse(a));this.yq(a instanceof Array?a.length:1);c.c4=!0;e=this.sl(a,c,!0,!1);this.Bk();this.Gb(g,b.Y.D.RESET,this,c,null);return this.Kw(e)};b.b.g("Collection.prototype.reset",{reset:b.j.prototype.reset});
b.j.prototype.at=function(a,b){return this.ul(a,b,!1,this.vf(b))};b.b.g("Collection.prototype.at",{at:b.j.prototype.at});b.j.prototype.ul=function(a,b,c,e){0>a&&(a+=this.Yd());if(0>a||this.Yha(a))return c||!this.Wa()&&!e?null:this.Wd(function(){return Promise.resolve(null)});var g=this;return c||!this.Wa()&&!e?this.Mb(a):this.Wd(function(){return g.UH(a,b)})};b.j.prototype.v5=function(){return this.$n?this.$n:Promise.resolve()};b.b.g("Collection.prototype.whenReady",{v5:b.j.prototype.v5});b.j.prototype.Wd=
function(a){var d=this;void 0===this.$n&&(this.rx=0,this.$n=Promise.resolve());this.rx++;return this.$n=this.$n.then(a.bind(d)).then(function(a){d.rx--;0===d.rx&&(d.$n=void 0,d.Gb(!1,b.Y.D.READY,d,null,null));return a},function(a){d.rx--;0===d.rx&&(d.$n=void 0);return Promise.reject(a)})};b.j.prototype.UH=function(a,d){var c=this,e=c.Mb(a);return void 0===e?new Promise(function(e,f){var k={};b.lc.Xe(k,d||{});k.context=c;k.startIndex=a;k.error=function(a,e,g){f(b.j.fw(a,e,g,c,d))};k.success=function(){e(c.Mb(a))};
c.Ae(k,-1,!1)}):new Promise(function(a){a(e)})};b.j.prototype.lN=function(a){for(var b=this.Ac(),c,e=null,g=0;g<this.Vb.length;g++)if(c=this.Vb[g],b[c]&&a===b[c].cid){e=b[c];break}if(e)return e;if(this.Wa())throw Error("Not found locally and not supported by server for virtual collections");return null};b.b.g("Collection.prototype.getByCid",{lN:b.j.prototype.lN});b.j.prototype.get=function(a,b){var c=this.Eh(a,b,this.vf(b));if(c){if(f.isFunction(c.then))return this.Wd(function(){return new Promise(function(a,
b){c.then(function(b){a(b.m)},function(a){b(a)})})});if(this.Wa())return this.Wd(function(){return new Promise(function(a){a(c.m)})});if(c.hasOwnProperty("m"))return c.m}return null};b.b.g("Collection.prototype.get",{get:b.j.prototype.get});b.j.prototype.WV=function(a){return(a=this.XV(a))?a.m:null};b.j.prototype.XV=function(a){var d=a;a instanceof b.t?(d=a.gp(),a=a.Vf()):b.j.zl(a)&&void 0!==a.id&&(a=a.id);for(var c=null,e=this.Vb.length,g,f=this.Ac(),k,l=0;l<e;l++)if(k=this.Vb[l],g=f[k],void 0!==
g&&g.kp(a,d)){c=b.j.Hl(k,g);break}return c?c:b.j.Hl(-1,void 0)};b.j.prototype.Eh=function(a,d,c,e){var g=a;void 0===e&&(e=!1);a instanceof b.t?(g=a.gp(),a=a.Vf()):b.j.zl(a)&&void 0!==a.id&&(a=a.id);for(var f=null,k=this.Ac(),l,m=0;m<this.Vb.length;m++)if(l=this.Vb[m],k[l]&&k[l].kp(a,g)){f=b.j.Hl(l,k[l]);break}if(f)return c?new Promise(function(a){a(f)}):f;if(this.Wa()){if(void 0===a&&void 0!==g)return new Promise(function(a){a(b.j.Hl(-1,void 0))});var n=this;return new Promise(function(c,f){var h=
{};b.lc.Xe(h,d||{});h.context=n;h.startID=a;h.error=function(a,c,e){f(b.j.fw(a,c,e,n,d))};h.success=function(d,e){if(null!=e){var f=n.dJ(),h=n.Mb(f);void 0!==h&&h.kp(a,g)?c(b.j.Hl(f,h)):c(b.j.Hl(-1,void 0))}else c(b.j.Hl(-1,void 0))};n.Ae(h,-1,e)})}var p=b.j.Hl(-1,void 0);return c?new Promise(function(a){a(p)}):p};b.j.Hl=function(a,b){return{index:a,m:b}};b.j.prototype.parse=function(a){var b;if(a instanceof Array||!a)return a;for(b in a)if(a.hasOwnProperty(b)&&a[b]instanceof Array)return a[b];return a};
b.j.prototype.N$=function(a,b,c){return this.qq()&&0<this.totalResults&&c.start+c.count>=this.totalResults?!0:c.start===a&&c.count===b};b.j.prototype.Zy=function(a,b){var c=this;return this.Wd(function(){return c.L_(a,b)})};b.b.g("Collection.prototype.setRangeLocal",{Zy:b.j.prototype.Zy});b.j.prototype.L_=function(a,b){this.Wa()&&this.lL();var c=this.CB(a,b),e=this;if(this.N$(a,b,c))return new Promise(function(a){a(c)});var g=this.$V();-1<g&&g<b&&(this.modelLimit=b);return new Promise(function(c,
g){e.K_(a,b,-1,{start:a,count:b},c,g,!0)})};b.j.prototype.K_=function(a,d,c,e,g,f,k){var l=this,m=a+d;this[b.j.Hd]&&this[b.j.Hd]>d&&(m=this[b.j.Hd]+a);var n=null;this.Wa()?(n=this.KV(a,m),n>a&&(a=n,m=a+d,this[b.j.Hd]&&this[b.j.Hd]>d&&(m=this[b.j.Hd]+a)),n={context:this,startIndex:a,fetchSize:m-a}):n={context:this};n.error=function(a,d,c){f(b.j.fw(a,d,c,l,null))};n.success=function(){var b=l.CB(e.start,e.count);if(k&&l.qq()&&b.count<e.count){var c=b.start+b.count,q=a+d;q<l.totalResults?l.K_(q,d,c,
e,g,f,k):g(b)}else g(b)};try{this.Ae(n,c,-1<c)}catch(p){p instanceof b.Ym&&(c=l.CB(a,d),g(c))}};b.j.fw=function(a,d,c,e,g){var f=!1;g&&g.silent&&(f=g.silent);b.t.Vx(e,f,g,d,c,a);g=Error(d);g.xhr=a;g.error=c;g.collection=e;g.status=d;return g};b.j.prototype.vda=function(a,b){var c=this.Tc();return 0===c?a+b:a+b>c?c:a+b};b.j.prototype.x3=function(a,b){var c=this.CB(a,b);return 0===this.Tc()?0===b:a===c.start&&(b===c.count||a+b>this.Tc())};b.b.g("Collection.prototype.isRangeLocal",{x3:b.j.prototype.x3});
b.j.prototype.Bw=function(a,b){for(var c=[],e=this.Ac(),g=a+b,f=a;f<g;f++)c.push(e[f]);return c};b.j.prototype.CB=function(a,b){if(!this.Wa()){if(0<this.Tc()){if(a+b>this.Tc()){var c=this.Tc()-a;return{start:a,count:c,models:this.Bw(a,c)}}return{start:a,count:b,models:this.Bw(a,b)}}return{start:a,count:0,models:[]}}c=this.vda(a,b);if(!this.qq()&&c<a+b)return{start:a,count:c-a,models:this.Bw(a,c-a)};if(0===c)return{start:a,count:0,models:[]};var e=this.KV(a,c);if(-1<e)return{start:a,count:e-a,models:this.Bw(a,
e-a)};a>c?b=0:a+b>c&&(b=c-a);return{start:a,count:b,models:this.Bw(a,b)}};b.j.prototype.KV=function(a,b){for(var c=a;c<b;c++)if(void 0===this.Mb(c))return c;return-1};b.j.prototype.fetch=function(a){var b=this.Ae(a,-1,!1);this.Wd(function(){return Promise.resolve(b)});return b};b.b.g("Collection.prototype.fetch",{fetch:b.j.prototype.fetch});b.j.prototype.Ae=function(a,d,c){function e(a,b,d){a.Wa()?d||a.lL():b.add||b.bP||a.reset(null,{silent:!0})}var g=a||{},f=g.success,k,l=g.error;g.set&&(g.bP=g.set?
!0:!1);void 0===g.parse&&(g.parse=!0);k=this;g.error=function(d,c,e){b.t.Vx(k,!1,a,c,e,d);l&&l.call(b.t.Ti(a,k),d,c,e)};g.success=function(m){var n;try{n=k.parse(m,a)}catch(p){b.j.MC(k,p,g.error,a);return}k.H_(m,a,n,c);var r=null;if(g.add||k.model){e(k,g,c);try{q=!1,-1===d&&(q=!0,d=k.dJ()),r=k.lca(n,d,q,g)}catch(l){b.j.MC(k,l,g.error,a);return}}else if(!c)if(k.Wa()){e(k,g,c);var q=!1;-1===d&&(q=!0,d=k.dJ());r=k.Eia(n,d,q)}else g.bP?k.wL(n,!1,g,!1):k.reset(n,{silent:!0});k.Wa()&&r&&(k.lastFetchCount=
r.length);k.Gb(g.silent?!0:!1,b.Y.D.SYNC,k,m,g);f&&f.call(b.t.Ti(a,k),k,m,g)};return this.YU(g)};b.j.prototype.Eia=function(a,b,c){var e;if(a){e=a instanceof Array?a:[a];a={};c&&this.yq(e.length);c=this.Wa();for(var g=null,f=0;f<e.length;f+=1)c&&(a={at:b},g=this.ul(b,null,!0,!1)),a.silent=!0,this.sl(e[f],a,!0,!1),this.ul(b,null,!0,!1)!==g&&b++}return e};b.j.prototype.lca=function(a,d,c,e){e=e||{};var g=e.parse,f=b.j.JH(this);if(a){var k=a instanceof Array?a:[a];a={};c&&this.yq(k.length);c=this.Wa();
if(e.bP&&!c){for(var l=0;l<k.length;l+=1)d=f&&g?f.parse(k[l]):k[l],k[l]=d;this.wL(k,!1,e,!1)}else{e=null;for(var m=d,l=0;l<k.length;l+=1)d=f&&g?f.parse(k[l]):k[l],c&&(a={at:m},e=this.ul(m,a,!0,!1)),a.silent=!0,this.sl(d,a,!0,!1),this.ul(m,null,!0,!1)!==e&&m++}}return k};b.j.MC=function(a,d,c,e){b.r.error(d.toString());c&&c.call(b.t.Ti(e,a),a,d,e)};b.j.prototype.ica=function(a){var d=a||{},c=d.success,e,g;void 0===d.parse&&(d.parse=!0);g=this;d.success=function(f){var k,l,m=null,n=[];try{k=g.parse(f,
a)}catch(p){b.j.MC(g,p,d.error,a);return}if(d.add||g.model)if(l=b.j.JH(g),k)for(m=k instanceof Array?k:[k],k=0;k<m.length;k+=1){if(l&&d.parse)try{e=l.parse(m[k])}catch(r){b.j.MC(g,r,d.error,a);return}else e=m[k];n.push(g.jx(e))}g.Gb(!1,b.Y.D.SYNC,g,f,d);c&&c.call(b.t.Ti(a,g),g,n,d)};this.YU(d)};b.j.prototype.YU=function(a){try{return b.t.Rw("read",this,a)}catch(d){throw b.t.Vx(this,!1,a,null,d,null),d;}};b.j.prototype.lL=function(){var a=this.totalResults;void 0!==a&&this.Tc()!==a&&(this.Hq(Array(a),
!0),this.Ex(),this.Bk())};b.j.prototype.mk=function(a){a=a||{};return a[b.j.Hd]||this[b.j.Hd]};b.j.prototype.Wa=function(){return-1<this.mk(null)};b.j.prototype.JB=function(a,d,c,e,g){a=parseInt(b.j.IB(a,d,c),10);return void 0===a||null===a||isNaN(a)?e?e:g:a};b.j.prototype.uT=function(a){return-1===a?void 0:a};b.j.prototype.H_=function(a,d,c,e){var g={};this.customPagingOptions&&((g=this.customPagingOptions.call(this,a))||(g={}));d=d||{};this.lastFetchSize=this.JB(g,a,"limit",d.fetchSize,this.fetchSize);
this.offset=this.JB(g,a,"offset",d.startIndex,0);this.lastFetchCount=this.JB(g,a,"count",this.lastFetchCount,this.lastFetchCount);this.totalResults=this.uT(this.JB(g,a,"totalResults",this.totalResults,this.totalResults));this.hasMore=this.fda(b.j.IB(g,a,"hasMore"),this.offset,this.lastFetchSize,this.totalResults);e||(this.totalResults=this.M9(this.uT(parseInt(b.j.IB(g,a,"totalResults"),10)),this.hasMore,this.offset,parseInt(b.j.IB(g,a,"count"),10),c&&Array.isArray(c)?c.length:0));!this.Wa()&&this.totalResults&&
this.totalResults!==this.lastFetchCount&&this.lastFetchSize&&this.DE(this.lastFetchSize)};b.j.prototype.M9=function(a,b,c,e,g){return!b&&isNaN(a)?(isNaN(e)?g:e)+c:this.totalResults};b.j.prototype.fda=function(a,d,c,e){return b.j.zl(a)?a:void 0===e||null===e?!0:d+c>e?!1:!0};b.j.IB=function(a,b,c){return a.hasOwnProperty(c)?a[c]:b?b[c]:void 0};b.j.prototype.dJ=function(){return b.j.zl(this.offset)?this.offset:0};b.j.prototype.create=function(a,d){function c(d,c){d.save(a instanceof b.t?null:a,c);return d}
function e(a,b){if(d.wait){if(g.Wa()||f)return g.Wd(function(){return Promise.resolve(void 0)})}else return g.add(a,b)}var g=this;d=d||{};var f=this.vf(d),k=this.jx(a,d,!1),l=d.success,m=d.context;d.context=this;d.success=function(a,b,c){c.xhr&&(d.xhr=c.xhr);d.wait&&g.add(k,d);l&&l.call(null!=m?m:g,a,b,d)};if(null==k)return!1;d.forceNew=null!=k.Vf();var n=b.t.Up(d);k.hv(this);if(f||this.Wa())return new Promise(function(a){n.merge=!0;n.deferred=!0;e(k,n).then(function(){d.success=function(b,c,e){e.xhr&&
(d.xhr=e.xhr);d.wait?(g.Wa()&&(n.force=!0),g.add(k,n).then(function(){l&&l.call(null!=m?m:g,b,c,d);a(b)})):(l&&l.call(null!=m?m:g,b,c,d),a(b))};var b=c(k,d);b||a(b)})});n.merge=!0;e(k,n);return c(k,d)};b.b.g("Collection.prototype.create",{create:b.j.prototype.create});b.j.prototype.m4=function(a){var b=[],c;this.Cf("pluck");for(c=0;c<this.Yd();c+=1)b.push(this.at(c).get(a));return b};b.b.g("Collection.prototype.pluck",{m4:b.j.prototype.m4});b.j.prototype.w5=function(a,b){return this.Kw(this.ay(a,
b))};b.b.g("Collection.prototype.where",{w5:b.j.prototype.w5});b.j.prototype.ay=function(a,d){d=d||{};var c=this.vf(d),e=this;if(this.Wa())return new Promise(function(c,g){e.ica({query:a,all:!0,success:function(a,b){c(b)},error:function(a,c,f){g(b.j.fw(a,c,f,e,d))}})});var g=[],f,k;for(f=0;f<this.Yd();f+=1)k=this.at(f),k.G5(a)&&g.push(k);return c?new Promise(function(a){a(g)}):g};b.j.prototype.x5=function(a,d){d=d||{};var c=this.vf(d),e=this;if(this.Wa()||c)return e.Wd(function(){return new Promise(function(b,
c){return e.ay(a,d).then(function(a){a=e.wY(a);b(a)},function(a){c(a)})})});c=this.ay(a,d);c=this.wY(c);c[b.j.Hd]=-1;c.Bk();return c};b.b.g("Collection.prototype.whereToCollection",{x5:b.j.prototype.x5});b.j.prototype.wY=function(a){var b=this.ET(!1);b.Hq(a,!1);b.Ex();b.Bk();return b};b.j.prototype.Cf=function(a){if(this.Wa())throw Error(a+" not valid on a virtual Collection");};b.j.prototype.map=function(a,b){var c=[],e;this.Cf("map");this.Ac().forEach(function(g){e=a.call(b||this,g);c.push(e)});
return c};b.b.g("Collection.prototype.map",{map:b.j.prototype.map});b.j.prototype.each=function(a,b){this.Cf("each");this.Ac().forEach(a,b)};b.b.g("Collection.prototype.each",{each:b.j.prototype.each});b.j.prototype.size=function(){return this.Yd()};b.b.g("Collection.prototype.size",{size:b.j.prototype.size});b.j.prototype.Q4=function(a,d){var c=[],e;this.Cf("sortBy");this.Ac().forEach(function(a){c.push(a)});e=this;c.sort(function(c,h){var k,l;if(f.isFunction(a))return k=a.call(d||e,c),l=a.call(d||
e,h),b.j.wl(k,l,e.sortDirection);k=c.get(a);l=h.get(a);return b.j.wl(k,l,e.sortDirection)});return c};b.b.g("Collection.prototype.sortBy",{Q4:b.j.prototype.Q4});b.j.prototype.a3=function(a,b){var c={},e;this.Cf("groupBy");this.Ac().forEach(function(g){e=f.isFunction(a)?a.call(b||this,g):g.get(a);void 0===c[e]&&(c[e]=[]);c[e].push(g)},this);return c};b.b.g("Collection.prototype.groupBy",{a3:b.j.prototype.a3});b.j.prototype.m3=function(a,b){var c={},e;this.Cf("indexBy");this.Ac().forEach(function(g){e=
f.isFunction(a)?a.call(b||this,g):g.get(a);c[e]=g},this);return c};b.b.g("Collection.prototype.indexBy",{m3:b.j.prototype.m3});b.j.prototype.min=function(a,b){var c={},e,g;this.Cf("min");if(0==this.Tc())return null;c=this.Mb(0);e=a.call(b||this,this.Mb(0));this.Ac().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g<e&&(c=f,e=g))},this);return c};b.b.g("Collection.prototype.min",{min:b.j.prototype.min});b.j.prototype.max=function(a,b){var c={},e,g;this.Cf("max");if(0==this.Tc())return null;c=this.Mb(0);
e=a.call(b,this.Mb(0));this.Ac().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g>e&&(c=f,e=g))},this);return c};b.b.g("Collection.prototype.max",{max:b.j.prototype.max});b.j.prototype.filter=function(a,b){var c=[];this.Cf("filter");this.Ac().forEach(function(e){a.call(b||this,e)&&c.push(e)});return c};b.b.g("Collection.prototype.filter",{filter:b.j.prototype.filter});b.j.prototype.y5=function(a){var b=[],c,e,g,f;this.Cf("without");for(var k,l=0;l<this.Ac().length;l++){f=!0;k=this.Mb(l);for(c=0;c<
arguments.length;c+=1)if(g=arguments[c].gp(),e=arguments[c].Vf(),k.kp(e,g)){f=!1;break}f&&b.push(k)}return b};b.b.g("Collection.prototype.without",{y5:b.j.prototype.y5});b.j.prototype.P1=function(a){var b=[],c,e,g,f,k;this.Cf("difference");for(var l,m=0;m<this.Ac().length;m++){k=!0;l=this.Mb(m);for(c=0;c<arguments.length;c+=1){for(e=0;e<arguments[c].length;e++)if(f=arguments[c][e].gp(),g=arguments[c][e].Vf(),l.kp(g,f)){k=!1;break}if(!k)break}k&&b.push(l)}return b};b.b.g("Collection.prototype.difference",
{P1:b.j.prototype.P1});b.j.prototype.mh=function(){return 0===this.Yd()};b.b.g("Collection.prototype.isEmpty",{mh:b.j.prototype.mh});b.j.prototype.d1=function(a,b){this.Cf("any");for(var c,e=0;e<this.Tc();e+=1)if(c=this.Mb(e),a.call(b||this,c))return!0;return!1};b.b.g("Collection.prototype.any",{d1:b.j.prototype.d1});b.j.prototype.V1=function(a,b){var c=this.vf(b),e=this;if(this.Wa()||c)return this.Wd(function(){return new Promise(function(c){e.ay(a,b).then(function(a){a&&0<a.length&&c(a[0]);c(null)})})});
c=this.ay(a,b);return 0<c.length?c[0]:null};b.b.g("Collection.prototype.findWhere",{V1:b.j.prototype.V1});b.j.prototype.slice=function(a,b,c){var e=this.vf(c);c=[];if(void 0===b){if(this.Wa()&&!this.qq())throw Error("End must be set for virtual collections with no totalResults");b=this.Tc()}if(e||this.Wa()){var g=this;return this.Wd(function(){return g.Nr(a,b)})}for(e=a;e<b;e+=1)c.push(this.Mb(e));return c};b.b.g("Collection.prototype.slice",{slice:b.j.prototype.slice});b.j.prototype.set=function(a,
b){return this.wL(a,!0,b,this.vf(b)||this.Wa())};b.b.g("Collection.prototype.set",{set:b.j.prototype.set});b.j.HZ=function(a,b,c,e,g){if(c)for(c=b.length-1;0<=c;c-=1)-1==e.indexOf(c)&&a.Gq(b[c],c,g)};b.j.prototype.hla=function(a,b,c,e){if(this.TB()||!c||!e)return{index:a,TO:!1};c=this.Tc();if(a>=c||b>=c)return{index:a,TO:!1};c=this.Mb(a);e=this.Mb(b);this.UC(a,e);e.iv(a);this.UC(b,c);c.iv(b);return{index:b,TO:b!==a}};b.j.prototype.wL=function(a,d,c,e){c=c||{};var g=void 0===c.add?!0:c.add,f=void 0===
c.remove?!0:c.remove,k=void 0===c.merge?!0:c.merge,l=[],m=null,n;d&&(a=this.parse(a));n=Array.isArray(a)?a:[a];if(e){var p=this;return this.Wd(function(){return p.oba(n,p.Ac(),c,f,g,k)})}d=!1;for(a=0;a<n.length;a+=1)if(m=this.P0(this.jx(n[a],c,!0),g,k,e),-1!==m){var m=this.hla(m,a,f,g),r=m.index;m.TO&&(d=!0);-1===l.indexOf(r)&&l.push(r)}d&&this.Gb(c.silent,b.Y.D.SORT,this,c.add?{add:!0}:null,null);b.j.HZ(this,this.Ac(),f,l,c)};b.j.prototype.oba=function(a,d,c,e,g,f){var k=[],l,m=this;return new Promise(function(n,
p){function r(b){return new Promise(function(d,e){m.P0(m.jx(a[b],c,!0),g,f,!0).then(function(a){-1!==a&&k.push(a);d(b+1)},e)})}var s=Promise.resolve(0);for(l=0;l<a.length;l+=1)s=s.then(r);s.then(function(){b.j.HZ(m,d,e,k,c);n(void 0)},p)})};b.j.prototype.P0=function(a,b,c,e){function g(e,g,f){var h=g?g.index:-1;if(g&&g.m){if(c){var k={merge:c};if(f)return new Promise(function(b){e.sl(a,k,!1,!0).then(function(){b(h)})});e.add(a,k)}}else if(b){if(f)return new Promise(function(b){e.sl(a,k,!1,!0).then(function(){b(e.Yd()-
1)})});e.add(a);h=e.Yd()-1}return h}if(e||this.Wa()){var f=this;return new Promise(function(b){f.Eh(a,{silent:!0},e).then(function(a){g(f,a,!0).then(function(a){b(a)})})})}var k=this.Eh(a);return g(this,k,!1)};b.j.prototype.toJSON=function(){var a=[];this.Cf("toJSON");this.Ac().forEach(function(b){a.push(b.toJSON())});return a};b.b.g("Collection.prototype.toJSON",{toJSON:b.j.prototype.toJSON});b.j.prototype.first=function(a,b){var c=this.vf(b),e=this.Yd(),g=[];a?e=a:a=1;c=this.Wa()||c;if(1===a){if(c){var f=
this;return this.Wd(function(){return f.UH(0,null)})}return 0<this.Tc()?this.Mb(0):null}e>this.Tc()&&(!this.Wa()||this.qq())&&(e=this.Tc());if(c)return f=this,this.Wd(function(){return f.Nr(0,e)});for(c=0;c<e;c+=1)g.push(this.Mb(c));return g};b.b.g("Collection.prototype.first",{first:b.j.prototype.first});b.j.prototype.indexOf=function(a,b){var c=this.vf(b);if(this.Wa()||c){var e=this;return this.Wd(function(){return e.Eh(a,null,!0).then(function(a){return a.index})})}return this.Eh(a).index};b.b.g("Collection.prototype.indexOf",
{indexOf:b.j.prototype.indexOf});b.j.prototype.contains=function(a,b){var c=this.vf(b);if(this.Wa()||c){var e=this;return this.Wd(function(){return e.Eh(a,null,!0).then(function(a){return-1<a.index})})}return-1<this.Eh(a).index};b.b.g("Collection.prototype.contains",{contains:b.j.prototype.contains});b.j.prototype.l3=b.j.prototype.contains;b.b.g("Collection.prototype.include",{l3:b.j.prototype.l3});b.j.prototype.lha=function(a){a=this.XV(a);return void 0!==a?a.index:-1};b.j.prototype.pop=function(a){var b=
this.vf(a);if(this.Wa()||b){var c=this;return this.at(this.Yd()-1,{deferred:b}).then(function(b){c.remove(b,a);return b})}b=this.at(this.Yd()-1);this.remove(b,a);return b};b.b.g("Collection.prototype.pop",{pop:b.j.prototype.pop});b.j.prototype.push=function(a,b){var c=this.vf(b);this.yq(1);return this.Kw(this.sl(a,b,!1,c))};b.b.g("Collection.prototype.push",{push:b.j.prototype.push});b.j.prototype.lastIndexOf=function(a,d){var c;this.Cf("lastIndexOf");void 0===d&&(d=0);for(c=this.Yd()-1;c>=d;c-=1)if(b.b.Iv(a,
this.at(c)))return c;return-1};b.b.g("Collection.prototype.lastIndexOf",{lastIndexOf:b.j.prototype.lastIndexOf});b.j.prototype.xW=function(a){return void 0===a?[]:a.split(",")};b.j.Qda=function(a){a=Array.isArray(a)?a:[a];var d="",c,e,g,h;for(g=0;g<a.length;g++){c=a[g];for(h in c)if(c.hasOwnProperty(h))for(var k=Array.isArray(c[h])?c[h]:[c[h]],l=0;l<k.length;l++){if(b.t.FP(k[l])){e=k[l].value;var m=null,m=k[l].comparator,m=f.isFunction(m)?m(null,h,e):m;e=h+m+e}else e=h+"\x3d"+c[h];d+=e+"+"}d=d.substring(0,
d.length-1)+","}return","===d.substring(d.length-1)?d.substring(0,d.length-1):d};b.j.prototype.l6=function(a){var d={},c;for(c in a)a.hasOwnProperty(c)&&(d[c]=a[c]);if((a=this.comparator)&&b.Ea.jd(a)){a=this.xW(a);for(c=0;c<a.length;c++)d.sort=0===c?a[c]:d.sort+(","+a[c]);d.sortDir=this.yW()}this.Wa()&&(d[b.j.Hd]=this.mk(d));return d};b.j.prototype.a6=function(){if(f.isFunction(this.customURL))return!0;var a=this.xP(null);return b.j.zl(a)};b.j.prototype.xP=function(a){var d=b.t.Qm(this,"url");if(this.Wa()){var c=
a.all,e=null;e=c?(e=this.totalResults)?e:this.mk(a):this.mk(a);d=d&&-1<d.indexOf("?")?d+"\x26":d+"?";d+="limit\x3d"+e;c||(b.j.zl(a.startIndex)&&(d+="\x26offset\x3d"+a.startIndex),a.startID&&(d+="\x26fromID\x3d"+a.startID),a.since&&(d+="\x26since\x3d"+a.since),a.until&&(d+="\x26until\x3d"+a.until));a.query&&(a=b.j.Qda(a.query))&&0<a.length&&(d+="\x26q\x3d"+a);if((a=this.comparator)&&b.Ea.jd(a))for(a=this.xW(a),c=this.yW(),e=0;e<a.length;e++)d=0===e?d+("\x26orderBy\x3d"+a[e]+":"+c):d+(","+a[e]+":"+
c);d+="\x26totalResults\x3dtrue"}return d};b.j.prototype.yW=function(){return-1===this.sortDirection?"desc":"asc"};b.j.prototype.sync=function(a,b,c){return window.oj.sync(a,b,c)};b.j.Hd="fetchSize"});