/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojbutton","ojs/ojmenu","ojs/ojlistview"],function(b,f){b.od=function(a,b,e){this.u=a;this.qb=b;this.aO=e};b.od.prototype.Le=function(){this.qb.removeClass("oj-navigationlist-expanded oj-navigationlist-vertical")};b.od.prototype.Lr=function(){};b.od.prototype.Ir=function(){};b.od.prototype.BP=function(){return!1};b.od.prototype.qF=function(){};b.od.prototype.AF=function(a,b){a.attr("aria-selected",b?"true":"false")};b.od.prototype.UE=function(){};
b.od.prototype.HP=function(){};b.od.prototype.IP=function(){};b.od.prototype.ip=function(b,c,e){return a.q.ip.apply(this.u,arguments)};b.od.prototype.Mr=function(b){return a.q.Mr.apply(this.u,arguments)};b.od.prototype.Oe=function(b){return a.q.Oe.apply(this.u,arguments)};b.od.prototype.lp=function(b,c){a.q.lp.apply(this.u,arguments)};b.od.prototype.Init=function(){this.qb.addClass("oj-navigationlist-expanded oj-navigationlist-vertical")};b.od.prototype.uh=function(b){return a.q.uh.apply(this.u,arguments)};
b.od.prototype.dv=function(){};b.od.prototype.lP=function(){};b.od.prototype.zr=function(){};b.Wf=function(a,c,e){b.Wf.q.constructor.call(this,a,c,e)};b.b.ga(b.Wf,b.od,"oj.HorizontalNavListHandler");b.Wf.prototype.Le=function(){this.qb.removeClass("oj-navigationlist-expanded oj-navigationlist-horizontal");this.qb.find("."+this.u.Kr).remove()};b.Wf.prototype.AF=function(a,b){a.attr("aria-pressed",b?"true":"false")};b.Wf.prototype.ip=function(b,c,e){b===f.ui.keyCode.LEFT?b=this.u.Lf()?f.ui.keyCode.DOWN:
f.ui.keyCode.UP:b===f.ui.keyCode.RIGHT&&(b=this.u.Lf()?f.ui.keyCode.UP:f.ui.keyCode.DOWN);b=a.q.ip.call(this.u,b,c,e);"top"===this.u.W.options.edge&&this.u.ib.elem[0].scrollIntoView(!1);return b};b.Wf.prototype.Mr=function(a){return a===this.u.yF||a===this.u.WE||a===this.u.$u||a===this.u.oz};b.Wf.prototype.qF=function(a){a=this.u.dE(a);a.attr("role","button");a[0].hasAttribute("aria-selected")&&(a.attr("aria-pressed","false"),a.removeAttr("aria-selected"))};b.Wf.prototype.UE=function(){var a=this;
this.u.element.attr("role","toolbar");this.u.element.find("."+this.u.Jf()+":visible").each(function(b){0<b&&a.BS(this,b)})};b.Wf.prototype.BS=function(a,b){var e=f(a),g=e.prev();0<b&&e.is(":visible")&&g.length&&!g.is("li."+this.u.Kr)&&e.before('\x3cli role\x3d"separator" class\x3d"'+this.u.Kr+'"\x3e\x3c/li\x3e')};b.Wf.prototype.HP=function(a,b){this.BS(a,b.index)};b.Wf.prototype.IP=function(a){a=f(a);var b=a.prev();b.length&&b.is("li."+this.u.Kr)?b.remove():(a=a.next(),a.is("li."+this.u.Kr)&&a.remove())};
b.Wf.prototype.uh=function(a){return this.u.ke(f(a))[0].hasAttribute("aria-pressed")};b.Wf.prototype.Init=function(){this.qb.addClass("oj-navigationlist-expanded oj-navigationlist-horizontal")};b.Wf.prototype.dv=function(){};b.Oj=function(a,c,e){b.Oj.q.constructor.call(this,a,c,e)};b.b.ga(b.Oj,b.od,"oj.CollapsibleNavListHandler");b.Oj.prototype.Le=function(){this.qb.removeClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};b.Oj.prototype.Init=function(){this.qb.addClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};
b.Oj.prototype.Lr=function(b,c){a.q.RE.apply(this.u,arguments)};b.Oj.prototype.Ir=function(b,c){a.q.PE.apply(this.u,arguments)};b.Oj.prototype.BP=function(a,b,e,g){var h=0<e.children("."+this.u.Ei()).length;if(b===this.u.$u||b===this.u.oz)return b===this.u.$u&&!this.u.Lf()||b===this.u.oz&&this.u.Lf()?this.u.Oe(e)===this.u.Wi&&this.u.Nm(e,a,!0,g,!0,!0):this.u.Oe(e)===this.u.Vi&&this.u.ep(e,a,!0,g,!0,!0,!0),!0;if(h&&(b===f.ui.keyCode.ENTER||b===f.ui.keyCode.SPACE)){if(0>=e.length)return;this.u.Oe(e)===
this.u.Vi?this.u.ep(e,null,!0,g,!0,!0,!0):this.u.Oe(e)===this.u.Wi&&this.u.Nm(e,null,!0,g,!0,!0);return!0}return!1};b.Oj.prototype.dv=function(){};b.Yc=function(a,c,e){b.Yc.q.constructor.call(this,a,c,e);this.dO=[]};b.b.ga(b.Yc,b.Oj,"oj.SlidingNavListHandler");b.Yc.prototype.Le=function(){this.qb.removeClass("oj-navigationlist-slider oj-navigationlist-vertical");this.hD.remove()};b.Yc.prototype.d0=function(a,b,e){var f=this,h=this.u.yN(),k=h.outerWidth()/2,l=this.u.Lf();b||(k*=-1);l?(h.css({"margin-right":k}),
h.animate({"margin-right":"0px"},400,"swing",function(){f.aD(a,b,e)})):(h.css({"margin-left":k}),h.animate({"margin-left":"0px"},400,"swing",function(){f.aD(a,b,e)}))};b.Yc.prototype.aD=function(a,b,e){null!==this.u.Ee&&(e&&(e=this.u.qd(e[0]),this.u.wh("currentItem",e)),b?this.u.SE(a.children("."+this.u.Ei())):this.u.QE(a.children("."+this.u.Ei())))};b.Yc.prototype.Lr=function(a,b){var e=f(a).parents(".oj-navigationlist-item-element:first"),g=e.children("."+this.u.Ei()),h,k=null,l=e.closest("."+this.u.Vm);
if(0<l.length){l.removeClass(this.u.Vm);e.addClass(this.u.Vm);var k=g.find("."+this.u.Jf()+":eq(0)"),m=e.parentsUntil(l,"ul"),m=l.is(this.u.element)?m.get().concat(l.get()):m.get(),n=this,p,m=f(m.reverse());m.each(function(a,b){h=f(b).is(n.u.element)?n.u.bE():n.u.rN(f(b).parent());p=a===m.length-1?e:f(m.get(a+1)).parent();n.E9(n.u.qd(p[0]),n.u.rN(p),h);n.dO.push(p)})}b?this.d0(e,!0,k):this.aD(e,!0,k);this.u.element.focus();e.siblings().attr("aria-hidden","true");e.children("."+this.u.kh()).children("."+
this.u.Rj).attr("aria-hidden","true");g.removeAttr("aria-hidden");a.css("display","");e.addClass("oj-skipfocus")};b.Yc.prototype.Ir=function(a,b){var e=a.children("."+this.u.Ei()),f=a.parent();a.children("."+this.u.kh()).children("."+this.u.Rj).removeAttr("aria-hidden");e.attr("aria-hidden","true");a.siblings().removeAttr("aria-hidden");a.removeClass("oj-skipfocus");a.removeClass(this.u.Vm);0===a.closest("."+this.u.Vm).length&&(f.closest("."+this.u.Jf()).addClass(this.u.Vm),this.u.element.is(f)&&
this.u.element.addClass(this.u.Vm));b?this.d0(a,!1,e.parent()):this.aD(a,!1,e.parent());this.pja();this.u.element.focus()};b.Yc.prototype.AF=function(a,b){b?a.attr("aria-describedby","selectedLabel"):a.removeAttr("aria-describedby")};b.Yc.prototype.Oe=function(a){a=this.u.ke(a).attr("aria-expanded");return"true"===a?this.u.Wi:"false"===a?this.u.Vi:this.u.aQ};b.Yc.prototype.lp=function(a,b){b===this.u.Wi?(this.u.ke(a).attr("aria-expanded","true"),a.removeClass(this.u.iP).addClass(this.u.rP)):b===this.u.Vi&&
(this.u.ke(a).attr("aria-expanded","false"),a.removeClass(this.u.rP).addClass(this.u.iP))};b.Yc.prototype.qF=function(a,b){var e=this.u.ke(a);e.attr("role","menuitem");b.attr("id")||b.uniqueId();var f=a.children("."+this.u.Ei());0<f.length&&(e.attr("aria-haspopup","true"),f.attr("role","menu"),f.css("display",""),a.removeAttr("aria-expanded"),e.attr("aria-expanded","false"))};b.Yc.prototype.UE=function(){this.u.element.attr("role","menu")};b.Yc.prototype.Init=function(a){this.qb.addClass("oj-navigationlist-slider oj-navigationlist-vertical");
a.element.addClass("oj-navigationlist-current");this.x$(a);this.kga()};b.Yc.prototype.x$=function(a){var b;this.hD=f(document.createElement("div"));this.hD.addClass("oj-navigationlist-toolbar");this.Tl=f(document.createElement("a"));this.qx=f(document.createElement("span"));this.qx.addClass("oj-navigationlist-previous-icon oj-component-icon oj-clickable-icon-nocontext").attr("role","img").attr("alt",this.aO.A("previousIcon"));this.qx.hide();this.Tl.addClass("oj-navigationlist-previous-link").attr("tabindex",
"-1").append(this.qx);this.Mw=f(document.createElement("label"));this.Mw.addClass("oj-navigationlist-current-header").text(this.u.bE());this.wD=f(document.createElement("span"));this.wD.attr("role","separator").attr("aria-orientation","vertical").addClass("oj-navigationlist-toolbar-separator");this.Fh=f(document.createElement("button"));this.Fh.addClass("oj-navigationlist-hierarchical-button");this.wf=f(document.createElement("ul"));this.wf.addClass("oj-navigationlist-hierarchical-menu").hide();b=
f(document.createElement("label"));b.addClass("oj-helper-hidden-accessible").attr("aria-hidden","true").attr("id","selectedLabel");b.text(this.aO.A("selectedLabel"));this.Tl.append(this.Mw);this.hD.append(this.Tl).append(this.wD).append(this.Fh).append(this.wf).append(b);this.qb.prepend(this.hD);this.YC(a.hierarchyMenuDisplayThresholdLevel)};b.Yc.prototype.lP=function(){var a=this.dO.pop();a&&this.u.Nm(a,null,!0,null,!0,!0)};b.Yc.prototype.kga=function(){var a=this,b=this.wf.uniqueId().attr("id");
this.wf.ojMenu({openOptions:{position:{my:"end top",at:"end bottom"}},select:function(b,c){for(var h=c.item.nextAll(),k,l,m=a.dO,n=c.item.data("key");0<m.length&&(l=m.pop(),k=a.u.qd(l[0]),a.u.Nm(f(l),null,!0,k,!0,!0),n!==k););h.remove();c.item.remove();a.wf.ojMenu("refresh")}});this.Fh.ojButton({label:this.aO.A("hierMenuBtnLabel"),display:"icons",icons:{start:"oj-fwk-icon oj-hier-icon"},menu:"#"+b,disabled:!0,chroming:"half"})};b.Yc.prototype.E9=function(a,b,e){if(this.Fh){var g=this.wf.find("li").length,
h=f(document.createElement("li")),k=f(document.createElement("a"));k.attr("href","#");h.append(k);if(0<g){for(var l=0;l<g;l++)0<l&&k.append(f(document.createElement("span")).addClass("oj-navigationlist-hvitem-space"));k.append(f(document.createElement("span")).addClass("oj-menu-item-icon oj-icon oj-navigationlist-level-indicator"))}g=f(document.createElement("span")).addClass("oj-navigationlist-hierarchical-menu-label");g.text(e);k.append(g);h.data("key",a);this.wf.append(h);this.wf.ojMenu("refresh");
this.YC(this.u.Qd("hierarchyMenuDisplayThresholdLevel"));this.Fh.ojButton("option","disabled",!1);this.qx.show();this.Tl.attr("tabindex","0");this.Mw.text(b)}};b.Yc.prototype.zr=function(a){this.u.Qd("hierarchyMenuDisplayThresholdLevel")!==a.hierarchyMenuDisplayThresholdLevel&&this.YC(a.hierarchyMenuDisplayThresholdLevel)};b.Yc.prototype.YC=function(a){var b=this.wf.find("li").length;-1===a||b<a?(this.wD.hide(),this.Fh.hide()):b>=a&&(this.wD.show(),this.Fh.show())};b.Yc.prototype.pja=function(){if(this.Fh){var a=
this.wf.find("li").last().remove();this.wf.ojMenu("refresh");this.YC(this.u.Qd("hierarchyMenuDisplayThresholdLevel"));0===this.wf.children("li").length?(this.Fh.ojButton("option","disabled",!0),this.qx.hide(),this.Tl.attr("tabindex","-1"),this.Mw.text(this.u.bE())):this.Mw.text(a.children("a").text())}};b.Yc.prototype.dv=function(a,b){a.removeClass(this.u.Vm);b.removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-describedby").removeAttr("aria-hidden")};var a=function(a,c){function e(){}
b.b.ga(e,a,"");f.extend(e.prototype,c);return e}(b.BK,{Rj:"oj-navigationlist-item-content",rP:"oj-expanded",iP:"oj-collapsed",Vm:"oj-navigationlist-current",Kr:"oj-navigationlist-divider",I6:"oj-navigationlist-category-divider",WF:"oj-navigationlist-item-label",ZQ:"oj-navigationlist-icon-only",C7:"oj-navigationlist-item-icon",uqa:"oj-navigationlist-horizontal",uR:"oj-navigationlist-has-icons",vR:"oj-navigationlist-item-no-icon",e8:"oj-navigationlist-item-title",wR:"oj-navigationlist",xR:"oj-navigationlist-touch",
f8:"oj-navigationlist-listview-container",Jz:"IsTitleAttrDueToTruncation",FF:"oj-navigationlist-app-level",eG:"oj-navigationlist-page-level",rN:function(a){a=this.ZD(a);return a.is("a")?f.trim(a.text()):f.trim(a.find("."+this.e8).text())},ZD:function(a){var b=a.children("."+this.Rj);0===b.length&&(b=a.children("."+this.kh()).children("."+this.Rj),0===b.length&&(b=a.children("."+this.kh()).children(":not(."+this.gm()+"):not(."+this.Ej()+")")));return b},Lf:function(){return"rtl"===this.W.ac()},Bm:function(){this.Xb.UE();
a.q.Bm.apply(this,arguments)},z3:function(a,b){this.Xb.HP(a,b)},QN:function(b){this.Xb.IP(b);a.q.QN.apply(this,arguments)},g_:function(a){a=a.children();for(var b=0;b<a.length;b++){var e=a[b],e=f(e);if(e.hasClass(this.Kr))e.remove();else{var g=this.ZD(e);g.removeClass(this.Rj).removeClass(this.vR).removeAttr("aria-haspopup");e.removeClass("oj-default").removeAttr("role").removeAttr("aria-disabled").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-pressed");var h=this.ke(e);h.removeAttr("role").removeAttr("aria-hidden").removeAttr("aria-pressed");
g.children("."+this.WF).contents().unwrap();h.data(this.Jz)&&h.removeAttr("title");h=e.children("ul");0<h.length?(h.removeAttr("style").removeClass(this.uR).removeAttr("aria-hidden"),this.Xb.dv(e,g,h),this.g_(h)):this.Xb.dv(e,g)}}},kz:function(b){return b.hasClass(this.Rj)||b.hasClass(this.gm())||b.hasClass(this.Ej())?!1:a.q.kz.apply(this,arguments)},GP:function(a){return a.prop("nodeName").match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&!a.hasClass(this.Rj)||a.hasClass("oj-component")},mia:function(a){var b=
{drillMode:"none"!==a.drillMode?"collapsible":"none",selection:null!==a.selection?[a.selection]:[],item:a.item,data:a.data,selectionMode:"single"};b.element=this.Wn;b.item.focusable=function(a){return f(a.data).is("li")?!f(a.data).hasClass("oj-disabled"):!f(a.parentElement).hasClass("oj-disabled")};return b=f.extend(f.extend({},a),b)},bE:function(){return this.W.options.rootLabel?this.W.options.rootLabel:this.W.A("defaultRootLabel")},gv:function(){var b=this.W.element.attr("aria-labelledby");b?(this.element.attr("aria-labelledby",
b),this.W.element.removeAttr("aria-labelledby")):this.element.attr("aria-label",this.bE());a.q.gv.apply(this,arguments)},zF:function(){this.element.attr("aria-labelledby")&&(this.W.element.attr("aria-labelledby",this.element.attr("aria-labelledby")),this.element.removeAttr("aria-labelledby"));this.element.attr("aria-label")&&this.element.removeAttr("aria-label");a.q.zF.apply(this,arguments)},om:function(d){var c=this,e=d.W.element;e.addClass(this.wR);b.v.Od()&&e.addClass(this.xR);this.Wn=e.children("ul:first");
0===this.Wn.length&&(this.Wn=f(document.createElement("ul")),e.append(this.Wn));e=f(document.createElement("div"));e.addClass(this.f8);this.Wn.wrap(e);d=this.mia(d);a.q.om.call(this,d);this.element.removeClass("oj-component-initnode");this.W._on(this.W.element,{touchstart:function(a){(a=c.Ri(f(a.target)))&&!a.hasClass("oj-disabled")&&c.jp(a,"oj-active",!0)},touchend:function(a){a=c.Ri(f(a.target));c.jp(a,"oj-active",!1)},mousedown:function(a){(a=c.Ri(f(a.target)))&&!a.hasClass("oj-disabled")&&c.jp(a,
"oj-active",!0)},mouseup:function(a){a=c.Ri(f(a.target));c.jp(a,"oj-active",!1)},"click .oj-navigationlist-previous-link":function(){c.AH()},"keydown .oj-navigationlist-previous-link":function(a){a.keyCode===f.ui.keyCode.ENTER&&c.AH()},"keydown .oj-navigationlist-element":function(a){a.keyCode!==f.ui.keyCode.ESCAPE||a.isDefaultPrevented()||c.AH()},"mouseenter a.oj-navigationlist-item-content":function(a){a=f(a.currentTarget);var b=a.find("."+c.WF);b[0].offsetWidth<b[0].scrollWidth&&!a.attr("title")&&
(a.attr("title",b.text().trim()),a.data(c.Jz,"true"))},"mouseleave a.oj-navigationlist-item-content":function(a){a=f(a.currentTarget);a.data(c.Jz)&&(a.removeData(c.Jz),a.removeAttr("title"))}})},AH:function(){this.Xb.lP()},AX:function(){var a=this.W.options.drillMode,c=this.W.options.edge;this.Xb="sliding"===a?new b.Yc(this,this.W.element,this.W):"collapsible"===a?new b.Oj(this,this.W.element,this.W):"none"===a&&"top"===c?new b.Wf(this,this.W.element,this.W):new b.od(this,this.W.element,this.W);this.Xb.Init(this.options);
this.E_(this.W.options.navigationLevel)},E_:function(a){"none"===this.W.options.drillMode&&("application"===a?(this.W.element.addClass(this.FF),this.W.element.removeClass(this.eG)):"page"===a&&(this.W.element.addClass(this.eG),this.W.element.removeClass(this.FF)))},du:function(){this.AX();a.q.du.apply(this,arguments)},yP:function(){return"oj-navigationlist-listview"},dF:function(){return"oj-navigationlist-element"},Gj:function(){return"oj-navigationlist-item"},Mk:function(){return"oj-navigationlist-focused-element"},
Jf:function(){return"oj-navigationlist-item-element"},Ej:function(){return"oj-navigationlist-collapse-icon"},gm:function(){return"oj-navigationlist-expand-icon"},oN:function(a){return"oj-navigationlist-depth-"+a},kh:function(){return"oj-navigationlist-group-item"},Ei:function(){return"oj-navigationlist-group"},qu:function(){return"oj-navigationlist-collapsible-transition"},$q:function(){return this.qu()},RE:function(a,b){this.Xb.Lr(a,b)},PE:function(a,b){this.Xb.Ir(a,b)},ip:function(a,b,e){return this.Xb.ip(a,
b,e)},Mr:function(a){return this.Xb.Mr(a)},Oe:function(a){return this.Xb.Oe(a)},lp:function(a,b){this.Xb.lp(a,b)},iF:function(b){var c=this.Ri(f(b.target));null!=c&&0!==c.length&&(this.$h(c)?b.preventDefault():(this.qd(c[0]),this.kz(f(b.target))||(c=this.ZD(c).attr("href"),c&&"#"!==c&&0===b.button&&(b.shiftKey||b.ctrlKey)||(a.q.iF.apply(this,arguments),b.preventDefault()))))},CP:function(a){var b,e,g;b=a.keyCode;e=this.ib.elem;g=this.ib.key;if(b===f.ui.keyCode.HOME||b===f.ui.keyCode.END){var h;h=
b===f.ui.keyCode.HOME?this.element.find("."+this.Rj+":visible").first().closest("."+this.Jf()):this.element.find("."+this.Rj+":visible").last().closest("."+this.Jf());h=this.qd(h[0]);this.wh("currentItem",h);a.preventDefault()}else h=this.EP(a),b=this.Xb.BP(a,b,e,g),!0!==h&&!0!==b||a.preventDefault()},rz:function(b,c,e){var f=this.ib.elem;this.uh(f[0])&&!this.cY(f)&&this.uI(b,f)&&(a.q.rz.apply(this,arguments),this.bK(f))},jp:function(a,b,e){var g;a=f(a);"oj-selected"===b&&this.Xb.AF(this.ke(a),e);
g=a.children("."+this.kh());0<g.length&&(a=f(g[0]));e?a.addClass(b):a.removeClass(b);a.hasClass("oj-selected")||a.hasClass("oj-hover")||a.hasClass("oj-active")||a.hasClass("oj-disabled")?a.removeClass("oj-default"):a.addClass("oj-default")},uh:function(a){return!f(a).hasClass("oj-disabled")&&this.Xb.uh(f(a))},Xm:function(a,b,e){return"ready"!==a?this.W._trigger(a,b,e):!0},wh:function(a,b,e){if("selection"===a){var f=e._context,h=f&&f.Cj&&f.Cj.items;h&&(f.Cj.item=h,f.Cj.items=void 0);b&&0<b.length?
this.W.option(a,b[0],e):this.W.option(a,null,e)}else this.W.option(a,b,e);this.options[a]=b},dQ:function(a){return null!=a.data||null!=a.drillMode||null!=a.item||null!=a.display||null!=a.edge},zr:function(b,c){var e={NO:[]},g;void 0!==b.hierarchyMenuDisplayThresholdLevel&&this.Xb.zr(b);void 0!==b.navigationLevel&&this.E_(b.navigationLevel);if(void 0!==b.selection)if(g=b.selection){var h=this.Qd("selection");h&&0!==h.length&&h[0]===g?delete b.selection:(h=this.Fd(g))&&this.uh(h)?this.uI(null,f(h))?
(b.selection=[g],this.bK(f(h))):(delete b.selection,e.NO.push("selection")):(delete b.selection,e.NO.push("selection"))}else b.selection=[];e.Qoa=a.q.zr.call(this,b,c);void 0!==g&&(b.selection=g);return e},Qd:function(a){var b=this.W.option(a);return"selection"===a?b?[b]:[]:null===b?this.options[a]:b},sg:function(){return b.Components.sg(this.W.element)},fv:function(b,c){if(!b.hasClass("oj-disabled")&&this.uh(b[0])){var e=this.qd(b[0]);this.wh("currentItem",e);!this.cY(b)&&this.uI(c,b)&&(a.q.fv.apply(this,
arguments),this.bK(b))}},uI:function(a,b){var e=this.qd(b[0]);return this.Xm("beforeSelect",a,{item:b,key:e})},bK:function(a){return(a=this.ZD(a).attr("href"))&&"#"!==a?(window.location.href=a,!0):!1},cY:function(a){var b;b=this.Qd("selection");a=this.qd(a[0]);return-1<b.indexOf(a)?!0:!1},Ly:function(b,c){var e=f(b);if(e.hasClass(this.I6))e.removeClass(this.Jf()),e.removeClass(this.Mk()),e.removeClass(this.Gj()),e.removeAttr("aria-selected"),e.children().remove(),e.attr("role","separator");else{var g=
this.Ej(),h=this.gm(),k=this.C7,l=e.children("."+this.kh()),m;0<l.length?(l.addClass(this.Gj()),m=l.children(":not(."+h+"):not(."+g+")"),h=l.children("."+h),0===h.length&&(h=l.children("."+g)),h.attr("role","presentation"),h.removeAttr("aria-labelledby"),e.hasClass("oj-disabled")&&l.addClass("oj-disabled")):m=e.children().first();m.addClass(this.Rj);g=m.wrapInner('\x3cspan class\x3d"'+this.WF+'"\x3e\x3c/span\x3e').find("."+k);0<g.length?(g.insertBefore(g.parent()),"icons"===this.W.options.display&&
(this.W.element.addClass(this.ZQ),g.attr("aria-label",this.rN(e)),g.attr("role","img")),e.closest("ul").addClass(this.uR)):m.addClass(this.vR);e.hasClass("oj-disabled")?this.ke(e).attr("aria-disabled","true"):0<l.length?l.addClass("oj-default"):e.addClass("oj-default");this.Xb.qF(e,m);a.q.Ly.apply(this,arguments)}},getNodeBySubId:function(a){var b;if(null===a)return this.element?this.element[0]:null;b=a.subId;return"oj-navigationlist-item"===b?(a=a.key,a=this.Fd(a)):"oj-navigationlist-previous-link"===
b?this.Xb.Tl?this.Xb.Tl[0]:null:"oj-navigationlist-hierarchical-button"===b?this.Xb.Fh?this.Xb.Fh[0]:null:"oj-navigationlist-hierarchical-menu"===b?this.Xb.wf?this.Xb.wf[0]:null:null},getSubIdByNode:function(a){if(this.Xb.Tl&&this.Xb.Tl[0]===a)return{subId:"oj-navigationlist-previous-link"};if(this.Xb.Fh&&this.Xb.Fh[0]===a)return{subId:"oj-navigationlist-hierarchical-button"};if(this.Xb.wf&&this.Xb.wf[0]===a)return{subId:"oj-navigationlist-hierarchical-menu"};a=this.Ri(a);return null!=a&&0<a.length&&
(a=this.qd(a[0]),null!=a)?{subId:"oj-navigationlist-item",key:a}:null},refresh:function(){this.a_();this.AX();a.q.refresh.apply(this,arguments)},a_:function(){this.W.element.removeClass(this.ZQ);this.W.element.removeClass(this.FF);this.W.element.removeClass(this.eG);this.g_(this.element);this.Xb.Le()},destroy:function(){this.a_();a.q.destroy.apply(this,arguments);this.Wn.unwrap();this.Wn.is(":empty")&&this.Wn.remove();this.W.element.removeClass(this.wR+" "+this.xR);this.W._off(this.element,"click");
this.W._off(this.element,"focus");this.W._off(this.element,"blur");this.W._off(this.element,"mouseover");this.W._off(this.element,"mousein");this.W._off(this.element,"mouseout");this.W._off(this.element,"keydown")}});(function(){b.ya("oj.ojNavigationList",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{currentItem:null,drillMode:"none",edge:"start",hierarchyMenuDisplayThresholdLevel:0,rootLabel:null,selection:null,expanded:"auto",data:null,display:"all",navigationLevel:"page",item:{renderer:null,
selectable:!0},beforeSelect:null,beforeCollapse:null,beforeCurrentItem:null,collapse:null,beforeExpand:null,expand:null,optionChange:null},_ComponentCreate:function(){this._super();this.Aa()},hf:function(){this._super();this.nh.du()},lf:function(a,b,e){this.nh.d4(a,b,e)},Aa:function(){for(var b in this.options)this.T0(b,this.options[b]);this.xD(this.options.drillMode,this.options.display,this.options.edge);this.nh=new a;b={W:this};b=f.extend(this.options,b);this.nh.om(b)},getNodeBySubId:function(a){return this.nh.getNodeBySubId(a)},
getSubIdByNode:function(a){return this.nh.getSubIdByNode(a)},expand:function(a,b){this.nh.ZM(a,b,!0,!0)},collapse:function(a,b){this.nh.t1(a,b,!0)},getExpanded:function(){return this.nh.getExpanded()},xD:function(a,b,e){if("none"!==a){if("icons"===b)throw"Icon only navigation list should have drillMode set to 'none'.";if("top"===e)throw"Horizontal navigation list should have drillMode set to 'none'.";}},T0:function(a,b){var e=!0;"drillMode"===a?e="none"===b||"collapsible"===b||"sliding"===b:"display"===
a?e="all"===b||"icons"===b:"edge"===a&&(e="top"===b||"start"===b);if(!e)throw"Invalid value: "+b+" for key: "+a;},_setOption:function(a,b){this.T0(a,b);switch(a){case "drillMode":this.xD(b,this.options.display,this.options.edge);break;case "display":this.xD(this.options.drillMode,b,this.options.edge);break;case "edge":this.xD(this.options.drillMode,this.options.display,b)}return this._super(a,b)},_setOptions:function(a,b){var e=this.nh.zr(a,b),f;for(f in a)0>e.NO.indexOf(f)&&this._setOption(f,a[f],
b);e.Qoa&&this.nh.refresh();return this},ii:function(){this.nh.e4()},ml:function(){},refresh:function(){this._super();this.nh.refresh()},_destroy:function(){this.nh.destroy();this._super();delete this.nh}});b.Components.Em({ojNavigationList:{hierarchyMenuDisplayThresholdLevel:b.Components.ih(function(){return b.we.Ok("navigationList").hierarchyMenuDisplayThresholdLevel})}})})()});