/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","promise","ojs/ojjquery-hammer","ojs/ojcomponentcore"],function(b,f,a){b.o={};o_("OffcanvasUtils",b.o,b);b.o.NF="oj-offcanvasEdge";b.o.an="oj-offcanvas";b.o.OF="oj-mediaQueryListener";b.o.GQ="oj-offcanvasHammer";b.o.ev="selector";b.o.Tu="start";b.o.Su="end";b.o.pP="top";b.o.XE="bottom";b.o.Qu="displayMode";b.o.Ru="push";b.o.oP="overlay";b.o.e6="modality";b.o.jqa="none";b.o.f6="modal";b.o.gz="_dismissHandler";b.o.rF="_openPromise";b.o.Pu="_closePromise";b.o.hz=
"_glassPane";b.o.bQ="_surrogate";b.o.uF="data-oj-surrogate-id";b.o.q6="oj-offcanvas-outer-wrapper";b.o.OP="oj-offcanvas-open";b.o.Wm="oj-offcanvas-transition";b.o.P5="oj-offcanvas-glasspane";b.o.wP="oj-offcanvas-glasspane-dim";b.o.kqa="oj-offcanvas-generated";b.o.Ska={start:"oj-offcanvas-shift-start",end:"oj-offcanvas-shift-end",top:"oj-offcanvas-shift-down",bottom:"oj-offcanvas-shift-up"};b.o.Tba={start:"oj-offcanvas-start",end:"oj-offcanvas-end",top:"oj-offcanvas-top",bottom:"oj-offcanvas-bottom"};
b.o.Tca=function(a){a=a[b.o.Qu];a!==b.o.oP&&a!==b.o.Ru&&(a=b.we.Ok("offcanvas").displayMode);return a};b.o.pi=function(a){return f(a[b.o.ev])};b.o.iK=function(a){return a[b.o.e6]===b.o.f6};b.o.Sn=function(a){return a.hasClass(b.o.OP)};b.o.Cw=function(a){return a.closest("."+b.o.q6)};b.o.pB=function(a){var c=b.o.pi(a);return a[b.o.Qu]===b.o.Ru?c.parent():c};b.o.uW=function(a){var c=b.o.Ska[a];if(!c)throw"Invalid edge: "+a;return c};b.o.ae=function(){return"rtl"===b.v.im()};b.o.AL=function(a,b){a.css({"-webkit-transform":b,
"-ms-transform":b,transform:b})};b.o.WC=function(a,c,e){c=c===b.o.Su;b.o.ae()&&(c=!c);b.o.AL(a,"translate3d("+(c?"-":"")+e+", 0, 0)")};b.o.Jka=function(a,c,e){b.o.AL(a,"translate3d(0, "+(c===b.o.XE?"-":"")+e+", 0)")};b.o.i_=function(a){var c=a.edge;a=b.o.pi(a);c&&c.length||(c=a.hasClass("oj-offcanvas-start")?b.o.Tu:a.hasClass("oj-offcanvas-end")?b.o.Su:a.hasClass("oj-offcanvas-top")?b.o.pP:a.hasClass("oj-offcanvas-bottom")?b.o.XE:b.o.Tu);f.data(a[0],b.o.NF,c);return c};b.o.HI=function(a){return f.data(a[0],
b.o.NF)};b.o.gD=function(a,c,e){var f=a[b.o.Qu],h=b.o.pi(a),k=b.o.OP,f=f===b.o.oP?b.o.Wm+" oj-offcanvas-overlay":b.o.Wm;e?(e=h.attr("tabIndex"),void 0!==e&&(a.tabIndex=e),h.addClass(k).attr("tabIndex","-1"),c.addClass(f)):(e=a.tabIndex,void 0===e?h.removeAttr("tabIndex"):h.attr("tabIndex",e),h.removeClass(k),c.removeClass(f))};b.o.uga=function(a){return"none"!=a.autoDismiss};b.o.PY=function(a,b){function e(){b();a.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",e)}a.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",
e)};b.o.DZ=function(a){b.o.N0(a);if(b.o.uga(a)){var c=b.o.pi(a),e=a[b.o.gz]=function(e){var g=e.target;b.v.r3(e)||"focus"===e.type&&!f(g).is(":focusable")||b.v.Doa(c[0],g)||b.o.close(a)},g=document.documentElement;b.v.Od()&&g.addEventListener("touchstart",e,!0);g.addEventListener("mousedown",e,!0);g.addEventListener("focus",e,!0)}b.o.IC(a)};b.o.N0=function(a){var c=a[b.o.gz];if(c){var e=document.documentElement;b.v.Od()&&e.removeEventListener("touchstart",c,!0);e.removeEventListener("mousedown",c,
!0);e.removeEventListener("focus",c,!0);delete a[b.o.gz];a[b.o.gz]=null}b.o.oD(a)};b.o.IC=function(d){if(b.v.Od()){var c=d[b.o.ev],e=f(c),g=b.o.HI(e),h,k;g===b.o.Tu&&!b.o.ae()||g===b.o.Su&&b.o.ae()?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_LEFT}]]},h="swipeleft"):g===b.o.Tu&&b.o.ae()||g===b.o.Su&&!b.o.ae()?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_RIGHT}]]},h="swiperight"):g===b.o.pP?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_UP}]]},h="swipeup"):g===b.o.XE&&(k={recognizers:[[a.Swipe,
{direction:a.DIRECTION_DOWN}]]},h="swipedown");e=e.Zk(k).on(h,function(a){a.preventDefault();b.o.close(d)});f.data(f(c)[0],b.o.GQ,{event:h,hammer:e})}};b.o.oD=function(a){a=b.o.pi(a);(a=f.data(a[0],b.o.GQ))&&a.hammer.off(a.event)};b.o.IS=function(a){var c=b.o.pi(a);if(f.data(c[0],b.o.an)===a){b.o.HI(c);var e=b.o.pB(a);b.o.gD(a,e,!1);b.o.rja(a);b.o.N0(a);c.trigger("ojclose",a);f.removeData(c[0],b.o.an)}};b.o.P_=function(a,c,e){var g=f(a);(c=!!c)&&b.o.Sn(g)&&b.o.vl(a,!1);g.toggleClass(b.o.Tba[e],!c)};
b.o.Cpa=function(a){var c=a.query;if(null!==c){var e=a[b.o.ev],c=window.matchMedia(c),g=b.o.i_(a);a=function(a){b.o.P_(e,a.matches,g)};c.addListener(a);b.o.P_(e,c.matches,g);f.data(f(e)[0],b.o.OF,{mqList:c,mqListener:a})}};o_("OffcanvasUtils.setupResponsive",b.o.Cpa,b);b.o.Qpa=function(a){a=b.o.pi(a);var c=f.data(a[0],b.o.OF);c&&(c.mqList.removeListener(c.mqListener),f.removeData(a[0],b.o.OF))};o_("OffcanvasUtils.tearDownResponsive",b.o.Qpa,b);b.o.open=function(a){var c=b.o.pi(a),e=f.data(c[0],b.o.an);
if(e){if(e[b.o.Pu])return e[b.o.Pu];if(e[b.o.rF])return e[b.o.rF]}var e=new Promise(function(e,g){b.l.xd(c,jQuery);var l=b.o.i_(a),m=f.Event("ojbeforeopen");c.trigger(m,a);if(!1===m.result)g("ojbeforeopen veto");else{var n,m=b.o.Tca(a),p=f.extend({},a);p[b.o.Qu]=m;f.data(c[0],b.o.an,p);var r;r=b.o.pB(p);b.l.xd(r,jQuery);b.o.gD(p,r,!0);l===b.o.Tu||l===b.o.Su?(n=void 0===n?c.outerWidth(!0)+"px":n,m===b.o.Ru&&b.o.WC(r,l,n)):(n=void 0===n?c.outerHeight(!0)+"px":n,m===b.o.Ru&&b.o.Jka(r,l,n));var s;window.setTimeout(function(){s=
b.o.Cw(c);b.l.xd(s,jQuery);s.addClass(b.o.uW(l))},10);b.o.a$(p,c);b.o.PY(r,function(){r.removeClass(b.o.Wm);b.pd.ny(c[0]);c.trigger("ojopen",p);b.o.DZ(p);e(!0)})}}),g=f.data(c[0],b.o.an);g&&(g[b.o.rF]=e);return e};o_("OffcanvasUtils.open",b.o.open,b);b.o.close=function(a){return b.o.vl(a[b.o.ev],!0)};o_("OffcanvasUtils.close",b.o.close,b);b.o.vl=function(a,c){var e=f(a);b.l.xd(e,jQuery);var g=f.data(e[0],b.o.an);if(g&&g[b.o.Pu])return g[b.o.Pu];var h=new Promise(function(h,l){if(b.o.Sn(e)){a!=g[b.o.ev]&&
h(!0);var m=b.o.HI(e),n=g[b.o.Qu],m=b.o.uW(m),p=b.o.Cw(e);b.l.xd(p,jQuery);p.hasClass(m)||h(!0);var r=f.Event("ojbeforeclose");e.trigger(r,g);if(!1===r.result)l("beforeClose veto");else{r=b.o.pB(g);if(c){var s=0,q=function(){b.o.IS(g);0!==s&&window.cancelAnimationFrame(s);h(!0)},t=function(){null==e[0].offsetParent?q():s=window.requestAnimationFrame(t)};b.o.PY(r,q);s=window.requestAnimationFrame(t)}n===b.o.Ru&&b.o.AL(r,"");p.removeClass(m);b.o.iK(g)&&g[b.o.hz].removeClass(b.o.wP);c?r.addClass(b.o.Wm):
(b.o.IS(g),h(!0))}}else h(!0)});(g=f.data(e[0],b.o.an))&&(g[b.o.Pu]=h);return h};b.o.toggle=function(a){var c=b.o.pi(a);b.l.xd(c,jQuery);return b.o.Sn(c)?b.o.close(a):b.o.open(a)};o_("OffcanvasUtils.toggle",b.o.toggle,b);b.o.z9=function(a){var c=f("\x3cdiv\x3e");c.addClass(b.o.P5);c.attr("role","presentation");c.attr("aria-hidden","true");c.appendTo(a.parent());c.on("keydown keyup keypress mousedown mouseup mouseover mouseout click focusin focus",function(a){a.stopPropagation();a.preventDefault()});
return c};b.o.MH=function(a){var c=f("\x3cscript\x3e"),e=a.attr("id");e?(e=[e,"surrogate"].join("_"),c.attr("id",e)):e=c.uniqueId();c.insertBefore(a);a.attr(b.o.uF,e);return c};b.o.ila=function(a,c){a[b.o.bQ]=b.o.MH(c);c.appendTo(c.parent())};b.o.Qja=function(a){var c=b.o.pi(a);a=a[b.o.bQ];c&&a&&c.attr(b.o.uF)===a.attr("id")&&(c.insertAfter(a),c.removeAttr(b.o.uF),a.remove())};b.o.a$=function(a,c){b.o.iK(a)&&(a[b.o.hz]=b.o.z9(c),b.o.ila(a,c),window.setTimeout(function(){a[b.o.hz].addClass(b.o.wP)},
0))};b.o.rja=function(a){b.o.iK(a)&&(a[b.o.hz].remove(),b.o.Qja(a))};b.o.O4=function(d){var c,e,g,h,k,l,m,n,p,r,s,q;null==f(d).attr("oj-data-pansetup")&&(f(d).attr("oj-data-pansetup","true"),d.displayMode="push",c=b.o.pi(d),e=d.size,null==e&&(e=c.outerWidth()),g=b.o.Cw(c),h=b.o.pB(d),k={recognizers:[[a.Pan,{direction:a.DIRECTION_HORIZONTAL}]]},l=!1,f(g).Zk(k).on("panstart",function(e){switch(e.gesture.direction){case a.DIRECTION_LEFT:m=b.o.ae()?"end":"start";break;case a.DIRECTION_RIGHT:m=b.o.ae()?
"start":"end"}n={direction:m,distance:Math.abs(e.gesture.deltaX)};p=f.Event("ojpanstart");c.trigger(p,n);p.isDefaultPrevented()||(d._closePromise=null,b.o.gD(d,h,!0),l=!0)}).on("panmove",function(a){l&&(r=Math.abs(a.gesture.deltaX),c.css("width",r),h.removeClass(b.o.Wm),b.o.WC(h,"start",a.gesture.deltaX+"px"),n={direction:m,distance:r},p=f.Event("ojpanmove"),c.trigger(p,n))}).on("panend",function(a){l&&(l=!1,r=Math.abs(a.gesture.deltaX),n={distance:r},p=f.Event("ojpanend"),c.trigger(p,n),p.isDefaultPrevented()?
(q=function(){b.o.gD(d,h,!1);h.removeClass(b.o.Wm);h.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",q)},h.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",q),h.addClass(b.o.Wm),b.o.WC(h,"start","0px")):(h.addClass(b.o.Wm),c.css("width",e+"px"),s=d.edge,null==s&&(s=c.hasClass("oj-offcanvas-start")?"start":"end"),b.o.WC(h,s,e+"px"),f.data(c[0],b.o.an,d),f.data(c[0],b.o.NF,s),b.o.DZ(d)))}))};o_("OffcanvasUtils.setupPanToReveal",b.o.O4,b);b.o.b5=function(a){a=
b.o.pi(a);f(b.o.Cw(a)).off("panstart panmove panend")};o_("OffcanvasUtils.tearDownPanToReveal",b.o.b5,b)});