/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojpagingtabledatasource"],function(b){b.ue=function(b,a){this.mr=b;this.sm=a};o_("PagingHeaderSet",b.ue,b);b.ue.prototype.getData=function(b,a){return this.mr.getData(b+this.sm,a)};b.b.g("PagingHeaderSet.prototype.getData",{getData:b.ue.prototype.getData});b.ue.prototype.getMetadata=function(b,a){return this.mr.getMetadata(b+this.sm,a)};b.b.g("PagingHeaderSet.prototype.getMetadata",{getMetadata:b.ue.prototype.getMetadata});b.ue.prototype.R=function(){return this.mr.R()};
b.b.g("PagingHeaderSet.prototype.getCount",{R:b.ue.prototype.R});b.ue.prototype.pg=function(){return this.mr.pg()};b.b.g("PagingHeaderSet.prototype.getLevelCount",{pg:b.ue.prototype.pg});b.ue.prototype.Rb=function(b,a){return this.mr.Rb(b+this.sm,a)};b.b.g("PagingHeaderSet.prototype.getExtent",{Rb:b.ue.prototype.Rb});b.ue.prototype.ie=function(b,a){return this.mr.ie(b+this.sm,a)};b.b.g("PagingHeaderSet.prototype.getDepth",{ie:b.ue.prototype.ie});b.ue.prototype.x2=function(){return this.mr};b.b.g("PagingHeaderSet.prototype.getHeaderSet",
{x2:b.ue.prototype.x2});b.ue.prototype.vy=function(){return this.sm};b.b.g("PagingHeaderSet.prototype.getStartIndex",{vy:b.ue.prototype.vy});b.Ka=function(f){if(!(f instanceof b.Om))throw new b.X("Not a datagridatasource","Not a datagridatasource",b.X.Qb.ERROR);this.sc=f;this.$=0;this.Init()};o_("PagingDataGridDataSource",b.Ka,b);b.b.ga(b.Ka,b.Om,"oj.PagingDataGridDataSource");b.Ka.prototype.Init=function(){b.Ka.q.Init.call(this);this.$K()};b.b.g("PagingDataGridDataSource.prototype.Init",{Init:b.Ka.prototype.Init});
b.Ka.prototype.$K=function(){this.sc.on("change",this.rea.bind(this))};b.Ka.prototype.getPage=function(){return this.Kc};b.b.g("PagingDataGridDataSource.prototype.getPage",{getPage:b.Ka.prototype.getPage});b.Ka.prototype.setPage=function(f,a){a=a||{};f=parseInt(f,10);try{b.Ka.q.handleEvent.call(this,b.$b.D.BEFOREPAGE,{page:f,previousPage:this.Kc})}catch(d){return Promise.reject(null)}this.La=null!=a.pageSize?a.pageSize:this.La;a.startIndex=f*this.La;var c=this.Kc;this.Kc=f;this.$=a.startIndex;var e=
this;return new Promise(function(b,d){e.Ae(a).then(function(){b(null)},function(){e.Kc=c;e.$=e.Kc*e.La;d(null)})})};b.b.g("PagingDataGridDataSource.prototype.setPage",{setPage:b.Ka.prototype.setPage});b.Ka.prototype.Ae=function(b){this.Ml=!0;this.$=b.startIndex;var a=this;return new Promise(function(b){a.handleEvent("change",{operation:"sync",pageSize:a.La});b(void 0)})};b.Ka.prototype.fetch=function(b){this.La=b.pageSize+b.startIndex;b.startIndex=0;return this.Ae(b)};b.b.g("PagingDataGridDataSource.prototype.fetch",
{fetch:b.Ka.prototype.fetch});b.Ka.prototype.getStartItemIndex=function(){return this.$};b.b.g("PagingDataGridDataSource.prototype.getStartItemIndex",{getStartItemIndex:b.Ka.prototype.getStartItemIndex});b.Ka.prototype.getEndItemIndex=function(){return this.gj};b.b.g("PagingDataGridDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.Ka.prototype.getEndItemIndex});b.Ka.prototype.getPageCount=function(){var b=this.totalSize();return-1==b?-1:Math.ceil(b/this.La)};b.b.g("PagingDataGridDataSource.prototype.getPageCount",
{getPageCount:b.Ka.prototype.getPageCount});b.Ka.prototype.rea=function(f){switch(f.operation){case "refresh":this.$=0;this.handleEvent("change",{operation:"sync",pageSize:this.La});this.handleEvent(b.ka.D.REFRESH,null);break;case "reset":this.handleEvent(b.ka.D.RESET,null);break;case "insert":this.handleEvent(b.ka.D.ADD,{index:f.indexes.row});break;case "delete":this.handleEvent(b.ka.D.REMOVE,null);break;case "update":f.indexes.row=0<=f.indexes.row-this.$?f.indexes.row-this.$:-1;this.handleEvent("change",
f);break;default:this.handleEvent("change",f),this.handleEvent(b.ka.D.SYNC,null)}};b.Ka.prototype.R=function(b){var a=this.sc.R(b);return"row"===b&&0<=a?this.$+this.La<a?this.La:a-this.$:a};b.b.g("PagingDataGridDataSource.prototype.getCount",{R:b.Ka.prototype.R});b.Ka.prototype.og=function(b){return this.sc.og(b)};b.b.g("PagingDataGridDataSource.prototype.getCountPrecision",{og:b.Ka.prototype.og});b.Ka.prototype.Gf=function(f,a,d){var c;null==this.Ml?(c=new b.Cd(0,0,f.axis,null),null!=a&&a.success&&
a.success.call(d.success,c,f)):"row"===f.axis?(f.start+=this.$,f.start+f.count>this.$+this.La&&(f.count=this.La-f.start),this.Jt={callbacks:a,callbackObjects:d},this.sc.Gf(f,{success:this.KJ.bind(this),error:this.sfa.bind(this)},d)):this.sc.Gf(f,a,d)};b.b.g("PagingDataGridDataSource.prototype.fetchHeaders",{Gf:b.Ka.prototype.Gf});b.Ka.prototype.KJ=function(f,a){var d,c,e;a.start-=this.$;a.count+=1;d=new b.ue(f,this.$);c=this.Jt.callbacks.success;e=this.Jt.callbackObjects.success;this.Jt=null;c.call(e,
d,a)};b.Ka.prototype.sfa=function(b){var a,d;a=this.Jt.callbacks.error;d=this.Jt.callbackObjects.error;this.Jt=null;a.call(d,b)};b.Ka.prototype.ng=function(f,a,d){var c;if(null==this.Ml)c=new b.Qf(0,0,0,0,null),null!=a&&a.success&&a.success.call(d.success,c,f);else{for(c=0;c<f.length;c+=1)"row"===f[c].axis&&(f[c].start+=this.$,f[c].start+f[c].count>this.$+this.La&&(f[c].count=this.La-f[c].start));this.Ht={callbacks:a,callbackObjects:d};this.sc.ng(f,{success:this.qea.bind(this),error:this.pea.bind(this)},
d)}};b.b.g("PagingDataGridDataSource.prototype.fetchCells",{ng:b.Ka.prototype.ng});b.Ka.prototype.qea=function(f,a){var d,c,e;for(d=0;d<a.length;d+=1)"row"===a[d].axis&&(a[d].start-=this.$,a[d].count+=1);d=new b.Yh(f,this.$);c=this.Ht.callbacks.success;e=this.Ht.callbackObjects.success;this.Ht=null;this.gj=this.$+f.R("row")-1;this.handleEvent("sync",{data:Array(f.R("row")),startIndex:this.$});c.call(e,d,a)};b.Ka.prototype.pea=function(b){var a,d;a=this.Ht.callbacks.error;d=this.Ht.callbackObjects.error;
this.Ht=null;a.call(d,b)};b.Ka.prototype.keys=function(b){return this.sc.keys({column:b.column,row:b.row+this.$})};b.b.g("PagingDataGridDataSource.prototype.keys",{keys:b.Ka.prototype.keys});b.Ka.prototype.tg=function(b){b=this.sc.tg(b);-1!=b.row&&(b.row-=this.$);return b};b.b.g("PagingDataGridDataSource.prototype.indexes",{tg:b.Ka.prototype.tg});b.Ka.prototype.getCapability=function(b){return this.sc.getCapability(b)};b.b.g("PagingDataGridDataSource.prototype.getCapability",{getCapability:b.Ka.prototype.getCapability});
b.Ka.prototype.size=function(){var b;if(null==this.Ml)return-1;b=this.sc.R("row");return this.sc.R("row")>this.La?this.La:b};b.b.g("PagingDataGridDataSource.prototype.size",{size:b.Ka.prototype.size});b.Ka.prototype.sort=function(b,a,d){this.sc.sort(b,a,d)};b.b.g("PagingDataGridDataSource.prototype.sort",{sort:b.Ka.prototype.sort});b.Ka.prototype.totalSize=function(){return null==this.Ml?-1:this.sc.R("row")};b.b.g("PagingDataGridDataSource.prototype.totalSize",{totalSize:b.Ka.prototype.totalSize});
b.Ka.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("PagingDataGridDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.Ka.prototype.totalSizeConfidence});b.Ka.prototype.md=function(b,a,d){return this.sc.md(b,a,d)};b.b.g("PagingDataGridDataSource.prototype.moveOK",{md:b.Ka.prototype.md});b.Ka.prototype.move=function(b,a,d,c,e){this.sc.move(b,a,d,c,e)};b.b.g("PagingDataGridDataSource.prototype.move",{move:b.Ka.prototype.move});b.Yh=function(b,a){this.lE=b;this.sm=a};o_("PagingCellSet",
b.Yh,b);b.Yh.prototype.getData=function(b){return this.lE.getData({column:b.column,row:b.row+this.sm})};b.b.g("PagingCellSet.prototype.getData",{getData:b.Yh.prototype.getData});b.Yh.prototype.getMetadata=function(b){return this.lE.getMetadata({column:b.column,row:b.row+this.sm})};b.b.g("PagingCellSet.prototype.getMetadata",{getMetadata:b.Yh.prototype.getMetadata});b.Yh.prototype.R=function(b){return this.lE.R(b)};b.b.g("PagingCellSet.prototype.getCount",{R:b.Yh.prototype.R});b.Yh.prototype.i2=function(){return this.lE};
b.b.g("PagingCellSet.prototype.getCellSet",{i2:b.Yh.prototype.i2});b.Yh.prototype.vy=function(){return this.sm};b.b.g("PagingCellSet.prototype.getStartIndex",{vy:b.Yh.prototype.vy})});