/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b){b.ka=function(f){if(!(f instanceof b.T))throw Error(b.T.dc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.dc._ERR_DATA_INVALID_TYPE_DETAIL);this.sc=f;this.gj=this.$=0;this.Init()};o_("PagingTableDataSource",b.ka,b);b.b.ga(b.ka,b.T,"oj.PagingTableDataSource");b.ka.prototype.Init=function(){b.ka.q.Init.call(this)};b.b.g("PagingTableDataSource.prototype.Init",{Init:b.ka.prototype.Init});b.ka.prototype.getWrappedDataSource=function(){return this.sc};
b.b.g("PagingTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:b.ka.prototype.getWrappedDataSource});b.ka.prototype.getPage=function(){return"loadMore"==this.dB?0:this.GB()};b.b.g("PagingTableDataSource.prototype.getPage",{getPage:b.ka.prototype.getPage});b.ka.prototype.setPage=function(f,a){a=a||{};f=parseInt(f,10);try{b.ka.q.handleEvent.call(this,b.$b.D.BEFOREPAGE,{page:f,previousPage:this.GB()})}catch(d){return Promise.reject(null)}var c=this.GB();this.La=null!=a.pageSize?a.pageSize:
this.La;a.pageSize=this.La;a.startIndex=f*this.La;this.$=null==a.startIndex?this.$:a.startIndex;this.dB="page";var e=this;return new Promise(function(d,f){0<e.La?e.sc.fetch(a).then(function(a){a.startIndex=0;e.rD();b.ka.q.handleEvent.call(e,b.$b.D.PAGE,{page:e.GB(),previousPage:c});d(null)},function(){e.$=c*e.La;f(null)}):d(null)})};b.b.g("PagingTableDataSource.prototype.setPage",{setPage:b.ka.prototype.setPage});b.ka.prototype.getStartItemIndex=function(){return"loadMore"==this.dB?0:this.$};b.b.g("PagingTableDataSource.prototype.getStartItemIndex",
{getStartItemIndex:b.ka.prototype.getStartItemIndex});b.ka.prototype.getEndItemIndex=function(){return this.gj};b.b.g("PagingTableDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.ka.prototype.getEndItemIndex});b.ka.prototype.getPageCount=function(){var b=this.totalSize();return-1==b?-1:Math.ceil(b/this.La)};b.b.g("PagingTableDataSource.prototype.getPageCount",{getPageCount:b.ka.prototype.getPageCount});b.ka.prototype.at=function(b,a){return this.sc.at(b,a)};b.b.g("PagingTableDataSource.prototype.at",
{at:b.ka.prototype.at});b.ka.prototype.fetch=function(b){b=b||{};if(null==b.startIndex)return this.setPage(this.getPage());this.dB="loadMore";this.$=null==b.startIndex?this.$:b.startIndex;var a=null!=b.pageSize?b.pageSize:this.La;b.pageSize=a;b.startIndex=this.$;var d=this;return new Promise(function(c,e){0<a?d.sc.fetch(b).then(function(a){d.rD();c(a)},function(a){e(a)}):c(null)})};b.b.g("PagingTableDataSource.prototype.fetch",{fetch:b.ka.prototype.fetch});b.ka.prototype.get=function(b,a){return this.sc.get(b,
a)};b.b.g("PagingTableDataSource.prototype.get",{get:b.ka.prototype.get});b.ka.prototype.getCapability=function(b){return this.sc.getCapability(b)};b.b.g("PagingTableDataSource.prototype.getCapability",{getCapability:b.ka.prototype.getCapability});b.ka.prototype.on=function(f,a){var d=this,c=this.sc;if(f==b.T.D.SYNC){var e=function(b){d.yfa(b,a)};c.on(f,e);return e}if(f==b.T.D.ADD||f==b.T.D.REMOVE||f==b.T.D.CHANGE)return e=function(b){d.rfa(b,a)},c.on(f,e),e;if(f==b.T.D.REFRESH||f==b.T.D.RESET)return e=
function(b){d.$=0;a(b)},c.on(f,e),e;if(f==b.$b.D.PAGE||f==b.$b.D.PAGECOUNT)b.ka.q.on.call(this,f,a);else c.on(f,a);return a};b.b.g("PagingTableDataSource.prototype.on",{on:b.ka.prototype.on});b.ka.prototype.off=function(f,a){return f==b.$b.D.PAGE||f==b.$b.D.PAGECOUNT?(b.ka.q.off.call(this,f,a),a):this.sc.off(f,a)};b.b.g("PagingTableDataSource.prototype.off",{off:b.ka.prototype.off});b.ka.prototype.sort=function(b){return this.sc.sort(b)};b.b.g("PagingTableDataSource.prototype.sort",{sort:b.ka.prototype.sort});
b.ka.prototype.totalSize=function(){return this.sc.totalSize()};b.b.g("PagingTableDataSource.prototype.totalSize",{totalSize:b.ka.prototype.totalSize});b.ka.prototype.totalSizeConfidence=function(){return this.sc.totalSizeConfidence()};b.b.g("PagingTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.ka.prototype.totalSizeConfidence});b.ka.prototype.GB=function(){return 0<this.La?Math.floor(this.$/this.La):0};b.ka.prototype.rfa=function(b,a){var d=[],c;for(c=0;c<b.indexes.length;c++){var e=
b.indexes[c];void 0!==e&&(e-=this.$,(0>e||e>=this.$+this.La)&&d.push(c))}if(0<d.length)for(d.sort(function(a,b){return a-b}),c=d.length-1;0<=c;c--)b.data.splice(d[c],1),b.indexes.splice(d[c],1),b.keys.splice(d[c],1);this.rD();b.startIndex=this.$;a(b)};b.ka.prototype.yfa=function(f,a){f.startIndex!=this.$&&(this.$=f.startIndex);this.rD();if("page"==this.dB){var d={};b.lc.Xe(d,f);d.startIndex=0;a(d)}else a(f)};b.ka.prototype.rD=function(){var b=this.totalSize();this.gj=this.$+this.La-1;0<b&&(this.gj=
this.gj>b-1?b-1:this.gj)};b.ka.D={ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh",SORT:"sort"};o_("PagingTableDataSource.EventType",b.ka.D,b);b.$b=function(){};o_("PagingModel",b.$b,b);b.$b.prototype.getPage=function(){};b.b.g("PagingModel.prototype.getPage",{getPage:b.$b.prototype.getPage});b.$b.prototype.setPage=function(){};b.b.g("PagingModel.prototype.setPage",{setPage:b.$b.prototype.setPage});b.$b.prototype.getStartItemIndex=function(){};b.b.g("PagingModel.prototype.getStartItemIndex",
{getStartItemIndex:b.$b.prototype.getStartItemIndex});b.$b.prototype.getEndItemIndex=function(){};b.b.g("PagingModel.prototype.getEndItemIndex",{getEndItemIndex:b.$b.prototype.getEndItemIndex});b.$b.prototype.getPageCount=function(){};b.b.g("PagingModel.prototype.getPageCount",{getPageCount:b.$b.prototype.getPageCount});b.$b.prototype.totalSize=function(){};b.b.g("PagingModel.prototype.totalSize",{totalSize:b.$b.prototype.totalSize});b.$b.prototype.totalSizeConfidence=function(){};b.b.g("PagingModel.prototype.totalSizeConfidence",
{totalSizeConfidence:b.$b.prototype.totalSizeConfidence});b.$b.D={BEFOREPAGE:"beforePage",PAGE:"page",PAGECOUNT:"pageCount"};o_("PagingModel.EventType",b.$b.D,b)});