/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","hammerjs","ojs/ojpagingtabledatasource","ojs/ojinputtext","ojs/ojjquery-hammer"],function(b,f,a,d){(function(){b.ya("oj.ojPagingControl",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,overflow:"fit",pageSize:25,pageOptions:{layout:["auto"],type:"numbers",maxPageLinks:6,orientation:"horizontal"},loadMoreOptions:{maxCount:500},mode:"page",ready:null},xa:{L7:"labelAccPaging",G7:"labelAccNavFirstPage",
H7:"labelAccNavLastPage",I7:"labelAccNavNextPage",K7:"labelAccNavPreviousPage",J7:"labelAccNavPage",M7:"labelLoadMore",N7:"labelLoadMoreMaxRows",mR:"labelNavInputPage",XF:"labelNavInputPageMax",wqa:"labelNavInputPageSummary",qR:"msgItemRangeCurrent",rR:"msgItemRangeCurrentSingle",sR:"msgItemRangeItems",b8:"msgItemRangeOfAtLeast",a8:"msgItemRangeOfApprox",c8:"msgItemRangeOf",lS:"tipNavInputPage",i9:"tipNavPageLink",nS:"tipNavNextPage",oS:"tipNavPreviousPage",kS:"tipNavFirstPage",mS:"tipNavLastPage",
qp:"pageInvalid.summary",rqa:"pageInvalid.detail",RQ:"dataInvalidType.summary",QQ:"dataInvalidType.detail",m7:"maxPageLinksInvalid.summary",l7:"maxPageLinksInvalid.detail"},Ca:{EG:"oj-component",gf:"oj-active",op:"oj-clickable-icon-nocontext",tb:"oj-disabled",kf:"oj-enabled",Zi:"oj-focus",Xj:"oj-hover",bd:"oj-selected"},O:{l8:"oj-pagingcontrol",FR:"oj-pagingcontrol-acc-label",GR:"oj-pagingcontrol-content",IR:"oj-pagingcontrol-loadmore",Sz:"oj-pagingcontrol-loadmore-link",fG:"oj-pagingcontrol-loadmore-max-rows",
Tz:"oj-pagingcontrol-loadmore-range",gG:"oj-pagingcontrol-loadmore-range-current",hG:"oj-pagingcontrol-loadmore-range-max",KR:"oj-pagingcontrol-nav",Uz:"oj-pagingcontrol-nav-arrow",JR:"oj-pagingcontrol-nav-arrow-section",kG:"oj-pagingcontrol-nav-page",y8:"oj-pagingcontrol-nav-page-ellipsis",n8:"oj-pagingcontrol-nav-dot",m8:"oj-pagingcontrol-nav-dot-bullet",x8:"oj-pagingcontrol-nav-page-acc-label",MR:"oj-pagingcontrol-nav-label",LR:"oj-pagingcontrol-nav-input-section",Ap:"oj-pagingcontrol-nav-input",
zv:"oj-pagingcontrol-nav-input-max",Av:"oj-pagingcontrol-nav-input-summary",iG:"oj-pagingcontrol-nav-input-summary-current",jG:"oj-pagingcontrol-nav-input-summary-max",OR:"oj-pagingcontrol-nav-pages-section",NR:"oj-pagingcontrol-nav-pages-links",ns:"oj-pagingcontrol-nav-first",o8:"oj-pagingcontrol-nav-first-acc-label",rs:"oj-pagingcontrol-nav-previous",z8:"oj-pagingcontrol-nav-previous-acc-label",qs:"oj-pagingcontrol-nav-next",u8:"oj-pagingcontrol-nav-next-acc-label",ps:"oj-pagingcontrol-nav-last",
r8:"oj-pagingcontrol-nav-last-acc-label",p8:"oj-pagingcontrol-nav-first-icon",A8:"oj-pagingcontrol-nav-previous-icon",v8:"oj-pagingcontrol-nav-next-icon",s8:"oj-pagingcontrol-nav-last-icon",q8:"oj-pagingcontrol-nav-first-vertical-icon",B8:"oj-pagingcontrol-nav-previous-vertical-icon",w8:"oj-pagingcontrol-nav-next-vertical-icon",t8:"oj-pagingcontrol-nav-last-vertical-icon",Gp:"oj-component-icon",gi:"oj-helper-hidden-accessible"},FQ:"data-oj-pagenum",Ng:"enabled",kn:"disabled",Pg:"tabindex",$j:{dn:"loadMore",
ER:"page"},pf:{Lg:"auto",mv:"all",Iz:"input",D8:"rangeText",j8:"pages",tR:"nav"},k8:6,fA:{yqa:"numbers",e7:"dots"},firstPage:function(){return null!=this.Ya()?this.si(0,!1):this.gt()},previousPage:function(){if(null!=this.Ya()){var a=this.uf();if(0<a)return this.si(a-1,!1)}return this.gt()},nextPage:function(){if(null!=this.Ya()){var a=this.uf();if(a+1<=this.Kd()-1||0>this.Kd())return this.si(a+1,!1)}return this.gt()},lastPage:function(){return null!=this.Ya()&&0<this.Kd()?this.si(this.Kd()-1,!1):
this.gt()},page:function(a){return null!=this.Ya()&&(this.Yg()&&a<=this.Kd()-1||0>this.Kd()||!this.Yg())?this.si(a,!1):this.gt()},loadNext:function(){return null!=this.Ya()?this.sga():this.gt()},refresh:function(){this._super();this.Ld()},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId,d=null;"oj-pagingcontrol-nav-input"===b?d=this.Jd().find("."+this.O.Ap)[0]:"oj-pagingcontrol-nav-input-max"===b?d=this.Jd().find("."+this.O.zv)[0]:"oj-pagingcontrol-nav-input-summary"===
b?d=this.Jd().find("."+this.O.Av)[0]:"oj-pagingcontrol-nav-input-summary-current"===b?d=this.Jd().find("."+this.O.iG)[0]:"oj-pagingcontrol-nav-input-summary-max"===b?d=this.Jd().find("."+this.O.jG)[0]:"oj-pagingcontrol-nav-first"===b?d=this.Jd().find("."+this.O.ns)[0]:"oj-pagingcontrol-nav-next"===b?d=this.Jd().find("."+this.O.qs)[0]:"oj-pagingcontrol-nav-previous"===b?d=this.Jd().find("."+this.O.rs)[0]:"oj-pagingcontrol-nav-last"===b?d=this.Jd().find("."+this.O.ps)[0]:"oj-pagingcontrol-nav-page"===
b?(a=a.index,d=this.Jd().find("["+this.FQ+"\x3d"+a+"]")[0]):"oj-pagingcontrol-load-more-link"===b?d=this.Jd().find("."+this.O.Sz)[0]:"oj-pagingcontrol-load-more-range"===b?d=this.Jd().find("."+this.O.Tz)[0]:"oj-pagingcontrol-load-more-range-current"===b?d=this.Jd().find("."+this.O.gG)[0]:"oj-pagingcontrol-load-more-range-max"===b?d=this.Jd().find("."+this.O.hG)[0]:"oj-pagingcontrol-load-more-max-rows"===b&&(d=this.Jd().find("."+this.O.fG)[0]);void 0===d&&(d=null);return d},getSubIdByNode:function(a){return f(a).hasClass(this.O.Ap)?
{subId:"oj-pagingcontrol-nav-input"}:f(a).hasClass(this.O.zv)?{subId:"oj-pagingcontrol-nav-input-max"}:f(a).hasClass(this.O.Av)?{subId:"oj-pagingcontrol-nav-input-summary"}:f(a).hasClass(this.O.iG)?{subId:"oj-pagingcontrol-nav-input-summary-current"}:f(a).hasClass(this.O.jG)?{subId:"oj-pagingcontrol-nav-input-summary-max"}:f(a).hasClass(this.O.ns)?{subId:"oj-pagingcontrol-nav-first"}:f(a).hasClass(this.O.qs)?{subId:"oj-pagingcontrol-nav-next"}:f(a).hasClass(this.O.rs)?{subId:"oj-pagingcontrol-nav-previous"}:
f(a).hasClass(this.O.ps)?{subId:"oj-pagingcontrol-nav-last"}:f(a).hasClass(this.O.kG)?{subId:"oj-pagingcontrol-nav-page",index:f(a).attr(this.FQ)}:f(a).hasClass(this.O.Sz)?{subId:"oj-pagingcontrol-load-more-link"}:f(a).hasClass(this.O.Tz)?{subId:"oj-pagingcontrol-load-more-range"}:f(a).hasClass(this.O.gG)?{subId:"oj-pagingcontrol-load-more-range-current"}:f(a).hasClass(this.O.hG)?{subId:"oj-pagingcontrol-load-more-range-max"}:f(a).hasClass(this.O.fG)?{subId:"oj-pagingcontrol-load-more-max-rows"}:
null},_ComponentCreate:function(){this._super();this.Eq();this.kw();this.tj(this.Jd());this._on(this.Cl)},hf:function(){this._super();this.IC();this.si(0,!0)},_destroy:function(){this.Dk();this.oD()},kw:function(){var a=this.options;this.element.addClass(this.O.l8);this.element.addClass(this.Ca.EG);this.Maa();this.Saa();this.EY=a.mode;a.mode==this.$j.dn?(this.YT(),this.ZT(),this.$T()):this.aU()},Cl:{"mouseup .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();f(a.target).data("_mouseup",
!0);a.preventDefault()},"click .oj-pagingcontrol-loadmore-link":function(a){f(a.target).data("_mouseup")?f(a.target).data("_mouseup",!1):this.loadNext();a.preventDefault()},"click .oj-pagingcontrol-nav-dot":function(a){var d=f(a.currentTarget).attr("data-oj-pagenum"),g=this;this.page(d).then(function(){},function(a){var c=g.A(g.xa.qp);b.r.error(c+"\n"+a)});a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var d=f(a.currentTarget).attr("data-oj-pagenum"),g=this;this.page(d).then(function(){},
function(a){var c=g.A(g.xa.qp);b.r.error(c+"\n"+a)});a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){if(!f(a.currentTarget).hasClass(this.Ca.tb)){var d=this;this.firstPage().then(function(){},function(a){var c=d.A(d.xa.qp);b.r.error(c+"\n"+a)})}a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){if(!f(a.currentTarget).hasClass(this.Ca.tb)){var d=this;this.previousPage().then(function(){},function(a){var c=d.A(d.xa.qp);b.r.error(c+"\n"+a)})}a.preventDefault()},
"click .oj-pagingcontrol-nav-next":function(a){if(!f(a.currentTarget).hasClass(this.Ca.tb)){var d=this;this.nextPage().then(function(){},function(a){var c=d.A(d.xa.qp);b.r.error(c+"\n"+a)})}a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){if(!f(a.currentTarget).hasClass(this.Ca.tb)){var d=this;this.lastPage().then(function(){},function(a){var c=d.A(d.xa.qp);b.r.error(c+"\n"+a)})}a.preventDefault()},"keypress .oj-pagingcontrol-nav-input":function(a){13==a.which&&a.preventDefault()},
"mousedown .oj-pagingcontrol-nav-first":function(a){f(a.currentTarget).hasClass(this.Ca.tb)||f(a.target).addClass(this.Ca.gf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(a){f(a.currentTarget).hasClass(this.Ca.tb)||f(a.target).addClass(this.Ca.gf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(a){f(a.currentTarget).hasClass(this.Ca.tb)||f(a.target).addClass(this.Ca.gf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(a){f(a.currentTarget).hasClass(this.Ca.tb)||
f(a.target).addClass(this.Ca.gf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.gf);
a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.gf);a.preventDefault()}},Ld:function(){this.i!=this.options.data&&(this.wH(),this.si(0,!0));var a=0,b=0;null!=this.i&&(b=this.i.getStartItemIndex());null!=this.i&&0!=this.i.totalSize()&&
0<=this.i.getEndItemIndex()&&(a=this.i.getEndItemIndex()-b+1);if(this.EY!=this.options.mode)this.EY=this.options.mode,this.options.mode==this.$j.dn?this.sZ(a,b):this.tZ(a,b);else if(this.options.mode==this.$j.dn){var d=this.Ya(),f=this.et();null!=d&&(b+a==d.totalSize()&&this.Yg()||0==d.totalSize())?f.css("display","none"):this.sZ(a,b)}else this.tZ(a,b)},_setOption:function(a,b){this._superApply(arguments);this.si(0,!0);if(this.options.mode!=this.$j.dn&&"pageOptions"==a){var d=this.ri();null!=d&&(this.oM(d),
this.oD(),d.empty());this.W$();this.aU();this.IC()}this.Ld()},wH:function(){null!=this.i&&this.Dk();this.i=null},V$:function(){this.cH=this.bH=this.aH=null},W$:function(){this.fH=this.eH=this.dH=null},uf:function(){var a=this.Ya(),b=0;null!=a&&(b=a.getPage());return b},Ya:function(){this.i||null==this.options.data||(this.i=this.options.data,this.Eq());return this.i},SI:function(a,b){var d=0<=b?b:0,h=f(document.createElement("span")),k=f(document.createElement("span"));this.options.mode==this.$j.dn?
k.addClass(this.O.gG):k.addClass(this.O.iG);h.append(k);var l=this.Ya();if(null!=l&&null!=l.totalSize()&&null!=a){var m=this.A(this.xa.rR,{pageFrom:d}),m=parseInt(b,10)+parseInt(a,10),d=0<m?d+1:0;if(-1!=l.totalSize()){var m=m>l.totalSize()?l.totalSize():m,m=d==m?this.A(this.xa.rR,{pageFrom:d}):this.A(this.xa.qR,{pageFrom:d,pageTo:m}),d=this.A(this.xa.c8),n=null;"atLeast"==l.totalSizeConfidence()?n=this.A(this.xa.b8):"estimate"==l.totalSizeConfidence()&&(n=this.A(this.xa.a8));var p=f(document.createElement("span"));
null==n?p.text(" "+d+" "):p.text(" "+n+" ");h.append(p);d=f(document.createElement("span"));this.options.mode==this.$j.dn?d.addClass(this.O.hG):d.addClass(this.O.jG);d.text(l.totalSize());h.append(d)}else m=this.A(this.xa.qR,{pageFrom:d,pageTo:m});l=this.A(this.xa.sR);d=f(document.createElement("span"));d.text(" "+l);h.append(d);k.text(m)}return h},YV:function(){var a=this.options.pageOptions.maxPageLinks;this.options.pageOptions.type==this.fA.e7?a=Number.MAX_VALUE:a||(a=this.k8);return a},ZV:function(a){var b=
0;0<this.Kd()&&this.Yg()?b=this.Kd():0<a?(a=this.Ya(),b=null==a||"atLeast"!=a.totalSizeConfidence()&&"estimate"!=a.totalSizeConfidence()?this.uf()+2:this.Kd()+1):b=this.uf()+1;return b},gt:function(){return Promise.reject()},Kd:function(){var a=this.Ya(),b=0;null!=a&&(b=a.getPageCount());return-1<=b?b:0},AJ:function(){var a=f(document.activeElement);if(a.hasClass(this.O.kG)){var b=a.attr("data-oj-pagenum"),d=this;setTimeout(function(){0<=b&&d.ri().find("div[data-oj-pagenum\x3d"+b+"]").focus()},100)}else a.hasClass(this.O.ns)?
(d=this,setTimeout(function(){d.ri().find("."+d.O.ns).focus()},100)):a.hasClass(this.O.rs)?(d=this,setTimeout(function(){d.ri().find("."+d.O.rs).focus()},100)):a.hasClass(this.O.qs)?(d=this,setTimeout(function(){d.ri().find("."+d.O.qs).focus()},100)):a.hasClass(this.O.ps)?(d=this,setTimeout(function(){d.ri().find("."+d.O.ps).focus()},100)):a.hasClass(this.O.Ap)&&(d=this,setTimeout(function(){d.ri().find("."+d.O.Ap).focus()},100));this.Mt()},Aea:function(a){a.page!=a.previousPage&&this.Mt()},Mn:function(){this.si(0,
!1)},SB:function(){this.Mt()},DJ:function(a){this.options.mode==this.$j.dn&&this.Mn(a)},BJ:function(a){this.options.mode==this.$j.ER&&this.VX(a)?this.si(this.uf(),!0):this.Mt()},CJ:function(a){0<this.Kd()&&this.uf()>this.Kd()-1?this.si(this.Kd()-1,!0):this.VX(a)?this.si(this.uf(),!0):this.Mt()},nfa:function(a,d){var g=d.value;if(g!=this.uf()+1&&!isNaN(g)&&0<g){var g=Math.round(g),f=this;this.page(g-1).then(function(){},function(a){var c=f.A(f.xa.qp);b.r.error(c+"\n"+a)})}},si:function(a,b){try{a=
parseInt(a,10)}catch(d){return Promise.reject(d)}this.Dh=0;if(b)return this.Gia(a),Promise.resolve();var f=this.Ya(),k=this;return new Promise(function(b,d){null!=f?f.setPage(a,{pageSize:k.options.pageSize}).then(function(){b(null)},function(a){d(a)}):b(null)})},sga:function(){var a=this.Ya(),b=this.options.pageSize;this.Dh=this.Dh?this.Dh+b:b;if(!this.Yg()||a.totalSize()>this.Dh&&this.Yg()){var d=this;return new Promise(function(f,k){a.fetch({startIndex:d.Dh,pageSize:b}).then(function(a){f(a)},function(){k(null)})})}return Promise.resolve()},
VX:function(a){var b=this.Ya(),d=this.options.pageSize,f;for(f=0;f<a.indexes.length;f++){var k=a.indexes[f],l=b.getStartItemIndex(),m=l+d;this.options.mode==this.$j.dn&&(l=0);if(k>=l&&k<m)return!0}return!1},Yg:function(){var a=this.Ya();return null!=a&&"actual"==a.totalSizeConfidence()?!0:!1},Gia:function(a){var d=this;this.It||(this.Bq=0,this.It=Promise.resolve());this.Bq++;this.Zha=a;this.It=this.It.then(function(){d.Bq--;if(0==d.Bq){d.It=void 0;var a=d.Ya();null!=a&&a.setPage(d.Zha,{pageSize:d.options.pageSize}).then(function(){},
function(a){d.Bq--;0>=d.Bq&&(d.It=void 0,b.r.error(a))})}},function(a){d.Bq--;0>=d.Bq&&(d.It=void 0,b.r.error(a))})},Mt:function(){var a=this;this.mx||(this.zx=0,this.mx=Promise.resolve());this.zx++;this.mx=this.mx.then(function(){a.zx--;0==a.zx&&(a.mx=void 0,a.Ld(),a._trigger("ready"))},function(d){a.zx--;0==a.zx&&(a.mx=void 0,b.r.error(d))})},sZ:function(a,b){var d=this.ri();null!=d&&d.empty();this.V$();this.YT();d=-1;null!=a&&(d=b+a);0>d||d<this.options.loadMoreOptions.maxCount?(this.ZT(),this.$T(a,
b)):this.Taa()},tZ:function(a,b){var d=this.options.overflow;this.Oia(a,b);this.Nia();this.Mia();this.Qia(a,b);this.Pia(a,b);this.Lia(a,b);if("fit"==d){var d=this.element.width(),f=this.eJ(),k=this.fJ(),l=this.Kda(),m=this.Jda(),n=null!=f?f[0].offsetWidth:0,p=null!=k?k[0].offsetWidth:0,k=null!=l?l.width():0,r=null!=m?m.width():0,n=n+p+r;n>d?n-k<=d?l.css("display","none"):n-k-r<=d?(null!=l&&l.css("display","none"),null!=m&&m.css("display","none")):(null!=l&&l.css("display","none"),null!=m&&m.css("display",
"none"),null!=f&&f.css("display","none")):0<n&&(null!=l&&l.css("display",""),null!=m&&m.css("display",""),null!=f&&f.css("display",""))}},Lia:function(a){var b=this.eJ(),d=b.children("."+this.O.ns);if(d&&0<d.length){var d=f(d[0]),h=this.A(this.xa.kS);d.attr("title",h);0==this.uf()?(d.addClass(this.Ca.tb),d.removeClass(this.Ca.kf),d.attr("tabindex","-1")):(d.addClass(this.Ca.kf),d.removeClass(this.Ca.tb),d.attr(this.Pg,"0"))}(d=b.children("."+this.O.rs))&&0<d.length&&(d=f(d[0]),h=this.A(this.xa.oS),
d.attr("title",h),0==this.uf()?(d.addClass(this.Ca.tb),d.removeClass(this.Ca.kf),d.attr(this.Pg,"-1")):(d.addClass(this.Ca.kf),d.removeClass(this.Ca.tb),d.attr(this.Pg,"0")));(d=b.children("."+this.O.ps))&&0<d.length&&(d=f(d[0]),h=this.A(this.xa.mS),d.attr("title",h),this.uf()==this.Kd()-1||0>=this.Kd()||!this.Yg()?(d.addClass(this.Ca.tb),d.removeClass(this.Ca.kf),d.attr(this.Pg,"-1")):(d.addClass(this.Ca.kf),d.removeClass(this.Ca.tb),d.attr(this.Pg,"0")));(b=b.children("."+this.O.qs))&&0<b.length&&
(b=f(b[0]),d=this.A(this.xa.nS),b.attr("title",d),this.uf()==this.Kd()-1&&this.Yg()||0===this.Kd()||0>this.Kd()&&0===a?(b.addClass(this.Ca.tb),b.removeClass(this.Ca.kf),b.attr(this.Pg,"-1")):(b.addClass(this.Ca.kf),b.removeClass(this.Ca.tb),b.attr(this.Pg,"0")))},Pia:function(a,b){var d=this.Il().find("."+this.O.OR);null!=d&&0<d.length&&(d=f(d.get(0)),d.empty(),this.bU(d,this.YV(),a,b))},Nia:function(){var a=this.fJ();if(null!=a&&(a=a.children("."+this.O.MR),null!=a&&0<a.length)){var a=f(a[0]),b=
this.A(this.xa.mR);a.text(b)}},Mia:function(){var a=this.Ida();if(null!=a){var b=this.A(this.xa.lS);a.attr("title",b);a.ojInputText("option","title",b)}},Qia:function(a,b){var d=this.Il().children("."+this.O.Av);if(null!=d&&0<d.length){var h=this.SI(a,b);0<h.text().length&&(d=f(d.get(0)),d.empty(),d.append("("),d.append(h),d.append(")"))}},Oia:function(a){a=this.ZV(a);if(0<this.Kd()&&this.Yg()){var b=this.Il().find("."+this.O.zv);if(null!=b&&0<b.length){var b=f(b.get(0)),d=this.A(this.xa.XF,{pageMax:a});
b.text(d)}else d=this.fJ(),null!=d&&(b=f(document.createElement("span")),b.addClass(this.O.zv),d.append(b),d=this.A(this.xa.XF,{pageMax:a}),b.text(d))}b=this.Il().find("."+this.O.Ap);null!=b&&0<b.length&&(b=f(b.get(0)),b.val(this.uf()+1),b.ojInputText("option","validators",[{type:"numberRange",options:{min:1,max:a}}]))},Eq:function(){var a=this.Ya();if(null!=a){this.Dk();this.Ua=[];this.Ua.push({eventType:b.$b.D.PAGE,eventHandler:this.Aea.bind(this)});this.Ua.push({eventType:b.$b.D.PAGECOUNT,eventHandler:this.SB.bind(this)});
this.Ua.push({eventType:b.ka.D.ADD,eventHandler:this.BJ.bind(this)});this.Ua.push({eventType:b.ka.D.REMOVE,eventHandler:this.CJ.bind(this)});this.Ua.push({eventType:b.ka.D.RESET,eventHandler:this.Mn.bind(this)});this.Ua.push({eventType:b.ka.D.REFRESH,eventHandler:this.SB.bind(this)});this.Ua.push({eventType:b.ka.D.SYNC,eventHandler:this.AJ.bind(this)});this.Ua.push({eventType:b.ka.D.SORT,eventHandler:this.DJ.bind(this)});var d,g;for(d=0;d<this.Ua.length;d++)(g=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&
(this.Ua[d].eventHandler=g)}},tj:function(a){if(!this.kC){var d=this;b.v.eh(a[0],function(){d.Mt()},50);this.kC=!0}},IC:function(){if(b.v.Od()&&this.options.mode==this.$j.ER){var a=this.eJ();if(null!=a){var e=this;if("vertical"==this.options.pageOptions.orientation){var g={recognizers:[[d.Swipe,{direction:d.DIRECTION_VERTICAL}]]};this.zJ=a.Zk(g).on("swipeup",function(a){a.preventDefault();e.nextPage()});this.wJ=a.Zk(g).on("swipedown",function(a){a.preventDefault();e.previousPage()})}else g={recognizers:[[d.Swipe,
{direction:d.DIRECTION_HORIZONTAL}]]},this.xJ=a.Zk(g).on("swipeleft",function(a){a.preventDefault();e.nextPage()}),this.yJ=a.Zk(g).on("swiperight",function(a){a.preventDefault();e.previousPage()})}}},Dk:function(){var a=this.Ya();if(null!=this.Ua&&null!=a){var b;for(b=0;b<this.Ua.length;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}},oM:function(a){var b=this;a.find("*").each(function(){b.Fp(this)})},oD:function(){b.v.Od()&&("vertical"==this.options.pageOptions.orientation?(null!=this.zJ&&
(this.zJ.off("swipeup"),this.zJ=null),null!=this.wJ&&(this.wJ.off("swipedown"),this.wJ=null)):(null!=this.xJ&&(this.xJ.off("swipeleft"),this.xJ=null),null!=this.yJ&&(this.yJ.off("swiperight"),this.yJ=null)))},Js:function(a,b){var d=f(document.createElement("span"));d.addClass(b);d.addClass(this.O.gi);d.text(a);return d},Maa:function(){var a=this.Jd(),b=this.A(this.xa.L7),b=this.Js(b,this.O.FR),d=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",d);a.append(b);return b},Qaa:function(){var a=
this.A(this.xa.J7);return this.Js(a,this.O.x8)},Naa:function(){var a=this.A(this.xa.G7);return this.Js(a,this.O.o8)},Oaa:function(){var a=this.A(this.xa.H7);return this.Js(a,this.O.r8)},Paa:function(){var a=this.A(this.xa.I7);return this.Js(a,this.O.u8)},Raa:function(){var a=this.A(this.xa.K7);return this.Js(a,this.O.z8)},Saa:function(){var a=this.Jd(),b=f(document.createElement("div"));b.addClass(this.O.GR);var d=this.Hda().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",d);a.append(b);
return b},YT:function(){var a=this.ri(),b=f(document.createElement("div"));b.addClass(this.O.IR);a.append(b);return b},ZT:function(){var a=this.et(),b=f(document.createElement("a"));b.addClass(this.O.Sz);var d=this.A(this.xa.M7);b.text(d);b.attr(this.Pg,"0");b.attr("href","#");a.append(b);return b},Taa:function(){var a=this.et(),b=f(document.createElement("span"));b.addClass(this.O.fG);var d=this.A(this.xa.N7,{maxRows:this.options.loadMoreOptions.maxCount});b.text(d);a.append(b);return b},$T:function(a,
b){var d=this.et(),h=f(document.createElement("span"));h.addClass(this.O.Tz);var k=this.SI(a,b);h.append(k);d.append(h);return h},aU:function(a,b){var d="vertical"==this.options.pageOptions.orientation?!0:!1,h="dots"==this.options.pageOptions.type?!0:!1,k=this.options.pageOptions.layout;null==k&&(k=[this.pf.Lg]);var l=this.ri(),m=f(document.createElement("div"));m.addClass(this.O.KR);l.append(m);if(-1!=f.inArray(this.pf.Lg,k)&&!h||-1!=f.inArray(this.pf.mv,k)||-1!=f.inArray(this.pf.Iz,k)){l=f(document.createElement("div"));
l.addClass(this.O.LR);m.append(l);var n=f(document.createElement("label"));n.attr("for",this.element.attr("id")+"_nav_input");n.addClass(this.O.MR);n.addClass("oj-label-inline");var p=this.A(this.xa.mR);n.text(p);l.append(n);n=f(document.createElement("input"));n.addClass(this.O.Ap);p=this.A(this.xa.lS);this._focusable(this.element);n.attr("id",this.element.attr("id")+"_nav_input");n.attr("title",p);n.attr(this.Pg,"0");n.val(this.uf()+1);l.append(n);p=this.ZV(a);if(0<this.Kd()&&this.Yg()){var r=f(document.createElement("span"));
r.addClass(this.O.zv);var s=this.A(this.xa.XF,{pageMax:p});r.text(s);l.append(r)}n.ojInputText({displayOptions:{messages:["notewindow"],converterHint:["notewindow"],validatorHint:["notewindow"]},rootAttributes:{style:"width: auto; min-width: 0;"},optionChange:this.nfa.bind(this),validators:[{type:"numberRange",options:{min:1,max:p}}]})}if(-1!=f.inArray(this.pf.Lg,k)&&!h||-1!=f.inArray(this.pf.mv,k)||-1!=f.inArray(this.pf.D8,k))l=f(document.createElement("span")),l.addClass(this.O.Av),n=this.SI(a,
b),0<n.text().length&&(l.append("("),l.append(n),l.append(")")),m.append(l);l=f(document.createElement("div"));l.addClass(this.O.JR);m.append(l);if(-1!=f.inArray(this.pf.Lg,k)&&!h||-1!=f.inArray(this.pf.mv,k)||-1!=f.inArray(this.pf.tR,k))n=f(document.createElement("a")),n.addClass(this.O.Uz),n.addClass(this.O.ns),d?n.addClass(this.O.q8):n.addClass(this.O.p8),n.addClass(this.O.Gp),n.addClass(this.Ca.op),n.addClass(this.Ca.tb),p=this.A(this.xa.kS),this._hoverable(n),this._focusable(n),n.attr("title",
p),n.attr(this.Pg,"0"),n.attr("href","#"),n.attr("oncontextmenu","return false;"),p=this.Naa(),n.append(p),d&&n.css("display","block"),l.append(n),n=f(document.createElement("a")),n.addClass(this.O.Uz),n.addClass(this.O.rs),d?n.addClass(this.O.B8):n.addClass(this.O.A8),n.addClass(this.O.Gp),n.addClass(this.Ca.op),n.addClass(this.Ca.tb),p=this.A(this.xa.oS),this._hoverable(n),this._focusable(n),n.attr("title",p),n.attr(this.Pg,"0"),n.attr("href","#"),n.attr("oncontextmenu","return false;"),p=this.Raa(),
n.append(p),d&&n.css("display","block"),l.append(n);if(-1!=f.inArray(this.pf.Lg,k)||-1!=f.inArray(this.pf.mv,k)||-1!=f.inArray(this.pf.j8,k))n=f(document.createElement("div")),n.addClass(this.O.OR),l.append(n),this.bU(n,this.YV(),a,b);if(-1!=f.inArray(this.pf.Lg,k)&&!h||-1!=f.inArray(this.pf.mv,k)||-1!=f.inArray(this.pf.tR,k))h=f(document.createElement("a")),h.addClass(this.O.Uz),h.addClass(this.O.qs),d?h.addClass(this.O.w8):h.addClass(this.O.v8),h.addClass(this.O.Gp),h.addClass(this.Ca.op),h.addClass(this.Ca.tb),
k=this.A(this.xa.nS),this._hoverable(h),this._focusable(h),h.attr("title",k),h.attr(this.Pg,"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.Paa(),h.append(k),d&&h.css("display","block"),l.append(h),h=f(document.createElement("a")),h.addClass(this.O.Uz),h.addClass(this.O.ps),d?h.addClass(this.O.t8):h.addClass(this.O.s8),h.addClass(this.O.Gp),h.addClass(this.Ca.op),h.addClass(this.Ca.tb),k=this.A(this.xa.mS),this._hoverable(h),this._focusable(h),h.attr("title",k),h.attr(this.Pg,
"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.Oaa(),h.append(k),d&&h.css("display","block"),l.append(h);return m},bU:function(a,b,d){if(5>b){var h=this.A(this.xa.m7);d=this.A(this.xa.l7);throw Error(h+"\n"+d);}h=f(document.createElement("div"));h.addClass(this.O.NR);a.append(h);a=this.Kd();var k=this.uf(),l=b;b=[];if(0<=k){if(this.Yg()&&a<=l)for(b[0]=0,d=1;d<a;d++)b[d]=d;else{b.push(0);0!=k&&b.push(k);k!=a-1&&this.Yg()&&b.push(a-1);var l=l-b.length,m=k-1,n=1;for(!this.Yg()||
k!=a-1&&k!=a-2||(n=0);l>n&&1<=m;)b.push(m),m--,l--;k+=1;for(-1==a&&(l=0<d?1:0);0<l&&(k<=a||-1==a);)b.push(k),k++,l--}b.sort(function(a,b){return a-b});for(d=0;d<b.length;d++)a=b[d],this.KH(h,a),d!=b.length-1&&a!=b[d+1]-1&&this.KH(h,-1);this.Yg()||this.KH(h,-1)}return h},KH:function(a,b){var d=this.uf(),h=null,k="rtl"===this.ac(),l="vertical"==this.options.pageOptions.orientation?!0:!1,m="dots"==this.options.pageOptions.type?!0:!1;if(-1==b)h=f(document.createElement("span")),h.addClass(this.O.y8),
h.text("...");else{d==b?(h=f(document.createElement("div")),h.addClass(this.Ca.bd),h.addClass(this.Ca.gf),h.addClass(this.Ca.tb),h.removeClass(this.Ca.kf)):(h=f(document.createElement("a")),h.removeClass(this.Ca.bd),h.removeClass(this.Ca.gf),h.removeClass(this.Ca.tb),h.addClass(this.Ca.kf),h.attr("href","#"));h.attr("data-oj-pagenum",b);m?h.addClass(this.O.n8):h.addClass(this.O.kG);var n=this.A(this.xa.i9,{pageNum:(b+1).toString()});this._hoverable(h);this._focusable(h);h.attr("title",n);h.attr(this.Pg,
"0");h.attr("oncontextmenu","return false;");n=this.Qaa();h.append(n);n=f(document.createElement("span"));n.append((b+1).toString());m&&(n.addClass(this.O.m8),this._hoverable(n),d==b&&(n.addClass(this.Ca.bd),n.addClass(this.Ca.gf)));n.attr("dir",k?"rtl":"ltr");h.append(n);this._hoverable(h);l&&h.css("display","block")}a.append(h);return h},Hda:function(){var a=this.Jd(),b=null;a&&(b=a.find("."+this.O.FR))&&0<b.length&&(b=f(b.get(0)));return b},Jd:function(){return f(this.element)},ri:function(){if(!this.cT){var a=
this.Jd(),b=null;a&&(b=a.find("."+this.O.GR))&&0<b.length&&(this.cT=f(b.get(0)))}return this.cT},et:function(){if(!this.aH){var a=this.ri(),b=null;a&&(b=a.children("."+this.O.IR))&&0<b.length&&(this.aH=f(b.get(0)))}return this.aH},Qqa:function(){if(!this.bH){var a=this.et(),b=null;a&&(b=a.children("."+this.O.Sz))&&0<b.length&&(this.bH=f(b.get(0)))}return this.bH},Rqa:function(){if(!this.cH){var a=this.et(),b=null;a&&(b=a.children("."+this.O.Tz))&&0<b.length&&(this.cH=f(b.get(0)))}return this.cH},
Il:function(){if(!this.dH){var a=this.ri(),b=null;a&&(b=a.children("."+this.O.KR))&&0<b.length&&(this.dH=f(b.get(0)))}return this.dH},Ida:function(){if(!this.eH){var a=this.Il(),b=null;a&&(b=a.find("."+this.O.Ap))&&0<b.length&&(this.eH=f(b.get(0)))}return this.eH},Jda:function(){if(!this.fH){var a=this.Il(),b=null;a&&(b=a.find("."+this.O.Av))&&0<b.length&&(this.fH=f(b.get(0)))}return this.fH},Kda:function(){var a=this.Il(),b=null;a&&(b=a.find("."+this.O.NR))&&0<b.length&&(b=f(b.get(0)));return b},
eJ:function(){var a=this.Il(),b=null;if(a)if((b=a.find("."+this.O.JR))&&0<b.length)b=f(b.get(0));else return null;return b},fJ:function(){var a=this.Il(),b=null;if(a)if((b=a.find("."+this.O.LR))&&0<b.length)b=f(b.get(0));else return null;return b}})})()});