/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore"],function(b,f){(function(){var a="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),d={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-center oj-bottom","center-bottom":"oj-center oj-bottom"};b.ya("oj.ojPopup",f.oj.baseComponent,
{widgetEventPrefix:"oj",options:{autoDismiss:"focusLoss",chrome:"default",initialFocus:"auto",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",modality:"modeless",role:"tooltip",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},_ComponentCreate:function(){this._super();var a=f("\x3cdiv\x3e");this.fe=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-component");var b=f("\x3cdiv\x3e").addClass("oj-popup-content");b.attr("role","presentation");
b.appendTo(a);this.element.after(a);this.element.appendTo(b);this.element.show();this.eU();this.v_();this.Zx=f.proxy(this.$x,this)},_destroy:function(){this.isOpen()&&this.Rp();this.BU();delete this.Zx;delete this.sj;b.v.unwrap(this.element,this.fe);this.element.hide();var a=this.vn;isNaN(a)||(delete this.vn,window.clearTimeout(a));this.CU();this._super()},widget:function(){return this.fe},open:function(a,d){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.wka(a);var f=this.fe;a=this.ic;
b.Ea.Gi(f.attr("id"))&&f.attr("id",this.MB("wrapper"));if(!1!==this._trigger("beforeOpen")){this.I_(d);var h=this.options;this.sL(h.autoDismiss);this.v9();f.attr("role",h.role);d=h.position;var k="rtl"===this.ac();d=b.nc.xg(d,k);var k="oj-popup-layer",l=h.tail;"none"!==l&&(k+=" "+["oj-popup-tail",l].join("-"));l={};l[b.N.Qa.cf]=f;l[b.N.Qa.Zu]=a;l[b.N.Qa.cv]=d;l[b.N.Qa.dp]=this.ft();l[b.N.Qa.Sm]=k;l[b.N.Qa.Wh]=h.modality;b.N.le().open(l);this._trigger("open");this.dK();this.iga();this._on(f,{keydown:this.zt,
keyup:this.zt});a&&0<a.length&&this._on(a,{keydown:this.zt,keyup:this.zt})}},close:function(){if(this.isOpen()&&(!1!==this._trigger("beforeClose")||this.Pw)){this.Pja();var a=this.ic,d=this.fe;this._off(d,"keydown keyup");a&&0<a.length&&this._off(a,"keydown keyup");this.CU();a={};a[b.N.Qa.cf]=d;b.N.le().close(a);this.gja();this.sL();delete this.ic;d=this.options.position;d._ofo&&(delete d._ofo,delete d.of);this._trigger("close")}},isOpen:function(){return this.fe.is(":visible")},refresh:function(){this._super();
this.isOpen()&&this.XZ();var a=this.fe;b.N.le().YO(a,b.N.xc.Um)},_setOption:function(a,d){var f=this.options;switch(a){case "tail":d!==f.tail&&this.Ika(d);break;case "chrome":d!==f.chrome&&this.v_(d);break;case "position":this.I_(d);this.refresh();return;case "autoDismiss":this.isOpen()&&d!==f.autoDismiss&&this.sL(d);break;case "modality":this.isOpen()&&(f={},f[b.N.Qa.cf]=this.fe,f[b.N.Qa.Wh]=d,b.N.le().ju(f))}this._superApply(arguments)},Sqa:function(){return"oj-popup"},Ika:function(a){this.BU();
this.eU(a);this.XZ()},eU:function(a){a=a?a:this.options.tail;if("none"!==a){a=["oj-popup-tail",a].join("-");var d=f("\x3cdiv\x3e").hide();d.addClass("oj-popup-tail").addClass(a);d.attr("role","presentation");this.x0=d.attr("id",this.MB("tail")).attr("id");var g=this.fe;d.appendTo(g);g.addClass(a);this.isOpen()&&(d={},d[b.N.Qa.cf]=g,d[b.N.Qa.Sm]="oj-popup-layer "+a,b.N.le().ju(d))}},DW:function(){var a=this.x0;return a?f(document.getElementById(a)):null},BU:function(){var a=this.DW();a&&a.remove();
delete this.x0;a=this.fe;a.removeClass(["oj-popup-tail",this.options.tail].join("-"));if(this.isOpen()){var d={};d[b.N.Qa.cf]=a;d[b.N.Qa.Sm]="oj-popup-layer";b.N.le().ju(d)}},v_:function(a){a=a?a:this.options.chrome;var b=this.fe;"default"===a&&b.hasClass("oj-popup-no-chrome")?b.removeClass("oj-popup-no-chrome"):"none"!==a||b.hasClass("oj-popup-no-chrome")||b.addClass("oj-popup-no-chrome")},wka:function(a){a?"string"===f.type(a)?a=f(a):1===a.nodeType&&(a=f(a)):a=f(document.activeElement);if(a instanceof
jQuery&&1<a.length)for(var d=this.fe,g=0;g<a.length;g++){var h=a[0];if(!b.v.Ho(d[0],h)){a=f(h);break}}else if(!(a instanceof jQuery)||a instanceof jQuery&&0===a.length)a=f(document.activeElement);this.ic=a},I_:function(a){var b=this.options;a&&(b.position=f.extend(b[a],a));a=b.position;b=this.Zx;f.isFunction(a.using)&&a.using!==b&&(a.origUsing=a.using);a.using=b;b=this.ic;a.of||(a.of=b,a._ofo=!0)},$x:function(c,e){var g=e.element.element;if(c.top!==g.css("top")||c.left!==g.css("left")){var h=this.DW();
if(h){h.hide();for(var k=0;k<a.length;k++)h.removeClass(a[k]),g.removeClass(a[k]);h.removeAttr("style");if(e.target&&0===e.target.height&&0===e.target.width&&(k="rtl"===this.ac(),k=b.nc.xg(this.options.position,k).my,!b.Ea.Gi(k))){var k=k.split(" "),l=k[0],m="middle";1<k.length&&(m="center"===k[1]?"middle":k[1]);e.horizontal=l;e.vertical=m}k=d[[e.horizontal,e.vertical].join("-")];h.addClass(k);g.addClass(k);h.show();"left"===e.horizontal?(k=h.outerWidth(),k-=k+b.v.py(h.css("left")),c.left+=k-2):"right"===
e.horizontal&&(k=h.outerWidth(),k-=k+b.v.py(h.css("right")),c.left-=k-2);"top"===e.vertical?(k=h.outerHeight(),k-=k+b.v.py(h.css(e.vertical)),c.top+=k-2):"bottom"===e.vertical&&(k=h.outerHeight(),k-=k+b.v.py(h.css(e.vertical)),c.top-=k-2);g.css(c);"center"===e.horizontal?(g=g.width(),g=Math.round((g/2-h.outerWidth()/2)/g*100),h.css({left:g+"%"})):"middle"===e.vertical&&(g=g.height(),g=Math.round((g/2-h.outerHeight()/2)/g*100),h.css({top:g+"%"}))}else g.css(c);h=this.options;(g=h.position.origUsing)&&
g(c,e);"focusLoss"===h.autoDismiss&&b.nc.JN(e)&&(this.XJ=!0,this.vn=this._delay(f.proxy(this.Rp,this),1))}},XZ:function(){var a=this.fe,d=this.options.position,f="rtl"===this.ac();a.position(b.nc.xg(d,f))},dK:function(a){var b=this.rba();a&&"none"===b&&(b="popup");"firstFocusable"===b&&(a=this.element.find(":focusable"),0<a.length?(f(a[0]).focus(),this._trigger("focus")):b="popup");"popup"===b&&(b=this.fe,b.attr("tabindex","-1"),b.focus(),this._trigger("focus"))},rba:function(){var a=this.options,
d=a.initialFocus;"auto"===d&&(d="modal"===a.modality?b.v.Od()?"popup":"firstFocusable":"none");return d},hC:function(a,d){a||(a=document.activeElement);if(!a)return!1;var f=this.fe;d&&(f=f.parent());return b.v.Ho(f[0],a)},OX:function(a){a||(a=document.activeElement);return b.v.Ho(this.ic[0],a)},Pja:function(){this.XJ?delete this.XJ:this.hC(null,!0)&&this.ic.focus()},zt:function(a){if(!a.isDefaultPrevented()){var b=a.type,d=a.target;if("keyup"===b&&a.keyCode===f.ui.keyCode.ESCAPE&&(this.hC(d)||this.OX(d)))a.preventDefault(),
this.close();else if("keydown"===b&&117===a.keyCode)this.hC(d)?(d=this.options,"modeless"===d.modality?(a.preventDefault(),a=this.ic,a.focus()):this.close()):this.OX(d)&&(a.preventDefault(),this.dK(!0));else if("keydown"===b&&a.keyCode===f.ui.keyCode.TAB&&this.hC(d)){var h=this.element.find(":tabbable");if(0<h.length){var b=h[0],h=h[h.length-1],k=this.fe;b!==d&&k[0]!==d||!a.shiftKey?h!==d||a.shiftKey||(a.preventDefault(),h===b?(k.attr("tabindex","-1"),k.focus()):f(b).focus()):(a.preventDefault(),
b===h&&b===d?(k.attr("tabindex","-1"),k.focus()):f(h).focus())}else a.preventDefault(),d=this.options,"modeless"===d.modality?(a=this.ic,a.focus()):this.close()}}},sL:function(a){var d=this.mV,g=this.ft();d&&(delete g[b.N.xc.Qr],delete this.mV);"focusLoss"===a&&(d=this.mV=f.proxy(this.vba,this),g[b.N.xc.Qr]=d);this.isOpen()&&(a={},a[b.N.Qa.cf]=this.fe,a[b.N.Qa.dp]=g,b.N.le().ju(a))},vba:function(a){var d=this.ic,g=this.fe.parent(),h=a.target,k=this.lB;if(k&&(k=k.getLink())&&b.v.Ho(k[0],h))return;
if(!b.v.Ho(d[0],h)&&!b.v.Ho(g[0],h)){if(f(h).is(":focusable")){if("mousedown"===a.type||"touchstart"===a.type)return;this.XJ=!0}this.close()}},v9:function(){var a=this.ic,b=this.fe.attr("id"),d=a.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(b);d=f.trim(d.join(" "));a.attr("aria-describedby",d)},gja:function(){var a=this.ic,b=this.fe.attr("id"),d=a.attr("aria-describedby"),d=d?d.split(/\s+/):[],b=f.inArray(b,d);-1!==b&&d.splice(b,1);(d=f.trim(d.join(" ")))?a.attr("aria-describedby",d):a.removeAttr("aria-describedby")},
iga:function(){var a=b.Ma.oy().os===b.Ma.Ui.mF,d=this.rK;d||(d=this.rK=new b.ve);var g;g=a?this.A("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNoneTouch":"ariaLiveRegionInitialFocusFirstFocusableTouch"):this.A("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");d.mma(g);if(a){if(!this.lB){var d=this.MB("focusSkipLink"),h=this.ic,a=f.proxy(this.dK,this,!0);g=this.A("ariaFocusSkipLink");this.lB=new b.Zh(h,g,a,d)}this.zH||(d=
this.MB("closeSkipLink"),h=this.element,a=f.proxy(this.Rp,this),g=this.A("ariaCloseSkipLink"),this.zH=new b.Zh(h,g,a,d))}},CU:function(){var a=this.rK;a&&(a.destroy(),delete this.rK);if(a=this.lB)a.destroy(),delete this.lB;if(a=this.zH)a.destroy(),delete this.zH},MB:function(a){var d=this.element.attr("id");b.Ea.Gi(d)&&(d=this.uuid);return[d,a].join("_")},Mq:function(){this.element.remove()},ft:function(){if(!this.sj){var a=this.sj={};a[b.N.xc.Rr]=f.proxy(this.Rp,this);a[b.N.xc.Sr]=f.proxy(this.Mq,
this);a[b.N.xc.Um]=f.proxy(this.refresh,this)}return this.sj},Rp:function(){this.Pw=!0;this.close();delete this.Pw}});b.Components.Em({ojPopup:{modality:b.Components.ih(function(){return b.we.Ok("popup").modality})}})})()});