/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","jqueryui-amd/position"],function(b,f){b.nc={};b.nc.xg=function(a,d){for(var c=f.extend({},a),e=0;e<b.nc.oQ.length;e++){var g=b.nc.oQ[e],h=c[g];h&&(c[g]=h.replace("start",d?"right":"left").replace("end",d?"left":"right").replace("\x3c",d?"+":"-").replace("\x3e",d?"-":"+"))}return c};b.nc.Uoa=function(a,b,c){return"event"===a?c:null==a||"launcher"===a?b:a};b.nc.Qha=function(a){f.each(["pageX","pageY"],function(b,c){if(a&&void 0===a[c]&&a.originalEvent){var e=
a.originalEvent,f=e.type;(f="touchstart"===f||"touchmove"===f?"touches":"touchend"===f?"changedTouches":null)&&(e=e[f][0])&&(a[c]=e[c])}})};b.nc.oQ=["my","at"];b.nc.JN=function(a){return a.target&&0<a.target.height&&0<a.target.width?!b.v.Eoa(a.target.element):!1};f.ui.position.flipcenter={left:function(a,d){var c=a.left;f.ui.position.flip.left.call(this,a,d);var e=d.within,g=e.isWindow?e.scrollLeft:e.offset.left,h=a.left-d.collisionPosition.marginLeft,e=h+d.collisionWidth-e.width-g;if(0<g-h||0<e)"right"===
d.at[0]?c-=d.targetWidth/2:"left"===d.at[0]&&(c+=d.targetWidth/2),g="rtl"===b.v.im()?-1:1,c-=d.elemWidth/2*g,a.left=c},top:function(a,b){var c=a.top;f.ui.position.flip.top.call(this,a,b);var e=b.within,e=e.isWindow?e.scrollTop:e.offset.top,g=a.top-b.collisionPosition.marginTop,h=g+b.collisionHeight-b.within.height-e;if(0<e-g||0<h)"top"===b.at[1]?c+=b.targetHeight/2:"bottom"===b.at[1]&&(c-=b.targetHeight/2),c+=b.elemHeight/2,a.top=c}};f.ui.position.flip={left:function(a,b){var c=b.within,e=c.offset.left+
c.scrollLeft,f=c.width,c=c.isWindow?c.scrollLeft:c.offset.left,h=a.left-b.collisionPosition.marginLeft,k=h-c,h=h+b.collisionWidth-f-c,l="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,m="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,n=-2*b.offset[0],p,r;if(0>k&&Math.abs(p)<Math.abs(r)){if(p=a.left+l+m+n+b.collisionWidth-f-e,0>p||p<Math.abs(k))a.left+=l+m+n}else 0<h&&(r=a.left-b.collisionPosition.marginLeft+l+m+n-c,0<r||Math.abs(r)<h)&&(a.left+=l+m+n)},top:function(a,
b){var c=b.within,e=c.offset.top+c.scrollTop,f=c.height,h=c.isWindow?c.scrollTop:c.offset.top,k=a.top-b.collisionPosition.marginTop,c=k-h,k=k+b.collisionHeight-f-h,l="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,m="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,n=-2*b.offset[1];0>c?(e=a.top+l+m+n+b.collisionHeight-f-e,(0>e||e<Math.abs(c))&&0>k&&c<k&&(a.top+=l+m+n)):0<k&&(e=a.top-b.collisionPosition.marginTop+l+m+n-h,0<e||Math.abs(e)<k)&&(a.top+=l+m+n)}};b.N=function(){this.Init()};
b.b.ga(b.N,b.b,"oj.PopupService");b.N.prototype.Init=function(){b.N.q.Init.call(this)};b.N.le=function(){b.N.LK||(b.N.LK=new b.mb);return b.N.LK};b.N.prototype.open=function(){b.l.Wb()};b.N.prototype.close=function(){b.l.Wb()};b.N.prototype.ju=function(){b.l.Wb()};b.N.prototype.YO=function(){b.l.Wb()};b.N.prototype.destroy=function(){delete b.N.LK};b.N.Wh={NONE:"none",oF:"modal",g6:"modeless"};b.N.xc={Sr:"ojPopupRemove",Rr:"ojPopupClose",Um:"ojPopupRefresh",Qr:"ojPopupAutoDismiss"};b.N.Rm={xF:"topLevel",
NP:"nearestAncestor"};b.N.Qa={cf:"popup",dp:"events",Wh:"modality",Zu:"launcher",cv:"position",Sm:"layerSelectors",Rm:"layerLevel"};b.mb=function(){this.Init()};b.b.ga(b.mb,b.N,"oj.PopupServiceImpl");b.mb.prototype.open=function(a){b.l.Df(a);var d=a[b.N.Qa.cf];b.l.xd(d,jQuery);var c=a[b.N.Qa.Zu];b.l.xd(c,jQuery);var e=a[b.N.Qa.cv];b.l.i1(e);var f=a[b.N.Qa.dp];b.l.Df(f);var h=a[b.N.Qa.Wh];if(!h||b.N.Wh.g6!==h&&b.N.Wh.oF!==h)h=b.N.Wh.NONE;var k=a[b.N.Qa.Sm];b.l.vo(k);a=a[b.N.Qa.Rm];if(!a||b.N.Rm.xF!==
a&&b.N.Rm.NP!==a)a=b.N.Rm.NP;b.v.H4(d,c);b.J.ima(d,c,f,h,k,a);d.show();d.removeAttr("aria-hidden");e&&d.position(e);this.PG();b.Components.Hm(d[0])};b.mb.prototype.close=function(a){b.l.Df(a);a=a[b.N.Qa.cf];b.l.xd(a,jQuery);b.J.jpa(a);a.hide();a.attr("aria-hidden","true");b.v.H4(a,null);this.PG();b.Components.Xo(a[0])};b.mb.prototype.ju=function(a){b.l.Df(a);var d=a[b.N.Qa.cf];b.l.xd(d,jQuery);d=b.J.ry(d);b.l.xd(d,jQuery);var c=a[b.N.Qa.dp];c&&b.J.e1(d,c);(c=a[b.N.Qa.Wh])&&b.J.f1(d,c);a=a[b.N.Qa.Sm];
b.Ea.Gi(a)||d.attr("class",a)};b.mb.prototype.YO=function(a,d,c){var e={};e.event=d;e.argsArray=c;a=b.J.ry(a);b.J.vO(a,this.Ela,e)};b.mb.prototype.Ela=function(a,d){var c=d.event,e=d.argsArray,g=b.J.pN(a);g&&f.isFunction(g[c])&&g[c].apply(this,e);return b.J.Kg.bp};b.mb.prototype.PG=function(){var a=b.J.f3(),d=this.mT;if(!a&&d){window.removeEventListener("resize",b.mb.bo,!0);window.removeEventListener("scroll",b.mb.bo,!0);a=document.documentElement;a.removeEventListener("mousewheel",b.mb.bo,!0);a.removeEventListener("DOMMouseScroll",
b.mb.bo,!0);delete this.mT;for(var c=0;c<b.mb.Xz.length;c++){var e=b.mb.Xz[c];a.removeEventListener(e,d,!0)}if(d=this.b0)d.destroy(),delete this.b0}else if(a&&!d){window.addEventListener("resize",b.mb.bo,!0);window.addEventListener("scroll",b.mb.bo,!0);a=document.documentElement;a.addEventListener("mousewheel",b.mb.bo,!0);a.addEventListener("DOMMouseScroll",b.mb.bo,!0);d=this.mT=f.proxy(this.Zba,this);for(c=0;c<b.mb.Xz.length;c++)e=b.mb.Xz[c],a.addEventListener(e,d,!0);b.v.Od()&&(this.b0=new b.xh(d))}};
b.mb.prototype.Zba=function(a){var d=f(a.target);if(!b.J.f3())this.PG();else if(!b.v.r3(a)&&("focus"!==a.type||d.is(":focusable"))){var c=b.J.Do();if("keydown"===a.type&&b.J.ooa()&&!b.v.Sk(c[0],d[0]))b.J.ona(f.Event(a));else{var e=b.J.ry(d);if(c[0]!==e[0]){if(!e.hasClass(b.mb.Ez)){var g=this.pK;g&&g.removeClass(b.mb.Ez);e.addClass(b.mb.Ez);this.pK=e}}else if(g=this.pK)g.removeClass(b.mb.Ez),delete this.pK;if("focus"!==a.type||"-1"!==d.attr("tabindex")){var d={},e={},h;for(h in a)b.mb.P6[h]&&!f.isFunction(a[h])&&
(e[h]=a[h]);d.event=f.Event(a,e);b.J.vO(c,b.mb.Jia,d)}}}};b.mb.Jia=function(a,d){var c=b.J.pN(a),e=d.event;if(c&&f.isFunction(c[b.N.xc.Qr]))c[b.N.xc.Qr](e);return b.J.Kg.bp};b.mb.bo=function(){isNaN(b.mb.AZ)&&(b.mb.AZ=window.setTimeout(function(){delete b.mb.AZ;var a=b.J.Do();b.J.vO(a,b.mb.Tia)},b.mb.E8))};b.mb.Tia=function(a,d){if(0<d.level)return b.J.Kg.nz;var c=b.J.pN(a);if(c&&f.isFunction(c[b.N.xc.Um]))c[b.N.xc.Um]();return b.J.Kg.bp};b.mb.prototype.destroy=function(){b.mb.q.destroy.call(this)};
b.mb.Ez="oj-focus-within";b.mb.Xz=["focus","mousedown","keydown"];b.mb.P6={altKey:!0,bubbles:!0,cancelable:!0,ctrlKey:!0,currentTarget:!0,eventPhase:!0,metaKey:!0,relatedTarget:!0,shiftKey:!0,target:!0,timeStamp:!0,view:!0,which:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pageX:!0,pageY:!0,screenX:!0,screenY:!0,toElement:!0,"char":!0,charCode:!0,key:!0,keyCode:!0};b.mb.E8=100;b.J={};b.J.ry=function(a){if(!a)return b.J.Do();for(;a&&0<a.length&&a.attr("oj.ZOrderUtils._SURROGATE_ATTR")!==
b.J.PF;){if(b.J.SJ(a[0]))return a;a=a.parent()}return b.J.Do()};b.J.Do=function(){var a=f(document.getElementById(b.J.PF));if(0<a.length)return a;a=f("\x3cdiv\x3e");a.attr("role","presentation");a.attr("id",b.J.PF);a.prependTo(f(document.body));return a};b.J.ima=function(a,d,c,e,g,h){var k=a[0];if(b.J.SJ(k.parentNode))throw Error("JET Popup is already open - id: "+k.getAttribute("id"));d=b.J.ry(h===b.N.Rm.xF?null:d);h=f("\x3cdiv\x3e");var l=a.attr("id");b.Ea.Gi(l)?h.uniqueId():h.attr("id",[l,"layer"].join("_"));
h.attr("role","presentation");h.addClass(g);a.after(h);g=b.J.MH(h);b.Components.Bg(k);a.appendTo(h);h.appendTo(d);b.Components.Nf(k);b.J.f1(h,e);b.J.e1(h,c,g)};b.J.e1=function(a,d,c){if(!c){var e=a.attr(b.J.Cv);e&&(c=f(document.getElementById(e)))}a.data(b.J.Cz,d);c&&d&&f.isFunction(d[b.N.xc.Sr])&&(c.surrogate(),c.surrogate("option","beforeDestroy",d[b.N.xc.Sr]))};b.J.pN=function(a){return a.data(b.J.Cz)};b.J.MH=function(a){var d=f("\x3cscript\x3e"),c=a.attr("id");b.Ea.Gi(c)?d.uniqueId():d.attr("id",
[c,"surrogate"].join("_"));d.insertBefore(a);c=d.attr("id");a.attr(b.J.Cv,c);return d};b.J.uja=function(a){var d=a.attr(b.J.Cv);a.removeAttr(b.J.Cv);d=f(document.getElementById(d));a.insertAfter(d);d.surrogate("option","beforeDestroy",null);d.remove()};b.J.jpa=function(a){var d=b.J.ry(a);b.J.wO(d,b.J.daa);b.J.eL(d);d.removeData(b.J.Cz);d.removeData(b.J.$F);var c=a[0];b.Components.Bg(c);b.J.uja(d);b.v.unwrap(a,d);b.Components.Nf(c)};b.J.daa=function(a,d){if(0<d.level)return b.J.Kg.nz;var c=a.data(b.J.Cz);
if(c&&f.isFunction(c[b.N.xc.Rr]))c[b.N.xc.Rr]();return b.J.Kg.bp};b.J.f1=function(a,d){var c=a.data(b.J.$F);a.data(b.J.$F,d);b.Ea.Gi(c)?b.N.Wh.oF===d?b.J.zS(a):b.J.eL(a):c!==d&&(d!==c&&d===b.N.Wh.oF?b.J.zS(a):b.J.eL(a))};b.J.ooa=function(){for(var a=b.J.Do().children(),d=a.length-1;-1<d;d--)if(f(a[d]).hasClass(b.J.DR))return!0;return!1};b.J.zS=function(a){var d=f("\x3cdiv\x3e");d.addClass(b.J.DR);d.addClass(a[0].className);d.attr("role","presentation");var c=a.attr("id");b.Ea.Gi(c)?d.uniqueId():d.attr("id",
[c,"overlay"].join("_"));a.before(d);d=d.attr("id");a.attr(b.J.dG,d)};b.J.eL=function(a){var d=a.attr(b.J.dG);b.Ea.Gi(d)||(a.removeAttr(b.J.dG),f(document.getElementById(d)).remove())};b.J.Kg={bp:0,nz:1,VE:2};b.J.hA={QP:0,PP:1};b.J.vO=function(a,d,c){c||(c={});c.level=0;c.type=b.J.hA.PP;b.J.yM(a,d,c)};b.J.wO=function(a,d,c){c||(c={});c.level=0;c.type=b.J.hA.QP;b.J.yM(a,d,c)};b.J.yM=function(a,d,c){var e=c.level;a=a.children();for(var g=a.length-1;-1<g;g--){var h=f(a[g]);if(b.J.SJ(h[0])){var k;if(c.type===
b.J.hA.QP){k=d(h,c);if(k===b.J.Kg.VE)return k;if(k===b.J.Kg.nz)break}c.level=e+1;k=b.J.yM(h,d,c);c.level=e;if(k===b.J.Kg.VE)return k;if(c.type===b.J.hA.PP){k=d(h,c);if(k===b.J.Kg.VE)return k;if(k===b.J.Kg.nz)break}}}return b.J.Kg.bp};b.J.SJ=function(a){return 1===a.nodeType&&a.hasAttribute(b.J.Cv)?!0:!1};b.J.f3=function(){return 0<b.J.Do().children().length};b.J.wN=function(){var a={popupCount:0},d=b.J.Do();b.J.wO(d,b.J.Tha,a);return a.popupCount};b.J.Tha=function(a,d){d.popupCount+=1;return b.J.Kg.bp};
b.J.$M=function(){var a={},d=[];a.popups=d;d=b.J.Do();b.J.wO(d,b.J.Uha,a);d=a.popups;return f(d)};b.J.Uha=function(a,d){d.popups.push(a[0]);return b.J.Kg.bp};b.J.PM=function(a,d){function c(a,c){for(var d=["absolute","relative","fixed"],e=a.parents(),g=[],h=e.length-1;-1<h;h--)g.push(f(e[h]));e=g;e.push(a);for(var g=[],k=0,h=0;h<e.length;h++){var l=e[h],m=l.css("position"),n=b.v.zna(l.css("opacity")),B=b.v.py(l.css("z-index")),l=f.inArray(l[0],l.parent().children());-1<f.inArray(m,d)?g.push({weight:[k++,
B,l],order:[l]}):1>n?g.push({weight:[k++,1,l],order:[l]}):c&&g.push({weight:[0,0,l],order:[l]})}return g}function e(a,b){for(var c=Math.max(a.length,b.length),d=0;d<c;d++){var e=d<a.length?a[d]:-1,f=d<b.length?b[d]:-1;if(e!==f)return e<f?-1:1}return 0}b.l.xd(a,jQuery);b.l.xd(d,jQuery);for(var g=c(a,!1),h=c(d,!1),k=Math.max(g.length,h.length),l=0;l<k;l++){var m=l<g.length?g[l].weight:[-1],n=l<h.length?h[l].weight:[-1],m=e(m,n);if(0!==m)return m}g=c(a,!0);h=c(d,!0);k=Math.max(g.length,h.length);for(l=
0;l<k;l++)if(m=l<g.length?g[l].order:[-1],n=l<h.length?h[l].order:[-1],m=e(m,n),0!==m)return m;return 0};b.J.ona=function(a){a.stopPropagation();a.preventDefault()};b.J.Cz="oj-popup-events";b.J.$F="oj-popup-modality";b.J.PF="__oj_zorder_container";b.J.Cv="data-oj-surrogate-id";b.J.dG="data-oj-overlayid";b.J.DR="oj-component-overlay";f.widget("oj.surrogate",{options:{create:null,beforeDestroy:null},_create:function(){this._super();this.element.uniqueId()},_destroy:function(){this._trigger("beforeDestroy");
this.element.removeUniqueId();this._super()}});b.xh=function(a){this.y0=a;this.Init()};b.b.ga(b.xh,b.b,"oj.SimpleTapRecognizer");b.xh.prototype.Init=function(){b.xh.q.Init.call(this);for(var a=this.TU=f.proxy(this.bB,this),d=document.documentElement,c=0;c<b.xh.dA.length;c++)d.addEventListener(b.xh.dA[c],a,!0)};b.xh.prototype.bB=function(a){var d=this.y0,c=a.type;"touchstart"===c?(this.Pq=a,this.Pq.lla=(new Date).getTime()):"touchmove"===c||"touchcancel"===c?delete this.Pq:"touchend"===c&&(this.Pq&&
(a=this.Pq.lla,isNaN(a)?d(this.Pq):(new Date).getTime()-a<b.xh.C8&&d(this.Pq)),delete this.Pq)};b.xh.prototype.destroy=function(){delete this.y0;var a=this.TU;delete this.TU;for(var d=document.documentElement,c=0;c<b.xh.dA.length;c++)d.removeEventListener(b.xh.dA[c],a,!0)};b.xh.dA=["touchstart","touchmove","touchcancel","touchend"];b.xh.C8=700;b.ve=function(){this.Init()};b.b.ga(b.ve,b.b,"oj.PopupLiveRegion");b.ve.prototype.Init=function(){b.ve.q.Init.call(this);isNaN(b.ve.yx)?b.ve.yx=1:++b.ve.yx};
b.ve.prototype.destroy=function(){if(!isNaN(b.ve.yx)&&(--b.ve.yx,1>b.ve.yx)){var a=f(document.getElementById(b.ve.lG));0<a.length&&a.remove()}};b.ve.prototype.mma=function(a){if(!b.Ea.mh(a)){var d=b.ve.tda();d.children().remove();f("\x3cdiv\x3e").text(a).appendTo(d)}};b.ve.tda=function(){var a=f(document.getElementById(b.ve.lG));0===a.length&&(a=f("\x3cdiv\x3e"),a.attr({id:b.ve.lG,role:"log","aria-live":"polite","aria-relevant":"additions"}),a.addClass("oj-helper-hidden-accessible"),a.appendTo(document.body));
return a};b.ve.lG="__oj_popup_arialiveregion";b.Zh=function(a,d,c,e){b.l.xd(a,jQuery);b.l.vo(d);b.l.uo(c);b.l.DM(e);this.ZC=a;this.Et=d;this.nH=c;this.mj=e?e:"";this.Init()};b.b.ga(b.Zh,b.b,"oj.PopupSkipLink");b.Zh.prototype.Init=function(){b.Zh.q.Init.call(this);var a=this.ZC,d=this.nH,c=this.Et;delete this.Et;var e=this.mj;delete this.mj;var g=f("\x3ca\x3e").attr({tabindex:"-1",href:"#"});b.Ea.mh(e)||g.attr("id",e);g.addClass("oj-helper-hidden-accessible");g.text(c);g.insertAfter(a);g.on("click",
d);a.data(b.Zh.aA,g)};b.Zh.prototype.destroy=function(){var a=this.ZC;delete this.ZC;var d=this.nH;delete this.nH;if(a){var c=a.data(b.Zh.aA);a.removeData(b.Zh.aA);c&&(c.off("click",d),c.remove())}};b.Zh.prototype.getLink=function(){var a=this.ZC,d;a&&(d=a.data(b.Zh.aA));return d};b.Zh.aA="oj-skiplink"});