/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(b,f){(function(){b.ya("oj.ojRadioset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:!1,value:void 0},refresh:function(){this._super();this.Aa()},widget:function(){return this.Xpa},Ud:function(a,c){var e;this._super(a,c);b.re.Rk([{V:"disabled",vc:!0},{V:"placeholder"},{V:"required",We:!0,vc:!0},{V:"title"}],c,this);this.Pf=this.tI();void 0===c.value&&(e=this.Pf.filter(":checked"),
e=0===e.length?void 0:e.val(),void 0!==e&&this.option("value",e,{_context:{Ec:!0,Za:!0}}),void 0===this.options.value&&(this.options.value=null))},_ComponentCreate:function(){var a=this.element;this._super();if(a.is("fieldset"))throw Error("ojRadioset cannot be bound to a fieldset. Use a div instead.");this.Pf._ojRadioCheckbox();this.Xpa=a.addClass("oj-radioset oj-component").attr("role","radiogroup").wrapInner("\x3cdiv class\x3d'oj-radioset-wrapper'\x3e\x3c/div\x3e");this._on(this.Cl)},hf:function(){this._super();
this.Aa()},nG:function(){this.Pf=this.tI();this.Pf.filter(".oj-radio").each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.Pf.not(".oj-radio")._ojRadioCheckbox()},Focus:function(){this.Td().first().focus();return!0},qG:function(){},tI:function(){var a=this.element,c=a.find("input[type\x3dradio]:first");0===c.length&&b.r.warn("Could not find any input type\x3dradio within this element");c=c.attr("name");return void 0===
c?(a=a.find("input[type\x3dradio]"),a.not("[name]")):a.find("input[type\x3dradio][name\x3d"+c+"]")},lf:function(a,b,e){a=this.element.find("input[type\x3dradio]");var f=a.filter(":checked");a=f.length?f:a.filter(":enabled").first();this.nf(b,e,{launcher:a})},_GetMessagingLauncherElement:function(){var a=this.Td(),c=b.we.Ok("radioset").renderInputAs;return c&&"html"!==c?this.widget():a},Aa:function(){this.ao(this.options.disabled)},Cl:{change:function(a){this.Hz(a)}},Hz:function(b){var c=this.ag();
this.ec(c,b,a)},ag:function(){return this.gs()},li:function(a){var b;b="[value\x3d'"+a+"']";void 0!==this.Pf&&(a=this.Pf.filter(b),void 0!==a&&0<a.length?(b=this.Pf.not(b),a._ojRadioCheckbox("option","checked",!0),void 0!==b&&0<b.length&&b._ojRadioCheckbox("option","checked",!1)):this.Pf._ojRadioCheckbox("option","checked",!1))},gs:function(){var a=this.Pf.filter(":checked");return 0===a.length?null:a.val()},_GetDefaultStyleClass:function(){return"oj-radioset"},Td:function(){return this.tI()},mG:function(){},
uz:function(){return!0},ao:function(a){a=!!a;this.Pf.each(function(){f(this).data("oj-_ojRadioCheckbox").Jv(a)});this.Pf._ojRadioCheckbox("refreshDisabled")},_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&this.ao(b)},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radioset-inputs"===a&&(b=this.Pf.get()));return b||null},_destroy:function(){var a=this._super(),b=this.element[0].firstChild;this.Pf&&this.Pf._ojRadioCheckbox("destroy");f(b).contents().unwrap();
return a}});var a={Yq:!1}})()});