/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b,f){b.ya("oj._ojRadioCheckbox",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:null,checked:null,type:null},label:function(){void 0===this.Ob&&(this.Ob=this.UI());return this.Ob},refresh:function(){this._super();this.Aa()},refreshDisabled:function(){this.jL()},widget:function(){return this.p5},Ud:function(a,b){var c;this._super(a,b);"checked"in b||(this.HN=!0,c=!!this.element.prop("checked"),
this.option("checked",c,{_context:{Za:!0}}));if("boolean"!==typeof this.options.checked)throw Error("checked option must be a boolean");"disabled"in b||(c=!!this.element.prop("disabled"),this.option("disabled",c,{_context:{Za:!0}}));if("boolean"!==typeof this.options.disabled)throw Error("disabled option must be a boolean");"type"in b||this.option("type",this.element.prop("type"),{_context:{Za:!0}})},_ComponentCreate:function(){this._super();var a=this.options.type;"checkbox"==a?(this.p5=this.element.addClass("oj-checkbox oj-component"),
this.Ob=this.UI(),this.Ob.addClass("oj-checkbox-label")):"radio"==a&&(this.p5=this.element.addClass("oj-radio oj-component"),this.Ob=this.UI(),this.Ob.addClass("oj-radio-label"));this.Lm=this.Ica();this._focusable(this.element);f.each(this.Ob,function(){f(this.childNodes[0]).wrap("\x3cspan class\x3d'oj-radiocheckbox-label-text'\x3e\x3c/span\x3e");var a=document.createElement("span");a.setAttribute("class","oj-radiocheckbox-icon");this.appendChild(a)});this.Aa()},Dv:function(a){this.Hx=a.attr("class")},
us:function(){this.Hx?this.element.attr("class",this.Hx):this.element.removeAttr("class")},Aa:function(){this.jL();this.HN||this.Ix(this.options.checked);this.element.toggleClass("oj-selected",this.options.checked);this.Ob.toggleClass("oj-selected",this.options.checked)},Ix:function(a){this.element.prop("checked",!!a)},jL:function(){this.Vd()?(this.element.prop("disabled",!0).removeAttr("aria-disabled").removeClass("oj-enabled").addClass("oj-disabled"),this.Ob.removeClass("oj-enabled").addClass("oj-disabled"),
this.Lm&&this.Lm.removeClass("oj-enabled").addClass("oj-disabled")):(this.element.prop("disabled",!1).removeAttr("aria-disabled").removeClass("oj-disabled").addClass("oj-enabled"),this.Ob.addClass("oj-enabled").removeClass("oj-disabled"),this.Lm&&this.Lm.addClass("oj-enabled").removeClass("oj-disabled"))},_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&(b=!!b,this.jL(b));"checked"===a&&(this.Ix(b),this.element.toggleClass("oj-selected",b),this.Ob.toggleClass("oj-selected",b),
this.Lm&&this.Lm.toggleClass("oj-selected",b))},UI:function(){var a=this.element.closest("label"),b="label[for\x3d'"+this.element.prop("id")+"']";return a.add(f(b))},Ica:function(){var a;if(this.Ob&&(a=this.Ob.parent())&&(a.hasClass("oj-choice-row")||a.hasClass("oj-choice-row-inline")))return a;b.r.warn("The radioset/checkboxset's input and label dom should be wrapped in a dom node with class 'oj-choice-row' or 'oj-choice-row-inline'");return null},getNodeBySubId:function(a){var b=this._super(a);
b||(a=a.subId,"oj-radiocheckbox-input"===a&&(b=this.element[0]),"oj-radiocheckbox-label"===a&&(b=this.label()[0]));return b||null},_destroy:function(){var a=this._super(),b=this.options.type;"checkbox"==b?this.Ob.removeClass("oj-enabled oj-disabled oj-selected oj-checkbox-label"):"radio"==b&&this.Ob.removeClass("oj-enabled oj-disabled oj-selected oj-radio-label");this.Lm&&this.Lm.removeClass("oj-enabled oj-disabled oj-selected");f.each(this.Ob,function(){this.removeChild(this.getElementsByClassName("oj-radiocheckbox-icon")[0]);
var a=this.getElementsByClassName("oj-radiocheckbox-label-text");void 0!==a&&f(a[0].childNodes[0]).unwrap()});return a}})});