/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b,f){var a={Vu:"oj-select-options-generated",Ga:{TAB:9,ENTER:13,YE:27,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,$P:16,E5:17,z5:18,PAGE_UP:33,PAGE_DOWN:34,HOME:36,END:35,TE:8,mP:46,LN:function(b){switch(b.which){case a.Ga.$P:case a.Ga.E5:case a.Ga.z5:return!0}return b.metaKey||b.ctrlKey?!0:!1},ON:function(a){a=a.which?a.which:a;return 112<=a&&123>=a}},H5:70,Vr:{qP:"enter_pressed",p6:"option_selected",hP:"blur",u6:"search_icon_clicked"},TN:{x:0,
y:0},Eu:function(){var a=1;return function(){return a++}}(),A4:null,em:function(a,b){for(var c=f.isFunction(a[0])?f(a[0]()):f(a[0]),d=-1,e=a.length;++d<e&&(c.context=c[0]=f.isFunction(a[0])?a[d]():a[d])&&!1!==b.call(c[0],d,c););return a},Ooa:function(){var a=f("\x3cdiv class\x3d'oj-listbox-measure-scrollbar'\x3e\x3c/div\x3e");a.appendTo("body");var b={width:a.width()-a[0].clientWidth,height:a.height()-a[0].clientHeight};a.remove();return b},Gm:function(a,b){var c,d,e;if(null===a||1>a.length)return[];
c=a.split(b);d=0;for(e=c.length;d<e;d+=1)c[d]=f.trim(c[d]);return c},M2:function(a){return a.outerWidth(!1)-a.width()},zoa:function(b){b.on("keydown",function(){void 0===f.data(b,"keyup-change-value")&&f.data(b,"keyup-change-value",b.val())});b.on("keyup",function(c){c.which===a.Ga.ENTER?c.stopPropagation():(c=f.data(b,"keyup-change-value"),void 0!==c&&b.val()!==c&&(f.removeData(b,"keyup-change-value"),b.trigger("keyup-change")))})},yoa:function(b){b.on("mousemove",function(b){var c=a.TN;if(void 0===
c||c.x!==b.pageX||c.y!==b.pageY)f(b.target).trigger("mousemove-filtered",b),a.TN.x=b.pageX,a.TN.y=b.pageY})},Spa:function(a){var b=!1,c;return function(){!1===b&&(c=a(),b=!0);return c}},fg:function(a){a[0]!==document.activeElement&&window.setTimeout(function(){var b=a[0],c=a.val().length;a.focus();a.is(":visible")&&b===document.activeElement&&(b.setSelectionRange?b.setSelectionRange(c,c):b.createTextRange&&(b=b.createTextRange(),b.collapse(!1),b.select()))},40)},Ana:function(a){a=f(a)[0];var b=0,
c=0;"selectionStart"in a?(b=a.selectionStart,c=a.selectionEnd-b):"selection"in document&&(a.focus(),b=document.selection.createRange(),c=document.selection.createRange().text.length,b.moveStart("character",-a.value.length),b=b.text.length-c);return{offset:b,length:c}},kd:function(a){a.preventDefault();a.stopPropagation()},Hoa:function(a){a.preventDefault();a.stopImmediatePropagation()},qra:function(a){var b={"\\":"\x26#92;","\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#39;"};
return String(a).replace(/[&<>"'\\]/g,function(a){return b[a]})},Joa:function(b,c){function d(a){return""+a.label}var e=b,g,h;f.isArray(e)&&(h=e,e={fb:h});!1===f.isFunction(e)&&(h=e,e=function(){return h});var k=e();k&&k.text&&(d=k.text,f.isFunction(d)||(g=k.text,d=function(a){return a[g]}));return function(b){var g={fb:[]};""!==b.Yo||c?(e()&&a.em(f(e().fb),function(e,f){a.PK(b,f,g.fb,c,!0,d)}),b.Jb(g)):b.Jb(e())}},TM:function(b,c,d,e){var g=f("\x3coption\x3e");g.addClass("oj-listbox-result oj-listbox-result-selectable oj-listbox-results-depth-"+
b);g.attr("role","option");g.attr("id","oj-listbox-result-label-"+a.Eu());g.text(e(d));g.attr("value",c);return g},G1:function(a,b,c){var d=f("\x3coptgroup\x3e");d.addClass("oj-listbox-results-sub");d.attr("label",c(b));a.addClass("oj-listbox-result-with-children");return d},Ioa:function(b,c,d){function e(b,c,g){var h,k,p,m;c.each(function(){k=f(this);k.is("li")&&(0<k.children("ul").length?(p=k.contents().filter(function(){return 1!==this.nodeType||"ul"!==this.tagName.toLowerCase()}).text(),h=a.G1(b,
p,d),m=k.children("ul"),e(h,m.children(),g+1)):h=a.TM(g,k.attr("oj-data-value"),k.text(),d),h.appendTo(b))})}e(b,c,0)},WN:function(a,b,c){c=b[c]||c;return a[c]},g1:function(b,c,d,e){function g(b,c,e,f){for(var h,q,k,p=0,m=c.length;p<m;p++)h=c[p],k=a.WN(h,f,"children"),q=a.WN(h,f,"label"),k&&0<k.length?(q=a.G1(b,q,d),g(q,k,e+1,f.childKeys||{})):(k=a.WN(h,f,"value"),q=a.TM(e,k,q,d)),q.appendTo(b)}g(b,c,0,e||{})},s1:function(a){a.children().remove();a.removeClass("oj-listbox-result-with-children")},
ipa:function(b,c){return function(d){var e={component:this.W};d.value?e.value=d.value:e.term=d.Yo||"";b(e).then(function(b){var e={fb:[]};b&&a.em(f(b),function(b,g){a.PK(d,g,e.fb,c,!1)});d.Jb(e)})}},PK:function(b,c,d,e,g,h){var k,m;c=c[0];!c.label&&e&&e.label&&(c.label=c[e.label]);!c.value&&e&&e.value&&(c.value=c[e.value]);!c.children&&e&&e.children&&(c.children=c[e.children],delete c[e.children]);if(c.children){k={};for(m in c)c.hasOwnProperty(m)&&(k[m]=c[m]);k.children=[];a.em(f(c.children),function(c,
d){a.PK(b,d,k.children,e&&e.childKeys?e.childKeys:null,g,h)});(!g||k.children.length||b.Oo(b.Yo,h(k),c))&&d.push(k)}else g&&!b.Oo(b.Yo,h(c),c)||d.push(c)},Bma:function(a,b,c){if(f.isFunction(b))return!0;if(!b)return!1;throw Error(c+" must be a function or a false value");},yo:function(a,c){function d(){}b.b.ga(d,a,"");d.prototype=f.extend(d.prototype,c);return d},JP:"last-query-result",B2:function(b){return f.data(b.ra,b.za+"-"+a.JP)},upa:function(b,c){f.data(b.ra,b.za+"-"+a.JP,c)}},d=a.yo(Object,
{ud:function(a){var b=this;return function(){a.apply(b,arguments)}},_init:function(b){var c,d=this.za,e=this.Sc;this.W=b.W;this.U=b=this.Yn(b);this.id=b.id;this.g3=!1;void 0!==b.element.data(e)&&null!==b.element.data(e)&&b.element.data(e)._destroy();this.ra=this.cw();var g=this.U.rootAttributes;this.$l=g&&g.id?g.id:"ojChoiceId_"+(b.element.attr("id")||"autogen"+a.Eu());this.$l.replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g,"\\$1");this.ra.attr("id",this.$l);this.body=a.Spa(function(){return b.element.closest("body")});
this.ra.attr("style",b.element.attr("style"));this.YM=this.U.element.attr("tabindex");this.U.element.data(e,this).attr("tabindex","-1").before(this.ra);this.ra.data(e,this);this.tc=this.ra.find(".oj-listbox-drop");this.tc.data("ojlistbox",this);this.tc.attr("data-oj-containerid",this.$l);this.fb=this.ra.find(".oj-listbox-results");this.fb.on("click",a.kd);b.list&&f("#"+b.list).is("ul")&&(e=f("#"+b.list),this.R1=e.parent(),e.addClass("oj-listbox-results").attr("role","listbox"),this.fb.replaceWith(e),
this.fb=this.ra.find(".oj-listbox-results"),this.fb.css("display",""));this.search=c="oj-select"==d?this.ra.find("input.oj-listbox-input"):this.ra.find("input."+d+"-input");this.EO=this.r4=0;this.context=null;this.cC();this.ra.on("click",a.kd);a.yoa(this.fb);this.tc.on("mousemove-filtered touchstart touchmove touchend",".oj-listbox-results",this.ud(this.pX));f(this.ra).on("change","."+d+"-input",function(a){a.stopPropagation()});f(this.tc).on("change","."+d+"-input",function(a){a.stopPropagation()});
var h=this;a.zoa(c);c.on("keyup-change input paste",this.ud(this.bu));c.on("focus",function(){c.addClass(d+"-focused");"oj-select"!==d&&h.ra.addClass("oj-focus")});c.on("blur",function(){c.removeClass(d+"-focused");"oj-select"!==d&&h.ra.removeClass("oj-focus")});this.tc.on("mouseup",".oj-listbox-results",this.ud(function(a){0<f(a.target).closest(".oj-listbox-result-selectable").length&&(this.pX(a),this.qL(null,a))}));this.tc.on("click mouseup mousedown",function(a){a.stopPropagation()});f.isFunction(this.U.Go)&&
this.tq();e=b.element.prop("disabled");void 0===e&&(e=!1);this.fj(!e);e=b.element.prop("readonly");void 0===e&&(e=!1);this.vx(e);a.A4=a.A4||a.Ooa();this.autofocus=b.element.prop("autofocus");b.element.prop("autofocus",!1);this.autofocus&&this.fg()},yH:function(a){var b=this.tc;!f(a.target).closest(b).length&&!f(a.target).closest("#"+b.attr("data-oj-containerid")).length&&0<b.length&&(b=b.data("ojlistbox"),b.close(a))},Mq:function(){this.tc&&this.tc.remove()},_destroy:function(){var a=this.vn;isNaN(a)||
(delete this.vn,window.clearTimeout(a));var a=this.U.element,b=a.data(this.Sc);this.close();this.q4&&(delete this.q4,this.q4=null);this.U.list&&this.fb&&(this.uH(this.fb),this.R1&&this.R1.append(this.fb));void 0!==b&&(b.ra.remove(),b.tc.remove(),a.removeAttr("aria-hidden").removeData(this.Sc).off("."+this.za).prop("autofocus",this.autofocus||!1),this.YM?a.attr({Ura:this.YM}):a.removeAttr("tabindex"),a.show())},uH:function(a){if(a&&a.is("ul")){a.removeClass("oj-listbox-results oj-listbox-result-sub");
a.removeAttr("role");for(var b=a.children().length-1;0<=b;b--)this.uH(f(a.children()[b]))}else a.is("li")&&((a.hasClass("oj-listbox-placeholder")||a.hasClass("oj-listbox-no-results"))&&a.remove(),a.attr("class")&&a.attr("class",a.attr("class").replace(/\oj-listbox-\S+/g,"")),(b=a.children(".oj-listbox-result-label"))&&b.contents().unwrap(),"none"==a.css("display")&&a.css("display",""),this.uH(a.children("ul")))},Aq:function(a){if(a.is("option"))return{value:a.prop("value"),label:a.text(),element:a.get(),
css:a.attr("class"),disabled:a.prop("disabled"),locked:"locked"===a.attr("locked")||!0===a.data("locked")};if(a.is("optgroup"))return{label:a.attr("label"),children:[],element:a.get(),css:a.attr("class")};if(a.is("li")){var b,c=null;(b=a.children())&&0<b.length&&b.is("ul")?(b=a.attr("oj-data-label")?a.attr("oj-data-label"):a.clone().children().remove().end().text().trim(),c=[]):b=a.attr("oj-data-label")?a.attr("oj-data-label"):a.text().trim();return{value:a.attr("oj-data-value"),label:b,element:a.get(),
css:a.attr("class"),children:c}}},Yn:function(b){var d,e,g=this;b.options&&Array.isArray(b.options)&&b.optionsKeys&&(b.options=f.extend(!0,[],b.options));d=b.element;var h=d.get(0).tagName.toLowerCase();"input"===h&&d.attr("list")?this.Kk=e=f("#"+d.attr("list")):"select"===h&&0<d.children().length?this.Kk=e=d:b.list&&(this.Kk=e=f("#"+b.list));b=f.extend({},{$oa:function(c,d,e,h){var k,m=this.U.id,l=this.U.optionRenderer;"function"!==typeof l&&(l=null);k=function(c,d,h,t,n){function r(a,d){if(l){var g=
{index:x,depth:t,leaf:!d.children,parent:c,data:d,component:b.W,parentElement:a.get(0)},g=l.call(b.W,g);null!==g&&(null===g.parentNode||g.parentNode instanceof DocumentFragment)&&a.appendChild(g)}else O=b.a2(d),void 0!==O&&a.text(O);!0!==e.fE&&(g=a.find(".oj-listbox-highlighter-section"),g.length||(g=a),s(g,e.Yo))}function s(a,b){function c(a,b){var d=0;if(3===a.nodeType){var e=a.data.toUpperCase().indexOf(b);if(0<=e){d=document.createElement("span");d.className="oj-listbox-highlighter";e=a.splitText(e);
e.splitText(b.length);var g=e.cloneNode(!0);d.appendChild(g);e.parentNode.replaceChild(d,e);d=1}}else if(1===a.nodeType&&a.childNodes&&!/(script|style)/i.test(a.tagName))for(e=0;e<a.childNodes.length;++e)e+=c(a.childNodes[e],b);return d}a.length&&b&&b.length&&a.each(function(){c(this,b.toUpperCase())})}function w(a,b){if(b.children&&0<b.children.length){var c=b.element&&f(b.element[0]).is("li")&&f(b.element[0]).children("ul"),d=c?f(b.element[0]).children("ul"):f("\x3cul\x3e\x3c/ul\x3e");d.hasClass("oj-listbox-result-sub")||
d.addClass("oj-listbox-result-sub");k(b,b.children,d,t+1,!1);c||a.append(d)}}var x,v,H,L,G,O;v=g.Ln();n&&null!==v&&!e.Yo&&0>=h.find(".oj-listbox-placeholder").length&&(v={value:"",label:v},G=f("\x3cli\x3e\x3c/li\x3e"),G.addClass("oj-listbox-placeholder oj-listbox-results-depth-0 oj-listbox-result oj-listbox-result-selectable"),G.attr("role","presentation"),H=f(document.createElement("div")),H.addClass("oj-listbox-result-label"),H.attr("id","oj-listbox-result-label-"+a.Eu()),H.attr("role","option"),
O=b.a2(v),void 0!==O&&H.text(O),G.append(H),G.data(g.Sc,v),h.prepend(G));x=0;for(n=d.length;x<n;x+=1){v=d[x];L=!0===v.disabled;H=!L&&void 0!==m(v);var P=v.element&&f(v.element[0]).is("li");G=P?f(v.element[0]):f("\x3cli\x3e\x3c/li\x3e");G.hasClass("oj-listbox-result")?(v.children&&0<v.children.length&&w(G,v),f(v.element[0]).css("display","")):(G.addClass("oj-listbox-results-depth-"+t),G.addClass("oj-listbox-result"),G.addClass(H?"oj-listbox-result-selectable":"oj-listbox-result-unselectable"),L&&G.addClass("oj-disabled"),
v.children&&G.addClass("oj-listbox-result-with-children"),G.attr("role","presentation"),H=f(document.createElement("div")),H.addClass("oj-listbox-result-label"),H.attr("id","oj-listbox-result-label-"+a.Eu()),H.attr("role","option"),L&&H.attr("aria-disabled","true"),P||(r(H,v),G.append(H)),v.children&&0<v.children.length&&w(G,v),G.data(g.Sc,v),P?(f(v.element[0]).contents().filter(function(){return"UL"!==this.tagName}).wrapAll(H),f(v.element[0]).css("display","")):h.append(G))}};k(null,d,c,0,h)}},c,
b);b.id=function(a){return a.value};b.a2=function(a){return isNaN(a.label)?a.label:this.W.Yp(a.label)};b.jN=function(a){return a&&a.label?isNaN(a.label)?a.label:this.W.Yp(a.label):void 0};"select"!==h&&null!==b.manageNewEntry&&(b.manageNewEntry=function(a){var b={};b.value=b.label=f.trim(a);return b});e?b.ur=this.ud(function(b){var c={fb:[],Fra:!1},d=b.Yo,f,h;h=function(c,e){var f,k=c.children()&&0<c.children().length&&c.children().is("ul");if(c.is("option")||c.is("li")&&!k)b.Oo(d,c.text(),c)&&e.push(g.Aq(c));
else if(c.is("optgroup")||c.is("li")&&k)f=g.Aq(c),a.em(c.is("optgroup")?c.children():c.children("ul").children(),function(a,b){h(b,f.children)}),0<f.children.length&&e.push(f)};f=e.children();void 0!==this.Ln()&&0<f.length&&""==f.first().attr("value")&&(f=f.slice(1));a.em(f,function(a,b){h(b,c.fb)});b.Jb(c)}):"options"in b&&(b.ur=f.isFunction(b.options)?a.ipa(b.options,b.optionsKeys?b.optionsKeys:null):a.Joa(b.options,b.optionsKeys?b.optionsKeys:null));return b},Baa:function(){var a=this.U.element.find(".oj-listbox-header");
if(a.length){this.header=f("\x3cli\x3e",{"class":"oj-listbox-result-header oj-listbox-result-unselectable",role:"presentation"});this.header.append(a.children());this.jga();a=f("\x3cul\x3e",{"class":"oj-listbox-results-with-header",role:"listbox"});a.append(this.header);a.appendTo(this.fb.parent());var b=f("\x3cli\x3e",{role:"presentation"});a.append(b);this.fb.attr("role","presentation");this.fb.appendTo(b)}this.g3=!0},jga:function(){this.Nh=this.header.find("li[role\x3d'option'], li:not([role])");
this.Nh.uniqueId();this.header.find("ul").attr("role","presentation");this.header.find("li:not([role])").attr("role","option");this.header.find("a, input, select, textarea, button, object, .oj-component-initnode").each(function(){f(this).attr("tabIndex",-1)})},PX:function(a){var b=!1;this.Nh.each(function(){if(f(this).attr("id")===a)return b=!0,!1});return b},Ada:function(a){if(!this.Nh)return null;if(!a)return this.Nh.first();var b=!1,c=null;this.Nh.each(function(){if(b)return c=f(this),!1;b=f(this).attr("id")===
a});return c},Oda:function(a){if(!this.Nh)return null;var b=null;this.Nh.each(function(){if(f(this).attr("id")===a)return!1;b=f(this)});return b},mka:function(a){var b=a.find(".oj-component .oj-enabled").first();0===b.length&&(b=a.find("a, input, select, textarea, button, object, .oj-component-initnode").first(),0===b.length&&(b=a.children().first()));b&&b.addClass("oj-focus")},nja:function(){this.Nh&&this.Nh.find(".oj-focus").removeClass("oj-focus")},K0:function(a){a=f.Event(this.Sc+"-selecting",
{val:this.id(a),object:a});this.U.element.trigger(a);return!a.isDefaultPrevented()},tk:function(){return!0===this.S1},Ss:function(){var a=this.Ts&&!this.vx;if(a===this.S1)return!1;this.ra.toggleClass("oj-disabled",!a);this.close();this.S1=a;return!0},fj:function(a){void 0===a&&(a=!0);this.Ts!==a&&(this.Ts=a,this.U.element.prop("disabled",!a),this.ra.toggleClass("oj-enabled",a),this.Ss())},ZH:function(){this.fj(!1)},vx:function(a){void 0===a&&(a=!1);if(this.vx===a)return!1;this.vx=a;this.U.element.prop("readonly",
a);this.Ss();return!0},fd:function(){return this.ra.hasClass("oj-listbox-dropdown-open")},Uca:function(){return this.ra.children().first()},$x:function(a,c){if(b.nc.JN(c))this.vn=window.setTimeout(f.proxy(this.close,this),1);else{var d=this.ra,e=c.element.element;e.css(a);"bottom"===c.vertical?(d.addClass("oj-listbox-drop-above"),e.addClass("oj-listbox-drop-above")):(d.removeClass("oj-listbox-drop-above"),e.removeClass("oj-listbox-drop-above"))}},GV:function(){var a={my:"start top",at:"start bottom",
of:this.Uca(),collision:"flip",using:f.proxy(this.$x,this)},c="rtl"===b.v.im();return b.nc.xg(a,c)},NK:function(){var a=this.tc,b=this.GV();a.css("width",this.ra.outerWidth());a.position(b)},Tka:function(a){return this.fd()||!1===this.Ts||!0===this.vx?!1:this.W._trigger("beforeExpand",a,{component:this.U.element})},xT:function(){this.ra.removeClass("oj-listbox-drop-above");this.tc.removeClass("oj-listbox-drop-above")},open:function(a,b){if(!this.Tka(a))return!1;this.zq(a,b);return!0},zq:function(){this.g3||
this.Baa();this.ra.addClass("oj-listbox-dropdown-open")},XC:function(){if(this.fd()&&"true"!==this.Dl().attr("aria-expanded")){this.xT();this.tc[0]!==this.body().children().last()[0]&&this.tc.detach().appendTo(this.body());this.tc.appendTo(this.body());this.header&&(this.tc.find(".oj-listbox-results-with-header").prepend(this.header),this.header.show());var a={};a[b.N.xc.Rr]=f.proxy(this.close,this);a[b.N.xc.Sr]=f.proxy(this.Mq,this);a[b.N.xc.Qr]=f.proxy(this.yH,this);a[b.N.xc.Um]=f.proxy(this.NK,
this);var c={};c[b.N.Qa.cf]=this.tc;c[b.N.Qa.Zu]=this.U.element;c[b.N.Qa.dp]=a;c[b.N.Qa.cv]=this.GV();c[b.N.Qa.Sm]="oj-listbox-drop-layer";b.N.le().open(c);f("#oj-listbox-drop").removeAttr("id");this.tc.attr("id","oj-listbox-drop");this.tc.attr("data-oj-containerid",this.$l);this.NK();this.Dl().attr("aria-expanded",!0)}},close:function(){if(this.fd()){this.ra.removeClass("oj-listbox-dropdown-open");var a=this.Dl().attr("aria-expanded");if(a&&"false"!==a){var a=this.$l,c="scroll."+a,d="resize."+a,
e="orientationchange."+a;this.ra.parents().add(window).each(function(){f(this).off(c).off(d).off(e)});this.xT();a={};a[b.N.Qa.cf]=this.tc;b.N.le().close(a);this.header&&(this.header.hide(),this.header.appendTo(this.ra));this.tc.removeAttr("data-oj-containerid");this.tc.removeAttr("id");this.U.list?this.Cx():(this.tc.detach(),this.fb.empty());this.Dl().attr("aria-expanded",!1)}}},un:function(){},Xba:function(){var a=this.fb,b,c,d,e;c=this.sq();0>c||(0==c?a.scrollTop(0):(b=this.Ws().find(".oj-listbox-result-label"),
d=f(b[c]),e=d.offset().top+d.outerHeight(!0),c===b.length-1&&(b=a.find("li.oj-listbox-more-results"),0<b.length&&(e=b.offset().top+b.outerHeight(!0))),b=a.offset().top+a.outerHeight(!0),e>b&&a.scrollTop(a.scrollTop()+(e-b)),e=d.offset().top-a.offset().top,0>e&&"none"!=d.css("display")&&a.scrollTop(a.scrollTop()+e)))},Ws:function(){return this.fb.find(".oj-listbox-result-selectable:not(.oj-disabled, .oj-selected)").filter(function(){return"none"!=f(this).css("display")})},FY:function(a){var b=this.Ws(),
c=this.sq();if(this.header&&(0>=c||c===b.length-1)){var d=this.Dl().attr("aria-activedescendant"),e=this.PX(d);e||(d=null);var g=null;0<a&&(0>c||c===b.length-1)?g=this.Ada(d):0>a&&(e&&0>c||0===c)&&(g=this.Oda(d));if(g){this.Cx();this.mka(g);this.Dl().attr("aria-activedescendant",g.attr("id"));return}e&&0>a&&(c=0)}for(;-1<=c&&c<b.length;)if(c+=a,c==b.length?c=0:-1==c&&(c=b.length-1),d=f(b[c]),d.hasClass("oj-listbox-result-selectable")&&!d.hasClass("oj-disabled")&&!d.hasClass("oj-selected")){this.sq(c);
break}},sq:function(a){var b=this.Ws();if(0===arguments.length){var c=b.filter(".oj-hover");c.length||(c=b.children(".oj-hover").closest(".oj-listbox-result"));return b.get().indexOf(c[0])}a>=b.length&&(a=b.length-1);0>a&&(a=0);this.Cx();b=f(b[a]);b.hasClass("oj-listbox-result-with-children")?b.children(".oj-listbox-result-label").addClass("oj-hover"):b.addClass("oj-hover");this.Dl().attr("aria-activedescendant",b.find(".oj-listbox-result-label").attr("id"));this.Xba()},Cx:function(){this.fb.find(".oj-hover").removeClass("oj-hover");
this.nja()},pX:function(a){a=f(a.target).closest(".oj-listbox-result-selectable");if(0<a.length&&!a.is(".oj-hover")){var b=this.Ws();this.sq(b.index(a))}else 0==a.length&&this.Cx()},bu:function(b){var c=this,d=this.search.val(),e=f.data(this.ra,this.za+"-last-term");if(!0===b||!e||d!==e)if(e||d||!b||"input"!==b.type)f.data(this.ra,this.za+"-last-term",d),d.length>=(this.U.minLength||0)?(clearTimeout(this.cpa),b&&!0!==b?this.cpa=setTimeout(function(){c.lZ(b)},a.H5):this.lZ(b)):this.close()},lZ:function(b){function c(){h.NK();
if(h.header&&h.Nh.length){var a=h.Ws(),b=h.Nh.length+a.length;h.Nh.attr("aria-setsize",b);a.length&&(a=a.children("[role\x3d'option']"),a.attr("aria-setsize",b),a.first().attr("aria-posinset",h.Nh.length+1))}}var d=this.search,e=this.fb,g=this.U,h=this,k;k=d.val();var m;(g.minLength||0)>k.length?this.close():(this.open(null,!0),m=++this.r4,this.Cx(),k=this.search.val(),k=void 0!==k&&null!==k&&(!0!==b||g.Sb||0<g.minLength)?k:"",this.EO=1,g.ur({element:g.element,Yo:k,page:this.EO,context:null,Oo:g.Oo,
Jb:this.ud(function(k){m===this.r4&&this.fd()&&(this.context=k&&void 0!==k.context?k.context:null,k&&0!==k.fb.length||!a.Bma(h.W,g.Z1,"formatNoMatches")?(a.upa(this,k.fb),this.XC(),this.$Y(e),h.U.$oa.call(this,e,k.fb,{Yo:d.val(),page:this.EO,context:null,fE:b},this.Y_()),this.ox(k,b),c()):"oj-select"===this.za&&!0!==this.U.multiple||this.header?(k=f("\x3cli\x3e"),k.addClass("oj-listbox-no-results"),k.text(g.Z1(h.W,d.val())),this.XC(),this.$Y(e),e.append(k),c()):this.close())})}))},$Y:function(a){this.U.list?
(a=a.children(),this.mX(a)):a.empty()},mX:function(a){for(var b=0;b<a.length;b++){f(a[b]).is("LI")&&((f(a[b]).hasClass("oj-listbox-no-results")||f(a[b]).hasClass("oj-listbox-placeholder"))&&f(a[b]).remove(),f(a[b]).css("display","none"),f(a[b]).hasClass("oj-selected")&&f(a[b]).removeClass("oj-selected"));var c=f(a[b]).children("ul");c&&c.children()&&this.mX(c.children())}},oH:function(a){this.close(a)},Ys:function(){a.fg(this.search)},qL:function(b,c){if(this.header){var d=this.Dl().attr("aria-activedescendant");
if(this.PX(d)){var d=f("#"+d),e=d.find("a, input, select, textarea, button, object").first();0===e.length&&(e=d.children());e.length&&e[0].click();this.close(c);return}}d=this.sq();(e=this.fb.find(".oj-hover").closest(".oj-listbox-result").data(this.Sc))?(this.sq(d),b=b||{},b.trigger=a.Vr.p6,this.kx(e,b,c)):b&&b.Toa&&this.close(c)},Ln:function(){return this.U.element.attr("placeholder")||this.U.element.attr("data-placeholder")||this.U.element.data("placeholder")||this.U.placeholder},Ck:function(){var a=
this.Ln();a&&(this.search.attr("placeholder",a),this.ra.removeClass(this.za+"-allowclear"))},tX:function(){var a;a:{var b,c,d;a=this.U.element.attr("style");if(void 0!==a)for(a=a.split(";"),c=0,d=a.length;c<d;c+=1)if(b=a[c].replace(/\s/g,""),b=b.match(/^width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/i),null!==b&&1<=b.length){a=b[1];break a}a=void 0}null!==a&&this.ra.css("width",a)},Kb:function(){return this.W.option("value")},Vo:function(a,b,c){var d={Yq:!1};c&&(d._context=c);"string"===
typeof a?this.W.ec([a],b,d):this.W.ec(a,b,d);this.U.element.val(a)},Y_:function(){return!1},Dl:function(){return this.search},lt:function(){return void 0!==this.U.minimumResultsForSearch&&void 0!==this.ra.lt},ij:function(a,b){for(var c=0;c<a.length;c++)if(f(a[c]).data(this.Sc).value===b)return a[c];return null}}),c={NM:!0,Lra:!0,Z1:function(a){return a.A("noMatchesFound")},id:function(a){return a.id},Oo:function(a,b){return 0<=(""+b).toUpperCase().indexOf((""+a).toUpperCase())},separator:","},e=a.yo(d,
{Ss:function(){e.q.Ss.apply(this,arguments)&&this.search.prop("disabled",!this.tk())},fg:function(){this.fd()&&this.close()},_destroy:function(){f("label[for\x3d'"+this.search.attr("id")+"']").attr("for",this.U.element.attr("id"));e.q._destroy.apply(this,arguments)},vH:function(a){this.selection.data(this.Sc)&&(a||b.r.warn("Event should not be null when user modified the value in UI"),"oj-select"===this.za&&this.W.cn()||this.Vo([],a),this.search.val(""),this.selection.removeData(this.Sc));this.Ck()},
tq:function(){this.U.Go.call(null,this.Kk?this.Kk:this.U.element,this.ud(this.R0))},Hs:function(b){if(this.tk())if(b.which===a.Ga.PAGE_UP||b.which===a.Ga.PAGE_DOWN)a.kd(b);else{switch(b.which){case a.Ga.UP:case a.Ga.DOWN:this.fd()?this.FY(b.which===a.Ga.UP?-1:1):this.open(b);a.kd(b);return;case a.Ga.ENTER:this.qL(null,b);a.kd(b);this.fd()||(this.Rq=!1);return;case a.Ga.TAB:this.close(b);this.Rq=!1;return;case a.Ga.YE:this.fd()&&(this.oH(b),a.kd(b));this.Rq=!1;return}this.Rq=!0}},maa:function(a){this.tk()&&
!this.fd()&&this.open(a)},cC:function(){var b;b=this.ra;var c,d=this.U.rootAttributes,d=d&&d.id?d.id:this.U.element.attr("id")||a.Eu();this.selection=b=b.find("."+this.za+"-choice");b.attr("id",this.za+"-choice-"+d);c=f("label[for\x3d'"+this.U.element.attr("id")+"']");c.attr("id")||c.attr("id",this.za+"-label-"+d);b.find("."+this.za+"-input").attr("id",this.za+"-input-"+d);this.fb.attr("id")||this.fb.attr("id","oj-listbox-results-"+d);this.search.attr("aria-owns",this.fb.attr("id"));this.search.attr("aria-labelledby",
c.attr("id"));this.U.element.attr("aria-labelledby",c.attr("id"));this.search.attr("id")&&c.attr("for",this.search.attr("id"));this.U.element.attr("aria-label")&&this.search.attr("aria-label",this.U.element.attr("aria-label"));this.U.element.attr("aria-controls")&&this.search.attr("aria-controls",this.U.element.attr("aria-controls"));b.on("keydown",this.ud(this.Hs));b.on("mousedown","abbr",this.ud(function(b){this.tk()&&(this.vH(b),a.Hoa(b),this.close(b),this.selection.focus())}));b.on("mousedown",
this.ud(function(b){this.U.element.prop("disabled")&&a.kd(b);this.fd()?this.close(b):this.tk()&&this.open(b);var c=this.search.parent().attr("aria-hidden");c&&"true"==c?this.selection.focus():this.search.focus();this.ra.addClass("oj-active");a.kd(b)}));b.on("mouseup",this.ud(function(){this.ra.removeClass("oj-active")}));b.on("focus",this.ud(function(b){a.kd(b)}));this.search.on("blur keyup",this.ud(function(b){if("keyup"!==b.type||10===b.keyCode||13===b.keyCode){if(void 0!==this.search.val()&&0>=
this.fb.find(".oj-hover").length)if(this.U.manageNewEntry){var c=this.selection.data(this.Sc);if(!c&&""!==this.search.val()||c&&(c.label!==this.search.val()||!this.W.isValid()))c=this.U.manageNewEntry(this.search.val()),this.kx(c,{trigger:"blur"===b.type?a.Vr.hP:a.Vr.qP},b)}else null==this.U.manageNewEntry&&((c=this.selection.data(this.Sc),""==this.search.val())?this.vH(b):c||""===this.search.val()?"oj-select"!==this.za&&(b=this.U.jN(c),void 0!==b&&this.search.val(b)):this.un());this.search.removeClass(this.za+
"-focused");this.ra.removeClass("oj-focus")}}));this.tX();this.U.element.hide().attr("aria-hidden",!0);this.Ck()},Yn:function(){var b=e.q.Yn.apply(this,arguments),c=this,d=b.element.get(0).tagName.toLowerCase();if("input"===d&&b.element.attr("list")||"select"===d&&0<b.element.children().length||b.list){var g=b.list?"li":"option";b.Go=function(a,b){var d,e=c.Kb();Array.isArray(e)&&(e=e[0]);d=void 0!==e&&null!==e?c.Aq(a.find(g).filter(function(){if("li"==g)return this.getAttribute("oj-data-value")===
e;if("option"==g)return this.value===e})):c.Aq(a.find(g).filter(function(){if("li"==g)return!0===this.getAttribute("oj-data-selected");if("option"==g)return this.selected}));b(d)};b.validate=function(a,b){var d;void 0!==b&&null!==b&&(d=c.Aq(a.find(g).filter(function(){if("li"==g)return this.getAttribute("oj-data-value")===b;if("option"==g)return this.value===b})));return!!d}}else if("options"in b||this.Kb()&&0<this.Kb().length)f.isFunction(b.options)?b.Go=function(d,e){function g(a,c){for(var d=0,
e=a.length;d<e;d++){var f=a[d];if(c===b.id(f)||f.children&&(f=g(f.children,c)))return f}return null}var h="";c.Kb()&&c.Kb().length&&(h=c.Kb()[0]);var k=null;if(h){var q=a.B2(c);q&&(k=g(q,h));k||(q=c.currentItem)&&q.length&&h===b.id(q[0])&&(k=q[0]);k||c.cP?e(k):b.ur({value:[h],Jb:f.isFunction(e)?function(a){a&&a.fb&&(k=g(a.fb,h));e(k)}:f.noop})}else e(k)}:(b.Go=function(a,e){var g="";c.Kb()&&c.Kb().length&&(g=c.Kb()[0]);var h="select"==d&&c.W.tp()&&!c.W.cn()?c.Ln():null,k=null;b.ur({Oo:function(a,
c,d){(a=g===b.id(d))&&(k=d);null==h&&(h=d);return a},Jb:f.isFunction(e)?function(){k||"select"!==d||(k=h);e(k)}:f.noop})},b.validate=function(a,c){var d=null;b.ur({Oo:function(a,e,g){(a=c===b.id(g))&&(d=g);return a},Jb:f.noop});return!!d});return b},ox:function(b,c,d){var e=-1,g=this;b=this.Ws();a.em(b,function(a,b){if(g.Kb()&&g.Kb()[0]===g.id(b.data(g.Sc)))return e=a,!1});!1!==d&&!0===c&&0<=e&&this.sq(e)},kx:function(a,b,c){if(this.K0(a)){var d;b&&b.trigger&&(d={rr:{trigger:b.trigger}});this.close(c);
this.Vo(0===this.id(a).length?[]:this.id(a),c,d);this.Ys()}},un:function(){this.search.val("")}}),g=a.yo(e,{Sc:"ojcombobox",za:"oj-combobox",cw:function(){return f(document.createElement("div")).attr({"class":"oj-combobox oj-component"}).html("\x3cdiv class\x3d'oj-combobox-choice' tabindex\x3d'-1' role\x3d'presentation'\x3e   \x3cinput type\x3d'text' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off'       spellcheck\x3d'false' class\x3d'oj-combobox-input' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' /\x3e   \x3cabbr class\x3d'oj-combobox-clear-entry' role\x3d'presentation'\x3e\x3c/abbr\x3e   \x3ca class\x3d'oj-combobox-arrow oj-combobox-icon oj-component-icon oj-clickable-icon-nocontext oj-combobox-open-icon'       role\x3d'button' aria-label\x3d'expand'\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d'oj-listbox-drop' style\x3d'display:none' role\x3d'presentation'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")},
fj:function(a){g.q.fj.apply(this,arguments);this.Ts?this.ra.find(".oj-combobox-arrow").removeClass("oj-disabled"):this.ra.find(".oj-combobox-arrow").addClass("oj-disabled")},close:function(a){this.fd()&&g.q.close.apply(this,arguments)},zq:function(a,b){g.q.zq.apply(this,arguments);b||this.bu(!0)},Hs:function(b){a.Ga.LN(b)||a.Ga.ON(b)||g.q.Hs.apply(this,arguments)},oo:function(a){var b,c=[];this.selection.data(this.Sc,a);null!==a&&0!=a.length?(b=this.U.jN(a),void 0!==b&&this.search.val()!==b&&this.search.val(b),
this.search.removeClass(this.za+"-default"),c.push(a)):(this.search.val(""),this.Ck());this.currentItem=c;this.U.lma&&this.ra.addClass(this.za+"-allowclear")},R0:function(a){if(void 0===a||null===a)a=(a=this.Kb())?Array.isArray(a)?Array.isArray(a)&&a.length?{label:a[0]}:null:{label:a}:null;this.oo(a)}}),h=a.yo(e,{Sc:"ojselect",za:"oj-select",Rq:!1,cw:function(){return f(document.createElement("div")).attr({"class":"oj-select oj-component"}).html("\x3cdiv class\x3d'oj-select-choice' tabindex\x3d'0' role\x3d'combobox'      aria-autocomplete\x3d'none' aria-expanded\x3d'false' aria-ready\x3d'true'\x3e  \x3cspan class\x3d'oj-select-chosen'\x3e\x3c/span\x3e  \x3cabbr class\x3d'oj-select-search-choice-close' role\x3d'presentation'\x3e\x3c/abbr\x3e  \x3ca class\x3d'oj-select-arrow oj-component-icon oj-clickable-icon-nocontext oj-select-open-icon' role\x3d'presentation'\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d'oj-listbox-drop' style\x3d'display:none' role\x3d'presentation'\x3e  \x3cdiv class\x3d'oj-listbox-search-wrapper'\x3e  \x3cdiv class\x3d'oj-listbox-search'\x3e    \x3cinput type\x3d'text' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off'           spellcheck\x3d'false' class\x3d'oj-listbox-input' title\x3d'Search field'            role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' /\x3e    \x3cspan class\x3d'oj-listbox-spyglass-box'\x3e      \x3cspan class\x3d'oj-component-icon oj-clickable-icon-nocontext oj-listbox-search-icon' role\x3d'presentation'\x3e       \x3cb role\x3d'presentation'\x3e\x3c/b\x3e\x3c/span\x3e    \x3c/span\x3e  \x3c/div\x3e  \x3c/div\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")},
fj:function(a){h.q.fj.apply(this,arguments);this.Ts?(this.ra.find(".oj-select-choice").attr("tabindex","0"),this.ra.find(".oj-select-arrow").removeClass("oj-disabled")):(this.ra.find(".oj-select-choice").attr("tabindex","-1"),this.ra.find(".oj-select-arrow").addClass("oj-disabled"))},close:function(b){this.fd()&&(h.q.close.apply(this,arguments),this.ra.find(".oj-select-choice").attr("aria-expanded",!1),this.RL(b)||this.un(),b instanceof MouseEvent&&b.target!=this.selection&&b.target!=this.search||
a.fg(this.selection),this.ra.find(".oj-listbox-spyglass-box").off("mouseup click"))},zq:function(b,c){h.q.zq.apply(this,arguments);var d;b&&"keydown"==b.type&&b.which!=a.Ga.UP&&b.which!=a.Ga.DOWN&&b.which!=a.Ga.LEFT&&b.which!=a.Ga.RIGHT&&(d=String.fromCharCode(b.which),a.kd(b));this.Z_(d);c||(d?this.bu():this.bu(!0))},XC:function(){if(this.fd()){h.q.XC.apply(this,arguments);this.ra.find(".oj-select-choice").attr("aria-expanded",!0);var a,b;this.lt()&&(a=this.search.get(0),a.createTextRange?(a=a.createTextRange(),
a.collapse(!1),a.select()):a.setSelectionRange&&(b=this.search.val().length,a.setSelectionRange(b,b)))}},cC:function(){var a=this.$l+"_selected";this.text=this.ra.find(".oj-select-chosen").attr("id",a);h.q.cC.apply(this,arguments);this.ra.find(".oj-select-choice").attr({"aria-owns":this.search.attr("aria-owns"),"aria-labelledby":this.search.attr("aria-labelledby"),"aria-describedby":a});(a=this.U.element.attr("aria-label"))&&this.selection.attr("aria-label",a);this.search.on("keydown",this.ud(this.Hs));
this.search.on("keyup-change input",this.ud(this.maa));this.search.attr("title",this.W.A("seachField"));var b=this;this.selection.on("blur",function(a){b.RL(a)})},tq:function(){this.YX()?(this.oo(null),this.close(),this.Ck()):h.q.tq.apply(this,arguments)},R0:function(a){if(void 0!==a&&null!==a){var b,c=this.Kb(),c=Array.isArray(c)?c[0]:c;b=this.U.id(a);c!==b&&(void 0===c||null===c?this.W.options.value=Array.isArray(b)?b:[b]:this.Vo(Array.isArray(b)?b:[b]));this.oo(a);this.close()}},oo:function(a){this.selection.data(this.Sc,
a);null!==a&&this.text.text(a.label);a&&""!=a.id&&this.text.removeClass(this.za+"-default");this.U.lma&&this.ra.addClass(this.za+"-allowclear")},Dl:function(){return this.search.attr("aria-expanded")&&this.lt()?this.search:this.selection},YX:function(){if(null===this.Ln())return!1;var a=this.Kb(),a=Array.isArray(a)?a[0]:a;return""===a||void 0===a||null===a},Ln:function(){return this.U.placeholder},Y_:function(){return!0},Ck:function(){var a=this.Ln();this.YX()&&void 0!==a&&(void 0===a&&(a=""),this.text.text(a).addClass(this.za+
"-default"),this.ra.removeClass(this.za+"-allowclear"))},Vo:function(a,b,c){h.q.Vo.call(this,a,b,c);this.selection.data("selectVal",a)},Hs:function(b){if(!(a.Ga.LN(b)&&b.which!=a.Ga.$P||a.Ga.ON(b))){switch(b.which){case a.Ga.TAB:this.close(b);this.selection.focus();this.RL(b);return;case a.Ga.ENTER:if(b.target===this.selection[0]&&!this.fd()){this.open(b);a.kd(b);return}}var c=this.lt();h.q.Hs.apply(this,arguments);this.Rq&&!this.fd()&&this.open(b);if(!c&&this.Rq){var d;b.which!=a.Ga.LEFT&&b.which!=
a.Ga.RIGHT&&(d=String.fromCharCode(b.which));this.Z_(d);this.bu();a.kd(b)}}},RL:function(a){return""==this.text.text()?(this.vH(a),!0):!1},Z_:function(b){var c=!1,d=this.tc.find(".oj-listbox-search");d&&(this.lt()?(this.tc.find(".oj-listbox-search-wrapper").removeClass("oj-helper-hidden-accessible"),f(d).removeAttr("aria-hidden"),this.search.val(b),c=!0):(this.tc.find(".oj-listbox-search-wrapper").addClass("oj-helper-hidden-accessible"),f(d).attr("aria-hidden","true")));a.fg(c?this.search:this.selection);
if(c){var e=this;d.find(".oj-listbox-spyglass-box").on("mouseup click",function(a){e.search.focus();a.stopPropagation()})}},lt:function(){var a=this.U.minimumResultsForSearch;return(this.U.list?f("#"+this.U.list).find("li").length:this.Kk?this.Kk[0].length:this.U.options?this.U.options.length:0)>a||this.Rq}}),k=a.yo(d,{Yn:function(){var b=k.q.Yn.apply(this,arguments),c=this,d=b.element.get(0).tagName.toLowerCase();if("input"===d&&b.element.attr("list")||"select"===d&&0<b.element.children().length||
b.list){var e=b.list?"li":"option";b.Go=function(b,g){var f=[];if(c.Kb())for(var h,k=c.Kb(),m=0;m<k.length;m++){var l=k[m];(h=b.find(e).filter(function(){if("option"===e)return this.value===l;if("li"===e)return this.getAttribute("oj-data-value")===l}))&&h.length?f.push(c.Aq(h)):f.push({value:l,label:l})}else"select"!==d&&(h=b.find(e).filter(function(){if("option"===e)return this.selected;if("li"===e)return!0===this.getAttribute("oj-data-selected")}),a.em(h,function(a,b){f.push(c.Aq(b))}));g(f)}}else"options"in
b&&(b.Go=f.isFunction(b.options)?function(d,e){function g(){for(var a=[],d=0;d<k.length;d++){for(var f=k[d],h=!1,m=0;m<q.length;m++){var l=q[m];if(f===b.id(l)){a.push(l);q.splice(m,1);h=!0;break}}if(!h){if((m=c.currentItem)&&m.length)for(l=0;l<m.length;l++)if(f===b.id(m[l])){a.push(m[l]);h=!0;break}h||a.push({value:f,label:f})}}e(a)}function h(a,c){for(var d=[],e=0,g=a.length;e<g;e++){var k=a[e];0<=c.indexOf(b.id(k))&&d.push(k);k.children&&(k=h(k.children,c))&&k.length&&f.merge(d,k)}return d}var k=
c.Kb(),q=[],m=a.B2(c);m&&(q=h(m,k));c.cP?g():b.ur({value:k,Jb:function(a){a&&a.fb&&(a=h(a.fb,k))&&a.length&&f.merge(q,a);g()}})}:b.Go||function(a,d){var e=c.Kb(),g=[];b.ur({Oo:function(a,c,d){(a=f.grep(e,function(a){return a===b.id(d)}).length)&&g.push(d);return a},Jb:f.isFunction(d)?function(){for(var a=[],c=0;c<e.length;c++){for(var f=e[c],h=!1,k=0;k<g.length;k++){var q=g[k];if(f===b.id(q)){a.push(q);g.splice(k,1);h=!0;break}}h||a.push({value:f,label:f})}d(a)}:f.noop})});return b},Pt:function(a){var b=
this.ra.find("."+this.za+"-selected-choice.oj-focus");b.length&&a&&a[0]==b[0]||(b.length&&this.U.element.trigger("choice-deselected",b),b.removeClass("oj-focus"),a&&a.length&&(this.close(),a.addClass("oj-focus"),this.ra.find("."+this.za+"-description").text(a.attr("valueText")+". Press back space to delete.").attr("aria-live","assertive"),this.U.element.trigger("choice-selected",a)))},_destroy:function(){f("label[for\x3d'"+this.search.attr("id")+"']").attr("for",this.U.element.attr("id"));k.q._destroy.apply(this,
arguments)},cC:function(){var b="."+this.za+"-choices",c,d=a.Eu(),e;this.GO=this.ra.find("."+this.za+"-search-field");this.selection=c=this.ra.find(b);var g=this;this.selection.on("click","."+this.za+"-selected-choice:not(."+this.za+"-locked)",function(){g.search[0].focus();g.Pt(f(this))});e=f("label[for\x3d'"+this.U.element.attr("id")+"']");e.attr("id")||e.attr("id",this.za+"-label-"+d);c.find("."+this.za+"-input").attr("id",this.za+"-input-"+d);this.fb.attr("id")||this.fb.attr("id","oj-listbox-results-"+
d);this.search.attr("aria-owns",this.fb.attr("id"));this.search.attr("aria-labelledby",e.attr("id"));this.U.element.attr("aria-labelledby",e.attr("id"));this.search.attr("id")&&e.attr("for",this.search.attr("id"));this.U.element.attr("aria-label")&&this.search.attr("aria-label",this.U.element.attr("aria-label"));this.U.element.attr("aria-controls")&&this.search.attr("aria-controls",this.U.element.attr("aria-controls"));this.search.attr("tabindex",this.YM);this.RN=0;this.search.on("keydown",this.ud(function(b){if(this.tk()){++this.RN;
var d=c.find("."+this.za+"-selected-choice.oj-focus"),e=d.prev("."+this.za+"-selected-choice:not(."+this.za+"-locked)"),g=d.next("."+this.za+"-selected-choice:not(."+this.za+"-locked)"),f=a.Ana(this.search);if(!d.length||b.which!=a.Ga.LEFT&&b.which!=a.Ga.RIGHT&&b.which!=a.Ga.TE&&b.which!=a.Ga.mP&&b.which!=a.Ga.ENTER)if((b.which!==a.Ga.TE||1!=this.RN)&&b.which!=a.Ga.LEFT||0!=f.offset||f.length){this.Pt(null);if(this.fd())switch(b.which){case a.Ga.UP:case a.Ga.DOWN:this.FY(b.which===a.Ga.UP?-1:1);a.kd(b);
return;case a.Ga.ENTER:this.qL(null,b);a.kd(b);return;case a.Ga.TAB:this.close(b);return;case a.Ga.YE:this.oH(b);a.kd(b);return}if(!(b.which===a.Ga.TAB||a.Ga.LN(b)||a.Ga.ON(b)||b.which===a.Ga.YE||b.which===a.Ga.ENTER&&this.search.val()&&"ojcombobox"===this.Sc))switch(b.which){case a.Ga.UP:case a.Ga.DOWN:this.open();a.kd(b);break;case a.Ga.PAGE_UP:case a.Ga.PAGE_DOWN:a.kd(b);break;case a.Ga.ENTER:a.kd(b)}}else this.Pt(c.find("."+this.za+"-selected-choice:not(."+this.za+"-locked)").last()),a.kd(b);
else f=d,b.which==a.Ga.LEFT&&e.length?f=e:b.which==a.Ga.RIGHT?f=g.length?g:null:b.which===a.Ga.TE?(this.pM(d.first(),b),this.search.width(10),f=e.length?e:g):b.which==a.Ga.mP?(this.pM(d.first(),b),this.search.width(10),f=g.length?g:null):b.which==a.Ga.ENTER&&(f=null),this.Pt(f),a.kd(b),f&&f.length||this.open()}}));this.search.on("keyup",this.ud(function(){this.RN=0}));this.search.on("blur keyup",this.ud(function(b){if("keyup"!==b.type||10===b.keyCode||13===b.keyCode){if(this.U.manageNewEntry&&this.search.val()&&
0>=this.fb.find(".oj-hover").length){var c=this.U.manageNewEntry(this.search.val());this.kx(c,{trigger:"blur"===b.type?a.Vr.hP:a.Vr.qP},b)}this.search.removeClass(this.za+"-focused");this.ra.removeClass("oj-focus");this.Pt(null);this.fd()||this.un();b.stopImmediatePropagation()}}));this.ra.on("click touchstart",b,this.ud(function(a){!this.tk()||0<f(a.target).closest("."+this.za+"-selected-choice").length||(this.Pt(null),this.fd()?this.close(a):(this.open(),this.Ys()),a.preventDefault())}));this.ra.on("focus",
b,this.ud(function(){}));this.tX();this.U.element.hide().attr("aria-hidden",!0);this.un()},Ss:function(){k.q.Ss.apply(this,arguments)&&this.search.prop("disabled",!this.tk())},tq:function(){null!==this.Kb()&&0!==this.Kb().length||"oj-select"!==this.za&&""!==this.U.element.text()||(this.oo([]),this.close(),this.un());if(this.Kk||null!==this.Kb()&&this.Kb().length){var a=this;this.U.Go.call(null,this.Kk?this.Kk:this.U.element,function(b){void 0!==b&&null!==b&&0!==b.length&&(a.oo(b),a.close(),a.un())})}},
un:function(){var a=this.Ln(),b=this.wda();void 0===a||this.Kb()&&0!==this.Kb().length?(this.search.attr("placeholder",""),this.search.val("").width(10),this.GO.width("auto")):(this.search.attr("placeholder",a),this.search.val("").width(0<b?b:this.ra.css("width")),this.GO.width("100%"))},zq:function(a,b){this.Jja();k.q.zq.apply(this,arguments);this.Ys();b||this.bu(!0);this.search.focus()},close:function(a){this.fd()&&k.q.close.apply(this,arguments)},fg:function(){this.close();this.search.focus()},
oo:function(a){var b=[],c=[],d=this;f(a).each(function(){0>b.indexOf(d.id(this))&&(b.push(d.id(this)),c.push(this))});a=c;this.selection.find("."+this.za+"-selected-choice").remove();f(a).each(function(){d.I9(this)});this.currentItem=a;this.U.element.val(0===b.length?"":b.join(this.U.separator));d.ox()},kx:function(b,c,d){if(this.K0(b)){var e;c&&c.trigger&&(e={rr:{trigger:c.trigger}});var g=this.id(b),h=this.Kb()?this.Kb().slice(0):[];this.W.isValid()||(h=a.Gm(this.U.element.val(),this.U.separator));
f(b).each(function(){0>h.indexOf(g)&&h.push(g)});this.Vo(h,d,e);!this.select&&this.U.NM||this.ox(b,!1,!0===this.U.NM);this.U.NM&&(this.close(d),this.search.width(10));c&&c.Toa||this.Ys()}},oH:function(a){this.close(a);this.Ys()},I9:function(b){var c=!b.locked,d=f("\x3cli class\x3d'"+this.za+"-selected-choice'\x3e    \x3cdiv\x3e\x3c/div\x3e    \x3ca href\x3d'#' onclick\x3d'return false;' role\x3d'button' aria-label\x3d'remove' class\x3d'"+this.za+"-clear-entry       oj-component-icon oj-clickable-icon-nocontext "+
this.za+"-clear-entry-icon' tabindex\x3d'-1'\x3e    \x3c/a\x3e\x3c/li\x3e"),e=f("\x3cli class\x3d'"+this.za+"-selected-choice "+this.za+"-locked'\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/li\x3e"),d=c?d:e;this.id(b);e=this.U.jN(b);void 0!==e&&(d.find("div").addClass(this.za+"-selected-choice-label").text(e),d.find("."+this.za+"-clear-entry").attr("aria-label",e+" remove"),d.attr("valueText",e));if(c)d.find("."+this.za+"-clear-entry").on("mousedown",a.kd).on("click dblclick",this.ud(function(b){this.tk()&&(f(b.target).closest("."+
this.za+"-selected-choice").fadeOut("fast",this.ud(function(){this.pM(f(b.target),b);this.selection.find("."+this.za+"-selected-choice.oj-focus").removeClass("oj-focus");this.close(b);this.Ys()})).dequeue(),a.kd(b))}));d.data(this.Sc,b);d.insertBefore(this.GO)},pM:function(b,c){var d=this.Kb()?this.Kb().slice(0):[],e,g;b=b.closest("."+this.za+"-selected-choice");if(0===b.length)throw"Invalid argument: "+b+". Must be ."+this.za+"-selected-choice";if(e=b.data(this.Sc)){for(this.W.isValid()||(d=a.Gm(this.U.element.val(),
this.U.separator));0<=(g=d.indexOf(this.id(e)));)d.splice(g,1),this.Vo(d,c),this.select&&this.ox();b.remove()}},ox:function(){var b=this.Kb()&&(this.U.element.val()||this.W.isValid())?this.Kb():[],c=this.fb.find(".oj-listbox-result"),d=this.fb.find(".oj-listbox-result-with-children"),e=this;a.em(c,function(a,c){var d=e.id(c.data(e.Sc));b&&0<=b.indexOf(d)&&(c.addClass("oj-selected"),c.find(".oj-listbox-result-selectable").addClass("oj-selected"))});a.em(d,function(a,b){b.is(".oj-listbox-result-selectable")||
0!==b.find(".oj-listbox-result-selectable:not(.oj-selected)").length||b.addClass("oj-selected")});0< !c.filter(".oj-listbox-result:not(.oj-selected)").length&&this.close()},wda:function(){return this.selection.width()-a.M2(this.search)},pla:function(a){var b=document.createElement("span");a=document.createTextNode(a);b.style.display="none";b.appendChild(a);f("body").append(b);b=f("body").find("span:last").width();f("body").find("span:last").remove();return b},Jja:function(){var b,c,d,e,g=a.M2(this.search);
b=this.pla(this.search.val())+10;c=this.search.offset().left;d=this.selection.width();e=this.selection.offset().left;c=d-(c-e)-g;c<b&&(c=d-g);40>c&&(c=d-g);0>=c&&(c=b);this.search.width(Math.floor(c))},Vo:function(b,c,d){var e;e=[];"string"===typeof b&&(b=a.Gm(b,this.U.separator));for(var g=0;g<b.length;g++)0>e.indexOf(b[g])&&e.push(b[g]);b={Yq:!1};d&&(b._context=d);this.W.ec(e,c,b);(this.W.isValid()||0===e.length)&&this.U.element.val(0===e.length?"":e.join(this.U.separator));this.search.attr("aria-activedescendant",
this.U.element.attr("id"))}}),l=a.yo(k,{Sc:"ojcombobox",za:"oj-combobox",cw:function(){return f(document.createElement("div")).attr({"class":"oj-combobox oj-combobox-multi oj-component"}).html("\x3cul class\x3d'oj-combobox-choices'\x3e  \x3cli class\x3d'oj-combobox-search-field'\x3e    \x3cinput type\x3d'text' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off' spellcheck\x3d'false' class\x3d'oj-combobox-input'\x3e  \x3c/li\x3e\x3c/ul\x3e\x3cdiv class\x3d'oj-combobox-description oj-helper-hidden-accessible'/\x3e\x3cdiv class\x3d'oj-listbox-drop oj-listbox-drop-multi' style\x3d'display:none'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")}}),
m=a.yo(k,{Sc:"ojselect",za:"oj-select",cw:function(){return f(document.createElement("div")).attr({"class":"oj-select oj-select-multi oj-component"}).html("\x3cul class\x3d'oj-select-choices'\x3e  \x3cli class\x3d'oj-select-search-field'\x3e    \x3cinput type\x3d'text' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off' spellcheck\x3d'false' class\x3d'oj-listbox-input'\x3e  \x3c/li\x3e\x3c/ul\x3e\x3cdiv class\x3d'oj-select-description oj-helper-hidden-accessible'/\x3e\x3cdiv class\x3d'oj-listbox-drop oj-listbox-drop-multi' style\x3d'display:none'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")}});
b.ya("oj.ojCombobox",f.oj.editableValue,{defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:void 0,placeholder:"",list:void 0,multiple:!1,options:null,optionsKeys:null,optionRenderer:null,minLength:0,beforeExpand:null},widget:function(){return this.rc.ra},_ComponentCreate:function(){this._super();this.Aa()},Ud:function(c,d){this._super(c,d);b.re.Rk([{V:"disabled",vc:!0},{V:"placeholder"},{V:"required",We:!0,vc:!0},{V:"title"}],d,this);if(void 0===this.options.value)this.options.value=
void 0!==this.element.attr("value")?a.Gm(this.element.val(),","):null;else{var e=this.options.value;Array.isArray(e)?e=e.slice(0):"string"===typeof e&&(e=!0===this.options.multiple?a.Gm(e,","):[e]);this.options.value=e}},Aa:function(){var a={},b=this.options.multiple;a.element=this.element;a.W=this;a=f.extend(this.options,a);this.rc=b?new l:new g;this.rc._init(a)},_destroy:function(){this.rc._destroy();this._super()},refresh:function(){this._super();this.rc._destroy();this.Aa();this.bA();this.Og("required",
this.options.required)},_setOption:function(b,c,d){"value"===b&&(Array.isArray(c)?c=c.slice(0):"string"===typeof c&&(c=!0===this.options.multiple?a.Gm(c,","):[c]),this.rc.cP=d&&d._context&&d._context.rr?d._context.rr.trigger:null);this._super(b,c,d);"options"===b&&(this.rc.U.options=c,this.rc.U=this.rc.Yn(this.rc.U));"disabled"===b&&(c?this.rc.ZH():this.rc.fj())},ii:function(){this.rc.close()},ll:function(){this.rc.close()},li:function(){this.rc.tq()},nn:function(a){this.rc&&(this.rc.U.placeholder=
a,this.rc.Ck&&this.rc.Ck())},validate:function(){var a=this.rc.search.val(),b=null;!0!==this.options.multiple?b=void 0===a||null===a||""===a?[]:[a]:(b=this.rc.Kb(),b=void 0===a||null===a||""===a?b:b.push(a));return this.ec(b,null,this.gA)},BC:function(b){var c=[];"string"===typeof b&&(b=!0===this.options.multiple?a.Gm(b,","):[b]);if(Array.isArray(b))for(var d=0;d<b.length;d++){var e=this._super(b[d]);c.push(e.toString())}return c},_GetMessagingLauncherElement:function(){return this.rc.search},Td:function(){return this.rc.search},
_GetDefaultStyleClass:function(){return"oj-combobox"},vw:function(){if(this.rc&&this.rc.fd())for(var a=f(".oj-listbox-drop"),b=0;b<a.length;b++)if("oj-listbox-drop"==f(a[b]).attr("id")&&f(a[b]).attr("data-oj-containerid")==this.rc.$l)return f(a[b]);return null},ij:function(a,b){for(var c=0;c<a.length;c++)if(f(a[c]).data("ojcombobox").value===b)return a[c];return null},getNodeBySubId:function(a){var b=null,c;if(null==a)return this.rc.ra?this.rc.ra[0]:null;b=this._super(a);if(!b){c=a.subId;"oj-combobox-drop"===
c&&(c="oj-listbox-drop");"oj-combobox-results"===c&&(c="oj-listbox-results");"oj-combobox-selection"===c&&(c="oj-combobox-selected-choice");var d=this.vw();switch(c){case "oj-combobox-input":case "oj-combobox-arrow":b=this.widget().find("."+c)[0];break;case "oj-listitem":d&&(b=d.find(".oj-listbox-result"),b=this.ij(b,a.value));break;case "oj-combobox-remove":b=this.widget().find(".oj-combobox-selected-choice");b=(a=this.ij(b,a.value))?f(a).find(".oj-combobox-clear-entry-icon")[0]:null;break;case "oj-listbox-drop":d&&
(b=d[0]);break;case "oj-listbox-results":d&&(b=d.find("."+c)[0]);break;case "oj-combobox-selected-choice":b=this.widget().find("."+c).toArray()}}return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a=f(a),a.hasClass("oj-combobox-input")?b={subId:"oj-combobox-input"}:a.hasClass("oj-combobox-arrow")?b={subId:"oj-combobox-arrow"}:a.hasClass("oj-listbox-result")?b={subId:"oj-listitem",value:a.data("ojcombobox").value}:a.hasClass("oj-combobox-clear-entry-icon")&&(b={subId:"oj-combobox-remove",
value:a.closest(".oj-combobox-selected-choice").data("ojcombobox").value}));return b}});b.ya("oj.ojSelect",f.oj.editableValue,{defaultElement:"\x3cselect\x3e",widgetEventPrefix:"oj",options:{minimumResultsForSearch:10,placeholder:null,list:void 0,multiple:!1,options:null,optionsKeys:null,beforeExpand:null,renderMode:"jet"},widget:function(){return this.select?this.select.ra:this.element.parent()},_ComponentCreate:function(){this._super();this.Aa()},HY:function(a){a?(this.element.attr("disabled",""),
this.element.parent().addClass("oj-disabled").removeClass("oj-enabled")):(this.element.removeAttr("disabled"),this.element.parent().removeClass("oj-disabled").addClass("oj-enabled"))},Fha:function(a){var b=[],c=!this.cn()&&this.tp();f(a.target).find("option").each(function(){this.selected&&(this.value||c&&""===this.value)&&b.push(this.value)});this.ec(b,a,{Yq:!1})},Hha:function(){var b=this.element;b.wrap("\x3cdiv\x3e").parent().addClass("oj-select-native oj-component oj-select oj-form-control");
b.addClass("oj-select-select oj-component-initnode");this.options.multiple?(b.attr("multiple",""),b.parent().prepend("\x3ca class\x3d'oj-select-arrow oj-component-icon oj-clickable-icon-nocontext oj-select-multiple-open-icon' role\x3d'presentation'\x3e\x3c/a\x3e")):b.parent().prepend("\x3ca class\x3d'oj-select-arrow oj-component-icon oj-clickable-icon-nocontext oj-select-open-icon' role\x3d'presentation'\x3e\x3c/a\x3e");this.HY(this.options.disabled);this.options.list?(a.Ioa(b,f("#"+this.options.list).children(),
this.Yp.bind(this)),b.addClass(a.Vu)):this.options.options&&(a.g1(b,this.options.options,this.Yp.bind(this),this.options.optionsKeys),b.addClass(a.Vu));b.change(this.Fha.bind(this))},Uga:function(){var a={},b=this.options.multiple;a.element=this.element;a.W=this;a=f.extend(this.options,a);this.select=b?new m:new h;this.select._init(a);this.select.ra.addClass("oj-select-jet oj-form-control")},Aa:function(){this.vt()?this.Hha():this.Uga()},refresh:function(){this._super();this.ek();this.Aa();this.bA();
this.Og("required",this.options.required)},_destroy:function(){this.ek();this._super()},ii:function(){this.select&&this.select.close()},ll:function(){this.select&&this.select.close()},nn:function(b){if(this.vt()&&null!=b){var c=f(this.element.children("option:first-child"));c&&""===c.attr("value")?(c.text(this.options.placeholder),c.attr("value","")):(c=a.TM(0,"",b,this.Yp.bind(this)),c.addClass("oj-listbox-placeholder"),c.prependTo(this.element))}},tp:function(){return"string"===typeof this.options.placeholder},
EQ:function(){this.WR(null);this.nn(null)},Ud:function(c,d){this._super(c,d);b.re.Rk([{V:"disabled",vc:!0},{V:"placeholder"},{V:"required",We:!0,vc:!0},{V:"title"}],d,this);if(void 0===this.options.value)this.options.value=void 0!==this.element.attr("value")?a.Gm(this.element.val(),","):null;else{var e=this.options.value;Array.isArray(e)&&(e=e.slice(0));this.options.value=e}},validate:function(){return this.select?this.ec(this.select.Kb(),null,this.gA):!0},li:function(a){this.select?this.select.tq():
null==a?this.tp()?(this.element[0].selectedIndex=0,this.element.addClass("oj-select-default")):(a=this.element.children(),0<a.length&&(this.options.value=[a.first().attr("value")])):this.element.val(a)},GY:function(){var a=this.element.children("option:not(:disabled)");return 0<a.length?[f(a[0]).attr("value")]:null},Gha:function(b){var c=this.options.value,d=this.element;if(d.hasClass(a.Vu))a.s1(d);else{var e=d.children();0<e.length&&e.remove()}a.g1(d,b,this.Yp.bind(this),this.options.optionsKeys);
d.addClass(a.Vu);b=null;this.tp()&&(this.options.required&&(b=this.GY()),this.nn());null===b&&(b=this.GY());this.options.value=b;this._setOption("value",c)},tja:function(a){for(var b,c=[],d=0;d<a.length;d++)b=a[d],null!=b&&(0<b.length?(1==c.length&&""===c[0]&&c.pop(),c.push(b)):0==c.length&&c.push(b));return c},_setOption:function(a,b,c){if("value"===a)if(this.tp()&&b&&0==b.length)this._super(a,b,c);else{var d;this.select&&(d=this.select.Kk,d||(d=this.select.U.element));Array.isArray(b)||(b=[b]);
this.vt()&&(b=this.tja(b),1==b.length&&""==b[0]?this.element.addClass("oj-select-default"):this.element.removeClass("oj-select-default"));for(var e=[],g=0;g<b.length;g++)this.select?(this.options.multiple||this.select.U.validate(d,b[g]))&&e.push(b[g]):0<this.element.find("option[value\x3d'"+b[g]+"']").length&&e.push(b[g]);(0<e.length||this.options.multiple)&&this._super(a,e,c)}else"placeholder"===a?this.select?(this.select.U.placeholder=b,this.select.Ck()):(d=this.options.value,d&&0!==d.length&&d[0]||
(this.element[0].selectedIndex=0)):"minimumResultsForSearch"===a?this.select&&(this.select.U.minimumResultsForSearch=b):"renderMode"===a&&(this.ek(),this.options.renderMode=b,this.refresh()),this._super(a,b,c),"disabled"===a?this.select?b?this.select.ZH():this.select.fj():this.HY(b):"options"===a&&(this.select?(this.select.U.options=b,this.select.U=this.select.Yn(this.select.U),this._super("value",this.select.Kb())):this.Gha(b))},vw:function(){if(this.select&&this.select.fd()){var a=this.select.tc;
if(a&&a.attr("data-oj-containerid")===this.select.$l)return a}return null},vt:function(){return"native"===this.options.renderMode},ek:function(){var b=this.vt();b&&this.element.parent().hasClass("oj-select-native")?(this.element.off("change"),this.element.hasClass(a.Vu)&&a.s1(this.element),this.element.parent().hasClass("oj-select-native")&&(this.element.parent().children(".oj-select-arrow").remove(),this.element.unwrap()),this.element.removeClass("oj-select-select oj-component-initnode"),this.element.attr({"aria-labelledby":""})):
!b&&this.select&&(this.select._destroy(),this.select=void 0)},getNodeBySubId:function(a){var b=null,c;if(null==a)return(a=this.widget())?a[0]:null;if(this.vt())return null;b=this._super(a);if(!b){var d=this.vw();c=a.subId;switch(c){case "oj-select-drop":d&&(b=d[0]);break;case "oj-select-results":d&&(b=d.find(".oj-listbox-results")[0]);break;case "oj-select-search":d&&(b=d.find(".oj-listbox-search")[0]);break;case "oj-select-input":case "oj-listbox-input":!0===this.options.multiple?b=this.widget().find(".oj-listbox-input")[0]:
d&&(b=d.find(".oj-listbox-input")[0]);break;case "oj-select-choice":case "oj-select-chosen":case "oj-select-arrow":b=this.widget().find("."+c)[0];break;case "oj-listitem":d&&(b=d.find(".oj-listbox-result"),b=this.select.ij(b,a.value));break;case "oj-select-remove":b=this.widget().find(".oj-select-selected-choice");b=(a=this.select.ij(b,a.value))?f(a).find(".oj-select-clear-entry-icon")[0]:null;break;case "oj-listbox-result-label":d&&(d=f("#"+this.select.fb.attr("id")).children(),a=a.index,d.length&&
a<d.length&&(b=d.eq(a).find("."+c)[0]))}}return b||null},getSubIdByNode:function(a){if(this.vt())return this._super(a);var b=null;null!=a&&(a=f(a),a.hasClass("oj-listbox-input")?b={subId:"oj-select-input"}:a.hasClass("oj-select-arrow")?b={subId:"oj-select-arrow"}:a.hasClass("oj-listbox-result")?b={subId:"oj-listitem",value:a.data("ojselect").value}:a.hasClass("oj-select-clear-entry-icon")&&(b={subId:"oj-select-remove",value:a.closest(".oj-select-selected-choice").data("ojselect").value}));return b},
_GetDefaultStyleClass:function(){return"oj-select"},_GetMessagingLauncherElement:function(){return this.select?this.select.selection:this.element},Td:function(){return this.select?this.select.selection:this.element}});b.Components.Em({ojSelect:{displayOptions:{converterHint:["none"]},renderMode:b.Components.ih(function(){return b.we.Ok("select").renderMode})}});var n=a.yo(g,{Sc:"ojinputsearch",za:"oj-inputsearch",cw:function(){var a=f(document.createElement("div")).attr({"class":"oj-inputsearch oj-component"}).html("\x3cdiv class\x3d'oj-inputsearch-choice' tabindex\x3d'-1' role\x3d'presentation'\x3e   \x3cinput type\x3d'text' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off'       spellcheck\x3d'false' class\x3d'oj-inputsearch-input' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' /\x3e   \x3ca class\x3d'oj-inputsearch-search-button oj-inputsearch-search-icon oj-component-icon oj-clickable-icon-nocontext'       role\x3d'button' aria-label\x3d'search'\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d'oj-listbox-drop' style\x3d'display:none' role\x3d'presentation'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e"),
b=a.find(".oj-inputsearch-search-button");this.f$(b);return a},f$:function(b){var c=this;b.on("click",function(b){if(c.tk()){if(c.U.manageNewEntry){var d=c.U.manageNewEntry(c.search.val());c.kx(d,{trigger:a.Vr.u6},b)}return!1}}).on("mousedown",function(a){a.stopPropagation();return!1})},fj:function(a){n.q.fj.apply(this,arguments);this.Ts?this.ra.find(".oj-inputsearch-search-button").removeClass("oj-disabled"):this.ra.find(".oj-inputsearch-search-button").addClass("oj-disabled")}});b.ya("oj.ojInputSearch",
f.oj.editableValue,{defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{placeholder:void 0,options:null,optionsKeys:null,optionRenderer:null,minLength:0,beforeExpand:null,optionChange:null},widget:function(){return this.Sb.ra},_ComponentCreate:function(){this._super();this.Aa()},Ud:function(c,d){this._super(c,d);b.re.Rk([{V:"disabled",PD:null,vc:!0},{V:"placeholder",PD:""},{V:"required",PD:!1,We:!0,vc:!0},{V:"title",PD:""}],d,this);if(void 0===this.options.value)this.options.value=void 0!==
this.element.attr("value")?a.Gm(this.element.val(),","):null;else{var e=this.options.value;Array.isArray(e)?e=e.slice(0):"string"===typeof e&&(e=[e]);this.options.value=e}},Aa:function(){var a={};a.element=this.element;a.W=this;a.Sb=!0;a=f.extend(this.options,a);this.Sb=new n;this.Sb._init(a)},_destroy:function(){this.Sb._destroy();this._super()},refresh:function(){this._super();this.Sb._destroy();this.Aa();this.bA();this.Og("required",this.options.required)},_setOption:function(a,b,c){"value"===
a&&(Array.isArray(b)?b=b.slice(0):"string"===typeof b&&(b=[b]),this.Sb.cP=c&&c._context&&c._context.rr?c._context.rr.trigger:null);this._super(a,b,c);"options"===a&&(this.Sb.U.options=b,this.Sb.U=this.Sb.Yn(this.Sb.U));"disabled"===a&&(b?this.Sb.ZH():this.Sb.fj())},ii:function(){this.Sb.close()},ll:function(){this.Sb.close()},li:function(){this.Sb.tq()},nn:function(a){this.Sb&&(this.Sb.U.placeholder=a,this.Sb.Ck&&this.Sb.Ck())},validate:function(){var a=this.Sb.search.val(),b=null,b=this.Sb.Kb(),
b=void 0===a||null===a||""===a?b:b.push(a);return this.ec(b,null,this.gA)},BC:function(a){var b=[];"string"===typeof a&&(a=[a]);if(Array.isArray(a))for(var c=0;c<a.length;c++){var d=this._super(a[c]);b.push(d.toString())}return b},_GetMessagingLauncherElement:function(){return this.Sb.search},Td:function(){return this.Sb.search},_GetDefaultStyleClass:function(){return"oj-inputsearch"},vw:function(){if(this.Sb&&this.Sb.fd())for(var a=f(".oj-listbox-drop"),b=0;b<a.length;b++)if("oj-listbox-drop"==f(a[b]).attr("id")&&
f(a[b]).attr("data-oj-containerid")==this.Sb.$l)return f(a[b]);return null},expand:function(){this.Sb.open()},collapse:function(){this.Sb.close()},getNodeBySubId:function(a){var b=null,c;if(null===a)return this.Sb.ra?this.Sb.ra[0]:null;b=this._super(a);if(!b)switch(c=a.subId,"oj-inputsearch-search"===c&&(c="oj-inputsearch-search-button"),c){case "oj-inputsearch-input":case "oj-inputsearch-search-button":b=this.widget().find("."+c)[0];break;case "oj-listitem":if(c=this.vw())b=c.find(".oj-listbox-result"),
b=this.Sb.ij(b,a.value)}return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a=f(a),a.hasClass("oj-inputsearch-input")?b={subId:"oj-inputsearch-input"}:a.hasClass("oj-inputsearch-search-button")?b={subId:"oj-inputsearch-search"}:a.hasClass("oj-listbox-result")&&(b={subId:"oj-listitem",value:a.data("ojinputsearch").value}));return b}})});