/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","jqueryui-amd/draggable","ojs/ojtouchproxy"],function(b,f){(function(){b.ya("oj.ojSlider",f.oj.editableValue,{defaultElement:"\x3cinput\x3e",version:"1.0.1",widgetEventPrefix:"oj",options:{distance:0,max:100,min:0,orientation:"horizontal",readOnly:!1,disabled:!1,step:1,type:"fromMin",value:0,rawValue:void 0},MY:5,e0:null,ae:function(){return"rtl"===b.v.im()},_ComponentCreate:function(){this._super();this.element.removeAttr("pattern");this.GX=!1;
this.element.is("INPUT")?(this.GX=!0,this.element[0].style&&(this.ela=this.element[0].style.cssText),this.EX=this.element.css("display"),this.element.css("display","none"),this.oi=f(this.element).wrap("\x3cdiv\x3e \x3c/div\x3e").parent()):this.oi=this.element;this.LT()},LT:function(){this.KY=[];this.hg=null;var a="oj-slider ",a=this.hc()?a+"oj-slider-vertical":a+"oj-slider-horizontal",a=a+" oj-component oj-form-control";this.options.AO&&(a+=" oj-read-only");this.options.disabled&&(a+=" oj-disabled");
this.oi.removeClass();this.oi.addClass(a);this.zf="range"===this.options.type?!0:!1;this.jT();this.aba();this.waa();this.A$();this.Yaa();this.dba();this.Xx();this.xj()},hf:function(){this._super();this.Ct();var a=this.t7();if(a){var b=this.oi.find(".oj-slider-thumb"),c=a.attr("id");c||(c=a.attr("for"));b.attr("aria-labelledby",c);1<a.length&&1<b.length&&b[1].attr("aria-labelledby",String(c))}else if(a=this.element.attr("aria-label"))b=this.oi.find(".oj-slider-thumb"),b.attr("aria-label",a)},t7:function(){var a=
this.Bca();if(null!==a&&0!==a.length)return a;a=this.Aca();if(null!==a&&0!==a.length)return a},Aca:function(){var a=this.element.prop("id");if(void 0!==a){var b=f("label[for\x3d'"+a+"']");if(0<b.length)return b;a="span[for\x3d'"+a+"']";if(0!==f(a).length)return f(a)}return null},Bca:function(){var a=this.element.attr("aria-labelledby");if(void 0!==a){var b=f("label[id\x3d'"+a+"']");if(0<b.length)return b;a=f("span[id\x3d'"+a+"']");if(0<a.length)return a}else return null},widget:function(){return this.oi},
li:function(a){this.e0=a},ag:function(){return this.e0},wB:function(){return this.element[0].id},pJ:function(a){return this.wB()+"-thumb"+a},rV:function(){return this.wB()+"-barValue"},Dca:function(){return this.wB()+"-barBack"},Xda:function(){return this.wB()+"-sliderWrapper"},dba:function(){var a,b,c="",e="class\x3d'oj-slider-thumb ui-state-default' tabindex\x3d'0' role\x3d'slider'"+("aria-valuemin \x3d '"+this.Vc()+"' ")+("aria-valuemax \x3d '"+this.Ve()+"' ")+"\x3e\x3c/span\x3e",g=[];b=this.zf?
this.options.value.length:1;for(a=0;a<b;a++)c="\x3cspan "+("id\x3d'"+this.pJ(a)+"' ")+e,g.push(c);this.ig=f(g.join("")).appendTo(this.zi);this.jo=this.ig.eq(0);var h=this;this.ig.each(function(a){f(this).data("oj-slider-thumb-index",a);h.hc()&&f(this).attr("aria-orientation","vertical");h.options.disabled?(f(this).attr("aria-disabled","true"),f(this).removeAttr("tabindex")):f(this).removeAttr("aria-disabled");h.options.readOnly?f(this).attr("title","read only"):f(this).removeAttr("title")})},aba:function(){var a=
this.Xda(),b=this.oi.find("#"+a);b.length&&b.remove();this.zi=f("\x3cdiv\x3e\x3c/div\x3e");f(this.zi).attr("id",a);this.zi.addClass("oj-slider-container");this.element.after(this.zi);this.zi[0].style.cssText=this.ela;this.hc()&&""==this.zi[0].style.height&&(this.zi[0].style.height="150px")},waa:function(){var a=this.Dca(),b=this.oi.find("#"+a);b.length&&b.remove();this.Rc=f("\x3cdiv\x3e\x3c/div\x3e");b="oj-slider-bar";b=this.hc()?b+" oj-slider-vertical":b+" oj-slider-horizontal";f(this.Rc).attr("id",
a);this.Rc.addClass(b);this.zi.append(this.Rc);var c=this;this.Rc.on("mousedown"+c.eventNamespace,function(a){c.YZ(a);c.dx(a);c.oB().focus()})},A$:function(){this.options.type&&(this.options.value?this.zf&&2!=this.options.value.length&&(this.options.value=[0<this.options.value.length?this.options.value[0]:this.Vc(),this.Ve()],this.option("value",this.options.value,{_context:{Ec:!0,Za:!0}})):(this.options.value=this.zf?[this.Vc(),this.Ve()]:this.Vc(),this.option("value",this.options.value,{_context:{Ec:!0,
Za:!0}})))},Yaa:function(){var a=this.options,b="";if(a.type){this.Cb=f("\x3cdiv\x3e\x3c/div\x3e");f(this.Cb).attr("id",this.rV());this.zi.append(this.Cb);var b="oj-slider-range oj-slider-bar-value",c=this;this.Cb.on("mousedown"+c.eventNamespace,function(a){c.YZ(a);c.dx(a);c.oB().focus()});this.Cb=this.zi.find("#"+this.rV());var e="";"fromMin"===a.type?e=" oj-slider-range-min":"fromMax"===a.type&&(e=" oj-slider-range-max");this.Cb.addClass(b+e)}else this.Cb&&this.Cb.remove(),this.Cb=null},Qka:function(a){this.WL=
b.ze.b1(a)},nla:function(a){b.ze.v4(a)},xj:function(){this.qv()&&this._hoverable(this.oi);this._focusable(this.oi);this.ig.toArray().forEach(function(a){a=f(a);this.Fp(a);this._on(a,this.sla);this.Qka(a)},this)},Td:function(){return this.oi},zU:function(){this.ig.toArray().forEach(function(a){a=f(a);this.nla(a)},this);this.Cb&&this.Cb.remove();this.zi&&this.zi.remove()},Lla:function(){b.v.unwrap(this.element,this.oi);this.element.css("display",this.EX);this.us(this.element)},_destroy:function(){this.zU();
this.Lla();return this._super()},YZ:function(a){var b,c,e,g=this,h=this.options;e=0;this.IT=this.jo;if(h.disabled||h.readOnly)return!1;b=this.Cda({x:a.pageX,y:a.pageY});c=this.Ve()-this.Vc()+1;this.zf&&this.ig.each(function(a){var l=Math.abs(b-g.fq(a));if(c>l||c===l&&(a===g.Yga||g.fq(a)===h.min))c=l,this.IT=f(this),e=a});this.hg=e;if(this.IT)return this.ig.hasClass("ui-state-hover")||this.Kq(a,e,b),this.oB().addClass("oj-active").focus(),this.Cb.addClass("oj-active"),!0},Yfa:function(a,b){var c=this.options;
if(c.disabled||c.readOnly)return!1;b.addClass("oj-active").focus();this.Cb.addClass("oj-active");return!0},Cha:function(a,b){var c=this.eW(b);this.Kq(a,this.hg,c,!0);c=100*this.LV(b);this.zf?this.M_(c,this.hg):this.J_(c);return!1},dx:function(a,b){this.ig.removeClass("oj-active");this.Cb.removeClass("oj-active");var c=this.eW(b);this.Kq(a,this.hg,c);this.Ch(a,this.hg,!1);this.hg=null;return!1},hc:function(){return"vertical"===this.options.orientation},fW:function(a){1<a&&(a=1);0>a&&(a=0);this.hc()&&
(a=1-a);return a},Cda:function(a){var b=this.cda(a);a=this.Ve()-this.Vc();this.ae()&&!this.hc()&&(b=1-b);return this.Kh(this.Vc()+b*a)},cda:function(a){var b;this.hc()?(b=this.Rc.height(),a=a.y-this.Rc.offset().top):(b=this.Rc.width(),a=a.x-this.Rc.offset().left);return 0==b?1:b=this.fW(a/b)},oB:function(){return this.zf?f(this.ig[this.hg]):this.jo},LV:function(a){var b;a||(a=this.oB());this.hc()?(b=a.outerHeight()/2,b=a.offset().top+b,a=this.Rc.height(),b-=this.Rc.offset().top):(b=a.outerWidth()/
2,b=a.offset().left+b,a=this.Rc.width(),b-=this.Rc.offset().left);return 0==a?1:a=this.fW(b/a)},eW:function(a){var b;a=this.LV(a);b=this.Ve()-this.Vc();this.ae()&&!this.hc()&&(a=1-a);return this.Kh(this.Vc()+a*b)},Eda:function(a){return this.fq(a?0:1)},yda:function(a,b,c){return 2===this.options.value.length&&(0===a&&b>c||1===a&&b<c)?c:b},Kq:function(a,b,c,e){var f;this.zf?(f=this.Eda(b),c=this.yda(b,c,f),c!==this.fq(b)&&this.zka(a,b,c,e)):c!==this.vW()&&(this.Gka(a,c,e),e||this.GX&&this.element.val(c))},
Gka:function(a,b,c){this.wC=this.Kh(b);c||(this.ec(this.wC,a),this.Xx());this.ws(this.wC,a)},Ch:function(a,b,c){this.zf?(this.lY=this.zda(b,this.KY[b]),this.ws(this.lY,a),c||this.ec(this.lY,a)):(this.ws(this.wC,a),c||this.ec(this.wC,a));this.Yga=b},zda:function(a,b){var c,e;c=this.options.value.slice();for(e=0;e<c.length;e+=1)c[e]=this.Kh(c[e]);a===this.hg&&(c[a]=b);return c},vW:function(){return this.LW()},fq:function(a){return this.dea(a)},zka:function(a,b,c,e){this.KY[b]=this.Kh(c);this.Ch(a,b,
e);e||this.Xx()},_setOption:function(a,b,c){"value"===a&&(Array.isArray(b)?isNaN(b[0])?(this.zf=!1,this.xk(a,b[0])):this.zf=!0:(this.zf=!1,this.xk(a,b)));b="max"===a||"min"===a?this.xk(a,b):"step"===a?this.lx(b):b;"disabled"!=a&&this._super(a,b,c);"readOnly"===a&&(this.options.AO=b);"disabled"===a&&(this.options.disabled=b);switch(a){case "value":this.Xx();this.Ct();break;case "min":case "max":this.jT();this.Xx();this.Ct();break;case "orientation":case "readonly":case "step":case "type":case "disabled":this.Hia()}},
Hia:function(){this.zU();this.LT();this.hf()},LW:function(){var a=this.options.value;return a=this.Kh(a)},dea:function(a){return this.Kh(this.options.value[a])},Kh:function(a){if(a<=this.Vc())return this.Vc();if(a>=this.Ve())return this.Ve();var b=0<this.options.step?this.options.step:1,c=(a-this.Vc())%b;a-=c;2*Math.abs(c)>=b&&(a+=0<c?b:-b);return parseFloat(a.toFixed(5))},jT:function(){var a=this.Vc();this.max=0!==(this.options.max-a)/this.options.step%1?this.options.max-(this.options.max-a)%this.options.step:
this.options.max},Vc:function(){return this.options.min},Ve:function(){return this.max},MV:function(){var a;a=0<this.options.step?(this.Ve()-this.Vc())/this.options.step:100;a=(this.hc()?this.Rc.height():this.Rc.width())/a;1>a&&(a=1);return this.hc()?[1,a]:[a,1]},qJ:function(a){return(this.fq(a)-this.Vc())/(this.Ve()-this.Vc())},Xx:function(){var a,b,c,e;this.zf?this.ig.toArray().forEach(function(b,c){var d=f(b);a=100*this.qJ(c);this.ae()&&!this.hc()&&(a=100-a);this.hc()?f(d).css({top:100-a+"%"}):
f(d).css({left:a+"%"});f(d).attr("aria-valuenow",this.fq(c));this.M_(a,c)},this):(b=this.LW(),c=this.Vc(),e=this.Ve(),a=e!==c?(b-c)/(e-c)*100:0,this.ae()&&!this.hc()&&(a=100-a),this.hc()?this.jo.css({top:100-a+"%"}):this.jo.css({left:a+"%"}),f(this.jo).attr("aria-valuenow",b),this.J_(a))},J_:function(a){var b=this.options.type;this.hc()?("fromMin"===b&&this.Cb.css({height:a+"%"}),"fromMax"===b&&this.Cb.css({height:100-a+"%"})):this.ae()?("fromMin"===b&&this.Cb.css({width:100-a+"%"}),"fromMax"===b&&
this.Cb.css({width:a+"%"})):("fromMin"===b&&this.Cb.css({width:a+"%"}),"fromMax"===b&&this.Cb.css({width:100-a+"%"}))},M_:function(a,b){var c=this.Cb.attr("id");if(0==b)switch(c=100*this.qJ(1),this.options.type){case "fromMin":this.hc()?this.Cb.css({height:a+"%"}):this.Cb.css({width:a+"%"});break;case "range":this.hc()?(this.Cb.css({top:100-c+"%"}),this.Cb.css({height:c-a+"%"})):this.ae()?(this.Cb.css({left:100-c+"%"}),this.Cb.css({width:c-(100-a)+"%"})):(this.Cb.css({left:a+"%"}),this.Cb.css({width:c-
a+"%"}))}else{var e=100*this.qJ(0);switch(this.options.type){case "fromMax":this.hc()?this.Cb.css({height:100-a+"%"}):this.Cb.css({width:100-a+"%"});break;case "range":this.hc()?document.getElementById(c)&&(this.Cb.css({top:100-a+"%"}),this.Cb.css({height:a-e+"%"})):this.ae()?document.getElementById(c)&&(this.Cb.css({left:a+"%"}),this.Cb.css({width:-a+100-e+"%"})):document.getElementById(c)&&this.Cb.css({width:a-parseInt(document.getElementById(c).style.left,10)+"%"})}}},sla:{keydown:function(a){var b,
c,e,g=f(a.target).data("oj-slider-thumb-index");this.hg=g;switch(a.keyCode){case f.ui.keyCode.HOME:case f.ui.keyCode.END:case f.ui.keyCode.PAGE_UP:case f.ui.keyCode.PAGE_DOWN:case f.ui.keyCode.UP:case f.ui.keyCode.RIGHT:case f.ui.keyCode.DOWN:case f.ui.keyCode.LEFT:a.preventDefault(),f(a.target).addClass("oj-active")}e=this.options.step;b=this.zf?c=this.fq(g):c=this.vW();switch(a.keyCode){case f.ui.keyCode.HOME:c=this.Vc();break;case f.ui.keyCode.END:c=this.Ve();break;case f.ui.keyCode.PAGE_UP:c=
this.Kh(b+(this.Ve()-this.Vc())/this.MY);break;case f.ui.keyCode.PAGE_DOWN:c=this.Kh(b-(this.Ve()-this.Vc())/this.MY);break;case f.ui.keyCode.UP:if(b===this.Ve())return;c=this.Kh(b+e);break;case f.ui.keyCode.RIGHT:if(!this.ae()||this.hc()){if(b===this.Ve())return;b+=e}else{if(b===this.Vc())return;b-=e}c=this.Kh(b);break;case f.ui.keyCode.DOWN:if(b===this.Vc())return;c=this.Kh(b-e);break;case f.ui.keyCode.LEFT:if(!this.ae()||this.hc()){if(b===this.Vc())return;b-=e}else{if(b===this.Ve())return;b+=e}c=
this.Kh(b)}this.Kq(a,g,c)},keyup:function(a){var b=f(a.target).data("oj-slider-thumb-index");this.hg=b;this.Ch(a,b,!1);f(a.target).removeClass("oj-active");this.hg=null}},Ud:function(a,d){var c=this.options,e=this;this._superApply(arguments);b.re.Rk([{V:"disabled",vc:!0},{V:"value"},{V:"title"},{V:"min"},{V:"max"},{V:"step"}],d,this,function(a){for(var b=["value","step","min","max"],d=0;d<b.length;d++){var f=b[d],m=f in a?a[f]:c[f];null!=m&&("step"===f?a[f]=e.lx(m):"min"===f||"max"===f?a[f]=e.xk(f,
m):"value"===f&&(Array.isArray(m)?a[f]=m:a[f]=e.xk(f,m)))}});if(void 0===c.value)throw Error(this.A("noValue"));if(null!=c.min&&null!=c.max){if(c.max<c.min)throw Error(this.A("maxMin"));if(c.value<c.min||c.value>c.max)throw Error(this.A("valueRange"));}},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-slider-thumb-0"===a?this.widget().find(".oj-slider-thumb")[0]:"oj-slider-thumb-1"===a?this.widget().find(".oj-slider-thumb")[1]:"oj-slider-bar"===a?
this.widget().find("."+a)[0]:"oj-slider-bar-value"===a?this.widget().find("."+a)[0]:null},getSubIdByNode:function(a){if(null!=a){if(a.id===this.pJ(0)&&f(a).hasClass("oj-slider-thumb"))return{subId:"oj-slider-thumb-0"};if(a.id===this.pJ(1)&&f(a).hasClass("oj-slider-thumb"))return{subId:"oj-slider-thumb-1"};if(f(a).hasClass("oj-slider-bar"))return{subId:"oj-slider-bar"};if(f(a).hasClass("oj-slider-bar-value"))return{subId:"oj-slider-bar-value"}}return null},_GetDefaultStyleClass:function(){return"oj-slider"},
xk:function(a,b){var c;c=null!==b?+b:b;if(isNaN(c))throw Error(this.A("optionNum",{option:a}));return c},lx:function(a){if(null===a)return 1;a=this.xk("step",a);if(0>=a)throw Error(this.A("invalidStep"));if(null===a||0>=a)a=1;return a},Lqa:function(){return this.Rc.offset().left+this.Rc.width()},Tqa:function(){return this.Rc.offset().left},kT:function(a){var b=this.MV(),c=a[0].style,e=this;a.draggable({axis:this.hc()?"y":"x",grid:b,disabled:!1,start:function(b){a[0]==f(e.ig)[0]?e.hg=0:a[0]==f(e.ig)[1]&&
(e.hg=1);e.Yfa(b,a)},drag:function(b,d){var k=d.position;e.hc()?(c.left="",k.left=""):(c.top="",k.top="");e.Cha(b,a);e.hc()?(0>k.top&&(k.top=0),k.top>e.Rc.height()&&(k.top=e.Rc.height())):(0>k.left&&(k.left=0),k.left>e.Rc.width()&&(k.left=e.Rc.width()));if(e.zf){var l;l=0==e.hg?f(e.ig[1]):f(e.ig[0]);if(e.hc()){var m=a.outerHeight()/2,n=e.Rc.offsetParent().offset().top;a.offset();l=l.offset().top+m-n}else m=a.outerWidth()/2,n=e.Rc.offsetParent().offset().left,a.offset(),l=l.offset().left+m-n;0==e.hg?
e.hc()?k.top<l&&(k.top=l):e.ae()?k.left<l&&(k.left=l):k.left>l&&(k.left=l):e.hc()?k.top>l&&(k.top=l):e.ae()?k.left>l&&(k.left=l):k.left<l&&(k.left=l)}},stop:function(b){this.style.width="";this.style.height="";e.dx(b,a)}})},Ct:function(){this.options.disabled||(this.zf?this.ig.toArray().forEach(function(a){a=f(a);this.kT(a)},this):this.kT(this.jo))},Hqa:function(){this.zf?this.ig.toArray().forEach(function(a){a=f(a);a.is(".ui-draggable")&&a.draggable("disable")},this):this.jo.is(".ui-draggable")&&
this.jo.draggable("disable")}})})()});