/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b){(function(){b.ya("oj.ojSwitch",$.oj.editableValue,{version:"1.1.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:!1,readOnly:!1,required:!1,title:"",value:!1},refresh:function(){this._super();this.Aa()},widget:function(){return this.Bl},getNodeBySubId:function(b){var a,d=this.widget();a=null==b||null==b.subId?d:null;return a||(b=b.subId,"oj-switch-thumb"!==b&&"oj-switch-track"!==b)?a||null:d.find("."+b)[0]},
getSubIdByNode:function(b){var a=$(this.element).attr("id"),d,c=null;null!=b&&($(b).hasClass("oj-switch-track")||$(b).hasClass("oj-switch-thumb"))&&(d=$(b).parents("div.oj-switch").find("input.oj-component-initnode").attr("id"),a===d&&$(b).hasClass("oj-switch-track")?c={subId:"oj-switch-track"}:a===d&&$(b).hasClass("oj-switch-thumb")&&(c={subId:"oj-switch-thumb"}));return c},xa:{Z8:"SwitchOFF",a9:"SwitchON"},Ud:function(f,a){var d;this._super(f,a);b.re.Rk([{V:"disabled",vc:!0},{V:"readonly",option:"readOnly",
vc:!0},{V:"required",vc:!1,We:function(){return!1}},{V:"checked",option:"value",vc:!1,We:function(a){return a?!0:!1}},{V:"title"}],a,this);d=this.option("value");this.option({required:!1,value:!!d},{_context:{Ec:!0,Za:!0}})},_ComponentCreate:function(){this._super();if(!this.element.is("input"))throw Error("ojSwitch can be bound to INPUT only.");this.EX=this.element.css("display");this.element.css("display","none").attr("type","checkbox").attr("checked",this.option("value")).attr("tabindex","-1").attr("disabled",
this.option("disabled")).attr("readonly",this.option("readOnly"));this.Bl=this.element.wrap("\x3cdiv\x3e\x3c/div\x3e").parent().addClass("oj-switch oj-component oj-form-control");this.Bl.append("\x3cdiv class\x3d'oj-switch-container'\x3e\x3cdiv class\x3d'oj-switch-track'\x3e\x3cdiv class\x3d'oj-switch-thumb' tabIndex\x3d'0'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");this.al=this.Bl.find(".oj-switch-thumb");this.al.attr("role","switch checkbox");this.aka(this.element,this.al);this.Aa()},aka:function(b,
a){var d=b.prop("id"),c=b.attr("aria-labelledby"),e=b.attr("aria-label");e?a.attr("aria-label",e):c?a.attr("aria-labelledby",c):d&&(d=$("label[for\x3d'"+d+"']"))&&(d.attr("id")?a.attr("aria-labelledby",d.attr("id")):a.attr("aria-label",$(d).text()))},Aa:function(){var b=$(this.widget()),a=this.option("title");this.xj();if(void 0!==b){this.element.attr("checked",this.option("value"));b.removeClass("oj-disabled oj-read-only oj-selected oj-hover oj-active");$(this.al).attr("tabindex","0");$(this.al).html("");
if(this.option("disabled")||this.option("readOnly"))this.option("disabled")?b.addClass("oj-disabled"):(b.addClass("oj-read-only"),$(this.al).html(this.Dka())),$(this.al).removeAttr("tabindex");this.option("value")&&b.addClass("oj-selected");void 0!==a&&$(this.al).attr("title",a);$(this.al).attr("aria-checked",this.option("value"));$(this.al).removeAttr("aria-disabled");b.removeAttr("aria-disabled");this.qv()||$(this.al).attr("aria-disabled","true")}},Dka:function(){var b=this.xa.Z8;this.option("value")&&
(b=this.xa.a9);return this.A(b)},xj:function(){this._off(this.Bl,"keydown keyup mousedown mouseup mouseleave mouseenter touchstart");this.qv()&&(this._on(this.Bl,this.jla),this._hoverable(this.Bl));this._focusable(this.Bl)},jla:{keydown:function(b){if(b.which===$.ui.keyCode.ENTER||b.which===$.ui.keyCode.SPACE)$(b.currentTarget).addClass("oj-active"),b.preventDefault()},keyup:function(b){b.which!==$.ui.keyCode.ENTER&&b.which!==$.ui.keyCode.SPACE||this.ec(!this.option("value"),b)},mousedown:function(b){1===
b.which&&$(b.currentTarget).addClass("oj-active")},mouseup:function(b){1===b.which&&this.ec(!this.option("value"),b)},mouseleave:function(b){1===b.which&&$(b.currentTarget).removeClass("oj-active")},mouseenter:function(b){1===b.which&&$(b.currentTarget).addClass("oj-active")},Vra:function(b){this.ec(!this.option("value"),b);b.preventDefault()}},_GetDefaultStyleClass:function(){return"oj-switch"},ira:function(){return"switch checkbox"},_destroy:function(){this.Bl.find(".oj-switch-track").remove();
b.v.unwrap(this.element);this.us(this.element);return this._super()},Td:function(){return this.Bl},_setOption:function(b,a,d){switch(b){case "disabled":case "readOnly":case "value":a=!!a;break;case "required":a=!1;break}this._super(b,a,d);this.Aa()}})})()});