/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise","ojdnd","ojs/ojdomscroller","ojs/ojeditablevalue","ojs/ojmenu","ojs/ojdatasource-common","ojs/ojpagingtabledatasource","ojs/ojflattenedtreetabledatasource"],function(b,f){(function(){b.ya("oj.ojTable",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3ctable\x3e",widgetEventPrefix:"oj",options:{accessibility:null,currentRow:null,data:null,display:"list",dnd:{drag:null,drop:null,reorder:{columns:"disabled"}},emptyText:null,horizontalGridVisible:"auto",
rowRenderer:null,scrollPolicy:"auto",scrollPolicyOptions:{fetchSize:25,maxCount:500},selection:[],selectionMode:null,verticalGridVisible:"auto",columns:[{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,id:null,sortable:"auto",sortProperty:null,style:null}],columnsDefault:{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,
headerRenderer:null,headerStyle:null,headerText:null,sortable:"auto",sortProperty:null,style:null},beforeCurrentRow:null,ready:null,sort:null,optionChange:null},xa:{Z7:"msgFetchingData",d8:"msgNoData",O7:"labelSelectColumn",nR:"labelSelectRow"},dc:{TQ:"Did not change current row due to error.",SQ:"Error detail: {error}.",g7:"Did not change current row due to unavailable row index.",f7:"Unavailable row index: {rowIdx}.",o7:"Invalid row index value.",n7:"Row index: {rowIdx}.",RQ:"Invalid data type.",
QQ:"Please specify the appropriate data type.",k7:"Invalid element type.",j7:"Only a \x3ctable\x3e element can be specified for ojTable.",i7:"Exceeded maximum rows for table scrolling.",h7:"Please reload with smaller data set."},Dz:"id",Yi:"data",pv:"indexes",$m:"key",$r:"keys",xe:"startIndex",Re:"endIndex",BQ:"pageSize",Rd:"column",Sd:"row",pqa:"_headerColumn",qqa:"_headerColumnText",mqa:"_headerColumnAsc",oqa:"_headerColumnDsc",N6:"_hdrCol",fs:"_focusedCalled",Qz:"auto",Ng:"enabled",kn:"disabled",
CR:"none",ki:{vs:"single",wp:"multiple"},h8:{Lg:"auto",R7:"loadMoreOnScroll"},zh:{np:"ascending",bs:"descending"},d7:"oj-table-dnd-reorder-table-id",Tb:{kR:32,D7:13,Nz:38,Mz:40,iR:37,jR:39,hR:36,gR:35,F7:9,E7:27,vp:"shiftKey"},getContextByNode:function(a){return this.getSubIdByNode(a,!0)},getDataForVisibleRow:function(a){a=this.p().me(a);return null!=a?a.data("rowData"):null},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var d=a.subId;if("oj-table-cell"===d){var d=
0,c=this.Ya();c instanceof b.ka&&(d=c.getStartItemIndex());d+=parseInt(a.rowIndex,10);a=a.columnIndex;return this.p().Kna(d)[a]}if("oj-table-header"===d||"oj-table-sort-ascending"===d||"oj-table-sort-descending"===d){if(a=a.index,a=f(this.p().Mna()[a]),null!=a){if("oj-table-header"===d)return a[0];a="oj-table-sort-ascending"===d?a.find("."+b.f.C.pp):a.find("."+b.f.C.Zr);if(0<a.length)return a[0]}}else if("oj-table-footer"===d&&(a=a.index,a=this.p().Lna()[a],null!=a))return a;return null},getSubIdByNode:function(a,
d){var c=f(a).closest("."+b.f.C.xs);if(0<c.length){var e=0,g=this.Ya();g instanceof b.ka&&(e=g.getStartItemIndex());return{subId:"oj-table-cell",rowIndex:e+this.p().Eo(c),columnIndex:this.p().je(c)}}c=f(a).closest("."+b.f.C.pp);if(0<c.length)return{subId:d?"oj-table-header":"oj-table-sort-ascending",index:this.p().je(c)};c=f(a).closest("."+b.f.C.Zr);if(0<c.length)return{subId:d?"oj-table-header":"oj-table-sort-descending",index:this.p().je(c)};c=f(a).closest("."+b.f.C.Zm);if(0<c.length)return{subId:"oj-table-header",
index:this.p().je(c)};c=f(a).closest("."+b.f.C.Dp);return 0<c.length?{subId:"oj-table-footer",index:this.p().je(c)}:null},refresh:function(){this._super();this.Ld()},refreshRow:function(a){var d=this.Ya();if(!d)return!1;var c=this.p().Kf();if(isNaN(a)||0>a||null!=c&&a>=c.length)throw d=this.dc.o7,c=b.ha.Ib(this.dc.n7,{rowIdx:a.toString()}),new RangeError(d+"\n"+c);var c=this.jq(a),e=d.get(c);if(null==e)return!1;var g=this;return this.yi(function(){return e.then(function(b){g.HC(a,b)}).then(function(){return!0})})},
widget:function(){var a=this.p().kc();return null!=a?a:this.element},_ComponentCreate:function(){this._super();this.kw();this.Wia();this._on(this.Cl);if(this.kK()){var a=this.p().kc();this._on(a,this.$ba)}this.Xia();this.Eq();this.eT=f.extend(!0,{},this.options)},hf:function(){this._super();this.p().E1(this.lj.bind(this));this.dC()},lf:function(a,b,c){var e={};this.dj=b.originalEvent;if(!(this.jK(f(this.dj.target))||this.Hga(f(this.dj.target))||"touch"==c&&this.Iga(f(this.dj.target)))){var g=this.p().Fo(f(this.dj.target),
"oj-table-column-header-cell"),g=null==g?this.p().Nc(this.wS):g,h=this.p().Fo(f(this.dj.target),"oj-table-data-cell");null!=h&&(g=this.p().je(h),g=this.p().Nc(g));"keydown"===this.dj.type&&(h=this.PL.Mc(),this.dj.target==h[0]?null!=g&&null!=g[0]?e.position={my:"start top",at:"start bottom",of:g[0]}:(h=this.jj(),0<=h?(h=this.p().me(h),e.position={my:"start top",at:"start bottom",of:h[0]}):e.position={my:"start top",at:"start bottom",of:this.dj.target}):e.position={my:"start top",at:"start bottom",
of:this.dj.target});g.attr("data-oj-sortable")==this.Ng?(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").removeClass("oj-disabled"),f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").removeClass("oj-disabled")):(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").addClass("oj-disabled"),f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").addClass("oj-disabled"));this.nf(b,c,e)}},_destroy:function(){this.Ya();this.Dk();this.Ek();this.p().hd().removeAttr(b.Components.hn);
this.element.children().remove("."+b.f.C.zG);this.element.children().remove("."+b.f.C.rG);this.element.children().remove("."+b.f.C.yG);this.element.children().remove("."+b.f.C.AG);this.element.children().remove("."+b.f.C.dS);b.v.unwrap(this.element,this.p().kc());this.element.removeClass(b.f.C.YR)},kw:function(){this.kka(function(){this.p().zE();this.Rt(this.options.selection);this.vi()&&!this.kU&&this.cI.checkViewport().then(this.MU,null)});if(!this.element.is("table"))throw new RangeError(this.dc.k7+
"\n"+this.dc.j7);this.element.addClass(b.f.C.f9);this.p().Oma(this.nC(),this.eY());this.p().Hpa();this.yZ();this.Bx();this.xZ();this.p().zE();this.vi()&&this.EZ();this.options.disabled&&this.disable();this.tj()},Cl:{blur:function(a){var b=this.p().Mc();0<b.has(a.relatedTarget).length||null!=a.originalEvent&&a.originalEvent.explicitOriginalTarget==b[0]||(this.Z$(),this.yT(),this.zT(!1),this.VC(!1))},focus:function(a){this.qT(a)},"focus .oj-table-column-header-acc-asc-link":function(a){var b=this;setTimeout(function(){b.qT(a)},
0)},"click .oj-table-checkbox-acc-select-column":function(a){var b=this.p().je(f(a.currentTarget)),c=f(a.currentTarget).is(":checked");c&&this.zk(b,!0,!0,null);this.Ak(b,c,a.currentTarget,a,!0);a.stopPropagation()},"click .oj-table-checkbox-acc-select-row":function(a){var b=this.p().Eo(f(a.currentTarget)),c=f(a.currentTarget).is(":checked"),e=!1;c&&(e=this.Hh(b,!0,!0,null,a,!0));e&&this.dh(b,c,a.currentTarget,a,!0);a.stopPropagation()},keydown:function(a){if(!(this.jK(f(a.target))||null!=this.p().Pk()&&
0<this.p().Pk().has(a.target).length)&&(this.G9(a.keyCode),1==this.Fl().length||2==this.Fl().length&&a[this.Tb.vp])){if(this.xf(this.Tb.Nz)||this.xf(this.Tb.Mz)||this.xf(this.Tb.kR)||this.xf(this.Tb.hR)||this.xf(this.Tb.gR))a.preventDefault(),a.stopPropagation();this.xf(this.Tb.Nz)||this.xf(this.Tb.Mz)?this.Xea(a):this.xf(this.Tb.iR)||this.xf(this.Tb.jR)?this.Vea(a):this.xf(this.Tb.F7)&&this.Wea(a)}},keyup:function(a){if(!(this.jK(f(a.target))||null!=this.p().Pk()&&0<this.p().Pk().has(a.target).length)){if(1==
this.Fl().length){var b=this.Fl()[0];b==this.Tb.kR?this.bfa(a):b==this.Tb.D7?this.Zea(a):b==this.Tb.hR?this.afa(a):b==this.Tb.gR?this.Yea(a):b==this.Tb.E7&&this.$ea(a);this.cL(b)}this.cL(a.keyCode)}},"mousedown .oj-table-body":function(a){this.ah=this.p().Eo(f(a.target));null!=this.ah&&(a=this.p().me(this.ah),null!=a&&a.prop("draggable")?this.ah=null:null!=this.ah&&this.Pp())},"mouseup .oj-table-body":function(){this.ah=null},"mouseenter .oj-table-body-row":function(a){f(a.currentTarget).addClass(b.f.la.Xj);
this.HJ(a.target)},"mouseleave .oj-table-body-row":function(a){f(a.currentTarget).removeClass(b.f.la.Xj)},"mousedown .oj-table-column-header-cell":function(a){var b=this.p().je(f(a.currentTarget));this.zk(b,!0,!0,a);f(a.target).data(this.fs,!0)},"mouseenter .oj-table-column-header-cell":function(a){f(a.currentTarget).addClass(b.f.la.Xj);a=this.p().je(f(a.currentTarget));this.a0(a)},"mouseleave .oj-table-column-header-cell":function(a){f(a.currentTarget).removeClass(b.f.la.Xj);a=this.p().je(f(a.currentTarget));
this.rq(a,!0);this.rq(a,!1)},"mousedown .oj-table-data-cell":function(a){var b=this.p().Eo(f(a.currentTarget));this.Hh(b,!0,!0,a.currentTarget,a);f(a.target).data(this.fs,!0)},"mouseenter .oj-table-data-cell":function(a){f(a.currentTarget).addClass(b.f.la.Xj)},"mouseleave .oj-table-data-cell":function(a){f(a.currentTarget).removeClass(b.f.la.Xj)},"click .oj-table-column-header-asc-link":function(a){var b=this.p().je(f(a.target)),c=this.p().Nc(b);c&&(c.data("sorted")==this.zh.np?this.pk(b,!1,a):this.pk(b,
!0,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-asc-link":function(a){var b=this.p().je(f(a.target));this.pk(b,!0,a);a.preventDefault();a.stopPropagation()},"click .oj-table-column-header-dsc-link":function(a){var b=this.p().je(f(a.target)),c=this.p().Nc(b);c&&(c.data("sorted")==this.zh.bs?this.pk(b,!0,a):this.pk(b,!1,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-dsc-link":function(a){var b=this.p().je(f(a.target));this.pk(b,!1,a);
a.preventDefault();a.stopPropagation()},"click .oj-table-data-cell":function(a){var d=this.p().Eo(f(a.currentTarget));if(!f(a.target).data(this.fs)){var c=this.Hh(d,!0,!0,a.currentTarget,a);f(a.target).data(this.fs,!1);if(!c)return}if(a[this.Tb.vp]){if(c=this.qda(),null!=c)if(window.getSelection().removeAllRanges(),d<c){var e;for(e=d;e<=c;e++)this.dh(e,!0,a.currentTarget,a,!0)}else for(e=c;e<=d;e++)this.dh(e,!0,a.currentTarget,a,!0)}else b.v.Io(a)?this.dh(d,!this.Fw(d),a.currentTarget,a,!0):0==this.Fl().length&&
(this.Pp(),this.dh(d,!this.Fw(d),a.currentTarget,a,!0),this.kK()&&this.ht()==this.ki.wp&&this.p().Rma(d))},"contextmenu .oj-table-data-cell":function(a){var b=this.p().Eo(f(a.currentTarget)),b=this.jq(b);this.Xl({rowKey:b},a)},"click .oj-table-column-header-cell":function(a){var d=this.p().je(f(a.currentTarget));f(a.target).data(this.fs)||(this.zk(d,!0,!0,a),f(a.target).data(this.fs,!1));if(a[this.Tb.vp]){var c=this.pda();if(null!=c)if(d<c){var e;for(e=d;e<=c;e++)this.Ak(e,!0,a.currentTarget,a,!0)}else for(e=
c;e<=d;e++)this.Ak(e,!0,a.currentTarget,a,!0)}else b.v.Io(a)?this.Ak(d,!this.yw(d),a.currentTarget,a,!0):0==this.Fl().length&&(this.aw(),this.Ak(d,!this.yw(d),a.currentTarget,a,!0),this.Vg().M4(d,!0))},"dragstart .oj-table-column-header-cell":function(a){return this.Vg().Vna(a)},"dragenter .oj-table-column-header-cell":function(a){return this.Vg().Sna(a)},"dragover .oj-table-column-header-cell":function(a){return this.Vg().Una(a)},"dragleave .oj-table-column-header-cell":function(a){return this.Vg().Tna(a)},
"drop .oj-table-column-header-cell":function(a){return this.Vg().Wna(a)},"dragend .oj-table-column-header-cell":function(){return this.Vg().Rna()},"dragstart .oj-table-body-row":function(a){return this.Vg().loa(a)},"drag .oj-table-body-row":function(a){return this.Vg().goa(a)},"dragend .oj-table-body-row":function(a){return this.Vg().hoa(a)},"dragenter .oj-table-body":function(a){return this.Vg().ioa(a)},"dragover .oj-table-body":function(a){return this.Vg().koa(a)},"dragleave .oj-table-body":function(a){return this.Vg().joa(a)},
"drop .oj-table-body":function(a){return this.Vg().moa(a)}},$ba:{touchstart:function(a){if(1==a.originalEvent.touches.length&&this.ht()==this.ki.wp)if(f(a.target).hasClass(b.f.C.wG)||f(a.target).hasClass(b.f.C.$R))a.preventDefault(),this.ah=this.p().Q2().data("rowIdx");else if(f(a.target).hasClass(b.f.C.vG)||f(a.target).hasClass(b.f.C.ZR))a.preventDefault(),this.ah=this.p().R2().data("rowIdx")},touchmove:function(a){null!=this.ah&&(a.preventDefault(),a=this.IW(a),this.HJ(a))},touchend:function(a){null!=
this.ah&&(a=this.IW(a),this.HJ(a));this.ah=null},touchcancel:function(){this.ah=null}},Ld:function(){var a=null,b=!1;this.i!=this.options[this.Yi]&&(this.wH(),null==this.i?b=!0:a=0,this.vi()&&(null!=this.cI&&this.cI.destroy(),this.EZ()));this.PT!=this.p().n2()&&this.p().E1(this.lj.bind(this));this.p().Ema();this.p().dpa();this.Sia();if(b)return this.dC();var c=this;this.yi(function(){return c.fC(a)})},_setOption:function(a,b){this._superApply(arguments);this.Nga(a,b)?this.Ld():"selection"==a?(this.Pp(),
this.aw(),this.Rt(b)):"currentRow"==a&&this.Xl(b,null,!0)},G9:function(a){var b=!1,c;for(c in this.Tb)this.Tb.hasOwnProperty(c)&&this.Tb[c]==a&&(b=!0);if(b){b=this.Fl();c=!1;var e,g=b.length;for(e=0;e<g;e++)if(b[e]==a){c=!0;break}c||b.push(a)}},CS:function(a,b,c,e){var g=this.p().H1(a,b[this.$m]);this.p().RO(g,!0);this.p().p3(a,g,b,c);this.HC(a,b,g,c,e,!0)},qT:function(a){var b=this.jj(),c=this.El();null==b&&null==c&&(this.nC()?this.Hh(0,!0,!0,null,a):this.zk(0,!0,!1,a))},X$:function(){this.xn=null;
this.VC(!1)},wH:function(){null!=this.i&&this.Dk();this.i=null},fk:function(){this.Gfa();this.Hfa();this.kU=!1},Z$:function(){this.oK=[]},yT:function(){var a=this.El();null!=a&&this.zk(a,!1,!1,null);this.wS=-1},zT:function(a){null!=this.jj()&&this.Hh(-1,!0,a,null,null)},aw:function(){var a=this.sW(),b,c=a.length;for(b=0;b<c;b++)this.Ak(a[b],!1,null,null,!1)},Pp:function(){var a=this.Gw(),b,c=a.length;for(b=0;b<c;b++)this.dh(a[b],!1,null,null,!1);this.kK()&&this.ht()==this.ki.wp&&this.p().kpa()},CT:function(a){var d=
this.Yda();if(null!=d){var c=this.p().Nc(d),e=c.data("sorted");c.data("sorted",null);d!=a?e==this.zh.np?this.rq(d,!0):this.rq(d,!1):(c.find("."+b.f.C.pp).removeClass(b.f.la.bd),c.find("."+b.f.C.Zr).removeClass(b.f.la.bd))}},aca:function(a){var d=this;this.yi(function(){var c=!1;if(1<a.length){var e,g=a.length,h=!0;for(e=0;e<g;e++)if(0!=e&&a[e-1].Rh!=a[e].Rh-1){h=!1;break}if(h){c=d.p().hd();h=f(document.createDocumentFragment());g=a.length;for(e=0;e<g;e++)d.CS(a[e].Rh,a[e].row,h,a[0].Rh);0==a[0].Rh?
c.prepend(h):(e=d.p().me(a[0].Rh),null!=e?c[0].insertBefore(h[0],e[0]):c[0].insertBefore(h[0],null));d.p().Vq();b.Components.Nf(c[0]);c=!0}}if(!c)for(g=a.length,e=0;e<g;e++)d.CS(a[e].Rh,a[e].row);d.p().Vq();d.Bx()})},bca:function(a){var b=this;this.yi(function(){var c,e=a.length;for(c=0;c<e;c++)b.HC(a[c].Rh,a[c].row);b.Bx()})},cca:function(a){var d=this,c=this.DV(),e=null!=c?c.rowKey:null;this.yi(function(){var c,f,k=a.length;for(c=0;c<k;c++)d.p().u4(a[c].Rh),null!=e&&(f=a[c].row[d.Dz],b.b.gh(f,e)&&
(d.Xl(null,null),e=null));d.Bx();c=d.p().Kf();null!=c&&0!=c.length||this.X_()})},vb:function(){this.xn||(this.xn=this.xV());return this.xn},xV:function(){var a=this.options.columns,b=this.options.columnsDefault;if((0==a.length||1==a.length&&null==a[0].id&&null==a[0].headerText&&null==a[0].field)&&null==b.headerText&&null==b.field)return[];var c=[],e,g=a.length;for(e=0;e<g;e++)c[e]=f.extend({},b,a[e]);a=[];b=c.length;for(e=0;e<b;e++)a.push(c[e]);e=this.Ya();c=!1;null!=e&&"full"==e.getCapability("sort")&&
(c=!0);for(e=0;e<b;e++)null==a[e][this.Dz]&&(a[e][this.Dz]=this.N6+e),null!=a[e].sortable&&a[e].sortable!=this.Qz||!c||(a[e].sortable=this.Ng);return a},vV:function(a){var d=this.vb();if(null!=d){var c,e,g=d.length;for(c=0;c<g;c++)if(e=d[c],b.b.gh(e.id,a))return c}return null},wV:function(a){a=this.p().Mc().find(a);var b=[];if(a&&0<a.length){var c,e,g,h,k,l=a.length;for(c=0;c<l;c++){h=this.p().je(f(a.get(c)));g=!1;k=b.length;for(e=0;e<k;e++)b[e]==h&&(g=!0);g||b.push(h)}}return b},rB:function(a){var b=
this.vb();return null!=b&&a<b.length?b[a][this.Dz]:null},En:function(a,b){var c=this.vb()[a];return"cell"==b?c.renderer:"footer"==b?c.footerRenderer:"header"==b?c.headerRenderer:null},DV:function(){return this.Ya()?this.Wp:null},Ya:function(){if(!this.i&&null!=this.options.data){var a=this.options.data;if(a instanceof b.T||a instanceof b.ka)this.i=a;else throw Error(this.dc.RQ+"\n"+this.dc.QQ);this.Eq()}return this.i},El:function(){return this.wV("."+b.f.C.Zm+"."+b.f.la.Zi)[0]},jj:function(){return this.qW("."+
b.f.C.Cp+"."+b.f.la.Zi)[0]},Mqa:function(a){return this.MI(a).Dj},yw:function(a){return this.MI(a).selected},sB:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Rd]},MI:function(a){a=this.p().Nc(a);return{Dj:a.hasClass(b.f.la.Zi),selected:a.hasClass(b.f.la.bd)}},Fl:function(){this.oK||(this.oK=[]);return this.oK.reverse()},pda:function(){return null!=this.Tn&&0<this.Tn.length?this.Tn[0]:null},qda:function(){return null!=this.Un&&0<this.Un.length?this.Un[0]:null},
Uda:function(a,b){var c=[];if(null!=a){var e,g=a[this.pv].length;for(e=0;e<g;e++)c.push({row:{data:a[this.Yi][e],key:a[this.$r][e],index:a[this.pv][e]},Rh:b+e})}return c},Dw:function(a){var d=this.p().Kf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)if(b.b.gh(f(d[c]).data("rowKey"),a))return c}return null},aq:function(a){var d=this.p().Kf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)if(b.b.gh(f(d[c]).data("rowKey"),a))return a=this.Ya(),d=0,a instanceof b.ka&&(d=a.getStartItemIndex()),
c+d}return null},qW:function(a){a=this.p().Mc().find(a);var b=[];if(a&&0<a.length){var c,e,g,h,k,l=a.length;for(c=0;c<l;c++){g=this.p().Eo(f(a.get(c)));k=!1;h=b.length;for(e=0;e<h;e++)b[e]==g&&(k=!0);k||b.push(g)}}return b},Ew:function(a){var d=this.p().Kf();if(null!=d&&0<d.length){var c=this.Ya(),e=0;c instanceof b.ka&&(e=c.getStartItemIndex());for(var g=d.length,c=0;c<g;c++)if(e+c==a)return f(d[c]).data("rowKey")}return null},jq:function(a){a=this.p().me(a);return null!=a?a.data("rowKey"):null},
rW:function(){return this.options.rowRenderer},Fw:function(a){return this.p().me(a).hasClass(b.f.la.bd)},ht:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Sd]},sW:function(){return this.wV("."+b.f.C.Zm+"."+b.f.la.bd)},Gw:function(){return this.qW("."+b.f.C.Cp+"."+b.f.la.bd)},tW:function(){var a=this.Gw(),b=this.sW(),c=null,e=!0;if(null!=a&&0<a.length)c=a;else if(null!=b&&0<b.length)c=b,e=!1;else return null;var a=[],b=0,g=null,f,k,l,m,n,p=c.length;for(n=0;n<
p;n++)l=c[n],0==n?(f={},f[this.xe]={},f[this.Re]={},f.startKey={},f.endKey={},e?(m=this.jq(l),k=this.aq(m),f.startKey[this.Sd]=m,f.endKey[this.Sd]=m,f[this.xe][this.Sd]=k,f[this.Re][this.Sd]=k):(f[this.xe][this.Rd]=l,f[this.Re][this.Rd]=l,m=this.rB(l),f.startKey[this.Rd]=m,f.endKey[this.Rd]=m),a[0]=f):(f=a[b],e?(m=this.jq(l),k=this.aq(m),f.endKey[this.Sd]=m,f[this.Re][this.Sd]=k):(f[this.Re][this.Rd]=l,m=this.rB(l),f.endKey[this.Rd]=m),l!=g+1&&(e?(m=this.jq(g),k=this.aq(m),f.endKey[this.Sd]=m,f[this.Re][this.Sd]=
k,f={},f[this.xe]={},f[this.Re]={},f.startKey={},f.endKey={},m=this.jq(l),k=this.aq(m),f.startKey[this.Sd]=m,f.endKey[this.Sd]=m,f[this.xe][this.Sd]=k,f[this.Re][this.Sd]=k):(f[this.Re][this.Rd]=g,m=this.rB(g),f.endKey[this.Rd]=m,f={},f[this.xe]={},f[this.Re]={},f.startKey={},f.endKey={},f[this.xe][this.Rd]=l,f[this.Re][this.Rd]=l,m=this.rB(l),f.startKey[this.Rd]=m,f.endKey[this.Rd]=m),b++,a[b]=f)),g=l;return a},Yda:function(){var a=this.p().wy(),b,c,e=a.length;for(b=0;b<e;b++)if(c=f(a[b]).data("sorted"),
null!=c)return b;return null},NB:function(a){a=a.find(":tabbable");return null!=a&&0<a.length?a:null},Vg:function(){this.t0||(this.t0=new b.bb(this));return this.t0},p:function(){this.PL||(this.PL=new b.f(this));return this.PL},IW:function(a){a=a.originalEvent.changedTouches[0];return f(document.elementFromPoint(a.clientX,a.clientY))},lj:function(a,b){var c=b.item.attr("data-oj-command"),e=this.p().Fo(f(this.dj.target),"oj-table-column-header-cell"),g=this.p().Fo(f(this.dj.target),"oj-table-data-cell"),
h=null;null!=e&&(h=this.p().je(e));null!=g&&(h=this.p().je(g));"oj-table-sortAsc"==c?this.pk(h,!0,a):"oj-table-sortDsc"==c&&this.pk(h,!1,a)},yea:function(a){this.fk();b.r.error(a)},zea:function(){this.A_()},AJ:function(a){try{var d=this;this.yi(function(){var c=0,g=d.Ya();g instanceof b.ka&&(c=g.getStartItemIndex());var g=[],f,k=a[d.Yi].length;for(f=0;f<k;f++)g[f]=f+c+a[d.xe];d.oZ({data:a[d.Yi],keys:a[d.$r],indexes:g},a[d.xe])})}catch(c){b.r.error(c)}finally{this.fk()}},SB:function(){try{var a=this.fC(),
d=this;this.yi(function(){d.Xl(null,null);return a})}catch(c){b.r.error(c)}finally{this.fk()}},Mn:function(){try{this.dC();var a=this;this.yi(function(){a.Xl(null,null)})}catch(d){b.r.error(d)}finally{this.fk()}},BJ:function(a){try{var d=this.Ya(),c=a[this.Yi],e=a[this.pv],g=a[this.$r];c instanceof Array||(c=[c]);a=0;d instanceof b.ka&&(a=d.getStartItemIndex());var d=[],f,k=c.length;for(f=0;f<k;f++){var l=e[f]-a;void 0!==l&&d.push({row:{data:c[f],key:g[f],index:e[f]},Rh:l})}0<d.length&&this.aca(d)}catch(m){b.r.error(m)}finally{this.fk()}},
Bea:function(a){try{var d=this.Ya(),c=a[this.Yi],e=a[this.pv],g=a[this.$r];c instanceof Array||(c=[c]);a=0;d instanceof b.ka&&(a=d.getStartItemIndex());var d=[],f,k=c.length;for(f=0;f<k;f++){var l=e[f]-a;void 0!==l&&d.push({row:{data:c[f],key:g[f],index:e[f]},Rh:l})}0<d.length&&this.bca(d)}catch(m){b.r.error(m)}finally{this.fk()}},CJ:function(a){try{var d=this.Ya(),c=a[this.Yi],e=a[this.pv],g=a[this.$r];c instanceof Array||(c=[c]);a=0;d instanceof b.ka&&(a=d.getStartItemIndex());var d=[],f;for(f=
c.length-1;0<=f;f--){var k=e[f]-a;void 0!==k&&d.push({row:{data:c[f],key:g[f],index:e[f]},Rh:k})}0<d.length&&this.cca(d)}catch(l){b.r.error(l)}finally{this.fk()}},DJ:function(a){try{var d;if(null!=a){var c=this.vb(),e,g,f,k=c.length;for(e=0;e<k;e++)if(g=c[e],f=null==g.sortProperty?g.field:g.sortProperty,a.header==f){d=e;break}null!=d&&this.wZ(d,a.direction==this.zh.np)}var l=this.options.selection;if(null!=l){a=!1;if(1<l.length)a=!0;else if(null!=l[0]){var m=l[0][this.Re];b.b.gh(l[0][this.xe],m)||
null==m||(a=!0)}a&&(this.Rt(null),this.option("selection",null,{_context:{Ec:!0,Za:!0}}))}this.Xl(this.options.currentRow,null);var n=this;this.yi(function(){return n.fC(null)}).then(function(){null!=d&&setTimeout(function(){n.j_(d)},0)})}catch(p){b.r.error(p)}finally{this.fk()}},Vea:function(a){var b=this.El(),c=this.vb();if(null!=b){var e=b;this.xf(this.Tb.iR)?e=0<b?b-1:b:this.xf(this.Tb.jR)&&(e=b<c.length-1?b+1:b);e!=b&&(this.zk(e,!0,!1,null),a[this.Tb.vp]&&(c=this.yw(e),this.Ak(e,!c,null,a,!0),
c&&this.yw(b)&&this.Ak(b,!1,null,a,!0)))}},Wea:function(a){var b=!1,c=this.jj();if(null!=c&&this.v0){var e=document.activeElement,g=this.p().hd();if(f.contains(g[0],e))return;e=this.NB(g);null==e||a[this.Tb.vp]||(b=!0,c=this.p().me(c),c=this.NB(c),null!=c?f(c[0]).focus():f(e[0]).focus(),a.preventDefault(),a.stopPropagation())}if(!b){e=this.p().Mc();b=this.NB(f(document));c=b.length;e=this.NB(e);e=null!=e?e.length:0;g=b.index(this.p().Mc());if(a[this.Tb.vp])if(0<=g){if(0==g)return;f(b[g-1]).focus()}else return;
else{if(g==c-1)return;f(b[g+e+1]).focus()}a.preventDefault();a.stopPropagation()}this.cL(a.keyCode)},Xea:function(a){var b=this.jj(),c=this.El();if(null!=b){var c=this.p().Kf(),e=null!=c?c.length:0,c=b;this.xf(this.Tb.Nz)?c=0<b?b-1:b:this.xf(this.Tb.Mz)&&(c=b<e-1?b+1:b);c!=b?this.Hh(c,!0,!0,null,a)&&a[this.Tb.vp]&&(e=this.Fw(c),this.dh(c,!e,null,a,!0),e&&this.Fw(b)&&this.dh(b,!1,null,a,!0)):c==b&&0==b&&this.xf(this.Tb.Nz)&&this.zk(0,!0,!1,null)}else null!=c&&this.xf(this.Tb.Mz)&&this.Hh(0,!0,!0,null,
a)},Yea:function(a){var b=this.El();if(null!=b&&b!=this.vb().length-1)this.zk(this.vb().length-1,!0,!1,null);else{var b=this.jj(),c=this.p().Kf(),c=null!=c?c.length:0;null!=b&&b!=c-1&&0<c&&this.Hh(c-1,!0,!0,null,a)}},Zea:function(a){var b=this.El();if(null!=b&&this.vb()[b].sortable==this.Ng){var c=this.p().Nc(b).data("sorted");null==c||c==this.zh.bs?this.pk(b,!0,a):this.pk(b,!1,a)}},$ea:function(a){a.preventDefault();a.stopPropagation();this.p().Mc().focus();this.VC(!1)},afa:function(a){var b=this.El();
null!=b&&0!=b?this.zk(0,!0,!1,null):(b=this.jj(),null!=b&&0!=b&&this.Hh(0,!0,!0,null,a))},bfa:function(a){var b=this.jj();null!=b?this.dh(b,!this.Fw(b),null,a,!0):(b=this.El(),null!=b&&(this.Pp(),this.Ak(b,!this.yw(b),null,a,!0)))},HJ:function(a){var b=this.p().Eo(f(a));if(null!=b&&null!=this.ah&&this.ah!=b){var c=this.ah,e=this.Gw();if(b<c){var g;for(g=0;g<e.length;g++)(e[g]<b||e[g]>c)&&this.dh(e[g],!1,a,null,!0);for(g=c;g>=b;g--)this.dh(g,!0,a,null,!0),this.p().Z3(g)}else{for(g=0;g<e.length;g++)(e[g]>
b||e[g]<c)&&this.dh(e[g],!1,a,null,!0);for(g=c;g<=b;g++)this.dh(g,!0,a,null,!0),this.p().Y3(g)}}},LJ:function(){this.Wka(this.dc.i7,this.dc.h7,b.X.Qb.WARNING)},ufa:function(a){var d=this.p().km(),c=this.p().Pk();this.p().Tk()?(d&&("rtl"===this.ac()?d.css(b.f.F.Yz,"-"+a+b.f.ma.bc):d.css(b.f.F.Zj,"-"+a+b.f.ma.bc)),c&&("rtl"===this.ac()?c.css(b.f.F.Yz,"-"+a+b.f.ma.bc):c.css(b.f.F.Zj,"-"+a+b.f.ma.bc))):((d=this.p().er())&&("rtl"===this.ac()?d.css(b.f.F.Yz,"-"+a+b.f.ma.bc):d.css(b.f.F.Zj,"-"+a+b.f.ma.bc)),
(d=this.p().wu())&&("rtl"===this.ac()?d.css(b.f.F.Yz,"-"+a+b.f.ma.bc):d.css(b.f.F.Zj,"-"+a+b.f.ma.bc)))},pk:function(a,b,c){this.CT(a);var e=this.vb()[a];this.tga(null==e.sortProperty?e.field:e.sortProperty,b,c);this.f0=e;this.wZ(a,b)},iX:function(a){if(null!=this.rW())return!0;var b=null;if(null!=a)b=this.En(a,"cell");else{var c=this.vb().length;for(a=0;a<c&&(b=this.En(a,"cell"),null==b);a++);}return null!=b?!0:!1},Gfa:function(){var a=this.p().BN();if(a.css(b.f.F.sd)!=b.f.ma.en){var d=a.outerHeight(),
c=this.p().kc(),e=parseInt(c.css(b.f.F.tQ),10),g=parseInt(c.css(b.f.F.Oz),10);c.css(b.f.F.Oz,g-e-d+b.f.ma.bc);c.removeClass(b.f.la.iA);a.removeClass(b.f.la.iA);a.css(b.f.F.IF,"");a.css(b.f.F.sd,b.f.ma.en)}},UJ:function(){var a=this.p().V2();null!=a&&a.remove()},Hfa:function(){this.p().xy().css(b.f.F.sd,b.f.ma.en)},rq:function(a,d){if(this.vb()[a].sortable==this.Ng){var c=this.p().Nc(a),e=c.data("sorted");!d||null!=e&&e!=this.zh.bs?d||null!=e&&e!=this.zh.np||(c=c.find("."+b.f.C.Zr),c.addClass(b.f.la.tb),
c.removeClass(b.f.la.kf),c.removeClass(b.f.la.bd)):(c=c.find("."+b.f.C.pp),c.addClass(b.f.la.tb),c.removeClass(b.f.la.kf),c.removeClass(b.f.la.bd))}},dC:function(){var a=this,d=this.Ya();null!=d&&d instanceof b.T&&!(d instanceof b.ka)?(this.p().Lc()[0].scrollTop=0,this.yi(function(){return a.fC(0,{fetchType:"init"})})):null==d&&this.yi(function(){return Promise.resolve()})},fC:function(a,d){d=d||{};d[this.xe]=a;!d[this.BQ]&&this.vi()&&(d[this.BQ]=this.options.scrollPolicyOptions.fetchSize);d.silent=
!0;var c="init"==d.fetchType?!0:!1,e=this.Ya(),g=this;return new Promise(function(a,f){null!=e?(g.A_(),e.fetch(d).then(function(d){if(null!=d&&null!=d[g.Yi]){var f=0;e instanceof b.ka&&(f=e.getStartItemIndex());var k=[],p,r=d[g.Yi].length;for(p=0;p<r;p++)k[p]=p+f+d[g.xe];g.oZ({data:d[g.Yi],keys:d[g.$r],indexes:k},d[g.xe],c,c)}g.fk();a(null)},function(a){g.fk();f(a)})):a(null)})},tga:function(a,b,c){var e=this.Ya();if(!e)return null;this.$_();var g={};g[this.$m]=a;g.direction=b?this.zh.np:this.zh.bs;
this._trigger("sort",c,{header:g[this.$m],direction:g.direction});e.sort(g)},xga:function(){if(null!=this.xn){var a=this.xV();if(this.xn.length!=a.length)return!0;var b,c,e=a.length;for(b=0;b<e;b++)for(c in a[b])if(a[b].hasOwnProperty(c)&&a[b][c]!=this.xn[b][c])return!0;return!1}return!0},xf:function(a){var b=this.Fl(),c,e=b.length;for(c=0;c<e;c++)if(b[c]==a)return!0;return!1},vi:function(){return this.options.scrollPolicy==this.h8.R7?!0:!1},jK:function(a){return this.TX(a,/^INPUT|TEXTAREA/)},Hga:function(a){return this.TX(a,
/SELECT|OPTION|BUTTON|^A\b/)},Iga:function(a){return 0<a.closest("[draggable\x3d'true']").length},TX:function(a,b){for(var c,e=this.p().Mc();null!=a&&a[0]!=e[0]&&"TD"!=(c=a.prop("nodeName"))&&"TH"!=c;)if(3==a[0].nodeType)a=a[0].parentNode;else{var g=a.attr("tabIndex");if(c.match(b)&&-1!=g)return!0;a=a.parentNode}return!1},eY:function(){var a,b,c=this.vb().length;for(a=0;a<c;a++)if(b=this.En(a,"footer"),null!=b)return!1;return!0},nC:function(){var a=this.vb(),b,c=a.length;for(b=0;b<c;b++)if(null!=
a[b].headerText||null!=a[b].headerStyle||null!=a[b].sortable&&a[b].sortable!=this.CR||null!=a[b].sortProperty||null!=a[b].headerRenderer)return!1;return!0},Mga:function(){return!0==this.Cja},cra:function(){return this.v0},Nga:function(a,d){var c=this.eT,e=!1;"contextMenu"==a&&d=="#"+this.p().Qk()+"_contextmenu"?e=!1:"selection"==a||"currentRow"==a||b.b.gh(d,c[a])||(e=!0);this.eT=f.extend(!0,{},this.options);return e},Oga:function(){var a=this.vb(),b,c=a.length;for(b=0;b<c;b++)if(null!=a[b].sortable&&
a[b].sortable!=this.CR)return!0;return!1},kK:function(){if(void 0==this.xt){var a=navigator.userAgent.toLowerCase();-1!=a.indexOf("mobile")||-1!=a.indexOf("android")?this.xt=!0:this.xt=!1}return this.xt},oZ:function(a,d,c,e){if(this.xga()||!this.Mga()&&!this.nC())if(this.X$(),this.yZ(),null!=this.f0){var g,f,k=!1,l=this.vb();if(null!=l){var m=l.length;for(g=0;g<m;g++)if(f=l[g],b.b.gh(f,this.f0)){k=!0;break}k||this.Ya().sort(null)}}this.Bx();this.xZ(a,d,c,e)},wZ:function(a,d){this.CT(a);var c=this.p().Nc(a),
e=c.data("sorted");d&&e!=this.zh.np?(c.data("sorted",this.zh.np),e=c.find("."+b.f.C.pp),e.addClass(b.f.la.kf),e.removeClass(b.f.la.tb),e=c.find("."+b.f.C.vz),e.removeClass(b.f.la.tb),e=c.find("."+b.f.C.Az),e.addClass(b.f.la.tb),this.rq(a,!d)):d||e==this.zh.bs||(c.data("sorted",this.zh.bs),e=c.find("."+b.f.C.Zr),e.addClass(b.f.la.kf),e.removeClass(b.f.la.tb),e=c.find("."+b.f.C.Az),e.removeClass(b.f.la.tb),e=c.find("."+b.f.C.vz),e.addClass(b.f.la.tb))},xZ:function(a,d,c,e){var g=this.p().hd();if(null!=
g){a=this.Uda(a,d);var h;if(0==d)b.Components.Bg(g[0]),g.empty();else if(h=g.children(),null!=h&&0<h.length)for(h=h.length-1;h>=d;h--)this.p().u4(h);this.p().Vq();this.UJ();h=g.children();if(0!=a.length||null!=h&&0!=h.length){var k=f(document.createDocumentFragment()),l,m,n,p=a.length;for(h=0;h<p;h++)l=a[h].row,m=a[h].Rh,null!=l&&(n=this.p().H1(m,l[this.$m]),this.p().RO(n,!0),this.p().p3(m,n,l,k),this.HC(m,l,n,k,d,!0));g.append(k);this.iX()&&(this.p().zE(null,null,c,e),b.Components.Nf(g[0]))}else this.X_()}},
HC:function(a,d,c,e,g,h){var k=this.rW();this.vb();var l=this.p().hd();(isNaN(a)||0>a)&&b.r.error("Error: Invalid rowIdx value: "+a);var m=this.p().hr(d[this.$m]);if(null==c)if(c=this.p().me(a))c.empty(),h=!0,this.p().UM(a,d[this.$m],m,c,h);else return;this.UJ();c.data("rowData",d);h={rowContext:b.Yf.aE(this,d,c[0]),row:f.extend({},d[this.Yi])};if(k){k=k(h);null!=k?c.append(k):(null==e?c=f(l.children()[a]):(g=null==g?0:g,c=f(e.children()[a-g])),this.p().Vq(),this.p().LO(d,c),this.p().RO(c,!1));this.p().UM(a,
d[this.$m],m,c,!1);g=c.children(b.f.kb.rl);l=g.length;for(e=1;e<l;e++)k=f(g[e]),this.p().KO(a,d[this.$m],m,e-1,k),this.p().QO(e-1,k,!1);if(null!=this.hk)for(e=0;e<this.hk.length-1;e++)this.hk[e]>e&&(a=f(g[this.hk[e]+1]),d=f(g[e+1]),a[0].parentNode.insertBefore(a[0],d[0]),g=c.children(b.f.kb.rl))}else b.Yf.Opa(a,d,h)},Bx:function(){var a=this.vb(),d=this.p().Pk();if(!d){if(this.eY())return;d=this.p().I1();this.p().W4(d)}d=this.p().wu();d.empty();if(a&&0<a.length){this.p().J1(d);for(var c,e,g=a.length,
a=0;a<g;a++)c=this.En(a,"footer"),e=this.p().Uma(),this.p().X4(a,e),this.p().uoa(a,e),c&&(c=c({footerContext:b.Yf.aE(this,null,e[0]),columnIndex:a}),null!=c?(e.empty(),e.append(c)):(e=f(d.children(":not(."+b.f.C.gi+")")[a]),this.p().X4(a,e)))}},yZ:function(){var a=this.vb(),d=this.p().km();if(!d){if(this.nC())return;d=this.p().K1();this.p().Y4(d)}d=this.p().er();this.oM(d);d.empty();if(a&&0<a.length){var c=this.p().Vma();d.append(c);for(var e,g,h,k,l=a.length,c=0;c<l;c++)e=a[c],g=this.En(c,"header"),
h=this.p().Wma(c),g&&(k=b.Yf.aE(this,null,h[0]),k={headerContext:k,columnIndex:c,data:e.headerText},e.sortable==b.f.Ng?k.columnHeaderSortableIconRenderer=function(a,c){b.Yf.w1(this,c)}:k.columnHeaderDefaultRenderer=function(a,c){b.Yf.u1(this,c)},e=g(k),null!=e?(h.empty(),h.append(e)):(h=f(d.children(":not(."+b.f.C.MF+")")[c]),this.p().L4(c,h),this.p().Z4(c,h,!1))),this.p().Xma(c,this.sB());this.Cja=!0}},Sia:function(){var a=this.p().xy();null!=a&&a.remove();this.p().L1()},Wia:function(){var a=f.event.special;
a.ojtablebeforecurrentrow={handle:function(a,b){return a.handleObj.handler.apply(this,[a,b])}};a.ojtablesort={handle:function(a,b){return a.handleObj.handler.apply(this,[a,b])}}},Eq:function(){var a=this.Ya();if(null!=a){this.Dk();this.Ua=[];this.Ua.push({eventType:b.T.D.REQUEST,eventHandler:this.zea.bind(this)});this.Ua.push({eventType:b.T.D.SYNC,eventHandler:this.AJ.bind(this)});this.Ua.push({eventType:b.T.D.SORT,eventHandler:this.DJ.bind(this)});this.Ua.push({eventType:b.T.D.ADD,eventHandler:this.BJ.bind(this)});
this.Ua.push({eventType:b.T.D.REMOVE,eventHandler:this.CJ.bind(this)});this.Ua.push({eventType:b.T.D.CHANGE,eventHandler:this.Bea.bind(this)});this.Ua.push({eventType:b.T.D.REFRESH,eventHandler:this.SB.bind(this)});this.Ua.push({eventType:b.T.D.RESET,eventHandler:this.Mn.bind(this)});this.Ua.push({eventType:b.T.D.ERROR,eventHandler:this.yea.bind(this)});var d,c,e=this.Ua.length;for(d=0;d<e;d++)(c=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&(this.Ua[d].eventHandler=c)}},Xia:function(){null!=
this.p().Lc()&&this.p().Lc().scroll(function(a){this.ufa(this.p().J2(a.target))}.bind(this))},EZ:function(){var a=this;this.MU=function(b){null!=b&&b.maxCountLimit&&a.LJ()};this.cI=new b.Gg(this.p().Lc(),this.Ya(),{fetchSize:this.options.scrollPolicyOptions.fetchSize,maxCount:this.options.scrollPolicyOptions.maxCount,success:this.MU})},tj:function(){var a=this.p().kc();if(!this.Wl){var d=this;this.Wl=function(){var a=d.p().kc().outerHeight(),b=d.p().kc().outerWidth();d.p().zE(b,a)}}this.kC||(b.v.eh(a[0],
this.Wl,50),this.kC=!0)},cL:function(a){var b=this.Fl(),c,e=b.length;for(c=0;c<e;c++)b[c]==a&&b.splice(c,1)},j_:function(a){var b="rtl"===this.ac(),c=this.p().hd(),e=this.p().Nc(a);if(e){a=this.p().K2();var e=e.get(0).getBoundingClientRect(),g=c.get(0).getBoundingClientRect(),f=!1;b?(e.left<g.left+a&&(b=g.left-e.left+a,this.p().iC()||(b*=-1),c.scrollLeft(c.scrollLeft()+b),f=!0),e.right>g.right&&!f&&(b=e.right-g.right,this.p().iC()||(b*=-1),c.scrollLeft(c.scrollLeft()-b))):(e.left<g.left&&(b=g.left-
e.left,c.scrollLeft(c.scrollLeft()-b),f=!0),e.right>g.right-a&&!f&&(b=e.right-g.right+a,c.scrollLeft(c.scrollLeft()+b)))}},Zja:function(a){var b=this.p().me(a);a=this.p().Hna();var b=b.get(0).getBoundingClientRect(),c=this.p().Lc(),e=c.get(0).getBoundingClientRect(),g=!1;b.bottom>e.bottom-a&&(a=b.bottom-e.bottom+a,c.scrollTop(c.scrollTop()+a),g=!0);b.top<e.top&&!g&&(a=e.top-b.top,c.scrollTop(c.scrollTop()-a))},Xl:function(a,d,c){var e=this.Wp,g;g=!0;if(null==a){if(null!=e){try{g=this._trigger("beforecurrentrow",
d,{currentRow:null,previousCurrentRow:this.Wp})}catch(f){a=this.dc.TQ;var k=b.ha.Ib(this.dc.SQ,{error:f.toString()});b.r.info(a+"\n"+k);return!1}if(!g)return!1;this.Wp=null;this.option("currentRow",null,{_context:{Ec:!0,originalEvent:d,Za:!0}});null==d&&this.Hh(-1,!0,!1,null,d);e=e.rowIndex;e=this.Ew(e);e=this.Dw(e);g=this.p().me(e);null!=g&&g.removeClass(b.f.C.tG)}return!0}var l=this.Ya(),m=a.rowIndex,n=a.rowKey;null==n&&(n=this.Ew(m));null==m&&(m=this.aq(n));k=this.Dw(n);a={rowIndex:m,rowKey:n};
if(-1!=k&&(!l||0==l.totalSize()||-1>k||null===k||null===n)){a=this.dc.g7;k=b.ha.Ib(this.dc.f7,{rowIdx:k});if(c)throw Error(a+"\n"+k);b.r.info(a+"\n"+k);return!1}c=this.jj();if(l=!b.b.gh(this.Wp,a)){try{g=this._trigger("beforecurrentrow",d,{currentRow:{rowIndex:m,rowKey:n},previousCurrentRow:this.Wp})}catch(p){return a=this.dc.TQ,k=b.ha.Ib(this.dc.SQ,{error:p.toString()}),b.r.info(a+"\n"+k),!1}if(!g)return!1;this.Wp={rowIndex:m,rowKey:n};this.option("currentRow",this.Wp,{_context:{Ec:!0,originalEvent:d,
Za:!0}});g=this.p().me(k);null!=g&&g.addClass(b.f.C.tG);null!=e&&(e=e.rowIndex,e=this.Ew(e),e=this.Dw(e),g=this.p().me(e),null!=g&&g.removeClass(b.f.C.tG))}(l||c!=a.rowIndex)&&null==d&&this.Hh(k,!0,!1,null,d);return!0},A_:function(){this.$_();this.UJ();this.kU=!0},zk:function(a,b,c,e){var g=null;null!=e&&(g=e.currentTarget);if(b){var f=this.El();null!=f&&f!=a&&this.zk(f,!1,!1,e);this.zT(!0);c&&this.Pp();this.j_(a);this.wS=a}this.B_(a,{Dj:b},g)},Ak:function(a,d,c,e,g){if(this.sB()==this.ki.vs||this.sB()==
this.ki.wp)(isNaN(a)||0>a)&&b.r.error("Error: Invalid column selection value: "+a),this.sB()==this.ki.vs&&d&&this.aw(),this.B_(a,{selected:d},c,e),this.tka(a,d),a=this.p().U2(a),f(a.children("."+b.f.C.vQ)[0]).prop("checked",d),g&&(d=this.tW(),this.option("selection",d,{_context:{Ec:!0,Za:!0}}))},B_:function(a,d){var c=this.p().Nc(a);if(c){var e=d.Dj,g=d.selected;null!=g&&c.hasClass(b.f.la.bd)!=g&&(g?c.addClass(b.f.la.bd):c.removeClass(b.f.la.bd));null!=e&&(e?(c.addClass(b.f.la.Zi),this.a0(a)):(c.removeClass(b.f.la.Zi),
this.rq(a,!0),this.rq(a,!1)));this.Sla(a)}},tka:function(a,b){this.Tn||(this.Tn=[]);var c,e=this.Tn.length;for(c=0;c<e;c++)if(this.Tn[c]==a){this.Tn.splice(c,1);break}b&&this.Tn.push(a)},vka:function(a,b){this.Un||(this.Un=[]);var c,e=this.Un.length;for(c=0;c<e;c++)if(this.Un[c]==a){this.Un.splice(c,1);break}b&&this.Un.push(a)},Hh:function(a,d,c,e,g){if(-1==a){var f=this.jj();null!=f&&this.Hh(f,!1,c,null,null);return c&&(g=this.Xl(null,g),!g)?!1:!0}var k=this.p().me(a);if(!k)return!1;if(d){f=this.jj();
null!=f&&f!=a&&this.Hh(f,!1,c,e,null);if(c&&(c=this.jq(a),g=this.Xl({rowKey:c},g),!g))return!1;k.addClass(b.f.la.Zi);this.Zja(a);this.tD(a,{Dj:!0,hover:!1});this.yT();this.aw();this.VC(!0)}else k.removeClass(b.f.la.Zi);this.tD(a,{Dj:d});return!0},dh:function(a,d,c,e,g){if(this.ht()==this.ki.vs||this.ht()==this.ki.wp)if((isNaN(a)||0>a)&&b.r.error("Error: Invalid row selection value: "+a),this.ht()==this.ki.vs&&d&&this.Pp(),c=this.p().me(a),null!=c){e=!1;if(c.hasClass(b.f.la.bd)!=d){d?c.addClass(b.f.la.bd):
c.removeClass(b.f.la.bd);e=!0;var h=this.options.dnd.drag;h&&("rows"===h||h.rows)&&c.prop("draggable",d)}e&&(d?this.tD(a,{hover:!1,Dj:!1,selected:!0}):this.tD(a,{selected:!1}));this.vka(a,d);a=this.p().P2(c);f(a.children("."+b.f.C.wQ)[0]).prop("checked",d);g&&(d=this.tW(),this.option("selection",d,{_context:{Ec:!0,Za:!0}}))}},Rt:function(a){if(null==a)this.Pp(),this.aw();else{var d,c,e,g,f,k,l=a.length;for(d=0;d<l;d++){e=a[d];if(null==e.startKey&&null==e[this.xe]||null==e.endKey&&null==e[this.Re])return b.r.error("Error: Invalid range object in selection. Both start and end objects must be specified"),
null;g=k=c=f=null;null!=e.startKey&&null!=e.startKey[this.Sd]&&(f=this.aq(e.startKey[this.Sd]));null!=e.endKey&&null!=e.endKey[this.Sd]&&(c=this.aq(e.endKey[this.Sd]));null!=e.startKey&&null!=e.startKey[this.Rd]&&(k=this.vV(e.startKey[this.Rd]));null!=e.endKey&&null!=e.endKey[this.Rd]&&(g=this.vV(e.endKey[this.Rd]));null==f&&null!=e[this.xe]&&(f=e[this.xe][this.Sd]);null==c&&null!=e[this.Re]&&(c=e[this.Re][this.Sd]);null==k&&null!=e[this.xe]&&(k=e[this.xe][this.Rd]);null==g&&null!=e[this.Re]&&(g=
e[this.Re][this.Rd]);if(null!=f&&null!=c&&null!=k&&null!=g)return b.r.error("Error: Invalid range object in selection - Can only support row or column selection. Not both"),null;if(null!=f&&0<=f&&null!=c&&0<=c)for(g=this.Ew(f),c=this.Ew(c),g=this.Dw(g),e=this.Dw(c),c=g;c<=e;c++)try{this.dh(c,!0,null,null,!1)}catch(m){b.r.error("Error: "+m)}else if(null!=k&&null!=g)for(c=k;c<=g;c++)try{this.Ak(c,!0,null,null,!1)}catch(n){b.r.error("Error: "+n)}else return b.r.error("Error: Invalid range object in selection - \n start row: "+
f+"\nend row: "+c+"\nstart column: "+k+"\nend column: "+g),null}}},VC:function(a){this.v0=a},Wka:function(a,d,c){this.p().zpa(a,d,c);a=this.p().BN();if(a.css(b.f.F.sd)==b.f.ma.en){a.css(b.f.F.sd,b.f.ma.Xr);var e=parseInt(a.css(b.f.F.yp),10),g=parseInt(a.css(b.f.F.zp),10);d=this.p().kc();c==b.X.Qb.WARNING&&(d.addClass(b.f.la.iA),a.addClass(b.f.la.iA));c=d.width();a.css(b.f.F.td,c-e-g+b.f.ma.bc);c=a.outerHeight();var e=parseInt(d.css(b.f.F.tQ),10),g=parseInt(d.css(b.f.F.H6),10),f=parseInt(d.css(b.f.F.Oz),
10),f=f+e+c;d.css(b.f.F.Oz,f+b.f.ma.bc);a.css(b.f.F.IF,-1*(f+e)+b.f.ma.bc);a.css(b.f.F.Zj,-1*g+b.f.ma.bc)}},X_:function(){null==this.p().V2()&&this.p().bna(this.vb().length)},$_:function(){this.p().xy().css(b.f.F.sd,b.f.ma.cR);this.p().s4()},a0:function(a){if(this.vb()[a].sortable==this.Ng&&(a=this.p().Nc(a))&&null==a.data("sorted")){var d=a.find("."+b.f.C.pp);d.addClass(b.f.la.kf);d.removeClass(b.f.la.tb);a.find("."+b.f.C.vz).removeClass(b.f.la.tb);a.find("."+b.f.C.Az).addClass(b.f.la.tb)}},oM:function(a){var b=
this;a.find("*").each(function(){b.Fp(this)})},Dk:function(){var a=this.Ya();if(null!=this.Ua&&null!=a){var b,c=this.Ua.length;for(b=0;b<c;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}},Ek:function(){var a=this.p().kc();b.v.Qh(a[0],this.Wl);this.kC=!1},Sla:function(a){var d=this.MI(a).selected,c=this.Gw(),e=this.p().Kf();if(null!=e&&0<e.length)for(var g,h,k,l,m=e.length,e=0;e<m;e++)if(h=this.p().dr(e,a),d)f(h).addClass(b.f.la.bd);else{k=!1;l=c.length;for(g=0;g<l;g++)if(e==c[g]){k=!0;break}k||
f(h).removeClass(b.f.la.bd)}},tD:function(a,d){var c=this.p().zN(a),e=d.Dj,g=d.selected,h=d.hover;if(c){if(null!=h){var k,l=c.length;for(k=0;k<l;k++)h?f(c[k]).addClass(b.f.la.Xj):f(c[k]).removeClass(b.f.la.Xj)}if(null!=e)for(l=c.length,k=0;k<l;k++)e?f(c[k]).addClass(b.f.la.Zi):f(c[k]).removeClass(b.f.la.Zi);if(null!=g)for(l=c.length,k=0;k<l;k++)g?f(c[k]).addClass(b.f.la.bd):f(c[k]).removeClass(b.f.la.bd)}},kka:function(a){this.cV=a?a.bind(this):void 0},yi:function(a){var d=this;this.Kt||(this.Ox=
0,this.Kt=Promise.resolve());this.Ox++;return this.Kt=this.Kt.then(a.bind(d)).then(function(a){d.Ox--;0==d.Ox&&(d.Kt=void 0,d.cV&&d.cV(),d._trigger("ready"));return a},function(a){d.Ox--;0==d.Ox&&(d.Kt=void 0,b.r.error(a));return Promise.reject(a)})}})})();b.Components.Em({ojTable:{display:b.Components.ih(function(){return b.we.Ok("table").display})}});b.f=function(a){this.Q=a;this.options=a.options;this.element=a.element;this.Init()};o_("TableDomUtils",b.f,b);b.b.ga(b.f,b.b,"oj.TableDomUtils");b.f.prototype.Init=
function(){b.f.q.Init.call(this)};b.b.g("TableDomUtils.prototype.Init",{Init:b.f.prototype.Init});b.f.prototype.Ema=function(){this.Vq();this.Bi=null};b.f.prototype.Vq=function(){this.hH=null};b.f.prototype.E1=function(a){var d=null,c=this;if(null!=this.options.contextMenu||null!=this.Mc().attr("contextmenu")){var e=this.n2(),d=f(e);if(null!=d&&0<d.length){var g=d.find("[data-oj-command]");if(null!=g&&0<g.length){var h;g.each(function(){0===f(this).children(b.f.kb.DF).length&&(h=f(this).attr("data-oj-command").split("-"),
f(this).replaceWith(c.F1(h[h.length-1])))});this.zY=d;this.Q.PT=e;d.ojMenu("refresh");d.on("ojselect",a)}}}else this.Q.Oga()&&(d=f(document.createElement(b.f.kb.m9)),d.css(b.f.F.sd,b.f.ma.en),d.attr(b.f.jb.Yj,this.Qk()+"_contextmenu"),this.kc().append(d),e=this.F1("sort"),d.append(e),d.ojMenu(),this.zY=d,this.Q.PT="#"+d.attr(b.f.jb.Yj),d.on("ojselect",a),this.Q._setOption("contextMenu","#"+d.attr(b.f.jb.Yj)))};b.f.prototype.F1=function(a){return"sort"===a?f(this.RM(a)).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.RM("sortAsc"))).append(f(this.RM("sortDsc")))):
null};b.f.prototype.RM=function(a){var b=f(document.createElement("li"));b.attr("data-oj-command","oj-table-"+a);b.append(this.Nma(a));return b};b.f.prototype.Nma=function(a){var d=f(document.createElement(b.f.kb.DF));d.attr(b.f.jb.u7,"#");var c=null;"sort"==a?c=this.Q.A("labelSort"):"sortAsc"==a?c=this.Q.A("labelSortAsc"):"sortDsc"==a&&(c=this.Q.A("labelSortDsc"));d.text(c);return d};b.f.prototype.Oma=function(a,b){this.Mc();this.Sma();this.Tk()&&this.Tma();a||this.K1();b||this.I1();this.Pma();this.L1();
this.Zma()};b.f.prototype.Pma=function(){var a=this.Mc(),d=f(document.createElement(b.f.kb.gS));a.append(d);this.gH=d};b.f.prototype.Qma=function(){return f(document.createElement(b.f.kb.rl))};b.f.prototype.UM=function(a,d,c,e,g){var h=null;g||(h=this.P2(e));null==h&&(h=null!=d?d.toString():a.toString(),a=null==c?this.hr(h):c,h=f(document.createElement(b.f.kb.rl)),h.addClass(b.f.C.sG),h.css("padding","0"),h.css("border","0"),null!=this.km()&&h.attr(b.f.jb.UF,this.Qk()+":"+b.f.zQ),c=f(document.createElement(b.f.kb.Iz)),
c.attr(b.f.jb.Yj,this.Qk()+":acc_sel_row_"+a),c.attr(b.f.jb.fA,"checkbox"),c.attr(b.f.jb.Ev,"-1"),a=this.Q.A(this.Q.xa.nR),c.attr(b.f.jb.cA,a),c.addClass(b.f.C.wQ),c.addClass(b.f.C.gi),h.append(c),e.prepend(h))};b.f.prototype.H1=function(a,d){var c=f(document.createElement(b.f.kb.Ep));this.UM(a,d,null,c,!0);return c};b.f.prototype.Rma=function(a){var d=f(document.createElement(b.f.kb.Vj));d.addClass(b.f.C.wG);d.addClass(b.f.C.xG);d.data("rowIdx",a);var c=f(document.createElement(b.f.kb.Vj));c.addClass(b.f.C.$R);
c.attr("role","button");c.attr("aria-label",this.Q.A("labelAccSelectionAffordanceTop"));c.data("rowIdx",a);d.append(c);c=f(document.createElement(b.f.kb.Vj));c.addClass(b.f.C.vG);c.addClass(b.f.C.xG);c.data("rowIdx",a);var e=f(document.createElement(b.f.kb.Vj));e.addClass(b.f.C.ZR);e.attr("role","button");e.attr("aria-label",this.Q.A("labelAccSelectionAffordanceBottom"));e.data("rowIdx",a);c.append(e);e=this.kc();e.append(d);e.append(c);this.Z3(a);this.Y3(a)};b.f.prototype.Sma=function(){var a=f(document.createElement(b.f.kb.Vj));
this.element.parent()[0].replaceChild(a[0],this.element[0]);a.prepend(this.element);this.BA=a};b.f.prototype.I1=function(){var a=this.Mc(),d=f(document.createElement(b.f.kb.hS)),c=f(document.createElement(b.f.kb.Ep));this.J1(c);d.append(c);c=this.km();null!=c?c.after(d):(c=this.hd(),null!=c?c.before(d):a.append(d));return d};b.f.prototype.J1=function(a){var d=a.children("."+b.f.C.gi);null!=d&&0<d.length?f(d[0]):(d=f(document.createElement(b.f.kb.rl)),d.addClass(b.f.C.gi),d.attr(b.f.jb.Ev,"-1"),a.prepend(d))};
b.f.prototype.Uma=function(){return f(document.createElement(b.f.kb.rl))};b.f.prototype.K1=function(){var a=this.Mc(),d=f(document.createElement(b.f.kb.jS)),c=f(document.createElement(b.f.kb.Ep));this.kH=c;d.append(c);c=this.Pk();null!=c?c.before(d):(c=this.hd(),null!=c?c.before(d):a.append(d));return this.jH=d};b.f.prototype.Vma=function(){var a=f(document.createElement(b.f.kb.iS));a.addClass(b.f.C.MF);a.attr(b.f.jb.Yj,this.Qk()+":"+b.f.zQ);var d=this.Q.A(this.Q.xa.nR);a.attr(b.f.jb.cA,d);a.css("padding",
"0");a.css("border","0");var c=f(document.createElement(b.f.kb.X8));c.text(d);c.addClass(b.f.C.gi);a.append(c);return a};b.f.prototype.Wma=function(a){var d=this.Q.vb()[a],c=f(document.createElement(b.f.kb.iS));this.Z4(a,c,!0);c.attr("abbr",d.headerText);c.attr(b.f.jb.cA,d.headerText);this.voa(a,c);a={columnIndex:a,headerContext:{component:this.Q,parentElement:c}};d.sortable==b.f.Ng?(c.attr("data-oj-sortable",b.f.Ng),b.Yf.w1(a,null)):b.Yf.u1(a,null);return c};b.f.prototype.Yma=function(a){a=this.Nc(a).clone();
a.removeClass(b.f.la.ds);a.removeClass(b.f.la.Zi);a.removeClass(b.f.la.Xj);a.addClass(b.f.C.yQ);a.css(b.f.F.ql,b.f.ma.EF);a.css(b.f.F.zs,"0");a.css(b.f.F.Zj,"0");a.css(b.f.F.o9,"-999");this.kc().append(a);return a};b.f.prototype.Xma=function(a,d){if(d==b.f.ki.vs||d==b.f.ki.wp){var c=this.Nc(a),e=this.U2(a);if(null==e){e=f(document.createElement(b.f.kb.Vj));e.addClass(b.f.C.xQ);e.addClass(b.f.C.gi);var g=f(document.createElement(b.f.kb.Iz));g.attr(b.f.jb.Yj,this.Qk()+":acc_sel_col"+a);g.attr(b.f.jb.fA,
"checkbox");g.attr(b.f.jb.Ev,"-1");var h=this.Q.A(this.Q.xa.O7);g.attr(b.f.jb.cA,h);g.addClass(b.f.C.vQ);e.append(g);c.prepend(e)}}};b.f.prototype.Tma=function(){var a=this.Mc(),d=this.kc(),c=f(document.createElement(b.f.kb.Vj));c.addClass(b.f.C.fS);d[0].replaceChild(c[0],a[0]);c.append(a);this.iH=c};b.f.prototype.bna=function(a){var d=this.hd(),c=f(document.createElement(b.f.kb.Ep));c.addClass(b.f.C.eS);this.$ma(c);this.ana(c,a);d.append(c)};b.f.prototype.$ma=function(a){var d=f(document.createElement(b.f.kb.rl));
d.addClass(b.f.C.gi);d.attr(b.f.jb.Ev,"-1");a.prepend(d)};b.f.prototype.ana=function(a,d){var c=f(document.createElement(b.f.kb.rl));c.attr(b.f.jb.Yr,d||1);c.addClass(b.f.C.dS);var e=null,e=null!=this.options.emptyText?this.options.emptyText:this.Q.A(this.Q.xa.d8);c.text(e);a.append(c)};b.f.prototype.Zma=function(){var a=this.kc(),d=f(document.createElement(b.f.kb.Vj));d.addClass(b.f.C.cS);d.css(b.f.F.sd,b.f.ma.en);a.append(d);this.lH=d};b.f.prototype.L1=function(){var a=this.kc(),d=f(document.createElement(b.f.kb.Vj));
d.addClass(b.f.C.AG);d.css(b.f.F.sd,b.f.ma.en);var c=f(document.createElement(b.f.kb.Vj));c.addClass(b.f.C.g9);c.text(this.Q.A(this.Q.xa.Z7));d.append(c);a.append(d);this.mH=d};b.f.prototype.Q1=function(a,d){this.BE();var c=this.er(),e=this.Nc(a);if(null!=e)d?e.addClass(b.f.C.yz):e.addClass(b.f.C.xz);else if(e=this.Q.vb(),null==e||0==e.length)d?c.addClass(b.f.C.yz):c.addClass(b.f.C.xz)};b.f.prototype.jna=function(a,d){this.CO();var c=f(document.createElement(b.f.kb.Ep));c.addClass(b.f.C.uG);d&&c.height(d.height());
var e=f(document.createElement(b.f.kb.rl)),g=this.Q.vb();e.attr(b.f.jb.Yr,g.length+1);c.append(e);e=this.me(a);null!=e?e.before(c):this.hd().append(c)};b.f.prototype.n2=function(){return null==this.options.contextMenu?"#"+this.Mc().attr("contextmenu"):this.options.contextMenu};b.f.prototype.je=function(a){var d=this.Fo(a,b.f.C.xs);if(null!=d)return d.parent().children("."+b.f.C.xs).index(d);d=this.Fo(a,b.f.C.Zm);if(null!=d)return d.parent().children("."+b.f.C.Zm).index(d);a=this.Fo(a,b.f.C.Dp);return null!=
a?a.parent().children("."+b.f.C.Dp).index(a):null};b.f.prototype.Eo=function(a){a=this.Fo(a,b.f.C.Cp);return null!=a?a.index():null};b.f.prototype.Fo=function(a,b){var c;if(null==a)return null;a=f(a);if(a.hasClass(b))return a;c=a.parents("."+b);return 0!=c.length?c.eq(0):null};b.f.prototype.Hna=function(){var a=this.Lc();return 0<a.get(0).clientHeight?a.get(0).offsetHeight-a.get(0).clientHeight:0};b.f.prototype.K2=function(){var a=this.Lc();return 0<a.get(0).clientWidth?a.get(0).offsetWidth-a.get(0).clientWidth:
0};b.f.prototype.Lc=function(){return this.Tk()?this.S2():this.hd()};b.f.prototype.J2=function(a){a=f(a);var b=a[0].scrollLeft;"rtl"===this.Q.ac()&&(b=Math.abs(b),this.gY()&&(b=a[0].scrollWidth-a[0].clientWidth-b));return b};b.f.prototype.Mc=function(){return f(this.element)};b.f.prototype.hd=function(){if(!this.gH){var a=this.Mc(),d=null;a&&(d=a.children("."+b.f.C.rG))&&0<d.length&&(this.gH=f(d.get(0)))}return this.gH};b.f.prototype.dr=function(a,b,c){return(a=this.zN(a,c))?a.length>b?f(a[b]):null:
null};b.f.prototype.P2=function(a){return null!=a&&(a=a.children("."+b.f.C.sG),null!=a&&0<a.length)?f(a[0]):null};b.f.prototype.Kna=function(a){return(a=this.zN(a,void 0))?this.CI(a):null};b.f.prototype.zN=function(a,d){d||(d=this.me(a));if(!d)return null;var c=d.children("."+b.f.C.xs);return null!=c&&0<c.length?c:null};b.f.prototype.me=function(a){var b=this.Kf();return b&&null!=a?b.length>a?f(b[a]):null:null};b.f.prototype.Kf=function(){if(!this.hH){var a=this.hd().children("."+b.f.C.Cp);null!=
a&&0<a.length&&(this.hH=a)}return this.hH};b.f.prototype.R2=function(){var a=this.kc().children("."+b.f.C.wG);return null!=a&&0<a.length?a=f(a[0]):null};b.f.prototype.Q2=function(){var a=this.kc().children("."+b.f.C.vG);return null!=a&&0<a.length?a=f(a[0]):null};b.f.prototype.kc=function(){this.BA||(this.Tk()?this.BA=f(this.element.get(0).parentNode.parentNode):this.BA=f(this.element.get(0).parentNode));return this.BA};b.f.prototype.Pk=function(){var a=this.Mc(),d=null;return a&&(d=a.children("."+
b.f.C.yG))&&0<d.length?f(d.get(0)):null};b.f.prototype.AN=function(a){var b=this.T2();return null!=b&&b.length>a?f(b[a]):null};b.f.prototype.T2=function(){var a=this.wu(),a=f(a).children("."+b.f.C.Dp);return null!=a&&0<a.length?a:null};b.f.prototype.Lna=function(){var a=this.T2();return a?this.CI(a):null};b.f.prototype.wu=function(){if(!this.dT){var a=this.Pk();if(!a)return null;this.dT=f(a.children("."+b.f.C.aS).get(0))}return this.dT};b.f.prototype.km=function(){if(!this.jH){var a=this.Mc(),d=null;
a&&(d=a.children("."+b.f.C.zG))&&0<d.length&&(this.jH=f(d.get(0)))}return this.jH};b.f.prototype.Nc=function(a){var b=this.wy();return b?b.length>a?f(b[a]):null:null};b.f.prototype.U2=function(a){a=this.Nc(a);return null!=a&&(a=a.children("."+b.f.C.xQ),null!=a&&0<a.length)?f(a[0]):null};b.f.prototype.wy=function(){var a=this.er();return null!=a&&(a=a.children("."+b.f.C.Zm),null!=a&&0<a.length)?a:null};b.f.prototype.Mna=function(){var a=this.wy();return a?this.CI(a):null};b.f.prototype.er=function(){if(!this.kH){var a=
this.km();if(!a)return null;this.kH=f(a.children("."+b.f.C.bS).get(0))}return this.kH};b.f.prototype.S2=function(){if(!this.iH){var a=this.kc();a&&(a=a.children("."+b.f.C.fS))&&0<a.length&&(this.iH=f(a.get(0)))}return this.iH};b.f.prototype.Qk=function(){this.u0||(this.u0=this.Mc().attr(b.f.jb.Yj));return this.u0};b.f.prototype.BN=function(){if(!this.lH){var a=this.kc();a&&(a=a.children("."+b.f.C.cS))&&0<a.length&&(this.lH=f(a.get(0)))}return this.lH};b.f.prototype.V2=function(){var a=this.hd();return a&&
(a=a.children("."+b.f.C.eS))&&0<a.length?f(a.get(0)):null};b.f.prototype.xy=function(){if(!this.mH){var a=this.kc();a&&(a=a.children("."+b.f.C.AG))&&0<a.length&&(this.mH=f(a.get(0)))}return this.mH};b.f.prototype.Nna=function(){if(!this.w0){var a=this.Qk();null==a&&(a=(1E32*Math.random()).toString(36));this.w0=a}return this.w0};b.f.prototype.hr=function(a){"string"!=f.type(a)&&(a=a.toString());var b=0;if(0==a.length)return b;var c,e,g=a.length;for(e=0;e<g;e++)c=a.charCodeAt(e),b=(b<<5)-b+c,b&=b;return b};
b.f.prototype.toa=function(a,b,c,e,g,h){this.KO(a,b,c,e,g);f(h).append(g)};b.f.prototype.p3=function(a,d,c,e){this.LO(c,d);null==e?(c=this.hd(),e=c.children("."+b.f.C.Cp),0==a?c.prepend(d):e.length>=a?f(e.get(a-1)).after(d):c.append(d)):e.append(d);this.Vq()};b.f.prototype.uoa=function(a,d){var c=this.wu(),e=f(c).children("."+b.f.C.Dp);0==a?(e=c.children("."+b.f.C.gi),null!=e&&0<e.length?f(e[0]).after(d):c.prepend(d)):c.length>=a?f(e.get(a-1)).after(d):c.append(d)};b.f.prototype.voa=function(a,d){var c=
this.er(),e=this.wy();this.L4(a,d);var g=this.Nc(a);g?g.replaceWith(d):0==a?(e=c.children("."+b.f.C.MF),null!=e&&0<e.length?f(e[0]).after(d):c.prepend(d)):e.length>=a?f(e.get(a-1)).after(d):c.append(d)};b.f.prototype.Tk=function(){return this.iC()&&10>this.iC()?!0:!1};b.f.prototype.y3=function(){var a=this.kc(),d=this.Mc(),c=this.xy(),e=c.css(b.f.F.sd).toString();c.css(b.f.F.sd,b.f.ma.en);var g=[];g[0]=0<a[0].clientHeight?d[0].clientHeight>a[0].clientHeight?1:1<a[0].clientHeight-d[0].clientHeight?
-1:0:0;g[1]=0<a[0].clientWidth?d[0].clientWidth>a[0].clientWidth?1:1<a[0].clientWidth-d[0].clientWidth?-1:0:0;c.css(b.f.F.sd,e);return g};b.f.prototype.Z3=function(a){var d=this.R2();if(null!=d){d.data("rowIdx",a);f(d.children()[0]).data("rowIdx",a);var c=this.hd();a=this.me(a)[0].getBoundingClientRect();var e=this.kc()[0].getBoundingClientRect();d.css(b.f.F.zs,a.top-e.top-d.height()/2);d.css(b.f.F.Zj,c.width()/2+"px")}};b.f.prototype.Y3=function(a){var d=this.Q2();if(null!=d){d.data("rowIdx",a);
f(d.children()[0]).data("rowIdx",a);var c=this.hd();a=this.me(a)[0].getBoundingClientRect();var e=this.kc()[0].getBoundingClientRect();d.css(b.f.F.zs,a.top-e.top+a.height-d.height()/2);d.css(b.f.F.Zj,c.width()/2+"px")}};b.f.prototype.Poa=function(a,d,c){var e=this.Q.vb(),g=this.Nc(a),f=this.AN(a),k=null,l=k=k=null,m=null,n=!1;d==e.length&&(d-=1,n=!0);null!=g&&(m=g.attr(b.f.jb.Yr),k=this.Nc(d),null==k||null!=m&&1!=m||(n?k.after(g):k.before(g)));null!=f&&(m=f.attr(b.f.jb.Yr),k=this.AN(d),null==k||null!=
m&&1!=m||(n?k.after(f):k.before(f)));g=this.Kf();if(null!=g)for(e=0;e<g.length;e++)k=this.dr(e,a,null),null!=k&&(l=this.dr(e,d,null),m=k.attr(b.f.jb.Yr),null==l||null!=m&&1!=m||(n?l.after(k):l.before(k)));m=this.options.columns;d=a<d&&!n?d-1:d;n=m.splice(a,1);m.splice(d,0,n[0]);m=m.slice(0);this.Q.option("columns",m,{_context:{Ec:!0,originalEvent:c,Za:!0}});c=this.Q.xn.splice(a,1);this.Q.xn.splice(d,0,c[0]);if(!this.hk)for(this.hk=[],e=0;e<m.length;e++)this.hk[e]=e;a=this.hk.splice(a,1);this.hk.splice(d,
0,a[0]);this.Q.yi(function(){});return this.hk};b.f.prototype.dpa=function(){var a=this,d=this.zY;d&&0<d.length&&d.find("[data-oj-command]").each(function(){var c=f(this).children(b.f.kb.DF);if(0<c.length){var d=f(this).attr("data-oj-command").split("-"),d=d[d.length-1],g;"sort"==d?g=a.Q.A("labelSort"):"sortAsc"==d?g=a.Q.A("labelSortAsc"):"sortDsc"==d&&(g=a.Q.A("labelSortDsc"));c.contents().filter(function(){return 3===this.nodeType})[0].nodeValue=g}})};b.f.prototype.zE=function(a,b,c,e){this.Q.Ek();
this.Ria(a,b,c,e);this.Q.tj();this.Q.Xl(this.options.currentRow,null)};b.f.prototype.BE=function(){var a=this.Mc().find("."+b.f.C.yz+",."+b.f.C.xz),d=0;if(a&&0<a.length)for(var c=a.length,d=0;d<c;d++)f(a[d]).removeClass(b.f.C.yz),f(a[d]).removeClass(b.f.C.xz)};b.f.prototype.CO=function(){var a=this.hd(),d=a.children("."+b.f.C.uG),a=a.children("."+b.f.C.e9),c=0;if(d&&0<d.length)for(var e=d.length,c=0;c<e;c++)f(d[c]).remove();if(a&&0<a.length)for(d=a.length,c=0;c<d;c++)f(a[c]).remove()};b.f.prototype.u4=
function(a){a=this.me(a);null!=a&&(b.Components.Bg(a[0]),a.remove(),this.Vq())};b.f.prototype.kpa=function(){var a=this.kc().children("."+b.f.C.xG);if(null!=a&&0<a.length){var d;for(d=0;d<a.length;d++)a[d].remove()}};b.f.prototype.lpa=function(){var a=this.kc().find("."+b.f.C.yQ);if(a&&0<a.length){var d,c=a.length;for(d=0;d<c;d++)f(a[d]).remove()}};b.f.prototype.J4=function(a,b){a=f(a);"rtl"===this.Q.ac()&&(b=Math.abs(b),this.gY()?b=a[0].scrollWidth-a[0].clientWidth-b:this.Cga()&&(b*=-1));a[0].scrollLeft!=
b&&(a[0].scrollLeft=b)};b.f.prototype.KO=function(a,d,c,e,g){var f=this.options.accessibility;e=this.Q.vb()[e];var k=null,l=null==this.km()?!0:!1,k=null!=f&&null!=f.rowHeader?f.rowHeader:this.Q.vb()[0].id;a=null!=d?d.toString():a.toString();c=null==c?this.hr(a):c;c=this.Qk()+":"+k+"_"+c;a=this.Qk()+":"+e.id;k==e.id?(g.attr(b.f.jb.Yj,c),l&&(a="")):a=l?c:a+" "+c;g.attr(b.f.jb.UF)||g.attr(b.f.jb.UF,a)};b.f.prototype.LO=function(a,b){b.data("rowKey",a.key)};b.f.prototype.L4=function(a,d){var c=this.Q.vb()[a];
d.attr(b.f.jb.Yj)||d.attr(b.f.jb.Yj,this.Qk()+":"+c.id)};b.f.prototype.K4=function(a,b,c){var e=this.Kf();if(null!=e&&0<e.length)if(null===a){if(a=null,a=b?this.hd().find("[td]"):this.hd().find("."+c),null!=a&&0<a.length)for(var g=a.length,e=0;e<g;e++)b?f(a[e]).addClass(c):f(a[e]).removeClass(c)}else for(var h=e.length,e=0;e<h;e++)g=this.dr(e,a,null),b?f(g).addClass(c):f(g).removeClass(c)};b.f.prototype.zpa=function(a,d,c){var e=this.BN();e.empty();e.append(b.Na.l1(document,a,d,c,null))};b.f.prototype.Hpa=
function(){var a=this.Mc(),d=this.kc(),c=a.children(b.f.kb.jS),c=0<c.length?f(c[0]):null,e=a.children(b.f.kb.hS),e=0<e.length?f(e[0]):null,g=a.children(b.f.kb.gS),g=0<g.length?f(g[0]):null;a.attr(b.f.jb.Ev,"0");this.Q._focusable(a);this.Q._focusable(d);this.Y4(c);this.W4(e);this.Ipa(g)};b.f.prototype.Ipa=function(a){a.addClass(b.f.C.rG);a.attr(b.Components.hn,this.Q.widgetName)};b.f.prototype.QO=function(a,d,c){a=this.Q.vb()[a];if(c||!d.hasClass(b.f.C.xs))d.addClass(b.f.C.xs),null==a.style||!c&&d.attr(b.f.jb.ak)==
a.style||d.attr(b.f.jb.ak,a.style),null==a.className||!c&&d.hasClass(a.className)||d.addClass(a.className);this.lK()&&(!c&&d.hasClass(b.f.C.ys)||d.addClass(b.f.C.ys))};b.f.prototype.RO=function(a,d){!d&&a.hasClass(b.f.C.Cp)||a.addClass(b.f.C.Cp);this.QX()&&(!d&&a.hasClass(b.f.C.Fv)||a.addClass(b.f.C.Fv))};b.f.prototype.Jpa=function(a){a.addClass(b.f.C.YR);a.addClass(b.f.C.d9);a.addClass(b.f.la.EG);this.options.display==b.f.zR.VQ&&a.addClass(b.f.C.c9)};b.f.prototype.W4=function(a){a&&(a.addClass(b.f.C.yG),
f(a.children(b.f.kb.Ep)[0]).addClass(b.f.C.aS))};b.f.prototype.X4=function(a,d){this.Q.vb();var c=this.Q.vb()[a];d.attr(b.f.jb.ak,c.footerStyle);d.hasClass(b.f.C.Dp)||d.addClass(b.f.C.Dp);this.lK()&&!d.hasClass(b.f.C.ys)&&d.addClass(b.f.C.ys);c.footerClassName&&d.addClass(c.footerClassName)};b.f.prototype.Y4=function(a){a&&(a.addClass(b.f.C.zG),a.css(b.f.F.sd,"table-header-group"),a=f(a.children(b.f.kb.Ep)[0]),a.addClass(b.f.C.bS),a.css(b.f.F.ql,b.f.ma.ts))};b.f.prototype.Z4=function(a,d,c){a=this.Q.vb()[a];
if(c||!d.hasClass(b.f.C.Zm))d.addClass(b.f.C.Zm),this.lK()&&(!c&&d.hasClass(b.f.C.ys)||d.addClass(b.f.C.ys)),null==a.headerStyle||!c&&d.attr(b.f.jb.ak)==a.headerStyle||d.attr(b.f.jb.ak,a.headerStyle),null==a.headerClassName||!c&&d.hasClass(a.headerClassName)||d.addClass(a.headerClassName)};b.f.prototype.CI=function(a){var d,c,e=0,g=[],h=a.length;for(d=0;d<h;d++){var k=f(a[d]).attr(b.f.jb.Yr);if(null!=k){k=parseInt(k,10);for(c=0;c<k;c++)g[e+c]=a[d];e+=k}else g[e++]=a[d]}return f(g)};b.f.prototype.QX=
function(){return this.options.horizontalGridVisible==b.f.Ng||this.options.horizontalGridVisible==b.f.Qz?!0:!1};b.f.prototype.lK=function(){return this.options.verticalGridVisible==b.f.Ng||this.options.verticalGridVisible==b.f.Qz&&this.options.display==b.f.zR.VQ?!0:!1};b.f.prototype.Cga=function(){return-1<navigator.userAgent.toLowerCase().indexOf("firefox")?!0:!1};b.f.prototype.iC=function(){if("undefined"==typeof this.yA){var a=navigator.userAgent;"Microsoft Internet Explorer"==navigator.appName?
(a=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(a),null!=a&&(this.yA=parseFloat(a[1]))):0<=a.indexOf("Trident")?this.yA=11:this.yA=null}return this.yA};b.f.prototype.gY=function(){if("undefined"==typeof this.aT){var a=navigator.userAgent.toLowerCase();this.aT=/webkit/.test(a)&&!/edge/.test(a)}return this.aT};b.f.prototype.Ria=function(a,d,c,e){var g=this.Mc(),h=this.km(),k=this.Pk(),l=this.wu(),m=this.er(),n=this.kc(),p=this.hd(),r=null,s=null;if(null!=this.Lc()){var q=this.Lc()[0].scrollHeight-this.Lc()[0].clientHeight,
t=this.Lc()[0].scrollWidth-this.Lc()[0].clientWidth;0<q&&(r=this.Lc()[0].scrollTop);0<t&&(s=this.J2(this.Lc()[0]))}this.xja();this.Jpa(n);q=this.y3();this.Vt=1===q[0]?!0:!1;this.Nq=1===q[1]?!0:!1;if(null!=p){if(this.Vt||this.Nq)this.Bi||(this.Bi={}),0<a||0<d?(0<a&&this.Nq&&(this.Bi[b.f.F.td]=a),0<d&&this.Vt&&(this.Bi[b.f.F.sp]=d)):(this.Bi[b.f.F.sp]=this.Vt?n[0].offsetHeight:0,this.Bi[b.f.F.td]=this.Nq?n[0].offsetWidth:0),this.dD||(this.dD=n.outerWidth()-n.innerWidth()),this.s0||(this.s0=n.outerHeight()-
n.innerHeight()),a=0,this.Vt&&!this.Nq&&(n.css(b.f.F.Rz,b.f.ma.Lg),a=n.get(0).offsetWidth-n.get(0).clientWidth,0<this.Bi[b.f.F.td]?g.css(b.f.F.td,n.get(0).clientWidth+b.f.ma.bc):(g.css(b.f.F.td,n.get(0).scrollWidth+a+b.f.ma.bc),q=this.y3(),1===q[1]&&g.css(b.f.F.td,n.get(0).clientWidth+b.f.ma.bc)),n.css(b.f.F.Rz,"")),d=g.width(),this.bka(),t=0,g=g.children("caption"),null!=g&&0<g.length&&(t=f(g[0]).outerHeight(),g.css(b.f.F.sd,b.f.ma.cR),null!=h&&h.css(b.f.F.uQ,n.css(b.f.F.uQ).toString())),g=0,null!=
h&&(h.css(b.f.F.sd,b.f.ma.Xr),this.Tk()?(h.css(b.f.F.ql,b.f.ma.EF),h.css(b.f.F.zs,"0px")):h.css(b.f.F.ql,b.f.ma.ts),m.css(b.f.F.sd,b.f.ma.Xr),m.css(b.f.F.ql,b.f.ma.ts),g=h.outerHeight()),this.Tk()&&n.css(b.f.F.i8,g+t+b.f.ma.bc),m=0,null!=k&&(this.Tk()?(k.css(b.f.F.ql,b.f.ma.EF),h.css(b.f.F.IF,"0px")):k.css(b.f.F.ql,b.f.ma.ts),k.css(b.f.F.sd,b.f.ma.Xr),l.css(b.f.F.sd,b.f.ma.Xr),l.css(b.f.F.ql,b.f.ma.ts)),p.css(b.f.F.sd,b.f.ma.Xr),l=0,this.Tk()||(p.css(b.f.F.cG,b.f.ma.Lg),p.css(b.f.F.ql,b.f.ma.ts),
this.Nq?p.css(b.f.F.td,this.Bi[b.f.F.td]-this.dD):0<a&&p.css(b.f.F.td,d-this.dD+a),p.width(),null!=k&&(m=k.outerHeight(),p.css(b.f.F.zs,-1*m+b.f.ma.bc)),this.Vt?(l=this.Bi[b.f.F.sp]-g-m-t-this.s0,0<l&&(p.css(b.f.F.sp,l+b.f.ma.bc),p.css(b.f.F.pR,l+b.f.ma.bc))):l=p.outerHeight(),a=this.K2(),this.Nq?(d=this.Kf(),null!=d&&0<d.length?(p.css(b.f.F.yv,b.f.ma.Lg),n.css(b.f.F.yv,b.f.ma.js),n.css(b.f.F.cG,b.f.ma.js),null!=h&&(d=this.Bi[b.f.F.td]-this.dD,0<d&&(0<a?h.css(b.f.F.td,d-a+b.f.ma.bc):h.css(b.f.F.td,
d+b.f.ma.bc)))):(p.css(b.f.F.yv,b.f.ma.js),n.css(b.f.F.yv,b.f.ma.Lg),n.css(b.f.F.cG,b.f.ma.js))):p.css(b.f.F.yv,b.f.ma.js)),this.Tk()&&(h=this.S2(),h.css(b.f.F.Rz,b.f.ma.Lg),this.Nq&&h.css(b.f.F.td,this.Bi[b.f.F.td]),this.Vt&&h.css(b.f.F.sp,this.Bi[b.f.F.sp]-g-m),p.css(b.f.F.p7,b.f.ma.Zj),n.css(b.f.F.Rz,b.f.ma.js)),null!=k&&(this.Tk()||k.css(b.f.F.zs,l+b.f.ma.bc));this.oka();this.wja(0>q[0]);this.s4();null==r||c?c&&(this.Lc()[0].scrollTop=0,this.Lc().scroll()):(q=this.Lc()[0].scrollHeight-this.Lc()[0].clientHeight,
r=r>q?q:r,this.Q.vi()&&q==r&&r--,this.Lc()[0].scrollTop=r,this.Lc().scroll());null==s||e?e&&(this.J4(this.Lc()[0],0),this.Lc().scroll()):(this.J4(this.Lc()[0],s),this.Lc().scroll())}};b.f.prototype.s4=function(){var a=this.kc(),d=this.hd(),c=this.xy(),e=a;0<d.height()&&(e=d);c&&c[0].offsetParent&&(c.css(b.f.F.sp,d.height()+b.f.ma.bc),c.css(b.f.F.td,d.width()+b.f.ma.bc),d=f(c[0].children[0]),a="rtl"===this.Q.ac(),e={my:"center",at:"center",collision:"none",of:e},e=b.nc.xg(e,a),c.position(e),c={my:"center",
at:"center",collision:"none",of:c},c=b.nc.xg(c,a),d.position(c))};b.f.prototype.lja=function(){var a,d,c=this.Q.vb().length;for(a=0;a<c;a++)d=this.Nc(a),null!=d&&d.css(b.f.F.wv,"");a=this.Kf();if(null!=a&&0<a.length)for(a=0;a<c;a++)d=this.dr(0,a,null),null!=d&&d.css(b.f.F.wv,"")};b.f.prototype.wja=function(a){if(this.QX()){var d=this.Kf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)f(d[c]).hasClass(b.f.C.Fv)||f(d[c]).addClass(b.f.C.Fv);d=f(d[d.length-1]);a||d.removeClass(b.f.C.Fv)}}};
b.f.prototype.xja=function(){var a=this.Mc(),d=this.km(),c=this.er(),e=this.Pk(),g=this.wu(),h=this.hd();if(null!=d&&(d.attr(b.f.jb.ak,""),c.attr(b.f.jb.ak,""),(d=c.find("."+b.f.C.ov))&&0<d.length))for(var k=d.length,c=0;c<k;c++)f(d[c]).css(b.f.F.td,"");null!=e&&(e.attr(b.f.jb.ak,""),g.attr(b.f.jb.ak,""));a.css(b.f.F.sd,"");a.css(b.f.F.td,"");null!=h&&h.attr(b.f.jb.ak,"");this.lja()};b.f.prototype.bka=function(){var a=[],d=[],c=null,e,g,f,c=null,k,l,m=this.Q.vb().length;for(k=0;k<m;k++)c=this.Nc(k),
null!=c&&(l=window.getComputedStyle(c[0]),a[k]=parseInt(l[b.f.F.td],10),f=this.Q.En(k,"header"),e||null!=f?d[k]=null!=f?parseInt(l[b.f.F.zp],10)+parseInt(l[b.f.F.yp],10):e:(e=parseInt(l[b.f.F.zp],10)+parseInt(l[b.f.F.yp],10),d[k]=e),f=null,(l=c.find("."+b.f.C.ov))&&0<l.length&&(f=l.get(0).clientHeight),null!=f&&(c=c.find("."+b.f.C.wz),c.css(b.f.F.pR,f+b.f.ma.bc)));e=[];k=this.Kf();if(null!=k&&0<k.length)for(k=0;k<m;k++)f=this.dr(0,k,null),null!=f&&(c=this.Q.En(k,"cell"),g||this.Q.iX(k)?null!=c?(c=
window.getComputedStyle(f[0]),c=parseInt(c[b.f.F.zp],10)+parseInt(c[b.f.F.yp],10)):c=g:(c=window.getComputedStyle(f[0]),c=g=parseInt(c[b.f.F.zp],10)+parseInt(c[b.f.F.yp],10)),c=c>d[k]?a[k]-c+d[k]:a[k]+d[k]-c,e[k]=c);for(k=0;k<m;k++)c=this.Nc(k),null!=c&&c.css(b.f.F.wv,a[k]+b.f.ma.bc),f=this.dr(0,k,null),null!=f&&f.css(b.f.F.wv,e[k]+b.f.ma.bc),g=this.AN(k),null!=g&&(c=parseInt(g.css(b.f.F.zp),10)+parseInt(g.css(b.f.F.yp),10),c=c>d[k]?a[k]-c+d[k]:a[k]+d[k]-c,g.css(b.f.F.wv,c+b.f.ma.bc))};b.f.prototype.oka=
function(){var a=this.Q.vb(),d,c,e,g,h,k,l=a.length;for(d=0;d<l;d++)c=a[d],e=this.Nc(d),null!=e&&(g=e.children("."+b.f.C.wz),0<g.length&&(g=f(g[0]),(h=e.find("."+b.f.C.ov))&&0<h.length&&(k=0,c.sortable==b.f.Ng&&(k=f(e.find("."+b.f.C.AQ).get(0)).width()),0<g[0].clientWidth&&h.width()+k>g[0].clientWidth&&(h.css(b.f.F.td,""),c=h.width(),e=e.width()-k,c>e+1&&h.css(b.f.F.td,e+b.f.ma.bc)))))};b.f.C={vQ:"oj-table-checkbox-acc-select-column",wQ:"oj-table-checkbox-acc-select-row",d9:"oj-table-container",fS:"oj-table-scroller",
YR:"oj-table",c9:"oj-table-grid-display",f9:"oj-table-element",yG:"oj-table-footer",aS:"oj-table-footer-row",zG:"oj-table-header",bS:"oj-table-header-row",Zm:"oj-table-column-header-cell",nqa:"oj-table-column-header-drop-empty-cell",xQ:"oj-table-column-header-acc-select-column",MF:"oj-table-column-header-acc-select-row",lqa:"oj-table-column-header-acc-select-row-text",wz:"oj-table-column-header",ov:"oj-table-column-header-text",vz:"oj-table-column-header-asc",Az:"oj-table-column-header-dsc",AQ:"oj-table-column-header-sort-placeholder",
J6:"oj-table-column-header-acc-asc-link",K6:"oj-table-column-header-acc-dsc-link",pp:"oj-table-column-header-asc-link",Zr:"oj-table-column-header-dsc-link",L6:"oj-table-column-header-asc-icon",M6:"oj-table-column-header-dsc-icon",yz:"oj-table-column-header-drag-indicator-before",xz:"oj-table-column-header-drag-indicator-after",yQ:"oj-table-column-header-cell-drag-image",rG:"oj-table-body",Cp:"oj-table-body-row",uG:"oj-table-body-row-drag-indicator-before",e9:"oj-table-body-row-drag-indicator-after",
wG:"oj-table-body-row-touch-selection-affordance-top",vG:"oj-table-body-row-touch-selection-affordance-bottom",$R:"oj-table-body-row-touch-selection-affordance-top-icon",ZR:"oj-table-body-row-touch-selection-affordance-bottom-icon",xG:"oj-table-body-row-touch-selection-affordance-touch-area",tG:"oj-table-body-current-row",xs:"oj-table-data-cell",sG:"oj-table-data-cell-acc-select",ys:"oj-table-vgrid-lines",Fv:"oj-table-hgrid-lines",Dp:"oj-table-footer-cell",Dqa:"oj-table-footer-drop-empty-cell",cS:"oj-table-inline-message",
AG:"oj-table-status-message",g9:"oj-table-status-message-text",dS:"oj-table-no-data-message",eS:"oj-table-no-data-row",Gp:"oj-component-icon",gi:"oj-helper-hidden-accessible"};b.f.F={sd:"display",ql:"position",sp:"height",td:"width",zs:"top",IF:"bottom",Zj:"left",Yz:"right",i8:"padding-top",yp:"padding-left",zp:"padding-right",Rz:"overflow",yv:"overflow-x",cG:"overflow-y",wv:"min-width",pR:"min-height",p7:"float",uQ:"border-top",tQ:"border-bottom-width",H6:"border-left-width",Oz:"margin-bottom",n9:"vertical-align",
DQ:"cursor",o9:"z-index"};b.f.ma={en:"none",Xr:"block",ts:"relative",EF:"absolute",cR:"inline",Lg:"auto",js:"hidden",Zj:"left",bc:"px",X7:"middle",Y7:"move"};b.f.jb={ak:"style",Ev:"tabindex",fA:"type",Yj:"id",cA:"title",u7:"href",UF:"headers",Yr:"colspan"};b.f.kb={Vj:"div",DF:"a",Ep:"tr",rl:"td",iS:"th",Cqa:"table",gS:"tbody",jS:"thead",hS:"tfoot",Iz:"input",m9:"ul",X8:"span"};b.f.la={EG:"oj-component",gf:"oj-active",op:"oj-clickable-icon-nocontext",tb:"oj-disabled",kf:"oj-enabled",Zi:"oj-focus",
Xj:"oj-hover",bd:"oj-selected",iA:"oj-warning",NQ:"oj-draggable",ds:"oj-drag"};b.f.zQ="_hdrColRowSel";b.f.Qz="auto";b.f.Ng="enabled";b.f.kn="disabled";b.f.ki={vs:"single",wp:"multiple"};b.f.zR={xqa:"list",VQ:"grid"};b.bb=function(a){this.Q=a;this.options=a.options;this.Init()};o_("TableDndContext",b.bb,b);b.b.ga(b.bb,b.b,"oj.TableDndContext");b.bb.prototype.Init=function(){b.bb.q.Init.call(this)};b.b.g("TableDndContext.prototype.Init",{Init:b.bb.prototype.Init});b.bb.prototype.w9=function(a){this.p().Nc(a).addClass(b.f.la.ds);
this.p().K4(a,!0,b.f.la.ds)};b.bb.prototype.hja=function(){var a=this.p().km().find("."+b.f.la.ds);if(null!=a&&0<a.length){var d,c=a.length;for(d=0;d<c;d++)f(a[d]).removeClass(b.f.la.ds)}this.p().K4(null,!1,b.f.la.ds)};b.bb.prototype.caa=function(a){var b;a[0].getBoundingClientRect();var c=a.scrollLeft(),e=a.scrollTop();b=a.clone();b.css({overflow:"hidden","overflow-x":"hidden","overflow-y":"hidden","background-color":"transparent",width:a.css("width"),height:a.css("height"),position:"fixed",top:1E4});
f("body").append(b);b.scrollLeft(1*c);b.scrollTop(1*e);return b};b.bb.prototype.tba=function(){this.eI&&(this.eI.remove(),this.eI=null)};b.bb.prototype.bq=function(a){return this.p().je(f(a.currentTarget))};b.bb.prototype.Fda=function(a){var d;d=f(a.target).closest("tr");d=(a=this.Q.getContextByNode(a.target))&&"oj-table-cell"==a.subId?a.rowIndex:d&&d.hasClass(b.f.C.uG)?this.Dn:(d=this.p().Kf())?d.length:0;return d};b.bb.prototype.p=function(){return this.Q.p()};b.bb.prototype.Vna=function(a){if(this.eK()){var b=
this.bq(a);this.XA=b;this.Eka(a,b);this.Q.Rt(null);this.Q.option("selection",null,{_context:{Ec:!0,Za:!0}});setTimeout(function(){window.getSelection().removeAllRanges()},0);this.w9(b);return!0}};b.bb.prototype.Rna=function(){this.eK()&&(this.M4(null,!1),this.XA=null,this.p().BE(),this.p().lpa(),this.hja())};b.bb.prototype.Sna=function(a){if(!this.gC()){var b=this.bq(a);return this.tt("columns","dragEnter",a,{columnIndex:b})}};b.bb.prototype.Xna=function(a){var b=this.bq(a),c=this.XA;null!=c&&c!=
b&&((this.Ks=this.fK(a))&&c==b-1||!this.Ks&&c==b+1||this.p().Q1(b,this.Ks),a.preventDefault())};b.bb.prototype.Una=function(a){if(this.gC())return this.Xna(a);var b=this.bq(a);this.Ks=this.fK(a);var c=this.tt("columns","dragOver",a,{columnIndex:b});(!1===c||a.isDefaultPrevented())&&this.p().Q1(b,this.fK(a));return c};b.bb.prototype.Tna=function(a){if(!this.gC()){this.p().BE();var b=this.bq(a);return this.st("drop","columns","dragLeave",a,{columnIndex:b})}};b.bb.prototype.Yna=function(a){var b=this.bq(a);
this.Ks||b++;this.Q.hk=this.p().Poa(this.XA,b,a);a.preventDefault()};b.bb.prototype.Wna=function(a){if(this.gC())return this.Yna(a);this.p().BE();var b=this.bq(a);this.Ks||b++;return this.tt("columns","drop",a,{columnIndex:b})};b.bb.prototype.loa=function(a){var b=this.options.dnd.drag;if(b&&b.rows)return(b=this.fka(a,b.rows.dataTypes,this.Q.Gw()))?this.st("drag","rows","dragStart",a,b):!1};b.bb.prototype.goa=function(a){return this.st("drag","rows","drag",a)};b.bb.prototype.hoa=function(a){this.tba();
return this.st("drag","rows","dragEnd",a)};b.bb.prototype.ioa=function(a){var b=this.Fda(a),c=this.tt("rows","dragEnter",a,{rowIndex:b});(!1===c||a.isDefaultPrevented())&&this.Qla(a,b);return c};b.bb.prototype.koa=function(a){return this.tt("rows","dragOver",a,{rowIndex:this.Dn})};b.bb.prototype.joa=function(a){var b=this.st("drop","rows","dragLeave",a,{rowIndex:this.Dn});this.Aga(a,a.currentTarget)||(this.p().CO(),this.Dn=null);return b};b.bb.prototype.moa=function(a){var b=this.Dn;this.p().CO();
this.Dn=null;return this.tt("rows","drop",a,{rowIndex:b})};b.bb.prototype.Lfa=function(a,b){var c;c=a.children("tr");for(var e=0;e<c.length;e++)-1==b.indexOf(e)&&f(c[e]).css("visibility","hidden")};b.bb.prototype.st=function(a,d,c,e,g){a=this.options.dnd[a];var f;if(a&&a[d]&&(d=a[d][c])&&"function"==typeof d)try{e.dataTransfer=e.originalEvent.dataTransfer,f=d(e,g)}catch(k){b.r.error("Error: "+k)}return f};b.bb.prototype.tt=function(a,b,c,e){b=this.st("drop",a,b,c,e);void 0===b&&this.oha(c,a)&&c.preventDefault();
return b};b.bb.prototype.eK=function(){var a=this.options.dnd;return a&&a.reorder&&a.reorder.columns==this.Q.Ng?!0:!1};b.bb.prototype.gC=function(){return null!=this.XA};b.bb.prototype.Aga=function(a,b){var c=b.getBoundingClientRect(),e=a.originalEvent;return e.clientX>=c.left&&e.clientX<c.right&&e.clientY>=c.top&&e.clientY<c.bottom};b.bb.prototype.fK=function(a){var d=a.currentTarget.getBoundingClientRect();return null!=a.originalEvent.clientX?(a=d.right-a.originalEvent.clientX<(d.right-d.left)/
2,"rtl"===b.v.im()?a:!a):!1};b.bb.prototype.oha=function(a,b){var c=a.originalEvent.dataTransfer.types,e=this.options.dnd.drop;if(e&&e[b]&&e[b].dataTypes)for(var e=e[b].dataTypes,e="string"==typeof e?[e]:e,g=0;g<c.length;g++)if(0<=e.indexOf(c[g]))return!0;return!1};b.bb.prototype.nka=function(a,d){if(a.draggable=d)f(a).css(b.f.F.DQ,b.f.ma.Y7),f(a).addClass(b.f.la.NQ)};b.bb.prototype.Y$=function(a){a.draggable="";f(a).css(b.f.F.DQ,b.f.ma.Lg);f(a).removeClass(b.f.la.NQ)};b.bb.prototype.eka=function(a,
b,c){a=a.dataTransfer;c=JSON.stringify(c);if("string"==typeof b)a.setData(b,c);else if(b)for(var e=0;e<b.length;e++)a.setData(b[e],c)};b.bb.prototype.fka=function(a,b,c){for(var e=[],g=0;g<c.length;g++){var h=this.Q.getDataForVisibleRow(c[g]);h&&e.push(h)}return e.length?(this.eka(a.originalEvent,b,e),this.eI=this.gka(a.originalEvent,f(a.currentTarget).closest("tbody"),c),{rows:e}):null};b.bb.prototype.gka=function(a,b,c){var e=this.caa(b);this.Lfa(e,c);c=b[0].getBoundingClientRect();var g=b.scrollLeft();
b=b.scrollTop();a.dataTransfer.setDragImage(e[0],a.clientX-c.left+g,a.clientY-c.top+b);return e};b.bb.prototype.Eka=function(a,b){var c=a.originalEvent.dataTransfer,e=this.p().hr(this.p().Nna());c.setData("Text",this.Q.d7+":"+e+":"+b);e=this.p().Yma(b);try{c.setDragImage(e[0],0,0)}catch(g){}};b.bb.prototype.M4=function(a,b){if(this.eK()){var c=this.p().wy();if(null!=c&&0<c.length){var e;for(e=0;e<c.length;e++){var g=c[e];null!=a&&e==a?this.nka(g,b):this.Y$(g)}}}};b.bb.prototype.Qla=function(a,b){if(this.Dn!=
b){var c=f(a.target).closest("tr");this.Dn=b;this.p().jna(this.Dn,c)}};b.Yf={};b.Yf.u1=function(a,d){var c=f(a.headerContext.parentElement),e=f(document.createElement("div"));e.addClass(b.f.C.wz);c.empty();c.append(e);c=f(document.createElement("div"));c.addClass(b.f.C.ov);e.prepend(c);null!=d?d(c):this.v1(c,a)};b.Yf.w1=function(a,d){var c=a.headerContext.component,e=f(a.headerContext.parentElement),g=f(document.createElement("div"));g.addClass(b.f.C.wz);e.empty();e.append(g);"rtl"===c.ac()?g.css(b.f.F.yp,
"0px"):g.css(b.f.F.zp,"0px");e=f(document.createElement("div"));e.addClass(b.f.C.vz);g.append(e);var h=f(document.createElement("a"));h.addClass(b.f.C.pp);h.addClass(b.f.C.Gp);h.addClass(b.f.C.L6);h.addClass(b.f.la.tb);h.addClass(b.f.la.op);c._hoverable(h);e.append(h);var h=e.width(),k=e.height(),l=f(document.createElement("a"));l.attr("tabindex","0");l.attr("href","#");l.addClass(b.f.C.J6);l.addClass(b.f.C.gi);l.text(c.A("labelSortAsc"));e.append(l);e=f(document.createElement("div"));e.addClass(b.f.C.AQ);
e.css(b.f.F.sd,"inline-block");e.css(b.f.F.n9,b.f.ma.X7);e.css("width",h+"px");e.css("height",k+"px");g.append(e);e=f(document.createElement("div"));e.addClass(b.f.C.Az);e.addClass(b.f.la.tb);g.append(e);h=f(document.createElement("a"));h.addClass(b.f.C.Zr);h.addClass(b.f.C.Gp);h.addClass(b.f.C.M6);h.addClass(b.f.la.tb);h.addClass(b.f.la.op);c._hoverable(h);e.append(h);h=f(document.createElement("a"));h.attr("tabindex","0");h.attr("href","#");h.addClass(b.f.C.K6);h.addClass(b.f.C.gi);h.text(c.A("labelSortDsc"));
e.append(h);c=f(document.createElement("div"));c.addClass(b.f.C.ov);g.prepend(c);null!=d?d(c):this.v1(c,a)};b.Yf.v1=function(a,b){var c=b.columnIndex,c=b.headerContext.component.vb()[c];a.text(c.headerText)};b.Yf.Opa=function(a,b,c){var e=c.rowContext.component,g=f(c.rowContext.parentElement),h=e.p().hr(b.key),k=e.vb();e.p().LO(b,g);g=k.length;for(e=0;e<g;e++)this.Npa(a,e,b,h,c)};b.Yf.Npa=function(a,d,c,e,g){var h=g.rowContext.component;g=f(g.rowContext.parentElement);var k=h.vb()[d],l=h.p().Qma();
h.p().QO(d,l,!0);h.p().toa(a,c.key,e,d,l,g);var m=null;null!=k.field&&(m=c.data[k.field]);if(k=h.En(d,"cell")){var n=this.aE(h,c,l[0]),m=k({cellContext:n,columnIndex:d,data:m,row:f.extend({},c.data)});null!=m?l.append(m):(l=f(g.children(":not(."+b.f.C.sG+")")[d]),h.p().KO(a,c.key,e,d,l),h.p().QO(d,l,!1))}else l.text(m)};b.Yf.aE=function(a,d,c){var e={};e.component=a;var g=a.Ya();g instanceof b.ka&&(g=g.getWrappedDataSource());e.datasource=g;e.parentElement=c;if(null!=d&&(e.status=this.Gna(a,d),g instanceof
b.lb)){a=g.YI(d.index);for(var f in a)a.hasOwnProperty(f)&&(e[f]=a[f])}return e};b.Yf.Gna=function(a,b){return{rowIndex:b.index,rowKey:b.key,currentRow:f.extend({},a.DV())}}});