/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtTreemap"],function(b,f,a,d,c){b.ya("oj.ojTreemap",f.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{optionChange:null},jf:function(a,b,d){return c.DvtTreemap.newInstance(a,b,d)},ai:function(a){var b=a.subId;"oj-treemap-node"==b?b="node"+this.rp(a.indexPath):"oj-treemap-tooltip"==b&&(b="tooltip");return b},$f:function(a){var b={};0==a.indexOf("node")?(b.subId="oj-treemap-node",b.indexPath=this.kl(a)):
"tooltip"==a&&(b.subId="oj-treemap-tooltip");return b},ye:function(){var a=this._super();a.push("oj-treemap");return a},bi:function(){var a=this._super();a["oj-treemap-isolate-icon"]={path:"_resources/isolate",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-hover"]={path:"_resources/isolateOver",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-active"]={path:"_resources/isolateDown",property:"CSS_URL"};a["oj-treemap-restore-icon"]={path:"_resources/restore",property:"CSS_URL"};a["oj-treemap-restore-icon oj-hover"]=
{path:"_resources/restoreOver",property:"CSS_URL"};a["oj-treemap-restore-icon oj-active"]={path:"_resources/restoreDown",property:"CSS_URL"};a["oj-treemap-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node oj-hover"]={path:"nodeDefaults/hoverColor",
property:"border-top-color"};a["oj-treemap-node oj-selected"]=[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header"]=[{path:"nodeDefaults/header/backgroundColor",property:"background-color"},{path:"nodeDefaults/header/borderColor",property:"border-top-color"},{path:"nodeDefaults/header/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-treemap-node-header oj-hover"]=[{path:"nodeDefaults/header/hoverBackgroundColor",
property:"background-color"},{path:"nodeDefaults/header/hoverOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/hoverInnerColor",property:"border-bottom-color"},{path:"nodeDefaults/header/_hoverLabelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-treemap-node-header oj-selected"]=[{path:"nodeDefaults/header/selectedBackgroundColor",property:"background-color"},{path:"nodeDefaults/header/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/selectedInnerColor",
property:"border-bottom-color"},{path:"nodeDefaults/header/_selectedLabelStyle",property:"CSS_TEXT_PROPERTIES"}];return a},di:function(){return["optionChange"]},ei:function(){var a=this.options.translations,b=this._super();b["DvtTreemapBundle.COLOR"]=a.labelColor;b["DvtTreemapBundle.ISOLATE"]=a.tooltipIsolate;b["DvtTreemapBundle.RESTORE"]=a.tooltipRestore;b["DvtTreemapBundle.SIZE"]=a.labelSize;b["DvtUtilBundle.TREEMAP"]=a.componentName;return b},hi:function(a){var b=a&&a.getType?a.getType():null;
b===c.DvtSelectionEvent.TYPE?this.gc("selection",a.getSelection()):b===c.DvtTreemapIsolateEvent.TYPE?(b=this.options.hY,b||(this.options.hY=[],b=this.options.hY),(a=a.getId())?(b.push(a),this.gc("isolatedNode",a)):(b.pop(),this.gc("isolatedNode",0<b.length?b[b.length]:null))):this._super(a)},getNode:function(a){a=this.na.getAutomation().getNode(a);this.Mg(a);return a},getContextByNode:function(a){return(a=this.getSubIdByNode(a))&&"oj-treemap-tooltip"!==a.subId?a:null},ci:function(){return{root:["nodes"]}}})});