/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojdnd"],function(b,f){function a(){}a.ji="oj-expanded";a.mf="oj-collapsed";a.xp="oj-hover";a.$i="oj-selected";a.ad="oj-disabled";a.Aqa="oj-default";a.ms="oj-treenode-temp";b.fa=function(a){this.Init(a)};b.b.ga(b.fa,b.b,"oj.TreeDndContext");b.fa.prototype.Init=function(a){b.fa.q.Init.call(this);this.Q=a;this.options=a.options;this.ZZ()};b.b.g("TreeDndContext.prototype.Init",{Init:b.fa.prototype.Init});b.fa.prototype.t3=function(){var a=this.oc;return a.reorder||
a.mg};b.fa.prototype.Boa=function(){var a=this.oc;return a.reorder||a.Aj};b.fa.prototype.Zna=function(){var a=this.oc,c=b.fa,e=a.reorder,f=a.mg;this.HU();this.o3();a=this.oc;if(e!=a.reorder||f!=a.mg)a.reorder||a.mg||this.Q.aa.find("li").removeClass(c.aG).removeClass(c.Pz).removeClass(c.jn).removeAttr("draggable");this.n3()};b.fa.prototype.o3=function(){var a=this.options.dnd,c=this.oc,e=b.fa,g=!0,h;c.reorder=!1;"object"!=typeof a?this.options.dnd={reorder:"disable"}:(h=a[e.c7],"string"===typeof h&&
("enable"===h?(c.reorder=!0,g=!1):"disable"==h&&(g=!1)),g&&(this.options.dnd.reorder="disable"),h=a[e.T6],"object"==typeof h&&(h=h[e.MQ],"object"==typeof h&&(g=h[e.W6],"function"==typeof g&&(c.ky=g,c.mg=!0),g=h[e.U6],"function"==typeof g&&(c.QD=g,c.mg=!0),g=h[e.V6],"function"==typeof g&&(c.XM=g,c.mg=!0),g=h[e.LQ],f.isArray(g)?(c.Zq=g.slice(),c.mg=!0):"string"==typeof g&&(c.Zq=[g],c.mg=!0))),h=a[e.X6],"object"==typeof h&&(h=h[e.MQ],"object"==typeof h&&(g=h[e.Y6],"function"==typeof g&&(c.SD=g,c.Aj=
!0),g=h[e.a7],"function"==typeof g&&(c.UD=g,c.Aj=!0),g=h[e.Z6],"function"==typeof g&&(c.TD=g,c.Aj=!0),g=h[e.b7],"function"==typeof g&&(c.VD=g,c.Aj=!0),g=h[e.LQ],f.isArray(g)?(c.RD=g.slice(),c.Aj=!0):"string"==typeof g&&(c.RD=[g],c.Aj=!0))),c.reorder||(c.Zq||c.ky||(c.mg=!1,c.ky=c.QD=c.XM=c.Zq=null),c.VD||(c.Aj=!1,c.SD=c.UD=c.TD=c.VD=c.RD=null)),c.yE=c.reorder&&!c.mg)};b.fa.prototype.n3=function(){var a=this.oc,c=a.Ad,e=b.fa;if(a.mg||a.Aj||a.reorder){b.fa.OU?(c.Uk=b.fa.OU,c.Ki=b.fa.Lba):(c.Uk=f("\x3cdiv class\x3d'oj-tree-drop-marker'\x3e\x3cspan class\x3d'oj-tree-drop-ptr oj-component-icon'\x3e\x26#160;\x3c/span\x3e\x3c/div\x3e").css("pointer-events",
"none").hide().appendTo("body"),c.Ki=f("\x3cdiv /\x3e").addClass(e.g8).css("pointer-events","none").hide().appendTo("body"),b.fa.OU=c.Uk,b.fa.Lba=c.Ki);a.T3=c.Ki.width();var c=this.Q.element[0],g=f(c).children("ul:eq(0)");if(a.reorder||a.mg)a.gN=this.gI.bind(this),a.cN=this.Iba.bind(this),f(c).on("dragstart",a.gN),f(c).on("dragend",a.cN),g.length&&g.find("li").addClass(e.aG).addClass(e.Pz).addClass(e.jn).attr("draggable","true");if(a.reorder||a.Aj)a.aN=this.Gba.bind(this),a.dN=this.Jba.bind(this),
a.fN=this.Nba.bind(this),a.eN=this.Kba.bind(this),a.bN=this.Hba.bind(this),f(c).on("drag",a.aN),f(c).on("dragenter",a.dN),f(c).on("dragover",a.fN),f(c).on("dragleave",a.eN),f(c).on("drop",a.bN)}};b.fa.prototype.eaa=function(){this.HU()};b.fa.prototype.gI=function(d){var c,e,g=f(d.target).closest("li"),h=d.originalEvent.dataTransfer,k;c=this.oc;e=c.Ad;e.rb=null;e.va=null;c.pr=null;c.pO=null;c.Ty=null;c.ly=!1;if(!c.reorder&&!c.mg||g.hasClass(a.ad)||this.Q.i.Z.locked)d.preventDefault();else{e=this.Q.isSelected(g)?
this.Q.sa(null,!0):e=g;(c.mg||c.yE)&&this.dka(h,e);if(c.ky){k=c.ky(d,{item:void 0});if(d.isDefaultPrevented()||"boolean"===typeof k&&!k)return k;if(!c.Zq&&!this.O$(h)&&!c.reorder)return d.preventDefault(),!1}"uninitialized"===h.effectAllowed&&(h.effectAllowed=c.yE?"move":b.v.Io(d)?"copy":"move");this.Bba(e,g,d)}};b.fa.prototype.Gba=function(a){var b=this.oc;b.QD&&b.QD(a)};b.fa.prototype.Jba=function(d){this.Q.aa[0].firstChild||this.D9();var c=f(d.target),e=this.Q.sa(c),g=this.oc,h=g.Ad,k=e&&0<e.length&&
e.hasClass("oj-tree-node"),l=d.originalEvent.dataTransfer,m=b.fa,n=!1,p=!1,r;k&&e.hasClass(a.ms)&&(g.Hk=!0);if(!k||"UL"!=d.target.tagName||"group"!=d.target.getAttribute("role"))if(g.Hf=!g.ly,!g.Hf&&!g.reorder||g.Hf&&this.gK(l,m.SF))this.Xp();else{if(g.Hf&&(n=this.gK(l,m.RF),!g.Aj)){this.Xp();return}h.va=!1;g.pr&&this.Zv(g.pr);c.hasClass("oj-tree")&&(e=g.pr);if(!e||!e.length||e.attr("id")!=g.Ty){n&&k&&(g.pr=null,h.rb=2);g.Hf&&!n&&(h.rb=1);h.va=e;g.pr=e;this.IU(d,e);if(this.wba()){h.va.removeClass(m.bG).addClass(m.jn).addClass(m.yR);
g.SD&&(r=g.SD(d,{item:g.Hk?null:e,position:g.Hk?"first":g.zg,reference:g.Hk?null:h.va}));if(void 0===r)this.MX(l)?(d.preventDefault(),d.stopPropagation()):p=g.Hf||!g.reorder;else if(!1===r||d.isDefaultPrevented())d.preventDefault(),d.stopPropagation();else if(g.Hf||!g.reorder)p=g.Hf||!g.reorder;p&&this.Xp();return r}this.Zv(h.va);h.va=null}this.Os()}};b.fa.prototype.Nba=function(a){var b=this.oc,e=b.Ad,f=a.originalEvent.dataTransfer,h=!1,k,l,m;if(e.va&&e.va.length&&(l=e.va,l.hasClass("oj-tree-node")&&
(k=l.attr("id"),k!=b.Ty&&(this.IU(a,l),this.bI())))){b.UD&&(m=b.UD(a,{item:b.Hk?null:l,reference:b.Hk?null:e.va,position:b.Hk?"first":e.UN}));if(void 0===m)this.MX(f)?(a.preventDefault(),a.stopPropagation()):h=b.Hf||!b.reorder;else if(!1===m||a.isDefaultPrevented())a.preventDefault(),a.stopPropagation();else if(b.Hf||!b.reorder)h=b.Hf||!b.reorder;h&&this.Xp();return m}this.Os()};b.fa.prototype.Hba=function(a){var b=this.oc,e=b.Ad,f=!1,h;if(e.va){if(b.VD)h=b.VD(a,{reference:b.Hk?null:e.va,position:b.Hk?
"first":e.UN,reorder:!b.Hf&&b.reorder});else if(b.Hf||!b.reorder)f=!0;f||h&&!a.isDefaultPrevented()||this.xba(a)}b.Hf&&this.Xp();f||(a.preventDefault(),a.stopPropagation());b.pO=null;return h};b.fa.prototype.Iba=function(a){var b=this.oc,e=b.Ad;b.XM&&b.XM(a,{reorder:b.reorder&&!1===e.rb});this.Cba();this.Xp()};b.fa.prototype.D9=function(){this.IX||(this.IX=f("\x3cli class\x3d'"+a.ms+" oj-tree-node oj-tree-leaf oj-valid-drop' id\x3d'"+a.ms+"'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e\x3ca href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e\x3c/span\x3e\x3c/a\x3e\x3c/li\x3e"));
this.Q.aa.append(this.IX)};b.fa.prototype.Kba=function(a){var b=this.oc,e=b.Ad,g=f(a.target),h=g.closest("li"),k=h&&0<h.length&&h.hasClass("oj-tree-node");h.attr("id");var l=a.originalEvent.dataTransfer;b.TD&&b.TD(a,{item:b.Hk?null:h});g.hasClass("oj-tree")||!k||"none"==l.dropEffect?this.yba(a):b.pO=h;e.va&&this.Zv(e.va)};b.fa.prototype.wba=function(){var b=this.oc,c=b.Ad,e;b.wE=!1;e=this.bI();var f=b.Voa;f&&(b.Mra&&clearTimeout(b.xm),c.va&&c.va.length&&c.va.hasClass(a.mf)&&(b.xm=setTimeout(this.zba.bind(this),
f)));b=typeof e;return"boolean"==b&&e||"string"==b};b.fa.prototype.zba=function(){var a=this.oc,b=a.Ad;a.xm=!1;this.Q.Xd(b.va,this.bI.bind(this),!0)};b.fa.prototype.xba=function(a){var c=this.oc,e=c.Ad;c.ly&&c.reorder&&"object"==typeof e.rb&&0<e.rb.length&&(this.Q.hx(e.rb,e.va,e.UN,b.v.Io(a)),e.rb=!1)};b.fa.prototype.WA=function(b){b.hasClass(a.$i)&&(b.removeClass(a.$i),this.Q.vj(b,!0));var c=(b=this.Q.getChildren(b))&&b.length?b.length:0,e;for(e=0;e<c;e++)this.WA(f(b[e]))};b.fa.prototype.IU=function(b,
c){var e=this.oc;c&&(c.hasClass(a.ms)?e.zg="after":(b=b.originalEvent,e.off=c.offset(),e.zg=b.pageY-(e.off.top||0),e.zg=e.zg>=this.Q.i.Z.Jo?"after":0>e.zg?"before":"inside","after"===e.zg&&c.hasClass(a.ji)&&(e.zg="first")))};b.fa.prototype.yba=function(a){var b=this.oc,e=b.Ad;b.after=!1;b.before=!1;b.xu=!1;b.Cra=null;this.Os();e.va&&e.va[0]===a.target.parentNode&&b.xm&&(clearTimeout(b.xm),b.xm=!1)};b.fa.prototype.Xp=function(){this.Os();var a=this.oc,b=a.Ad;b.rb=!1;b.va=!1;a.xm&&clearTimeout(a.xm);
a.Ty=null;a.Hf=!1;a.pr=null;a.pO=null;a.after=!1;a.before=!1;a.xu=!1;a.off=!1;a.wE=!1;a.xm=!1;a.Hf=!1;a.Hk=!1};b.fa.prototype.HU=function(){var a=this.oc,b;b=f(this.Q.ua[0]);b.off("dragstart",a.gN);b.off("dragend",a.cN);b.off("drag",a.aN);b.off("dragenter",a.dN);b.off("dragover",a.fN);b.off("dragleave",a.eN);b.off("drop",a.bN);this.Xp();this.ZZ()};b.fa.prototype.bI=function(){var a=this.oc,b=a.Ad,e=this.Q,f=!1;if(!b.va||!b.va.length)return!1;if("number"==typeof b.rb&&(1===b.rb||2===b.rb))f=!0;else if(!b.rb)return!1;
a.off=b.va.offset();this.Q.lC&&(a.off.right=a.off.left+b.va.width()-b.va.find("\x3ea").width()-30);a.a5=b.va.find("a").width();f?(a.before="before"==a.zg,a.after="after"==a.zg,a.xu="inside"==a.zg):(e.px(b.rb,b.va,"before"),a.before=e.EA(),e.px(b.rb,b.va,"after"),a.after=e.EA(),this.Q.Ol(b.va)?(e.px(b.rb,b.va,"inside"),a.xu=e.EA()):a.xu=!1);a.wE=!0;return this.Aba()};b.fa.prototype.Aba=function(){var a=this.oc,c=!1,e=b.fa,f=a.Ad,h=this.Q.lC,k,l,m,n=this.Q.i.Z.Jo,p=!1;if(!a.wE)return this.Os(),p;if("after"==
a.zg&&a.after||"inside"==a.zg&&a.xu||"before"==a.zg&&a.before||"first"==a.zg)p=a.zg;"first"===p&&(c=f.va.find("li:eq(0)"),a.off=c.offset());l=h?a.off.right-18:a.off.left+5;c=!this.Q.isLeaf(f.va);k=h?l+a.a5+18:l;l=h?k-a.T3:l+8;m=a.off.top-3;switch(p){case "before":case "first":this.gx(f.Uk,{left:k,top:m-7});f.Ki&&this.gx(f.Ki,{left:l,top:m});break;case "after":m+=n;this.gx(f.Uk,{left:k,top:m-2});f.Ki&&this.gx(f.Ki,{left:l,top:m+6});break;case "inside":this.gx(f.Uk,{left:k+(h?c?-4:0:4),top:a.off.top+
n/2-8});f.Ki&&f.Ki.hide();break;default:this.Os()}p?f.va.removeClass(e.bG).addClass(e.jn):f.va.removeClass(e.jn).removeClass(e.jn);return f.UN=p};b.fa.prototype.Os=function(){var a=this.oc.Ad;a&&(a.Uk&&a.Uk.hide(),a.Ki&&a.Ki.hide(),a.va&&this.Zv(a.va))};b.fa.prototype.gx=function(a,b){b.left+="px";b.top+="px";a.css(b).show()};b.fa.prototype.Bba=function(a,c,e){var f=this.oc,h=f.Ad,k=b.fa;h.rb=a;h.rb.addClass(k.Pz);f.Ty=c.attr("id");try{e.currentTarget.unselectable="on",e.currentTarget.onselectstart=
function(){return!1},e.currentTarget.style&&(e.currentTarget.style.MozUserSelect="none")}catch(l){}this.Q.Pga()&&h.Uk&&h.Uk.addClass("oj-tree-"+this.Q.i.Ab.Mu);a=this.Q.ua;f.Hma=a.offset();f.cna=parseInt(a.width(),10);f.ch=parseInt(a.height(),10);f.ly=!0};b.fa.prototype.Cba=function(){var a=this.oc,c=a.Ad,e=b.fa;c.va&&this.Zv(c.va);"number"!=typeof c.rb&&c.rb&&c.rb.removeClass(e.Pz);a.ly=!1};b.fa.prototype.dka=function(a,c){var e=this.oc,f=b.fa,h,k;(h=this.Q.tS(c))&&(k=JSON.stringify(h));if(e.Zq)for(h=
0;h<e.Zq.length;h++)a.setData(e.Zq[h],k);a.setData(f.RF,"0");e.yE&&a.setData(f.SF,"0")};b.fa.prototype.gK=function(a,b){var e=a.types,f=e.length,h;for(h=0;h<f;h++)if(b==e[h])return!0;return!1};b.fa.prototype.MX=function(a){var b=this.oc.RD,e=!1,f;if(b)for(e=!(0<b.length),f=0;f<b.length;f++){if(this.gK(a,b[f])){e=!0;break}}else e=!0;return e};b.fa.prototype.O$=function(a){var c=(a=a.types)&&a.length?a.length:0,e=b.fa,f=!1,h,k;for(k=0;k<c;k++)if(h=a[k],h!=e.RF&&h!=e.SF){f=!0;break}return f};b.fa.prototype.Zv=
function(a){var c=b.fa;a&&a.removeClass(c.jn).removeClass(c.bG).removeClass(c.yR)};b.fa.prototype.ZZ=function(){var a={};this.oc=a;a.reorder=!1;a.yE=!1;a.Hf=!1;a.ly=!1;a.Ty=null;a.pr=null;a.gN=null;a.cN=null;a.aN=null;a.dN=null;a.fN=null;a.eN=null;a.bN=null;a.mg=!1;a.Aj=!1;a.ky=null;a.QD=null;a.rra=null;a.SD=null;a.UD=null;a.TD=null;a.sra=null;a.RD=null;a.after=!1;a.xu=!1;a.before=!1;a.off=!1;a.wE=!1;a.xm=!1;a.Hma=!1;a.cna=!1;a.ch=!1;a.T3=100;a.a5=100;a.Voa=500;a.Ad={};a.Ad.rb=!1;a.Ad.va=!1;a.Ad.Uk=
!1;a.Ad.Ki=!1};b.fa.prototype.I0=function(a){this.Q.I0(a)};b.fa.aG="oj-draggable";b.fa.Pz="oj-drag";b.fa.yR="oj-active-drop";b.fa.jn="oj-valid-drop";b.fa.bG="oj-invalid-drop";b.fa.Bqa="oj-drop";b.fa.zqa="oj-tree-drop-marker";b.fa.g8="oj-tree-drop-marker-line";b.fa.c7="reorder";b.fa.T6="drag";b.fa.X6="drop";b.fa.MQ="node";b.fa.LQ="dataTypes";b.fa.W6="dragStart";b.fa.U6="drag";b.fa.V6="dragEnd";b.fa.Y6="dragEnter";b.fa.a7="dragOver";b.fa.Z6="dragLeave";b.fa.b7="drop";b.fa.RF="_ojtree";b.fa.SF="_ojtreereorder";
(function(){function d(a){r.push(a);f(a.r_).keydown(c)}function c(a){var c="";b.v.Io(a)?c+="ctrl+":a.shiftKey&&(c+="shift+");var d=a.which;switch(d){case 32:c+="space";break;case 37:c+="left";break;case 38:c+="up";break;case 39:c+="right";break;case 40:c+="down";break;case 46:c+="del";break;case 33:c+="pgup";break;case 34:c+="pgdn";break;case 35:c+="end";break;case 36:c+="home";break;case 56:c="*";break;case 113:case 121:c+="f"+(1-(112-d))}if(0===c.length||"shift+"==c||"ctrl+"==c)return!0;var e=null;
f.each(r,function(b,d){if(d.Qx.i.ui.Dj)return d.Qx.i.ui.Cr=!1,"shift+f10"==c?d.Qx.i.menu.CD=d.Qx.i.ui.Db:d.gX[c]&&(a.preventDefault(),e=d.gX[c].call(d.Qx,a)),!1});if(null!=e)return e}function e(a){f.each(r,function(b){if(r[b].r_===a)return f(a).off("keydown"),r[b]=null,r.splice(b,1),!1})}function g(a){var b=!0,c;for(c in a)if(a.hasOwnProperty(c)){b=!1;break}return b}function h(a){var b=!1,c=!0;a.IE&&(a.title&&(b=f("style[id\x3d'"+a.title+"-stylesheet']")[0]),b?c=!1:(b=document.createElement("style"),
b.setAttribute("type","text/css"),a.title&&b.setAttribute("id",a.title+"-stylesheet")),b.styleSheet?c?(document.getElementsByTagName("head")[0].appendChild(b),b.styleSheet.cssText=a.IE):b.styleSheet.cssText=b.styleSheet.cssText+" "+a.IE:(b.appendChild(document.createTextNode(a.IE)),document.getElementsByTagName("head")[0].appendChild(b)))}var k={cut:"ojtreecut",copy:"ojtreecopy",paste:"ojtreepaste",remove:"ojtreeremove",rename:"ojtreerename"},l={cut:"labelCut",copy:"labelCopy",paste:"labelPaste",
remove:"labelRemove",rename:"labelRename"},m,n,p;f(function(){/msie/.test(navigator.userAgent.toLowerCase())?(n=f('\x3ctextarea cols\x3d"10" rows\x3d"2"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),p=f('\x3ctextarea cols\x3d"10" rows\x3d"2" style\x3d"overflow: hidden;"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),m=n.width()-p.width(),n.add(p).remove()):(n=f("\x3cdiv /\x3e").css({width:100,height:100,overflow:"auto",position:"absolute",
top:-1E3,left:0}).prependTo("body").append("\x3cdiv /\x3e").find("div").css({width:"100%",height:200}),m=100-n.width(),n.parent().remove())});var r=[],s=-1;b.ya("oj.ojTree",f.oj.baseComponent,{widgetEventPrefix:"oj",defaultElement:"\x3cdiv\x3e",options:{dnd:{reorder:"disable"},expandParents:!1,initExpanded:null,soa:[],selection:[],selectionMode:"single",selectedParentCollapse:!1,selectedParentExpand:!0,selectPrevOnDelete:!1,data:null,emptyText:null,icons:!0,types:null,before:null,collapse:null,create:null,
collapseAll:null,cut:null,dehover:null,remove:null,destroy:null,expand:null,expandAll:null,hover:null,loaded:null,move:null,optionChange:null,paste:null,refresh:null,rename:null},collapse:function(b,c){var d=(c=c||!1)?0:this.NG;b=this.sa(b);if(!b.length||-1===b||!b.hasClass(a.ji)||this.i.Z.locked||b.hasClass(a.ad))return!1;var e=this.ub({obj:b,func:"collapse"},"before");if("boolean"!=typeof e||e)b.removeClass(a.ji).addClass(a.mf).attr("aria-expanded","false"),f(b.children()[0]).removeClass(a.$i).addClass("oj-default"),
!c&&d?this.Kq(b,!0):this.bM(f(b.children("UL")[0]),b)},Kq:function(a,b){var c,d,e;c=f(a.children("ul"));this.bY?c[0].addEventListener("webkitTransitionEnd",this.FC):c[0].addEventListener("transitionend",this.FC);b?(d=c[0].offsetHeight,e=0):(d=0,e=this.Wca(c[0]));c.css("max-height",d+"px");c.css("overflow","hidden");b||(c[0].style.display="block");setTimeout(function(){c.addClass("oj-tree-transition");c.css("max-height",e+"px")},20)},Wca:function(a){var b,c,d,e,g=f("\x3cdiv style\x3d'position: absolute'\x3e");
b=a.parentNode;c=a.nextSibling;b.removeChild(a);e=a.style.display;a.style.display="block";g.append(a);this.ua[0].appendChild(g[0]);d=a.offsetHeight||a.scrollHeight;a.style.display=e;this.ua[0].removeChild(g[0]);g[0].removeChild(a);c?b.insertBefore(a,c):b.appendChild(a);return d+10},$t:function(a){a=f(a.target);var b=a.closest("li");this.bY?a[0].removeEventListener("webkitTransitionEnd",this.FC):a[0].removeEventListener("transitionend",this.FC);a.removeClass("oj-tree-transition");this.bM(a,b)},bM:function(b,
c){c.hasClass(a.mf)?(b[0].style.display="none",b.css("max-height",""),this.ub({obj:c},"collapse"),this.after_close(c)):(b[0].style.display="block",b.css("max-height",""),this.ub({obj:c},"expand"))},collapseAll:function(b,c){var d=b?b:-1,e=this;if(!this.i.Z.locked&&((b=b?this.sa(b):this.ua)&&-1!==d&&(d=b),b&&-1!==d||(b=this.aa),!b.hasClass(a.ad))){var f;-1!==d&&this.isExpanded(b)&&(f=b[0]);var g=b.find("li.oj-expanded");g.length&&g.each(function(){e.collapse(this,!c)});f&&(this.collapse(f,!c),g.splice(0,
0,f));g.length&&this.ub({obj:g,targ:d},"collapseAll")}},expand:function(a,b){this.Xd(a,!1,b)},expanded:function(a,b){var c,d,e=this;if(a&&"array"===f.type(a)){if(this.i.Z.locked)return null;d=a.length;f.each(a,function(a,c){e.Xd(c,!1,b)});return null}a=this.aa.find("li.oj-expanded");d=a.length;c=[];for(var g=0;g<d;g++)c.push(a[g]);return f(c)},expandAll:function(a,b){this.lI(a,b)},toggleExpand:function(b,c){if((b=this.sa(b))&&b.length&&-1!==b&&!b.hasClass(a.ad)&&!this.i.Z.locked){if(b.hasClass(a.mf))return this.expand(b,
c);if(b.hasClass(a.ji))return this.collapse(b,c)}},deselect:function(a){var b=this.options.selection.slice(0);this.Ns(a);this.pw("selection",b,null,null)},deselectAll:function(a){if(!this.i.Z.locked){var b=this.options.selection.slice(0);this.SA(a);this.pw("selection",b,null,null)}},select:function(a){this.vj(a,!0)},toggleSelect:function(b){b=this.sa(b);if(!b.length||b.hasClass(a.ad)||this.i.Z.locked)return!1;this.isSelected(b)?this.deselect(b):this.vj(b,!0);return!0},isCollapsed:function(b){return(b=
this.sa(b))&&-1!==b&&b.hasClass(a.mf)},isExpanded:function(b){return(b=this.sa(b))&&-1!==b&&b.hasClass(a.ji)},isLeaf:function(a){return this.hK(a)},isSelected:function(a){a=this.sa(a);var b=!1;a&&a.length&&this.i.ui.selected&&(b=0<=this.i.ui.selected.index(a));return b},create:function(a,b,c){var d,e,g;e=f.isArray(c);if(!e||1==c.length)return d=this.ew(a,b,e?c[0]:c),this.Fn().WA(d),d;e=[];if("before"!=b)for(g=c.length-1;0<=g;g--)d=this.ew(a,b,c[g]),e.unshift(d[0]),this.Fn().WA(d);else for(g=0;g<c.length;g++)d=
this.ew(a,b,c[g]),e.push(d[0]),this.Fn().WA(d);return f(e)},remove:function(b){b=this.sa(b);if(!b.length||b.hasClass(a.ad)||this.i.Z.locked)return!1;var c=this.ub({obj:b,func:"remove"},"before");if("boolean"==typeof c&&!c)return!1;this.Ip();var c=this.kj(b),d=f([]),e=this,g=this.Jl(b);b.each(function(){d=d.add(e.Jl(this))});b=b.detach();-1!==c&&0===c.find("\x3e ul \x3e li").length&&c.removeClass("oj-expanded oj-collapsed").addClass("oj-tree-leaf").removeAttr("aria-expanded");this.Qg(c);this.ub({obj:b,
prev:g,parent:c},"remove");return b},getText:function(a){a=this.sa(a);if(!a.length)return!1;a=a.children("a:eq(0)");a=a.find("span:eq(0)");return a[0].textContent},rename:function(a,b){this.TZ(a,b)},hover:function(b){if(!this.i.menu.CD&&(b=this.sa(b),b.length&&!b.hasClass(a.ad)&&!this.i.Z.locked&&!b.hasClass(a.xp))){var c=this.ub({obj:b,func:"hover"},"before");if("boolean"!=typeof c||c)b.hasClass(a.xp)||this.dehover(),this.i.ui.Db=b.children("a").addClass(a.xp).parent(),this.aa.attr("aria-activedescendant",
this.i.ui.Db.attr("id")),this.jV(b),this.ub({obj:b},"hover")}},dehover:function(){if(!this.i.menu.CD){var b=this.i.ui.Db,c;if(b&&b.length&&!b.hasClass(a.ad)&&!this.i.Z.locked){c=b.find("a.oj-hover");if(!c.length&&(c=this.aa.find("a.oj-hover"),!c.length))return;c.removeClass(a.xp).parent();this.aa.removeAttr("aria-activedescendant");this.i.ui.Db=null;void 0!=b.attr("id")&&this.ub({obj:b},"dehover")}}},getPath:function(a,b){var c=[],d=this;a=this.sa(a);if(-1===a||!a||!a.length)return!1;a.parentsUntil(".oj-tree",
"li").each(function(){c.push(b?this.id:d.getText(this))});c.reverse();c.push(b?a.attr("id"):this.getText(a));return c},getRoot:function(){return this.ua.children("ul:eq(0)")},refresh:function(a){this._super();this.i.Z.locked||this.Ld(a?a:-1)},move:function(a,b,c,d){this.hx(a,b,c,d)},getType:function(a){return this.uJ(a)},setType:function(a,b){return this.Kka(a,b)},getNodeBySubId:function(a){return a?this.zia(a):this.element?this.element[0]:null},getSubIdByNode:function(a){return this.Zda(a)},getContextByNode:function(a){var b,
c;a=this.sa(null==a||void 0==a?0:a);b=-1!=a&&0<a.length;c=-1==a;return b||c?{subId:b?"oj-tree-node":"oj-tree",node:b?a:!1,leaf:b?this.hK(a):!1}:null},getParent:function(a){return(a=this.kj(a))&&0<a.length?a:null},getPrevSibling:function(a){return(a=this.Jl(a,!0))&&0<a.length?a:null},getNextSibling:function(a){return(a=this.gq(a,!0))&&0<a.length?a:null},getChildren:function(b){return(b=(b=this.Hca(b?b:-1))&&b.length?b.not("."+a.ms):b)&&0<b.length?b:null},scrollIntoView:function(a,b,c){a?(a=a.node,
a=this.sa(a)):a=-1;-1==a&&(a=this.ua.find("\x3e ul \x3e li:first-child"));if(a&&a.length)return b="top"==b,c&&(this.aa.focus(),this.hover(a)),a[0].scrollIntoView(b),this},_ComponentCreate:function(){this._super();this.Pfa=this.Lha();this.Ps=this.element.attr("id");void 0===this.Ps&&(this.Ps="oj-tree-"+this.Ug(),this.element.attr("id",this.Ps));this.Ps="#"+this.Ps;this.ua=this.element;this.aa=null;this.i={};this.z0=null;this.lC="rtl"===this.ac();this.xt=b.v.Od();this.dga();if(this.NG=this.zca())this.bY=
b.Ma.oy().browser===b.Ma.gl.ZP,this.FC=f.proxy(this.$t,this);this.Ih()},_destroy:function(){this.aaa();this.i.html.Cu&&(this.ua.append(this.i.html.Cu),this.i.html.qE.remove(),this.i.html.qE=!1,this.i.html.JE=!1);this.i.Oa.type=0;this._super()},_setOption:function(a,b,c){var d;if("selection"===a)b="string"==typeof b?[b]:b&&b.length?b:[],this.i.Z.Br=!0,this.wfa(b),this.i.Z.Br=!1,b=this.iJ();else if("selectionMode"===a)"none"===b?d=0:"single"===b?d=1:"multiple"===b?d=-1:(d=0,b="none"),d!=this.i.Z.Dm&&
(this.i.Z.Dm=d);else if("icons"===a)"boolean"==f.type(b)&&b!=this.i.Ab.icons&&((this.i.Ab.icons=b)?this.FL():this.TJ());else if("contextMenu"===a)this.Op(),b&&this.On(b);else if("disabled"===a)this.Eea(b);else{if("data"===a){this._super(a,b,c);this.wX();this.xX();this.yX();this.sY();return}if("dnd"===a){this._super(a,b,c);this.Fn().Zna();return}"emptyText"==a&&(b=this.aB(b))}this._super(a,b,c)},rv:function(a,b,c){return"selection"===a?this.JT(b,c):this._superApply(arguments)},JT:function(a,b){var c,
d,e,g,h,k=!1,l=!1;g=a&&a.length?a.length:0;h=b&&b.length?b.length:0;if(g!==h)k=!0;else if(0==g&&0===h)k=!1;else for(c=0;c<g;c++){e=f(a[c]).attr("id");l=!1;for(d=0;d<h;d++)if(e==f(b[d]).attr("id")){l=!0;break}if(!l){k=!0;break}}return!k},aaa:function(){this.Gv&&(this.Gv.eaa(),this.Gv=null);var a=this.Ug();this.ua.unbind(".oj-tree").undelegate(".oj-tree").removeData("oj-tree-instance-id").find("[class^\x3d'oj-tree']").addBack().attr("class",function(){return this.className.replace(/oj-tree[^ ]*|$/ig,
"")});var b=this.ua.attr("class"),b=b.trim();0===b.length&&this.ua.removeAttr("class");e(this.aa);f(document).unbind(".oj-tree-"+a).undelegate(".oj-tree-"+a);this.aa.remove();this.aa=null},sa:function(a,b){if("undefined"===typeof a||null===a)return b?this.i.ui.selected:this.i.ui.Lb;var c=f(a,this.ua);if(c.is(".oj-tree")||-1===a)return-1;c=c.closest("li",this.ua);return c.length?c:!1},Jl:function(b,c){b=this.sa(b);if(-1===b)return this.ua.find("\x3e ul \x3e li:last-child");if(!b.length)return!1;if(c)return 0<
b.prevAll("li").length?b.prevAll("li:eq(0)"):!1;if(b.prev("li").length){for(b=b.prev("li").eq(0);b.hasClass(a.ji);)b=b.children("ul:eq(0)").children("li:last");return b}var d=b.parentsUntil(".oj-tree","li:eq(0)");return d.length?d:!1},gq:function(b,c){b=this.sa(b);return-1===b?this.ua.find("\x3e ul \x3e li:first-child"):b.length?c?0<b.nextAll("li").size()?b.nextAll("li:eq(0)"):!1:b.hasClass(a.ji)?b.find("li:eq(0)"):0<b.nextAll("li").size()?b.nextAll("li:eq(0)"):b.parentsUntil(".oj-tree","li").next("li").eq(0):
!1},kj:function(a){a=this.sa(a);if(-1==a||!a.length)return!1;a=a.parentsUntil(".oj-tree","li:eq(0)");return a.length?a:-1},Hca:function(a){a=this.sa(a);return-1===a?this.ua.children("ul:eq(0)").children("li"):a.length?a.children("ul:eq(0)").children("li"):!1},hK:function(a){return(a=this.sa(a))&&-1!==a&&a.hasClass("oj-tree-leaf")},Bda:function(a){a=this.aa.find(a);var b=!1;a&&a.length&&0<a.length&&f(a).is("li")&&(b=a);return b},Kia:function(a,c){var d=a.parents("div").eq(0);(d=b.Components.sg(d))&&
c&&d("getCI",c);return this},getCI:function(a){a.$k=this},Y9:function(a,b){void 0!=a&&void 0!=b&&f.each(b,function(b,c){void 0==a[b]&&(a[b]=c)})},Eea:function(b){var c;"undefined"!==typeof b&&((c=this.aa.hasClass(a.ad))||(c=!1),c!=b&&(b?(this.aa.addClass(a.ad),this.aa.prop("disabled",!0)):(this.aa.removeClass(a.ad),this.aa.prop("disabled",!1)),this.Dla(b)))},Dla:function(b){b?(this.i.Z.locked=!0,this.i.ui.opacity=this.ua.children("ul").css("opacity"),this.aa.addClass(a.ad).css("opacity","0.9")):(this.i.Z.locked=
!1,this.aa.removeClass(a.ad).css("opacity",this.i.ui.opacity))},dra:function(){return this.i.Z.locked},wfa:function(a){var b=a.slice(0),c=[],d=this,e,g,h,k;f.grep(b,function(a,f){if(e=d.Bda(a))c.push(e),b[f]=e[0];else return!1;return!0});a=this.iJ();f.each(a,function(a,b){k=c.length;g=f(b).attr("id");h=!1;for(a=0;a<k;a++)if(g==c[a].attr("id")){h=!0;break}h||d.Ns(b)});this.Fka(c,null)},px:function(a,b,c,d,e){var f={};b=-1!==b&&b?this.sa(b):-1;this.Kia(a,f);f.Uo=this;f.rb=f.$k.sa(a);f.va=b;f.ym="undefined"===
typeof c||!1===c?"last":c;if(!e&&this.i.Z.Ag.rb&&this.i.Z.Ag.rb[0]===f.rb[0]&&this.i.Z.Ag.va[0]===f.va[0]&&this.i.Z.Ag.ym===f.ym)d&&d.call(this,this.i.Z.Ag);else{if(-1!==f.va&&f.va){if(!/^(before|after)$/.test(f.ym)&&!this.Ol(f.va))return this.Pl(f.va,function(){this.px(a,b,c,d,!0)});switch(f.ym){case "before":f.yj=f.va.index();f.Xq=f.Uo.kj(f.va);break;case "after":f.yj=f.va.index()+1;f.Xq=f.Uo.kj(f.va);break;case "inside":case "first":f.yj=0;f.Xq=f.va;break;case "last":f.yj=f.va.find(" \x3e ul \x3e li").length;
f.Xq=f.va;break;default:f.yj=f.ym,f.Xq=f.va}}else switch(f.Xq=-1,f.ym){case "first":case "before":case "inside":f.yj=0;break;case "after":case "last":f.yj=f.Uo.ua.find(" \x3e ul \x3e li").length;break;default:f.yj=f.ym}f.um=-1==f.Xq?f.Uo.ua:f.Xq;f.wm=f.$k.kj(f.rb);f.ora=f.rb.index();-1===f.wm&&(f.wm=f.$k?f.$k.ua:this.ua);!/^(before|after)$/.test(f.ym)&&f.wm&&f.um&&f.wm[0]===f.um[0]&&f.rb.index()<f.yj&&f.yj++;f.sO=f.um.find(" \x3e ul \x3e li:nth-child("+(f.yj+1)+")");this.i.Z.Ag=f;d&&d.call(this,this.i.Z.Ag,
"prepare_move")}},EA:function(){var a=this.i.Z.Ag,b=!0,c;c=-1===a.va?this.ua:a.va;if(!a||!a.rb||a.sO[0]===a.rb[0]||!a.va)return!1;if(!a.OD){if(a.wm&&a.um&&a.wm[0]===a.um[0]&&a.yj-1===a.rb.index())return!1;a.rb.each(function(){if(-1!==c.parentsUntil(".oj-tree","li").addBack().index(this))return b=!1})}return b},TZ:function(a,b){var c;a=this.sa(a);this.Ip();c=this.getText(a);if(a&&a.length){var d=this.ub({obj:a,func:"rename",title:b,prevTitle:c},"before");if("boolean"==typeof d&&!d)return}a&&a.length&&
this.BL.apply(this,Array.prototype.slice.call(arguments))&&this.ub({obj:a,title:b,prevTitle:c},"rename")},hx:function(b,c,d,e,g,h){g||(b=this.sa(b));if(!(b.hasClass&&b.hasClass(a.ad)||this.i.Z.locked)){if(!g)return this.px(b,c,d,function(a){a.$k===a.Uo||a.OD||a.$k.deselect(a.rb);this.hx(a,!1,!1,e,!0,h)});e&&(this.i.Z.Ag.OD=!0);if(!h&&!this.EA())return!1;this.Ip();c=!1;e?(c=b.rb.clone(!0),c.find("*[id]").addBack().each(function(){this.id&&(this.id="copy_"+this.id)})):c=b.rb;b.sO.length?b.sO.before(c):
(b.um.children("ul").length||f("\x3cul /\x3e").appendTo(b.um),b.um.children("ul:eq(0)").append(c));try{b.$k.Qg(b.wm),b.Uo.Qg(b.um),b.wm.find("\x3e ul \x3e li").length||b.wm.removeClass("oj-expanded oj-collapsed").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove()}catch(k){}e&&(this.i.Z.Ag.OD=!0,this.i.Z.Ag.qO=c);c=f.extend(!0,{},this.i.Z.Ag);c.obj=b.rb;this.ub(c,"move");return this.i.Z.Ag}},Oqa:function(){return this.i.Bc.Ag},uJ:function(a){var b=null;this.options.types&&
(b=this.sa(a));return b&&b.length?b.attr(this.options.types.attr)||"default":!1},Kka:function(a,b){var c=this.options.types,d,e=!1;a=this.sa(a);c&&a&&-1!=a&&a.length&&b&&(d=c.attr)&&c[b]&&(a.attr(d,b),a.addClass("oj-tree-type"),e=!0);return e},M$:function(a,b){b=this.sa(b);var c=!1,d=this.uJ(b),e=this.hq().types,g=!1;if(-1===b)if(e[a])c=e[a];else return;else{if(!1===d)return;(g=this.i.types.Cc.useData?b.data("oj-tree"):!1)&&g.types&&"undefined"!==typeof g.types[a]?c=g.types[a]:e.types[d]&&"undefined"!==
typeof e.types[d][a]?c=e.types[d][a]:e.types["default"]&&"undefined"!==typeof e.types["default"][a]&&(c=e.types["default"][a])}f.isFunction(c)&&(c=c.call(this,b));return c},Qg:function(c){var d,e,g,h=this.Fn(),k=b.fa;h.t3()&&(d=k.aG,e="draggable",g=!0);h.Boa()&&(d+=" "+k.jn);c=c&&-1!=c?f(c):this.aa;c=c.is("li")?c.find("li").addBack():c.find("li");c.removeClass("oj-tree-last").addClass("oj-tree-node").addClass(d).attr(e,g).filter("li:last-child").addClass("oj-tree-last").end().filter(":has(li)").not(".oj-expanded").removeClass("oj-tree-leaf").addClass(a.mf).attr("aria-expanded",
"false");c.not(".oj-expanded, .oj-collapsed").addClass("oj-tree-leaf").children("ul").remove();var l=this.options.types?this.options.types.attr:!1;c.find("li");var m,n;f.each(c,function(){n=f(this);m=n.find("\x3e ins");1<m.length&&(m=f(m[0]));n.hasClass("oj-tree-leaf")?(m.removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),m.addClass("oj-tree-icon")):(m.addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),m.removeClass("oj-tree-node-icon"));
l&&n.attr(l)&&n.addClass("oj-tree-type")})},ew:function(b,c,d,e,g){b=b||-1;b=this.sa(b);if(-1!==b&&!b.length)return null;var h;c="undefined"===typeof c?"last":c;if(!g&&!this.Ol(b))return this.Pl(b,function(){this.ew(b,c,d,e,!0)}),null;this.Ip();d=this.Sl(d);if(!d)return null;d=d.children();g=f(d[0]);-1===b&&(b=this.ua,"before"===c&&(c="first"),"after"===c&&(c="last"));switch(c){case "before":b.before(g);h=this.kj(b);break;case "after":b.after(g);h=this.kj(b);break;case "inside":case "first":b.children("ul").length||
b.append("\x3cul /\x3e");b.children("ul").prepend(g);h=b;break;case "last":b.children("ul").length||b.append("\x3cul /\x3e");b.children("ul").append(g);h=b;break;default:b.children("ul").length||b.append("\x3cul /\x3e"),c||(c=0),h=b.children("ul").children("li").eq(c),h.length?h.before(g):b.children("ul").append(g),h=b}if(-1===h||h.get(0)===this.ua.get(0))h=-1;this.Qg(h);this.ub({obj:g,parent:h},"create");e&&e.call(this,g);1<this.aa[0].childNodes.length&&this.aa.find("."+a.ms).remove();return g},
Xd:function(b,c,d){b=this.sa(b);if(!b||!b.length)return!1;d=d||!1;if(!b.hasClass(a.ad)&&!this.i.Z.locked){if(!b.hasClass(a.mf))return c&&c.call(),!1;var e=this.ub({obj:b,func:"expand"},"before");if("boolean"!=typeof e||e){var e=d?0:this.NG,g=this;this.Ol(b)?(this.options.expandParents&&b.parentsUntil(".oj-tree",".oj-collapsed").each(function(){g.Xd(this,!1,!0)}),b.removeClass(a.mf).addClass(a.ji).attr("aria-expanded","true").children("a").removeClass("oj-tree-loading"),f(b.children()[0]).removeClass(a.$i).addClass("oj-default"),
!d&&e?this.Kq(b,!1):this.bM(f(b.children("UL")[0]),b),c&&c.call()):(b.children("a").addClass("oj-tree-loading"),this.Pl(b,function(){g.Xd(b,c,d)},c))}}},lI:function(a,b,c){var d=a?a:-1;(a=a?this.sa(a):-1)&&-1!==a?d=a:a=this.aa;c?a=a.find("li.oj-collapsed"):(c=a,a=a.is(".oj-collapsed")?a.find("li.oj-collapsed").addBack():a.find("li.oj-collapsed"));var e=this;a.each(function(){var a=this;e.Ol(this)?e.Xd(this,!1,!b):e.expand(this,function(){e.lI(a,b,c)},!b)});0===c.find("li.oj-collapsed").length&&this.ub({obj:a,
targ:d},"expandAll")},vj:function(c,d,e){var f=this.i.Z,g=this.i.ui,h=f.Dm;if(0==h)return!1;c=this.sa(c);if(-1==c||!c||!c.length||c.hasClass(a.ad)||f.locked)return!1;e&&"touchend"==e.type||(g.Cr=!1);var k=this.isSelected(c);if(!k){var l=this.ub({obj:c,func:"select"},"before");if("boolean"==typeof l&&!l)return!1}var l=this.options.selection.slice(0),m=this.options,n=g.Cc.selectMultipleModifier,p=g.Cc.selectRangeModifier,r=g.Cc.disableSelectingChildren,n="on"==n||!1!==n&&e&&b.v.Io(e),p=!1!==p&&e&&e[p+
"Key"]&&g.Lb&&this.i.ui.Lb[0]!==c[0]&&g.Lb.parent()[0]===c.parent()[0],s=!0,z=this;if(d){if(r&&n&&(c.parentsUntil(".oj-tree","li").children("a.oj-selected").length||c.children("ul").find("a.oj-selected:eq(0)").length))return!1;s=!1;switch(!0){case p:g.Lb.addClass("oj-tree-last-selected");c=c[c.index()<g.Lb.index()?"nextUntil":"prevUntil"](".oj-tree-last-selected").addBack();-1==h||c.length<h?(g.Lb.removeClass("oj-tree-last-selected"),g.selected.each(function(){this!==g.Lb[0]&&z.Ns(this)}),k=!1,s=
!0):s=!1;break;case g.Cr&&-1==h:g.Cr=!1;this.toggleSelect(c);s=!1;break;case k&&!n:if(!e)break;this.SA();g.PO||(k=!1);s=!0;break;case !k&&!n:e?g.selected&&1==g.selected.length?this.Ns(g.selected):this.SA(g.selected):1===h?this.Ns(g.selected):1<h&&this.SA();s=!0;break;case k&&n:this.deselect(c);break;case !k&&n:if(-1==h||g.selected.length+1<=h)s=!0}}d=!1;s&&!k&&(p||(g.Lb=c),c.children("a").addClass(a.$i),c.attr("aria-selected","true"),d=!0,m.selectedParentExpand&&c.parents(".oj-collapsed").each(function(){z.Xd(this,
!1,!0)}),g.selected=g.selected.add(c),this.jV(c.eq(0)),f.Br||this.pw("selection",l,null,e));return d},Ns:function(b){b=this.sa(b);if(!b.length)return!1;b.hasClass(a.ad)||this.i.Z.locked||!this.isSelected(b)||(b.children("a").removeClass(a.$i),b.removeAttr("aria-selected"),this.i.ui.selected=this.i.ui.selected.not(b),this.i.ui.Lb&&this.i.ui.Lb.length&&this.i.ui.Lb.get(0)===b.get(0)&&(this.i.ui.Lb=this.i.ui.selected.eq(0)))},SA:function(a){if(!this.i.Z.locked&&(a=a?f(a).find("a.oj-selected").parent():
this.ua.find("a.oj-selected").parent(),a.not(".oj-disabled"),0!==a.length)){var b=this;f.each(a,function(){b.Ns(this)})}},Fka:function(a,b){if(this.i.Z.locked)return null;if(a&&0<a.length){var c=this;f.each(a,function(a,d){d&&c.vj(d,!0,b)})}},$W:function(a){a.preventDefault();a.currentTarget.blur();f(a.currentTarget).hasClass("oj-tree-loading")||(this.eo(),this.vj(a.currentTarget,!0,a)&&this.aa.focus());this.i.ui.Cr=!1},EU:function(b,c){b=f(b);if(!b.hasClass(a.ad)&&!this.i.Z.locked){var d=b.parent(),
e=d.hasClass(a.mf);if(d.hasClass(a.ji)||e)c?(b.addClass(a.xp),b.removeClass("oj-default"),b.removeClass(a.$i)):(b.removeClass(a.xp),b.addClass("oj-default"))}},Ld:function(a){this.CZ(a)},CZ:function(a){var b=a?a:-1,c=this;this.Wja();a||(a=-1);(a=this.sa(a))?b=a:a=-1;-1!==a?a.children("UL").remove():(this.aa.empty(),this.cZ());this.Pl(a,function(){c.ub({obj:b},"refresh");c.JC()})},ZK:function(a){this.saveSelected();this.CZ(a)},after_close:function(a){this.ub({obj:a},"after_close",!0)},Dja:function(){var a=
this;this.i.Z.Cg.length&&f.each(this.i.Z.Cg,function(b,c){a.Xd(c,!1,!0)});this.ub({},"reopen",!0)},iJ:function(a){var b,c,d;a=a?f(a).find("a.oj-selected").parent():this.i.ui.selected;b=[];d=a.length;for(c=0;c<d;c++)b.push(a[c]);return b},BL:function(a,b){a=this.sa(a);if(!a.length)return!1;a=a.children("a:eq(0)");a=a.find("span:eq(0)");this.ub({obj:a,name:b},"set_text",!0);return a[0].textContent=b},sY:function(){0!==this.i.Oa.type&&-1!==this.i.Oa.type?this.Pl(-1,function(){this.uY();this.JC()}):(this.Z9(),
this.uY())},Pl:function(a){this.ub({obj:a},"load_node",!0)},Ol:function(){return!0},hha:function(a,b,c){var d=this;this.kha(a,function(){d.ub({obj:d.sa(a)},"load_node",!0);b.call(this)},c)},Rga:function(a){a=this.sa(a);return-1===a||!a||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},Uia:function(a){(a=this.sa(a))&&-1!==a&&a.removeData("oj-tree-children");return this.ZK(a)},jha:function(a,b,c){var d=this;this.gha(a,function(){d.ub({obj:d.sa(a)},"load_node",!0);b.call(this)},
c)},Tga:function(a){var b=this.options.data;a=this.sa(a);return-1==a||!a||!b.ajax&&!this.i.Oa.zO&&!f.isFunction(b.data)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},iha:function(a,b,c){var d=this;this.fha(a,function(){d.ub({obj:d.sa(a)},"load_node",!0);b.call(this)},c)},Sga:function(a){var b=this.options.data,c=null,d=null;b&&(c=b.data||null,d=b.ajax||null);a=this.sa(a);return-1==a||!a||!d&&!f.isFunction(c)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").size()},
reselect:function(){var a=this,b=this.i.ui.bz,b=f.map(f.makeArray(b),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});f.each(b,function(b,c){c&&"#"!==c&&a.select(c)});this.i.ui.selected=this.i.ui.selected.filter(function(){return this.parentNode});this.ub(null,"reselect",!0)},saveSelected:function(){var a=this.i.ui;a.bz=[];a.selected.each(function(){this.id&&a.bz.push("#"+this.id.toString().replace(/^#/,
"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))});this.ub(a.bz,"savedselected",!0)},rollback:function(a){a&&f.isArray(a)},get_rollback:function(){this.ub(null,"get_rollback",!0);return{Ara:this.Ug(),lh:this.ua.children("ul").clone(!0),pra:this.data}},kha:function(a,b){var c=this.fR(a&&-1!=a?a[0].id:a?a:-1,a);if(c.success&&c.My){var d=!a||-1===a,e=this.options.data;if(e.data&&!e.ajax||e.data&&e.ajax&&d)d&&((c=this.Sl(c.My,a))?(this.aa.empty().append(c.children()),
this.Qg()):this.i.Oa.lg&&this.aa.empty()),b&&b.call(this);else if(!e.data&&e.ajax||e.data&&e.ajax&&!d)(c=this.Sl(c.My,a))?(d?(d=this.aa,d.empty().append(c.children()),d.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.i.Z.Dm&&d.attr("aria-multiselectable",!0)):(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")),this.Qg(a),b&&b.call(this)):d?this.i.Oa.lg&&(this.aa.empty(),b&&b.call(this)):(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading"),e.correct_state&&(this.Vp(a),b&&b.call(this)))}},fR:function(a,b){var c=[],d=this.z0,e,g={},h={success:!1,My:null};-1==a&&(a=null,g.start=0);e=d.Ye(a);0<e&&(g.count=e,d.Ff(a,g,{success:f.proxy(function(a){for(var e=a.R(),f,g=0;g<e;g++){b={};(f=a.getData(g))&&(b.attr=f);b.title=a.Mf[g].title;f.Era&&(b.metadata=a.Mf[g].metadata);var k=b.attr.id;f=d.Ye(k);0<f&&(f=this.fR(k,b),b.children=f.My);c.push(b)}h.success=!0;h.My=c},this),error:function(){h.success=!1}}));return h},
Via:function(b){b=this.sa(b);if(!this.i.Z.locked){var c=!b||-1!==b||!b.length;if(c||!b.hasClass(a.ad)){var d=this.options.data.json;!c&&this.i.Oa.Iu&&(f.isFunction(d.data)||d.ajax)&&b.removeData("oj-tree-children");return this.ZK(b)}}},gha:function(a,b,c){function d(){}function e(){}var g=this.hq().data,h=g&&g.data||null,k=g&&g.ajax||null;!g||h||k||(h=g);if((a=this.sa(a))&&-1!==a&&(this.i.Oa.zO||this.i.Oa.Iu)&&!a.is(".oj-expanded, .oj-tree-leaf")&&0===a.children("ul").children("li").length&&a.data("oj-tree-children")){if(g=
this.Sl(a.data("oj-tree-children"),a))a.append(g),this.i.Oa.Iu||a.removeData("oj-tree-children");this.Qg(a);b&&b.call(this)}else{if(a&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k:throw"ojTree - neither data nor ajax settings supplied.";case f.isFunction(h):h.call(this,a,f.proxy(function(d){(d=this.Sl(d,a))?(-1!==a&&a?(a.append(d).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):this.aa.empty().append(d.children()),
this.Qg(a),b&&b.call(this)):(-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.i.Oa.lg&&this.Vp(a)):this.i.Oa.lg&&this.aa.empty(),c&&c.call(this))},this));break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||((g=this.Sl(h,a))?(this.aa.empty().append(g.children()),this.Qg()):this.i.Oa.lg&&this.aa.empty());b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:e=function(b,d,e){var f=this.hq().data.ajax.error;f&&f.call(this,d,e,b);-1!=
a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.i.Oa.lg&&this.Vp(a)):("error"==d||"success"===d&&this.i.Oa.lg)&&this.aa.empty();c&&c.call(this)},d=function(c,d,g){var h=this.hq().data.ajax.success;h&&(c=h.call(this,c,d,g)||c);if("string"==typeof c){d=c.replace(/^[\s\n]+$/,"");try{d=f.parseJSON(d)}catch(k){d=null}if(!d)return e.call(this,g,"Bad JSON","")}(c=this.Sl(c,a))?(-1!==a&&a?(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading")):(g=this.aa,g.empty().append(c.children()),g.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.i.Z.Dm&&g.attr("aria-multiselectable",!0)),this.Qg(a),b&&b.call(this)):-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.i.Oa.lg&&(this.Vp(a),b&&b.call(this))):this.i.Oa.lg&&(this.aa.empty(),b&&b.call(this))},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.dataType||(g.ajax.dataType=
"json"),f.isFunction(g.ajax.url)&&(g.ajax.url=g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}}},Sl:function(b,c,d){var e=!1,g,h,k,l;if(!b)return e;this.i.Oa.Iu&&c&&-1!==c&&c.data("oj-tree-children",e);if("string"==typeof b)try{b=f.parseJSON(b)}catch(m){b=[]}if(f.isArray(b)){e=f("\x3cul\x3e");if(!b.length)return!1;h=0;for(k=b.length;h<k;h++)g=this.Sl(b[h],c,!0),g.length&&(e=e.append(g));e=e.children()}else{"string"==typeof b&&(b={data:b});
l="string"==typeof b.title?b.title:" ";e=f("\x3cli role\x3d'treeitem' /\x3e");b.attr&&(this.i.types.nu&&!b.attr.type&&(b.attr.type="oj-tree-deftype",e.addClass("oj-tree-type")),e.attr(b.attr));b.metadata&&e.data(b.metadata);b.children&&0===b.children.length&&e.addClass(a.mf);b.state&&"s"===b.state&&e.addClass(a.$i);b.data||(b.data={dummy:0});var n=!1,p;g=f("\x3ca tabindex\x3d'-1' /\x3e");f.each(b.data,function(a,c){f.isFunction(c)&&(c=c.call(this,b));"string"!=typeof c&&("attr"==a?g.attr(c):"style"==
a&&g.css(c),"language"==a&&g.addClass(c));n||(p=f("\x3cspan class\x3d'oj-tree-title'\x3e"),p[0].textContent=l,g.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-node-icon oj-component-icon'\x3e\x26#160;\x3c/ins\x3e",p),n=!0);!c.icon&&b.icon&&(c.icon=b.icon);c.icon&&(-1===c.icon.indexOf("/")?g.children("ins").addClass(c.icon):g.children("ins").css("background","url('"+c.icon+"') center center no-repeat"))});e.append(g);e.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default'\x3e\x26#160;\x3c/ins\x3e");
b.children&&(this.i.Oa.zO&&"expanded"!==b.state?e.addClass(a.mf).attr("aria-expanded","false").data("oj-tree-children",b.children):(this.i.Oa.Iu&&e.data("oj-tree-children",b.children),f.isArray(b.children)&&b.children.length&&(g=this.Sl(b.children,c,!0),g.length&&(c=f("\x3cul role\x3d'group' /\x3e"),c.append(g),e.append(c)))))}d||(d=f("\x3cul /\x3e"),d.append(e),e=d);return e},tS:function(a,b,c,d){var e=[],h=this.options,k=this,l,m,n,p,r,s,z,E;(a=this.sa(a))&&-1!==a||(a=this.ua.find("\x3e ul \x3e li"));
b=f.isArray(b)?b:["id","class"];!d&&h.types&&b.push(h.types.attr);c=f.isArray(c)?c:[];a.each(function(){p=f(this);l={};b.length&&(l.attr={});f.each(b,function(a,b){(m=p.attr(b))&&m.length&&m.replace(/oj-tree[^ ]*/ig,"").length&&(m=(" "+m).replace(/ oj-tree[^ ]*/ig,"").replace(/ oj-[^ ]*/ig,"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,""),m.length&&(l.attr[b]=m))});k.Fn().t3()&&k.isSelected(p)&&(l.state="s");n=p.data();g(n)||(l.metadata=n);r=p.children("a");m=null;r.each(function(){s=f(this);
c.length||s.children("ins").get(0).style.backgroundImage.length||s.children("ins").get(0).className&&s.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,"").length?(E=k.getText(s),f.each(c,function(a,b){z=(" "+(s.attr(b)||"")).replace(/ oj-tree[^ ]*/ig,"").replace(/ oj-[^ ]*/ig,"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,"");z.length&&(m||(m={attr:{}}),m.attr[b]=z)}),s.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,"").replace(/^\s+$/ig,"").length&&(z=s.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,
"").replace(/ oj-[^ ]*/ig,"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,""),z.length&&(m||(m={}),m.icon=z)),s.children("ins").get(0).style.backgroundImage.length&&(z=s.children("ins").get(0).style.backgroundImage.replace("url(","").replace(")",""),z.length&&(m||(m={}),m.icon=z))):E=k.getText(s);null!=m&&(l.data||(l.data=[]),1<r.length?l.data.push(m):l.data=m);l.title=E});p=p.find("\x3e ul \x3e li");p.length&&(l.children=k.tS(p,b,c,!0));e.push(l)});return e},Vp:function(a){a=this.sa(a);if(!a||
-1===a)return!1;a.removeClass("oj-collapsed oj-expanded").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove();a.find("ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").addClass("oj-tree-icon");this.ub({obj:a},"correct_state",!0)},uY:function(){this.ub(null,"loaded")},fha:function(a,b,c){function d(){}function e(){}var g=this.hq().data,h=g&&g.data||null,k=g&&g.ajax||null;if((a=this.sa(a))&&-1!==a){if(a.data("oj-tree-is-loading"))return;
a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k&&g&&"string"===typeof g:this.rY(g,a,b,c);break;case f.isFunction(h):h.call(this,a,f.proxy(function(d){this.rY(d,a,b,c)},this));break;case !h&&!k:a&&-1!=a||(this.aa.empty().append(this.i.html.GD).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon' \x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
this.aa.find("li").children("ins:first-child").addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),this.eC(this.aa),this.i.types.nu&&this.Mv(this.aa),this.Qg(),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem"),this.aa.find("a").attr("tabindex",-1));b&&b.call(this);break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||(g=f(h),g.is("ul")||(g=f("\x3cul /\x3e").append(g)),this.aa.empty().append(g.children()).find("li, a").filter(function(){return!this.firstChild||
!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.aa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.eC(this.aa),this.i.types.nu&&this.Mv(this.aa),
this.Qg(),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem"),this.aa.find("a").attr("tabindex","-1"));b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:a=this.sa(a),e=function(b,d,e){var f=this.hq().data.ajax.error;f&&f.call(this,b,d,e);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.i.Oa.lg&&this.Vp(a)):"success"===d&&this.i.Oa.lg&&this.aa.empty();c&&c.call(this)},d=function(c,
d,g){var h=this.hq().data.ajax.success;h&&(c=h.call(this,c,d,g)||c);if(""===c||c&&c.toString&&""===c.toString().replace(/^[\s\n]+$/,""))return e.call(this,g,d,"");if(c){c=f(c);c.is("ul")||(c=f("\x3cul /\x3e").append(c));-1!=a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),this.ija(a),a.append(c).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
a.removeData("oj-tree-is-loading"),a.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),c=a):(this.aa.empty().append(c.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
this.aa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),c=this.aa);this.Tea(c);this.eC(c);d=c.children("UL");if(1<=d.length){d=d.first().find("span.oj-tree-title");var k=this;f.each(d,function(){this.textContent=k.aB(this.textContent)})}this.i.types.nu&&c&&this.Mv(this.aa);this.Qg(a);b&&b.call(this)}else a&&-1!==a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading"),this.i.Oa.lg&&(this.Vp(a),b&&b.call(this))):this.i.Oa.lg&&(this.aa.empty(),b&&b.call(this)),this.aa.find("ul").attr("role","group"),this.aa.find("li").attr("role","treeitem")},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.ajax.dataType||(g.ajax.dataType="html"),f.isFunction(g.ajax.url)&&(g.ajax.url=g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}},Tea:function(b){b=b.find(b.is("ul")?"li ul":"ul").filter(function(){return!this.firstChild||
0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});f.each(b,function(){f(this).closest("li").addClass(a.mf)})},ija:function(a){a=a.find("ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});0<a.length&&a.remove()},rY:function(a,b,c){if(a&&""!==a&&a.toString&&""!==a.toString().replace(/^[\s\n]+$/,"")){a=f(a);a.is("ul")||(a=f("\x3cul /\x3e").append(a));-1!=b&&b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
b.append(a).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),b.removeData("oj-tree-is-loading"),a=b,this.Mv(this.Kra)):(this.aa.empty().append(a.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||
"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.aa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),a=this.aa,this.Mv(this.aa));a&&this.eC(a);a=
a.children("UL");if(1<=a.length){a=a.first().find("span.oj-tree-title");var d=this;f.each(a,function(){this.textContent=d.aB(this.textContent)})}this.Qg(b);c&&c.call(this)}else b&&-1!==b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.removeData("oj-tree-is-loading"),this.i.Oa.lg&&(this.Vp(b),c&&c.call(this))):this.i.Oa.lg&&(this.aa.empty(),c&&c.call(this))},eC:function(a){f.each(a.find("li a"),function(a,b){var c=b.innerHTML,c=c.replace("ins\x3e","ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e");
b.innerHTML=c+"\x3c/span\x3e"})},Mv:function(a){var b,c;this.i.types.nu&&(c=(b=this.options.types)?b.attr:this.i.types.Cc.attr,f.each(a.find("li"),function(a,b){b=f(b);b.attr(c)||b.attr(c,"oj-tree-deftype").addClass("oj-tree-type")}))},Wja:function(){var a=this;this.i.Z.Cg=[];this.aa.find("li.oj-expanded").each(function(){this.id&&a.i.Z.Cg.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))})},JC:function(a){var b=
this,c=!0,d=[],e=[],g,h;a||(this.i.Z.DO=!1,this.i.Z.epa=!0);this.Jga()&&(this.i.Z.Cg=[],this.aa.find("li.oj-collapsed").each(function(){h="#"+f(this).attr("id");b.isExpanded(h)||b.i.Z.Cg.push(h)}));this.i.Z.Cg=f.map(f.makeArray(this.i.Z.Cg),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.i.Z.bl=f.map(f.makeArray(this.i.Z.bl),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,
"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.i.Z.Cg.length&&(this.i.Z.bl=this.i.Z.bl.concat(this.i.Z.Cg),this.i.Z.bl=this.i.Z.bl.reduce(function(a,b){0>a.indexOf(b)&&a.push(b);return a},[]));this.i.Z.bl.length&&(f.each(this.i.Z.bl,function(a,c){if("#"==c)return!0;g=b.ua.find(c);g.length?b.isExpanded(c)||d.push(c):e.push(c)}),d.length&&(this.i.Z.bl=e,f.each(d,function(a,d){b.Ol(d)||(b.Pl(d,function(){b.JC(!0)},function(){b.JC(!0)}),c=!1)})));this.i.Z.Cg.length&&
f.each(this.i.Z.Cg,function(a,c){b.isExpanded(c)||b.Xd(c,!1,!0)});c&&(this.i.Z.DO&&clearTimeout(this.i.Z.DO),this.i.Z.DO=setTimeout(function(){b.ub({},"reload_nodes",!0)},50),this.i.Z.epa=!1,this.Dja())},setTheme:function(a,b){if(!a)return!1;b||(b=this.i.Ab.Px+a+"/style.css");-1==f.inArray(b,this.i.Ab.c5)&&(h({url:b}),this.i.Ab.c5.push(b));this.i.Ab.Mu!=a&&(this.ua.removeClass("oj-tree-"+this.i.Ab.Mu),this.i.Ab.Mu=a);this.ua.addClass("oj-tree-"+a);this.i.Ab.iy?this.V_():this.kX();this.i.Ab.icons?
this.FL():this.TJ()},Pga:function(){return null!=this.i.Ab},Uqa:function(){return this.i.Ab.Mu},isIcons:function(){return this.i.Ab.icons},FL:function(){this.i.Ab.icons=!0;this.ua.children("ul").removeClass("oj-tree-no-icons")},TJ:function(){this.i.Ab.icons=!1;this.ua.children("ul").addClass("oj-tree-no-icons")},toggleIcons:function(){},Wba:function(){this.i.keys.pna=!0},dga:function(){this.Wfa();this.Vfa();this.wX(!0);this.fga();this.Fn().o3();this.Ufa();this.hga();this.cga();this.xX();this.gga();
this.Fn().n3();this.On()},ub:function(a,b,c){if(b&&"string"===f.type(b)&&(!0!==this.i.Z.locked||"unlock"===b||"isLocked"===b||"lock"===b)){var d,e=Array.prototype.slice.call(arguments);d=this.ua;var g="before"===b,h=c?!1:!0;h||(b="_tree"+b);var k={};k.item=a?a.obj:void 0;k.inst=d;g?(d=a.func,k.func=d,k.args=e,"rename"===d&&(k.title=a.title,k.prevTitle=a.prevTitle)):h&&("move"==b?(k.position=a.ym,k.reference=a.va,k.data=a):"rename"==b?(k.title=a.title,k.prevTitle=a.prevTitle):"remove"==b?(k.parent=
a.parent,k.prev=a.prev):"delete"==b?(k.prev=a.prev,k.parent=a.parent):"expandAll"===b||"collapseAll"===b||"deselectAll"===b?k.targ=a.targ:"loaded"===b&&(k.item=-1));if(h){if(e=this._trigger(b,new f.Event("oj"+b),k),g)return"undefined"!=typeof e&&(e=e?!0:!1),e}else this.ua.trigger(b,k)}},pw:function(a,b,c,d){"selection"===a&&(null==c&&(c=this.iJ()),this.JT(b,c)||this.option(a,c,{_context:{originalEvent:d,Za:!0},changed:!0}))},Ip:function(){return this.get_rollback()},Ih:function(){this.lC&&this.ua.addClass("oj-tree-rtl").css("direction",
"rtl");this.ua.html("\x3cul role\x3d'tree' tabindex\x3d'0' class\x3d'oj-tree-list' style\x3d'outline:none'"+(-1===this.i.Z.Dm?" aria-multiselectable\x3d'true'":"")+"\x3e\x3cli class\x3d'oj-tree-last oj-tree-leaf'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e\x3ca class\x3d'oj-tree-loading' href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e"+this.lJ("stateLoading")+"\x3c/a\x3e\x3c/li\x3e\x3c/ul\x3e");this.aa=this.ua.children("ul:eq(0)");this.ua.data("oj-tree-instance-id",
this.Ug());this.i.Z.Jo=this.aa.find("li.oj-collapsed, li.oj-tree-leaf").eq(0).height()||18;this.xt&&this.ua.delegate(".oj-tree-list ins.oj-tree-disclosure-icon","touchend.ojtree",f.proxy(function(a){a.preventDefault();a=f(a.target);this.toggleExpand(a)},this));this.ua.delegate(".oj-tree-list ins.oj-tree-disclosure-icon","click.ojtree",f.proxy(function(a){a=f(a.target);this.toggleExpand(a)},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mousedown",f.proxy(function(b){this.i.ui.WM=!0;
f(b.target).removeClass("oj-default").removeClass(a.xp).addClass(a.$i)},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mouseup",f.proxy(function(b){f(b.target).removeClass(a.$i).addClass("oj-default")},this)).bind("mousedown.ojtree",f.proxy(function(){this.eo()},this)).bind("dblclick.ojtree",function(){var a;if(document.selection&&document.selection.empty)document.selection.empty();else if(window.getSelection){a=window.getSelection();try{a.removeAllRanges(),a.collapse(document.getElementsByTagName("body")[0],
0)}catch(b){}}});this.aa.focus(f.proxy(function(){if(this.i.ui.WM)this.i.ui.WM=!1;else{this.i.ui.Dj=!0;var a;this.i.ui.Hj?(this.i.ui.Db=this.i.ui.Hj,a=this.i.ui.Db):this.i.ui.Lb&&0<this.i.ui.Lb.length?(this.i.ui.Db=this.i.ui.Lb,a=this.i.ui.Db):a=this.aa.find("li:first");a&&(this.hover(a),this.i.ui.Hj=null,this.aa.find("a.oj-selected").removeClass("oj-tree-inactive"))}},this)).blur(f.proxy(function(){this.i.ui.Dj=!1;this.i.ui.Hj=this.i.ui.Db;this.i.ui.Hj&&this.dehover(this.i.ui.Db);this.aa.find("a.oj-selected").addClass("oj-tree-inactive")},
this));this.ub({},"init",!0);this.sY();this.i.menu.rh&&this.Ov();d({gX:this.zt,r_:this.aa,Qx:this});this.Wba()},Ufa:function(){this.i.Z.locked=!1;this.ua.addClass("oj-tree oj-tree-"+this.Ug());this.ua.css("outline","none");this.ua.css("MozUserSelect","none");this.ua.css("WebkitTouchCallout","none");this.ua.css("WebkitUserSelect","none");this.ua.css("WebkitTapHighlightColor","rgba(0,0,0,0)")},hga:function(){this.i.ui.selected=f();this.i.ui.Lb=!1;this.i.ui.Db=null;var b=this.options.selection;b&&"array"===
f.type(b)&&0<b.length&&(this.i.ui.bz=b,this.options.selection=[]);this.xt&&this.ua.delegate(".oj-tree-list a","touchend.ojtree",f.proxy(function(a){this.i.ui.Cr=!0;this.$W(a);f(a.currentTarget).hasClass("oj-tree-loading")||this.dehover()},this));this.ua.delegate(".oj-tree-list a","click.ojtree",f.proxy(function(a){this.i.ui.Cr=!1;this.$W(a)},this)).delegate(".oj-tree-list a","mouseenter.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.hover(a.target)},this)).delegate(".oj-tree-list a",
"mouseleave.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.dehover(a.target)},this)).delegate(".oj-tree-list .oj-tree-disclosure-icon","mouseenter.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.EU(a.target,!0)},this)).delegate(".oj-tree-list .oj-tree-disclosure-icon","mouseleave.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.EU(a.target,!1)},this)).bind("_treereopen",f.proxy(function(){this.reselect()},
this)).bind("_treeget_rollback",f.proxy(function(){this.dehover();this.saveSelected()},this)).bind("ojcollapse",f.proxy(function(a,b){var c=this.sa(b.item),d=c&&c.length?c.children("ul").find("a.oj-selected"):f();!1!==this.options.selectedParentCollapse&&d.length&&d.each(function(){this.deselect(this);"selectParent"===this.options.selectedParentCollapse&&this.select(c)})},this)).bind("ojremove",f.proxy(function(a,b){var c=this.options.selectPrevOnDelete,d=this.sa(b.item),d=d&&d.length?d.find("a.oj-selected"):
[],e=this,f;d.each(function(){e.deselect(this);e.i.ui.Hj&&(f=e.sa(this))&&e.i.ui.Hj.attr("id")==f.attr("id")&&(e.i.ui.Hj=null)});c&&d.length&&b.prev&&b.prev.each(function(){if(this.parentNode)return e.select(this),!1})},this)).bind("ojmove",f.proxy(function(b,c){var d=c.data,e=d.OD;e&&d.qO&&(d.qO.find("a.oj-selected").removeClass(a.$i),d.qO.removeAttr("aria-selected"));d.$k===d.Uo||e||(e=d.$k.i.ui,e.Hj&&(d.rb.attr("id")==e.Hj.attr("id")&&(e.Hj=null),e.Lb&&d.rb.attr("id")==e.Lb.attr("id")&&(e.Lb=null)))},
this))},xX:function(){this.ega();this.$fa();this.Zfa()},ega:function(){1===this.i.Oa.type&&(this.z0=this.options.data||null,this.Pl=this.hha,this.Ol=this.Rga,this.Ld=this.Uia)},$fa:function(){3===this.i.Oa.type&&(this.i.Oa.Iu&&this.ua.bind("_treeafter_close",function(a,b){b.item.children("ul").remove()}),this.Pl=this.jha,this.Ol=this.Tga,this.Ld=this.Via)},Zfa:function(){4===this.i.Oa.type&&(this.cZ(),this.Pl=this.iha,this.Ol=this.Sga,this.Ld=this.ZK)},cZ:function(){this.i.html.JE&&(this.i.html.Cu||
(this.i.html.Cu=this.ua.find(" \x3e ul"),this.i.html.qE=f("\x3cdiv id\x3d'oj-tree-existing-markup-"+this.Ug()+"' style\x3d'display:none'\x3e").append(this.i.html.Cu),this.ua.after(this.i.html.qE)),this.i.html.R3=this.i.html.Cu.find(" \x3e li"),this.i.html.GD=this.i.html.R3.clone(!0),this.i.html.GD.find("li").addBack().contents().filter(function(){return 3==this.nodeType}).remove())},cga:function(){!1===this.i.Ab.Px&&f("script").each(function(){if(this.src.toString().match(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/))return this.i.Ab.Px=
this.src.toString().replace(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/,"")+"themes/",!1});!1===this.i.Ab.Px&&(this.i.Ab.Px="themes/");this.ua.bind("_treeinit",f.proxy(function(){var a=this.options;this.i.Ab.iy=a.dots;this.i.Ab.icons=a.icons;this.setTheme(this.i.Ab.Mu,this.i.Ab.url)},this)).bind("ojloaded",f.proxy(function(){this.i.Ab.iy?this.V_():this.kX();this.i.Ab.icons?this.FL():this.TJ()},this))},gga:function(){var a=this.options.types;a&&this.ua.bind("_treeinit",f.proxy(function(){var b=f.extend(!0,
{},a.types),c=a.attr||this.i.types.Cc.attr,d="",e=this;f.each(b,function(a,b){f.each(b,function(a){/^(maxDepth|maxChildren|icon|validChildren)$/.test(a)||e.i.types.j1.push(a)});var g=typeof b.icon;if("undefined"===g){g=typeof b.image;if("boolean"===g&&!b.image)b.image="ojt$none";else if(!b.image&&!b.position)return!0;b.icon={};b.image&&(b.icon.image=b.image,delete b.image);void 0!==b.position&&(b.icon.position=b.position,delete b.position)}if(b.icon.image||b.icon.position)"default"==a?(e.i.types.nu=
!0,d+=".oj-tree-"+e.Ug()+" .oj-tree-list li.oj-tree-type a \x3e .oj-tree-node-icon { ",d+=e.DS(b,d),d+="} ",d+=".oj-tree-"+e.Ug()+" .oj-tree-list li["+c+'\x3d"oj-tree-deftype"].oj-tree-type \x3e a ins.oj-tree-node-icon { '):b.icon.image&&(d+=".oj-tree-"+e.Ug()+" .oj-tree-list li["+c+'\x3d"'+a+'"].oj-tree-type \x3e a \x3e ins.oj-tree-node-icon { '),d+=e.DS(b,d),d+="} "});""!==d&&h({IE:d,title:"oj-tree-types"})},this)).bind("ojbefore",f.proxy(function(a,b){var c,d,e=b.func,g=b.item;if((c=(c=this.i.types.Cc.useData?
this.sa(g):!1)&&-1!==c&&c.length?c.data("oj-tree"):!1)&&c.types&&!1===c[e]||-1!==f.inArray(e,this.i.types.j1)&&b.item&&(b.item.tagName||b.item.jquery)&&(c=this.options.types.types,d=this.uJ(g),(c[d]&&"undefined"!==typeof c[d][e]||c["default"]&&"undefined"!==typeof c["default"][e])&&!1===this.M$(e,g)))return a.stopImmediatePropagation(),!1},this))},DS:function(a){var b="",b="ojt$none"!==a.icon.image?b+(" background-image:url("+a.icon.image+"); "):b+" background-image:none; ";return b=a.icon.position?
b+(" background-position:"+a.icon.position+"; "):b+" background-position:0 0; "},Fn:function(){this.Gv||(this.Gv=new b.fa(this));return this.Gv},Xqa:function(){},On:function(a){var b,c;a||this.options.contextMenu||(b=this.ua.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;c=f.type(b);if("function"==c){try{b=b()}catch(d){b=null}c=f.type(b)}if("string"===c){if(b=f(b))b.css("display","none"),c=this.i.menu,c.Ge=b,c.rh=!0;this.i.menu.rh&&
a&&this.Ov()}}},lj:function(a,b){if(!b.inst&&this.i.menu.Vpa==this.Ps.substr(1)){var c=b?b.item.attr("id"):void 0;"ojtreecopy"===c?this.gba(this.i.menu.Kj):"ojtreecut"===c?this.iba(this.i.menu.Kj):"ojtreepaste"===c?this.jba(this.i.menu.Kj):"ojtreeremove"===c?this.isSelected(this.i.menu.Kj)?this.gU():this.gU(this.i.menu.Kj):"ojtreerename"===c?this.hU(this.i.menu.Kj):"ojtreecreate"===c&&this.hba(this.i.menu.Kj)}},lf:function(b,c,d){var e="keyboard"===d;if("contextmenu"==c.type||e||"touch"==d){this.i.menu.Kj=
e?this.i.ui.Db:f(c.target);var g=this.i.menu.Kj.find(".oj-tree-title")[0];this.i.menu.CD=null;this.i.menu.Kj?(this.i.menu.Vpa=this.i.menu.Kj.closest("div").attr("id"),b={launcher:this.aa},e&&(b.position={of:g}),this.i.menu.rh&&this.i.menu.Nu&&(e=!this.i.Bc.Di&&!this.i.Bc.Wq,!!this.i.menu.Nu.hasClass(a.ad)!=e&&(e?this.i.menu.Nu.addClass(a.ad):this.i.menu.Nu.removeClass(a.ad),this.i.menu.Ge.ojMenu("refresh"))),this.nf(c,d,b)):c.preventDefault()}},Vfa:function(){var a=this.options.selectionMode,a=void 0==
a?"single":a;"none"===a?a=0:"single"===a?a=1:"multiple"===a&&(a=-1);this.i.Z.Dm=a;this.i.Ab.icons=this.options.icons;this.yX();this.i.Z.bl=this.options.initLoaded},$qa:function(){},wX:function(a){var c=this.options.data,d;this.i.Oa.type=0;this.i.html.JE=!1;this.i.html.GD=!1;if(c)if(d=f.type(c),"string"===d)this.Dga(c)?this.i.Oa.type=4:this.i.Oa.type=3;else if("array"===d)this.i.Oa.type=3;else if("object"===d){try{c instanceof b.fc&&(this.i.Oa.type=1)}catch(e){this.i.Oa.type=-1}if(1!==this.i.Oa.type)try{c instanceof
b.Ia&&(this.i.Oa.type=2)}catch(g){this.i.Oa.type=-1}1!==this.i.Oa.type&&2!==this.i.Oa.type&&(c.data||c.ajax)&&((d=c.dataType)?"json"===d?this.i.Oa.type=3:"html"===d&&(this.i.Oa.type=4):(c.dataType="json",this.i.Oa.type=3))}a&&0==this.i.Oa.type&&0<this.ua.find("ul").length&&(this.i.Oa.type=4,this.i.html.JE=!0)},Zqa:function(){},Wqa:function(){},Vqa:function(){},Yqa:function(){},fga:function(){var a=this.options.types;"object"===typeof a&&this.Y9(a,{attr:this.i.types.Cc.attr})},yX:function(){this.i.Z.Cg=
this.ama(this.options,"initExpanded");null==this.i.Z.Cg&&(this.i.Z.Cg=[])},Wfa:function(){var a=this.i;a.Z={soa:[],Dm:1,Dra:!1,Jo:0,Cg:!1,bl:!1,Ag:{},Br:!1,Gpa:{}};a.ui={selected:f(),Lb:!1,Db:null,Hj:null,WM:!1,bz:null,opacity:1,PO:!1,Dj:!1,c1:null,Cr:!1};a.ui.Cc={selectMultipleModifier:"ctrl",selectRangeModifier:"shift",disableSelectingChildren:!1};a.Bc={};a.Bc.Wq=!1;a.Bc.Di=!1;a.Bc.Cc={inputWidthLimit:200,move:{alwaysCopy:!1,openOnMove:!0,defaultPosition:"last",checkMove:function(){return!0}}};
a.Bc.Ag={};a.Oa={};a.Oa.zO=!1;a.Oa.Iu=!1;a.Oa.lg=!0;a.Oa.type=0;a.Foa={};a.Foa.Cc={data:!1,ajax:!1};a.html={};a.html.Cc={data:!1,ajax:!1};a.html.JE=!1;a.html.Cu=!1;a.html.qE=!1;a.html.R3=!1;a.html.GD=!1;a.Ab={};a.Ab.icons=!0;a.Ab.iy=!1;a.Ab.Mu="default";a.Ab.url=!1;a.Ab.c5=[];a.Ab.Px=!1;a.types={};a.types.j1=[];a.types.nu=!1;a.types.Cc={maxChildren:-1,maxDepth:-1,validChildren:"all",useData:!1,attr:"type",types:{"default":{maxChildren:-1,maxDepth:-1,validChildren:"all"}}};a.menu={};a.menu.rh=!1;a.menu.Ge=
!1;a.menu.Nu=!1;a.menu.Kj=!1;a.menu.CD=!1;a.keys={};a.keys.pna=!0;a.keys.bound=[]},jV:function(a){var b=this.ua[0];b.scrollHeight>b.offsetHeight&&(a=this.sa(a))&&-1!==a&&a.length&&a.is(":visible")&&(a=a.offset().top-this.ua.offset().top,0>a&&(b.scrollTop=b.scrollTop+a-1),a+this.i.Z.Jo+(b.scrollWidth>b.offsetWidth?m:0)>b.offsetHeight&&(b.scrollTop+=a-b.offsetHeight+this.i.Z.Jo+1+(b.scrollWidth>b.offsetWidth?m:0)))},eo:function(){},kra:function(){},Lha:function(){return++s},Ug:function(){return this.Pfa},
hq:function(){return f.extend(!0,{},this.options)},Jqa:function(){return this.ua},Kqa:function(){return this.aa},zt:{up:function(){this.hover(this.Jl(this.i.ui.Db||this.i.ui.Lb||-1));return!1},"ctrl+up":function(){this.hover(this.Jl(this.i.ui.Db||this.i.ui.Lb||-1));return!1},"shift+up":function(){this.select(this.Jl(this.i.ui.Db||this.i.ui.Lb||-1),-1!==this.i.ui.Dm);return!1},down:function(){this.hover(this.gq(this.i.ui.Db||this.i.ui.Lb||-1));return!1},"ctrl+down":function(){this.hover(this.gq(this.i.ui.Db||
this.i.ui.Lb||-1));return!1},"shift+down":function(){this.select(this.gq(this.i.ui.Db||this.i.ui.Lb||-1),-1!==this.i.ui.Dm);return!1},left:function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&(b.hasClass(a.ji)?this.collapse(b):this.hover(this.Jl(b)));return!1},"ctrl+left":function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&(b.hasClass(a.ji)?this.collapse(b):this.hover(this.Jl(b)));return!1},"shift+left":function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&(b.hasClass(a.ji)?this.collapse(b):this.hover(this.Jl(b)));
return!1},right:function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&b.length&&(b.hasClass(a.mf)?this.expand(b):this.hover(this.gq(b)));return!1},"ctrl+right":function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&b.length&&(b.hasClass(a.mf)?this.expand(b):this.hover(this.gq(b)));return!1},"shift+right":function(){var b=this.i.ui.Db||this.i.ui.Lb;b&&b.length&&(b.hasClass(a.mf)?this.expand(b):this.hover(this.gq(b)));return!1},space:function(){this.i.ui.Db&&(this.i.ui.PO=!0,this.i.ui.Db.children("a:eq(0)").click(),
this.i.ui.PO=!1);return!1},home:function(){this.hover(this.aa.find("li:first"));return!1},end:function(){var a=this.aa.find("li.oj-tree-last:visible");a&&a.length&&this.hover(a[a.length-1]);return!1},"*":function(){this.aa.find("a");this.lI(-1,!1);return!1},"ctrl+space":function(){if(this.i.ui.Db){var a=f.Event("click");a.ctrlKey=!0;this.i.ui.Db.children("a:eq(0)").trigger(a)}return!1},"shift+space":function(){if(this.i.ui.Db){var a=f.Event("click");a.shiftKey=!0;this.i.ui.Db.children("a:eq(0)").trigger(a)}return!1},
"shift+home":function(a){var b,c=this.i.ui.Db;if(c){var d=!0,e=this,g=this.aa.find("li:visible");this.i.Z.Br=!0;b=this.options.selection.slice(0);c=c[0];f.each(g,function(a,b){b==c&&(d=!1);e.vj(b,!0);return d});this.i.Z.Br=!1;this.pw("selection",b,null,a)}return!1},"shift+pgdn":function(a){var b,c=this.i.ui.Lb||this.i.ui.Db;if(c){var d=!1,e=this,g=this.aa.find("li:visible");this.i.Z.Br=!0;b=this.options.selection.slice(0);c=c[0];f.each(g,function(a,b){d||(d=b==c);d&&!e.isSelected(b)&&e.vj(b,!0);return!0});
this.i.Z.Br=!1;this.pw("selection",b,null,a)}return!1},f2:function(){this.hU(this.i.ui.Db||this.i.ui.Lb);return!1},del:function(){this.remove(this.i.ui.Db||this.sa(null));return!1}},Ov:function(){if(this.i.menu.rh){var a=this.i.menu.Ge,b=this;a.on("ojselect",f.proxy(this.lj,this));var c=!1;a.find("[data-oj-command]").each(function(){var a;0===f(this).children("a").length&&(a=f(this).attr("data-oj-command").split("oj-tree-"),f(this).replaceWith(b.ni(a[a.length-1])),f(this).hasClass("oj-menu-divider")&&
f(this).removeClass("oj-menu-divider").addClass("oj-menu-item"),c=!0)});c&&a.ojMenu("refresh");this.i.menu.Nu=a.find("#ojtreepaste")}},Op:function(){var a=this.i.menu;a.rh&&(a.rh=!1,a.Ge.off("ojselect"),a.Ge=null)},ni:function(a){return f(this.cg(a))},cg:function(a){return"\x3cli id\x3d"+k[a]+"\x3e"+this.YG(a)+"\x3c/li\x3e"},YG:function(a){return'\x3ca href\x3d"#"\x3e'+this.lJ(l[a])+"\x3c/a\x3e"},iba:function(a){a=this.sa(a,!0);if(!a||!a.length)return!1;this.i.Bc.Wq=!1;this.i.Bc.Di=a;this.ub({obj:a},
"cut")},gba:function(a){a=this.sa(a,!0);if(!a||!a.length)return!1;this.i.Bc.Di=!1;this.i.Bc.Wq=a;this.ub({obj:a},"copy")},jba:function(a){a=this.sa(a);if(!a||!a.length)return!1;var b=this.i.Bc.Di?this.i.Bc.Di:this.i.Bc.Wq;if(!this.i.Bc.Di&&!this.i.Bc.Wq)return!1;this.i.Bc.Di&&(this.PH(this.i.Bc.Di,a),this.i.Bc.Di=!1);this.i.Bc.Di&&(this.PH(this.i.Bc.Di,a),this.i.Bc.Di=!1);this.i.Bc.Wq&&this.PH(this.i.Bc.Wq,a,!1,!0);this.ub({obj:a,nodes:b},"paste")},PH:function(a,b,c,d,e,f){var g=this.i.Bc.Cc.move;
if(!e)return"undefined"===typeof c&&(c=g.defaultPosition),"inside"!==c||g.defaultPosition.match(/^(before|after)$/)||(c=g.defaultPosition),this.hx(a,b,c,d,!1,f);if(!0===g.alwaysCopy||"multitree"===g.alwaysCopy&&a.Uo.Ug()!==a.$k.Ug())d=!0;this.hx(a,b,c,d,!0,f)},gU:function(a){a=this.sa(a,!0);this.Ip();this.remove(a)},hU:function(a){a=this.sa(a);this.Ip();this.iU(a,function(){})},iU:function(a,b){a=this.sa(a);var c=this.lC,d=this.i.Bc.Cc.inputWidthLimit,e=a.children("ins").width(),g=a.find("\x3e a:visible \x3e ins").width()*
a.find("\x3e a:visible \x3e ins").length,h=this.getText(a),k=this,l=f("\x3cdiv /\x3e",{css:{position:"absolute",top:"-200px",left:c?"0px":"-1000px",visibility:"hidden"}}).appendTo("body"),m=a.css("position","relative").append(f("\x3cinput /\x3e",{value:h,"class":"oj-tree-rename-input",css:{padding:"0",border:"1px solid silver",position:"absolute",left:c?"auto":e+g+4+"px",right:c?e+g+4+"px":"auto",top:"0px",height:this.i.Z.Jo-2+"px",lineHeight:this.i.Z.Jo-2+"px",width:"150px"},blur:f.proxy(function(){var c=
a.children(".oj-tree-rename-input"),d=c.val();""===d&&(d=h);l.remove();c.remove();this.BL(a,h);this.TZ(a,d);b.call(this,a,d,h);a.css("position","")},this),keyup:function(a){a=a.keyCode||a.which;if(!k.dI)return k.dI=!0,!1;27==a?(k.dI=!1,this.value=h,this.blur()):13==a?(k.dI=!1,this.blur()):m.width(Math.min(l.text("pW"+this.value).width(),d))},keypress:function(a){if(13==(a.keyCode||a.which))return!1}})).children(".oj-tree-rename-input");this.BL(a,"");l.css({fontFamily:m.css("fontFamily")||"",fontSize:m.css("fontSize")||
"",fontWeight:m.css("fontWeight")||"",fontStyle:m.css("fontStyle")||"",fontStretch:m.css("fontStretch")||"",fontVariant:m.css("fontVariant")||"",letterSpacing:m.css("letterSpacing")||"",wordSpacing:m.css("wordSpacing")||""});m.width(Math.min(l.text("pW"+m[0].value).width(),d))[0].select()},hba:function(b,c,d,e,g){var h=this;(b=this.sa(b))||(b=-1);this.Ip();return this.ew(b,c,d,function(b){var c=this.kj(b),d=f(b).index();e&&e.call(this,b);c.length&&c.hasClass(a.mf)&&this.expand(c,!1,!0);g?h.ub({obj:b,
name:this.getText(b),parent:c,position:d}):this.iU(b,function(a,b){h.ub({obj:a,name:b,parent:c,position:d})})})},Dga:function(a){var b=!1;a&&3<=a.length&&(a=a.trim(),b="\x3c"===a.charAt(0));return b},Z9:function(){var a=this.options.emptyText;"string"!==typeof a&&(a=this.lJ("labelNoData"));if(a&&0<a.length){var b=this.aa,c=f("\x3cli class\x3d'oj-tree-empty'\x3e\x3c/li\x3e");c[0].textContent=a;b.empty().append(c)}},zia:function(a){var b,c,d;d=null;var e;a&&(b=a.subId);if(!b)return null;d=b.split("[");
if(3===d.length&&(d[0]=d[0].trim(),"oj-tree-node"===d[0]&&(d[1]=d[1].trim(),b=d[1].charAt(0),b=d[1].indexOf(b,1),0<=b&&(a=d[1].substring(1,b).trim(),d[2]=d[2].trim(),b=d[2].charAt(0),b=d[2].indexOf(b,1),0<=b)))){d=d[2].substring(1,b).trim();try{c=this.sa(a)}catch(f){c=null}if(d&&c&&-1!==c)switch(d){case "icon":this.i.Ab.icons&&(e=c.find(" \x3e a \x3e ins:eq(0)"));break;case "link":e=c.find(" \x3e a:eq(0)");break;case "disclosure":this.hK(c)||(e=c.find(" \x3e ins:eq(0)"));break;case "title":e=c.find(" \x3e a \x3e span")}}return e?
e.length?e[0]:null:null},Zda:function(a){var b=a?this.sa(a):null,c,d=null;b&&-1!=b&&b.length&&b.hasClass("oj-tree-node")&&a.tagName&&a.parentNode&&(b=a.tagName,c=a.parentNode,c=c.tagName,"SPAN"===b?d="title":"A"===b?d="link":"INS"===b&&(a=f(a),"LI"===c&&a.hasClass("oj-tree-disclosure-icon")?d="disclosure":"A"===c&&a.hasClass("oj-tree-node-icon")&&(d="icon")));return d},kX:function(){this.i.Ab.iy=!1;this.ua.children("ul").addClass("oj-tree-no-dots")},V_:function(){this.i.Ab.iy=!0;this.ua.children("ul").removeClass("oj-tree-no-dots")},
Jga:function(){var a=this.options.initExpanded;return a&&"all"==a||f.isArray(a)&&a.length&&"all"==a[0]},lJ:function(a){var b=this.i.Z.Gpa,c;c=b[a];c||(c=this.A(a),c=this.aB(c),b[a]=c);return c},aB:function(a){var b=document.createElement("div");f(b).text(a);return b.textContent},Pqa:function(){return this.i.Z.Jo},zca:function(){var a=0,b,c;window.getComputedStyle&&(c=this.i.ui.c1,c||(c=f("\x3cdiv id\x3d'ojtree-comp-animduration'\x3e\x3cspan class\x3d'oj-tree-transition'\x3edummy\x3c/span\x3e\x3c/div\x3e"),
this.i.ui.c1=c,f("body").append(c)),b=c[0].childNodes[0],b=window.getComputedStyle(b),b=b.transitionDuration?b.transitionDuration:b["-webkit-transition-duration"]?b["-webkit-transition-duration"]:0,c.detach(),"string"==typeof b&&1<b.length&&(c=b.charAt(b.length-1).toLowerCase(),"s"==c?(b=b.substring(0,b.length-1),b=parseFloat(b),isNaN(b)||(a=1E3*b)):2<b.length&&(c=b.substring(b.length-2).toLowerCase(),"ms"==c&&(b=parseFloat(b),isNaN(b)||(a=b)))));return a},ama:function(a,b){var c={};c[b]=a[b];return f.extend(!0,
{},c)[b]},I0:function(a){this.ub({obj:{msg:a}},"trace",!0)}})})()});