/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,f){(function(){b.ya("oj.ojTrain",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selected:"",optionChange:null,beforeDeselect:null,deselect:null,beforeSelect:null,select:null},Ue:0,wb:null,_ComponentCreate:function(){this._super();this.T_()},T_:function(){var a=this.options,b=a.steps;this.Ue=b.length;this.cu=f("\x3cdiv class\x3d'oj-train-wrapper'\x3e\x3c/div\x3e");this.cu.appendTo(this.element);
this.IA=f("\x3cdiv class\x3d'oj-train-connector-wrapper'\x3e\x3c/div\x3e");this.IA.appendTo(this.cu);var c=this.element.attr("class");(this.m0=null!=c&&0<=c.indexOf("oj-train-stretch"))&&this.IA.css("padding","0 "+100/(2*this.Ue)+"%");this.MT=f("\x3cdiv class\x3d'oj-train-connector'\x3e\x3c/div\x3e");this.MT.appendTo(this.IA);this.Te=f("\x3cul\x3e");this.Te.addClass("oj-train-step-list");this.BH=f("\x3cdiv class\x3d'oj-train-connector-fill'\x3e\x3c/div\x3e");this.BH.appendTo(this.IA);this.Lka();this.wj=
this.kt(a.selected);-1===this.wj&&b[0]&&b[0].id&&(this.wj=0,a.selected=b[0].id);for(a=0;a<this.Ue;a++)b=f("\x3cli\x3e").addClass("oj-train-step-list-item").attr({id:this.wb[a][1]}),b.appendTo(this.Te),this.Pba(a),this.Sba(a),this.Oba(a),this.Qba(a),this.m0&&b.css("width",100/this.Ue+"%");this.BH.css({width:(this.Ue-1===this.wj?100:100/(2*(this.Ue-1))+this.wj/(this.Ue-1)*100)+"%"});this.Te.appendTo(this.cu);this.element.addClass("oj-train")},Lka:function(){var a=this.options;this.wb=[];for(var b=0;b<
this.Ue;b++){var c=a.steps[b];this.wb[b]=Array(5);this.wb[b][0]=c.label?c.label:null;this.wb[b][1]=c.id?c.id:null;this.wb[b][2]=c.disabled?!0:!1;this.wb[b][3]=c.visited?!0:!1;this.wb[b][4]=c.messageType?c.messageType:null}},Oba:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-button"),c=f("\x3cspan/\x3e"),e=this,g="";if(this.wb[a]){var h=this.wb[a][3],k=this.wb[a][2];this.wj===a?(b.addClass("oj-selected"),g=" current "):h&&!k?(b.addClass("oj-visited"),g=" visited "):h||k?b.addClass("oj-disabled"):
(b.addClass("oj-default"),g=" not visited ");this.wb[a][2]||this.wj===a||(this._hoverable(b),b.on("click"+this.eventNamespace,function(a){e.hB("selected",e.options.selected,this.parentNode.parentNode.id,a);e.refresh()}));h=this.Te.children().eq(a).find(".oj-train-button-connector");1<=h.length&&h.children().remove();h.append(b);c.text(g);c.addClass("oj-helper-hidden-accessible");this.Te.children().eq(a).find("a").append(c)}},Qba:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-icon"),c=f("\x3cspan/\x3e"),
e="",g=this;if(this.wb[a]){var h=this.wb[a][4];"confirmation"===h?(b.addClass("oj-confirmation"),e=" Confirmation "):"info"===h?(b.addClass("oj-info"),e=" Info "):"error"===h?(b.addClass("oj-error"),e=" Error "):"fatal"===h?(b.addClass("oj-error"),e=" Error "):"warning"===h&&(b.addClass("oj-warning"),e=" Warning ");var k=this.Te.children().eq(a).find(".oj-train-button");1<=k.children().length&&k.children().remove();this.wb[a][2]||this.wj===a||(this._hoverable(b),b.on("click"+this.eventNamespace,function(a){g.hB("selected",
g.options.selected,this.parentNode.parentNode.parentNode.id,a);g.refresh()}));null!=h&&(c.text(e),c.addClass("oj-helper-hidden-accessible"),this.Te.children().eq(a).find("a").append(c),k.append(b))}},hB:function(a,b,c,e){a={option:a,fromStep:this.getStep(b),toStep:this.getStep(c),optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};!1!==this._trigger("beforeDeselect",e,a)&&!1!==this._trigger("beforeSelect",e,a)&&(b=this.kt(b),-1!==b&&(this.options.steps[b].visited=!0),this._trigger("deselect",
e,a),this.option("selected",c,{_context:{originalEvent:e,Za:!0}}),this._trigger("select",e,a))},Sba:function(a){var b=f("\x3cdiv/\x3e");b.addClass("oj-train-button-connector");this.wb[a]&&(a<=this.wj&&b.addClass("oj-train-fill"),a=this.Te.children().eq(a).children(),b.insertBefore(a))},Pba:function(a){var b=this;if(this.wb[a]){var c=f("\x3cdiv/\x3e").addClass("oj-train-label-wrapper"),e=f("\x3ca\x3e");e.text(this.wb[a][0]);var g=this.wb[a][2];c.append(e);e.addClass("oj-train-label");a===this.wj?e.addClass("oj-selected"):
this.wb[a][3]&&!g?e.addClass("oj-visited"):g&&e.addClass("oj-disabled");g||(e.attr("href","#"),this._hoverable(e),e.on("click keydown"+this.eventNamespace,function(a){if(a.keyCode===f.ui.keyCode.ENTER||"click"===a.type)a.preventDefault(),b.hB("selected",b.options.selected,this.parentNode.parentNode.id,a),b.refresh(),a.keyCode===f.ui.keyCode.ENTER&&b.eo(this.parentNode.parentNode.id)}));e=this.Te.children().eq(a).children();1<=e.length&&e[0].remove();this.Te.children().eq(a).append(c)}},kt:function(a){for(var b=
0;b<this.Ue;b++)if(this.wb[b]&&this.wb[b][1]===a)return b;return-1},getStep:function(a){for(var b=0;b<this.Ue;b++)if(this.wb[b]&&this.wb[b][1]===a)return jQuery.extend({},this.options.steps[b]);return null},nextSelectableStep:function(){for(var a=this.kt(this.options.selected);a<this.Ue;a++)if(a+1<this.Ue&&this.wb[a+1]&&!this.wb[a+1][2])return this.wb[a+1][1];return null},previousSelectableStep:function(){for(var a=this.kt(this.options.selected);0<=a;a--)if(this.wb[a-1]&&!this.wb[a-1][2])return this.wb[a-
1][1];return null},setStep:function(a){if(a.id){var b=this.getStep(a.id),c=this.kt(a.id);-1!==c&&(c=this.options.steps[c],a.label&&(b[0]=a.label,c.label=a.label),"boolean"===typeof a.disabled&&(b[2]=a.disabled,c.disabled=a.disabled),"boolean"===typeof a.visited&&(b[3]=a.visited,c.visited=a.visited),a.messageType&&(b[4]=a.messageType,c.messageType=a.messageType));this.refresh()}},_setOptions:function(a){this._super(a);this.refresh()},_setOption:function(a,b,c){"selected"===a&&this.options.selected&&
this.wb&&this.wb[this.wj]&&this.hB("selected",this.wb[this.wj][1],b,null);this._super(a,b,c)},refresh:function(){this._super();this._destroy();this.T_()},_destroy:function(){this.Te.children().each(function(){f(this).remove()});this.element.removeClass("oj-train");this.element.find(".oj-train-wrapper").remove();this.element.find(".oj-train-connector-wrapper").remove();this.element.find(".oj-train-step-list").remove();this.element.find(".oj-train-step-list").remove();this._super()},eo:function(a){a=
this.kt(a);for(var b=0;b<this.Ue;b++)if(this.wb[(a+b+1)%this.Ue]&&!this.wb[(a+b+1)%this.Ue][2]){this.Te.children().eq((a+b+1)%this.Ue).find(".oj-train-label").focus();break}},getNodeBySubId:function(a){if(null===a)return this.element?this.element[0]:null;var b=a.index;if("number"!==typeof b||0>b||b>=this.Ue)return null;switch(a.subId){case "oj-train-step":return this.Te.children().eq(b)[0];case "oj-train-button":return this.Te.children().eq(b).find(".oj-train-button")[0];case "oj-train-button-connector":return this.Te.children().eq(b).find(".oj-train-button-connector")[0];
case "oj-train-connector":return this.MT;case "oj-train-connector-fill":return this.BH;case "oj-train-icon":return this.Te.children().eq(b).find(".oj-train-icon")[0];case "oj-train-label":return this.Te.children().eq(b).find(".oj-train-label")[0]}return null},getSubIdByNode:function(a){for(var b=this.wb?this.wb.length:0,c=0;c<b;c++){var e={subId:"oj-train-step",index:c};if(a===this.getNodeBySubId(e))return e}return null}})})()});